### ISSUE TITLE
WSL_HOST_IP not exported on WSL2 session

### ISSUE THREAD

**Issue by mscha** [mintty/mintty#1006]
With WSL version 2, WSL runs in a virtual machine and has a separate IP address.
This means that `export DISPLAY=:0`, with an X server running on the host, doesn't work.

According to the [wslbridge2 FAQ](https://github.com/Biswa96/wslbridge2/blob/master/FAQ.md), you can export the host's IP address in an environment variable `WSL_HOST_IP` by calling `wslbridge2.exe -e WSL_HOST_IP`.  But I can't find a way to get mintty to do this.

Can you add a way to do this, or if it already exists, document it?

**Comment by mintty** [comment]
@Biswa96. does this mean that WSL_HOST_IP is some standard thing used within WSL?
So should mintty determine the host ip and set that variable?
But then wouldn't the native WSL invocation also set this variable? Or is it used only for V2?

**Comment by Biswa96** [comment]
> Does this mean that WSL_HOST_IP is some standard thing used within WSL?

That WSL_HOST_IP thing is not a standard. In WSL2, the IP address in Linux VM is not static i.e. DHCP. So, for my bizarre experiments I thought those type of variables will be useful.

> So should mintty determine the host ip and set that variable?

I think mintty has nothing to do with the IP address. One possible solution would be to add the parameters `-e WSL_HOST_IP` in wsltty shortcuts.

> But then wouldn't the native WSL invocation also set this variable?

As said, those variables are created by me for experiments. In future, the network stack may change in WSL2. So, the variables are not permanent.

> Or is it used only for V2?

Yes, it is only for WSL2. In WSL1, both side has same IP address.

**Comment by mintty** [comment]
> add the parameters -e WSL_HOST_IP in wsltty shortcuts.

That makes sense only if the variable is set before invoking the shortcut, i.e. on Windows level, like in your experiments. I don't see it useful as a generic option, unless it is ensured that this variable will be set. In fact, I see a `setenv("WSL_HOST_IP", ...)` in the wslbridge2 code, under some conditions. I cannot test WSL V2 right now, but would wslbridge2 set it then? In that case, however, the `-e` option is not needed, right? Confused.

**Comment by mintty** [comment]
Taking @Biswa96's comment
> I think mintty has nothing to do with the IP address.

Also this appears to be an experimental setting.
You may ask @Biswa96 to set up the info regularly when running WSL V2.

**Comment by Biswa96** [comment]
Try this:

1. Go to https://ci.appveyor.com/project/Biswa96/wslbridge2 > click on Image: Visual Studio 2019 > click on Artifacts > Download the wslbridge2.7z file > extract it with 7zip > copy the wslbridge2.exe to C:\Users\YourUserName\AppData\Local\wsltty\bin, make sure to rename the original one to something.
2. Set `WSLENV` variable to `WSL_HOST_IP` in control panel advanced system settings. No reboot is required.

You're good to go. The first step is temporary for now. It can be added in next release. The second step is necessary, see WSL docs.

**Comment by mintty** [comment]
Still confused. If wslbridge2 sets WSL_HOST_IP and that is propagated as advised via WSLENV, couldn't wslbridge2 also set (or extend) WSLENV? It's troublesome to tell users they need to set that variable manually in some very deeply hidden corner of system configuration in order to get certain functionality...

**Comment by Biswa96** [comment]
In my opinion, settings `WSLENV` explicitly may not be correct choice. Here are my reasons.

1. `WSLENV` may be used already for other reason then program has to fetch it first and append it with `WSL_HOST_IP`.
2. `WSL_HOST_IP` may not be the only used by wslbridge2, VSCode, many custom WSL2 X server may use it internally. That may conflict with wslbridge2.
3. Adding an environment variable is typical Windows settings. Also it gives a choice to user either he/she want to add or not.

**Comment by Biswa96** [comment]
In my opinion, settings `WSLENV` explicitly may not be correct choice. Here are my reasons.

1. `WSLENV` may be used already for other reason then program has to fetch it first and append it with `WSL_HOST_IP`.
2. `WSL_HOST_IP` may not be the only used by wslbridge2, VSCode, many custom WSL2 X server may use it internally. That may conflict with wslbridge2.
3. Adding an environment variable is typical Windows settings. Also it gives a choice to user either he/she want to add or not. 

Open to suggestions...

**Comment by Biswa96** [comment]
In my opinion, settings `WSLENV` explicitly may not be correct choice. Here are my reasons.

1. `WSLENV` may be used already for other reason then program has to fetch it first and append it with `WSL_HOST_IP`.
2. `WSL_HOST_IP` may not be the only used by wslbridge2, VSCode, Windows X server may use it internally. That may conflict with wslbridge2.
3. Adding an environment variable is typical Windows settings. Also it gives a choice to user either he/she want to add or not. 

Open to suggestions...

**Comment by mintty** [comment]
> 1. WSLENV may be used already for other reason then program has to fetch it first and append it with WSL_HOST_IP.

Yes, as I suggested "set (or extend) WSLENV". In fact, wslbridge2 should also check whether WSL_HOST_IP is set already and not overwrite it then, as the user could have set up a different host to be used for X or whatever. (This would be the 3rd parameter false of setenv but apparently setenv is not effective towards WSL...)

> 2. WSL_HOST_IP may not be the only used by wslbridge2, VSCode, Windows X server may use it internally. That may conflict with wslbridge2.

The value would likely be the same, however. Anyway, setting WSLENV in wslbridge2 would only affect the current session, and help it to make the WSL_HOST_IP thing work.

> 3. Adding an environment variable is typical Windows settings. Also it gives a choice to user either he/she want to add or not.

It should be. But MS made it more obscure to find this setting more than once, with major Windows versions, so I don't want to have to explain our users how to do it.

**Comment by Biswa96** [comment]
This is fixed in [wsltty version 3.4.1](https://github.com/mintty/wsltty/releases/tag/3.4.1).

**Comment by Biswa96** [comment]
This is fixed in [wsltty version 3.4.1](https://github.com/mintty/wsltty/releases/tag/3.4.1). The WSL_HOST_IP is generated from routing table of eth0 virtual network interface in WSL2.

**Comment by mintty** [comment]
Released 3.4.1.
