### ISSUE TITLE
Slow scrolling with Less

### ISSUE THREAD

**Issue by nu8** [mintty/mintty#1007]
I recently upgraded from 3.0.0, to 3.1.6

I noticed now when scrolling, for example with `git diff`, that the scroll is painfully slow, like some big calculation is being done after each press of down arrow.

**Comment by nu8** [comment]
as a workaround, I switched to ConEmu:

https://github.com/Maximus5/ConEmu

**Comment by mintty** [comment]
Cannot reproduce. What if you run mintty with empty config?

**Comment by nu8** [comment]
I am just running Mintty from a stock MSYS2 install. I dont know where any config is.

**Comment by mintty** [comment]
I see no issue with less in mintty 3.1.6 on MSYS2. Can you isolate the issue and try plain less please?
If it happens only with git diff, redirect git diff > log and less log. If it happens then, upload the log here.

**Comment by nu8** [comment]
Happens with just Less as well - attached

[a.txt](https://github.com/mintty/mintty/files/4713810/a.txt)

**Comment by mintty** [comment]
I can check this on Windows 7 tomorrow. And don't start nagging about your assumptions again, or I'd need to measure them by your lousy bug reports (no mention of Windows 7 or MSYS2 originally).
Sure I test the feature claims occasionally but there is no full test suite on every release as you might expect from industrial projects and don't even get there.

**Comment by nu8** [comment]
The point is, it is not responsible to conspicuously claim support for a 20 year old operating system, when you arent even test it.

It would be better to just say "only Windows 10 is supported. It might work with older versions, but no testing is done".

That would more accurately reflect the state of things, and not mislead people like is currently happening.

**Comment by mintty** [comment]
I do not say every release is tested on those systems, but in fact fairly recent versions do run on them.

**Comment by avih** [comment]
While this could be a mintty issue, it's not likely to. It's more likely IMO to be a cygwin/MSYS2 issue. If you want to ensure it's a mintty issue, then you should switch back and forth the mintty version and confirm it only happens with one of them.

If you don't have access to older mintty versions then you can build it yourself in MSYS2 - it's quite easy to build any version you want after you clone this repo.

**Comment by mintty** [comment]
Actually there is a remaining uncertainty with this approach because MSYS2 applies patches to mintty.
There had already been ~2 issues that were related to them.
On the other hand, it's also a valuable test case to verify an issue with unmodified mintty.

**Comment by nu8** [comment]
I'm not going to build 5 or whatever different version just to do the testing that should have been done before release. Even a casual test with windows 7 before release would've easily revealed this problem.

It's now clear no regular testing outside of windows 10. Now that I know that fact, I can make other arrangements.

**Comment by mintty** [comment]
You're starting it again although I asked you not to. Instead of cooperating on testing you're molesting an open source project with inappropriate expectations. If you want all system configurations to be regularly tested before every release, are you willing to pay for it?

**Comment by nu8** [comment]
Its quite simple. My position is that if you say something is supported, you should be testing it. Thats not unreasonable, from any perspective.

The fact that I am calling attention to that fact, doesnt mean I am molesting someone. I just means I am pointing out objectively misleading statements on the home page.

If you want to keep the home page as is, and continue to do no testing, thats your business. You call my report "lousy". Well let me tell you, I left out the OS detail on purpose. Because I had suspicion that despite the home page, no testing was being done outside Windows 10. A suspicion which you easily confirmed.

Perhaps instead of getting defensive, you could take this moment to reflect on the courses of events that led to this situation. Do you really want to blame the user who simply read the homepage and used the software as advertised? People make mistakes. I have made plenty. Its not a weakness to acknowledge that.

**Comment by avih** [comment]
So what made you think it's a mintty issue? Was mintty the only thing which got upgraded? or were there gazilion other things which got updated and imntty was only one of them?

**Comment by nu8** [comment]
@avih using MSYS2 without Mintty (just `cmd.exe`) still works fine. and other
terminals like ConEmu still work fine.

But youre right, I dont know for sure. But even if I go, and build all the
versions and do all the testing and confirm its a Mintty problem, where does
that leave me? Even if the issue gets fixed, the maintainer has admitted in this
thread that regular testing isnt being done with anything outside Windows 10.

So you can see why I might be reluctant to carry out that effort. If active
testing was being done on the advertised operating systems, then I would glady
take that effort. But in this case, it just seems like a waste of time.

**Comment by avih** [comment]
You don't need to build all the versions. You reported it broke "from 3.0.0, to 3.1.6", so you only need 3.0.0. You might even still have it in your `/var/cache/pacman/pkg/` dir inside MSYS2. And if not, I happened to have `mintty-1~3.0.0-2-x86_64.pkg.tar.xz` and I uploaded here - https://0x0.st/iOP_.xz

**Comment by nu8** [comment]
Ok I tested it. Using pristine new MSYS2 with old Mintty, works fine.

Using pristine old MSYS2 with new Mintty, slow and bad.

**Comment by avih** [comment]
What about prinstine new MSYS2 with new mintty?

**Comment by nu8** [comment]
That was already tested with the posting of this issue...

Thats the exact reason this issue was posted...

**Comment by mintty** [comment]
> My position is that if you say something is supported, you should be testing it. Thats not unreasonable, from any perspective.

That's something that could be talked about if you were asking in a constructive polite manner.
But I do not approve that position even if you try to enforce it with additional nonsense about Mac support and your interpretation of the world.
Support means "if there is a problem, I will look into it". That is also not unreasonable, particularly in open source.

> Because I had suspicion that despite the home page, no testing was being done outside Windows 10. A suspicion which you easily confirmed.

Whereby you confirm that you were not so much interested in this issue but rather in finding tricky ways to impose your view of the world on this project, especially as there does not appear to be any issue as I've meanwhile tested.
And you have not answered my question:
If you want full testing to be carried out on each release, will you pay for it?

**Comment by nu8** [comment]
I gladly pay money for projects that I find useful. But I think misleading potential customers is a bad business practice.

**Comment by nu8** [comment]
I am closing this issue, because I am disgusted by the behavior of @mintty and I dont really want to use Mintty anymore, even if issue is fixed. Shame on you.

**Comment by avih** [comment]
IMHO that was pretty out of line the whole way. But whatever.

**Comment by mintty** [comment]
Might in fact be related to keyboard repeat, as mentioned in the other issue (fixed for 3.1.7).
A case for more proper and less misleading issue reports and cooperation attitude.
