### ISSUE TITLE
Ctrl+Alt+Left Click Opens session switcher instead of drag to move

### ISSUE THREAD

**Issue by Sawaiz** [mintty/mintty#1008]
Control, Alt, Left Click Drag opens the session switcher instead of moving the window. This occurs both with all my settings as well as launching with no config file. I did update from `2.9.4` so I might have missed this being removed.

In the manual under the `-B` flag
> However, a window move can also be done with Ctrl+Alt+click-drag.

`Mintty 3.1.4 (x86-64)`
`WSLtty 3.1.4.2 `

**Comment by mintty** [comment]
This was broken in 3.0.3 when additional mouse features were introduced that were just intended for the title bar.

**Comment by mintty** [comment]
Released 3.1.7.
