### ISSUE TITLE
Slow key repeat rate on 3.1.6

### ISSUE THREAD

**Issue by carlescufi** [mintty/mintty#1009]
I recently updated my Cygwin installation, which brought mintty 3.1.6. Since this update I have noticed that the key repeat rate is substantially slower than what the system (Windows 10)  is set to, and this seems to be a regression (I have been happily using Cygwin with mintty for 5+ years without this problem, thank you for the excellent terminal emulator by the way).

I am happy to run any tests you'd like me to. I tested the repeat rate by comparing it to the control panel one and a Windows Terminal with cmd.exe.

Separately, I just updated my Git for Windows from 2.25 to 2.27, which updated mintty in there from 3.1.0 to 3.1.6, bringing the slower key repeat rate. So I can confirm that this happens both with cygwin and msys and is only related to msys 3.1.6 (vs 3.1.0 as a refererence). 

Might be related to #1007.

**Comment by mintty** [comment]
This issue has been fixed; 3.1.7 to be released this week.

**Comment by mintty** [comment]
Released 3.1.7.

**Comment by carlescufi** [comment]
> This issue has been fixed; 3.1.7 to be released this week.

Thank you. Do you want me to close the issue?
