### ISSUE TITLE
“Git Bash here” is not working when opening by right click on windows 7

### ISSUE THREAD

**Issue by AyushAgrawalProgrammer** [mintty/mintty#1014]
I installed Git version 2.27.0.windows.1 .
I tried to open Git Bash by right click, then it created a file mintty.exe.stackdump in the same directory but git bash not started.
Please Help me...
When I tried to read mintty.exe.stackdump, then I have seen this -->
`Exception: STATUS_ACCESS_VIOLATION at eip=003003B6
eax=00000000 ebx=0045028B ecx=0022C5CC edx=77B470B4 esi=004A0410 edi=80000000
ebp=0022CB48 esp=0022C614 program=C:\Program Files\Git\usr\bin\mintty.exe, pid 1907, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CB48  003003B6 (20041370, 2004137A, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace`

**Comment by mintty** [comment]
You may have mintty 3.1.6 installed which had a problem on Windows 7 and also older Windows 10 versions (#1001). Please upgrade.

**Comment by mintty** [comment]
OK, apparently the newest release of Git for Windows comes with mintty 3.1.6 which is unfortunate.
Please report to them that mintty should be updated to 3.1.8.

**Comment by Biswa96** [comment]
cc @dscho

**Comment by AyushAgrawalProgrammer** [comment]
> cc @dscho

?

**Comment by AyushAgrawalProgrammer** [comment]
> OK, apparently the newest release of Git for Windows comes with mintty 3.1.6 which is unfortunate.
> Please report to them that mintty should be updated to 3.1.8.

Where to report @mintty ?

**Comment by dscho** [comment]
Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) of Git for Windows. The latest official release of Git for Windows was published at a time when v3.1.6 was still current.

**Comment by dscho** [comment]
> Please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) of Git for Windows.

@AyushAgrawalProgrammer did you test?

**Comment by mintty** [comment]
Git for Windows 2.28.0 is now available, which comes with mintty 3.2.0.
