### ISSUE TITLE
Symbols appear as strange characters 

### ISSUE THREAD

**Issue by charsi** [mintty/mintty#1017]
I am having trouble displaying some symbols in mintty 3.1.6. Tick mark for example displays as ΓêÜ

As the problem appeared to be UTF8 related I tried changing the character set to 'UTF-8' and using different fonts in mintty settings. None of this worked.

After scouring the internet for a workaround I did find running `chcp.com 65001` fixes it. But I do not remember having to do this in previous versions of mintty. Also this isn't a very good solution according to this post - https://dev.to/mattn/please-stop-hack-chcp-65001-27db

These are an example of symbols i am talking about, as printed by mocha test framework/noejs -

![image](https://user-images.githubusercontent.com/826310/85591837-78b80a00-b5fa-11ea-91d0-40e3228a739f.png)

before running chcp.com 65001 - 
![image](https://user-images.githubusercontent.com/826310/85591884-85d4f900-b5fa-11ea-9111-91053517fc55.png)

**Comment by mintty** [comment]
This is, to be assumed, with a non-cygwin, i.e. native Windows console application. If that application responds well to chcp and if you are running in a UTF-8 environment, there is nothing wrong with using that fix, it's not a hack, it's just something you'd need to have some knowledge about to apply it properly.
However, since cygwin 3.1.0, a respective adaption should actually occur automatically, by built-in ConPTY support (unless explicitly disabled), so my second assumption is that you're still running an older version of cygwin.
Either way, this is not a mintty issue.

**Comment by charsi** [comment]
Thanks. I am running mintty from the latest build (2.27.0) of git-for-windows which uses MSYS32. Is this worth reporting there?

**Comment by mintty** [comment]
What does `uname -a` say?

**Comment by mintty** [comment]
Ah, whatever it says, I recall they applied a patch to disable the new ConPTY support in MSYS2 for now. Which explains the issue.

**Comment by charsi** [comment]
Ah ok. For people who might land here from a search engine, easiest fix for me was to add `-c chcp.com 65001` to the launch shortcut for git-bash/mintty. 

Output from my uname -a
`MINGW64_NT-10.0-18362 COMPUTER_NAME 3.1.4-340.x86_64 2020-05-19 12:55 UTC x86_64 Msys`

**Comment by charsi** [comment]
Found the related bug - https://github.com/msys2/MSYS2-packages/issues/1974

**Comment by Biswa96** [comment]
If this is related to msys2 then try to set `MSYS=enable_pcon` environment variable system wide. msys2 makes the ConPTY feature as optional i.e. opt-in.

**Comment by dscho** [comment]
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by dscho** [comment]
Oh, wait, are you using Cygwin, MSYS2 or Git for Windows?

**Comment by charsi** [comment]
Confirmed fixed in the latest snapshot. I am using git for windows.
