### ISSUE TITLE
mintty does not show (certain) non-printable characters at the command prompt

### ISSUE THREAD

**Issue by cooky-cook** [mintty/mintty#1019]
Let us have the following command (need to attach to keep the character intact):
[command.txt](https://github.com/mintty/mintty/files/4889289/command.txt)

It contains a non-printable character (String Terminator) before the repo URL.

When I copy this command into mintty 3.2.0, I cannot see it at all at the command prompt. Trying to run the command results in an error (invalid repo URL) and the rogue character is shown in git output.

Here's how other terminals handle it:
windows cmd & powershell - the rogue character is shown after pasting the command
default Ubuntu 18.04 terminal - the rogue character gets removed when pasting and the clone proceeds fine

either of these seems better than not seeing the character. Is this behavior expected?

**Comment by mintty** [comment]
Mintty displays what the application gives it, in this case the shell. This is not a terminal issue (therefore closing as invalid).
I'd consider the Ubuntu behaviour as buggy, you cannot simply drop information. Note that with cygwin xterm, behaviour is identical.

**Comment by cooky-cook** [comment]
Is there a way to show all characters at the command prompt though? Notepad++ has such an option, for example (yes, it is not a terminal, I know)

**Comment by mintty** [comment]
U+9C STRING TERMINATOR is not a printable character. It's a control character, like ^C or linefeed which are not shown either.
The shell could decide to output it in an escape notation.

**Comment by mintty** [comment]
Actually, xterm has an option (allowC1Printable / -k8) to enable turn that range of control characters printable.
But then, how should they be displayed? Xterm only shows a hollow box.

**Comment by mintty** [comment]
New option PrintableControls=1 will display them. Reopening until next release.

**Comment by mintty** [comment]
Released 3.3.0.
