### ISSUE TITLE
The image saved by "Save as image" has a strange file name

### ISSUE THREAD

**Issue by GeekDuanLian** [mintty/mintty#1025]
![image](https://user-images.githubusercontent.com/6257434/88528386-29b62800-d031-11ea-850c-8314d6a8e621.png)

I think Windows may not want a colon in the file name 🙁

**Comment by mintty** [comment]
I could change it to YYYY-mm-dd_HH-MM-SS but saving as HTML file uses the same format (with colons) already. Should it be configurable?

**Comment by GeekDuanLian** [comment]
> I could change it to YYYY-mm-dd_HH-MM-SS but saving as HTML file uses the same format (with colons) already. Should it be configurable?

If it can be configurable, it will be the best, and it should prompt these characters that are not recognized by Windows.

At the same time, I hope I can also configure the default save path of the image, because some people may like to save it on the desktop, while others want to save it in the home directory, not just the current directory.
Or only saving it to the clipboard is also a good choice, because you may have to paste it elsewhere immediately.

For saving as HTML file, I have the same view as I said above.

**Comment by BrianInglis** [comment]
> I could change it to YYYY-mm-dd_HH-MM-SS but saving as HTML file uses the same format (with colons) already. Should it be configurable?

You should not use any device `:` or path separators `/ \`, glob `* ?`, redirection operators `< > |`, double quote `"` or null `\0` characters disallowed by Windows in filenames, as they can cause problems if used unquoted in many scripts, and Cygwin translates those into PUA UTF16LE characters in the filename which can be converted back properly for display only by Cygwin, and a lot of Cygwin users run from the cmd shell and use other programs (e.g. dir) which may not be able to handle them.

**Comment by avih** [comment]
Imagine a file named `c:windows` where it's impossible to tell whether it's at the CWD at drive C or contains colon relative to the current dir, for instance...

Agreed, file names should obey the OS rules.

**Comment by BrianInglis** [comment]
Good point, that could be used in a shell attack if Cygwin converted that back to the drive separator and used that in a target path; one reason I am not supportive of allowing any Windows paths in Cygwin filenames: interpretation can sometimes be ambiguous.

**Comment by mintty** [comment]
This kind of misinterpretation cannot happen as the colon is only in the time section of the file name, not at the second position.
I'll change it anyway.

**Comment by BrianInglis** [comment]
The colon is also the prefix for openssh command hostnames e.g.
```
$ scp -p cygwin:.email rpi2:cygwin/
```
which gives scope for some nasty _shellshocks_ with crafted names and links!

**Comment by mintty** [comment]
This was changed in the release.
