### ISSUE TITLE
Resize window to bigger number of lines may cause issues

### ISSUE THREAD

**Issue by paolo-sz** [mintty/mintty#1026]
https://github.com/mintty/mintty/blob/08a9d588427269212f58c034988a79e80fbd8d07/src/term.c#L1121-L1148

It seems terminals do not expect line scroll, if available in the scrollbuffer, to fill the new bigger window in case of a resize that increase the number of rows. In this case, some commands generate strange output.
In order to recreate the issue:
- be sure the screen is full of lines (better if not almost blank) and also the scrollback is full enough of lines (I usually press enter a lot of times or "cat" a text file)
- resize the window reducing the lines (better if you reduce a lot, up to only a few lines). Remember this size
- resize back the window to a bigger size
- run ipconfig (windows)

You can then see the output of the command is not printed out starting on the line below the prompt but on the line after the size of the screen when it was reduced to few lines.

Tried fixing restore variable to 0 (line 1123) and to remove code from line 1130 to 1147 and the issue seems to be fixed if you accept the text does not follow anymore the rows increase.
Tried other ways (ANSI escape sequences, ioctl, ...) in order to fix the issue retaining the current behavior but I got no success...

**Comment by mintty** [comment]
What's the issue? Please describe clearly.
Does your issue depend on calling a non-cygwin program (like ipconfig)?

**Comment by paolo-sz** [comment]
> What's the issue? Please describe clearly.

The issue is that the output of the command is not printed out where it was expected to be (it overwrites lines before the prompt line from where it is called).

> Does your issue depend on calling a non-cygwin program (like ipconfig)?

I do not think so. It seems the ipconfig text output is preceded by some ANSI escape sequences and this is something that could happens from any command (I think).
That escape sequences move the cursor around based on what it thinks the size of the terminal is. It also seems the OS or the terminal itself somehow "ignores" the last terminal resize or, at least, provides the "old" size to the executed program with the result that the command output overwrites previous terminal lines.

**Comment by mintty** [comment]
> > Does your issue depend on calling a non-cygwin program (like ipconfig)?

> I do not think so.

Well, I do think so. Running ipconfig activates ConPTY support of cygwin 3.1.0 and later (which is your version?). This causes the screen to be redisplayed, also using positioning sequences. However, I could not reproduce your specific observation of "starting at the wrong position". This is something that can happen if you enter some cursor-up or cursor-down keys typing ahead while the previous command is still producing output. That's why I have to ask for an exact test case to demonstrate whether there is an issue at all.

**Comment by paolo-sz** [comment]
Mine cygwin is 3.1.6-1

Here the screenshot of the result in my case
![mintty#1026](https://user-images.githubusercontent.com/7062844/88819983-0621e780-d1c1-11ea-8433-9bd3266fb394.png)

You can see the ipconfig command on the bottom of the screen and the cursor after the command in the red circle.
I didn't type anything else then <enter> (many times), "ipconfig<enter>" and the double resize (smaller, larger through mouse window resize) just before the ipconfig command (you must release the mouse button in between the two resize in order to allow window to do all the resize stuff). 
To tell you all the truth I don't feel the issue is really in mintty but somewhere in the OS or tty/pty implementation...
By the way, my OS is win10 build 1809 and mintty is ran as admin.

Anyway, the issue happens only with ipconfig (at least this is the only program I found triggering this issue) and after a so specific, and maybe not really frequent, case that it could be considered less than minor or even a simple information...

**Comment by paolo-sz** [comment]
sourcing (bash) this attached file triggers the issue as well..
[mintty#1026.txt](https://github.com/mintty/mintty/files/4996015/mintty.1026.txt)

**Comment by mintty** [comment]
I could not reproduce for a while as my ipconfig output is much longer than yours (and than a screen). After some tweaks, and adding sleep commands to the test script, reproduced the issue.
With a screen log (option `-l`), we can see that a bunch of positioning and clearing sequences are sent to the terminal, and then an explicit positioning to line 6 just before the output of ipconfig. So there is no issue on the terminal side.
It's likely a glitch in the cygwin ConPTY support code. Some component apparently still thinks the terminal has the size before the last resize.

**Comment by mintty** [comment]
I could not reproduce it with the latest patch of the cygwin ConPTY code (not yet released).
