### ISSUE TITLE
zsh p10k host 256 color is not showed by default (Git Bash MinTTY)

### ISSUE THREAD

**Issue by JiapengLi** [mintty/mintty#1027]
This is not an issue. It is just about the option. When the host computer enables 256 color, mintty should do the same. 

Like below: Options -> Terminal -> xterm-256color
![image](https://user-images.githubusercontent.com/3773923/89708254-e43a1900-d9a7-11ea-8e96-d837ce2d3edc.png)

**Comment by mintty** [comment]
Mintty always supports all colour settings, including 256 palette colour attributes and true colour attributes, not limited by the `Type` setting.
