### ISSUE TITLE
OSC returning \e\\ instead of \a

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#1028]
When I echo: \e]4;1;?\a

xterm returns: \e]4;1;rgb:bfbf/0000/0000\a

mintty returns: \e]4;1;rgb:bfbf/0000/0000\e\

Going by the xterm documentation xterm's behavior is as described:

>           XTerm accepts either BEL  or ST  for terminating OSC
>           sequences, and when returning information, uses the same ter-
>           minator used in a query.

**Comment by scandum** [comment]
Thanks, works like a charm.

**Comment by mintty** [comment]
Released 3.4.0.
