### ISSUE TITLE
[Enhancement] Visor mode / Quake style

### ISSUE THREAD

**Issue by meav** [mintty/mintty#1029]
Continue with this issue:
`https://github.com/mintty/mintty/issues/171`
With visor mode (Quake style), when I am in another program, I can go back to console window by using hotkey; and When I am in console window, I can minimize console window by same hotkey.
I think this feature very helpful and I hope it will be added in mintty.
Thank you for reading and sorry for my bad english.

**Comment by mintty** [comment]
Actually you can also configure a hotkey with Windows onboard means: in the properties menu of a desktop (or start menu) shortcut.

**Comment by meav** [comment]
> Actually you can also configure a hotkey with Windows onboard means: in the properties menu of a desktop (or start menu) shortcut.

Can you explain more?

**Comment by mintty** [comment]
Right-click on shortcut, Properties. Enter e.g. Alt+F9 in the field shown (in your respective language):
![grafik](https://user-images.githubusercontent.com/12740416/91412492-27223a80-e84a-11ea-90f8-2d39da981a0c.png)

**Comment by meav** [comment]
I am using Windows 8.1
In my Windows, this hotkey just open shotcut. This issue is about minimize/unminimize window with hotkey.

**Comment by mintty** [comment]
Configure the shortcut key, Save/OK. Hit shortcut key/hotkey. If not mintty is running, it will be started, otherwise a running instance will be activated. Verified in Windows 7 and Windows 10.

**Comment by meav** [comment]
In my windows 8.1; I tried with mintty and other program desktop shortcut; when I press hotkey, it just run shortcut (with or without running of program).
In windows 7 of my friend; I tried with other program shortcut (chrome, word, ...) (not mintty) and same result.

**Comment by ducklin5** [comment]
This can be done with mintty in conemu

**Comment by mintty** [comment]
Well, thanks for the hint, but Conemu isn't really a preferred wrapper for mintty, especially not just for this purpose.
Also, as I've described above, activating mintty with a hotkey can be achieved by plain Windows on-board means.
Maybe it's even possible to detect the hotkey and use it for later minimising as desired above.

**Comment by mintty** [comment]
Mintty now supports implicit detection of being hotkey-activated and reuses the same key/modifiers combination to put itself into the background again, effectively achieving the desired behaviour. Also added to the Tips wiki page.

For those familiar with the feature, is it rather called "visor mode" (#171, few google matches), "quake mode" or "quake style", what is "quake" and are there any references to shed light on this?

**Comment by mintty** [comment]
Released 3.4.0.

**Comment by meav** [comment]
Thank you very much for this feature.
About "quake": I used google and found this link:
http://freesoftwaremagazine.com/articles/how_to_use_quake-style_terminals_on_GNU_Linux/

> **What the heck is a Quake-style terminal?**
> Quake is a wildly popular first person shooter created by id Software. In the game, there is a terminal that is accessible by hitting the ~ key. It is used to edit settings and variables, show logs, and enter commands and cheats (for more, read the [Quake-style Console article](http://en.wikipedia.org/wiki/Quake-style_console) at Wikipedia). Quake isn’t the only program that has this functionality: Doom, Half-Life, Dark Engine, Lithtech, and several other games and game engines use similar consoles.
