### ISSUE TITLE
Performance slowdown with certain scroll regions

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#1030]
This issue is most easily reproduced in TinTin++. https://github.com/scandum/tintin

```
#unsplit
#line benchmark #help %*
```
Output: 1007029 USEC.
```
#split
#line benchmark #help %*
```
Output: 2751195 USEC.
```
#split 1 1
#line benchmark #help %*
```
Output: 1008461 USEC.

There's a notable slowdown in the second run. By the way, the latest Windows Terminal release runs the command in half the time compared to mintty.

If you have a screen with 24 rows #split should be equivalent to echo -e "\e[1;22r"

**Comment by mintty** [comment]
When I run tintin++, nothing happens, and commands like "split" or "#split" are ignored.
Please provide a test case, preferably independent of tintin, using `echo` or `cat` with suitable test data.

**Comment by scandum** [comment]
Should be as easy as:
```
git clone https://github.com/scandum/tintin
cd tintin/src
./configure
make
./tt++
```
Creating a test case by other means would not be easy.

**Comment by mintty** [comment]
That's not a test case, and I had done it already. The issue is that I am not familiar with that program and I don't see why I should spend effort into investigation of a specific program to reconstruct a test situation. That would not be easy too, and as you are claiming some issue with mintty, it's on your part to demonstrate it.

**Comment by mintty** [comment]
You could as well provide instructions what to do with tintin to demonstrate the issue. The key term here is "reproducible test case".

**Comment by mintty** [comment]
OK, I may have been mislead by tintin error messages (no session) and missing prompt first; in fact, your commands seem to work "offline". However, I get the same result after split 1 1 in most cases, there is no significant effect.

**Comment by scandum** [comment]
There's no notable difference between #unsplit and #split 1 1. The odd slowdown is with #split, no argument.

**Comment by mintty** [comment]
OK, so the test case is `echo -e "\e[1;22r"`; time cat something-long (not hard to produce).
So with activated scrolling region, scrolling is noticeably slower.

**Comment by scandum** [comment]
That was easier to reproduce then I thought.

In case it slipped by you, when using echo -e "\e[2;22r" the scrolling speed appears unaffected.

**Comment by mintty** [comment]
Output does not seem to be generally slower within a scrolling region but there is a delay after ~128KB. Note however, that the same delay occurs in xterm, so I have a suspicion it might be a cygwin issue, maybe related to pipes. Why and how it should depend on a scrolling region starting in the top line, however, is truely mysterious.

**Comment by mintty** [comment]
It's somehow related to the cygwin ConPTY support. It did not happen with cygwin 3.0.7 and is not supposed to not happen with cygwin 3.2.0 anymore (verified with snapshot 20200803).

**Comment by scandum** [comment]
While we're at it, the problem seems absent in qterm, which is also 4x faster than mintty.

I've pushed past the boundaries of what mintty and xterm can comfortably handle with sub-window handling.

https://user-images.githubusercontent.com/52607428/70944197-dcadb480-2052-11ea-95a5-409821e827c5.gif

**Comment by mintty** [comment]
If you are referring to qterminal, that thing, like some other X terminals, does not even start for me within a minute. If it's another terminal, it's not a cygwin program, so not comparable.
I have no idea what your animated gif is supposed to tell us.

**Comment by mintty** [comment]
And, for that matter, as you're running cygwin 3.1.*, it's its ConPTY support that slows down output speed a bit. Mintty is much faster as you'll see again with cygwin 3.2.*.

**Comment by scandum** [comment]
The animated gif tells us that mintty does not have a high frame rate. Hopefully things will improve with 3.2.

I recall mintty being quite zippy in the past, to the extent that I assumed it wasn't displaying large bodies of text and just dumped it to scrollback and skipped ahead.

**Comment by mintty** [comment]
To achieve maximum output speed, of course some optimisation is needed. This was introduced on request (#835) quite a while ago. You may experiment with option `DisplaySpeedup` (or, adversely, option `Baud`).

**Comment by scandum** [comment]
Setting the display speed to 9 doesn't seem to make a difference, possibly because there's no scrolling involved.

I'll take a peek at the mintty source code sometime and see if I can find any notable bottlenecks.

**Comment by mintty** [comment]
You may have missed a point; there is no bottleneck. Wait for release of cygwin 3.2.0, then you're welcome to any further analysis.

**Comment by mintty** [comment]
Cygwin 3.2.0 has been released.
