### ISSUE TITLE
CTRL + ALT_R + F combination does not work after start emacs in terminal

### ISSUE THREAD

**Issue by sunlin7** [mintty/mintty#1034]
Hi @mintty ,

When ssh to remote with `mintty` (terminal type is set to `xterm`), start emacs in terminal, try "Ctrl+Alt_R+B", there is nothing happend (no input to remote), while windows CMD will send `\33\6` (`^[^B`) to remote, the "Ctrl+Alt_L+B" also work correctly.
I found it's relate to emacs TUI display, after emacs display TUI in terminal, mintty will not send "Ctrl+Alt_R+B" to remote.
I try to reduct the TUI output into `^[[>0c^[]11;?^[\^[[>4;1m^[[?2004h` (base64 is `G1s+MGMbXTExOz8bXBtbPjQ7MW0bWz8yMDA0aA==`), for reproducing the issue, just follow the commands to reproduce my issue:
`cat - | hexdump -C # then press "Ctrl+Alt_R+B", "Enter", can see the ^[^B, then "Ctrl+d" to finish`
`echo G1s+MGMbXTExOz8bXBtbPjQ7MW0bWz8yMDA0aA==|base64 -d`
`cat - | hexdump -C # then press "Ctrl+Alt_R+B", "Enter", nothing send to terminal`

**Comment by mintty** [comment]
Ctrl+B is ^B or 0x02, Alt adds an ESC prefix, so you will get ESC ^B. This works, also remotely.

**Comment by sunlin7** [comment]
hi @mintty ,
I tried on mintty bounded with vanilla cygwin, ssh to remote server, starting emacs the press `ctrl+alt+b`... did I missed any configuration?

**Comment by mintty** [comment]
Likely emacs maps the sequence to something.

**Comment by sunlin7** [comment]
okay, I'll try more then update this ticket, thank you.

**Comment by sunlin7** [comment]
Hi @mintty ,
You're totally right, the keys can send to remote, I detect by `cat - | hexdump -b`, pressing the Ctrl+Alt+B, then press enter and Ctrl+d,  the keys are catched. So it's should be emacs issue. I'll investigate and report to upstream. Thank you.

**Comment by sunlin7** [comment]
Hi @mintty ,
I investigated more future, and find a way to reproduce my issue, and I can confirm it's relate to mintty, this issue not happend with windows CMD.

**Comment by sunlin7** [comment]
@mintty I had update the ticket description with exactly reproduce steps for the issue, please check it, thank you.

**Comment by sunlin7** [comment]
Hi @mintty ,
I had reduce the charactors to `^[[>4;1m`, and can be produce by `echo -e "\e[>4;1m"`, after that "Ctrl+ALT_R+F" will no data to remote.

**Comment by mintty** [comment]
^[[>4;1m is modifyOtherKeys mode which overrides Ctrl+Alt combinations. Works as specified.

**Comment by sunlin7** [comment]
Hi, after following the hints from mintty , I find this page https://invisible-island.net/xterm/modified-keys.html which give the hitory for `modifyOtherKeys`. 
Emacs will try enable `modifyOtherKeys` to get extra key binds in xterm. 
In mintty, when `modifyOtherKeys` is enabled, `Ctrl+rAlt` will be `AltGr`, then combination `Ctrl+rAlt+X` will send nothing to remote.
Enable the mintty-options->keys->"AltGr is also Alt" options can resolve my problem.
@mintty Thank you.

**Comment by mintty** [comment]
You had quoted

> CTRL + ALT_R + F

above, which I had ignored after you referred to modifyOtherKeys mode.
The _right_ Alt key is in fact AltGr, that's why Ctrl+righ-Alt does nothing for keys that have no AltGr binding.
Without the "AltGr is also Alt" option, you could also simply use the left Alt key instead.

**Comment by sunlin7** [comment]
Hi @mintty 
Yes, using left Alt key is worked for me for a while as a workaround.
The issue happend when I set terimnal type as xterm and start the emacs-TUI in remote (or, `echo -e "\e[>4;1m"`). 
That means, 
1. if set terminal type to vt220 (not xterm), the issue won't happen
2. terminal type is xterm, and before start emacs-TUI, the Ctrl+righ-Alt+B will rend  \33\6 (^[^B) correctly; after the start emacs-TUI, Ctrl+right-Alt+B send nothing to remote, until this mintty be closed.
$ `cat - | hexdump -C # then press "Ctrl+Alt_R+F", "Enter", can see the ^[^F, then "Ctrl+d" to finish`
$ `echo -e "\e[>4;1m"`
$ `cat - | hexdump -C # then press "Ctrl+Alt_R+F", "Enter", nothing send to terminal`
