### ISSUE TITLE
[Enhancement] [Quake mode] Keep mintty appear in taskbar after minimized by hotkey in quake mode

### ISSUE THREAD

**Issue by meav** [mintty/mintty#1035]
Hi everyone, it's me again.
Thank you very much about Quake mode feature.
I think in Quake mode, after mintty minimized by hotkey, mintty should appear in taskbar (now, mintty disappear in taskbar); hotkey should just minimize mintty window normal like minimize button do.
Sorry for my bad english and thanks for reading.

**Comment by mintty** [comment]
Minimized applications are normally still visible in the taskbar. If there is some setting that would change this, please demonstrate your issue. If that's the case, you are welcome to investigate how it could be overridden dynamically.

**Comment by meav** [comment]
In my machine, after I minimize mintty by hotkey, mintty not visible in taskbar.

![0004_20200924_182422](https://user-images.githubusercontent.com/29623675/94139484-e989ef00-fe93-11ea-8f21-0adeeb7e6769.gif)

I want mintty still visible in taskbar.

**Comment by mintty** [comment]
> In my machine,

This is not default behaviour I believe. I see it's happening for you but I cannot reproduce it. Did you configure anything about your desktop that might cause this?

> I want mintty still visible in taskbar.

Sure, that's understood from the issue. The statement doesn't help though, a test case and a technical solution are needed.

**Comment by meav** [comment]
Mintty still appear in taskbar when minimized by hotkey is normal?
I tested in my windows 8.1, not my window 7 and not my window 10; all mintty minimizeed by hotkey not appear in taskbar.
I not use third app to config window; just use option provied by window.
What info I can provide?

**Comment by mintty** [comment]
If you also have a Windows 10 machine, test it there. Otherwise I have no idea.

**Comment by meav** [comment]
I tested again in window 10; mintty not visible in taskbar after minimized by hotkey.
Anyway, this is unimportant issue.

**Comment by mintty** [comment]
Ah, right, I tested with "normal" session, not with hotkey-started terminal, as I assumed the minimizing would be the same.
Sorry I didn't test more carefully before.
However, the point is still that I have no idea how that could be changed. Patch proposals are welcome.

**Comment by mintty** [comment]
Actually, I have an idea...
It was more or less on purpose to hide the window rather than minimize it, as I had understood the quake/hotkey feature. How do other quake things behave? Should this be changed or does it need to be configurable?

**Comment by mintty** [comment]
Released 3.4.1.
