### ISSUE TITLE
every 8th column of characters go dark while using emacs

### ISSUE THREAD

**Issue by saurik** [mintty/mintty#1036]
I have installed mintty 3.4.0 via Cygwin (this also happened with 3.3.0 at least). If it is important, I have show bold" set to only "as color". I have verified the behavior is the same with TERM set to either "xterm" or "mintty". I'm also getting the same behavior when using a local copy of emacs installed via Cygwin or ssh'd to a remote computer running Ubuntu.

If you open emacs and go to likely/seemingly any kind of buffer--at least the default help screen has this issue, which should make it easy to reproduce--and hold down the right arrow, as you pass by characters, every 8th column will go dark as you pass it (and the following character will also become somewhat dark, but not as dark).

**Comment by mintty** [comment]
As I am not an emacs user, I cannot easily reproduce your issue.
As it sounds, however, it may be a consequence of emacs highlighting policy with your bold/colour settings. What if you change them?
To comment on the issue, the best would be to make a screenlog (not screenshot), using mintty -l, terminate logging as soon as the issue is visible, to get a file that will demonstrate the issue simply showing it with cat.

**Comment by mintty** [comment]
> terminate logging

As the issue seems to flip while moving the mouse, this may be a bit tricky. I'd try to make the issue visible, then switch window with Alt+Tab and copy the log file at this moment. Or trim the logfile later to cut out the issue.

**Comment by saurik** [comment]
> As I am not an emacs user, I cannot easily reproduce your issue.

To be clear, the reproduction I chose was designed to be something trivial that anyone could do without having to know how to use emacs: install it (in Cygwin as "emacs" or on Ubuntu as "emacs-nox" <- the normal "emacs" package might be sufficient, but I figure this is easier), run emacs (with no arguments <- this will bring up a default help screen), and then hold the right arrow key down.

> As the issue seems to flip while moving the mouse, this may be a bit tricky.

The characters change colors as the cursor moves across them, but they then stay the wrong color. I have thereby created a log for you, wherein I ran emacs, held down the right arrow to cause some glitches, and then closed mintty (to avoid a screen refresh). When I cat this file it does leave me in a state where some of the characters I went past are dark. I hope this is what you wanted?

[mintty-emacs.log](https://github.com/mintty/mintty/files/5288158/mintty-emacs.log)

**Comment by saurik** [comment]
Just for purposes of visually showing you what I'm talking about with the columns, and to maybe make this easier for others who might see this to know what I'm on about without trying it out, I'm _also_ going to give you some screenshots ;P. The first is what the terminal looks like when emacs is opened, and the latter is after I've held the right arrow key down long enough to have touched every character in the buffer.

<img width="896" alt="mintty-emacs-before" src="https://user-images.githubusercontent.com/36743/94363262-e5b5c280-0075-11eb-9855-fd9df2f6346d.png">
<img width="896" alt="mintty-emacs-after" src="https://user-images.githubusercontent.com/36743/94363265-e77f8600-0075-11eb-88ef-d23a87d8e4ab.png">

**Comment by mintty** [comment]
> I hope this is what you wanted?

Yes, thanks, but it does not produce the issue for me. That's why I asked you to vary settings also.

**Comment by mintty** [comment]
..., well, it does, but only in the first line, unlike your screenshot

**Comment by mintty** [comment]
It's caused by a strange series of cursor forward, Tab and Backspace controls at the end of the log.

**Comment by BrianInglis** [comment]
Cygwin emacs maintainer is on Github @ kbrow1i has helped in the past, and may be able to help here, but first OP should disable all emacs profiles, settings, and customizations, and retest, as those are often the cause of most issues

**Comment by saurik** [comment]
> OP should disable all emacs profiles, settings, and customizations, and retest

@BrianInglis I installed emacs for the first time yesterday and had verified I did not have a local ~/.emacs file of any kind on Cygwin. (I did on Ubuntu, but this also happens with the evil test target.) I am not an emacs user: I just started using emacs yesterday, and it didn't work on mintty.

> As it sounds, however, it may be a consequence of emacs highlighting policy with your bold/colour settings.

The issue with this is it is making it sound like I did something strange to emacs, which I haven't, nor have I claimed to, so I can't do this :(. If it makes you feel any better, I have now verified this with emacs -Q, -q, and -Q -q, which I think skips all configuration, including from Cygwin.

> That's why I asked you to vary settings also.

Ok, I have gone into the mintty and changed the setting of "show bold" to "as font" instead of "as colour". I mentioned that I changed that setting only out of completeness--as clearly mintty must work with "show colour" and if it didn't I would find a better terminal--and it didn't make it work.

**Comment by mintty** [comment]
@BrianInglis, thanks for further debugging proposals but the issue has already been reduced to be demonstrated without referring to emacs.
@saurik, thanks for cooperating for debugging but I've already acknowledged there's something weird in mintty and threating to find a "better" terminal isn't helpful and is not motivating to proceed with the due analysis.

**Comment by saurik** [comment]
To recap, I know it isn't related to: 1) my emacs configuration; 2) the particular build of emacs; 3) some recent version of emacs; or 4) anything from my terminfo database. I've now tested with various combinations of -Q and -q on my unconfigured setup using emacs version 26.3 from Cygwin, 27.1 from Ubuntu Focal, 22.1.1 from macOS Mohave, and 21.4.1 from Debian Squeeze.

**Comment by saurik** [comment]
@mintty FWIW, I had almost immediately changed "better" to "working", as my intent was to indicate that if "as colour" wasn't supported, that would be a deal breaker for me; I found the continual press on me to vary my settings--particularly with the context from the person asking me to isolate that this isn't an emacs issue--extremely frustrating.

**Comment by saurik** [comment]
(And to be more explicit about it, being treated as if this is obviously some kind of user error caused by my advanced usage of emacs is "isn't helpful and is not motivating to proceed with due analysis".)

**Comment by mintty** [comment]
This is a weird effect that has not been reported before, in years, so asking for confirmation of the issue is a basic step in issue processing and does not imply it's "obviously" a user error but in fact it could be one, so let's calm down please.

**Comment by saurik** [comment]
@mintty I have now to just instrument mintty myself. In the case of characters that work, emacs is sending "\e[C". In the cases where it is not, it is sending TAB BS (to get to the 7th character) and TAB (to get to the 8th character).

I've thereby tracked the behavior down to the write_tab function in termout.c, which modifies the ATTR_DIM and ATTR_BOLD states as it moves the cursor, and have thereby been able to craft a trivial reproduction of the issue.

```echo -e 'hello world\e[9D\t'```

<img width="129" alt="minttybug" src="https://user-images.githubusercontent.com/36743/94376000-8040f080-00cc-11eb-81b4-efe68d3368dd.png">

I asked my coworker--the developer of readline (and a prior maintainer of emacs), and so my local terminal expert ;P--if it is correct to "change the the color states" on a tab character, and he provided the following feedback:

> The tab character moves to the next tab stop. Unlike pure movement commands, it is a character that has an appearance on the screen, so the whitespace that is generated has the correct color (i.e., the color of whatever was in effect). So I wouldn't change any attributes. If his internal structure requires that for some reason, then he should immediately replace their states.

**Comment by BrianInglis** [comment]
Far from assuming a "user error", I know that some packages install shell completion and editor mode scripts, that can sometimes change a user experience in unexpected manners that reflect another person's tastes, rather than just provide a mechanism. 
It is so unusual, and nothing like that reported under mintty or Cygwin in the years I've used it. 
It reminded me of CSS styling striping formulae, vim modeline and list mode settings to highlight tab stops and special characters. 
Under Windows it could be anything from a hardware issue in graphics memory or beam output, a graphics pipeline or renderer bug, a text styling bug, console output bug, or terminal emulator issue. 
The first thing Windows support folks ask, that I forget to do, or ask others to do, is restart Windows, to see if that makes a problem go away. 
Especially if you have any Windows patches waiting for a restart: some patch components get updated on application, and some not until after a restart, so you can experience weird symptoms in all kinds of areas until then, and I often have, as I delay restarting for days to weeks.

**Comment by mintty** [comment]
Uploaded a fix, please check.

**Comment by saurik** [comment]
I can confirm this fix seems to work for me!

**Comment by mintty** [comment]
Released 3.4.1.
