### ISSUE TITLE
Selection does not preserve tabs

### ISSUE THREAD

**Issue by clayne** [mintty/mintty#1037]
When selecting output all tab characters are selected as spaces even though the output itself definitely contains actual tab (0x09) characters. This makes it very difficult to preserve an exact facsimile of the output.

**Comment by mintty** [comment]
TAB is a control character, not a printable character. Behaviour is the same in xterm.
Is there any terminal that would copy TAB as a character?

**Comment by BrianInglis** [comment]
Some hardware terminals might internally interpret a 0x09 \t TAB character and/or send it to a printer or replay it verbatim, so systems may be configured to pass certain characters through verbatim to/from a terminal, but most systems' terminal drivers and emulators nowadays are set to convert it to specified or default amounts of space (every 8th column), so that is what is rendered and returned.

**Comment by mintty** [comment]
The semantics of TAB is "Move cursor to next tab stop, or to right margin if no further tab stops are present on line", according to DEC specs. That would raise tricky design issues if such a feature were considered. Would e.g. Backspace controls be expected in the clipboard too? What about `echo -e "xy\e[9Gz"`, how should the resulting line be copied?
Moreover, implementation would not be trivial as start and end position of each TAB operation would need to be marked internally.
Thus I intend to close the issue.

**Comment by mintty** [comment]
Another, even more tricky design challenge: `echo -e "xy\e[12G\eHz\rXY\e[2IZ"`.

**Comment by clayne** [comment]
> Is there any terminal that would copy TAB as a character?

Yep, Mac OS Terminal does this natively but I'm certain it's not the only one out there able to do this.

To be honest I've come to rely on it when writing unit tests because I can just copy expected output to the test I'm working on, however aside from that it just seems like the right thing to do. While tab is a control character and how it's output is purely an aspect of the presentation layer (which is why it's so useful), it does seem like something that selection should preserve if possible. Now while I do agree with your points about preservation of other control characters, it does seem like we could arrive at a reasonable middle ground that doesn't require having to copy output and then running the entire thing through `unexpand -a` due to the inherent lossiness of implicit space conversion.

Additionally, making it an option would probably avoid any issues with people who've come to rely on implicit conversion to spaces.

**Comment by mintty** [comment]
Speaking of layers, the requested feature is an application feature while terminals provide a presentation layer, so it's not a traditional terminal feature for good reason. A logging feature that may be useful for you is `tee`. Actually, mintty also provides application-layer logging with its `-l` option. The difference is that the logging happens during output, not after its rendering. Any trivial hack on presentation level will only handle simple cases of sequential output, not any complex situation.

You did not respond to my design challenges, and I'll add another one now. Please check how you'd reasonably expect a selection to reflect their respective output, and how Mac OS Terminal does it.
`echo -e "x  \tz"` (as opposed to `echo -e "x\tz"`)
`echo -e "x  \by\t\byz"`
`echo -e "x^[[4Gy\rX\tz"`
(ignore the dimmed appearance of the 'y' in the last example, it's a bug already fixed for the next release)
If you can describe in convincing terms how all these should be copied, establish that Mac OS Terminal handles them properly, and can give a consistent general definition of the desired procedure, we can talk about an optional feature.

**Comment by mintty** [comment]
On the other hand, if `unexpand` is all you really want, you can integrate it into the copying and assign it to a key or menu item using available mintty features.

**Comment by mintty** [comment]
On the other other hand, rxvt-unicode and lxterminal provide the feature, so I had another look, and in fact it's not too complicated to implement. I'm uploading an experimental patch, for now it's enabled only in combination with option `DispTab=true`.

**Comment by mintty** [comment]
Released 3.4.1.
