### ISSUE TITLE
OSC 4 should accept multiple parameter pairs

### ISSUE THREAD

**Issue by shoaniki** [mintty/mintty#1038]
Per xterm documentation for OSC 4:

> Any number of c/spec pairs may be given. [...] Because more than one pair of color number and specification can be given in one control sequence, xterm can make more than one reply.

And indeed we observe in xterm (and VTE, iTerm2, etc) that e.g. `^[]4;1;?;2;?^G` will return `^[]4;1;rgb:cdcd/0000/0000^G^[]4;2;rgb:0000/cdcd/0000^G`.

mintty (as of 3.4.0) only appears to support OSC 4 with a single pair: `^[]4;1;?;2;?^G` is ignored as unrecognised, and it is necessary to send `^[]4;1;?^G^[]4;2;?^G` etc.

Not a major problem in the grand scheme of things, but I figure it's worth reporting given mintty's avowed goal of xterm compatibility.

**Comment by mintty** [comment]
Likewise OSC 5, 104, 105, and 10 with an even trickier auto-increment.

**Comment by mintty** [comment]
Uploaded a tweak. It's not 100% consistent with xterm right now, as it does more. For resetting dynamic colors, multiple parameters are not specified. Thus the sequence `echo -e "\e]110;111^G"` does nothing in xterm but still resets the foreground colour in mintty.

**Comment by mintty** [comment]
Released 3.4.1.
