### ISSUE TITLE
Predefined sets of colour settings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#104]
```
There could be a small choice of predefined sets of colour settings, e.g.:

- white on black (default)
- black on white (xterm-style)
- green on black (retro)
- yellow on blue (rxvt)
- System colours (reads Windows settings)
```

Original issue reported on code.google.com by `andy.koppe` on 9 May 2009 at 7:35

**Comment by mintty** [comment]
Note: Since 2.2.4, colour schemes are supported with option `ThemeFile`. They can be limited to foreground, background, cursor if desired.
