### ISSUE TITLE
Is it possible to force the use of BoldColour?

### ISSUE THREAD

**Issue by rovf** [mintty/mintty#1040]
This is more of a question, than a change request, though if mintty does offer me this possibility, I would like it to be understood as a feature request:

I understand, that the BoldColour is used (provided that BoldAsColour is true) in those cases, where the output requires something being printed as bold, but the concrete version of bold (i.e. BoldRed or BoldYellow) can't be determined from the context.

My question is: How can I output something, which would force the BoldColour to be used, for instance to verify that the current setting is visually pleasant?

For instance (I'm using zsh) for testing that, i.e. the setting of Red is visually well to see against the current background, I can do use the zsh command

`print -P '%F{red}SOME TEXT%f'`

and _SOME TEXT_ will be printed in red. I can't do this for BoldColour obviously. I know of  course the RGB setting for the BoldColour, but the approach using the _print_ statement would me allow only to set colours by name or by their position in the colour pallette (for instance `%F(137)SOME TEXT%f`  for colour number 137), but not by RGB value.

**Comment by mintty** [comment]
Well, BoldColour is a global option and not a character attribute. You can combine bold and specific colour attributes for text, of course, and you can use RGB colour attributes. So I'm not quite sure what's missing here.

**Comment by rovf** [comment]
Not exactly. I do have explicitly set all colours including their bold variant. I have included an example of such a configuration file. As you see, I set `BoldColour` to a different value than the other colours.

Experiment shows that, for instance, when I display a `man` page, that part which is usually printed in bold (like the title of the described command), is shown using the value I have set for BoldColour, while - for instance. It is possible, but a bit cumbersome and not very elegant to open a man page for the sole purpose of seeing, how BoldColour looks, so I was asking whether there is a simpler way.

[mintty_conf_example.txt](https://github.com/mintty/mintty/files/5369885/mintty_conf_example.txt)

**Comment by mintty** [comment]
So you just want to activate the bold colour to see how it looks? Then simply put something in bold:
`echo -e "\e[1mbold text, using BoldColour if set\e[m"`

**Comment by rovf** [comment]
Thanks a lot! Now when you say it, it's obvious.  Actually, I will go with `print -P "%Bbold text, using BoldColour if set%b"`, which I find more readable, but in the end it produces of course the same escape sequence.

**Comment by avih** [comment]
You can display the bright color without the boldness by using the "AIX colors" (90-97), or the colors 8-16 at the 256 colors palette.

Example using the AIX colors (might not work in all other terminals):
```sh
for c in `seq 90 97`; do printf "\033[${c}mX\033[1mX\033[m "; done; echo
```

See https://en.wikipedia.org/wiki/ANSI_escape_code#SGR

The colors 8-16 of the 256 colors palette is more likely to work in other terminals (which support 256 colors):
```sh
for c in `seq 8 16`; do printf "\033[38;5;${c}mX\033[1mX\033[m "; done; echo
```

**Comment by mintty** [comment]
@avih: fixed range 8-16 to 8-15 in your comment; deleting this comment from issue.

**Comment by mintty** [comment]
As a side note, note a subtle difference between basic ANSI VGA colours 0..7 (SGR 30..37) and ANSI palette colours 0..7 (SGR 38;5;0..7): With BoldAsColours enabled and bold attribute set, the former would change colour but the latter don't.
