### ISSUE TITLE
can't minize windows in **Tab Mode**

### ISSUE THREAD

**Issue by cmeriaux** [mintty/mintty#1041]
can't minimize windows when **Tab Mode** is enabled and several tabs are opened.

Example: we have two tab:  Tab1 and Tab2

- active Tab1
- click minimize windows button. Tab1 is minimized but Tab2 is auto activated.
- click again minimize windows button to minimize tab2. Tab2 is minimized but tab1 is auto activated.
We are stucked in an infinite loop

Here is my config

```
TabBar=yes
SessionGeomSync=2
```

**Comment by mintty** [comment]
[I thought I had responded to this issue.]
Set level SessionGeomSync=3 or higher to make it work, as documented.

**Comment by cmeriaux** [comment]
Thanks for the feedback.
Just for the record man page recommend to use **2**
Here is the man:

>With setting TabBar, an interactive tabbar complements the virtual tabs mechanism. (It works like the session switcher available via extended context menu or title bar menu.)  
It is recommended to also set SessionGeomSync=2 or higher to achieve a
              tabbed window behaviour.
