### ISSUE TITLE
Formatted clipboard despite CopyAsRTF=no and CopyAsHTML=none

### ISSUE THREAD

**Issue by mrinmoyg** [mintty/mintty#1042]
Version 3.4

I have:
Columns=80
Rows=62
BackgroundColour=100,100,100
ForegroundColour=232,232,232
Font=Courier
FontHeight=8
FontWeight=400
FontIsBold=no
CursorType=block
RightClickAction=paste
SwitchShortcuts=yes
ZoomShortcuts=no
ClickTargetMod=off
ScrollMod=off
TrimSelection=no
CursorBlinks=no
Term=xterm-256color
BoldAsColour=no
BoldAsFont=yes
ThemeFile=xterm
BellType=0
ScrollbackLines=10000
FontSmoothing=default
CopyAsRTF=no
CopyAsHTML=16842752
AllowSetSelection=no
CopyOnSelect=yes

But still I see background color getting copied on selection/copy.

**Comment by mintty** [comment]
For issue reporting, it is generally appreciated to provide a "minimal test case", which would include cleaning the demonstrated configuration from irrelevant entries. The value for CopyAsHTML looks strange, by the way.
CopyAsHTML may well be the reason for formatted copying, actually. It cannot be reproduced, however, as you don't say how and to which application you copy.

**Comment by mrinmoyg** [comment]
Sure. Copying is from mintty terminal to outlook.

No manual configuration was done on the .minttyrc, this is what was generated based on "options" from 3.4 mintty.

CopyAsHTML is set to "None" in the options.

**Comment by mintty** [comment]
There must have gone something wrong in your config. Please change the value for CopyAsHTML and Save, change back and Save again.

**Comment by mintty** [comment]
Hold on, the value is not cleared by this procedure, which I'll analyse.
So please set the value to 0 manually and check the resulting behaviour.

**Comment by mrinmoyg** [comment]
Yes, when I manually set the "CopyAsHTML" to 0 in ~/.minttyrc and relaunch my terminal, the copy/paste from mintty to outlook works without formatting (i.e no background).

1 hint if it helps, "16842752" is 0x1010000, and when I change the value from None->Partial->Default->Full, the value just increments by 1, but the Most significant 2 octets remain 0x0101, where the lower 2 bytes changes properly.

**Comment by mintty** [comment]
Uploaded a fix for the misinterpretation of CopyAsHTML, thanks for helping debug this.
I have no idea how the extra 0101 would have come into your config, and the new version would still not clear that, but it won't interpret it anymore when copying.

**Comment by mintty** [comment]
Tweaked the fix. Bogus values would now be sanitized.

**Comment by mintty** [comment]
Released 3.4.1.
