### ISSUE TITLE
Document how to use mintty/wsltty + ConEmu to have tabbed mintty/wsltty?

### ISSUE THREAD

**Issue by awesomer** [mintty/mintty#1047]
(Wasn't sure whether to file this in the mintty or wsltty repo. Although I am a wsltty user, ultimately decided to file it in the main repo because it also applies to users of mintty.)

Prior relevant issues :

https://github.com/mintty/mintty/issues/8
and
https://github.com/mintty/mintty/issues/944

Both relate to mintty having tabbed support for multiple windows. When I figured out how to use wsltty in ConEmu, 944 hadn't been completed, and so there was no native tabbed support. Now there is native tabbed support, but my understanding is that there are still outstanding issues with the implementation. I have been using wsltty inside of ConEmu for about six months and have never noticed a single issue with it.

I'm not sure how content you are with the new tabbed feature or how much you care about people using mintty/wsltty within ConEmu, so, modulo that... might there still be value to the community to documenting how to use mintty/wsltty within ConEmu's tabbing? Existing users of ConEmu who use it to launch multiple different terminals (CMD, powershell, etc.) might also benefit?

All it requires is creating a ConEmu task with the following definition :

> -new_console:d:C:\Users\USERNAME C:\Users\USERNAME\AppData\Local\wsltty\bin\mintty.exe --WSL= --configdir="C:\Users\USERNAME\AppData\Roaming\wsltty" -~  -

**Comment by mintty** [comment]
I once considered this but when I tested with ConEmu, it wasn't a smooth experience, so I dropped the idea.
Now with mintty virtual tabs and tabbar support, there is really no need anymore to use ConEmu for mintty.
And since cygwin 3.1.0, it should even be possible to run cmd or PowerShell seamlessly in a mintty tab.
The wsltty release with tabbar support is however still pending, as there are a few other issues. I'd expect mintty and wsltty 3.4.1 to be released in one or two weeks.

**Comment by Biswa96** [comment]
mintty and ConEmu both are terminal emulator. Why would anyone run a terminal emulator insider another one? Also ConEmu already has tab feature. One can run wslbridge2 program in ConEmu to get same experience as wsltty.

**Comment by mintty** [comment]
I wouldn't call it the same experience since mintty is of course a much superior terminal :)
ConEmu does have a tab-capturing feature for GUI applications, so the whole terminal would run in this mode. I once tried it but the integration experience wasn't feeling too nice actually.

**Comment by awesomer** [comment]
@Biswa96 : As indicated in my initial comment, I used ConEmu to provide a tabbed experience for wsltty chronologically before mintty had its own tabbing. So the answer to your question is "because doing that gave me tabs."

@mintty : While I obviously don't disagree with your subjective experience, I wonder what problems you had with the integration? I am sincere when I say that I don't notice any issues whatsoever, especially compared to vanilla ConEmu's problems with, for example, correctly emulating wide characters for mosh.

**Comment by mintty** [comment]
Released wsltty 3.4.1 with tabbar support.
