### ISSUE TITLE
Feature request : Timestamp 

### ISSUE THREAD

**Issue by CaptainLol** [mintty/mintty#1049]
Hello, 

would it be possible to add a "timestamp" feature to help readability when scrolling back? 

Regards

**Comment by Biswa96** [comment]
Just curious what the "timestamp" means. Do you any other terminal emulator which has that "timestamp" feature?

**Comment by Biswa96** [comment]
Just curious what the "timestamp" means. Do you know any other terminal emulator which has that "timestamp" feature?

**Comment by CaptainLol** [comment]
you're right. I mean [DATE - HOUR - MIN - SEC] => [22/10/2020 - 14h41:01] 

I don't know of any other terminal emulator with such a feature. But I know i'm not alone with this kind of need : [askubuntu](https://askubuntu.com/questions/193416/adding-timestamps-to-terminal-prompts)

I hope it helps.

**Comment by Biswa96** [comment]
The prompt text is a feature of shell (for example, bash, zsh, sh etc.). Whereas mintty is a terminal emulator. By settings `PS1` environment variable you can change prompt text. Try to add the `export PS1` command in the shell rc file (e.g. `.bashrc` for bash).

**Comment by Biswa96** [comment]
The prompt text is a feature of shell (for example, bash, zsh, sh etc.). Whereas mintty is a terminal emulator. By settings `PS1` environment variable you can change prompt text. Try to add an command to export `PS1` variable in the shell rc file (e.g. `.bashrc` for bash). Here is bash manual page https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html.

**Comment by CaptainLol** [comment]
thanks
