### ISSUE TITLE
New Feature request: get snapshot of full mintty terminal

### ISSUE THREAD

**Issue by KptainBiwouak** [mintty/mintty#1051]
Hi,

Thanks a lot for your efforts to develop and support Mintty?

Could it be possible to generate snapshots (PNG or SVG format) from mintty terminal from batch script started itself from mintty without calling an other tool? Is there some key combinations callable from script?

Thanks in advance,

**Comment by mintty** [comment]
An image snapshot feature is already available in the extended context menu: Ctrl+right-click, "Save as Image".

**Comment by KptainBiwouak** [comment]
Thanks for your reply, but the request is different.

The idea is to add the capability to get a full snapshot of the window
during some script execution in order to get proof of execution for
regression usage for example to include in data report what went wrong. It
is possible to parse log file to do that but most of the time
rendering features (like colors, etc) are lost.
then request would be to simulate "Ctrl + Save as" from script itself.

Do you understand better what I mean?

**Comment by mintty** [comment]
That's already available for HTML format, sequence Media Copy 10 (`ESC[10i`).
I've added a sequence for PNG format screen dump as well, that shall be Media Copy 12 (`ESC[10i`).

**Comment by mintty** [comment]
Released 3.4.2.
