### ISSUE TITLE
Mintty not display powerline character after update to 3.4.1

### ISSUE THREAD

**Issue by meav** [mintty/mintty#1052]
Mintty display all powerline character with version 3.4.0. After update to version 3.4.1; mintty not display powerline character anymore.
This is screenshot when display this file with vim:

https://github.com/just3ws/nerd-font-cheatsheets/blob/master/devicons.md

![Capture](https://user-images.githubusercontent.com/29623675/97185408-95e02d80-17d2-11eb-99e4-ba21a604e116.PNG)

This is my .minttyrc (It not change between 3.4.0 and 3.4.1):

Term=xterm-256color
Font=MesloLGS NF
FontHeight=13
BoldAsFont=yes
BoldAsColour=yes
FontSmoothing=full

How can I fix this?
Sorry for my bad english and thanks for reading

**Comment by mintty** [comment]
Cannot reproduce. I see pretty glyphs with that font. Something else must have changed on your system.

**Comment by meav** [comment]
I backed to version 3.4.0 -> issue still appear.
So, I reinstall cygwin and this issue disappear.
I not understand.
