### ISSUE TITLE
In v3.4.2, LANG in the CJK area will cause the tmux dividing line to display abnormally

### ISSUE THREAD

**Issue by GeekDuanLian** [mintty/mintty#1057]
![image](https://user-images.githubusercontent.com/6257434/98220153-dab15480-1f88-11eb-82f2-965f56efbaba.png)
![image](https://user-images.githubusercontent.com/6257434/98220179-e3a22600-1f88-11eb-9e1d-e9643092b92e.png)
![image](https://user-images.githubusercontent.com/6257434/98220193-e9980700-1f88-11eb-8430-6dbb72720edd.png)
![image](https://user-images.githubusercontent.com/6257434/98220198-ebfa6100-1f88-11eb-878e-bb5b8e8b5693.png)

**Comment by mintty** [comment]
See https://github.com/mintty/mintty/issues/1050#issuecomment-716127545 for an explanation. Workaround under consideration.

**Comment by GeekDuanLian** [comment]
OK, I solved the problem with `-o OldLocale=yes`, thanks.

**Comment by mintty** [comment]
Released 3.4.3.
