### ISSUE TITLE
I make some enhancements,new tab follow fatty,Win+hotkey,partline etc

### ISSUE THREAD

**Issue by qdzhaov** [mintty/mintty#1059]
I make some enhancements ,at [gitee](https://gitee.com/qdzhaov/mintty) ,
can your use it? sample:
[sample image](https://gitee.com/qdzhaov/mintty/raw/master/sample.png "sample")
hotkey Optimize not complete yet.

### enhancements ###
change orgin wintab to new Tab followed fatty,

add indicator,used hiade tabbar

Add control mode,So we can release many hotkeys,it's helpfull for tmux+vim,see below

Optimize HotKey,not complete,fast hotkey,easyly [un]define by your self

Surport Global HotKey

Surport Win+hotkey use SetWindowsHookExW(WH_KEYBOARD_LL,...)

surport partline last line can be partline,usrful for tmux
###  win hotkey 
win+Left        prevtab
win+right       nexttab
win+Shift+Left  tabmovetoprev
win+Shift+Right tabmovetoNext

**Comment by mintty** [comment]
Thanks for your contribution, which isn't "some enhancements" but adds a huge amount of code. Therefore it will be tricky to sort this out and check what can be integrated, and understand the new use cases in the first place.
Actually I am concerned by the introduction of struct STab which seems to add parameters to a bunch of functions in many source files. This is particularly what I did _not_ want to have in the code, as it adds stability risks, where the current terminal code works strictly on one virtual terminal, not multiple ones (see respective comments in the tab issues). I'd rather appreciate to stay with the current paradigm of tab interaction, strictly via messages and subsequent adaptation.

**Comment by mintty** [comment]
[Apparently I forgot to send my previous comment this morning, sorry.]
Running your version, it suspends itself to the terminal background, then it does not show a tab bar at all. Instead it overlays the terminal text area with some disturbing 0/1 indication.
Keyboard shortcuts can be assigned in mintty already, if you added new functions, please describe them.
The idea and function of "partline" is totally unclear.

If you want to improve on mintty, please go in comprehensible, well-described and convincing steps.

**Comment by qdzhaov** [comment]
Thank for you reply,
I'm sorry,My English is very poor,It may bother you.
last version is temporary  version,Basically finished what I wanted now.
Hope to test it again.
github is too slow,so I use gitee,the git url is https://gitee.com/qdzhaov/mintty,
I work branch is zhw,branch master is follow you,I add [mintty.exe](https://gitee.com/qdzhaov/mintty/raw/zhw/mintty.exe)  for you at branch zhw;

Thank you again.

== comments: 
**surport partline last line can be partline,usrful for tmux:**
because no divide exactly  ,it offten has a black borer at bottom of screen,it is discomfort ,
 somtimes we not need whole line,such as when use tmux,it will give me 1 more line.
or move part line at top?

**Control config dialog fontsize:**
the font of config dialog is ver small at my computer,it disturb me.
add case WM_SETFONT,WM_GETFONT code

**Surport Win+key as shortcuts key**,all confict key with windows,will overide it.
I use Win+left/right control tab in mac os,& linux,mintty can do too.

**Surport WSL/CYGWIN/COMMAND/POWERSHELL session**
I found the function in fluent terminal,so I try it.

**optimize shortcuts key:**
the key process code(win_key_down) is diturb me when I read putty code.
now I optimized it,and make rule for shutcuts key,you need not seach shortcut code,
user define shortcuts key have same  effcient.

**+ surport multiple Tab followed fatty,**
I like it,but it  is outdated. The new tab is not like mintty.
So I merged it.

**Map S+F12 to paste**
In my computer insert and F12 at same key,insert equal Fn+F12,fn key be locked,

**Comment by mintty** [comment]
Again, the program puts itself into suspend mode initially; when restarted, it now even crashes. This is not something I can test.
Comments:
* partial bottom line: When starting a mintty line, it adjuts its size evenly to the configure number of rows. There are cases, though, with additional bottom gap, e.g. after zooming the font size (and not using synchronous window zooming), full-screen and some others. However, I don't see this critical, and providing a partial line is not a typical terminal feauture, and not a good feature in my opinion.
* various keyboard shortcuts: This is possible already with a mintty feature (option KeyFunctions), so I don't see why any new hard-coded shortcuts should be introduced.
* Options menu font size: I could assess this if there were a dedicated patch for this feature, or a working demo.
* cmd/powershell sessions: This is already possible, option SessionCommands.
* multiple tabs: Those are already supported, no idea what additional value could be taken from fatty. Anyway, as stated before, interweaving tabs implementation in the code (as done by the struct STab) is a stability risk and not accepted.

**Comment by qdzhaov** [comment]
Thank you.

**Comment by mintty** [comment]
Concerning font size (and font) of the options menu: If you increase the size, you'll also need to increase the geometry of the dialog box, or text will overflow in its present space. I'll look into this, thanks for the suggestion.

**Comment by mintty** [comment]
Uploaded customizable font for the Options dialog.

**Comment by mintty** [comment]
Released 3.4.4.
