### ISSUE TITLE
How to use mintty as a ssh client(like putty)?

### ISSUE THREAD

**Issue by netjune** [mintty/mintty#1060]
I want to use mitty to ssh to my remote linux machine and run emacs on it.

I run the following command:
`mintty.exe -h always ssh test@192.168.1.1 /bin/start_emacs.sh`
and I get error message like this:
```
warning: agent returned different signature type ssh-rsa (expected rsa-sha2-512)
zsh:1: no such file or directory: D:/Apps/Git/usr/bin/start_emacs.sh
ssh.exe: Exit 127.
```

I don't known who translate `/bin/start_emacs.sh` to `D:/Apps/Git/usr/bin/start_emacs.sh`

Is it possible to do this? What is the right command?

**Comment by Biswa96** [comment]
> How to use mintty as a ssh client(like putty)?

mintty is a terminal emulator program. You need a different program (here SSH client) to be executed in terminal emulator.

> and I get error message like this

The error message is not related to mintty. Try to copy paste the warning in your favourite search website, you'll get some answers. PowerShell/Win32-OpenSSH repository has some similar issue with your provided warning.

**Comment by mintty** [comment]
Also, when running in cygwin with ssh installed, this should work. Maybe it's not cygwin ssh? What does `type ssh` say?

**Comment by netjune** [comment]
> 
> 
> Also, when running in cygwin with ssh installed, this should work. Maybe it's not cygwin ssh? What does `type ssh` say?

The mintty.exe and ssh.exe are in the git for windows package (version: 2.29).

I just tried another command:
```
mintty.exe -h always bash -c "ssh -tt jun@192.168.1.80"
```
and mintty displays the following message and nothing else:
```
Warning: Permanently added '192.168.1.80' (ECDSA) to the list of known hosts.
```

**Comment by mintty** [comment]
So try ssh in your current shell, without wrapping mintty. Also

> What does `type ssh` say?

**Comment by netjune** [comment]
> 
> 
> So try ssh in your current shell, without wrapping mintty. Also
> 
It works. I use the following command:
`ssh.exe -tt jun@192.168.1.80 /bin/emacs.sh`

> > What does `type ssh` say?
It gives an error message: `系统找不到指定的文件。` (Can't find the file.)

While `type ssh.exe` prints many mess codes.

**Comment by mintty** [comment]
So it's not git ssh, maybe its installation got corrupted.
Maybe your PATH is different after starting mintty, caused by your profiles?
Anyway, as Biswa said, it's not a terminal issue.

**Comment by netjune** [comment]
> 
> 
> So it's not git ssh, maybe its installation got corrupted.
> Maybe your PATH is different after starting mintty, caused by your profiles?
> Anyway, as Biswa said, it's not a terminal issue.

I tried with absolute path. It seems that the ssh.exe builtin with windows 10 also works without mintty.
`C:\Windows\System32\OpenSSH\ssh.exe -tt jun@192.168.1.80 /bin/emacs.sh`
Here it works well as the ssh.exe in git.

But it doesn't work with mintty. The following command doesn't work.
`d:\apps\git\usr\bin\mintty.exe -h always C:\Windows\System32\OpenSSH\ssh.exe -tt jun@192.168.1.80 /bin/emacs.sh`

And ssh.exe in git works well with mintty. The following command works.
`d:\apps\git\usr\bin\mintty.exe -h always d:\apps\git\usr\bin\ssh.exe -tt jun@192.168.1.80 /bin/emacs.sh`

There is something magic.

I have got the working command finally. Thank you.

**Comment by mintty** [comment]
MSYS2 (which Git for Windows is based on) used to disable "ConPTY" support (I don't know whether they still do) which explains that some native Windows programs do not work.
