### ISSUE TITLE
Pop-up window for redirected stderr; stdout lost

### ISSUE THREAD

**Issue by AndreBleau** [mintty/mintty#1062]
Hi Thomas,

A problem was reported on the Cygwin mailing list and some investigation seems to lead to mintty.

Configuration:
gcc (GCC) 10.2.0
CYGWIN_NT-10.0 XXX 3.1.7(0.340/5/3) 2020-08-22 17:48 x86_64 Cygwin
mintty 3.4.1 (x86_64-pc-cygwin)
CYGWIN variable is empty.

Simple test program: assert.cpp
#include <assert.h>
int main() {
  assert(false);
}

Compiled with: 
gcc assert.cpp

./a.exe < /dev/null > output.txt 2>&1

I get a message box pop-up saying:

    Failed assertion
        false
    at line 3 of file assert.cpp
    in function int main()

Also: output.txt is empty

If I omit either the stdin or the stderr redirection, the program behaves
as desired with no dialog box, and output.txt contains the expected error message.

The bug is OS specific; it occurs in Windows 10.
It seems the bug is related to pseudo-console support; that explains why it is Windows 10 specific.

Experiment:

CYGWIN=disable_pcon /usr/bin/mintty &

In the newly created window:

$ ./a.exe </dev/null >output.txt 2>&1
Aborted (core dumped)

No message box popup.

$ cat output.txt
assertion "false" failed: file "assert.cpp", line 3, function: int main()

so it works as expected in that case.

In a CMD Window, with empty CYGWIN env variable:

set path=%PATH%D:\Cygwin\bin;
a.exe <NUL: >outcmd.txt 2>&1
      1 [main] a 759 cygwin_exception::open_stackdumpfile: Dumping stack trace to a.exe.stackdump
type outcmd.txt
assertion "false" failed: file "assert.cpp", line 3, function: int main()
      1 [main] a 759 cygwin_exception::open_stackdumpfile: Dumping stack trace to a.exe.stackdump

so it works as expected in that case too.

Regards,

- André Bleau

**Comment by mintty** [comment]
Quick generic answer: if it's caused by ConPTY support, it's not related to mintty; also mintty never shows any popups.
Funny thing, though, but really: assert isn't handled by the terminal.
