### ISSUE TITLE
VT Torture Test fails again

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#1064]
Hey as a further to https://github.com/mintty/mintty/issues/551 and https://github.com/mintty/mintty/issues/915 which were solved it seems at least one irregularity has creeped back in:
![image](https://user-images.githubusercontent.com/2286713/99920283-5990e600-2d1a-11eb-910f-c9294a64c38c.png)

The last line isn't rendered whereas in 551 a passing terminal renders the last line (look at 551 for an example image).

**Comment by mintty** [comment]
I don't see the difference except that the subsequent prompt covers part of the test output.

**Comment by ElvenSpellmaker** [comment]
I'm not sure the prompt should get covered up, the test should end with a newline as it used to previously in the images in #551 or #915

**Comment by mintty** [comment]
Please check your test file. The one I have ends with an absolute position (CSI H) into line 22, the last "`abc..." line, and a final newline which would thereby position onto the trailer line.

**Comment by mintty** [comment]
Note that the trailer line ("This test created...") begins with 3 spaces, possibly intended to leave room for a _short_ prompt.

**Comment by ElvenSpellmaker** [comment]
![image](https://user-images.githubusercontent.com/2286713/101653929-d240b380-3a37-11eb-8474-f7a71c14a3a8.png)
Does the file move the prompt up a line even though the file ends in a newline? 🤔

**Comment by ElvenSpellmaker** [comment]
Yeah CSI H is move up?

**Comment by mintty** [comment]
CSI H is absolute cursor position. The test file is apparently set up to fit into 24 lines terminal configuration without scrolling.
