### ISSUE TITLE
Vim: Ctrl-V U******** does not work

### ISSUE THREAD

**Issue by Mariusz-W** [mintty/mintty#1066]
The mechanism in Vim to input a Unicode character from Supplemental Planes (in UTF-8 encoded by a 4-byte sequence) is by pressing in the insert mode **Ctrl-V** , then pressing **U** , and finally typing 8 hex digits comprising the code point of the character.

**What happens:** after I press **U** , the capital letter **U** is instantly echoed to the screen and I am back in the straight insert mode.

**Expected behavior:** the **U** I press after pressing **Ctrl-V** should not be echoed, neither the next 8 hex digits I type. After I make 9 consecutive keystrokes entering **U** and the digits, the glyph of the character should appear in the editor terminal window. This is the expected behavior I am accustomed to when the Vim was compiled with the full Unicode support.

All the binaries are Cygwin:
mintty 3.4.3-1
vim 8.2.0486-1
cygwin 3.1.7-1
bash 4.4.12-3

Exactly the same binaries but a different terminal application (the up-to date WindowsTerminal) : Ctrl-V U********  behaves as expected which suggests that this is not just a bug in the current binaries of Cygwin Vim. 

I have nothing fancy in my .minttyrc , just whatever was automatically generated.

This is for me an extremely awkward issue, as I am editing files with many characters from Supplemental Planes on a daily basis, and **mintty** has been my terminal application of choice for many years.

**Comment by mintty** [comment]
> I have nothing fancy in my .minttyrc

I would have asked, there is CtrlExchangeShift, please check anyway.
Apart from that, why do you think this would have anything to do with the terminal?

**Comment by Mariusz-W** [comment]
To answer your questions:

1) I don’t have anything related to CtrlExchangeShift in my .minttyrc . Is there any other place where this can be set?

2) This behavior occurs only in mintty. Exactly the same binaries (Cygwin, Vim invoked in Bash) behave correctly in WindowsTerminal.

When I first noticed that behavior (it was in the Summer) I checked whether there were any reports of it in Vim. I didn’t find any.

I would like to add to my report that the similar mechanism, **Ctrl-V u****** , used to enter Unicode characters encoded by a single 16-bit sequence in UTF-16 (note the lower case ‘u’ followed by 4, instead of 8, hex digits), works as expected.

**Comment by k-takata** [comment]
I confirmed that this occurs on mintty+Vim, and doesn't occur when the modifyOthersKey feature is disabled on Vim. (E.g. `vim --cmd "set t_TI= t_TE="`)
So, this should be a Vim issue. Please report this to the Vim project.

**Comment by Mariusz-W** [comment]
> vim --cmd "set t_TI= t_TE="

For me this doesn’t make a difference.  ‘U’ is still being echoed when I press it after entering Ctrl-V .

Note that both in mintty and in WindowsTerminal I am using the same Vim subject to exactly the same invocation and initialization. So this cannot be just this particular Cygwin Vim binary issue. The problem could have been introduced indeed in Cygwin Vim by makigg a change that conflicts with how mintty processes certain combinations of Ctrl key-strokes

**Comment by k-takata** [comment]
> For me this doesn’t make a difference. ‘U’ is still being echoed when I press it after entering Ctrl-V .

Then, how about `vim --clean --cmd "set t_TI= t_TE="`? (See `:help modifyOtherKeys` for detail.)

> Note that both in mintty and in WindowsTerminal I am using the same Vim subject to exactly the same invocation and initialization.

I don't think Windows Terminal supports modifyOtherKeys.

**Comment by Mariusz-W** [comment]
Thank you very much for pointing us in the right direction. The actual solution is to execute in Vim:

**:let &t_TI = ""**

and (important!) , execute afterwards an ex shell command, like **:!ls** . Only afterwards, the Vim binding for the xterm

**let &t_TI = "\<Esc>[>4;2m"**

is disabled. On a permanent basis, for Vim editing in mintty, one has to add

**let &t_TI = ""**

to ~/.vimrc .

I confirm that in either case **Ctrl-V U********** behaves as expected. I didn’t touch the t_TI settings, as they are, likely, irrelevant for the issue at hand.

The corresponding section of /usr/share/vim/vim82/doc/map.txt to which Mr. Takata kindly referred me contains an important passage that I would like the developer of mintty to read and consider:

_1.11 MAPPING IN modifyOtherKeys mode                    modifyOtherKeys

**Xterm and a few other terminals can be put in a mode where keys with modifiers
are sent with a special escape code.**  Vim recognizes these codes and can then
make a difference between CTRL-H and Backspace, even when Backspace sends the
character 8.  And many more special keys.

**For xterm modifyOtherKeys is enabled in the builtin termcap entry.**  If this is
not used you can enable modifyOtherKeys with these lines in your vimrc:
      let &t_TI = "\<Esc>[>4;2m"
      let &t_TE = "\<Esc>[>4;m"_

From the opening pragraph I infer that the developer of mintty may have indeed “put the terminal in a mode where keys with modifiers are sent with a special escape code”.

The developers of WindowsTerminal with whom I have been in touch regarding some of their own issues, informed me that they aimed at closely emulating xterm . Nevertheless, Cygwin Vim didn’t exhibit the problem I reported when used in WindowsTerminal.

**Comment by mintty** [comment]
If vim uses modifyOtherKeys mode, it should implement precautions to make cases of control characters still work. So this is a vim bug, please report there. Closing here.

**Comment by Mariusz-W** [comment]
I would like to take an opportunity to ask the developer of mintty how does mintty avoids the opitfall into which WindowsTerminal falls. Pasting into the Cygwin Bash window a character encoded in UTF-16 as a surrogate pair (i.e., precisely a character from one of the Supplemental Planes with which my report is concerned), results with exactly one of the two surrogates being pasted, the other is lost. This issue is critical for anybody in need of pasting strings or whole texts containing higher Unicode characters. It would be lovely to know about how mintty is able to properly handle the clipboard containing such characters.

**Comment by mintty** [comment]
Assuming you run mintty in UTF-8 encoding, it simply handles all pasted contents as UTF-8.

**Comment by Mariusz-W** [comment]
> 
> 
> If vim uses modifyOtherKeys mode, it should implement precautions to make cases of control characters still work. So this is a vim bug, please report there. Closing here.

From their own documentation it is clear that what they do they consider not not a bug in Vim, but a valid “precaution” to solve some other terminal related issues. Certainly, making Vim team aware of this particular problem is advisable, and one of thus should certainly do that. I am glad we found a practical solution. Mintty being a wonderful utility (hats off to its developer), deserves all such issues to be cleared and its user base to be informed about them.

**Comment by Mariusz-W** [comment]
> 
> 
> Assuming you run mintty in UTF-8 encoding, it simply handles all pasted contents as UTF-8.

Yes, of course, I do. WindowsTerminal Cygwin Bash is also operating in the same encoding, yet the WindowsTerminal team thinks that the problem originates on the Cygwin side, not on their own. They say that mintty avoids this “surrogate pair pitfall” because of some “preferential treatment” by the Cygwin developers who may be sharing with the developer of mintty some important details that are not known to them.

**Comment by Mariusz-W** [comment]
> 
> 
> Assuming you run mintty in UTF-8 encoding, **it simply handles all pasted contents as UTF-8.**

The issue seems to be not with how does the pasted contents is handled, but whether the contents is properly passed from the Windows clipboard to the terminal. What part of Cygwin does stand between the system clipboard and mintty when the contents is being pasted? There is no similar issue with copying higher Unicode characters in WIndowsTerminal Cygwin Bash. The contents reaches the clipboard uncorrupted.

**Comment by mintty** [comment]
> What part of Cygwin does stand between the system clipboard and mintty when the contents is being pasted?

None. Mintty directly reads from the Windows clipboard and converts to the terminal encoding (mostly UTF-8).

**Comment by Mariusz-W** [comment]
Does that mean that mintty itself handles the whole conversion process, from the moment it receives the contents of the clipboard to the moment it appears in the terminal window?

**Comment by mintty** [comment]
Yes, sure. And I don't know from your description what kind of problem other terminals might have.
Do they paste UTF-16 (which would be very buggy) or UTF-8-encoded separate surrogates?

**Comment by Mariusz-W** [comment]
**An addition to my original report:** The issue I described does not occur if mintty has the Terminal Type declared as **mintty** . This is why I didn’t detect the issue earlier. I recall changing the Terminal Type early in the Summer because remote login sessions to Linux servers did not recognize **mintty** as a valid terminal type, and were confusing the remote shell. This is why I changed manually the Terminal Type from **mintty** to **xterm-256color**. ccoridng to my test, the issue occurs for all **xterm-*** Terminal Types in mintty.

**Comment by mintty** [comment]
Which indicates that vim triggers its usage of the modifyOtherKeys mode by the value of TERM.

**Comment by k-takata** [comment]
I opened an issue here: https://github.com/vim/vim/issues/7413.

**Comment by k-takata** [comment]
Fixed in Vim 8.2.2084.

**Comment by Mariusz-W** [comment]
> 
> 
> Which indicates that vim triggers its usage of the modifyOtherKeys mode by the value of TERM.

It certainly does. They state this explicitly in the documentation.

**Comment by Mariusz-W** [comment]
> 
> 
> Fixed in Vim 8.2.2084.

Big Thank You!

**Comment by Mariusz-W** [comment]
> 
> 
> Yes, sure. And I don't know from your description what kind of problem other terminals might have.
> Do they paste UTF-16 (which would be very buggy) or UTF-8-encoded separate surrogates?

I don’t know the mechanism they use. They provided no details. The issue with pasting (no issues with copying) in Cygwin Bash running in WIndowsTerminal, that when one copies a 4-byte Unicode character, what appears in the file, when editing the file with vim, or on the command line, when pasting into the command-line, is one of the two 16-bit surrogates of the character when encoded in UTF-16. This may be an indication that WindowsTerminal passes the surrogate pair “raw”, so to speak, to Cygwin, and in the process one surrogate is lost. My discussion with one of the the developers of WindowsTerminal regarding this and related issues are here:

https://github.com/microsoft/terminal/issues/8302#issuecomment-730899790

**Comment by mintty** [comment]
> microsoft/terminal#8302 (comment) His claim, after some debugging tests, is that WIndowsTerminal passes both 16-bit surrogates, and thus the problem is on the Cygwin side.

The Cygwin console handler code does not handle this case. It will be moderate effort to provide a patch for it, once I find the time...
In the meanwhile, you might like to report it to the cygwin mailing list.

**Comment by Mariusz-W** [comment]
> 
> The Cygwin console handler code **does not handle this case**. It will be moderate effort to provide a patch for it, once I find the time...
> In the meanwhile, you might like to report it to the cygwin mailing list.

You mean by this, that “(t)he Cygwin console handler code” does not handle characters that Windows encodes as surrogate pairs? If this is the reason why pasting higher Unicode characters in WindowsTerminal Cygwin Bash is completely broken, then this indeed needs attention of Cygwin developers. Enormous amount of useful stuff is now in the first Supplemental Plane. All the Mathematical alphabets, and quite a lot of symbols. Additionally, the majority of ancient scripts necessary for serious philological work are there.
