### ISSUE TITLE
Install Font for All Users

### ISSUE THREAD

**Issue by buko** [mintty/mintty#1068]
This doesn't seem to be a documented bug. Maybe it's not a bug at all but I've noticed odd behavior.

In the latest Windows 10 (Windows 20H2) Adminstrator accounts have the option to 'Install' a font or to 'Install For All Users'. It looks like if you select 'Install for all Users' the font won't show up in mintty's font selection dialog. If you reinstall font but this time just do 'Install' it will show up.

**Comment by mintty** [comment]
This is weird but most certainly not a mintty issue. Mintty can only access the fonts that Windows provides it.
As a side note, since 3.4.1, there is also dynamic installation of temporary fonts, per session.

**Comment by buko** [comment]
I'm not API mintty uses to retrieve fonts but it seems in the recent past (~2018) Windows provided the ability to install system fonts and per-user fonts but there's no single unified to retrieve all of them. Other projects have tackled this in interesting way. See (matplotlib's approach to detecting all the fonts available to a user)[https://github.com/matplotlib/matplotlib/issues/12954/].

What I find strange is that mintty doesn't see system fronts but does see user fonts. Anyways even if it's not easy to fix it's worth documenting this issue. This has actually bugged me for years and I only stumbled upon the reason for the behavior today. Until now I thought it was due to certain fonts not being marked as monospace fonts.

**Comment by mintty** [comment]
Please check your original description, is it perhaps the wrong way? According to the referred issue, "Installing for all users" is the solution, according to your description, it's the problem.

**Comment by mintty** [comment]
Mintty uses either the system font choosing dialog, invoked with ChooseFont, or an internal font chooser (setting `FontMenu=0`) using function EnumFontFamilies. If there is anything that could be done via parameters to those functions to get those fonts listed, please anyone tell it here.

**Comment by mintty** [comment]
Closing as no evidence of a bug was demonstrated.

**Comment by alcm-b** [comment]
> "Installing for all users" is the solution

In case if you not have enough permissions to install your font for all users, there is a workaround.

I found out that mintty can in fact use the 'missing' font - it simply is not listed in the dialog window. Editing `.minttyrc` directly fixes the problem:

- In Windows settings, find the name of the font that is missing 
- Update `Font` option in `.minttyrc`: 

`Font=Consolas NF`
