### ISSUE TITLE
Transparency bug in Tabs is a feature for Glass

### ISSUE THREAD

**Issue by rbreaves** [mintty/mintty#1069]
So I noticed this bug the other day where the last 2 stacked tabs render on top of each other if transparency is enabled.. Kinda annoying, but then when I saw the broken state of the Glass transparency feature... I figured I could make 2 broken things work positively for each other.. Perhaps we can do something a little more official and allow us to set the background color of the tabs/tab bar?

![image](https://user-images.githubusercontent.com/10969616/101271236-91e6ea00-3746-11eb-8b64-18e0cbd4efc1.png)

**Comment by rbreaves** [comment]
I forgot to mention that I opened a couple of the tabs with Transparency set to Glass and the last tab set to medium and then I toggled back to the transparent tabs.

So in a more practical sense we'd need to instantiate one mintty instance using a semi transparent setting of Low, Medium or High and then the rest using glass and always stack each of the tabs on the semi transparent pane. Not sure if the author or another dev wants to spend the time working on this or not - but it looks like a very doable thing and can probably be done without running an entirely additional shell session I'd imagine.

**Comment by mintty** [comment]
Transparency with tabs does not really work now, the bottom tabs should rather be hidden. This needs some implementation (perhaps by @k-takata?).
Glass mode does not really work at all, that's why it was removed from the Options dialog in 3.1.5.

**Comment by mintty** [comment]
Implemented tab management, including tab transparency support. Available in the repository, testing is appreciated.

**Comment by mintty** [comment]
Release 3.6.5, enabling transparency in tab sets.
