### ISSUE TITLE
OSC12 Can't Support The 48bit  Hex Color String

### ISSUE THREAD

**Issue by Johnson9009** [mintty/mintty#1072]
I found this issue after I add dynamic cursor color to my Emacs configuration, it use the OSC12 to change the cursor color dynamically, the Emacs function give out 48bit hex color string, e.g., `#ffffafaf0000`, the 24bit hex color string of this color is `#ffaf00`, I found the cursor color is changed correctly when I use XTerm, but if I use mintty the color will wrong.
- **mintty**
![image](https://user-images.githubusercontent.com/19802523/102594877-c187f000-4151-11eb-9516-aea04909eb78.png)
- **XTerm**
![image](https://user-images.githubusercontent.com/19802523/102595974-75d64600-4153-11eb-8870-97430ee0e2d6.png)

After read the code I found we only support the 24bit hex color string now, if the hex color string is 48bit, then below line of code will success, but it get the wrong color `#ffffaf`, so the cursor color is changed to the wrong color.
https://github.com/mintty/mintty/blob/6970814e5892317e7054bfcf2ca4bb6870bb5e22/src/config.c#L827

**Comment by mintty** [comment]
Released 3.4.4.
