### ISSUE TITLE
Word wrap counter doesn't ignore ANSI Escape Codes

### ISSUE THREAD

**Issue by RobFro96** [mintty/mintty#1076]
I am using Git Bash on Windows 10 with mintty. I have ticked enable experimental support for pseudo consoles.
I have found out, that mintty has problems when working with ANSI escape characters for colors and text styles: the output has a line-break in the middle of the screen. I think your word wrapping algorithm doesn't ignore the escape characters. That is why the line break happens to early.
A test code for Git Bash and interactive python shell: `$ python`
```python
>>> print("\033[0m\033[0m\033[0m\033[0m\033[0m\033[0m\033[0m\033[0m\033[0mLorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata")
```

Output, as you can see, the first line is wrapped to early:
```
Lorem ipsum dolor sit amet, consetetur sadip
scing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna al
iquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et e
a rebum. Stet clita kasd gubergren, no sea takimata
```

**Comment by mintty** [comment]
Mintty never wraps output before the visual end of the line. You can verify with terminal logging (`mintty --log logfile`) that something else must be happening. I suspect some ConPTY interference due to the instance that you're lilkely running a Windows version of python. With cygwin python, output appears as would be expected.

**Comment by RobFro96** [comment]
Thank you for your fast response!

**Comment by RobFro96** [comment]
Just for your information: Using https://pypi.org/project/coloredlogs/ and logging.info(...) solved my issue - running a Windows version of python and Git Bash.
- Can't explain why.
