### ISSUE TITLE
Characters become bold unexpectedly

### ISSUE THREAD

**Issue by xcdxcdxcd** [mintty/mintty#1078]
Hi there, I'm using mintty and zsh for my terminal on win and characters rendered bold unexpectedly. 

stage 1
---
I set FontAsColour=yes while FontAsBold=no, mintty behaivoured as it should.
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105001879-65273180-5a6b-11eb-9a5b-fa8a6046174d.png)

stage 2
---
However, if I start a win program, chars become bold unexpectedly:
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105002005-96076680-5a6b-11eb-89b7-eecbb27385fd.png)
After that, if I restart a win program, it goes back to normal.
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105002061-acadbd80-5a6b-11eb-9469-5af8b5e01903.png)

Also, if I clear the terminal, it won't reproduce
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105002123-c3ecab00-5a6b-11eb-8073-e25ffc8ec844.png)

stage 3
---

The weirdest part is that if I start a cygwin command, it won't happen.....
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105002470-4c6b4b80-5a6c-11eb-9c82-9dfd3ac0c232.png)

my settings
---
Here's my .minttyrc

> Font=MesloLGS NF
FontHeight=10
FontSmoothing=full
CursorType=underscore
CharNarrowing=50
Title=Terminal
BellType=0
ConfirmExit=no
ScrollbackLines=100000
MiddleClickAction=void
RightClickAction=paste
Locale=en_US
Charset=UTF-8
BackgroundColour=40,40,40
ForegroundColour=162,162,162
CursorColour=162,162,162
Black=85,85,85
BoldBlack=136,136,136
Red=156,53,40
BoldRed=214,73,55
Green=97,188,59
BoldGreen=134,223,93
Yellow=243,180,58
BoldYellow=253,215,90
Blue=13,104,168
BoldBlue=15,117,189
Magenta=116,69,96
BoldMagenta=158,94,131
Cyan=40,142,156
BoldCyan=55,195,214
White=162,162,162
BoldWhite=249,249,249

And I'm using `MesloLGS NF Regular` as font.
&emsp;
The version is `3.4.4` as shown below
`screenshot:`
![image](https://user-images.githubusercontent.com/27773867/105002967-02369a00-5a6d-11eb-8206-f993f0cdd1a9.png)

---

Sorry to bother you(since I've been viewing mintty's issues about font rendering, and I fully understand it's a quite complicated and annoying issue), but I'm still curious about the cause of this issue. Thank you for your time.

**Comment by mintty** [comment]
This is not a mintty rendering issue but an effect caused by cygwin ConPTY handling. When running a Windows program and starting ConPTY support, the screen is redrawn and attributes may sometimes get tweaked before being sent to the terminal.
There is nothing mintty can do about it, please report it to the cygwin mailing list.

**Comment by xcdxcdxcd** [comment]
Thanks for replying, I'll try the mailing list 😄

**Comment by Biswa96** [comment]
Before that, I would suggest to check things are correct if ConPTY disabled. It can be disabled by seeting this environment variable `CYGWIN=disable_pcon` in Control Panel **before** runing any cygwin instance.

**Comment by mintty** [comment]
> CYGWIN=disable_pcon in Control Panel

It should be sufficient to run `CYGWIN=disable_pcon mintty` case by case.

**Comment by xcdxcdxcd** [comment]
I confirmed with the option `disable_pcon`. Since python3 I installed in windows won't respond, I use mvn instead. 
![image](https://user-images.githubusercontent.com/27773867/105151360-d389f380-5b40-11eb-94f7-4203c2718727.png)
![image](https://user-images.githubusercontent.com/27773867/105151346-ccfb7c00-5b40-11eb-8791-4fed4f9e297a.png)
As you can see from the above screenshot, It seems fonts are as expected. Also, the ANSI color sequence is displayed correctly. Since mvn is not a exe, I also tried java.exe and got the same conclusion.
I guess it can prove that this issue is caused by pcon things?

**Comment by xcdxcdxcd** [comment]
It seems that there've already had some discussion about similar issue of this, fyi.
http://cygwin.1069669.n5.nabble.com/Calling-a-Windows-program-changes-terminal-character-attributes-td149751.html#a149759

**Comment by mintty** [comment]
> I guess it can prove that this issue is caused by pcon things?

Quite for sure.

> It seems that there've already had some discussion about similar issue of this,

That thread is almost a year old and I see no solution. A request refreshing the issue might be good.

**Comment by mintty** [comment]
Marked issue as "invalid" as it's not caused by mintty.

**Comment by scandum** [comment]
Could this be caused by mintty applying the `\e[1m` bold attribute to 256 color codes?

In my own experience mintty can pseudo-randomly bold 256 color codes in environments that contain a mix of 16 and 256 color codes.

**Comment by mintty** [comment]
Attributes are accumulated on each character written and their total is considered for rendering, 
so no, I doubt there is any pseudo-random behaviour. If you encounter any, please try to demonstrate it.

**Comment by scandum** [comment]
It's when you're in a mixed environment. So if the terminal prompt uses 256 color codes and does not explicitly reset the color state at the start of the prompt, the prompt will be bolded if the previous command printed \e[1m.

Mintty has no setting to disable font bolding.

So @xcdxcdxcd might be able to fix the problem by having his prompt start out with \e[0m.

**Comment by avih** [comment]
> So if the terminal prompt uses 256 color codes and does not explicitly reset the color state at the start of the prompt, the prompt will be bolded if the previous command printed \e[1m.

That's not random at all. It's very specific, and according to spec. If bold was not reset then whatever follows stays bold. The terminal cannot and should not try to detect where the prompt ends and reset boldness when it does...

**Comment by mintty** [comment]
Browsing some old issues, I just noted that this was unanswered:

> Mintty has no setting to disable font bolding.

It does: `SuppressSGR=1`.

**Comment by scandum** [comment]
SuppressSGR=1 disables color bolding, not font bolding. Or possibly it disables both.

I'm talking about **fat** text here. I haven't found a way to specifically disable it.

**Comment by mintty** [comment]
Options - Text - Show bold: as colour

**Comment by scandum** [comment]
Try:
```
echo -e "\e[1;31mtest1 \e[38;5;64mtest2 \e[0m\e[38;5;64mtest3"
```
The goal is for test2 and test3 to display identical.

**Comment by mintty** [comment]
which is the case with SuppressSGR=1

**Comment by scandum** [comment]
That causes test1 to display a different color, so it's not a solution.

**Comment by mintty** [comment]
There would in fact be other test cases demonstrating your case. However, the point is, as has been discussed before in various issues, that I do not approve a combination of standard options that would make the bold attribute completely unnoticable as such. That means, particularly for palette colours and true colour attributes, alternative colours to indicate bold are not available, so there is no possibility other than bold font to indicate it.
Therefore I once introduced SuppressSGR as the only option that achieves bold suppression by completely disabling the attribute to be handled.
