### ISSUE TITLE
Documented feature "Drag and drop of itermcolors themes" not working.

### ISSUE THREAD

**Issue by souponaroom** [mintty/mintty#1079]
As specified in https://github.com/mintty/mintty/wiki/Tips#using-colour-schemes-themes

To reproduce: Download an itermcolors theme, and attempt to drag the file into the "theme" textbox in the "Looks" menu.

What happens instead: Mintty reverts to its default theme.

**Comment by mintty** [comment]
Local drag-and-drop works only for theme files in mintty format.
Format conversion for .itermcolors is only implemented for drag-and-drop as a downloadable URL (e.g. http:...).
Implementation is incomplete in this respect and documentation fuzzy, sorry. To be fixed.

**Comment by mintty** [comment]
Released 3.4.5.
