### ISSUE TITLE
KeyFunctions Ctrl+[Key]

### ISSUE THREAD

**Issue by BladeMight** [mintty/mintty#1080]
Can I assign <kbd>Ctrl</kbd>+<kbd>q</kbd> to `close`? I have tried, I have read man page I believe that is correct format for that:

```config
KeyFunctions=C+q:close;
```

But it didn't work. Is it even possible to assign Ctrl+[Key] shortcuts?

**Comment by mintty** [comment]
By default, all Ctrl+ combinations are mapped to the respective control _characters_ as typically expected from a terminal. See option `CtrlExchangeShift` to remap them to the Ctrl+Shift+ combinations, in which case functions assigned to those would become available for Ctrl+.
