### ISSUE TITLE
[mintty] ctrl+backspace or ctrl+shift+backspace not work as expected

### ISSUE THREAD

**Issue by sunlin7** [mintty/mintty#1082]
Hi, 
I ssh login remote and start emacs tui with mintty (xterm-color256), and press the `Ctrl+Backspace`, emacs got `\033[127;5u` can NOT work as `Ctrl+Backspace`.
Or just mintty and do 
```
$ echo -ne "\e[>4;1m"
$ # press Ctrl+Backspace
$ 7;5u
$ # press Ctrl+Shift+Backspace
$ 7;6u
```
Anyone know how to make the `Ctrl+Backspace` work with emacs-tui please?

**Comment by mintty** [comment]
> ssh login remote

remote from cygwin or into cygwin?
Assuming you login to another system, which one? Which version of emacs?
As xterm (which introduced modifyOtherKeys mode as enabled above) has two variants of this mode, emacs may be expecting the other escape sequence style...

**Comment by sunlin7** [comment]
From cygwin (windows) ssh login to remote CentOS 7, emacs26.
For `echo -ne "\e[>4;1m"` and then `Ctrl+Backspace`, both local mintty on windows and remote ssh session behaviors are same.

**Comment by mintty** [comment]
In fact, xterm treats Control+Backarrow as a special case (to serve backarrowKeyIsErase modes) for which it does not apply modifyOtherKeys mode even if enabled (1 or 2) and supported e.g. for Shift+Backarrow, Alt+Backarrow etc.

So emacs does not seem to expect escape sequence `\e[127;5u`. Maybe emacs should be asked to apply some generic recognition of modifyOtherKeys sequences to support more flexibility.

Maybe mintty should also restrict its handling to handle Control+Backarrow as a special case to be more compatible with xterm.

**Comment by mintty** [comment]
Actually, it's not related to anything "remote". Local text mode emacs behaves the same way in cygwin.

**Comment by mintty** [comment]
As a workaround, you could likely define some key binding for the escape sequence with emacs.
As I'm not familiar with emacs, I can't tell you how.

**Comment by mintty** [comment]
I've submitted a bug report to emacs.

**Comment by sunlin7** [comment]
@mintty thank you so much for helping, it should be a compatiable issue from the editor,  and look forward for response from mail list.
As your comment, yes, there is a workaround that bind key sequence in emacs with `(global-set-key (kbd "\e[127;6u") 'kill-whole-line)`.
And there is a refrenceticket https://github.com/mintty/mintty/issues/449.

Close this ticket for not a mintty issue.

**Comment by mintty** [comment]
Changed Backarrow to be consistent with xterm.

**Comment by sunlin7** [comment]
Thank you so much, look forward for the new release with change.

**Comment by mintty** [comment]
Released 3.4.5.

**Comment by sunlin7** [comment]
Great，thanks.

**Comment by sunlin7** [comment]
Hi mintty, I had verified on 3.4.6, and yes, pressing `Ctrl+Backsapce` or `Ctrl+Shift+Backsapce`  are `backspace` now.
I understand this behavior is compatable for `xterm`, but previous behavior that `Ctrl+Backsapce` and `Ctrl+Shift+Backsapce`  are identiable maybe more useful. : )

**Comment by mintty** [comment]
An application that wants to distinguish Shift-modified Backspace can use ModifyOtherKeys mode 2.

**Comment by mintty** [comment]
Also you can remap the key with something like
`KeyFunctions=S+Back:"Shift";C+S+Back:"Ctrl+Shift"`

**Comment by sunlin7** [comment]
Hi @mintty , `KeyFunctions=C+Back:"\e[127;5u";C+S+Back:"\e[127;6u";` is tried but **NOT** work in my local, is this invalid litteral string for `KeyFunctions`? Or, how to correctly bind the `C+Back` to `\e[127;5u`?  Thanks

**Comment by mintty** [comment]
There is no escape notation for the strings, so you'll have to embed a literal ESC control character in the config file.

**Comment by sunlin7** [comment]
Hi @mintty Yes, a literal ESC (ASCII 0x1B)  can be part of string for `KeyFunctions`, `KeyFunctions=C+Back:"[128;";` work for me now, thank you so much.

A `;` in `KeyFunctions` config seems has issue,  `KeyFunctions=C+Back:"a;b";` send **NOTHING** , while `KeyFunctions=C+Back:"ab";` work as expected.

**Comment by mintty** [comment]
Yes, embedding semicolon is another issue, but it's all described in the manual. You can change the separator character to a control character if you start the whole config string with it, again using literal control characters. Example (where ^[ is a literal ESC and ^S is a literal Control+S):
`KeyFunctions=^SC+Back:"^[[127;5u"^SC+S+Back:"^E[127;6u"`

**Comment by sunlin7** [comment]
@mintty Perfect :+1:  
Thank you so much for every details. I'll go through the document.
Best Regards
