### ISSUE TITLE
Not working: Previous Match Hotkey "Shift+Enter"

### ISSUE THREAD

**Issue by mallochine** [mintty/mintty#1085]
I didn't find it working in my mintty version 3.3.0 (wsltty).

I can see that "Shift+Enter" for search is in the man page. So it's supposed to work. But it's not for me. (man page here: https://stackoverflow.com/a/38869358/3325787

How to test:
1. Open search, Alt+F3
2. Search for a term
3. Press Enter and Shift+Enter several times

EDIT: just tested on mintty 3.4.4 (cygwin), doesn't work. It's kinda surprising this kind of basic feature isn't working after this many years. I guess a lot of people don't use scrollback search? Admittedly today was my first time using it in many months/years

**Comment by mintty** [comment]
Works for me.

**Comment by mallochine** [comment]
maybe it's a configuration thing?
![image](https://user-images.githubusercontent.com/1282950/107159720-ba59b300-6946-11eb-8a57-2060cf0fd434.png)

**Comment by mallochine** [comment]
system info 
![image](https://user-images.githubusercontent.com/1282950/107159732-cd6c8300-6946-11eb-941b-2d1ec20eb88a.png)

**Comment by mintty** [comment]
No issue for me. What does exactly happen if you press Enter and Shift+Enter?

**Comment by mallochine** [comment]
Enter does the same thing as Shift+Enter, it goes to the next match. Shift+Enter should go to the previous match.

**Comment by mintty** [comment]
Please upload your full configuration file.

**Comment by mallochine** [comment]
do u have a wiki article on how to export the configuration file? Cuz I can't find it if u do. Is that the minttyrc?

```
BackgroundColour=26,26,26
ForegroundColour=211,208,200
CursorColour=211,208,200
Black=51,51,51
BoldBlack=102,102,102
Red=242,119,122
BoldRed=242,119,122
Green=153,204,153
BoldGreen=153,204,153
Yellow=235,189,91
BoldYellow=235,189,91
Blue=102,153,204
BoldBlue=102,204,204
Magenta=242,119,122
BoldMagenta=242,119,122
Cyan=102,204,204
BoldCyan=102,204,204
White=211,208,200
BoldWhite=211,208,200
CursorType=block
CursorBlinks=no
ThemeFile=nord
```

We can setup a screensharing time for 5-10 min to let you find everything you need.

**Comment by mintty** [comment]
Nothing remarkable in this config file.
Please do this in a shell:
echo -e "\e[>4;1m"
od -t x1
Then type Shift+Enter, then Ctrl+D

**Comment by mintty** [comment]
The reason I was asking is to check whether the information about Shift+Enter actually arrives at mintty as such.
It could be e.g. that there is some hotkey tool installed that intercepts and interprets key event before passing them on to the application. As it works for others, there is no other explanation right now, so I'll mark the issue invalid and will eventually close it.

**Comment by mallochine** [comment]
oh ok, yea I had an Autohotkey, sorry this bug was invalid.

at least this will be useful to other people googling for the issue.
