### ISSUE TITLE
Default folder for Save as Image

### ISSUE THREAD

**Issue by wodim** [mintty/mintty#1086]
I think the "Save as Image" feature should default to some other folder, like the Pictures folder.

**Comment by Biswa96** [comment]
> Filename pattern and location are configurable (setting SaveFilename).

([man page][1])

[1]: https://mintty.github.io/mintty.1.html

**Comment by mintty** [comment]
> Filename pattern and location are configurable (setting SaveFilename).

With some limitations though. Neither a "~/" prefix nor variable substitution (like %APPDATA%/) would currently work, which I shall fix.

**Comment by wodim** [comment]
I know they are configurable, the title of the issue says "default".

The user folder is not a proper place to shove files in, it's not like ~ in Linux.

**Comment by Biswa96** [comment]
> The user folder is not a proper place to shove files in

Hence it should be configurable to `%UserProfile%` (e.g C:\Users\xyz), as example, like mintty said to be done.

**Comment by wodim** [comment]
I don't think you are getting me. The default **is** `%UserProfile%`. I'm arguing that it should be something else. `SHGetKnownFolderPath(FOLDERID_Pictures, ...)`

**Comment by Biswa96** [comment]
I said that an example. FOLDERID_Pictures == %USERPROFILE%\Pictures

**Comment by wodim** [comment]
No, you can't hardcode that path, the folder can be moved somewhere else or have another name.

**Comment by mintty** [comment]
The default SaveFilename pattern is a relative filename, so the default folder is the working directory from where mintty was started.
This may happen to be a user profile folder or anything else (if started from a command line).

I do not think the default folder (if any) should be "Pictures" as that thing lives in the domain of Windows paradigm while terminals reside in the POSIX domain.
I'll upload a tweak in a minute, so you can configure:
`SaveFilename=~/mintty.%Y-%m-%d_%H-%M-%S`
`SaveFilename=$USERPROFILE/Pictures/mintty/%Y-%m-%d_%H-%M-%S`
Note the POSIX syntax here (as described in the manual).

**Comment by wodim** [comment]
>I do not think the default folder (if any) should be "Pictures" as that thing lives in the domain of Windows paradigm while terminals reside in the POSIX domain.

The contextual menu that the "Save as Image" feature lives in is a Windows dropdown menu. I hope it is changed to a curses menu soon, so it's more POSIX-y.

**Comment by BrianInglis** [comment]
Most X Window desktop environments now set up (some of) user `Desktop`, `Documents`, `Downloads`, `Music`, `Pictures`, `Public`, `Templates`, `Video` folders, so defaulting to Cygwin `$HOME/Pictures/` if it exists and no alternative is specified is a reasonable default; `%UserProfile%/Pictures/` is a reasonable backup default as it likely exists, and Cygwin interoperates with Windows. 

Not sure what a `curses` menu is meant to look-and-feel like, other than shell `select` with cursor key support: Unix `n/curses/w` is a TUI, except for the alternative PDcurses native ports, which are not commonly used, nor a build option for most terminal emulators. 
POSIX dropped `curses` from their standards sometime in the 1990s, although it is still implied by their support of `vi`, but whether any libraries or other interfaces are used are implementation details. 

Like Cygwin Setup, `mintty` is Windows GUI, not X Window: they have to be able to run with only native libraries to (let you) fix issues; `mintty` also uses the Cygwin DLL to access the interfaces for that environment. 
For more of an X Window look-and-feel You may also run `lxterminal`, `xfce`, `xterm`, `rxvt`, `gnome-terminal`/`vte`, `konsole`, etc. instead under Cygwin Windows, LXDE, Gnome, KDE, or MATE desktop environments, or any remote X server, if you prefer.

**Comment by wodim** [comment]
The curses thing was tongue-in-cheek; I just don't understand the argument that wsltty, which is a Windows application, should act in a POSIX way just because it is used to emulate terminals.

As I said the Pictures folder (or even Documents or Desktop) is the appropriate place to put files in by default for Windows applications. You won't see Word or Firefox defaulting to save files to the User profile folder. But if we are going to argue wsltty is an application that has to conform to the POSIX standard then I'm at a loss. I hope in future versions it stops saving data in %appdata%, because that's not very POSIX-like.

**Comment by mintty** [comment]
You seem to have missed my explanation above: %APPDATA% is not the default.
Mintty follows xterm which is its general behaviour archetype, and save location of xterm is the initial working directory.
I do not know why mintty starts in %USERPROFILE% for you, it does not for me. Please check your desktop shortcut. Arguably mintty could detect being run from a desktop shortcut as a special case and set a specific working directory then. Suggestions welcome.

**Comment by wodim** [comment]
I did not install mintty directly, I installed it as part of wsltty (your software) instead, and this is the default shortcut that the installer created in `C:\Users\User\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`:

![image](https://user-images.githubusercontent.com/1001553/107695973-a3ea8900-6cb1-11eb-9d47-64c48ed4ffde.png)

In any case, I still do not see why images should be stored by default in the working directory. But if I haven't convinced you yet that you should follow the conventions of the OS I guess I never will so I'm leaving this here.

**Comment by mintty** [comment]
I've added this to the description of setting SaveFilename:
Note that if the filename pattern is a relative pathname (as is the default),
it will be taken as relative to the working directory mintty was started in,
with some tweaks as described above for the Log file.

**Comment by mintty** [comment]
Released 3.4.5.
