### ISSUE TITLE
Two mintty instances display the same char with different look(font)

### ISSUE THREAD

**Issue by netjune** [mintty/mintty#1092]
instance 1: mintty+WSL+emacs

instance 2: mintty+ssh.exe+emacs

They look like this:
![image](https://user-images.githubusercontent.com/17109782/108469360-0c91c100-72c3-11eb-8e54-be84fba026a6.png)

**Comment by mintty** [comment]
Your description is a bt fuzzy. I assume you refer to the double quote being double-width in one case.
This must be caused by different configuration, so information on how you run mintty in both cases is significant.
Also the locale setting (envionment variables LC_ALL, LC_CTYPE, LANG) are significant if you run mintty from a command line.

**Comment by netjune** [comment]
They are run in the same autohk script. So they have the same envionment. 
But the mintty.exe are not the same. The first one is from the git bundle. The second one is from wsltty(https://github.com/mintty/wsltty).

**Comment by mintty** [comment]
What's your WSL `locale`?
What's your Windows system locale/language?
Which mintty version is in use?

**Comment by netjune** [comment]
Now the two mintty.exe have the same version(3.4.3). The problem still exists.

> 
> 
> What's your WSL `locale`?

zh_CN.UTF-8

> What's your Windows system locale/language?

Chinese CP936

> Which mintty version is in use?

3.4.3

**Comment by mintty** [comment]
In CJK locales (even with UTF-8), CJK "ambiguous width" property is handled as wide in cygwin.
Mintty compensates for that in WSL mode by appropriate settings, but maybe they are not effective for you for some reason. Most likely you may have an explicit setting `Charwidth=ambig-wide` in your config file or in the command line of your shortcut.

**Comment by netjune** [comment]
Sorry for my poor English. I didn't discribe the problem clearly.

> In CJK locales (even with UTF-8), CJK "ambiguous width" property is handled as wide in cygwin.
> Mintty compensates for that in WSL mode by appropriate settings, but maybe they are not effective for you for some reason. 

There is no problem for WSL mode. The problem is in ssh mode.



> Most likely you may have an explicit setting `Charwidth=ambig-wide` in your config file or in the command line of your shortcut.

I add this setting to minttyrc. The problem still exists. The minttyrc:
```
CursorType=block
ThemeFile=dracula
CursorBlinks=no
Font=Consolas
FontHeight=10
Locale=zh_CN
Charset=UTF-8
Columns=115
Rows=35
ComposeKey=off
BackspaceSendsBS=no
Term=xterm-256color
ClicksPlaceCursor=yes
ClicksTargetApp=yes
ZoomShortcuts=no
WindowShortcuts=no
CopyAsRTF=no
Charwidth=ambig-wide
```

**Comment by netjune** [comment]
> Is Charwidth=ambig-narrow ok for CJK?

I see no problem until now.

**Comment by mintty** [comment]
> > Mintty compensates for that in WSL mode by appropriate settings, but maybe they are not effective for you for some reason.

> There is no problem for WSL mode.

Ah right, I confused this and my explanation was incomplete. Anyway, this compensation explains the quote mark to be narrow in WSL while it is wide in the right screenshot.
Now while (unfortunately), the cygwin CJK locales want the quote mark wide, if you ssh to a remote system with a different idea of CJK ambiguous width, this does not match. There is nothing that mintty could do automatically about it as it cannot magically detect whether you've logged in to a remote system. So you need to configure those instances that you use for running remote shell in the distinct way that we now established.

It is however also possible already to switch the mintty locale dynamically. But you'd need to apply that explicitly before and after remote login (e.g. in a login wrapper):
`echo -e "\e]701;zh_CN.UTF-8@cjknarrow\a"`
and to switch back to cygwin:
`echo -e "\e]701;zh_CN.UTF-8\a"`
I'll add this to the wiki Tips page, and provide a more generic script (patching @cjknarrow into the current locale being used).

**Comment by netjune** [comment]
> Now while (unfortunately), the cygwin CJK locales want the quote mark wide, if you ssh to a remote system with a different idea of CJK ambiguous width, this does not match.

Do you mean that mintty treat that char as wide but the remote emacs treat it as narrow?

> I'll add this to the wiki Tips page, and provide a more generic script (patching @cjknarrow into the current locale being used).

Thanks.

**Comment by mintty** [comment]
> Do you mean that mintty treat that char as wide but the remote emacs treat it as narrow?

Yes, you can detect that by moving the cursor around it in an editor. The dynamic locale setting sequence would force that to be changed while in the remote session.

**Comment by mintty** [comment]
Actually, this issue will be obsolete with cygwin 3.2.0 with my patch that drops the ambiguous-width wide property for CJK Unicode locales, so that will be consistent with remote systems.
I will instead provide a more generic script to strip any @cjk* modifier from the locale (if given) and adjust mintty accordingly.

**Comment by mintty** [comment]
Cygwin 3.2.0 has been released which unifies CJK width behaviour.
