### ISSUE TITLE
Launching a script with mintty opens two windows

### ISSUE THREAD

**Issue by heetbeet** [mintty/mintty#1093]
When I run `mintty -e <path-to-script>`, it opens two windows:

![image](https://user-images.githubusercontent.com/4103775/109299708-35bfcd80-783e-11eb-8e47-d86722770214.png)

How do I rather launch a script in a single window of mintty, like:
![image](https://user-images.githubusercontent.com/4103775/109299795-56882300-783e-11eb-9be8-79f68f736c09.png)

**Comment by Biswa96** [comment]
What script did you run? Shell or batch?

**Comment by heetbeet** [comment]
It's a batch script

**Comment by Biswa96** [comment]
Ten you may have to add `cmd.exe /k` after the mintty.exe.

**Comment by Biswa96** [comment]
Then you may have to add `cmd.exe /k` after the mintty.exe.

**Comment by heetbeet** [comment]
Just tried the following two commands

- `mintty python foo.py`
- `mintty cmd /k foo.bat`

And both resulted in two black windows.
For comarison, I tested both mintty from Git and from Cygwin

**Comment by avih** [comment]
I'm not sure whether cmd.exe (which is needed to run batch files) can operate without a windows console.

As for python, if that's a windows python then it's expected because it's probably compiled as a console application, which, again, needs a console window (which mintty is not).

**Comment by k-takata** [comment]
Couldn't reproduce.
I create `p.bat` which includes only a `pause` line, then run `mintty -e p.bat`.
A new mintty window is opened as expected, and the message "Press any key to continue..." is shown inside the window.

**Comment by heetbeet** [comment]
@k-takata that is good new, which version of mintty are you using?
I'm using `mintty 3.4.4 (x86_64_pc_cygwin)`

**Comment by heetbeet** [comment]
@avih how does mintty not provide a console window? I thought that is pretty much one of the jobs of mintty. In the images I posted, mintty did provide a console for my scripts to run in, it just provided two windows in stead of just one.

**Comment by k-takata** [comment]
3.4.4 (cygwin) and 3.4.5 (msys2)

**Comment by mintty** [comment]
We do not reproduce this and your issue remains undescribed. Without a proper description (what script? what system (cygwin/MSYS)?) I can only close the issue. Please provide a small reproducible test case.

**Comment by heetbeet** [comment]
A thanks, I finally found out what the problem was. I was using the minimum number of binaries necessary for a mintty window. I thought all that is necessary was `mintty.exe` and `msys-2.0.dll` and didn't realize that my specific problem is cased when `cygwin-console-helper.exe` isn't present.

I can now launch a script under a mintty window successfully by using a minimal collection of mintty binaries:
![image](https://user-images.githubusercontent.com/4103775/109388203-62431a80-790e-11eb-89cf-4b9369db3fb3.png)

And running the script as:
`mintty -e <path-to-script>`

**Comment by mintty** [comment]
I could have thought about that case but you didn't say that you're running in a standalone environment. Thanks for feedback.
