### ISSUE TITLE
Unexpected ligatures behaviour

### ISSUE THREAD

**Issue by antoineco** [mintty/mintty#1099]
mintty 3.4.7

_Mandatory disclaimer: before opening this issue, I tried to reproduce the behaviour in Windows Terminal, unsuccessfully, to ensure it wasn't a Vim issue. Reproducible at least with the Fira Code and Cascadia Code fonts, but probably not font related._

I noticed a couple of inaccuracies in the way ligatures are displayed (or actually _not_ displayed). It's especially noticeable in Vim, but also occurs e.g. in a shell.

Here is the list, with screenshots to illustrate:

---

Ligatures don't show while typing or after exiting Insert mode, but they do show **after resizing/moving either the window or tmux pane**.

![typing](https://user-images.githubusercontent.com/3299086/112462553-79d0c000-8d61-11eb-85d3-c0526ba9ea64.png)
_Fig. Before resize - Vim_

![resize](https://user-images.githubusercontent.com/3299086/112462557-7b9a8380-8d61-11eb-8511-157883fe451a.png)
_Fig. After resize (or move) - Vim_

---

Backspacing over ligatures makes them disappear again

![backspace](https://user-images.githubusercontent.com/3299086/112462869-daf89380-8d61-11eb-860d-7720490359c0.png)
_Fig. After backspacing - Vim_

---

Ligatures are never displayed when the cursor is positioned on one of the characters in the corresponding group (either on `!` or `=` in this simple example). After moving the cursor away from the ligature, it is not displayed either.

![cursor](https://user-images.githubusercontent.com/3299086/112463592-bb159f80-8d62-11eb-923f-9fe189bf9a7e.png)
_Fig. Cursor on ligature - Vim_
![cursor-term](https://user-images.githubusercontent.com/3299086/112464289-9a017e80-8d63-11eb-89a4-0bad1f40f374.png)
_Fig. A combination of these issues, occurring in a shell - no Vim, no tmux_

**Comment by mintty** [comment]
Displaying ligatures after they have been incrementally composed in the line requires additional display activity which I assume not all people will like, so that's not the default behaviour. Try option `LigaturesSupport=2`.

> Ligatures are never displayed when the cursor is positioned on one of the characters in the corresponding group 

This is on purpose. The assumption is that in this case you may be editing the line contents so you should clearly see the distinct characters that are combined rather than the resulting ligature.

**Comment by antoineco** [comment]
Thanks for the quick answer @mintty 🙌 

Didn't realize that option could mean anything else than true/false. Indeed, `LigaturesSupport=2` works like a charm.

> The assumption is that in this case you may be editing the line contents so you should clearly see the distinct characters that are combined rather than the resulting ligature.

Makes a lot of sense 👍 

Marking as resolved.
