### ISSUE TITLE
FZF for Windows does not work properly when part of a pipeline even though ConPTY support is enabled

### ISSUE THREAD

**Issue by bob-marcus** [mintty/mintty#1105]
Even if I enable ConPTY support in mintty, if `fzf` (compiled for Windows) is used as part of a pipeline (for example with `find`), it will display the input but fuzzy finding will not work. However, `fzf` will work if invoked by itself or as `winpty fzf` (this form cannot be used as part of a pipeline); it will also work as part of a pipeline in Windows Terminal if I set up Git-Bash according to this [StackOverflow answer](https://stackoverflow.com/a/57369284). Since Windows terminal also uses ConPTY for interactive CLI programs, the difference in behavior between it and mintty seems strange.
## How to reproduce
1. Open mintty
2. type `find  nonemptydirectory/  | fzf`
You will notice that if you start typing fuzzy finding will not work.
## Environment
mintty 3.4.7 (x86_64-pc-msys) [Windows 19042]
minttyrc:
```
Charset=UTF-8
ThemeFile=
FontWeight=400
FontIsBold=no
CursorType=line
Transparency=off
ConPTY=on
```
I hope that this is the appropriate place for this bug report.

**Comment by mintty** [comment]
Whatever the tool is supposed to do, it looks quite the same in xterm, so this is not a terminal issue.
Do you use the cygwin/msys version of it?

**Comment by bob-marcus** [comment]
@mintty FZF is supposed to take the output of a command, for example a list of file paths returned by a tool like `locate`, and allows the user to look for a certain string using fuzzy search and outputs the selected string.
For a test case, consider the `classic-literature` directory containing the following files:
```
classic-literature/
├── heart-of-darkness
├── on-the-road
├── the-adventures-of-tom-sawyer
└── the-great-gatsby
```
Here are two gifs that show the behavior of the pipeline `find . | fzf`, one recorded while using Windows Terminal, the other when using Git-bash.
Windows Terminal:
![fzfworking](https://user-images.githubusercontent.com/71236398/119573750-fb21ee80-bdb4-11eb-9d83-7fbd22c14837.gif)

Notice that the matched strings change dynamically according to the letters typed in the search field, and when I press enter, the string with the best match is returned.

Git-bash:
![fzfnotworking](https://user-images.githubusercontent.com/71236398/119573949-41774d80-bdb5-11eb-8501-c01fc01fde95.gif)

Here FZF just displays the output of `find` but it is completely unresponsive.

Now notice what happens when I use `winpty fzf` (here FZF is using the output of its default command, which is `dir` on Windows, as input):

![fzfworking2](https://user-images.githubusercontent.com/71236398/119574625-0cb7c600-bdb6-11eb-87c9-3c6e0354a409.gif)

Not only FZF works properly, but it also adopts the colors defined by the mintty colorscheme for its interface elements (for example the greater-than symbol on the side).

In all these examples, I'm using the native Windows binary of FZF.
I am sorry if I wasn't exhaustive enough in my first post.

**Comment by mintty** [comment]
Testing this in cygwin, with cygwin fzf, it works fine, with or without ConPTY support.

> In all these examples, I'm using the native Windows binary of FZF.

Maybe ConPTY support isn't strong enough for such an interactive use case? Ask on the cygwin mailing list.

**Comment by mintty** [comment]
Closing as it's not a terminal issue.
