### ISSUE TITLE
In command line, mintty.exe eat double slash ("\\")

### ISSUE THREAD

**Issue by fengyichui** [mintty/mintty#1107]
I want use WSL's VIM to open my window file by right click menu. So I add a command to Windows Registry (HKEY_CURRENT_USER\SOFTWARE\Classes\*\shell\vim-in-wsl\command):
> C:\Users\lenovo\AppData\Local\wsltty\bin\mintty.exe --WSL --configdir=C:\Users\lenovo\AppData\Roaming\wsltty --title "[vim] %1" --exec bash -c "vim \\"$(wslpath '%1')\\""

The `%1` is the absolute path of the file. If the file is in network driver, `%1` will expand to:
> \\\\192.168.5.11\server\abc.txt

But mintty eat the first double slash ("\\\\") to one ("\\"), so `wslpath` command will fail to parse it and setting title is wong.

**Comment by mintty** [comment]
It's not the terminal that interprets strings and escape notation. It's the shell, and maybe the additional nesting by $(...). You should double each backslash to compensate.
