### ISSUE TITLE
Include option to revert ctrl-backspace to send ^_

### ISSUE THREAD

**Issue by pnetherwood** [mintty/mintty#1109]
In release 3.4.5  ctrl-backspace and ctrl-shift-backspace was changed to just send backspace whereas prior to release 3.4.5 ctrl-backspace sent ^_

However, that's not very useful if you've mapped ^_ in .inputrc for bash and your .vimrc to do delete word backwards and ctrl-H to something else. I've tried various KeyFunctions as suggested in #1082 but I couldn't get any of them to work. Is there any way to revert back to the old functionality?

**Comment by mintty** [comment]
`KeyFunctions=C+Back:^_`

**Comment by mintty** [comment]
No other terminal maps Ctrl+Back to ^_, that's why I removed this mapping and hoped nobody would notice :)
Sorry for the trouble.

**Comment by mintty** [comment]
You could also configure this with the control character embedded verbatim in a user-defined string:
`KeyFunctions=C+Back:"^_"`
However, to try this on the command line, the quotes would need to be escaped, e.g. `KeyFunctions=C+Back:'"^_"'`.
Where the `^_` in the strings would be a verbatim Control+_, not an escape notation...

**Comment by pnetherwood** [comment]
> KeyFunctions=C+Back:^_

That works perfectly. Thanks guys.

The tips page will need to be updated as it refers to ^_
[https://github.com/mintty/mintty/wiki/Tips#user-content-terminal-line-settings](https://github.com/mintty/mintty/wiki/Tips#user-content-terminal-line-settings) and [https://github.com/mintty/mintty/wiki/Tips#user-content-readline-configuration](https://github.com/mintty/mintty/wiki/Tips#user-content-readline-configuration).

It was the tips page that brought me to relying on C-Back mapping to ^_

**Comment by mintty** [comment]
Tweaked the wiki page.
