### ISSUE TITLE
Why can't you output sixel images in centos7?

### ISSUE THREAD

**Issue by MrYang-Jia** [mintty/mintty#1110]
my system is win10
Using cygwin64 terminal mintty-3.5.0 
conect centos7 service
use
" lsix /data-4t/polardb/show_logo.png"
or
 "convert  /data-4t/polardb/show_logo.png  -geometry 800x480  sixel:-" 
but failed
![image](https://user-images.githubusercontent.com/76804829/125756733-4c024f98-4471-4729-b62a-56ab8826d5a8.png)

**Comment by mintty** [comment]
Both the upper-left corner icon and the quoted device attributes code suggest you are in fact not running mintty. How did you connect?

**Comment by MrYang-Jia** [comment]
cygwin64 -> mintty -> ssh user@ip

**Comment by MrYang-Jia** [comment]
![image](https://user-images.githubusercontent.com/76804829/125794739-abfc420d-6849-4e74-8ef6-8414a02ee663.png)

![image](https://user-images.githubusercontent.com/76804829/125794914-6340131f-1eb4-4e53-abe4-b9dc97d360b0.png)

**Comment by k-takata** [comment]
Do you use the Cygwin version of ssh? What does `type -a ssh` show?

**Comment by MrYang-Jia** [comment]
windows:
$ type -a ssh
ssh is /cygdrive/c/Windows/System32/OpenSSH/ssh





remote server:
ssh is /usr/bin/ssh


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mintty/mintty"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 晚上9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mintty/mintty] Why can't you output sixel images in centos7? (#1110)





 
Do you use the Cygwin version of ssh? What does type -a ssh show?

**Comment by MrYang-Jia** [comment]
> Do you use the Cygwin version of ssh? What does `type -a ssh` show?
windows:
$ type -a ssh
ssh is /cygdrive/c/Windows/System32/OpenSSH/ssh

**Comment by k-takata** [comment]
So, you are using the Win32 version of ssh. You should install the Cygwin version of ssh.

**Comment by MrYang-Jia** [comment]
Thank you. It's settled

**Comment by avih** [comment]
> So, you are using the Win32 version of ssh. You should install the Cygwin version of ssh.

Interesting. Do you know exactly why the windows version is not good enough to passthrough sixel data?

Does it modify the data in some ways?

**Comment by k-takata** [comment]
In my understanding, the Win32 ssh is some kind of terminal emulator. It parses escape sequences and draws the screen using the Win32 Console APIs.

**Comment by k-takata** [comment]
You can see that ssh.exe is using the Console APIs:
```
>dumpbin /imports C:\Windows\System32\OpenSSH\ssh.exe | findstr "Console"
                         3AC ReadConsoleW
                         36E PeekConsoleInputA
                         208 GetNumberOfConsoleInputEvents
                         183 GetConsoleMode
                         40B SetConsoleWindowInfo
                         17A GetConsoleCP
                         17F GetConsoleCursorInfo
                         3EA ScrollConsoleScreenBufferA
                         3A6 ReadConsoleInputW
                         186 GetConsoleOutputCP
                         407 SetConsoleScreenBufferSize
                          52 SetConsoleTitleA
                         408 SetConsoleTextAttribute
                         108 FillConsoleOutputCharacterA
                         3FE SetConsoleCursorInfo
                         402 SetConsoleMode
                         405 SetConsoleOutputCP
                         4ED WriteConsoleOutputA
                         107 FillConsoleOutputAttribute
                         3FD SetConsoleCtrlHandler
                         188 GetConsoleScreenBufferInfo
                         3A7 ReadConsoleOutputA
                         3FF SetConsoleCursorPosition
                         3FC SetConsoleCP
                         13F FreeConsole
                         4F2 WriteConsoleW
```

**Comment by Biswa96** [comment]
This may help https://github.com/powershell/openssh-portable

**Comment by avih** [comment]
> You can see that ssh.exe is using the Console APIs:

Well, it can use it, but it doesn't mean it does. I know the Windows ssh can be a terminal emulator, especially with older Windows consoles.

However, I'd think that on newer windows console which has good support for VT escape codes (and colors), it would passthrough the data so that the console does the emulation rather than inside the ssh binary.

But yeah, hard to tell what happens exactly. It's a good data point though that the windows ssh is still not a 100% passthrough even in modern windows PTY (which should be enabled by default for cygwin).
