### ISSUE TITLE
Emoji highlighting broken since 3.0.1

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#1116]
For example this snake emoji (from `pipenv`:
![image](https://user-images.githubusercontent.com/2286713/129421763-16100116-873d-453e-a179-009ca5b11d2b.png)

EDIT: I'm on 3.5.0, but the version is relatively irrelevant.

**Comment by mintty** [comment]
What's your output, which characters? I cannot assess this issue without any information.

**Comment by mintty** [comment]
And your emoji style?

**Comment by mintty** [comment]
Your mention of "some emojis" was confusing. Adapted title.

**Comment by ElvenSpellmaker** [comment]
Hey sorry.

The reason why I said some is that using the default text emojis it works fine, but using picture emojis like `noto` fails.

In Wsltty with no emoji set-up: 
![image](https://user-images.githubusercontent.com/2286713/129444713-39296807-0523-46c9-87b2-5bf90039e7c4.png)

In Mintty with emoji set-up:
![image](https://user-images.githubusercontent.com/2286713/129444705-70bb5b85-4db1-4e99-a8bf-3dedf84605e8.png)

My `.minttyrc` has this:
`Emojis=noto`

**Comment by mintty** [comment]
Released 3.5.1.

**Comment by ElvenSpellmaker** [comment]
Thanks 🙂
