### ISSUE TITLE
cygwin Error

### ISSUE THREAD

**Issue by RoumaissaNl** [mintty/mintty#1117]
Hello everybody
I have this problem in Cygwin
And i dont know how to handle with it
Any solutions please
![129666394-693bde5b-2d22-4871-8e0a-3ec5c26225c2](https://user-images.githubusercontent.com/71291705/129714175-67c363f9-17b2-4ce2-b967-804d6cb32aff.png)

**Comment by BrianInglis** [comment]
Check $CYGWIN_ROOT/var/log/setup.log.full for errors, rename that file if any and post that content here or attach to a post to the [Cygwin mailing list](mailto:cygwin@cygwin.com); rerun Cygwin Setup and recheck that run's $CYGWIN_ROOT/var/log/setup.log.full for errors; see if mintty will spawn bash.

**Comment by RoumaissaNl** [comment]
I don't know how to check for errors here 
![Capture](https://user-images.githubusercontent.com/71291705/129793393-0ad70421-aaec-47a1-a66b-a759a75f884b.PNG)

**Comment by k-takata** [comment]
Open `C:\cygwin64\bin` on Explorer and double click `ash.exe`.
Then run `./rebaseall`.

**Comment by BrianInglis** [comment]
> I don't know how to check for errors here
Everything under /var/log/ is (or should be) a text log file. 
Open the text log file setup.log.full with any text editor you prefer, read thru, and check for errors that are significant. 
If in doubt, post or attach here. 
For example, some insignificant errors:
```
$ egrep '^[12][90]([0-9]{2}[-./: \t]){6}error:[ \t]' /var/log/setup.log.full
2021/07/29 22:34:01 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:34:01 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:34:02 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:34:03 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:37:44 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:37:45 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
2021/07/29 22:37:49 error: Unable to remove temporary file '/var/log/setup.log.runXa05464'
```

**Comment by RoumaissaNl** [comment]
I just run ./rebaseall 
![Capture](https://user-images.githubusercontent.com/71291705/129848755-9363d5f9-2c48-4804-85cf-66e9ef3c378e.PNG)

What should i do after that

**Comment by RoumaissaNl** [comment]
I openen the text log file setup.log.full, it seems like that
![Capture](https://user-images.githubusercontent.com/71291705/129849081-431c30f1-a04d-42f2-9505-ea5b53ebbcd9.PNG)

**Comment by k-takata** [comment]
It might be better to reboot your Windows.

**Comment by BrianInglis** [comment]
> I open the text log file setup.log.full, it seems like that

Please just attach the log file using drag and drop into the comment box: you 
will first have to rename the file to setup.log.full.log. 
Most often problems appear towards the end of logs. 
Screenshots rarely contain all or any of the required information, are unsearchable for relevant content, resolution and/or fonts are so small as to be unreadable!

**Comment by RoumaissaNl** [comment]
I couldn't drop the log file, I just can drop this one :
[setup.log](https://github.com/mintty/mintty/files/7009988/setup.log)


> > I open the text log file setup.log.full, it seems like that
> 
> Please just attach the log file using drag and drop into the comment box: you
> will first have to rename the file to setup.log.full.log.
> Most often problems appear towards the end of logs.
> Screenshots rarely contain all or any of the required information, are unsearchable for relevant content, resolution and/or fonts are so small as to be unreadable!

**Comment by RoumaissaNl** [comment]
> It might be better to reboot your Windows and run ./rebaseall again.

![Capture](https://user-images.githubusercontent.com/71291705/129968058-27d5ef88-3f0d-4492-8e19-72f209c9e997.PNG)

**Comment by k-takata** [comment]
Try searching `cygwin1.dll` as the error message said.

**Comment by BrianInglis** [comment]
> I couldn't drop the log file, I just can drop this one :

As requested, please first rename setup.log.full to setup.log.full.log, then drag and drop setup.log.full.log into the comment box.

**Comment by BrianInglis** [comment]
The first problem seems to be that you are trying to save downloaded Cygwin packages into 
```2021/08/17 20:53:09 Selected local directory: C:\Windows\system32```
which Windows may have many issues with and silently interfere with, causing all subsequent postinstall steps to fail:
```
2021/08/17 21:02:39 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_000_autorebase.dash"
2021/08/17 21:02:39 abnormal exit: exit code=2
2021/08/17 21:02:39 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/0p_update-info-dir.dash"
2021/08/17 21:02:40 abnormal exit: exit code=2
2021/08/17 21:02:41 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/000-cygwin-post-install.sh"
2021/08/17 21:02:58 abnormal exit: exit code=254
2021/08/17 21:02:58 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/coreutils.sh"
2021/08/17 21:02:58 abnormal exit: exit code=-1073741819
2021/08/17 21:02:58 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/bash.sh"
2021/08/17 21:03:14 abnormal exit: exit code=254
2021/08/17 21:03:14 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/base-files-mketc.sh"
2021/08/17 21:03:30 abnormal exit: exit code=254
2021/08/17 21:03:30 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/base-files-profile.sh"
2021/08/17 21:03:46 abnormal exit: exit code=254
2021/08/17 21:03:46 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/p11-kit.sh"
2021/08/17 21:04:02 abnormal exit: exit code=254
2021/08/17 21:04:02 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/ca-certificates.sh"
2021/08/17 21:04:18 abnormal exit: exit code=254
2021/08/17 21:04:18 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/crypto-policies.sh"
2021/08/17 21:04:34 abnormal exit: exit code=254
2021/08/17 21:04:34 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/openssl.sh"
2021/08/17 21:04:50 abnormal exit: exit code=254
2021/08/17 21:04:50 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/man-db.dash"
2021/08/17 21:04:50 abnormal exit: exit code=2
2021/08/17 21:04:50 running: C:\cygwin64\bin\bash.exe --norc --noprofile "/etc/postinstall/mintty.sh"
2021/08/17 21:05:06 abnormal exit: exit code=254
2021/08/17 21:05:06 running: C:\cygwin64\bin\dash.exe "/etc/postinstall/zp_man-db-update-index.dash"
```
A better choice for the local package directory would be e.g. `C:\Users\...\Downloads\` where `...` is your user account id.

**Comment by BrianInglis** [comment]
> The first problem seems to be that you are trying to save downloaded Cygwin packages into
> `2021/08/17 20:53:09 Selected local directory: C:\Windows\system32`
> which Windows may have many issues with and silently interfere with, causing all subsequent postinstall steps to fail:
> A better choice for the local package directory would be e.g. `C:\Users\...\Downloads\` where `...` is your user account id.

Please also download Cygwin Setup-x86_64.exe under your normal user account id `...` and directory into `C:\Users\...\Downloads\` from [Cygwin 64 Setup](https://Cygwin.com/setup-x86_64.exe), and run Cygwin Setup from that Downloads directory under your normal user account id `...`.

**Comment by RoumaissaNl** [comment]
> > I couldn't drop the log file, I just can drop this one :
> 
> As requested, please first rename setup.log.full to setup.log.full.log, then drag and drop setup.log.full.log into the comment box.
as u can see I renamed the file to setup.log.full.log, but I could not drug it here 
![1](https://user-images.githubusercontent.com/71291705/130125654-5e2d93fd-dec1-4b88-b464-d0c27b627841.PNG)
![2](https://user-images.githubusercontent.com/71291705/130125667-dff1ed5e-145a-4ae6-846e-65fc89802c7e.PNG)

**Comment by RoumaissaNl** [comment]
> > I couldn't drop the log file, I just can drop this one :
> 
> As requested, please first rename setup.log.full to setup.log.full.log, then drag and drop setup.log.full.log into the comment box.


as u can see I renamed the file to setup.log.full.log, but I could not drug it here 
![1](https://user-images.githubusercontent.com/71291705/130125654-5e2d93fd-dec1-4b88-b464-d0c27b627841.PNG)
![2](https://user-images.githubusercontent.com/71291705/130125667-dff1ed5e-145a-4ae6-846e-65fc89802c7e.PNG)

**Comment by BrianInglis** [comment]
Works Just Fine For Me!
[setup.log.full.log](https://github.com/mintty/mintty/files/7017092/setup.log.full.log)

**Comment by RoumaissaNl** [comment]
> Try searching `cygwin1.dll` as the error message said.

![Capture](https://user-images.githubusercontent.com/71291705/130128322-487791d5-f4f5-42e3-a8d3-5994639abce1.PNG)
I cound nout unstall this one as the error message said

**Comment by RoumaissaNl** [comment]
> Works Just Fine For Me!
> [setup.log.full.log](https://github.com/mintty/mintty/files/7017092/setup.log.full.log)

Can I rename it to setup.log.full ??

**Comment by RoumaissaNl** [comment]
> Works Just Fine For Me!
> [setup.log.full.log](https://github.com/mintty/mintty/files/7017092/setup.log.full.log)

I created a new file, I named it as u requested and i copy the content of the setup.log.full.log and pest it in the new file
[setup.log.full.log.txt](https://github.com/mintty/mintty/files/7017182/setup.log.full.log.txt)

![Capture](https://user-images.githubusercontent.com/71291705/130129935-e808496a-b9a7-48a4-991b-051977141ef3.PNG)

**Comment by RoumaissaNl** [comment]
![Capture](https://user-images.githubusercontent.com/71291705/130130214-697ad095-7616-416f-ba75-e8e73e2b71af.PNG)

**Comment by RoumaissaNl** [comment]
> Try searching `cygwin1.dll` as the error message said.

When I deleated the cygwin1.DLL file doesn't work anymore and after i reboot the Cygwin Terminal this message apear
![Capture](https://user-images.githubusercontent.com/71291705/130131352-d955a527-eeff-4c40-bebb-99d5277777ff.PNG)

**Comment by BrianInglis** [comment]
Please try deleting your `\Cygwin64` directory, delete any cygwin files installed in `\Windows\System32`, restart your system, and retry running Cygwin Setup as you just did. 
Are you running Windows Defender or any AntiVirus?

**Comment by RoumaissaNl** [comment]
> Please try deleting your `\Cygwin64` directory, delete any cygwin files installed in `\Windows\System32`, restart your system, and retry running Cygwin Setup as you just did.
> Are you running Windows Defender or any AntiVirus?

Yes i'm running Windows Defender

**Comment by mintty** [comment]
Closing as this is not a mintty issue. Anyway, was the problem resolved meanwhile?
