### ISSUE TITLE
Negative values for position

### ISSUE THREAD

**Issue by robert-ross** [mintty/mintty#1123]
Version 3.5.0 honored negative values for `X` and `Y` when starting with `mintty -p X,Y` but version 3.5.1 does not.  For example, `mintty -p -8,-4` and `mintty -p 0,0` result in different placements in v3.5.0 but not in v3.5.1.  Please restore the former behavior.

**Comment by mintty** [comment]
I do not see 3.5.0 adjust the negative placement.
The gap is caused by some crude Windows design which was discussed in some other issue.

**Comment by mintty** [comment]
See also #1056.

**Comment by robert-ross** [comment]
The gap is what makes negative values important.  Using Cygwin's `setup-x86_64`, I downgraded to `3.5.0-1` and verified that `mintty -p -4,-4` and `mintty -p 0,0` had different positions.  I then used `setup-x86_64` to upgrade to `3.5.1-1` and the difference went away.  Earlier releases such as `3.4.7-1` also had different positions.  Please try with a 3.4.x release.  I've been taking advantage of negative positions for over two years on multiple machines so I know it worked in many environments.

**Comment by mintty** [comment]
> mintty -p -4,-4 and mintty -p 0,0 had different positions

Not for me. Please upload your complete configuration, maybe some other setting has side impact.

**Comment by robert-ross** [comment]
What command(s) should I run to collect my complete configuration?  I tried without any files matching `/etc/minttyrc`, `$APPDATA/mintty/config`, `~/.config/mintty/config`, and `~/.minttyrc` but got the same result.  I also tried with `C:\Cygwin\bin\mintty.exe -c C:\Cygwin\minttyrc -p -4,-4` where `C:\Cygwin\minttyrc` only contained `CursorBlinks=no` but got the same result.

**Comment by mintty** [comment]
Mysterious. What does `mintty -Rm` say?

**Comment by robert-ross** [comment]
On one machine
```
$ mintty -Rm
Monitor 1 current primary ( 96 dpi) w,h 1920,1200 (   0,   0...1920,1200)
1 monitors,      smallest width,height 1920,1200
```
but I can use negative positions on a 1920x1080 machine.  With mintty 3.5.0 I can also launch with positions that put parts of the terminal off-screen, e.g., `mintty -p -180,-4`.

**Comment by mintty** [comment]
For me, it's the other way round: negative offset was accepted on a 1920x1200@96dpi machine but not on a 1920x1080@120dpi machine. So I have a case to do some analysis but it may turn out that it's some strange Windows behaviour that mintty won't be able to work around.

**Comment by robert-ross** [comment]
I'm glad that it was finally reproduced by someone else!  Another machine, which also supported negative positions such as `-p -32,-32` in v3.5.0 and earlier, had
```
$ mintty -Rm
Monitor 1 current primary ( 96 dpi) w,h 1920,1080 (   0,   0...1920,1080)
1 monitors,      smallest width,height 1920,1080
```
Perhaps it has to be 96 dpi.  I'm hoping that mintty after 3.5.1 will allow it on machines where mintty before 3.5.1 allowed it.  It's now possible to determine what code change disallowed the behavior but I understand that the process may be difficult and negative offsets were never officially supported so the issue may not be resolved.

**Comment by robert-ross** [comment]
Thanks, 3.5.2 did fix it on all of my hosts.
