### ISSUE TITLE
mintty 3.5.1 fails on "--size maxheight" or "--size maxwidth"; no window created.

### ISSUE THREAD

**Issue by joeinwap** [mintty/mintty#1124]
I have a Windows icon called "Tall black shell" with this as its target:
`
  `   C:\cygwin64\bin\mintty.exe --size maxheight  --fg gray80 --bg black -`

Manually executing `mintty --size maxheight; echo $status` immediately returns 0 but no window is created.  Same for `mintty --size maxwidth; echo $status`.  The problem occurred immediately after the upgrade to mintty 3,5,1 this morning (2021-09-12).

As a workaround, I have had to change it to:

     `C:\cygwin64\bin\mintty.exe --size 80x57  --fg gray80 --bg black -`

**Comment by mintty** [comment]
Released 3.5.2.
