### ISSUE TITLE
size and postion changed by press apply button in maximised mode

### ISSUE THREAD

**Issue by walkerxk** [mintty/mintty#1126]
in maximised mode, when i press apply button or save button in options, the size and postion have changed.
before:![before](https://user-images.githubusercontent.com/3411710/133878102-7b1de53a-8130-4357-a0df-a1c69ef52a68.png)
after:![after](https://user-images.githubusercontent.com/3411710/133878100-b7ca1898-2d9b-40a3-9a05-faa0d8e1f577.png)

**Comment by walkerxk** [comment]
i use the version i build from newest git code and mintty 3.5.1, both them have the problem.

**Comment by mintty** [comment]
The screenshot shows actually "maximised", not "fullscreen"; anyway, this glitch slipped in with 2.9.0 (precisely, https://github.com/mintty/mintty/commit/46ce6686) via `win_fix_position`. Fixed locally.

**Comment by walkerxk** [comment]
yes, i made a mistake, it's maximised, not fullscreen. do you mean this couldn't be fixed? why do you add win_fix_position?

**Comment by mintty** [comment]
Function win_fix_position tries to make sure the window is placed within the (current) screen. So if you change window size while in Options and that makes the window larger so it reaches out of the screen area, it should be automatically repositioned into the screen on "Apply". I confined this handling to non-full size windows (not yet uploaded).

**Comment by walkerxk** [comment]
thanks for you work.

**Comment by mintty** [comment]
Released 3.5.2.

**Comment by mintty** [comment]
Released 3.5.3.
