### ISSUE TITLE
Glass transparency option added back in?

### ISSUE THREAD

**Issue by Gold-Phoenix** [mintty/mintty#1128]
Is there any chance that Glass Transparency can be added back into options? I'm running windows 7 and have had to revert back to mintty-1.4.0 to have this.

Thank you

**Comment by mintty** [comment]
Glass mode was a Windows Vista feature and more or less dropped from Windows 7 (#207).
As it does not work anymore (at least not reliably), it got dropped also from the mintty Options menu but it's still described in the manual page as deprecated setting.
Noting also that transparency does not really cooperate with tabs, for those who care (#1069).

**Comment by Gold-Phoenix** [comment]
It didnt work strangely

![image](https://user-images.githubusercontent.com/15869633/137625356-faf7c2c2-2d84-4d95-b5dc-23f3a2af16ef.png)

**Comment by yashpalgoyal1304** [comment]
> mintty -o Transparency=glass

thanks a lot. it worked. and i gotta admit it looked good. thanks author (@Gold-Phoenix) for bringing it up.

**Comment by Ullaakut** [comment]
It's a shame that they are dropping support for it. For some reason it works just fine on Windows 11 on my end. It fixes the issue with the other way transparency is handled, which is that text also becomes transparent with other transparency options, while with the glass setting, text stays at full opacity, in front of a transparent background.

This makes the other way of doing transparency impractical and it impairs readability IMO.

Anyway, this is only an esthetical feature, so I guess it is not very important. Everything works just great with an opaque background.

**Comment by mintty** [comment]
Release 3.6.5, enabling transparency in tab sets. Please recheck.
