### ISSUE TITLE
emojies & warning: Illegal date format

### ISSUE THREAD

**Issue by ullaskunder3** [mintty/mintty#1129]
Can any one explain this...
Goal is to get emoji on vs code bash terminal 

I followed this gist for help but this throwing message like this

![image](https://user-images.githubusercontent.com/66258652/139809085-39814b93-7b96-4c44-8b8b-dcca63757d21.png)

But if we use `python -c "print('emojisCode')"` it shows up normally 
![image](https://user-images.githubusercontent.com/66258652/139810977-9962663a-cb06-4cbb-91d8-f8a7bf6464fe.png)

**Comment by mintty** [comment]
The warning is a minor glitch that will not happen once you've downloaded the files before (and try to update).
The "Download failed" isn't related to that and must be a local or temporary issue.

**Comment by mintty** [comment]
Released mintty 3.5.2.
