### ISSUE TITLE
MSYS2 installation 

### ISSUE THREAD

**Issue by WCHIHO** [mintty/mintty#1131]
0

After installing MSYS2 installer 32bit for Windows 10, I followed the instructions given on http://scipy.github.io/devdocs/building/windows.html#building-openblas to build OpenBLAS. After an apparent successful installation, I open a MSYS2 MinGW terminal and type the following: pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-i686-cmake git. I got the error message:

MSYS ~ $ pacman -S --needed base-devel mingw-w64-i686-toolchain mingw-w64-i686-cmake git error: mingw32: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown :: Import PGP key 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [Y/n] y error: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" could not be looked up remotely error: mingw64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown :: Import PGP key 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [Y/n] ????????????????????????????????????????????????

This error occurs throughout using other command: pacman -Syu.

The version of MSYS2 installed is:

Mintty 3.1.4 (i686 -pc-msys) Created by Andy Koppe/Thomas Wolff
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
I have been to this page about creating your own GPG key: fedoraproject.org/wiki/…. I entered the command "gpg2 --full-gen-key", in MSYS2 terminal. The command is not recognized.

**Comment by Biswa96** [comment]
May I ask some information about your current system? Is the MS Windows system 64-bit? 32-bit msys2 was deprecated long ago[^1]. We would suggest to use 64-bit msys2 installation.

[^1]: https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported

**Comment by mintty** [comment]
This is not a terminal issue.
