### ISSUE TITLE
A 'nul' is appended to text copied by selection

### ISSUE THREAD

**Issue by Marmotian** [mintty/mintty#1132]
Up to date Cygwin installation on Windows 10.

"Copy on select" is ticked in "Options -> Selection" dialog

Use left mouse button to select **_some_text_** in mintty window.

Clipboard will contain **_some_text_**\x00

Regressed to version "3.5.1 (x86_64-pc-cygwin" and problem goes away.

Config file attached for reference.
[[dot]minttyrc.zip](https://github.com/mintty/mintty/files/7646820/dot.minttyrc.zip)

**Comment by mintty** [comment]
Since 3.5.2, mintty also copies in the cygwin private clipboard format, in order to support a proper timestamp on /dev/clipboard. So the NUL glitch only occured when retrieving the clipboard via /dev/clipboard, not when copying from one terminal to another. Fixed.

**Comment by mintty** [comment]
Released 3.5.3.
