### ISSUE TITLE
some problems about bash in vscode

### ISSUE THREAD

**Issue by StarLeet** [mintty/mintty#1137]
I encountered some problems in the gitbash integrated by vscode.

I compiled a C program with UTF-8 (my system locale is GBK), everything in my gitbash shows "zh_CN.UTF-8", but when I run the .exe in vscode, it shows messy (If I open git-bash from the desktop and run this .exe, it shows normal). How should I deal with it?

I tried to change the character set in the shell script, but it didn’t work, or it succeeded, but the git-bash popped up

**Comment by StarLeet** [comment]
![无标题](https://user-images.githubusercontent.com/89691566/146911024-5eb9feaf-33ff-4cd7-890e-9929dd37d543.png)

**Comment by StarLeet** [comment]
I found that as long as it is not opened via "git-bash here", whether it is used in vscode or Windows terminal, garbled characters will be displayed. Is there anything special about bash opened by "git-bash here"?

**Comment by mintty** [comment]
First, when running a bash from VSCODE, are you sure it's mintty running? What happens if you open a menu (Alt+Space or mouse-right-click)? Windows terminal is not mintty either. So just to verify, with a terminal opened via "git-bash here" everything is fine?

**Comment by StarLeet** [comment]
Yes, no matter where you run a git-bash.exe from, everything looks good from the results.
The configuration in vscode is not git-bash.exe, but /bin/
bash.exe (because I don't want an external pop-up window).
I'm not sure if it is related to mintty, but I hope to get some help. Because I don't know what is the difference between git-bash.exe(Well done) and bash.exe(Not good), maybe git-bash.exe did extra at startup Working?
![1](https://user-images.githubusercontent.com/89691566/147014609-21cbca6a-2ed3-4110-b5ae-1d5d48694072.png)

**Comment by mintty** [comment]
It's not related. Mintty is a stand-alone terminal application (which would in turn run bash.exe). In your setup, the "shell" (bash.exe) is run directly in some other environment, not a terminal.

**Comment by avih** [comment]
> not a terminal.

It's a terminal, just not mintty. IIRC it's xterm.js or some such, in vscode.

**Comment by StarLeet** [comment]
Thanks,all guys，help a lot
