### ISSUE TITLE
Does mintty support 24-bit color in emacs?

### ISSUE THREAD

**Issue by netjune** [mintty/mintty#1140]
I tried with the guide in this page(https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html). It seems that it doesn't work for emacs 26.3.

```
$ cat terminfo-custom.src

xterm-emacs|xterm with 24-bit direct color mode for Emacs,
  use=xterm-256color,
  setb24=\E[48\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&\
     %d\:%p1%{255}%&%dm,
  setf24=\E[38\:2\:\:%p1%{65536}%/%d\:%p1%{256}%/%{255}%&\
     %d\:%p1%{255}%&%dm,

$ tic -x -o ~/.terminfo terminfo-custom.src

$ TERM=xterm-emacs emacs -nw
```

**Comment by mintty** [comment]
Mintty supports 24-bit colours. How to enable any application to actually use it is not really a terminal issue.
Anyway, terminfo entries xterm-direct and mintty-direct should work to achieve this.
However, if you install them into your personal account, you'll also have to set environment variable TERMINFO=~/.terminfo to announce them to the libraries.

**Comment by netjune** [comment]
Before I run `tic -x -o ~/.terminfo terminfo-custom.src`, emacs couldn't start and said that it can't find xterm-emacs in terminfo.
After I run `tic -x -o ~/.terminfo terminfo-custom.src`, emacs starts OK. But I see too less colors in emacs, even less than the old 256 colors.

**Comment by mintty** [comment]
As far as I know, the terminfo capabilities are called setaf and setab, not setf24/setb24. Maybe that's the problem.
Otherwise, as said before, mintty always supports the colour control escape sequences, regardless of TERM or TERMINFO settings.

**Comment by BrianInglis** [comment]
Alternates are setb/setf - see *terminfo*(5) for all the details about supported colour mappings and [supported escape sequences](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html) for using those colour mappings.

**Comment by netjune** [comment]
> As far as I know, the terminfo capabilities are called setaf and setab, not setf24/setb24. Maybe that's the problem. Otherwise, as said before, mintty always supports the colour control escape sequences, regardless of TERM or TERMINFO settings.

It seems that I should upgrade emacs to 27.1. I will try.

**Comment by netjune** [comment]
I have no time to try. Close it first. Thanks.
