### ISSUE TITLE
Version info not showing up for CyberArk

### ISSUE THREAD

**Issue by Shygar** [mintty/mintty#1141]
On a computer with CyberArk installed, the mintty version and publisher is not showing up. However, many other apps are showing up, like cmd.

Steps to reproduce:

1. Install CyberArk (was done for me, so not clear on configuration)
2. Find mintty.exe and right click. Choose Run as Administrator
3. View the version always shows as 0.0.0.0

mintty:
![mintty_no_version](https://user-images.githubusercontent.com/2359678/150242328-21e7c10e-f8fa-4bcc-ae18-171ceef2fc9b.png)

cmd (example of a program that works):
![cmd_version](https://user-images.githubusercontent.com/2359678/150242377-63bf9969-ff5b-416e-ace3-ca489e994087.png)

**Comment by mintty** [comment]
So what's the interface used by CyberArk to retrieve the version?

**Comment by mintty** [comment]
If you right-click on the mintty exe file (in Explorer) and display the Properties - Details tab, the version is shown.
So mintty does provide the version by some standard means. Please report this issue to CyberArk.

**Comment by Shygar** [comment]
Sure, I can try that, but virtually all applications and exe files on my computer display this information. mintty is one of the few that doesn't. So I thought it must be pulling from somewhere that isn't defined in mintty.

**Comment by mintty** [comment]
Mentioning other applications does not help identify what CyberArk is expecting. Please ask them.

**Comment by BrianInglis** [comment]
There are no problems when running `mintty --version`, *SysInternals* `sigcheck`, or `Explorer`/`mintty`/Properties/Details:
```
$ mintty --version
mintty 3.5.2 (x86_64-pc-cygwin)
© 2013/2021 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
$ sigcheck `cygpath -m /usr/bin/mintty.exe`
Sigcheck v2.73 - File version and signature viewer
Copyright (C) 2004-2019 Mark Russinovich
Sysinternals - www.sysinternals.com
c:\...\bin\mintty.exe:
        Verified:       Unsigned
        Link date:      17:00 1969-12-31
        Publisher:      n/a
        Company:        Andy Koppe / Thomas Wolff
        Description:    Terminal
        Product:        mintty
        Prod version:   3.5.2
        File version:   3.5.2.0
        MachineType:    64-bit
```
![Explorer-mintty-Properties-Details](https://user-images.githubusercontent.com/23089181/150413829-8219a598-a3b5-4b4a-b694-d0547f020d07.png)

**Comment by mintty** [comment]
Windows has an incredible multitude of methods to retrieve some kind of version information from a file, some demonstrated by Brian. For all I tried, mintty reports its version like cmd.exe does. If CyberArk uses one peculiar method that happens not to work at mintty, it's their bug. Closing as invalid.

**Comment by mintty** [comment]
Thanks for contacting CyberArk as mentioned in the other issue. I contacted them too but got no response...
