### ISSUE TITLE
[3.5.3] mintty -B void no longer responds to Win-left/Win-right

### ISSUE THREAD

**Issue by jeremyhetzler** [mintty/mintty#1143]
Previously (3.5.2), mintty responded normally to Win-left arrow and Win-right arrow, snapping the window to the left or right sides of the screen. In 3.5.3, it ignores these key combinations. Attempting to snap the window to the sides of the screen by dragging also does not work. Win-up and Win-down still work.

This only happens with -B void. Without that switch, mintty responds normally.

This is on Windows 10 1904.1466; also on Windows Server 2019.

**Comment by mintty** [comment]
For me, mintty 3.5.2 and older versions don't react to this either. Mintty itself would not "respond" to these Win-combinations anyway, it's a Windows function. Maybe you have a tool (like AutoHotkey) that converts it to some window action?

**Comment by jeremyhetzler** [comment]
The snapping function does require Settings > System > Multitasking > Snap Windows to be set to On. I forgot that wasn't the default, sorry.

Win-left/Win-right still works in 3.5.3 with "-B frame" or no -B switch. It's just "-B void" where it doesn't work.

It makes sense that this is a function of the window manager. But somehow "-B void" is behaving differently.

**Comment by jeremyhetzler** [comment]
Upon further testing, I can't reproduce the old behavior under 3.5.2 or 3.5.1 using my current version of Windows. They both behave the same as 3.5.3: with "-B void" the Win-left/right shortcuts don't work, without "-B void" they do.

I guess this is more likely the result of a recent change to Windows than a recent change to mintty. I'll just use -B frame going forward.

Thanks for your help.
