### ISSUE TITLE
Lose control of terminal when using `Ctrl-r`

### ISSUE THREAD

**Issue by yszhang95** [mintty/mintty#1146]
Hi, I wants to edit an old command from the history.

For example, I typed `ls` and then I want to modify it to `ls -a`. In the case that I have already typed `ls`, I tried to type `C-r`, (control + r), followed by `ls`. Then I can type `enter`, it list the directory immediately. But I type `tab` instead, the I lose the control of `mintty`. The terminal tab show no responses.

I can type `C-c`. It may interrupt `cygwin` shell in a few seconds but it does not work under `wsltty`.

I tried to search similar issues but I cannot find any.

Is this an expected/known behavior?

**Comment by mintty** [comment]
Command input, filename completion, shell history searching, and even interruption are all handled by the shell.
This is not a terminal issue.
