### ISSUE TITLE
[Feature request] Add syntax highlight 

### ISSUE THREAD

**Issue by eugenov** [mintty/mintty#1147]
Hello!
Is there any plans to implement syntax highlighting? Examples: mobaxterm, xshell.
Thank you!

**Comment by mintty** [comment]
Syntax highlighting is a feature of applications, not terminals.
A colourful prompt or command line highlighting are provided by some shells.

**Comment by eugenov** [comment]
Well, mobaxterm is the best example, as it is based on cygwin. I don't know what colors output (some application or smth else), but that is what I see:
![image](https://user-images.githubusercontent.com/61651148/158659993-7c3ece9a-4b57-4751-a504-4b71f0e3fcdb.png)
I can set custom colors for expressions based on regex. It is nice, isn't it?

**Comment by mintty** [comment]
I see. Anyway, it's not a traditional terminal feature and it interferes with colour controls that can be used by applications to set terminal colours explicitly. I'm not convinced this would be a good feature.

**Comment by eugenov** [comment]
Ok, thanks for the answer!
