### ISSUE TITLE
Cursor style DECRQSS returns inaccurate default value

### ISSUE THREAD

**Issue by richardg867** [mintty/mintty#1154]
When querying the current cursor style (DECSCUSR) using a DECRQSS sequence, mintty defaults to a cursor style value of 1 (corresponding to a blinking box cursor), which may not reflect the default cursor style configured by the user:

```
$ # default style (blinking line)
$ echo -e '\033P$q q\033\\'
$ :1$r1 q^[\
$ # inaccurate, 1 is blinking block
$ # changed to another style option (steady box)
$ echo -e '\033P$q q\033\\'
$ :1$r1 q^[\
$ # inaccurate, 1 is blinking block
```

The returned value only changes when the cursor style is overridden by a DECSCUSR sequence:

```
$ # set blinking underline
$ echo -e '\033[3 q'
$ # query again
$ echo -e '\033P$q q\033\\'
$ :1$r3 q^[\
$ # accurate, 3 is blinking underline
```

The value should instead default to the user-configured cursor style, as done by xterm, despite its documentation stating 1 is the default:

```
$ # fresh xterm session with the default steady block cursor
$ echo -e '\033P$q q\033\\'
$ :1$r2 q^[\
$ # accurate, 2 is steady block
```

**Comment by mintty** [comment]
> The value should instead default to the user-configured cursor style

I don't think so, see https://vt100.net/docs/vt510-rm/DECRQSS.html

**Comment by mintty** [comment]
Arguably the response should reflect the currently effective state. Checking again, this is not always the case. Same with xterm, actually, when switching blinking from the menu.

**Comment by richardg867** [comment]
In this case, I'm developing an application which switches to a different cursor style on the Alternate Screen Buffer, and resets to the default style when going back to the main buffer (since the 1049 sequences are known to not save the cursor style). As far as I understand it, my options for that are:

* Full terminal reset;
* Save the cursor style reported by DECRQSS then set it after exiting the alternate buffer, hence this issue;
* Some terminals support a non-standard DECSCUSR 0 to reset the cursor style, per microsoft/terminal#1604.

**Comment by mintty** [comment]
Two remarks:
Many terminal don't support the sequence at all, so it's not promising for a portable solution.
You might try to convince Thomas Dickey to change the "0" behaviour for xterm.

**Comment by BrianInglis** [comment]
> In this case, I'm developing an application which switches to a different cursor style on the Alternate Screen Buffer, and resets to the default style when going back to the main buffer (since the 1049 sequences are known to not save the cursor style). As far as I understand it, my options for that are:
> ...

* Leave the cursor style as is because the user chose it so they can see it easily! If it's no longer a blinking block, I'm going to be unhappy if I can't easily find it! 
Like those who assume message text will be displayed on black backgrounds (rather than cream, so yellow sucks as badly as it does on white - use colour blindness-friendly orange please), without checking, or ensuring in the message background attribute that is so, and without allowing customization so I can change it or at least disable it easily with `--color=never|none|off|no|f|0|disable[d]` ;^> 

If you allow the cursor to be changed on the alternate buffer, that should be an option to select the default or required cursor attributes, and perhaps icon! SMOP

**Comment by richardg867** [comment]
> Many terminal don't support the sequence at all, so it's not promising for a portable solution.

I'm aware 0 is not portable; my cursor style reset code uses DECRQSS as a primary source for the default style, and falls back to 0 if no DECRQSS response is received.

> * Leave the cursor style as is because the user chose it so they can see it easily! If it's no longer a blinking block, I'm going to be unhappy if I can't easily find it!

In my case - an IBM PC emulator to which I'm adding a terminal-based renderer - I set the alternate buffer's cursor style to a blinking underline to mimic hardware behavior. I'll keep that in mind, though.

**Comment by BrianInglis** [comment]
Always had a blinking block cursor from Tandy 1000 (with PCjr Graphics) days; see
[Emulating IBM PC Cursors](https://www.pcjs.org/blog/2018/03/20/). 
If not supported by the OEM (Tandy/Radio Shack) provided utility programs e.g `mode`, utilities were created using assembler scripts for the provided `debug` utility to produce .com programs (start base 0x100? IIRC) to make *DOS* or *BIOS* `int` calls, change *BIOS* data area settings, reprogram some controller registers, and even hook int vectors to allow small *Terminate and Stay Resident* programs to maintain your settings.

**Comment by mintty** [comment]
Checking again, behaviour is consistent both with xterm and with the DEC spec, taken literally. Closing.
