### ISSUE TITLE
Treatment of whitespace in scp

### ISSUE THREAD

**Issue by pmor13** [mintty/mintty#1160]
In mintty 3.5.0 I can use whitespace in `scp` as:
```
$ scp xxx@yyy:\ /xxx/yyy .
yyy                                                                                    100% 2532    17.2KB/s   00:00
```
This whitespace is useful because the `/xxx/yyy` can be erased using `CTRL + W`.

However, in mintty 3.6.1 it does not work:
```
$ scp xxx@yyy:\ /xxx/yyy .
scp:  /xxx/yyy: No such file or directory
```

Any ideas?

Note: `bash` in the same:
```
$ bash --version
GNU bash, version 4.4.12(3)-release (x86_64-unknown-cygwin)
```

**Comment by mintty** [comment]
No, and this is certainly not a terminal issue.
Maybe you're using the Windows version of scp? (`type scp`)

**Comment by mintty** [comment]
Interpreting the escaping in `scp xxx@yyy:\ /xxx/yyy .` the command is equivalent to `scp "xxx@yyy: /xxx/yyy" .` which means copy as user xxx from remote machine yyy the file " /xxx/yyy", with a leading space. This is incorrect path usage, as confirmed by the error response `scp:  /xxx/yyy: No such file or directory` with two spaces after the ":".
I have no idea why this would have worked previously (and honestly I doubt it did) but the current error is proper.
Anyway, still not a terminal issue.

**Comment by pmor13** [comment]
@mintty Need for opinion / advice: is there any way / trick to erase `/xxx/yyy` at once (e.g. using `CTRL + W`) while keeping `xxx@yyy:`?

The problem is that if using `scp xxx@yyy:/xxx/yyy` followed by pressing `CTRL + W` erases `xxx@yyy:/xxx/yyy`, which is unwanted.

**Comment by BrianInglis** [comment]
If shell e.g. `bash` uses `readline` or otherwise supports `emacs`/`vi` editing, then under default `readline` `emacs` mappings, *\<ALT\>B*/*F* moves by word, so *\<ALT\>B* back to /xxx, insert space, *\<ALT\>F* forward, use *\<CTRL\>W* to delete word back to space. Or *\<ALT\>\<CTRL\>j* to switch to `vi` insert mode, *\<ESC\>* for move mode, *\<CTRL\>\<LEFT\>*/*\<RIGHT\>* to move, etc.
