### ISSUE TITLE
KeyFunctions consumed by ncurses app (eg. mc)

### ISSUE THREAD

**Issue by 3dom3k** [mintty/mintty#1161]
Hi,

I have defined my own shortcut using `KeyFunctions=A+Left:switch-prev;A+Right:switch-next;`. It works in bash, so I can switch between mintty tabs by pressing Alt+arrows.

But when I launch Midnight commander, it "steals" those shortcuts and uses them for it's internal functionalities, for example in it's built-in editor it selects text (extends/shrinks) selection.

Imho: mintty should be the first who utilizes the keypress, and if it has no action assigned to it, just then it should pass it to app.

Thanks.

**Comment by mintty** [comment]
This seems to be a specific limitation for assignments to the "small keypad" or "editing keypad" keys. In general, assignments work in mc, for example you could use the numeric keypad cursor keys:
`KeyFunctions=A+KP_Right:switch-next`
To be checked.

**Comment by mintty** [comment]
Fixed in repository, you can build yourself for testing.

**Comment by mintty** [comment]
Released 3.6.2.
