### ISSUE TITLE
Keyboard backlight turns off when Mintty window brought to forefront

### ISSUE THREAD

**Issue by NorthDecoder** [mintty/mintty#1165]
With a fresh install of

* git version 2.37.0.windows.1

which has

* mintty version 3.6.1 (x86_64-pc-msys)[Windows 19043]

The **keyboard back-light turns off** whenever the mintty window is brought to the forefront. When I push the back-light toggle button on the keyboard the light flashes on for a fraction of a second, then off. I want the keyboard back-light to always be on. When another window is brought to the forefront the back-light turns on. When the mintty window is exited the back-light turns on. No other applications have this feature.

Under the mintty options drop down menu, there seem to be no settings for this feature.

In web searches Xset is referenced, however it looks like that is not available by default with mintty.

What do you recommend?

**Comment by NorthDecoder** [comment]
Keyboard is Cooler Master Devastator II, Model SGB-3030-KKMF-1-US

**Comment by NorthDecoder** [comment]
In file `config.c`  I see  `{"ManageLEDs", OPT_INT, offcfg(manage_leds)}` which defaults to 7.  The readme seems to say this is a command line option that is called by whatever program is starting Mintty. I am guessing it is MINGW64?

**Comment by mintty** [comment]
You can start mintty explicitly with an option or configure it in a config file.
Please try values 3, 5, 6 for ManageLEDs. Or 0 if necessary. Which setting fixes the issue?

**Comment by rimrul** [comment]
Looking at various external sources the state of the backlight seems to be indeed tied to the state of the scroll lock LED. Setting `ManageLEDs=3` in `~/minttyrc` should fix that.
 https://linustechtips.com/topic/720120-fixing-cm-devastator-ii-backlight/
https://askubuntu.com/questions/1050632/cant-turn-on-backlight-for-cooler-master-devastator-ii-keyboard-on-ubuntu-18-04
https://www.reddit.com/r/linux_gaming/comments/c1yrun/cooler_master_devastator_2_other_keyboards/

@mintty how do you feel about a PR to add this to the options dialog?

**Comment by mintty** [comment]
Thanks, I think I'll add a note to the wiki Tips page.
The options dialog is deliberately kept lean, not to overwhelm users with lots of specialized settings like some software does.
