### ISSUE TITLE
mintty vs wsltty

### ISSUE THREAD

**Issue by yashpalgoyal1304** [mintty/mintty#1166]
I am using MSYS2, and have used mintty via that. I recently installed WSL and came to know about [wsltty](https://github.com/mintty/wsltty).

* What is the difference between mintty & wsltty? 
* can't the separation between them be diminished somehow? 
* so that, say that mintty supplied via msys2 itself can be made to function like wsltty with some addon etc??

i dont have any concrete stuff, i am just asking and want to know.

(i liked mintty a lot, but the TUI editors i tried - vim, micro, etc - dont like it, so, i had to give it up and find alternate)

**Comment by mintty** [comment]
People use standard editors in mintty - what's the problem here?
Mintty is a terminal application running in cygwin/MSYS operating environments.
Wsltty is the same application bundled as a stand-alone installation.
If you install wslbridge2 in your /bin, mintty --WSL will work like wsltty.
wslbridge2 could be made a cygwin package, or its functionality integrated into mintty, at some effort...

**Comment by yashpalgoyal1304** [comment]
> People use standard editors in mintty - what's the problem here?

Following Error shown only on `mintty`, not in any other among: `conhost` , `alacritty` , `wezterm`. I have also mentioned this before at : https://github.com/msys2/MSYS2-packages/issues/2744#issuecomment-1035929168

```bash
$ vim
Vim: Error: This version of Vim does not run in a Cygwin terminal

$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 22:11:39)
```
----------
> Wsltty is the same application bundled as a stand-alone installation

so, wsltty = standalone mintty + wslbridge2 right?

> If you install wslbridge2 in your /bin, mintty --WSL will work like wsltty.
> wslbridge2 could be made a cygwin package, or its functionality integrated into mintty, at some effort...

ohkayh, yeah, the former one (making wslbridge2 to be a cygwin/msys2 package) was what i meant. nice to know it's possible.

**Comment by yashpalgoyal1304** [comment]
> People use standard editors in mintty - what's the problem here?

Following Error shown only on `mintty`, not in any other among: `conhost` , `alacritty` , `wezterm`. I have also mentioned this before at : https://github.com/msys2/MSYS2-packages/issues/2744#issuecomment-1035929168

```bash
$ vim
Vim: Error: This version of Vim does not run in a Cygwin terminal

$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 22:11:39)
```

**update:** retried `micro` in mintty just now, it is not even executing, while it does happily in `wezterm`. the "existing output gone on exiting micro" issue is there in wezterm too.

I dont quite remember what the problem was with `micro` editor. IIRC, when i exit the micro, the existing output is all gone, and micro inside mintty also glitched a lot when i resized the terminal window size.

**Comment by BrianInglis** [comment]
Which distros of `mintty` and `vim` are those - *Msys2*/*Mingw64*? 
Do you have a TERM environment variable set? 
Even *Windows* `vim` runs under *Cygwin* `mintty` (started from `Xwin`):
```
$ echo $DISPLAY
:0
$ echo $TERM
xterm-256color
$ TERM=cygwin /proc/cygdrive/c/Program\ Files/Vim/vim90/vim
```
and also from *Cygwin* 32 `mintty` in a console window. 
I had refresh problems with *Linux* `vim` under "wsltty" running `mintty` with `wslbridge` and ...2.

**Comment by yashpalgoyal1304** [comment]
hey @BrianInglis , i am sorry, i cant understand what you want to say.  still, i'd try to fill in:

* my vim is windows vim, installed in "program files (x86)"
* mintty came via msys2, yes
* how to start `mintty` from `xterm` ? i dont have much info about "TERM"
* i have not installed wsltty or wslbridge2 or anything like that

following is the output on my system (the last command took from : https://github.com/msys2/MSYS2-packages/issues/2741#issuecomment-993220365 )

```bash
$ echo $TERM
xterm

$ echo $DISPLAY


$ echo $DISPLAY | od -c
0000000  \n
0000001
```

**Comment by mintty** [comment]
Assuming you may be running a Windows program, it may depend on ConPTY support which is disabled by default in MSYS.
Run `mintty -o ConPTY=on`.

**Comment by yashpalgoyal1304** [comment]
running that command, and vim in the newly launched instance works 👍. so, should i set that value to “on” permanently in the minty config file? will there be some downside to that?

> Assuming you may be running a Windows program, it may depend on ConPTY support which is disabled by default in MSYS.
Run mintty -o ConPTY=on.

**Comment by yashpalgoyal1304** [comment]
> wslbridge2 could be made a cygwin package, at some effort...

also, is this important enough to be opened as a separate issue for keeping track of?? asking as this one was kinda more like a discussion and has took a different topic too!!

**Comment by BrianInglis** [comment]
>> wslbridge2 could be made a cygwin package, at some effort...

> also, is this important enough to be opened as a separate issue for keeping track of?? asking as this one was kinda more like a discussion and has took a different topic too!!
> **edit:** oh, if opening, that issue would go to https://github.com/Biswa96/wslbridge2/

Ideally that would be adopted by a maintainer using a Fedora Cygwin cross-build environment to also build and package the wslbridge2 backend. 
I found that Fedora gcc and glibc releases (used to) trail other common distros, so those builds were more compatible across common Linux releases I tried the same backend binary on.

**Comment by mintty** [comment]
> should i set that value to “on” permanently in the minty config file? will there be some downside to that?

I am not aware of any downside or a reason why the MSYS folks still hesitate to enable it by default.
It can also be enabled by an environment variable (`MSYS=enable_pcon`).

> wslbridge2 could be made a cygwin package, at some effort...

Actually I have just had a fancy idea to craft a much simplified wslbridge3 instead...

> I found that Fedora gcc and glibc releases (used to) trail other common distros, so those builds were more compatible across common Linux releases I tried the same backend binary on.

Does that include those distributions that are based on the musl library rather than glibc? For wsltty, I build the backend with Alpine Linux to the same aim.

**Comment by BrianInglis** [comment]
Most common *Linux* distros use *glibc*, which is why those distros are used to build `wslbridge`/2 backend, so it can run on any of those distros using *glibc*. Builds with older *Linux* and *glibc* releases will be more compatible across other similarly based distros.  
*Alpine* builds will only be usable on distros using *musl*, which are not very common, and running with compatible releases. There may also be greater variations in *Linux* and *musl* releases used across those systems, so compatibility may be harder to determine.

**Comment by mintty** [comment]
Unless something has changed recently, the musl build of wslbridge2 also runs on glibc systems, that's why I bundle it with wsltty.

**Comment by yashpalgoyal1304** [comment]
hey, taking a step back and asking a dumb question 
* mintty without wslbridhge - doesnt launch the wsl right??
* so, wslbridge is like fundamental to getting wsl running, 
* **or** is its function something other/specific?

i got confused regarding this, as:
* the other terminal i was using (not the MS terminal) launched wsl straightaway, 
* while mintty just stood there with a blank line followed by a blinking cursor. and 
* there is no mention of smth else to be required for launching wsl on the official site either

**Comment by yashpalgoyal1304** [comment]
> Actually I have just had a fancy idea to craft a much simplified wslbridge3 instead...

if you are seriously saying, then dont name it with prefix 3 though 😅 . better to keep the version in sync with version of wsl

**Comment by mintty** [comment]
> while mintty just stood there with a blank line followed by a blinking cursor - i had to ^c to terminate that command

How did you invoke it?

Mintty runs wsl also without wslbridge, just run `mintty wsl`. However, the MS program `wsl` implements its own idea of a terminal and many mintty terminal features would then not be available.

**Comment by yashpalgoyal1304** [comment]
```bash
mintty
debian
```


https://user-images.githubusercontent.com/19423063/178261975-c6bddfcc-3ec4-4134-b528-e91af4774efd.mp4

**Comment by mintty** [comment]
Do you run wsl V2? What does `wsl -l -v` say?

**Comment by Biswa96** [comment]
Running debian.exe is same as running wsl.exe. The debian.exe calls WslLaunchInteractive or WslLaunch APIs which internally runs wsl.exe with same command line options. Source https://salsa.debian.org/debian/WSL/-/blob/master/DistroLauncher/WslApiLoader.cpp

**Comment by yashpalgoyal1304** [comment]
not v2, i am running wsl-v1:

```
$ wsl -l -v
  NAME      STATE           VERSION
* Debian    Stopped         1
```

**Comment by yashpalgoyal1304** [comment]
yeah, have got it working via wslbridge2 msys2 package, the prompt doesnt have colors, but it's fine with me for now 😇 
thanks a lot for pulling through (:

![vivaldi_iYradzr4kV](https://user-images.githubusercontent.com/19423063/178277695-8540a440-5e7a-45a0-bf35-18a567bb094b.png)

**Comment by yashpalgoyal1304** [comment]
**Self Notes/Observations**
feel free to ignore or hide this comment as OFFTOPIC if it so seems to be

----

`wsl` launches the default distro like Biswa96 mentioned above, so, use this instead of `debian` for the time being to maintain consistency in issue reporting

1. wslbridge2 doesnt bring any change in what the `wsl` or `mintty wsl` commands do in normal mintty, i.e. same situation as above video recording
2.  ... it just changes the behaviour of `mintty --WSL`
3. `wslbridge2` is like an alternate command to `wsl` ; refer [README](https://github.com/Biswa96/wslbridge2#options)
4. ... and it's better ∵ output isn't cleared while exiting it as with `wsl` (comparison relevant only for those terminals which open both of these inline)

----

1. Comparison of default prompts in the other terminal, vs mintty --WSL:
3. using the second prompt in `mintty --WSL` brings colors (ofc):
4. the error screen shown on `mintty --WSL` when wslbridge2 is not installed

```bash
PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\u@\h:\w\$ "

PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
```

![vivaldi_2BaGBJHASA](https://user-images.githubusercontent.com/19423063/178281738-caebfb95-7f47-4910-9032-577efe679489.png)


![wezterm-gui_12YobdvGMO](https://user-images.githubusercontent.com/19423063/178283465-1e2b1464-9ad9-4545-a216-5ef57da79737.png)
