### ISSUE TITLE
How to setup mintty session logging for multiple teminals?

### ISSUE THREAD

**Issue by CatalinSoare** [mintty/mintty#1167]
Hello,

I believe the simplest way is to have logfiles with timestamps in their name

What I'm trying to achieve here is basically as the title says, I want to be able to log multiple parallel sessions, but I don't understand the [syntax](https://mintty.github.io/mintty.1.html) for log file naming. 
It mentions "If FILE contains %d it will be substituted with the process ID. ". I've tried to setup a windows shortcut with this target:
`C:\cygwin64\bin\mintty.exe -o Logging=yes -l C:\cygwin64\logs\%d.log -i /Cygwin-Terminal.ico -`
but that only generates a file called "d.log".

I even tried to create a batch file that launches mintty and starts it with a timestamp generated by the batch script, but the %DATE%... vars are getting passed to mintty so that didn't help.

Can anybody please help with an example?

LE: I am running mintty v 3.6.1, that came installed with cygwin.

Thanks

**Comment by mintty** [comment]
Try POSIX pathname syntax instead: `-l /logs/%d.log`.

**Comment by mintty** [comment]
Actually, I can't reproduce the issue.  Even with Windows pathname in a shortcut as described it works for me.

**Comment by CatalinSoare** [comment]
> Actually, I can't reproduce the issue. Even with Windows pathname in a shortcut as described it works for me.

So, for you it works with something like `-l c:\cygwin64\logs\%d.log`?

Even this would help me at the moment, since I would love to be able to have separate logs for each mintty session. But since it doesn't interpret the %d, it just leaves the file called 'd.log' and the next session complains that it won't overwrite it.
Ideally, it would be to be able to generate a timestamp for each logfile similar to gnu's date format.

**Comment by mintty** [comment]
You can also use a strftime pattern, like for option SaveFilename. For some reason, this is missing in the manual page...

**Comment by mintty** [comment]
... no, it's not. It's mentioned there and described with option Log.

**Comment by CatalinSoare** [comment]
Hey, you were right, of course! :)
But since I couldn't find any examples online and with limited time for playing, it took me a while to understand it.

If you ask me, I would add this as an example to the documentation, because there aren't any?
In my case, I basically created a shortcut (pin to taskbar) with the following target:

`C:\cygwin64\bin\mintty.exe -l "/logs/mintty_%Y-%m-%d_%H-%M-%S.log" -i /Cygwin-Terminal.ico -`

The Windows path for logging also works:

`C:\cygwin64\bin\mintty.exe -l "/logs/mintty_%Y-%m-%d_%H-%M-%S.log" -i /Cygwin-Terminal.ico -`

This fixes my issue of having separate logs for each separate mintty session!

Thank you!
