### ISSUE TITLE
can i change transparency level with a shortcut?

### ISSUE THREAD

**Issue by walkerxk** [mintty/mintty#1168]
i'm using KeyFunctions=t:cycle-transparency-level now,but i don't want to use low and medium, i just use off when i want to screenshot something, and after that, i change back to high
KeyFunctions=o:transparency=off;h:transparency=high didn't work for me.

**Comment by mintty** [comment]
The effect corresponds to setting `Opaque when focused` I assume, so if I make that switchable by a hotkey, that would be the desired funvction, right?

**Comment by mintty** [comment]
Easiest implementation was a temporary override, user-definable function `transparency-opaque`.
It's not a switch, however; previous transparency will be restored on next applicable occasion, e.g. when leaving/entering the window.

**Comment by walkerxk** [comment]
transparency-opaque seem good for me, but i don't know if i use screenshot hotkey of another application, this is consider as leaving the window?

**Comment by mintty** [comment]
Released 3.6.2.

**Comment by walkerxk** [comment]
thank you very much

**Comment by mintty** [comment]
Thanks for closing but your previous comment is valid, this temporary state is clear if the window gets defocussed.
Maybe the hotkey of some screenshot application (which?) works anyway, but for others it won't, so the solution needs improvement...

**Comment by mintty** [comment]
New user-definable function toggle-opaque replaces transparency-opaque.

**Comment by mintty** [comment]
Released 3.6.3.
