### ISSUE TITLE
Paste of several consecutvie commands not working in Cygwin

### ISSUE THREAD

**Issue by emanalo69** [mintty/mintty#1170]
I have reinstalled my cygwing tool over Windows 10. I see the version is mintty 3.6.1.
The following feature doesn't seem to work preperly:
1. Copy a set of lines/commands from a text file. These commans are separated by an end-line. For example:
get CXC4012510
get . advancedDlSuMimoEnabled
get CXC4012590
2. Paste them on Cygwin. All commands should be executed, one by one.

What I see now is that the commands are pasted in the cygwin window, and "wait" until I press enter. Whenver I press enter, ONLY the firs one is executed and the remaining ones are ignored.

GBM80BB2> get CXC4012510
get . advancedDlSuMimoEnabled
get CXC4012590

I'm not sure if its due to a bug latest version I installed or is it some setting that was override or,

Any help?

Thanks and best regards,

Manuel Alonso

**Comment by mintty** [comment]
#1138

**Comment by emanalo69** [comment]
Thank you very much.

Issue is solved.

Best regards,

Manuel Alonso
