### ISSUE TITLE
Line cursor invisible (zero sized) if cell_width is small enough

### ISSUE THREAD

**Issue by paolo-sz** [mintty/mintty#1175]
After fixes for #1157 the line cursor had became invisible (zero sized) if the cell_width is small enough (< 8).
The "offending" line is this one:
https://github.com/mintty/mintty/blob/7c90db2788107a3f68c044eacff01b6e1dce0f17/src/wintext.c#L4120
where, if cell_width is less than 8 then caret_width is multiplied by 0.
Maybe it would be better to ensure a minimum value (eg. 1) in case caret_width is zero at that point.

**Comment by mintty** [comment]
I actually have the habit to close issues after the next release, but thanks anyway.

**Comment by mintty** [comment]
Released 3.6.2.
