### ISSUE TITLE
Text selection is by word, not by character / grapheme

### ISSUE THREAD

**Issue by kevinarpe** [mintty/mintty#1178]
I am using mintty 3.6.1 with Cygwin from Win 10 (19045) hosted on VirtualBox on Debian Linux.

![image](https://user-images.githubusercontent.com/4367212/199024577-b2adec48-e7ba-408d-8f3b-5a2ada5a8ded.png)

Strangely, the text selection is "by word" not "by character / grapheme".  I am a long time user, and I never saw this behaviour before.  (I am using Cygwin w/mintty for about 10 years.)  To be clear, I assume this is my mistake -- bad config.  I tried all the Selection options, no luck.

In the screenshot below, my username and hostname is hilited after select.  I only selected one grapheme in the middle of that "word".  I tried to move my mouse during click+drag, but the word always remains selected.

![image](https://user-images.githubusercontent.com/4367212/199024234-d28799ba-5843-45df-97d3-a744c4376293.png)

Here are my selection options.

![image](https://user-images.githubusercontent.com/4367212/199024816-004395df-692b-479c-b5ed-7d5e7b185057.png)

I am doing something wrong... or is this new (intentional) behaviour from mintty?  I would like to have selection "by character / grapheme".

Please kindly advise.

**Comment by mintty** [comment]
You don't describe how you got to that selection. Your prompt is normally not green? And then you click where? Once or twice? Maybe moving the mouse in between?

**Comment by mintty** [comment]
Could be that you accidently issued a double-click, maybe even due to hardware problem?
Anyway, for missing problem description, I'll need to close the issue soon.
