### ISSUE TITLE
has setting about crop background

### ISSUE THREAD

**Issue by lssler** [mintty/mintty#1180]
mintty auto crop image to fit background
in wintext.c static void load_background_image_brush(HDC dc, wstring fn)
change:
     HDC dc0 = CreateCompatibleDC(dc);
      HBITMAP oldhbm0 = SelectObject(dc0, hbm);

      // prepare destination memory DC, 
      // create and select the destination bitmap into it

      ///////////////////////////////////////////
      //crop image
      int imgw = w;
      int imgh = h;
      if(bw*h > w*bh)
      {
        imgw = w;
        imgh = bh*imgw/bw;
      }
      else if (bw*h < w*bh)
      {
        imgh = h;
        imgw = bw*imgh/bh;

      }
      w = imgw;
      h = imgh;

**Comment by mintty** [comment]
I am missing an explanation what this piece of code is meant to suggest or achieve...

**Comment by lssler** [comment]
> 我缺少解释这段代码旨在建议或实现的内容......

it keep picture proportions when window size changes, instead of scale image to fit window

**Comment by lssler** [comment]
> I am missing an explanation what this piece of code is meant to suggest or achieve...


it crop the picture to avoid deformation when window size changes, instead of scale image to fit window

**Comment by mintty** [comment]
I could try, but... could you clarify which of the background image modes is supposed to be affected?
How do you invoke mintty to get something that your patch changes?
Also, as I thought to have implemented all variations in the best way, what do you think is wrong about current behaviour?

**Comment by lssler** [comment]
background "_" is changed, it just change "scaled" to "crop".now ,i set background with "_", then window ratio  is  different from img ratio ,so, the img is scaled to window ratio. The code scale img with img's original  ratio.It looks better when change window size

**Comment by mintty** [comment]
> How do you invoke mintty to get something that your patch changes?

Please quote your command. Note there is a variation of behaviour already available, maybe prefix `%` to the image filename is what you want?
Otherwise, if you really mean to *crop* the image when resizing the terminal, it would not fill the complete background but would leave some empty area, which I do not consider desirable. On the other hand, there is also a tiling option `*`.

**Comment by lssler** [comment]
it will not has empty area,it will sacle until fill all area.

**Comment by lssler** [comment]
![无标题](https://user-images.githubusercontent.com/37359046/200127001-8552e3d1-54b2-467a-8087-7a3e6902b732.png)

**Comment by mintty** [comment]
I don't like guesswork investigation so much. You have still not answered my question how you invoke mintty to demonstrate the difference (i.e. which mode of Background=... you use). Also there are two similar locations in the source file where your patch would fit.

**Comment by mintty** [comment]
OK, if I guess right (:/) instead of simple tiling, you want to scale first, keeping aspect ratio, then tile.
This is not suitable for images (see below) but may be OK for patterns intended for tiling.
It would not be a change, however (see example) but rather a new mode.
![grafik](https://user-images.githubusercontent.com/12740416/200131493-0725f87d-5c9b-4fc7-b7af-202e16bf1284.png)

**Comment by mintty** [comment]
Prefix syntax could be `_*` (as these two functions are combined), `+`, `,` or `:`.

**Comment by lssler** [comment]
The code used in function "static void load_background_image_brush(HDC dc, wstring fn)"，in 1813 line

It is right scale first, keeping aspect ratio, then tile
The original tile is use pic size

**Comment by lssler** [comment]
If image is bigger then mintty size or more small ,the code can automatically scale img to suitable size.

**Comment by lssler** [comment]
If image is bigger then mintty size or more small ,the code can automatically scale img to suitable size.

**Comment by mintty** [comment]
> It is right scale first

or bottom scale first, depending on the dimensions.
This proposal needs some time to settle; it needs another flag and integration into the option.

**Comment by mintty** [comment]
I introduced this now with background image prefix `+` in either option `Background` or OSC 11.

**Comment by mintty** [comment]
Released 3.6.2.
