### ISSUE TITLE
Feature request: show which config files were parsed from options UI

### ISSUE THREAD

**Issue by pmmccorm** [mintty/mintty#1181]
This would help people figure out why they can't load their custom fonts :)

**Comment by mintty** [comment]
You mean custom fonts placed in a subfolder `fonts` of a config directory?

**Comment by pmmccorm** [comment]
Sorry for the delay! To take a step back: what I really want is for mintty to show all fixed width fonts on the system, not just a subset of them. Either way, I think it would be useful to show at runtime where the config comes from.

**Comment by mintty** [comment]
You didn't respond to my question; please describe your situation.
I could easily provide reporting output (to stdout, if started from a shell) listing the config dirs found; I don't see however how that would help debug the font issue.

**Comment by pmmccorm** [comment]
This was my mistake I figured out! I got confused about which fonts I had installed apparently. I am closing this, sorry for wasting your time.

**Comment by mintty** [comment]
Released 3.6.4.
