### ISSUE TITLE
Wiki > CtlSeqs > Terminal identification formatting glitch

### ISSUE THREAD

**Issue by oqibidipo** [mintty/mintty#1183]
There is a `|` in the second response string which throws the table formatting off.

```
| `^[[>0q` | `^[P>|mintty `_version_`^[\` | terminal identification query (xterm 354); _version_ like 3.1.5 |
```

| **request** | **response**                      | **comment** |
|:------------|:----------------------------------|:------------|
| `^[[>0c`    | `^[[>77;`_version_`;`_unicode_`c` | secondary devices attributes (DEC); _version_ like 30105, _unicode_ version when using built-in data |
| `^[[>0q`    | `^[P>|mintty `_version_`^[\`      | terminal identification query (xterm 354); _version_ like 3.1.5 |

Adding a backslash fixes that.
```
| `^[[>0q` | `^[P>\|mintty `_version_`^[\` | terminal identification query (xterm 354); _version_ like 3.1.5 |
```

| **request** | **response**                      | **comment** |
|:------------|:----------------------------------|:------------|
| `^[[>0q`    | `^[P>\|mintty `_version_`^[\`      | terminal identification query (xterm 354); _version_ like 3.1.5 |

**Comment by mintty** [comment]
Thanks.
