### ISSUE TITLE
Making your overstrike mode compatible with the DEC VK100

### ISSUE THREAD

**Issue by j4james** [mintty/mintty#1184]
Back when we were discussing Mintty's overstrike functionality in #1171, I said I didn't think there were any devices that allowed for that functionality to be turned on and off. But I've recently found there actually is a DEC terminal which supports overstrike - the [VK100](https://terminals-wiki.org/wiki/index.php/DEC_VK100) - and it can be turned on and off with a regular mode sequence (private mode 20).

So to enable overstrike mode, you'd do this:

```
printf "\e[?20h"
```

And to disable it again, you'd do this:

```
printf "\e[?20l"
```

It's not essential, but I thought since you already have support for overstrike, you might want to consider hooking it up to mode 20, so you'll have something that's actually compatible with a real terminal.

**Comment by BrianInglis** [comment]
The original GIGI "PC"  [See development memoir in comments](https://archive.org/details/bitsavers_decterminaGITerminalInstallationandOwnersManualApr_9201578) ReGIS graphics alternative to the VT125, which does not appear to support that mode. 
See mode OS OverStrike on page 68 in [GIGI Terminal Installation and Owner's Manual EK-VK100-IN-002](https://ia801900.us.archive.org/4/items/bitsavers_decterminaGITerminalInstallationandOwnersManualApr_9201578/EK-VK100-IN-002_GIGI_Terminal_Installation_and_Owners_Manual_Apr81_text.pdf#page=81)
Not documented in Thomas Dickey's [i-i.net](https://invisible-island.net/) [xterm ctlseqs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) - find last occurence of `CSI ? Pm h` or `CSI ? Pm l`

**Comment by j4james** [comment]
> the VT125, which does not appear to support that mode.

Yeah, I believe that's correct. I don't have access to a VT125 to test with, but there's no mention of it in the documentation I have.

Which reminds me, if you want to see how it works on a VK100, [MAME](https://www.mamedev.org/) has a at least a partially working VK100 implementation - good enough to mess around in local mode.

> Not documented in @ThomasDickey [GH snapshot](https://github.com/ThomasDickey/xterm-snapshots/blob/2a87de64ba3941afd0541a90c3225d8c04f3a7e2/ctlseqs.ms#L1326)

I think Thomas only includes the operations that XTerm actually supports. There are lots of modes and control sequences that aren't listed there.

**Comment by ThomasDickey** [comment]
The VK100 manual is careful to avoid stating that it is VT100-compatible (referring to VT52, ANSI and ReGIS), and does not describe the appearance of the *overstrike* mode.  That could be, for instance, either writing a strike-out bar across a character, or combining arbitrary characters (as done in printing terminals to get underlining or "bold").  The [_terminfo manpage_](https://invisible-island.net/ncurses/man/terminfo.5.html#h3-Basic-Capabilities) reminds me that the latter is more likely.  If the former is intended, that would be a different terminfo capability.

Interestingly, VT100/xterm don't use modes 20-23 which are listed for the VK100.

**Comment by j4james** [comment]
> The VK100 manual is careful to avoid stating that it is VT100-compatible

Yeah, it's not entirely VT100-compatible. It doesn't do the double-size line attributes, doesn't do margins, doesn't do custom tab stops, and doesn't do 132-column mode. And its SGR doesn't have bold, but it does actually have a limited support for ANSI color which is nice.

> That could be, for instance, either writing a strike-out bar across a character, or combining arbitrary characters

It's definitely combining arbitrary characters. Here's a screenshot from MAME showing how it looks (third line is a combination of the first line and second line):

![image](https://user-images.githubusercontent.com/4181424/202872104-c8e90a49-1bc2-48ec-9f82-21ea5af28eb5.png)

You can keep overwriting as many times as you like, but it quickly becomes an unreadable mess.

**Comment by BrianInglis** [comment]
> It's definitely combining arbitrary characters. Here's a screenshot from MAME showing how it looks (third line is a combination of the first line and second line):
> ![image](https://user-images.githubusercontent.com/4181424/202872104-c8e90a49-1bc2-48ec-9f82-21ea5af28eb5.png)
> You can keep overwriting as many times as you like, but it quickly becomes an unreadable mess.

Which can be a bonus when you want to be sure of password security, if you could not be sure no-echo would work properly: it was not so easy to cover spaces, when terminals could be glass or hardcopy with local echo on either, and use type bars, cylinders, wheels, or low quality dot matrix.

**Comment by mintty** [comment]
The DECSET 20 sequence seems to achieve visually same as the current SGR 8:7, however SGR are attributes, while DECSET switches modes, which is a subtle difference, e.g. when saving/restoring cursor or copying rectangular areas. In fact it might be more appropriate to handle overstrike as a mode rather than an attribute but please take this into account and reconsider whether to request this as an additional feature.

**Comment by j4james** [comment]
> when saving/restoring cursor

I've just checked now, and the state of overstrike mode is actually saved and restored with `DECSC`/`DECRC` on the VK100, so I think that matches your current behavior.

> copying rectangular areas

The VK100 doesn't support rectangular area operations, so this falls into the category of undefined behavior, but I personally think of overstriking as a kind of graphic overlay, and would expect it to be copied in the same way that I'd expect sixel graphics to be copied (although I know Mintty doesn't currently support that).

Anyway, it was just an idea. If you don't think it's an appropriate match for your existing overstrike functionality, that's OK. You're welcome to close this issue.

**Comment by mintty** [comment]
Released 3.6.3.
