### ISSUE TITLE
How to select other UI languages using only mintty & cygwin1.dll?

### ISSUE THREAD

**Issue by zixijian** [mintty/mintty#1186]
WinTin++ using mintty & cygwin1.dll run tt++( A mud client) binaries.
 When mintty is out of the cygwin environment ,the UI language is no longer optional ,and no one languages in the alternate list are visible.
How to fix this problem?

Here is the WinTin++：
https://github.com/scandum/tintin/releases/download/2.02.20/wintin-2.02.20.msi

**Comment by mintty** [comment]
The language packs (`.po` translation files) would need to be deployed together with the binary.
Best way is to put a directory structure usr/share/mintty in parallel to subdirectory bin (for the binary) and further subdirectory lang therein, and put all the .po files in it; same for themes and sounds if desired.
Check out wsltty as an example.

**Comment by zixijian** [comment]
> The language packs (`.po` translation files) would need to be deployed together with the binary. Best way is to put a directory structure usr/share/mintty in parallel to subdirectory bin (for the binary) and further subdirectory lang therein, and put all the .po files in it; same for themes and sounds if desired. Check out wsltty as an example.

Maybe I did something wrong, and it didn't work.

![Screenshot_2022-11-27-00-31-44-903-edit_com estrongs android pop](https://user-images.githubusercontent.com/4952406/204099038-dbe214f9-d93f-401f-b2a7-e138e6d09dec.jpg)

**Comment by mintty** [comment]
The lang directory for the po files must be in /usr/share/mintty, where the binary is in /bin, so up one directory from the shown one, then down into usr/share/mintty/.

**Comment by zixijian** [comment]
I got it,If I want to customize it as a sibling directory, which code file should I modify?
like:
wintin++/
├── lang
│   └── zh_CN.po
└── mintty.exe

**Comment by zixijian** [comment]
> The lang directory for the po files must be in /usr/share/mintty, where the binary is in /bin, so up one directory from the shown one, then down into usr/share/mintty/.

I got it,If I want to customize it as a sibling directory, which code file should I modify?
like:
wintin++/
├── lang
│   └── zh_CN.po
└── mintty.exe

**Comment by mintty** [comment]
I thought it used to be necessary that the binary directory needs to be called bin, but it does not seem to be the case (anymore). Anyway, I guess in your setup the directory above wintin++ is regarded as / (root directory) by cygwin1.dll, so the usr/share/mintty hierarchy should go into it.
You can choose a different configuration directory with invocation parameter --configdir CONFDIR and have subdires lang etc. in that if you like. This is described in the mintty manual.
I would not like to deal with project-specific source patches, please try to avoid that.

**Comment by zixijian** [comment]
Thanks.

**Comment by mintty** [comment]
Added some advice to the wiki Tips page: 
https://github.com/mintty/mintty/wiki/Tips#running-mintty-stand-alone
