### ISSUE TITLE
Sixel images don't work with native Windows C programs

### ISSUE THREAD

**Issue by CarterLi** [mintty/mintty#1192]
```c
#include <stdio.h>
#include <fcntl.h>
#include <io.h>

int main() {
    puts(
        "\033Pq\n"
        "#0;2;0;0;0#1;2;100;100;0#2;2;0;100;0\n"
        "#1~~@@vv@@~~@@~~$\n"
        "#2??}}GG}}??}}??-\n"
        "#1!14@\n"
        "\033\\"
    );
}
```

The image is from [Wikipedia](https://en.wikipedia.org/wiki/Sixel#Sample)

![image](https://user-images.githubusercontent.com/6134068/208898764-3dbcde27-c4a4-458c-84e5-ee92c7d369da.png)

It's very strange that if I pipe stdout to `/bin/cat`, the image is printed as expected. I have also tried `_setmode(fileno(stdout), _O_BINARY);` ( which prevents `puts` from converting LF to CRLF, I assume ) but it didn't help.

Env used: MSYS2/UCRT64

**Comment by k-takata** [comment]
I think it is because of this: https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs

**Comment by CarterLi** [comment]
I update my MSYS2 to the latest version by `pacman -Syu` and added `ConPTY=true` to `~/.minttyrc` and restarted `mintty`

It didn't work

![image](https://user-images.githubusercontent.com/6134068/208924863-8fc71546-f99a-434b-b26e-fc0ca7d08a29.png)

**Comment by CarterLi** [comment]
I have tried launch mintty with `mintty -P on`. It didn't work either.

**Comment by CarterLi** [comment]
Ok. After reading [the long post](https://github.com/microsoft/terminal/issues/1173), I understood that it was ConPTY that swallowed sixel specific ASCII escape sequences that ConPTY didn't understand. So it's impossible to fix before `ConPTY Passthrough mode` is supported by ConPTY.

My question is that why cygwin programs like `/bin/cat` work in this case? Can I simulate it in my program without touching cygwin?

**Comment by BrianInglis** [comment]
*Cygwin* `cat` gets the verbatim text stream and `cat` may prefix `\r` to terminal output newlines. 
Try explicitly writing `\r\n` at the end of each line: *DEC* systems used it and *DEC* devices expected it, although some may have been able to be set to accept others.

**Comment by CarterLi** [comment]
I don't get it.

Can I modify my code below to make it work like `cat`?

**Comment by CarterLi** [comment]
> Try explicitly writing `\r\n` at the end of each line

I replace  all `\n` to `\r\n`. It didn't work.

**Comment by mintty** [comment]
This works fine for me, in either cygwin or Msys. What does `type gcc` say?

**Comment by CarterLi** [comment]
`/ucrt64/bin/gcc`

```
gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys64\ucrt64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.2.0/configure --prefix=/ucrt64 --with-local-prefix=/ucrt64/local --build=x86_64-w64-mingw32 -
-host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/ucrt64/include --libexecdir=/ucrt6
4/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,f
ortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite
--enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-
lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disabl
e-symvers --with-libiconv --with-system-zlib --with-gmp=/ucrt64 --with-mpfr=/ucrt64 --with-mpc=/ucrt64 --with-isl=/ucrt6
4 --with-pkgversion='Rev6, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-g
nu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstd
c++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Rev6, Built by MSYS2 project)
```

**Comment by mintty** [comment]
Use /usr/bin/gcc.

**Comment by Biswa96** [comment]
Disabling conpty with `MSYS=disable_pcon` allows the sixel image from mingw gcc compiled executable.

**Comment by mintty** [comment]
This is not a mintty issue. Same variants of behaviour should be observable in any terminal.
