### ISSUE TITLE
Installing MinTTY as a shared depedency

### ISSUE THREAD

**Issue by sskras** [mintty/mintty#1194]
I have MSYS2, Cygwin (both 32-bit and 64-bit builds), and now a recent Midipix build installed on my laptop (in a single OS).

All of them seem to bring their own builds of MinTTY in parallel:
```
C:\>dir/s midipix\mintty
 Volume in drive C has no label.
 Volume Serial Number is 10FF-971D

 Directory of C:\midipix\bin

2022-11-27  19:22           566,272 mintty
               1 File(s)        566,272 bytes

 Directory of C:\midipix\share\terminfo\m

2022-11-27  19:17             3,817 mintty
               1 File(s)          3,817 bytes

     Total Files Listed:
               2 File(s)        570,089 bytes
```
```
C:\>dir/s msys64\mintty.exe
 Volume in drive C has no label.
 Volume Serial Number is 10FF-971D

 Directory of C:\msys64\usr\bin

2022-07-22  11:21           991,071 mintty.exe
               1 File(s)        991,071 bytes

     Total Files Listed:
               1 File(s)        991,071 bytes
```
```
C:\>dir/s cygwin\mintty.exe
 Volume in drive C has no label.
 Volume Serial Number is 10FF-971D

 Directory of C:\cygwin\bin

2021-11-10  20:02           942,621 mintty.exe
               1 File(s)        942,621 bytes

     Total Files Listed:
               1 File(s)        942,621 bytes
```
```
C:\>dir/s cygwin64\mintty.exe
 Volume in drive C has no label.
 Volume Serial Number is 10FF-971D

 Directory of C:\cygwin64\bin

2021-11-10  20:01           968,211 mintty.exe
               1 File(s)        968,211 bytes

     Total Files Listed:
               1 File(s)        968,211 bytes
```

MinTTY is absent from the `Control Panel\All Control Panel Items\Programs and Features`. It's buried in the dirs of Cygwin and MSYS2 installation.  

All the candidates that could use the shared installation:

- Cygwin
- Git-for-Windows
- MSYS (probably not developed anymore, left for the sake of completeness)
- MSYS2
- WSLtty
- midipix

**Comment by sskras** [comment]
A related question would be if the same build could be used by the same environment but for running processes of two different endianesses, like Cygwin 32-bit + Cygwin 64-bit?
```
saukrs@DESKTOP-O7JE7JE ~
$ ldd /usr/bin/mintty.exe
        ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x77b80000)
        KERNEL32.DLL => /cygdrive/c/Windows/System32/KERNEL32.DLL (0x766a0000)
        KERNELBASE.dll => /cygdrive/c/Windows/System32/KERNELBASE.dll (0x76390000)
        ADVAPI32.dll => /cygdrive/c/Windows/System32/ADVAPI32.dll (0x75a60000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x61000000)
        msvcrt.dll => /cygdrive/c/Windows/System32/msvcrt.dll (0x77530000)
        sechost.dll => /cygdrive/c/Windows/System32/sechost.dll (0x76c30000)
        RPCRT4.dll => /cygdrive/c/Windows/System32/RPCRT4.dll (0x769f0000)
        COMDLG32.DLL => /cygdrive/c/Windows/System32/COMDLG32.DLL (0x76940000)
        COMCTL32.DLL => /cygdrive/c/Windows/WinSxS/x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_a8625c1886757984/COMCTL32.DLL (0x6f370000)
        combase.dll => /cygdrive/c/Windows/System32/combase.dll (0x77880000)
        GDI32.dll => /cygdrive/c/Windows/System32/GDI32.dll (0x76c00000)
        ucrtbase.dll => /cygdrive/c/Windows/System32/ucrtbase.dll (0x77680000)
        win32u.dll => /cygdrive/c/Windows/System32/win32u.dll (0x75e20000)
        gdi32full.dll => /cygdrive/c/Windows/System32/gdi32full.dll (0x76cb0000)
        shcore.dll => /cygdrive/c/Windows/System32/shcore.dll (0x775f0000)
        msvcp_win.dll => /cygdrive/c/Windows/System32/msvcp_win.dll (0x75da0000)
        USER32.dll => /cygdrive/c/Windows/System32/USER32.dll (0x75ae0000)
        SHLWAPI.dll => /cygdrive/c/Windows/System32/SHLWAPI.dll (0x76790000)
        SHELL32.dll => /cygdrive/c/Windows/System32/SHELL32.dll (0x76da0000)
        IMM32.DLL => /cygdrive/c/Windows/System32/IMM32.DLL (0x75d10000)
        gdiplus.dll => /cygdrive/c/Windows/WinSxS/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_d9513b1fe1046fc7/gdiplus.dll (0x74de0000)
        ole32.dll => /cygdrive/c/Windows/System32/ole32.dll (0x76ab0000)
        WINMM.DLL => /cygdrive/c/Windows/SYSTEM32/WINMM.DLL (0x759b0000)
        USP10.dll => /cygdrive/c/Windows/SYSTEM32/USP10.dll (0x6f350000)
        WINSPOOL.DRV => /cygdrive/c/Windows/SYSTEM32/WINSPOOL.DRV (0x74fb0000)

saukrs@DESKTOP-O7JE7JE ~
$ uname -m
i686

saukrs@DESKTOP-O7JE7JE ~
$ ls -Al /usr/bin/mintty.exe
-rwxr-xr-x 1 saukrs None 942621 Nov 10  2021 /usr/bin/mintty.exe
```
```
saukrs@DESKTOP-O7JE7JE ~
$ ldd /usr/bin/mintty.exe
        ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x7ff99f050000)
        KERNEL32.DLL => /cygdrive/c/Windows/System32/KERNEL32.DLL (0x7ff99ed80000)
        KERNELBASE.dll => /cygdrive/c/Windows/System32/KERNELBASE.dll (0x7ff99ca40000)
        ADVAPI32.dll => /cygdrive/c/Windows/System32/ADVAPI32.dll (0x7ff99e660000)
        cygwin1.dll => /usr/bin/cygwin1.dll (0x180040000)
        msvcrt.dll => /cygdrive/c/Windows/System32/msvcrt.dll (0x7ff99ef70000)
        sechost.dll => /cygdrive/c/Windows/System32/sechost.dll (0x7ff99ea00000)
        RPCRT4.dll => /cygdrive/c/Windows/System32/RPCRT4.dll (0x7ff99e810000)
        comdlg32.dll => /cygdrive/c/Windows/System32/comdlg32.dll (0x7ff99d850000)
        COMCTL32.dll => /cygdrive/c/Windows/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e/COMCTL32.dll (0x7ff9879a0000)
        combase.dll => /cygdrive/c/Windows/System32/combase.dll (0x7ff99d9e0000)
        ucrtbase.dll => /cygdrive/c/Windows/System32/ucrtbase.dll (0x7ff99c800000)
        GDI32.dll => /cygdrive/c/Windows/System32/GDI32.dll (0x7ff99e500000)
        win32u.dll => /cygdrive/c/Windows/System32/win32u.dll (0x7ff99cd20000)
        shcore.dll => /cygdrive/c/Windows/System32/shcore.dll (0x7ff99d930000)
        gdi32full.dll => /cygdrive/c/Windows/System32/gdi32full.dll (0x7ff99c930000)
        msvcp_win.dll => /cygdrive/c/Windows/System32/msvcp_win.dll (0x7ff99cff0000)
        USER32.dll => /cygdrive/c/Windows/System32/USER32.dll (0x7ff99d230000)
        SHLWAPI.dll => /cygdrive/c/Windows/System32/SHLWAPI.dll (0x7ff99e710000)
        SHELL32.dll => /cygdrive/c/Windows/System32/SHELL32.dll (0x7ff99dda0000)
        IMM32.dll => /cygdrive/c/Windows/System32/IMM32.dll (0x7ff99ed20000)
        gdiplus.dll => /cygdrive/c/Windows/WinSxS/amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.2251_none_91a40448cc8846c1/gdiplus.dll (0x7ff984530000)
        ole32.dll => /cygdrive/c/Windows/System32/ole32.dll (0x7ff99e530000)
        WINSPOOL.DRV => /cygdrive/c/Windows/SYSTEM32/WINSPOOL.DRV (0x7ff976c30000)
        WINMM.dll => /cygdrive/c/Windows/SYSTEM32/WINMM.dll (0x7ff97ac30000)
        USP10.dll => /cygdrive/c/Windows/SYSTEM32/USP10.dll (0x7ff984b30000)

saukrs@DESKTOP-O7JE7JE ~
$ uname -m
x86_64

saukrs@DESKTOP-O7JE7JE ~
$ ls -Al /usr/bin/mintty.exe
-rwxr-xr-x 1 saukrs None 968211 Nov 10  2021 /usr/bin/mintty.exe
```

... which seems to the two different .exe files.

**Comment by mintty** [comment]
In addition to be built against different runtime libraries, there are also a few subtle differences between them.
Consider that the systems you list install lots of similar tools in parallel, not just mintty, beginning with the basic Unix tools.
So no, this is not a fruitful project.

**Comment by mintty** [comment]
By the way, how did you get a running Midipix installation? Is that project still active anyway?
I made a few adaptations to midipix in mintty a while ago but could never test them myself...

**Comment by sskras** [comment]
@mintty commented [Dec 30, 2022](#issuecomment-1367846152):

> By the way, how did you get a running Midipix installation? 

I cross-built it on Ubuntu Linux by following the default steps from here:
https://dev.midipix.org/build/midipix_build#2-building-and-deployment:~:text=2.%20Building%20and%20deployment
... namely the command:
```shell
$ ./build.sh -a nt64 -b release -D zipdist -P -v
```
... the resulting zip from which I then copied and extracted on my w10 machine (no real installer yet).

> Is that project still active anyway? I made a few adaptations to midipix in mintty a while ago but could never test them myself...

Nice to hear that. I think I saw the midipix-related issue or some other kind of discussion.

My take is that one of the main developers was contracted by some company called LBM Systems: 
https://sysdeer.net/

... and a year ago (in August 2021) formed his own company SysDeer Technologies, LLC – I guess it was Zvi Gilboa:
https://opencorporates.com/companies/us_va/11271157

Overall they seems to be quite active, at least in this repository:
https://dev.midipix.org/build/midipix_build/commits/main

... where they pushes updates to the software they build under Midipix.  Among them I saw quite a few X11 libs and apps, and some big app like qemu.

They seem to use their own fork of MinTTY:
https://dev.midipix.org/build/midipix_build/blob/main/f/groups/231.native_packages_etc.group#_304-308

... and has ~55 patches in advance: https://github.com/mintty/mintty/compare/master...midipix-ports:mintty:midipix

It appears to be quite old MinTTY, v2.8.1:
![image](https://user-images.githubusercontent.com/7887758/210112944-a409c605-6fd9-4d22-866b-676d5db7fa00.png)

**Comment by sskras** [comment]
@mintty commented [Dec 30, 2022](#issuecomment-1367843632):

> In addition to be built against different runtime libraries, 

OK, I checked the 3 executables, and after filtering out the system DLLs we get this:
```shell
saukrs@DESKTOP-O7JE7JE MSYS ~/src/midipix_build
$ for EXE in 'C:\cygwin64\bin\mintty.exe' 'C:\msys64\usr\bin\mintty.exe' 'C:\midipix\bin\mintty'; do echo Processing $EXE:; ldd $EXE | grep -vi /windows ; echo; done
Processing C:\cygwin64\bin\mintty.exe:
        cygwin1.dll => /c/cygwin64/bin/cygwin1.dll (0x180040000)

Processing C:\msys64\usr\bin\mintty.exe:
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)

Processing C:\midipix\bin\mintty:
```

Looks like Cygwin and MSYS2 really links their mintty build to their API translation engine.
But does it have to be so?

Because in the Midipix case things seems to be different:
```shell
saukrs@DESKTOP-O7JE7JE MSYS ~/src/midipix_build
$ ldd 'C:\midipix\bin\mintty'
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ff99f050000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ff99ed80000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ff99ca40000)
```

OK, maybe it loads most of these DLLs (that are used by a modern build) dynamically:
![image](https://user-images.githubusercontent.com/7887758/210113626-15dde218-01a4-4812-8c35-a1d5113f2d96.png)

But what main things make the need for mintty to have some *nix knowledge / to make some syscalls?
Is it the tty/pty stuff?

> ... there are also a few subtle differences between them. Consider that the systems you list install lots of similar tools in parallel, not just mintty, beginning with the basic Unix tools.

OK, the environments should bring their own executables and libs, that's expected.
But what prevents from expecting to find `mintty.exe` in the system path and running it from there?

Yes, I believe there should be some subtle differences for different environments, but how could they be found out?
I guess the only way is to mess around, ie. to copy `mintty.exe` from Cygwin to MSYS2 and try to get the replacement running.

**Comment by mintty** [comment]
I'd agree that a build without dependencies would have some benefit for standalone deployments as bundled with other software, e.g. my own text editor mined. However, for the use case of being the terminal of different subsystems, I see no benefit; in this context, mintty is a tool like, as I said, other Unix tools.

**Comment by sskras** [comment]
> in this context, mintty is a tool like, as I said, other Unix tools.

Well, you didn't answer about the architectural issues / technical details, so this sounds very abstract (and a bit foreign) to me.

And then mintty is different other Unix tools in that it uses native Windows APIs (like User, Kernel, GDI ones) directly.

**Comment by mintty** [comment]
The systems need different path handling (cygwin has a /cygdrive prefix for drive paths, msys does not) and checking the environment variable MSYS vs CYGWIN. I guess this could also be distinguished dynamically.

**Comment by midipix** [comment]
The Midipix framework uses framework-specific import libraries that are created by the mdso tool (https://git.midipix.org/mdso). Accordingly, the current tool to determine dependencies should be perk (https://git.midipix.org/perk) -- and later also xldd. Both mdso and perk are cross-tools which could be compiled and run on cygwin, linux, bsd, etc.

> $ perk -d /bin/mintty
libu16ports.so.0
comctl32.dll
imm32.dll
winmm.dll
winspool.drv
ole32.dll
kernel32.dll
user32.dll
gdi32.dll
comdlg32.dll
shell32.dll
advapi32.dll
usp10.dll
libc.so
libpsxscl.so

**Comment by midipix** [comment]
> The systems need different path handling (cygwin has a /cygdrive prefix for drive paths, msys does not) and checking the environment variable MSYS vs CYGWIN. I guess this could also be distinguished dynamically.

Indeed, but the real issue would be the incompatible implementations of pty's, fd's, etc. As @mintty commented, mintty should be regarded as just another tool within each of the distributions.

**Comment by mintty** [comment]
@midipix, thanks for stepping in, and I'd like to try midipix myself. However, it failed to build for me in two different environments. Can you provide a pre-built zip ready for installation?

**Comment by midipix** [comment]
@mintty: sure! Please pm me on irc (libera network) and we'll take it from there.

**Comment by sskras** [comment]
@midipix commented 10 hours ago:

> > The systems need different path handling (cygwin has a /cygdrive prefix for drive paths, msys does not) and checking the environment variable MSYS vs CYGWIN. I guess this could also be distinguished dynamically.
> 
> Indeed, but the real issue would be the incompatible implementations of pty's, fd's, etc. 

Now that got technical, thanks from me too:)

> As @mintty commented, mintty should be regarded as just another tool within each of the distributions.

I'm still not sure it's hard to make mintty a distribution agnostic, pure WinAPI binary.
My idea was that if mintty can run `cmd.exe` then it could delegate processing of ptys, fds and other *nixish stuff to the distro.

I guess that's the moment when I must go reading the code and try doing the actual split of binaries.  So I could see the details myself.

Thanks for giving some pointers. 
Unless someone is to provide more details, this issue probably can be closed already.
It still needs a **Question** label, I'd say.

Happy new year everyone:)!

**Comment by mintty** [comment]
> My idea was that if mintty can run cmd.exe then it could delegate processing of ptys, fds and other *nixish stuff to the distro.

Mintty just needs to be bundled with cygwin1.dll (or the msys dll for the other build), nothing else, and can then run cmd.exe and everything else that would run in a terminal. It can not take over the intrinsic task of the cygwin dll to implement ptys etc because that is subtle know-how developed over two decades - why should a client application want to assume responsibility for all that?

**Comment by sskras** [comment]
PS: @midipix wrote:

> As @mintty commented, mintty should be regarded as just another tool within each of the distributions.

Main reason I created this issue was that version of mintty that Midipix uses was too different from the versions used by MSYS2 and Cygwin on my box, and switching between running mintty windows from different distros using Ctrl-Tab works until the mintty terminal window coming from Midipix gets involved.

Then the thing can do unexpected window restore (from the maximized state) or even closure (maybe a crash).

So the related question could be that: is Midipix going to update the bundled mintty version / make switching between Cygwin / MSYS2 terminal windows using Ctrl-Tab seamless?

**Comment by sskras** [comment]
@mintty:

> Mintty [...] can then run cmd.exe and everything else that would run in a terminal. It can not take over the intrinsic task of the cygwin dll to implement ptys etc because that is subtle know-how developed over two decades - why should a client application want to assume responsibility for all that?

Ummm, no – my idea was quite an opposite. I wonder why would mintty need to know about ptys **at all** if it could run native Windows software without them too.  The aforementioned case of running `cmd.exe` in mintty:

![image](https://user-images.githubusercontent.com/7887758/210167093-ac5d4377-c03a-42c5-af21-22e602f58431.png)

**Comment by Biswa96** [comment]
> cygwin has a /cygdrive prefix for drive paths, msys does not

Just FYI, it's magic of /etc/fstab, not from any runtime code change. Continue...

**Comment by avih** [comment]
> I wonder why do we need to mention Cygwin dll and ptys **at all** if mintty can run native Windows software without them too

But it can't do that.

Every graphical terminal has two parts usually:
1. the graphics, using whatever graphic toolkit it can, like x11 (xterm) or gtk (gnome terminal) or win32 API (mintty), etc.
2. The actual terminal functionality which is POSIX, this needs to open PTY and fd's read and write from them, start a POSIX session, etc.

So for mintty, only the graphics part can be sort of shared as it uses win32 API.

But the actual terminal part, which needs POSIX API, uses the underlaying libc for that, be that cygwin, or msys2, or midipix, etc. And they are not compatible.

So you can't have one mintty which works with different implementations of POSIX APIs, unless you introduce some new intermediary module which interfaces between the win32 part of mintty, and the POSIX part of it, where for each POSIX backend (cygwin, msys2, etc) you'd need to build such adapter.

**Comment by mintty** [comment]
> >  cygwin has a /cygdrive prefix for drive paths, msys does not

> Just FYI, it's magic of /etc/fstab, not from any runtime code change. Continue...

There are in fact some subtle dependencies on constant "/cygdrive" (and its length!) in the winsup code, with unclear consequences for me. Also cygwin falls back to "/cygdrive" if /etc/fstab does not exist (e.g. in a standalone bundled minimal installation). The best way to determine the effective prefix seems to be /proc/cygdrive.

**Comment by sskras** [comment]
@avih commented [on Jan 1](https://github.com/mintty/mintty/issues/1194#issuecomment-1368410016):

> > I wonder why do we need to mention Cygwin dll and ptys **at all** if mintty can run native Windows software without them too
> 
> But it can't do that.

So does my last screenshot means that MinTTY emulates Windows Console API to run the `CMD.exe` successfully using the **pty** mechanism that is built into the Cygwin? That would be Wow to me.

> Every graphical terminal has two parts usually:
> 
> 1. the GUI, using whatever graphic toolkit it can, like x11 (xterm) or gtk (gnome terminal) or win32 API (mintty), etc. This handles KB input, the window, and renders the window content (text, buttons, etc).
> 2. The actual terminal functionality which is POSIX, this needs to open PTY and fd's read and write from them, start a POSIX session, etc.
> 
> So for mintty, only the graphics part can be sort of shared as it uses win32 API.
> 
> But the actual terminal part, which needs POSIX API, uses the underlaying libc for that, be that cygwin, or msys2, or midipix, etc. And they are not compatible.

Thanks for being technical and detailed, much appreciate that !

> So you can't have one mintty which works with different implementations of POSIX APIs, unless you introduce some new intermediary module which interfaces between the win32 part of mintty, and the POSIX part of it, where for each POSIX backend (cygwin, msys2, etc) you'd need to build such adapter.

Now I wonder what architectural differences allows the AlacriTTY to do this:

![image](https://user-images.githubusercontent.com/7887758/218758500-6fcf2557-3e3b-4852-9677-d6579094bc32.png)
(with the exception of **Midipix**'es Bash which closes just after the AlacriTTY window is drawn)

**Comment by mintty** [comment]
> So does my last screenshot means that MinTTY emulates Windows Console API to run the CMD.exe successfully using the pty mechanism that is built into the Cygwin?

Not quite. Mintty uses cygwin1.dll as its runtime environment. That implements the ConPTY feature (not the Console API) which kind of modifies the behaviour of the Console API which is in turn implemented by cmd.exe.

> architectural differences ...

Not sure what those screenshots are supposed to suggest. You are running different environment in 3 instances of the same terminal, which could as well be mintty.

**Comment by sskras** [comment]
> Not quite. Mintty uses cygwin1.dll as its runtime environment. That implements the ConPTY feature (not the Console API) which kind of modifies the behaviour of the Console API which is in turn implemented by cmd.exe.

Wow! Thanks.

> > architectural differences ...
> 
> Not sure what those screenshots are supposed to suggest. You are running different environment in 3 instances of the same terminal, which could as well be mintty.

I would like to stress: _in 3 instances of the same terminal **emulator**_

My suggestion was that both builds `bash.exe` from two different environments work in the same build of a terminal emulator.

So one Alacritty can work with at least two different POSIX implementations.  While MinTTY does not.
Does this mean Alacritty implements some TTY adapters you mentioned earlier:

> unless you introduce some new intermediary module which interfaces between the win32 part of mintty, and the POSIX part of it, where for each POSIX backend (cygwin, msys2, etc) you'd need to build such adapter.

... or does it happens to work in some other way?

PS. I would jump straight into reading the source code, but the codebases are large + I don't know Rust (in which Alacritty is written). Thanks.

**Comment by mintty** [comment]
I doubt Alacritty does anything special about "supporting" different client systems (not only POSIX, cmd.exe isn't).
The pty interface is a rather clear barrier to decouple interactive (terminal) environment from client runtime environment. Mintty achieves quite the same. Maybe there is one tiny difference: when running bash, the cygwin layer linked into mintty is the same that supports bash. On the other hand, you can also run wsl.exe or cmd.exe which decouples both runtime systems completely.
Anyway, as discussed before, I don't think these considerations lead to reasonable modifications of mintty, so I intend to close this as an issue.

**Comment by sskras** [comment]
> Mintty achieves quite the same. Maybe there is one tiny difference: when running bash, the cygwin layer linked into mintty is the same that supports bash.

Umm. The more I try to understand the difference/the issue, the more it gets obvious that I need to start reading the sources and maybe even launch a debugger every now and then.

> On the other hand, you can also run wsl.exe or cmd.exe which decouples both runtime systems completely. 

Well, I tend to avoid WSL in every way I can. (I just don't love architecture of WSL2:)
But thanks for pointing to the related implementation!

> I don't think these considerations lead to reasonable modifications of mintty, so I intend to close this as an issue.

I'm a bit sad to hear that, but ... I won't complain. :)
Thanks for keeping the discussion balanced and technical!

**Comment by mintty** [comment]
> I need to start reading the sources

To understand the interaction between terminal and client application, it should suffice to look at file child.c; however, I still don't understand to what aim you would spend such effort. Any big modification of mintty would need justification in some evident benefit which I don't see here.

**Comment by sskras** [comment]
> To understand the interaction between terminal and client application, it should suffice to look at file child.c; 

Thanks again for the pointer.

> however, I still don't understand to what aim you would spend such effort. Any big modification of mintty would need justification in some evident benefit which I don't see here.

I just search for a native, independent terminal emulator app that supports different POSIX-on-Windows implementations.
Seems like my Windows desktop setups will have to be migrated to Alacritty.
I tried to stay with the terminal emulator I know already (MinTTY).

PS. Well, `bash` from Midipix doesn't run without being launched in tandem with MinTTY + requires quite old version 2.8.1 of it.  So I can't run Midipix in neither from Alacritty, nor from a newer MinTTY yet.

But that's a story / bug from another project, it seems. :)

**Comment by mintty** [comment]
There aren't so many POSIX on Windows systems. Which one would not run in mintty? It shouldn't really bother the users to run different binaries of the same mintty version (like for cygwin or MSYS); midipix should eventually catch up, and I would support it as soon as I can run the system myself easily.

**Comment by sskras** [comment]
> There aren't so many POSIX on Windows systems. 

5 or 6 of them that I listed in the OP seems quite enough to me. : P

> Which one would not run in mintty?

With "independent terminal emulator app" I meant a thing that for example:

1. is able to have a single, shared configuration;
(so I can migrate between machines easier)
2. is updated once for all the POSIX systems I have;
(so a change in the Git-for-Windows window is valid for Cygwin's window too)
3. having some IPC bug* in _one build_ wouldn't affect the _other build_.
4. would allow me to integrate another P-o-W implementation** without requiring me to maintain my local copy of MinTTY code.

[*] Eg. the Midipix build of MinTTY can switch between windows using Ctrl-Tab _only_ if there are no newer builds on MinTTY running. Otherwise the former windows are "forgotten" as soon as a window of the newer build gets activated.
[**] Eg. [da-x/colinux](https://github.com/da-x/colinux)

> It shouldn't really bother the users to run different binaries of the same mintty version (like for cygwin or MSYS); 

Well, you probably see from my list why it's not the case for me.

If I would like to have different, per-system builds of terminal emulator, I would compile and run them on the corresponding system, and would render them using Windows-native X11 server, I think.

Aren't we done yet? =)

**Comment by mintty** [comment]
> shared configuration

This is a strong point but it's solved already: %APPDATA%/mintty/config or $APPDATA/mintty/config.

> Midipix build of MinTTY can switch between windows using Ctrl-Tab only if ...

That may be due to changes in mintty inter-window handling a while ago and should vanish once midipix updates their version.

**Comment by sskras** [comment]
Sorry for not answering earlier.

@mintty commented [on Feb 16](https://github.com/mintty/mintty/issues/1194#issuecomment-1433702591):

> > shared configuration
> 
> This is a strong point but it's solved already: %APPDATA%/mintty/config or $APPDATA/mintty/config.

Thanks for the info.  Though I haven't tried to share this file between Cygwin, MSYS2 and Midipix yet.

> > Midipix build of MinTTY can switch between windows using Ctrl-Tab only if ...
> 
> That may be due to changes in mintty inter-window handling a while ago and should vanish once midipix updates their version.

Sure, and the waiting for the fix in one of these environments is exactly the thing that would be avoided if the implementation would be common between all environments. Just saying :P
