### ISSUE TITLE
 how to know that I use mintty programmatically ?

### ISSUE THREAD

**Issue by vtorri** [mintty/mintty#1204]
I have read in the wiki that there is a shell script that can detect if I am in mintty (or cygwin or msys2).

But I would like to know if it is possible to detect if i'm in mintty programmatically.

More precisely, i would like to know if I use cmd, or mintty (or any of its variants).

**Comment by Biswa96** [comment]
Will this help?

```
$ echo $TERM_PROGRAM
mintty
```

**Comment by vtorri** [comment]
@Biswa96 according to https://github.com/mintty/mintty/wiki/Tips#terminal-type-detection--check-if-running-inside-mintty this method is not recommended

**Comment by BrianInglis** [comment]
Issue *CSI > c* `\e[>c` response `\e[>77;30603;0c` 
decode *term type* `mintty` version `3.6.3-0`

**Comment by vtorri** [comment]
@BrianInglis  and in C or C++ ?

**Comment by BrianInglis** [comment]
Write to terminal and read with 1s timeout:
would depend on your compiler runtime; 
in bash:
```
    read -d c -N 80 -p $'\E[>c' -s -t 1 r
    f='type version'
    n=${r#$'\E[>'}
    n=${n%c}
    v=${n#*\;}
    u=${v#*\;}
    v=${v%\;*}
    v=${v//0/.}
    n=${n%%\;*}
    case $n in
        0)  t=VT100;;
        1)  t=VT220;;
        2)  t=VT240;;
        18) t=VT330;;
        19) t=VT340;;
        24) t=VT320;;
        41) t=VT420;;
        61) t=VT510;;
        64) t=VT520;;
        65) t=VT525;;
        77) t=mintty;;
    esac
    echo "$f"$'\t'"$t v$v-$u"$'\t^[[>c\t\t'"$(cat -A <<< ${r})"
```
if no response after timeout you are probably in a DOS or Windows console without adequate ANSI support. 
You could do this as well in any other scripting language, perhaps even cmd, most easily if it supports any ANSI/xterm terminal escape support modules.

**Comment by vtorri** [comment]
@BrianInglis and in C or C++ ?

**Comment by vtorri** [comment]
to be precise : i want to write a log system with colors from scratch, which works with mintty-based terminal as well as cmd. with cmd, I use SetConsoleTextAttribute() to set the color, and with mintty, I use escaped commands (like in unix)

before the conpty usage, i detected that stdout was implemented with a pipe. But it's not the case anymore with conpty

**Comment by BrianInglis** [comment]
[How-to: Use ANSI colors in the terminal](https://ss64.com/nt/syntax-ansi.html)

**Comment by vtorri** [comment]
ok, i'll do this way:
1) I load dynamiquely kernel32.dll and see if conpty API is available (like CreatePseudoConsole ()). If so I enable ENABLE_VIRTUAL_TERMINAL_PROCESSING and ENABLE_PROCESSED_OUTPUT with SetConsoleMode(). Then colors are done like on linux, either mintty or cmd
2) if not, i check if pipes are used for stdout. If yes, it's like on Linux. It means that it is mintty without conpty.
3) otherwise, I use SetConsoleTextAttribute(). It means that it is cmd.exe without conpty

I'll write some code to verify this scheme is working

**Comment by Biswa96** [comment]
Can you provide why you want to check the terminal and in which scenario?

**Comment by vtorri** [comment]
@Biswa96 i've said what i wated to do above : logging system with colors for a cross-plateform project

**Comment by Biswa96** [comment]
The GetConsoleMode API checks the available features in the running console, not the terminal name. And there are already many logging library like spdlog (https://github.com/gabime/spdlog) or glog (https://github.com/google/glog) etc. with color output support.

**Comment by vtorri** [comment]
@Biswa96 finally, I don't want the terminal name any. Having the feature is better. And no, no additional library for this project

**Comment by BrianInglis** [comment]
The reason there are terminal databases and libraries using them, is that there are so many quirks in each implementation, you need a database driven library to identify and handle all the niggling little issues, that end up taking time to track down, diagnose, identify root cause, then develop, test, and promote each solution. 
It is always amusing to see when *little features* tie up a developer for a month solid, then dog the project budget for the rest of its life!

**Comment by mintty** [comment]
See also https://github.com/mintty/utils/issues/4#issuecomment-1473546223 which works in a terminal.
The problem in your use case is that the Windows console, and thus the Cygwin console, is not really a terminal and does not respond to that script, so other advice as above may be followed.

**Comment by vtorri** [comment]
thank you. it's enough for me. closing
