### ISSUE TITLE
Alt+Tab from mintty: focus next non-mintty window

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#1207]
Hello,

I use Ctrl+Tab to switch between mintty tabs. Also, `--tabbar=4` makes the minttys mostly feel like tabs of a single window. What's still missing for the single window-like workflow is:

When mintty is focused, Alt+Tab should focus the next window which is not part of the current Ctrl+Tab group (be it a mintty window with another `--class` or an unrelated window). Could you please make that possible? Maybe this should become option SessionGeomSync=5, but I tend to prefer a separate option.

**Comment by mintty** [comment]
Unlike Ctrl+TAB, Alt+TAB is handled directly by Windows, not mintty. So mintty cannot simply choose to do something different. A workaround may be very tricky.

**Comment by mkq** [comment]
Yes, I didn't actually mean to intercept Alt+Tab. But whenever a mintty window gets the focus (which it already notices, it seems, since there is an option Looks / Transparency / Opaque when focused), maybe it could put other windows in the same session at the end of the Alt+Tab order. (That seems to be possible, see [Autohotkey Winset Bottom](https://www.autohotkey.com/docs/v1/lib/WinSet.htm#Bottom); don't know the Windows API counterpart.)

**Comment by mintty** [comment]
Thanks for the hint to WS_EX_TOOLWINDOW, it works indeed. I am trying to combine it with a fresh attempt to combine tabs and transparency.

**Comment by mintty** [comment]
Release 3.6.5.

**Comment by mkq** [comment]
Wow. this is great! Thanks!

I just recently tried again to fix an Autohotkey workaround. It mostly works with SessionGeomSync <= 2, but has issues when mintty is minimized. I am happy to see that mintty's built-in handling seems to work flawlessly. (And I can live without separate taskbar button. Having a clean Alt+Tab list is my main priority.)

Maybe you should also mention Alt+Tab in the release notes? I would not expect an Alt+Tab cleanup when reading just "Group taskbar icons".

**Comment by mintty** [comment]
Changed on the release page, but I don't think I'll send another announcement mail on the cygwin list.
Thanks for the feedback.
