### ISSUE TITLE
caps-lock as compose key

### ISSUE THREAD

**Issue by calestyo** [mintty/mintty#1211]
Hey.

Under Linux I'm used to use the caps lock key as compose key. Would that be possible to add as a choice for `mintty`?

Thanks,
Chris.

**Comment by mintty** [comment]
I've uploaded a patch that adds a user-definable function `compose` so can assign it to any key combination, e.g.:
```
KeyFunctions=CapsLock:compose
```

Configuration by an additional option to setting ComposeKey would be somewhat more tricky as the implicit Windows function of it to change the Caps state would need to be compensated, whicih was already implemented for the case of user-definable functions.

**Comment by mintty** [comment]
Now also configurable via `ComposeKey=capslock` or interactively in the Options dialog.

**Comment by mintty** [comment]
Release 3.6.5.
