### ISSUE TITLE
[Feature Request] Is it possible to add border highlighting support for the command win-toggle-always-on-top ?

### ISSUE THREAD

**Issue by fengyichui** [mintty/mintty#1212]
Hi,

Is it possible to add border highlighting support for the action `win-toggle-always-on-top` ? Like PowerToys.

**Comment by Biswa96** [comment]
Could you provide any screenshot for reference?

**Comment by fengyichui** [comment]
Like this：

![56](https://user-images.githubusercontent.com/17896291/232196981-f5b9f888-9ceb-4df6-9964-f0452a16dab3.png)

**Comment by mintty** [comment]
The decoration layout is provided by Windows, not mintty.
Applications can draw their own decoration and borders in general, but only at extremely high effort and using insane APIs.
This is not likely to happen.

**Comment by fengyichui** [comment]
I known. Thanks!
