### ISSUE TITLE
mintty cursor, image of cursor remains after hitting Enter (#ghosting, #display)

### ISSUE THREAD

**Issue by Tarlak333** [mintty/mintty#1214]
Hello,

I have a weird issue with mintty running via cygwin on a "off-line" (non-WAN/internet connected) Windows workstation.  The cursor will leave an image of itself on the previous line after hitting the [Enter] key.  This does not happen all the time, the cursor leaves no image of itself at first but after ~3-5 commands it will leave an "image" of the cursor on the previous line 100% of the time. 

I'm also running ZSH as my shell.
**.zshenv contains:**
DISPLAY=localhost:0.0
export DISPLAY

Is there a particular .minttyrc config file option that may help with controlling this cursor behavior?

mintty = v3.6.3 (x86_64-pc-cygwin) [Windows 19044]
cygwin = v3.4.6
Windows = Windows 10 Enterprise 21H2 19044.2728

**Comment by mintty** [comment]
From the change log of mintty 3.6.4:
  * Fix cursor artefacts in connection with ClicksPlaceCursor=yes.

Please retry with current version.

**Comment by mintty** [comment]
Closing as fixed with current release.
