### ISSUE TITLE
tack testing shows `in` insert_null_glitch Insert mode distinguishes nulls needs set

### ISSUE THREAD

**Issue by BrianInglis** [mintty/mintty#1216]
Testing the latest `ncurses` `tack` release, the test lines were misaligned testing the `insert_null_glitch` `in` `in` *Insert mode distinguishes nulls* `terminfo` capability implying that `mintty` needs this boolean capability set. 
Can not find any good explanation for this capability. 
Has anyone come across this capability or issue?

**Comment by mintty** [comment]
How would tack demonstrate this issue? Does it happen with xterm?

**Comment by mintty** [comment]
The tack description for (in) says
 If these two lines line up ... then (in) should be set.
The two lines do not line up and (in) is not set, that sounds OK for me.
Also, xterm shows the same behaviour.

**Comment by BrianInglis** [comment]
I misread/misinterpreted it, as I thought it meant that `in` should be set as the lines were misaligned. Sorry for the noise! ;^>
