### ISSUE TITLE
mintty 3.6.4 string in the command line when use tmux

### ISSUE THREAD

**Issue by walkerxk** [mintty/mintty#1217]
when i use tmux attach in mintty, i got ":>|mintty 3.6.4^[" on my command line, even in vim. but i didn't input that string, how did that come from?
[tmux-server-1508.log.gz](https://github.com/mintty/mintty/files/11451823/tmux-server-1508.log.gz)
[tmux-client-43234.log.gz](https://github.com/mintty/mintty/files/11451824/tmux-client-43234.log.gz)
[tmux-out-1508.log.gz](https://github.com/mintty/mintty/files/11451825/tmux-out-1508.log.gz)
![image](https://github.com/mintty/mintty/assets/3411710/96e12413-db09-4c36-8fdb-340f47b0596c)

**Comment by mintty** [comment]
It's the terminal identification string sent on the terminal identification query `ESC [ > 0 q` as introduced by xterm 354.
Please check your setup (e.g. .bashrc file) for that query string.

**Comment by walkerxk** [comment]
8@00:23:17#xiakai1@tp/~> grep -R mintty .bash_profile .bashrc /etc/bash* /etc/profile*
8@00:24:50#xiakai1@tp/~>
i can't find any mintty in my setup

**Comment by mintty** [comment]
> Please check your setup (e.g. .bashrc file) for that query string.

That would be `grep ">0*q"`.

**Comment by walkerxk** [comment]
thanks, i will try this.

**Comment by walkerxk** [comment]
how did you find `ESC [ > 0 q` or `>0*q`, i didn't find any `ESC [ > 0 q` or `>0*q` in my log and .bash_profile .bashrc /etc/bash* /etc/profile*

**Comment by k-takata** [comment]
> even in vim.

At least, vim uses `ESC [ > 0 q` to identify the terminal.
If you set $TERM to xterm-256color even in tmux, you should use screen-256color instead.

**Comment by walkerxk** [comment]
> > even in vim.
> 
> At least, vim uses `ESC [ > 0 q` to identify the terminal. If you set $TERM to xterm-256color even in tmux, you should use screen-256color instead.

12@15:10:18#xiakai1@tp/~> grep -PiR 'TERM|-256color' .bash_profile .bashrc /etc/bash* /etc/profile*
.bash_profile:if [[ ! $TERM =~ screen|tmux ]]
.bashrc:# Don't wait for job termination notification
/etc/bash.bashrc:# Uncomment to use the terminal colours set in DIR_COLORS
/etc/profile.d/lang.csh:# if no locale variable is set, indicate terminal charset via LANG
/etc/profile.d/lang.sh:# if no locale variable is set, indicate terminal charset via LANG
/etc/profile.d/vte2.91.sh:# it under the terms of the GNU General Public License as published by
/etc/profile.d/vte2.91.sh:case "$TERM" in
/etc/profile.d/vte2.91.sh:  xterm*|vte*)
12@15:11:03#xiakai1@tp/~> echo $TERM
tmux-256color
12@15:11:06#xiakai1@tp/~>


i didn't set TERM to xterm-256color, seems like tmux set TERM to tmux-256color

**Comment by walkerxk** [comment]
> I guess the response strings were just discovered in the log file and this issue is out of curiosity, not a problem, right? Marking issue as question.

This display on the command line, i need to delete this string to do any thing and when in the vim, this string will changes my file.

**Comment by mintty** [comment]
What do `type tmux` and `type vim` report?

**Comment by walkerxk** [comment]
```
6@06:44:25#xiakai1@tp/~> type gcc
gcc is /usr/bin/gcc
6@06:44:27#xiakai1@tp/~>
```
cygwin packages of vim has an issue https://github.com/tmux/tmux/issues/3540
so i compile from git
cygwin packages of tmux has the same issue, so i compile from git

**Comment by j4james** [comment]
FYI, if you're using the conpty version of mintty, it's possible that the query response is arriving out of sequence. The app that generated the request would then fail to detect the response, so it ends up being interpreted as key presses instead. This shouldn't occur with wsltty.

**Comment by walkerxk** [comment]
> FYI, if you're using the conpty version of mintty, it's possible that the query response is arriving out of sequence. The app that generated the request would then fail to detect the response, so it ends up being interpreted as key presses instead. This shouldn't occur with wsltty.
> 
> See also #1118.

Thanks, i will read this first, i tried mintty build from git or mintty in cygwin, both the same.

**Comment by mintty** [comment]
I do not reproduce this issue, neither with both tools from git. Sure you compiled them with a cygwin toolchain?
Also, your steps to get the issue are not really described. Please provide a reproducible test case.

**Comment by mintty** [comment]
Is this issue resolved?

**Comment by nanaya** [comment]
I have similar problem and it looks like having this in tmux config:

```
set -g escape-time 0
```

Is one of the cause. Removing it or increasing it to something like 50 "resolves" the problem.

**Comment by mintty** [comment]
I do not reproduce such weird effect as described above even with escape-time 0.
As the issue is a bit older, please provide a fresh description of your issue.

**Comment by nanaya** [comment]
It doesn't always happen. It usually takes a few detach-attach cycle until it happens.

I'm just reporting what I found when trying various terminals last night, and I have no interest in investigating further, sorry.
