### ISSUE TITLE
Problem with link highlight/clicking when "_/" appears in path

### ISSUE THREAD

**Issue by jmmerz** [mintty/mintty#1218]
I've noticed a problem in Mintty 3.6.4 with link highlighting and clicking when the string `_/` (an underscore followed by a slash) appears in the URL or filesystem path.

### To reproduce:
1. Paste the string `https://www.example.com/this_/url/fails` into the terminal.
2. Hold the Control key and hover the mouse pointer over a point in the URL _**after**_ the `_/` (i.e. `url/fails` segment).

**Actual behavior:**
* When hovering, only `/url/fails` is highlighted.
* When I click on it, Mintty attempts to open the local directory `/url/fails`

**Expected behavior:**
* When hovering, the entire URL should be highlighted.
* When clicked, the entire URL `https://www.example.com/this_/url/fails` should be opened.

The same behavior occurs if `_/` appears in a local filesystem path. I'm keeping this report concise, but am happy to provide an example with local file paths if desired.

### Workaround:
If I hover the mouse over a point in the URL _before_ any instance of `_/` both highlight and clicking work as expected.

----
### Other info

* This works as expected in Mintty 3.6.3.
* I have not examined the code, but I suspect this may be related to the recent changes in #1196 to enable clicking URLs with parentheses.
* I'm using Mintty with Cygwin version 3.4.6-1 on Windows 10. (All recent Windows patches applied and I did a full update of Cygwin modules/dependencies/etc a few days ago).

**Comment by mintty** [comment]
This appears to be fixed in the current repository version already.

**Comment by jmmerz** [comment]
Thanks, just built from sources and verified it works.

Apologies for the noise, closing this issue now.
