### ISSUE TITLE
How to set the window title as the current working directory only?

### ISSUE THREAD

**Issue by silentmantra** [mintty/mintty#1220]
Currently it shows user@hostname: cwd which is too long and cut. I can't see the cwd.  
Removing user@hostname from the command prompt in the bash doesn't help.

**Comment by k-takata** [comment]
It would be set by `$PS1`.
You might want to search with "bash PS1 window title".

**Comment by silentmantra** [comment]
@k-takata set it, restarted, no changes. i mentioned that in the issue

**Comment by silentmantra** [comment]
there were several PS1 in .bashrc, fixed one and it started working
