### ISSUE TITLE
Feature suggestion: On <Escape>/<Enter> key, restore CJK IME to alphabet input mode

### ISSUE THREAD

**Issue by qqkookie** [mintty/mintty#1223]
Hi, I'd like to suggest a new feature on keyboard input and submit PR for it. 
This new feature will restore CJK input method editor(IME) state to alphabet input mode automatically on  \<Escape> or \<Enter> key press. 

Use case: User types CJK words using IME on command line shell or editor like Vim/Nano. User have to switch manually from CJK input mode to alphabet mode after typing \<Escape> or \<Enter> key. Most shell commands or editor commands key stroke are  English word or alphabet key. So CJK inputs typed after escape/enter key are mostly error. This is very error-prone and annoying for most CJK command line user. This will applies to most non-roman alphabet keyboard user with complex IME, like Korea, Japan, China, and most Asian/Indian and non-roman keyboard user including Cyrillic keyboard.

This feature/PR is to mitigate such CJK input annoyance. Pressing Escape key or Enter key will automatically restore IME mode to alphabet input mode. This feature is user configurable option in  Options/Keyboard feature page. The coding is done including Option setting addition. 

Any opinion or suggestion on such keyboard feature? May I submit new PR for it?

**Comment by mintty** [comment]
Thanks for the proposal. Questions:
* Does any other tool (terminal or application) have such a feature?
* What's the complete workflow? How is the IME activated for a single line?
* Wouldn't this interfere with other usage of the characters, esp. ESC which often has a meaning in text editors?

**Comment by qqkookie** [comment]
> Thanks for the proposal. Questions:
> 
> * Does any other tool (terminal or application) have such a feature?

hanterm (Korean version of X-window server: most widely used alternative to xterm in Korean Linux community),  [XSHELL](https://www.netsarang.com/en/xshell/) (commercial telnet/ssh client), [XMANAGER](https://www.netsarang.com/en/xmanager/) (commercial X-Window server), [iPuTTY](https://github.com/iPuTTY/iPuTTY) (open-source telnet/ssh client) comes to mind. This PR feature and code are inspired by work of the iPuTTY,

> * What's the complete workflow? How is the IME activated for a single line?

Nothing particular. Just add few lines of code to `wininput.c` and `config.[ch]` for option item and `make`.
See for yourself. https://github.com/mintty/mintty/compare/master...qqkookie:mintty:master

> * Wouldn't this interfere with other usage of the characters, esp. ESC which often has a meaning in text editors?

For roman alphabet keyboard like US English or European language keyboard, it does nothing. It only works on Korean, Japanese, Chinse, Cyrillic, and numerous non-roman alphabet language and keyboard that requires keyboard IME mode switching between native language input mode and ASCII alphabet input mode.  

Some caveats are when entering multi-line CJK text phrases, user have to press CJK composition key after pressing Enter key to add next line. Copy and pasting multi-line CJK-text is not affected. i.e. pasting works as expected.

**Comment by mintty** [comment]
I'd prefer to write out "keyboard" rather than "kbd" in the menu and the manual page.
Is "alphabet keyboard" actually an established term? Microsoft calls it "alphanumeric mode". Many people will not know what this is about. So maybe 
`ESC/Enter reset IME to alphnumeric keyboard`

> What's the complete workflow?

I didn't mean the patch but how do you enable IME again once it was reset by ESC/Enter?
Once we're settled, I can tweak the PR afterwards (e.g. space before but not after "(", some typos in the manual...).
The HTML manual does not need to be changed for a commit, that will be done automatically for the next release.

**Comment by qqkookie** [comment]
> I'd prefer to write out "keyboard" rather than "kbd" in the menu and the manual page. Is "alphabet keyboard" actually an established term? Microsoft calls it "alphanumeric mode". Many people will not know what this is about. So maybe `ESC/Enter reset IME to alphnumeric keyboard`

OK. I thought that "alphanumeric" and "IME" to be rather technical term. And "alphanumeric"  and "keyboard" words are  too long in crammed label space. I will change to `Esc/Enter restore IME to alphanumeric keyboard`

> 
> > What's the complete workflow?
> 
> I didn't mean the patch but how do you enable IME again once it was reset by ESC/Enter? Once we're settled, I can tweak the PR afterwards (e.g. space before but not after "(", some typos in the manual...). The HTML manual does not need to be changed for a commit, that will be done automatically for the next release.

Resetting IME does not means disable IME. It just switching to and pro between alphabet input mode and native CJK input mode. User can continue typing CJK words by  pressing the CJK compose key after pressing the Escape or Enter key. CJK compose key is dedicated key in CJK 103 key keyboard or right alt key in standard 101 key keyboard.  This PR just saves user on pressing single CJK compose  keystroke after typing Escape/Enter key to return to alphanumeric mode.

**Comment by mintty** [comment]
Forgot to mention, no </> tags in the change log please. So then submit the PR and I'll take care.

**Comment by mintty** [comment]
Release 3.6.5.
