### ISSUE TITLE
DECRQCRA is not reporting multiple rendition attributes correctly

### ISSUE THREAD

**Issue by j4james** [mintty/mintty#1225]
I'm using a simple bash test sequence to output a `*` with different rendition attributes, and then using `DECRQCRA` to checksum that cell. For example, this is how I'd test the underline attribute:
```
printf "\e[H\e[J\e[0;4m*\e[m\e[1;1;1;1;1;1*y"; read
```

And these are the results I'm seeing for a few different `SGR` attribute combinations:

| SGR     | Checksum |
| ------- | -------- |
| 0;4     | FFC6     |  
| 0;7     | FFB6     |
| 0;5     | FF96     |
| 0;4;7   | FFC6     |
| 0;4;5   | FFC6     |
| 0;4;5;7 | FFC6     |
| 0;5;7   | FFB6     |

Note how underline-reverse, underline-blink, and underline-blink-reverse are all returning the same checksum as underline by itself (i.e. `FFC6`). Similarly blink-reverse returns the same checksum as reverse by itself (`FFB6`). It looks like it's only counting one of the attributes when multiple are applied.

In case it's relevant, the version I'm using is mintty 3.6.4 (x86_64-pc-cygwin) - wsltty 3.6.4 (Windows 19045)

**Comment by mintty** [comment]
Thanks for the report. DEC specs are vague about the precise meaning of checksum, and they do not mention attributes to be considered at all. However, mintty aims to follow xterm behaviour and this is an easy fix.
Out of curiosity, do you see any practical use case for this request?

**Comment by j4james** [comment]
I find it useful for creating automated tests which can be run on multiple terminals, which can help identify interoperability issues. It's also useful being able to run tests on the original hardware, and that way verify that the tests themselves are correct - if the original hardware doesn't pass, there must be a bug in the test.

Just FYI, xterm doesn't exactly match the DEC hardware, because they support additional attributes and colors (on the VT525 at least). I can provide more details if you're interested, but I suspect you'll want to stick with xterm compatibility.

**Comment by BrianInglis** [comment]
Check the features and details match the [ctlseqs](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) docs as that, [vttest](https://invisible-island.net/vttest/vttest.html), [tack](https://invisible-island.net/ncurses/tack.html), and *ncurses* [terminfo](https://invisible-island.net/ncurses/ncurses.html#download_database) are the canonical sources which use, test, support, and document what terminals do. 
Feel free to submit additions, corrections, or questions to the developer at that site, as those are the most used references.

**Comment by mintty** [comment]
I did not mean mintty is limited by xterm. I just don't see any documentation _how_ DEC would support attributes. If you have an overview, please post it.
By the way, to enable support for characters above 0xFF in xterm as mintty is compatible to, you should `printf "\e[%d#y"  60` in xterm.

**Comment by j4james** [comment]
These are the attributes I'm aware of:

| Attribute            | Checksum Adjustment |
| -------------------- | ------------------- |
| Bold (SGR 1)         | 0x80                |
| Blink (SGR 5)        | 0x40                |
| Reverse (SGR 7)      | 0x20                |
| Underline (SGR 4)    | 0x10                |
| Invisible (SGR 8)    | 0x08                |
| Protected (DECSCA 1) | 0x04                |

Then on terminals with the color extension the checksum will track the colors values as follows:

* For the background color, the checksum is adjusted by the color index (in the range 0 to 15). For example, a blue background would adjust the checksum by 4.
* For the foreground color, the checksum is adjusted by the color index multiplied by 16. For example,  a blue foreground would adjust the checksum by 0x40.

Thus with the default colors usually being white on black, the checksum for a cell on a color terminal would typically differ from a monochrome terminal by 0x70.

**Comment by j4james** [comment]
> So there are no adjustments for âttributes like dim, italic

The DEC terminals that supported this sequence do not have dim and italic attributes.

> A "q" will have the same share or the checksum as an underlined "a"

This is not intended for reading the contents of the screen (although there are ways you could accomplish that if you really wanted to). The intent is to detect small mistakes in the output. And like any checksum, it's not guaranteed to catch everything, but it's not that likely that you'll have mistakenly output an underlined "a" when you actually meant to output a "q".

> About colors, there isn't really a concept of a default color in the ANSI range (0..15).

On DEC terminals there is. In the terminal's settings you can configure your preference for the default foreground and background colors, choosing from the available 16 colors in the palette. These are the colors that would be used for `SGR 0`, `SGR 39`, and `SGR 49`. There's also an escape sequence for altering those values. The original Windows console works in a similar way.

But as I said initially, I didn't think you'd want to support this functionality. You asked for the info, though, so I've provided it. I can quite easily skip color tests are terminals that don't support this so it's not a big deal to me. My main concern is the original bug report, because that causes a lot of tests to fail on Mintty that should otherwise work.

**Comment by mintty** [comment]
Released 3.6.5.

**Comment by j4james** [comment]
Thank you. That works much better now.

**Comment by mintty** [comment]
Released 3.7.1.
