### ISSUE TITLE
Feature suggestion: keep the window maximised when screen size changes

### ISSUE THREAD

**Issue by walkerxk** [mintty/mintty#1226]
I use a monitor on my work, when i join a meeting, I plug out hdmi cable, screen size changed, and I need to double click twice to maximised the window, can mintty keep the window maximised?

**Comment by mintty** [comment]
Screen size changes because the plugged-out monitor was coupled in desktop duplicate mode?
You can simulate this with only one monitor if you force another resolution - does the same thing happen?

**Comment by walkerxk** [comment]
the reason is because scale setting, I fix this by change scale to 100% :
I use 'show only on 2', 
first I take a screenshot when pluging to my monitor:
![screenshot-m1](https://github.com/mintty/mintty/assets/3411710/a896b36c-97b9-4641-9f48-3b2d2006e12a)
then I plug out hdmi cable:
![screenshot-l1](https://github.com/mintty/mintty/assets/3411710/3c61d2f9-e491-475f-b79f-bde2744cf057)
then I plug in hdmi cable again:
![screenshot-m2](https://github.com/mintty/mintty/assets/3411710/cd125a42-7922-47ff-afb8-76b0d25fc7f7)
display setting when plugin to my monitor:
![screenshot-ms](https://github.com/mintty/mintty/assets/3411710/116663bd-5958-4682-b09d-979eb8c90b3d)
display setting when plugin out:
![screenshot-ls](https://github.com/mintty/mintty/assets/3411710/9a9bce2a-80be-4268-8853-22010066f4a7)

**Comment by mintty** [comment]
Fixed the implicit change from fullscreen to maximised when DPI changes. It does not seem to be the same issue, though.
You may like to test the respository version anyway (build with packages gcc-core and make).

**Comment by walkerxk** [comment]
> Fixed the implicit change from fullscreen to maximised when DPI changes. It does not seem to be the same issue, though. You may like to test the respository version anyway (build with packages gcc-core and make).

thank you very much

**Comment by mintty** [comment]
The "normal" size and position (i.e. unzoomed) is now also preserved during changes of screen size or resolution, so if you restore the window from maximised or fullscreen after a screen change, the window should be restored as it was before zooming it.

**Comment by mintty** [comment]
I've now also tried to replay the original scenario but did not reproduce it, neither with the current repository version nor with release 3.6.4.
I simulated the different resolutions by forcing one monitor down to 800x600 while the other was 1920x1080, with one external monitor, tried both ways.
The maximised window stays maximised for me when switching monitor by plugging the cable.
Note, however, if you click its title bar and drag it just a little bit, the window restores from maximised to normal size, which may be the effect you observed. This is apparently normal Windows behaviour.

**Comment by mintty** [comment]
Release 3.6.5.

**Comment by walkerxk** [comment]
> I've now also tried to replay the original scenario but did not reproduce it, neither with the current repository version nor with release 3.6.4. I simulated the different resolutions by forcing one monitor down to 800x600 while the other was 1920x1080, with one external monitor, tried both ways. The maximised window stays maximised for me when switching monitor by plugging the cable. Note, however, if you click its title bar and drag it just a little bit, the window restores from maximised to normal size, which may be the effect you observed. This is apparently normal Windows behaviour.

Still the same, i didn't drag the title bar.

**Comment by mintty** [comment]
OK, I've tried to reproduce the procedure as described above. My external monitor is actually 1920x1200 but I scaled it down to 1920x1080, 100%. Internal 1920x1080, 150%. It works here, maximised is retained.

**Comment by mintty** [comment]
Released 3.7.7.
