### ISSUE TITLE
mintty prints junk when clicked

### ISSUE THREAD

**Issue by yunwu-jnpr** [mintty/mintty#1229]
This happens after Windows wakes up from a sleep.

![mintty](https://github.com/mintty/mintty/assets/89552663/485c7d26-5ba2-49d7-baeb-21422adfc43b)

Seems mitty is printing the coordinate of my mouse, because what printed is always same if mouse does not move, and it changes when mouse moved to another position.

**Comment by mintty** [comment]
These are mouse event reporting escape sequences.  Some program must have enabled them and then terminated or crashed without disabling them properly. What software did you run before in that terminal?

**Comment by yunwu-jnpr** [comment]
Oh... I was running `ssh` in mitty window.
Then seems it is `ssh` 's problem, instead of mintty's.

**Comment by mintty** [comment]
ssh itself does not set mouse reporting modes but maybe you were running some screen-oriented program, like an editor, on the remote side. Then ssh got disconnected because the connection could not be maintained during the sleep...

**Comment by yunwu-jnpr** [comment]
OK, maybe I was running `vim`, can not remember. Anway, agree it is not mintty problem. I am closing this one. Thank you very much!

**Comment by yunwu-jnpr** [comment]
Update:
I am able to confirm this is caused by `ssh`, because I had another test that before windows went to sleep, I had 2 mintty window open: one was running `ssh`, the other was not.
Then after windows woke up, only the mintty window running `ssh` has problem, the other does not.

Also, I found the problem can also be fixed by `reset` command, just like how I usually do on a Linux when my terminal prints junk.

Sorry for creating this, but hopefully this might also benefit other people who run into this.

**Comment by BrianInglis** [comment]
Recommendation is to run `ssh` sessions that might become disconnected under `tmux` (or `screen`), so that you can reconnect and continue your work:
[Right click to search in new tab: ssh tmux screen](https://duckduckgo.com/?q=ssh+tmux+screen)

**Comment by yunwu-jnpr** [comment]
@BrianInglis  right, I always do that, but I need to ssh to the server in mintty window before I can `tmux a -t <session>`.

**Comment by BrianInglis** [comment]
Recommendation is to start `tmux` locally, and run long running `ssh` sessions from it, so that if anything happens, you can resume your work where you left off.

**Comment by yunwu-jnpr** [comment]
@BrianInglis Right, I always run `tmux` (server) in ssh server, but I need a ssh connection in mintty window before I can type `tmux a -t <session>` (client).
