### ISSUE TITLE
LESS behavior changed in Git for Windows between v2.40 and 2.41

### ISSUE THREAD

**Issue by rcdailey** [mintty/mintty#1230]
In the [Git Release Notes](https://github.com/git-for-windows/git/releases/tag/v2.41.0.windows.1), it mentions MinTTY upgraded from v3.6.3 to v3.6.4. I'm not sure where this issue should technically be reported, so I'm starting here. I admittedly do not fully understand where the boundary lies between MinTTY and Cygwin. If I need to report this elsewhere, please point me in the right direction.

In Git for Windows v2.40.1, when I do `git log` (which uses `less`), my console clears when I quit and then the terminal prompt returns where it left off prior to that. I use these settings in my `.bashrc`:

```bash
export LESS="-RSic~ -x2"
export LESSHISTSIZE=0
export LESSCHARSET=UTF-8
```

## Behavior in v2.40.1

I type in `git log` and I get a full screen log using `less`, as expected:
![image](https://github.com/mintty/mintty/assets/1768054/2d7c3eb9-63c5-4502-8aef-3415d758201f)

After that, I hit `q` to exit and my terminal prompt appears just below the last `git log` which I expect:
![image](https://github.com/mintty/mintty/assets/1768054/5b99e843-31f3-4edf-81be-54e655ede9a6)

## Behavior in v2.41.0

The `git log` screen appears as it does in the previous section, so I won't repeat that screenshot here. However, the way it looks when I do `q` to exit is much different:
![image](https://github.com/mintty/mintty/assets/1768054/df80233d-6ebf-4f5f-9697-068a32b54fdf)

Notice how the previous command history is missing. I also sometimes see the prompt appear towards the bottom of the terminal, with a huge gap of whitespace.

Is this a MinTTY issue or something else?

**Comment by BrianInglis** [comment]
In general, you are better reporting issues to your distribution provider *GfW*, as they are aware of what they have changed recently, and can redirect if necessary to their upstreams to report. 
Looks like *GfW* `mintty` has not been updated in months but *GfW* `less` was updated recently, so report against that *GfW* package. 
If they feel it necessary, they can suggest you report upstream against *MSYS2* `less`.

**Comment by rcdailey** [comment]
I won't go into details, but I distance myself from the GfW project. So I need another solution. I appreciate your hint. I think I can look into reporting at the MSYS2 repo.

I'll go ahead and close this issue as it seems to be the case that this isn't the right place. Thank you!

**Comment by mintty** [comment]
I speculate the effect is related to switching to the alternate screen and back. Whether git or less changed some default or configuration I cannot say without further testing.

**Comment by dscho** [comment]
> Looks like _GfW_ `mintty` has not been updated in months

@BrianInglis that's because it's at v3.6.4, which is the latest.
