### ISSUE TITLE
double click doesn't select entire path from ~ with WordChars workaround setting

### ISSUE THREAD

**Issue by sh2ka** [mintty/mintty#1237]
Now it selects a path starting from slash, i.e. `~/foo/bar` is selected and copied as `/foo/bar`.
mintty version is 3.6.5 (x86_64-pc-msys). 
Tested using bash, zsh and fish shells. So it looks like mintty bug.

**Comment by mintty** [comment]
This was a bug in 3.6.4 but fixed in 3.6.5, please check again.
Do you have a WordChars setting configured?

**Comment by sh2ka** [comment]
Oh, yeah, thanks. It's true - I've found that setting in .minttyrc file. Probably, that was a trial to fix the problem by myself before the fix. Many thanks for the fix!
