### ISSUE TITLE
mintty + wsl.exe + tmux: resizing tmux pane with mouse not working

### ISSUE THREAD

**Issue by yunwu-jnpr** [mintty/mintty#1238]
1. If I use mintty to run `wsl.exe` then run tmux there (i.e. `mintty.exe -e wsl -- tmux` in short), then resizing tmux pane with mouse does not work.
![mintty_plus_wsl_plus_tmux__having_problem](https://github.com/mintty/mintty/assets/89552663/1da5fed1-593d-4cb4-8073-f478e669a979)

2. But if I run `wsl.exe` in cmd and run tmux there, then no problem.
![cmd_plus_wsl_plus_tmux__no_problem](https://github.com/mintty/mintty/assets/89552663/605184d1-2434-4bd2-a487-b47422965bba)

3. If I use mintty to ssh WSL and run tmux there, then also no problem.
![mintty_ssh_wsl_and_run_tmux__no_problem](https://github.com/mintty/mintty/assets/89552663/5396076d-be7f-4fb7-bd00-571d7cfcd40a)

**Comment by mintty** [comment]
Using wsl.exe imposes severe limitations on terminal function because wsl.exe has its own idea of what a terminal could be.
That's why the wsltty project was created.
Using ssh is an interesting alternative. How do you start WSL in this case and how do you determine the IP to use?

**Comment by yunwu-jnpr** [comment]
@mintty Thanks for pointing [wsltty](https://github.com/mintty/wsltty) to me, just aware of it. Let me try if that fix the problem.
For your question how to start WSL, not sure if this what you were asking, but I just start it by running `wsl` command in either cmd or mintty. I can close cmd or mintty window and run `wsl` again in another window.
To determine WSL IP address, I just use `127.0.0.1` since I have set `localhostForwarding=true` in my `C:\Users\<user>\.wslconfig`. See [Advanced settings configuration in WSL](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#main-wsl-settings) on Microsoft website. Alternatively, I also configure a static IP address for my WSL by configuring a bootup script in WSL `/etc/wsl.conf` > `[boot]` section > `command=<a_script>` (see [boot-settings](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#boot-settings) section on the same page).

**Comment by yunwu-jnpr** [comment]
I tried wsltty already. It fixes the tmux pane resizing not working problem indeed, however it loses a benefit `mintty` provides -- if you `ls` a directory and it shows those files, then you press `Ctrl` button and hover mouse on a file, then the file becomes a link, and you can click it then mintty launches an external application to open it (e.g. an text editor). This feature still works for `mintty + wsl.exe`. But with `wsltty`, or `mintty + ssh WSL`, this feature does not work.

So I probably will continue using `mintty + wsl.exe`, and switch to either `wsltty` or `mintty + ssh WSL` when I need tmux + panes.

Thanks!

(If the tmux pane resizing issue under `mintty + wsl.exe` is caused by `wsl.exe`, then we can close this. Thanks very much anyway!)

**Comment by ak2** [comment]
I use ssh to connect to WSL2 on localhost as well, with a small script in shell:startup to start a hidden persistent wsl session, as unfortunately ssh sessions don't keep it alive.
```
set ws=wscript.CreateObject("wscript.shell")
ws.run "wsl sleep infinity", 0
```
It's the `, 0` that hides it.

Relative file links in WSL sessions can be made to work by telling mintty what your working directory is in terms of the `wsl$` mount point that WSL creates for your distribution, using control sequence OSC 7. For example, by adding it to the PS1 setting:
```
PS1+='\e]7;//wsl\$/Ubuntu$PWD\a'
```
Absolute paths and those starting with `~` won't work though.

**Comment by mintty** [comment]
Unfortunately, there are more prerequisites to using ssh, so I don't think it can be used reliably in a package for WSL connectivity:

- sshd needs to be installed in each WSL distribution (Ubuntu has it by default, Debian and others don't)
- sshd needs to be configured and launched
- the IP address of each WSL distribution needs to be known

**Comment by yunwu-jnpr** [comment]
> unfortunately ssh sessions don't keep it alive

@ak2 have you tried `ServerAliveInterval` and `ServerAliveCountMax` SSH options?
I have `ServerAliveInterval 20` and `ServerAliveCountMax 3` in my `/c/Users/<user>/.ssh/config` and I never had a problem.

> the IP address of each WSL distribution needs to be known

@mintty Not really. You can use 127.0.0.1 as I said. The other 2, right, but I think it is pretty simple.

**Comment by ak2** [comment]
sshd staying alive isn't an issue, but WSL itself shuts down after 8 seconds if there isn't a wsl.exe session, even if an ssh session is open.

**Comment by mintty** [comment]
> You can use 127.0.0.1 as I said.

If you have multiple WSL distributions running, it will not be possible to reach them by the same IP.

> The other 2, right, but I think it is pretty simple.

For a WSL frontend (similar to wsltty), the issue is to get this done automatically, on-the-fly.
First, if you find sshd not to be installed, you'd need to install it, using different package managers, using sudo (and you'll be asked for a password). Then, running sshd fails for example with "Missing privilege separation directory: /run/sshd". This is all practically untractable.

**Comment by yunwu-jnpr** [comment]
I see your point. Thanks, @mintty .

**Comment by mintty** [comment]
I have an idea to create a new "bridge" that would be resilient against changes in the WSL system by using wsl.exe.
In order to make pty I/O transparent, escape sequences would be "tunneled" through virtual normal character I/O.
I have a prototype already, handling output only so far.

**Comment by yunwu-jnpr** [comment]
Not sure if you fixed it or something else workaround it, but I happened to notice that it is now working as expected in my Windows 11 + mintty + WSL + tmux.
(When reporting this problem I was using Windows 10).
I think we can close this ticket. And thanks again!

![mintty_wsl_tmux](https://github.com/user-attachments/assets/74fb38d2-940c-4261-9070-d97fb6e3038e)
