### ISSUE TITLE
getemoji script not working

### ISSUE THREAD

**Issue by AminoffZ** [mintty/mintty#1240]
`cd "C:\Program Files\Git\usr\share\mintty"`
`mkdir emojis`
`cd emojis`
`curl -LO https://raw.githubusercontent.com/wiki/mintty/mintty/getemojis`
`getemojis -d`
`getemojis .`

It creates all the folders but only adds some to common/
Running `getemojis . windows` echoes codes but nothing is extracted.

**Comment by mintty** [comment]
Apparently, unicode.org have changed their emoji publishing policy and the format of the emoji charts lists.
They do not offer a set of styles anymore, just one style, called "Sample" but looking like Google emojis.
I'll adapt the script to download at least those, for the other styles I have no download sources.
For now, please switch to another source as listed in the wiki, e.g. OpenMoji (now at version 14.0.0, 15 may be released soon according to git comments).

**Comment by mintty** [comment]
Released 3.7.0.
