### ISSUE TITLE
Minimizing tabbed mintty confuses focus; makes tab unreachable via keyboard

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#1242]
In #1207, I wrote
> I just recently tried again to fix an Autohotkey workaround. It mostly works with SessionGeomSync <= 2, but has issues when mintty is minimized. I am happy to see that mintty's built-in handling seems to work flawlessly.

But unfortunately, I have to retract that statement.

Steps to reproduce:

1. start `mintty --class=mintty-test --tabbar=4`
2. open new tab with Alt+F2
3. minimize mintty by any method
   - minimize button in Window title or
   - clicking on the taskbar button of the already focused window or
   - Alt+Tab to another window, then Windows+Home to minimize other windows
6. Alt+Tab to mintty
7. Ctrl+Tab => Bug: nothing happens
8. Click "unreachable" mintty tab => this works as expected
9. Ctrl+Tab (repeatedly) => mostly works; both tabs are reachable again, but:
   Bug: Sometimes it looks like no window has focus. 
   - Type a letter in this situation => it seems as if this is ignored, but…
   - Press Ctrl+Tab again (twice [or more if unlucky] to get back to the tab with the entered letter) => focus restored; now you see that the letter is there.

(Concerning affected versions: I think I had similar issues with mintty 3.6.5 on my private computer, but didn't look much into it. On my work computer, I have skipped 3.6.5 because it got blocked by Windows Security. Today, I tried 3.7.0, and Windows Security allows it.)

**Comment by mkq** [comment]
Now I had the state described in step 7 in a fresh mintty session of which no tab was ever minimized, just by hitting Ctrl+Tab repeatedly too fast, it seems.

(Probably irrelevant side note: That session was started via command `mintty --class=mintty-2 -s 210,92 -p bottom -p right --tabbar=4 -i /c/….ico -e /bin/zsh` pinned to the taskbar.)

**Comment by mintty** [comment]
Broken since 3.6.5, commit caf39a1f251c9b3bd9efbe3aa8f09cb425084435.

**Comment by mintty** [comment]
... however, reverting that change in the current version apparently does not fix the issue.

**Comment by mintty** [comment]
... this was a diagnostic mistake; there were 3 changes, a weird set of combining some of them does fix the Ctrl+TAB issue (step 7) while keeping the fixed transparency behaviour.
The hidden-after-minimized issue (step 5) is a different thing. It was the purpose of those changes to combine the tabs into only one taskbar icon, which makes the other tabs "very hidden". To be analysed.

**Comment by mintty** [comment]
Revised tab switching. Testing would be appreciated.

**Comment by mkq** [comment]
Thanks!

I have built the current (Commit afd564c2) repo. Unfortunately (and as expected), Windows security blocks the resulting mintty.exe on my work PC.

So I'll have to test on my private PC, but that will be less thorough.

**Comment by mkq** [comment]
First impressions: Works well for me.
(Reminder: I am using two mintty commands with different `--class` pinned to the taskbar.)

1. Minor issue: On every tab switch, an additional taskbar button is shown for a fraction of a second. I think only one extra button, even if the session consists of more than two tabs.
2. Extremely minor issue: After waking my PC from hibernation, one mintty session was shown as two taskbar buttons. After switching through the session's tabs, it fixed itself.

Hopefully, Windows Security will soon let me use an up-to-date mintty again. After using Windows Terminal for a few months, I noticed how much I miss some features: Keeping search open to highlight new matches, scroll markers, user commands.

**Comment by mkq** [comment]
(Windows Security now lets me use my self-built mintty.exe at work.)

Another minor issue: When e.g. minnty at taskbar position 5 (and in `--tabbar=4` mode) has focus and I press Win+5,

- sometimes it works as expected, i.e. the window is minimized and focus is transfered to another window, and
- sometimes the mintty window only flashes a little and I need to press Win+5 again to minimize.

**Comment by mintty** [comment]
> sometimes the mintty window only flashes a little and I need to press Win+5 again to minimize.

This seems to depend on whether the first or another of the tabs is currently in focus/foreground.
See also https://github.com/mintty/mintty/issues/1249#issuecomment-1903383919

**Comment by mintty** [comment]
Released 3.7.1.
