### ISSUE TITLE
In mintty, the Chinese characters are not displayed when executing 'appcmd.exe' for IIS

### ISSUE THREAD

**Issue by qidizi** [mintty/mintty#1248]
## systeminfo output

```text
OS 名称:          Microsoft Windows Server 2019 Datacenter
OS 版本:          10.0.17763 暂缺 Build 17763
系统区域设置:     zh-cn;中文(中国)
输入法区域设置:   zh-cn;中文(中国)
时区:             (UTC+08:00) 北京，重庆，香港特别行政区，乌鲁木齐

修补程序:         安装了 12 个修补程序。
                  [01]: KB5031990
                  [02]: KB4470788
                  [03]: KB4486153
                  [04]: KB4486155
                  [05]: KB5005112
                  [06]: KB5032196
                  [07]: KB5020374
                  [08]: KB5023789
                  [09]: KB5028316
                  [10]: KB5030505
                  [11]: KB5031589
                  [12]: KB5032306
```  

**C:\Windows\System32\inetsrv\appcmd.exe version (iis version)**: 10.0.17763.1
**D:\soft\cygwin64\cygwin\bin\mintty.exe version**:  3.7.0.0

## cmd.exe+appcmd.exe output

```text
Microsoft Windows [版本 10.0.17763.5122]
(c) 2018 Microsoft Corporation。保留所有权利。

C:\Users\Administrator>C:\Windows\System32\inetsrv\appcmd.exe /?
通用 IIS 命令行管理工具。

APPCMD (命令) (对象类型) <标识符> </参数1:值1 ...>

支持的对象类型:

  SITE      虚拟站点的管理
  APP       管理应用程序
  VDIR      管理虚拟目录
  APPPOOL   管理应用程序池
  CONFIG    管理常规配置节
  WP        管理工作进程
  REQUEST   管理 HTTP 请求
  MODULE    管理服务器模块
  BACKUP    管理服务器配置备份
  TRACE     使用失败请求跟踪日志
  BINDING   与 SSL 绑定一起使用的对象

(要列出每个对象支持的命令，请使用 /?，例如“appcmd.exe site /?”)

常用参数:

/?               显示上下文相关帮助消息。

/text<:value>    以文本格式(默认)生成输出。
                 /text:* 在详细信息视图中显示所有对象属性。
                 /text:<attribute> 显示每个对象的
                 指定特性的值。
/xml             以 XML 格式生成输出。
                 使用此参数生成的输出可发送至
                 以 /in 模式运行的其他命令。
/in or -         自标准输入读取和操作 XML 输入。
                 使用此参数可操作运行于 /xml 模式的
                 其他命令生成的输入。
/config<:*>      显示所显示对象的配置。
                 /config:* 还包括继承的配置。
/metadata        在显示配置时显示配置元数据。

/commit          设置用于保存配置更改的配置路径。
                 可以指定具体的配置路径、“site”、
                 “app”、“parent”或“url”以保存到该命令正在编辑的
                 路径的适当部分，也可以设置为对应的配置级别
                 的“apphost”、“webroot”或“machine”。
/apphostconfig   指定要编辑的替代 applicationHost.config 文件。
/debug           显示命令执行的调试信息。

-使用“!”以转义与常用参数同名的参数，
例如“/!debug:value”设置一个名为“debug”的配置属性。

C:\Users\Administrator>
```   

## but,mintty+appcmd output "hide chinese"

a.bat  content   

```batch
cd /d d:\Users\Administrator\Desktop
d:\soft\cygwin64\cygwin\bin\mintty.exe -l ./log.txt -h always -o Locale=zh_CN -o Charset=UTF-8 --trace ./trace.txt  --position 0,0 --dir ./ -e c:/Windows/System32/inetsrv/appcmd.exe /? 
```   

then double click to run `a.bat`     

but, trace.txt is empty!    

[log.txt](https://github.com/mintty/mintty/files/13695094/log.txt)    

log.txt content sceenShot    
<img width="424" alt="log txt Screenshot 2023-12-17 at 15 45 20" src="https://github.com/mintty/mintty/assets/3324382/80b05a51-4a80-480c-aee5-5744271dfd09">   

mintty output  content  
```text

Error: Could not open log file: File exists.

D:\Users\Administrator\Desktop\log.txt.
 IIS

APPCMD () () <> </1:1 ...>

:

  SITE
  APP
  VDIR
  APPPOOL
  CONFIG
  WP
  REQUEST    HTTP
  MODULE
  BACKUP
  TRACE
  BINDING    SSL

( /?appcmd.exe site /?)

:

/?

/text<:value>    ()
                 /text:*
                 /text:<attribute>

/xml              XML

                  /in
/in or -          XML
                  /xml

/config<:*>
                 /config:*
/metadata

/commit
                 site
                 appparenturl

                 apphostwebrootmachine
/apphostconfig    applicationHost.config
/debug

-!
/!debug:valuedebug

c:/Windows/System32/inetsrv/appcmd.exe: Exit 1.

```   

mintty+appcmd and mintty+cygwin+cmd screenShot    
<img width="1440" alt="a bat and cygwin Screenshot 2023-12-17 at 15 42 34" src="https://github.com/mintty/mintty/assets/3324382/df934934-752d-464e-ab6d-641e11debd2e">

**Comment by qidizi** [comment]
charset=GBK screenShot   
<img width="833" alt="gbk Screenshot 2023-12-17 at 16 04 09" src="https://github.com/mintty/mintty/assets/3324382/7cd1ce33-4738-4f87-83f0-006a855792d1">

**Comment by mintty** [comment]
Option `--trace` is only intended to capture debug and reporting output from mintty. In a release version, there is no debug output, so clearly the output stays empty unless you use one of the `-R` reporting options.
What is `appcmd`? Mintty is intended to run cygwin applications in the first place. With native Windows applications, you may indeed get character encoding problems. You configured mintty to run GBK encoding but is that also the encoding of your Windows environment? POSIX-style locale configuration will _not_ affect Windows applications, they use the Windows encoding anyway.
Simply running mintty with GBK works fine. Your screenshots do not explain anything either.

**Comment by qidizi** [comment]
`what is appcmd` ?   
[it is "C:\Windows\System32\inetsrv\appcmd.exe"](https://learn.microsoft.com/zh-cn/iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe)     
     

`Simply running mintty with GBK works fine`："Not true, still unable to display Chinese characters."，see `a.gbk.bat` code,and mintty output sceenshot:     

> charset=GBK screenShot <img alt="gbk Screenshot 2023-12-17 at 16 04 09" width="833" src="https://private-user-images.githubusercontent.com/3324382/291043283-7cd1ce33-4738-4f87-83f0-006a855792d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4MTA2MTIsIm5iZiI6MTcwMjgxMDMxMiwicGF0aCI6Ii8zMzI0MzgyLzI5MTA0MzI4My03Y2QxY2UzMy00NzM4LTRmODctODNmMC0wMDZhODU1NzkyZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTdUMTA1MTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjdlMjFkYzM1MGFhN2U4YmIxYzQ3Njc4NDhkNzNkNmZhMTY3NTdhMWZhNmQ1ZjAyMDNjMDdmMDg1MmE3Yjc0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NYfcHBur8Dm2jBK2n67qn3QdS514QRUXP1YGSJBxlEw">

**Comment by mintty** [comment]
My Windows folder System32/inetsrv is empty, so you've installed some additional feature.
The screenshot does not have any information about the character encoding used for output from your application. I tested it before my statement. In `mintty -o Locale=zh_CN -o Charset=GBK`, `cat` from a file with GBK encoding is displayed correctly. Your issue is an inconsistency of character encodings. You can probably analyse it when redirecting output of `appcmd` to a file and checking the encoding of the output there. If in doubt, upload such output file here.

**Comment by qidizi** [comment]
see this 
![Untitled](https://github.com/mintty/mintty/assets/3324382/969279f9-64e1-48c8-83bc-af6c283a61c6)

**Comment by qidizi** [comment]
log.txt see 1st post.    

<img width="793" alt="Screenshot 2023-12-17 at 19 20 14" src="https://github.com/mintty/mintty/assets/3324382/62038905-c325-4d65-9ba8-7bd10a858e26">

**Comment by qidizi** [comment]
#  cmd.exe+appcmd.exe  or mintty.exe+cmd.exe  can display chinese 
<img width="1142" alt="cmd" src="https://github.com/mintty/mintty/assets/3324382/fec70c8e-e471-47fa-933c-7b06ba4a92e0">   


# mintty.exe+utf8+appcmd.exe can not display chinese

<img width="1440" alt="appcmd utf8" src="https://github.com/mintty/mintty/assets/3324382/702877ad-1bfc-4c8c-9e9f-8e6f3401884c">   

# mintty.exe + gbk+appcmd.exe can not display chinese too!

<img width="1440" alt="appcmd gbk" src="https://github.com/mintty/mintty/assets/3324382/30a6ca74-fb7c-416b-b73b-5ac9777ab06e">

**Comment by mintty** [comment]
Your first log.txt screenshot does not show any Chinese characters. Your second log.txt shows Chinese characters only verbatim, not their encoding bytes, so nothing that could be analysed.
Now please (I could have asked before), in the GBK environment where you expect appcmd to work, run the Windows tool `chcp.com` to show the actual Windows encoding configured.
Even if it's GBK, it could still be the case that appcmd is simple not capable of adapting to encodings and ignores any such setting completely.
You've verified yourself that mintty and cmd cooperate well to display Chinese; you could also repeat that test case with GBK, please.

**Comment by qidizi** [comment]
I will attempt more tests.     

`appcmd.exe` is a built-in tool for Internet Information Services (IIS) v10.  [en version doc](https://learn.microsoft.com/en-us/iis/get-started/getting-started-with-iis/getting-started-with-appcmdexe#how-to-use-appcmdexe)    

<img width="801" alt="Screenshot 2023-12-17 at 20 13 40" src="https://github.com/mintty/mintty/assets/3324382/d3e9c02d-1843-43ec-a8e7-5b8559a887df">

**Comment by qidizi** [comment]
cmd.exe+ ASCII +appcmd.exe   or cmd.exe + gbk+ appcmd.exe or cmd.exe + utf8+appcmd.exe，All prompt text can be displayed completely.    
<img width="784" alt="image" src="https://github.com/mintty/mintty/assets/3324382/7edc06fb-0eab-47ea-aa42-c09fe7935d8d">  


I don't know how to switch mintty.exe to run appcmd with GBK encoding？

**Comment by qidizi** [comment]
Do it like this? However, it didn't solve the problem.   

<img width="1372" alt="image" src="https://github.com/mintty/mintty/assets/3324382/88d6c444-6f6a-4f66-938d-a44a96512b3a">

**Comment by mintty** [comment]
> I don't know how to switch mintty.exe to run appcmd with GBK encoding？

Codepage 936 is GBK. So run `mintty -o Locale=zh_CN -o Charset=GBK`, then inside it, run `chcp.com 936`.
This configures Windows tools to use GBK, but only those that respect the setting. Either it will work then, or your tool simply ignores the setting.

**Comment by qidizi** [comment]
Found the issue, it was caused by a character=0 encoding.    
<img width="1440" alt="image" src="https://github.com/mintty/mintty/assets/3324382/5a999fb2-fb33-4991-92c1-a373e5e46ddc">

**Comment by qidizi** [comment]
thank you!

**Comment by qidizi** [comment]
Suggestion: Assuming the `locale` is UTF-8, set mintty to use 'chcp.com 65001' initially, instead of 'chcp.com === 0'.

**Comment by mintty** [comment]
Mintty does not set chcp to 0. Thanks for confirming the solution, even though the cause is unclear.

**Comment by qidizi** [comment]
test step:  
1.  open cmd.exe    
2. input `chcp 65001 && d:\soft\cygwin64\cygwin\bin\mintty.exe -o Locale=zh_CN -o Charset=UTF-8 -h always -`  
3.  cmd.exe show `Active code page: 65001` and keep window   
4. mintty(maybe bash?) window run `locale` get `LANG=zh_CN.UTF-8 ...`,but run `chcp.com` get `活动代码页: 0` ,it mean `Active code page: 0`   
5. so

**Comment by qidizi** [comment]
`$ cat .minttyrc`   

get   
```bash
ThemeFile=mintty
Font=Menlo
Locale=zh_CN
Charset=UTF-8
FontHeight=14



# maybe do like this:   
if [[ "$Charset" == "UTF-8" ]];then
   chcp.com 65001
else
  chcp.com 437
fi


```

**Comment by mintty** [comment]
> maybe step 3 can not pass(keep) 65001 to mintty window(session).

No, it cannot. But it does not say 0 for me either. It reverts to 850, which I had before chcp 65001 in the fresh cmd console window. If you start a fresh cmd console, what does cpch tell you then?

**Comment by mintty** [comment]
> if [[ "$Charset" == "UTF-8" ]]; then chcp.com 65001

It was considered before that mintty could do that already but it seems it didn't work:
https://github.com/mintty/mintty/issues/1053#issuecomment-718504747

**Comment by qidizi** [comment]
> > maybe step 3 can not pass(keep) 65001 to mintty window(session).
> 
> No, it cannot. But it does not say 0 for me either. It reverts to 850, which I had before chcp 65001 in the fresh cmd console window. If you start a fresh cmd console, what does cpch tell you then?

1. change console default codepage. press `window+R` -> input `intl.cpl` -> ok -> region window/administrative panel/change system locale...  -> region settings -> current system locale is `Chinese (Simplified,China)` -> checked`Beta:use unicode utf-8 for worldwide language support` -> ok -> restart pc     
2.  get 1st cmd codepage. press `window+R` -> input `cmd` -> ok -> cmd window ,title is `administrator:c:\windows\system32\cmd.exe`,welcome text  `Microsoft Windows [Version 10.0.17763.5206]...` -> run `chcp` display `Active code page: 65001` -> run `start "" cmd.exe`  -> close this cmd window  
3.  get 2st cmd codepage. on new cmd window -> run `chcp` display `Active code page: 65001` too   -> run  `d:\soft\cygwin64\cygwin\bin\mintty.exe -o Locale=zh_CN -o Charset=UTF-8 -h always -`,named `mintty window` -> on this cmd window run `chcp` display `Active code page: 65001`   -> close this cmd window   
4. get mintty codepage.   on `mintty window` -> run `chcp.com` display `Active code page: 0`  ->  `cat ~/.minttyrc` display:  
```bash
ThemeFile=mintty
Font=Menlo
Locale=zh_CN
Charset=UTF-8
FontHeight=14
```
-> `locale` display  
```bash
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=

```  
  -> menu selected `options...`,and switch `text` :locale is `zh_CN`,Charset set is `UTF-8`  
-> back to `mintty window` -> run `cmd` -> inline cmd session -> run `chcp` display `Active code page: 0` -> run `start "" cmd ` -> on new cmd window -> run `chcp` display `Active code page: 65001` -> close this cmd window,back mintty inline cmd -> run `exit` -> in mintty session -> run `chcp.com` display `Active code page: 0` -> run `chcp.com 65001` ,display `Active code page: 65001` -> confirm ,run `chcp.com` ,display `Active code page: 65001` -> run `cmd` -> inline cmd session -> run `chcp` display `Active code page: 65001` -> run `c:/Windows/System32/inetsrv/appcmd.exe invalidOption`,display `Object 'INVALIDOPTION' is not supported.  Run 'appcmd.exe /?' to display support
ed objects.`,it is ok -> exit cmd to mintty session  -> run `chcp.com` display 65001 -> run `/cygdrive/c/Windows/System32/inetsrv/appcmd.exe invalidOption`,display `Object 'INVALIDOPTION' is not supported.  Run 'appcmd.exe /?' to display support
ed objects.`,it is ok -> try run `chcp.com xxx` ,**i can not reproduce `chcp.com` display codepage 0** ->run `bash` -> run `chcp.com` get 65001 -> exit -> run `bash -l` ->run `chcp.com` get 65001 -> exit -> run `mintty -` -> in new mintty window,run `cpch.com` **get 0**    


last: i do not know why mintty init codepage===0    
5.

**Comment by qidizi** [comment]
1. mkdir `d:\test\` and `d:\test\bin2`   
2.   copy d:\soft\cygwin64\cygwin\bin\mintty.exe and d:\soft\cygwin64\cygwin\bin\cygwin1.dll to `d:\test\bin2` 
3.  copy `d:\soft\cygwin64\cygwin\bin` and `d:\soft\cygwin64\cygwin\usr` to `d:\test\`  
4.  in any cmd window run `d:\test\bin2\mintty.exe -h always -o Locale=zh_CN -o Charset=UTF-8  -e chcp.com` will display `codepage===0`    

so must be `bin`or `usr` something wrong

**Comment by qidizi** [comment]
found   
when `bin/cygwin-console-helper.exe` exists, `d:\test\bin2\mintty.exe -h always -o Locale=zh_CN -o Charset=UTF-8  -e chcp.com` will display `codepage===0`   

rename `bin/cygwin-console-helper.exe`  to `bin/0000000cygwin-console-helper.exe`, will display `codepage===65001`

**Comment by BrianInglis** [comment]
Could that be because this is a non-Cygwin build of `mintty`? 
Is this built under *Msys2* or built for *WSL/2* with `wsltty` interfaces? 
Are /bin/cygwin1.dll and /bin/cygwin-console-helper.exe built within minutes of each other e.g.
```
$ stat /bin/cygwin{1.dll,-console-helper.exe}
  File: /bin/cygwin1.dll
  Size: 2954293         Blocks: 2888       IO Block: 65536  regular file
Device: 60997,17217     Inode: 2533274790402854  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (.../     ...)   Gid: (  544/Administrators)
Access: 2023-12-17 21:32:59.626505100 -0700
Modify: 2023-11-29 05:20:00.000000000 -0700
Change: 2023-12-15 11:11:24.000010700 -0700
 Birth: 2023-12-15 11:11:23.930989200 -0700
  File: /bin/cygwin-console-helper.exe
  Size: 41491           Blocks: 44         IO Block: 65536  regular file
Device: 60997,17217     Inode: 5910974510930725  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (.../     ...)   Gid: (  544/Administrators)
Access: 2023-12-17 07:11:00.803307700 -0700
Modify: 2023-11-29 05:19:54.000000000 -0700
Change: 2023-12-15 11:11:23.930989200 -0700
 Birth: 2023-12-15 11:11:23.930989200 -0700
```
It is much easier to understand the information you provide if you show actual `cmd`  `...>` or `bash` `$` or `%` prompts with input commands on one line, then outputs or results on later lines, with comments between on ':' or `#` prefixed comment lines; 
or split up each GUI selection on to a separate line; 
just as if in a test script or example. 

We are culturally accustomed to provide and process these, rather than paragraphs in "stream of consciousness" style, which we have to split up to make sense of, in order to avoid missing crucial information or points.

**Comment by qidizi** [comment]
run `$ uname -srvmo` display    

```text
CYGWIN_NT-10.0-17763 3.4.10-1.x86_64 2023-11-29 12:12 UTC x86_64 Cygwin
```  

run `stat /bin/cygwin{1.dll,-console-helper.exe}`   display    

```text
$ stat /bin/cygwin{1.dll,-console-helper.exe}
  File: /bin/cygwin1.dll
  Size: 2954293         Blocks: 2888       IO Block: 65536  regular file
Device: 29826,28544     Inode: 1970324837317283  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (197108/Administrator)   Gid: (197121/    None)
Access: 2023-12-15 12:32:48.817770700 +0800
Modify: 2023-11-29 20:20:00.000000000 +0800
Change: 2023-12-15 12:32:48.817770700 +0800
 Birth: 2023-12-15 12:32:48.714946000 +0800
  File: /bin/cygwin-console-helper.exe
  Size: 41491           Blocks: 44         IO Block: 65536  regular file
Device: 29826,28544     Inode: 1688849860606626  Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (197108/Administrator)   Gid: (197121/    None)
Access: 2023-12-15 12:32:48.699265900 +0800
Modify: 2023-11-29 20:19:54.000000000 +0800
Change: 2023-12-15 12:32:48.699265900 +0800
 Birth: 2023-12-15 12:32:48.699265900 +0800

```

**Comment by BrianInglis** [comment]
Sorry I was slow adding another edit to my previous questions. 

Which *Windows* keyboard for Chinese Simplified Pinyin/Wubi with IME China or Singapore and Options/Settings Double/Fuzzy/Name/U/V input, or for Chinese Traditional default/Bopomofo or ChangJie/Quick with IME Taiwan, Hong Kong, or Macao are you using? 

I am inexperienced in this area, so could that confuse *Cygwin* or `mintty` about your locale?

**Comment by qidizi** [comment]
only keep those files,and run `run-mintty.bat`,will get `codepage is 0`    

```text

Administrator@oa /cygdrive/d/cygwin-debug
$ pwd
/cygdrive/d/cygwin-debug

Administrator@oa /cygdrive/d/cygwin-debug
$ tree.com /f
卷 data 的文件夹 PATH 列表
卷序列号为 7482-6F80
D:.
│   run-mintty.bat
│
├───bin
│       cygwin-console-helper.exe
│       cygwin1.dll
│       mintty.exe
│
└───usr
    └───share
        └───terminfo
            └───78
                    xterm


$ stat usr/share/terminfo/78/xterm
  File: usr/share/terminfo/78/xterm
  Size: 3945            Blocks: 4          IO Block: 65536  regular file
Device: 29826,28544     Inode: 562949955375664  Links: 1
Access: (0750/-rwxr-x---)  Uid: (  544/Administrators)   Gid: (197121/    None)
Access: 2023-12-18 13:05:13.853638800 +0800
Modify: 2023-01-20 14:28:07.000000000 +0800
Change: 2023-12-18 13:18:08.767837800 +0800
 Birth: 2023-12-18 13:05:13.853638800 +0800


```

**Comment by qidizi** [comment]
zip those files ,copy to other pc test    

1.  other one pc is `windows server 2019 datacenter`,display    

 codepage===0     
   
  
2.  `windows server 2008 r2`,it `uname -a` is `CYGWIN_NT-6.1-7601 3.4.10-1.x86_64 2023-11-29 12:12 UTC x86_64 Cygwin`, display    

65001   

3.  `windows 10 pro`,version `22H2`,insider version `19045.3803`, display  

936

**Comment by BrianInglis** [comment]
Maybe try running `locale` to see what *Cygwin* thinks e.g.
```
$ for o in -s -u -i -f -n ''; do locale $o; done
en_US
en_GB
en_CA
en_CA
en_CA
LANG=en_CA.UTF-8
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_ALL=
```
I use my *own* definitions for `en_CA` on *POSIX* locale systems, and set up *Windows* language, locale, and regional settings as closely as possibly to those. 
[*Windows* 10 does not appear to support `%z` zone offsets or `%Z` zone abbreviations in date/time outputs.]

**Comment by qidizi** [comment]
in `windows server 2019 datacenter`     

```text
$ for o in -s -u -i -f -n ''; do locale $o; done
zh_CN
zh_CN
zh_CN
zh_CN
zh_CN
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```   


[cygwin-debug.zip](https://github.com/mintty/mintty/files/13699765/cygwin-debug.zip)   

this `zip` include    

```text 
$ tree.com /f
卷 data 的文件夹 PATH 列表
卷序列号为 7482-6F80
D:.
│   run-mintty.bat
│
├───bin
│       cygwin-console-helper.exe
│       cygwin1.dll
│       mintty.exe
│
└───usr
    └───share
        └───terminfo
            └───78
                    xterm
```

**Comment by k-takata** [comment]
I think that ConPTY on some versions of Windows had a bug, which wrongly returns 0 for `GetConsoleCP()`.

**Comment by qidizi** [comment]
> I think that ConPTY on some versions of Windows had a bug, which wrongly returns 0 for `GetConsoleCP()`.

give me a 'xxx-trace.exe` ,let it output something to same folder `trace.log`, i can test and post   .

**Comment by BrianInglis** [comment]
I wonder if the *datacenter* server is running *Windows* *Enterprise* and is customized to have no language or locale support other than default C/POSIX/ASCII? 

How about showing the *Windows* registry code pages on failing systems e.g. 
```
$ for cp in ACP MACCP OEMCP; do echo -n $cp$'\t'; regtool get -v /proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/$cp; done
ACP     65001
MACCP   65001
OEMCP   65001
```

WP notes that Chinese Simplified MS/W-936/GBK(W95) usage is down to ~5% in China and ~0.2% globally, presumably displaced by UTF8/ISO10646/CP65001/GB18030!

**Comment by qidizi** [comment]
> I wonder if the _datacenter_ server is running _Windows_ _Enterprise_ and is customized to have no language or locale support other than default C/POSIX/ASCII?
> 
> How about showing the _Windows_ registry code pages on failing systems e.g.
> 
> ```
> $ for cp in ACP MACCP OEMCP; do echo -n $cp$'\t'; regtool get -v /proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/$cp; done
> ACP     65001
> MACCP   65001
> OEMCP   65001
> ```
> 
> WP notes that Chinese Simplified MS/W-936/GBK(W95) usage is down to ~5% in China and ~0.2% globally, presumably displaced by UTF8/ISO10646/CP65001/GB18030!

```text

Administrator@oa ~
$ for o in -s -u -i -f -n ''; do locale $o; done
zh_CN
zh_CN
zh_CN
zh_CN
zh_CN
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

Administrator@oa ~
$ for cp in ACP MACCP OEMCP; do echo -n $cp$'\t'; regtool get -v /proc/registry/HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Control/Nls/CodePage/$cp; done
ACP     65001
MACCP   65001
OEMCP   65001

Administrator@oa ~
$ chcp.com
活动代码页: 0

Administrator@oa ~
$


```

**Comment by k-takata** [comment]
> I think that ConPTY on some versions of Windows had a bug, which wrongly returns 0 for `GetConsoleCP()`.

It seems that this bug existed around 2019. So, Windows server 2019 may have this bug.

**Comment by mintty** [comment]
When I run mintty from a minimal installation, from cmd, directly running chcp.com (like @qidizi did), I get the codepage configured via mintty option Locale. When I run /bin/dash first (or bash, adding some dlls), it gets overridden, e.g. by 65001 inspite of having configured GBK or CP1252. So it seems initialisation of the cygwin dll is also doing something here which is not suitable for all use cases.
GB18030 is unfortunately not supported by cygwin, so mintty applies a hack to fallback to GBK for locale handling, while supporting GB18030 itself.
