### ISSUE TITLE
`-` is shown as U+2010 in the manpage

### ISSUE THREAD

**Issue by k-takata** [mintty/mintty#1250]
Recently, `man mintty` shows `-` (U+002D, HYPHEN-MINUS) as `‐` (U+2010, HYPHEN).
So, searching for any options on the manpage (using the `/` command) doesn't work. (E.g. `/--WSL`)

E.g.:
https://github.com/mintty/mintty/blob/91bb8cad25f3856bc46f55d60142768a7cceac3f/docs/mintty.1#L36
`-` in this line should be escaped by `\` as follows:
```
implies a \fB\-\-WSL\fP\fI[=distro]\fP parameter.
```

**Comment by mintty** [comment]
I had noticed this before (the `man` toolchain seems to have changed a while ago), and now read https://lwn.net/Articles/947941/ - it's a mess.
Apparently many manpages have already been modified for a workaround, so mintty shall follow that.
