### ISSUE TITLE
mintty doesn't appear to support sixel graphics

### ISSUE THREAD

**Issue by ykhan21** [mintty/mintty#1252]
[mintty](https://mintty.github.io/) says that sixel graphics is supported.
In a PR [here](https://github.com/mintty/mintty/pull/571), img2sixel and [ImageMagick convert](https://github.com/mintty/mintty/pull/571#issuecomment-236380102) was used to display sixel graphics on mintty.  However, I can't seem to get sixel graphics to display on the mintty terminal provided by git bash (from Git for Windows).

ImageMagick convert (used [here](https://github.com/mintty/mintty/pull/571#issuecomment-236380102) no longer seems to work and neither does chafa (a modern terminal graphics program).

Both these commands return nothing:
`magick convert image.png -polaroid 10 -thumbnail 500x image.png sixel:-`
`chafa.exe -f sixel image.png`

Here is the image:
![image](https://github.com/mintty/mintty/assets/51864191/8aa487c1-813d-487b-a1f6-0bb20303a281)

Here is the text outputted by the ImageMagick command run above:
`magick convert image.png -polaroid 10 -thumbnail 500x image.png sixel:- > sixels-magick.txt`
[sixels-magick.txt](https://github.com/mintty/mintty/files/13806049/sixels-magick.txt)

Here is the text outputted by chafa command run above:
`chafa.exe -f sixel image.png > sixels-chafa.txt`
[sixels-chafa.txt](https://github.com/mintty/mintty/files/13806050/sixels-chafa.txt)

I've installed git for windows, chafa, and ImageMagick with the scoop package system.

**Comment by mintty** [comment]
Sixel output works in mintty, also in Git for Windows. Just retested and also used your magick example.
I don't know what chafa is, likely this and also your imagemagick version are a Windows build and do something weird. Please recheck with cygwin tools.

**Comment by BrianInglis** [comment]
Both your *sixel* files display fine on *Cygwin* `mintty` with `cat`. 
Check *GfW* `mintty` docs if *sixel* and/or *Tek* support are enabled/disabled.

**Comment by BrianInglis** [comment]
Your *Chafa* and *ImageMagick* packages probably need to be built with *Msys2* to run with *GfW*,  but *Scoop* probably grabs some *Windows* build. 
Try the *GH* hint to prefix *Windows* commands with `winpty`.

**Comment by ykhan21** [comment]
Thanks for the help.

@mintty, @BrianInglis It looks like scoop installs a windows build. 
I've downloaded and extracted the mingw build from [imagemagick](https://imagemagick.org/script/download.php) but the convert command in the bin folder doesn't output anything. Is this the build you are referring to?

@BrianInglis, I prefixed the original scoop-installed magick command with `winpty`, but this time text was output to the screen. Without `winpty` it was a blank line.

Also, where can I check in GfW supports sixel?

**Comment by mintty** [comment]
There is no way to disable sixel support in mintty, unless they would patch the sources.
I'm attaching a Sixel demo file for testing: 
[wizard.six.txt](https://github.com/mintty/mintty/files/13806347/wizard.six.txt)

**Comment by ykhan21** [comment]
How can I debug this further? BrianInglis mentions that the sixel text files I uploaded render fine on mintty, however, I can't get it work on my mintty from GfW.

**Comment by mintty** [comment]
DId you actually `cat` your two uploaded files into mintty?
Using your uploaded image, I replay
`magick convert sixel-1252.png -polaroid 10 -thumbnail 500x sixel-1252.png sixel:- > sixel-1252.six`
or just
`convert sixel-1252.png -polaroid 10 -thumbnail 500x sixel-1252.png sixel:- > sixel-1252.six`
(using the cygwin package ImageMagick) to get the attached file [sixel-1252.six.txt](https://github.com/mintty/mintty/files/13807520/sixel-1252.six.txt)

**Comment by ykhan21** [comment]
Yes, `cat` with your wizard file works, but any sixel file I generate does not.

**Comment by ykhan21** [comment]
Oh, so `cat`-ing the text file works, but only `cat`-ing:
![image](https://github.com/mintty/mintty/assets/51864191/37681f1a-398a-4e14-ac60-4f1ecf4e1de2)

**Comment by mintty** [comment]
Console output from a native Windows application first goes to the Windows console API, then through ConPTY layers before it arrives at the terminal. Whereever the incompatibility arises that obstructs this use case, your test case confirms it is not a mintty issue. I suggest to report it to the cygwin mailing list, maybe there is chance to expand cygwin ConPTY support to handle this case. It is more likely though, that the escape sequences needed for sixel  control are already discarded by the Windows console layer.

**Comment by ykhan21** [comment]
I see, thanks.
I understand that this is not the right place to ask this, but can you answer why exactly `cat` works? Does it not go through the ConPTY at all due to cygwin? I have seen https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs.

`cat`-ing a sixel text file does not work on Wezterm which _does_ support sixel graphics. The Wezterm maintainer said that this is due to ConPTY (see the end of the discussion [here](https://github.com/wez/wezterm/issues/1236), but it works in mintty.

**Comment by mintty** [comment]
ConPTY is not involved in direct output from a cygwin program (like cat) to the terminal.
In that other issue, the poster did not describe the test case well. My assumption is that native Windows ssh was in use which would force the output through Windows APIs.

**Comment by mintty** [comment]
Mintty sixel display is not affected by any windows terminal or powershell stuff.
About Windows-compiled binaries, see also my comment to the libsixel issue.
