### ISSUE TITLE
Clear selection on input setting no longer works in mintty 3.7.0

### ISSUE THREAD

**Issue by kdgts** [mintty/mintty#1253]
Repro steps:
1) Start mintty terminal using the following command:
C:\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -
assuming cygwin is installed to C:\cygwin.

2) Right click terminal title, select Options->Selection, check "Clear selection on input" checkbox.

3) Click apply and save

4) Select any text to clipboard, and paste it to the mintty terminal either using middle mouse button or using shift-insert

Result: inserted text is highlighted
Expected result: inserted text is NOT highlighted

**Comment by mintty** [comment]
I assume you paste into a shell command line. It's a recent feature of bash and has nothing to do with mintty. For a cross-test, run `cat` and paste into that.

**Comment by mintty** [comment]
See #1138 for background.

**Comment by kdgts** [comment]
Thank you, it is indeed not a mintty issue.
