### ISSUE TITLE
Ctrl-click on url doesn't open it when foreground process cwd is root directory (Regression in 3.7.0) 

### ISSUE THREAD

**Issue by jon-turney** [mintty/mintty#1254]
Under cygwin, I have a mintty terminal open, running ssh to a linux host, running a screen session, containing weechat.

Ctrl-clicking on a URL in the weechat output used to open it in my browser, but this seems to have stopped working with 3.7.0.

If I copy and paste the URL into another terminal, ctrl-clicking on it opens it, so this seems to be something about the remote session which prevents it from working now

Here's a mintty log of such a session.  Clicking on the URL in the last line of the IRC chat doesn't seem to work:
[mintty.log](https://github.com/mintty/mintty/files/13956291/mintty.log)

**Comment by jon-turney** [comment]
OK, sorry the log isn't much use, but I don't know what extra information to add to make it useful.

The problem affects all URL in my IRC sessions.  One other thing to note is that it gets underlinded as expected which I ctrl-hover over it, it's just that click does nothing.

I'll see if I can dig into it futher myself, during my copious spare time :)

**Comment by mintty** [comment]
OK, I didn't see you mentioned IRC before but I couldn't reproduce it anyway. Maybe the program adds some hidden characters (like combining characters) or an explicit hyperlink attribute (OSC 8).
Please make a screen log (e.g. `mintty -l .logfile.txt`) to extract the link, verify you can `cat` the log and reproduce the issue, then upload it.

**Comment by jon-turney** [comment]
I'm sorry. I poked at this a bit more, and discovered that it's nothing to do with a remote session! It's much simpler than that.  I just happen to run that session with a working directory of '/'.  

This seems to screw up somewhere inside the checking that happens inside `guardpath()`, since it decides that the URL with "//" prepended is a network path.  I don't immediately understand why this is being applied to a URL at all, so I think maybe there is a bug of some sort here.

So, reproduction on cygwin should just be:

```
$ cd /

$ echo https://cygwin.com
https://cygwin.com
```
and then try ctrl-clicking on the URL.

**Comment by mintty** [comment]
Thanks for clarifying the report. The issue was already fixed, referring to mintty/wsltty#346.

**Comment by mintty** [comment]
Released 3.7.1.
