### ISSUE TITLE
icons shown as tofu in mintty

### ISSUE THREAD

**Issue by goyalyashpal** [mintty/mintty#1260]
* These command `echo` character range from `\xee\x97\xba` to `\xee\x9a\xb2` etc.
* i stumbled upon these as: `eza --icons` (the last command below shows initial inspection with it)
* this issue seems to be related to the following, but those are either about italics, or clipping etc; in my case, no icon is show at all 
https://github.com/mintty/mintty/issues/638#issuecomment-284706464
https://github.com/mintty/mintty/issues/1104
https://github.com/mintty/mintty/issues/892

```bash
echo -e \\xee\\0227\\027{2..7}
echo -e \\xee\\023{0..2}\\02{0..7}{0..7} | cut -b 1-$(( 180*4 ))
echo -e \\xef\\020{0..7}\\02{0..7}{0..7}
echo -e \\xef\\02{1,2}{0..5}\\02{0..6}{0..7}

# eza -1d -s=none --icons=always L*s/ *.{txt,tdl,yaml,csv,pdf,odp,xlsx} | cut -c 1-3 | sd \\n '  ' | od -ct x1
```

### environment

```console
$ mintty --version | head -n1
mintty 3.7.1 (x86_64-pc-msys)

$ uname -rv
3.4.10.x86_64 2024-03-24 15:09 UTC

$ cat ~/.minttyrc
FontHeight=12
ThemeFile=dracula
CtrlShiftShortcuts=yes
Font=JetBrains Mono

```

### attachment screenshots

![image](https://github.com/mintty/mintty/assets/19423063/277e83b1-f8d2-4bc9-b18d-13bd2353e19a)

![image](https://github.com/mintty/mintty/assets/19423063/9f17346c-36ad-4d94-aeb4-e746bda3ccef)

**Comment by BrianInglis** [comment]
Mayber show us all the output from `mintty --version` and `uname -srvmo` so we know what you are actually running and on what, and label the images with something meaningful to tell us what system, terminal, and shell each was run from, preferably with commands showing versions, what fonts are installed in each environment, fallback fonts available, what is eza, and what do icons have to do with it?

**Comment by mintty** [comment]
Your echo commands generate a bunch of unassigned Unicode characters which get visible once you use a font that has them. I do see useful output here in mintty.

**Comment by goyalyashpal** [comment]
> once you use a font that has them. I do see useful output here in mintty.

which font r u using?

**Comment by mintty** [comment]
For example FiraCode NF, DejaVuSansMono NF (the Nerd Font variations).

**Comment by goyalyashpal** [comment]
ohkay. thanks a lot.



<details><summary>Some documentation resources for myself:</summary>
<p>

> Alternative fonts: simultaneous display of multiple fonts.
> Secondary fonts: script-specific alternative font usage.
> \- https://mintty.github.io

> Mintty can select alternative fonts for specific Unicode script ranges. ... Script names are as specified in the Unicode file Scripts.txt. 
> * special name `PictoSymbols` [for] ranges of pictographic symbols, including arrows, mathematical and technical symbols, shapes, dingbats, emoticons etc
> * special name `Private` covers the Private Use ranges, which are often used for additional icon symbols (e.g. by "Nerd Fonts" or "Powerline" fonts).
> 
> \- _https://github.com/mintty/mintty/wiki/Tips#alternative-fonts_


> WezTerm bundles [JetBrains Mono](https://www.jetbrains.com/lp/mono/), [Nerd Font Symbols](https://nerdfonts.com/) and [Noto Color Emoji](https://www.google.com/get/noto/help/emoji/) fonts and uses those for the default font configuration.
>
> **Fallback[¶](https://wezfurlong.org/wezterm/config/fonts.html#fallback)**
> WezTerm allows specifying an ordered list of fonts; when resolving text into glyphs the first font in the list is consulted, and if the glyph isn't present in that font, WezTerm proceeds to the next font in the fallback list.
>
> The default fallback includes the popular [Nerd Font Symbols](https://nerdfonts.com/) font, which means that you don't need to use specially patched fonts to use the powerline or Nerd Fonts symbol glyphs.
>
> \- _https://wezfurlong.org/wezterm/config/fonts.html_

</p>
</details> 




<details><summary>Some actionable resources for myself:</summary>
<p>

1. `nerd-fonts` scoop bucket at [matthewjberger/scoop-nerd-fonts](https://scoop.sh/#/apps?q=%22https%3A%2F%2Fgithub.com%2Fmatthewjberger%2Fscoop-nerd-fonts%22)

2. Look at the "reserved name" at [nf/font-downloads](https://www.nerdfonts.com/font-downloads)
<sub>Found by matching `Cascadia-Code` example on [scoop.sh](https://scoop.sh)</sub>

```console
$ wezterm ls-fonts | bat -pPl lua
Primary font:
wezterm.font_with_fallback({
  -- "$LOCALAPPDATA"\MICROSOFT\WINDOWS\FONTS\JETBRAINSMONO-REGULAR.TTF, DirectWrite
...
  -- <built-in>, BuiltIn
  "Symbols Nerd Font Mono",
})
```

</p>
</details> 



I am thinking of choosing among:
* FiraCode NF, DejaVuSansMono NF, Symbols Nerd Font Mono, `Cascadia Code` (exampled somewhere)
* 0xProto NF, Blex Mono NF `IBM Plex Mono` , CascadiaMono NF `Cascadia Mono`, ComicShannsMono NF

actions:

```console
$ scoop bucket add nerd-fonts
Checking repo... OK
The nerd-fonts bucket was added successfully.

$ # blex not found
$ echo {cascadia,comic,0xproto,firacode,dejavu,symbols} | xargs -tn1 scoop-search
...

$ scoop info nerdfontssymbolsonly | yq .Description
This font contains all Nerd Fonts symbols and is intended to be used as fallback or together with fo
ntconfig.

$ scoop home nerdfontssymbolsonly
$ scoop install nerdfontssymbolsonly

$ # Not idempotent:
$ echo -e "FontChoice=Private:3\nFont3=Symbols Nerd Font" >> ~/.minttyrc

$ # Restart mintty or i guess open a new mintty instance too?
$ echo \\xee\\x97\\xba \\xee\\x9a\\xb2
```

it is showing the last series _alongwith_ a tofu behind them as shown in image below, but it is bearable for now.

![image](https://github.com/mintty/mintty/assets/19423063/a45f5229-93f7-40e1-b38f-f50caef2deaf)

**Comment by goyalyashpal** [comment]
it is showing the last series _alongwith_ a tofu behind them as shown in image below, but it is bearable for now.

![image](https://github.com/mintty/mintty/assets/19423063/a45f5229-93f7-40e1-b38f-f50caef2deaf)
