### ISSUE TITLE
is it possible to remap C-1 to M-1 with KeyFunctions= ?

### ISSUE THREAD

**Issue by SequentialDesign** [mintty/mintty#1262]
basically what the title is : is it possible to remap C-1 to M-1 with KeyFunctions= ?

I want Control+1 to send Meta+1, but I don't know if it's possible in mintty using the KeyFunctions= feature

**Comment by mintty** [comment]
No, neither is Control+1 among the key combinations that would be remapped, nor can you map to another key combination (can be a string or a built-in function).
Note that Control+1 is one of the combinations that can be remapped to an escape sequence dynamically, using xterm modifyOtherKeys mode, so static remapping would interfere with that.

**Comment by SequentialDesign** [comment]
thanks 
I needed to put `FormatOtherKeys=1` in my .minttyrc.  then I got esc codes

**Comment by mintty** [comment]
Actually, the controls sent for Control+digit by default are not related to setting FormatOtherKeys.
Dynamic modifyOtherKeys mode is a switchable transformation of most keys with modifiers to escape sequences of two different formats, selectable by that option, as implemented by xterm.
