### ISSUE TITLE
Windows 11 taskbar icon twitching

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#1263]
So some genius at Microsoft thought it would be a great idea to make the Windows 11 taskbar twitch every time a command starts or ends in my zsh configuration (because that changes the window title and thereby often the taskbar button width).

I tried to counter that by simply adding lots of spaces and a dot at the end of the title, enough to make the button width static and the dot to be hidden. But then the mintty tab title is abbreviated near the beginning, i.e. something like "z…                                .".

Two possible remedies come to mind. Could you please add one of those? Or is there a better solution?

1. Add an option to make the tab title the window title truncated at the end.
2. Support new control sequences to set the tab title independently of the window title.

(1 sounds easy and is sufficient IMHO.) Thanks!

**Comment by mintty** [comment]
2 would break existing workflows, 1 would break expectations about the title.
I'd rather add an option (switchable in the extended context menu) so that the control sequence to set the window title only changes the tab title if there is a tabbar. And maybe a control sequence to sync or clear the window title.

**Comment by mkq** [comment]
Thanks. Can you please elaborate, as I understand neither of your points.

> 1 would break expectations about the title

I don't see how anything would break if you added an option and kept the current behavior the default.

> 2 would break existing workflows

You mean it would break users which only use the current control sequences and would now get empty tab title? In that case, couldn't the tab title equal the window title until the new ctrl seq occurs for the first time?
Or: The existing ctrl seq keeps changing both titles, and the new one just the tab title. So when used in the correct order, that would effectively give me "independently".

> I'd rather add an option (switchable in the extended context menu) so that the control sequence to set the window title only changes the tab title if there is a tabbar.

So a non-settable window title if there is a tabbar? That's not a solution to my problem, as I still want a meaningful window title, not just any fixed length one.

> And maybe a control sequence to sync or clear the window title.

As soon as I'd sync, would I be back at my initial abbreviation problem then?

**Comment by mintty** [comment]
ad 1: The control sequence OSC 2 is described to set the title to the given string, not part of it. People may wish to keep that but still get the remedy to be agreed.
ad 2: Scripts like shell profiles use OSC 2 and would all need to be changed to support the remedy. It should work automatically, keeping existing profiles portable. I don't want a solution that only works for power users.

A sequence that sets the actual window title (e.g. the sync sequence) could be sent less frequently, for example only when the working directory is changed in the shell. Or, with the "tab title only" mode enabled, a new sequence could be used to set the window title.

**Comment by mkq** [comment]
ad 1: In my suggestion 1, I don't mean any change to window title setting at all. Only tab title (which is not covered by standard OSC 2, I assume, and is already being abbreviated) would be abbreviated in a different way. (Plus keeping the old behavior as default should mean that nothing breaks. And even if the new abbreviation mode is used, the "break" is purely visual, since there is no way to programmatically read the tab title anyway.)

ad 2: Yeah, extra effort to use the new feature. That's why I prefer solution 1.

> A sequence that sets the actual window title (e.g. the sync sequence) could be sent less frequently, for example only when the working directory is changed in the shell.

My window title changes twice per entered command, and I want to keep it that way. (That's why the "re-layouting" of the Windows 11 taskbar is so annoying.)

> Or, with the "tab title only" mode enabled, a new sequence could be used to set the window title.

IIUC, for everyone who wants both titles, this would mean as much extra effort as my suggestion 2 (keep OSC 2 unchanged [window title and middle truncated tab title], add new CtrlSeq for tab title), just in a more confusing way.

How about a solution "4"?

- Add a new "post-processing" window title format string option which can contain a placeholder (say "%t") for the OSC-set window title and would default to just that. I'd set it to "%t _many spaces_ .", others might set it to "mintty - %t". When someone runs a command which sets a title he doesn't like, he'd use a string without "%t".
- All control sequences only set or copy the "%t" part.

**Comment by mintty** [comment]
I've meanwhile tried to reproduce the original issue on Windows 11 but I don't see any effect of title changing to the taskbar.
Please describe what you mean by "taskbar twitch" and how to reproduce an effect.

**Comment by mkq** [comment]
I'm currently not at my Windows 11 work computer, but I'll try:

1. Taskbar settings: enable window titles
2. Have some more windows open besides mintty
3. Ensure that mintty is not the rightmost taskbar button; drag it to the left if necessary
4. Call a command like `termtitle s; sleep .4; termtitle looooooooooooooooooong; sleep .4; termtitle s` assuming a script termtitle to set the title. (Simulates real world use case: shell prints a short title like "zsh [~]" when prompting, a prefix plus the command like "zsh> find "$APPDATA/" -newermt ..." (whatever - some long command) when starting a command.)

=> The mintty taskbar button gets temporarily wider, causing the buttons to the right to move right. When that happens often and quickly, it almost feels like the taskbar is flickering.

**Comment by j4james** [comment]
@mintty Assuming it's possible to set the taskbar icon label separately from the window title, have you considered using `OSC 1` for this? The Windows taskbar icons aren't _exactly_ equivalent to iconified applications in Unix, but they serve a similar purpose, and they both have a need for a shorter label, which is essentially what the `OSC 1` sequence was intended to provide.

**Comment by mintty** [comment]
> set the taskbar icon label separately from the window title

As far as I know this is not possible. (Otherwise I would have implemented distinct OSC 0/1/2)
If anyone finds how to achieve that, please inform us.

**Comment by mintty** [comment]
> Taskbar settings: enable window titles

I do not see this option in Windows 11. How are taskbar icon titles enabled?

**Comment by mkq** [comment]
Personalization / Taskbar / Taskbar behaviors / Combine taskbar buttons and hide labels must be set to "When taskbar is full" or "Never".

**Comment by mintty** [comment]
I don't have that option in my taskbar behavior menu. Maybe with 23H2 which is just downloading?

**Comment by mintty** [comment]
OK, I could now enable taskbar icon labels. The label is changed along with the window title as expected, clipped to some maximal length. I still do not see what you mean by "twitching". Everything looks fine for me.

**Comment by mintty** [comment]
OK, I've now seen the difference to Windows 10. I had misunderstood the issue to be related to long labels but it's about short labels of different length (as long labels are clipped anyway), right?
So you do not want the width of taskbar icons to get changed so often, I assume.
A simple workaround would be to pad the label with blank space (using a non-breaking space U+A0) but then the width would always be the maximum which you might not like either.

I'm pondering to offer the following solution, fitting into existing definitions of OSC sequences (but slightly tweaking them which might be considered unsuitable by some):
OSC 0 "Change Icon Name and Window Title to Pt." would set both window and tab title.
OSC 1 "Change Icon Name to Pt." would set the tab title only.
OSC 2 "Change Window Title to Pt." would set the window title only.
This would however break as a solution if Windows ever introduces an API to set the taskbar icon label distinctly from the window title...

**Comment by mintty** [comment]
The proposed design would be the reverse of what @j4james suggested, so apparently it's a matter of preference (and could be tweaked by an option). Still leaving open how to extend handling if one day we might have 3 distinct labels (window, tab, icon).

**Comment by mintty** [comment]
It was further confusing the issue to relate it to the tab title as it arises alike without tabbar, at least as I now understand it.

**Comment by mintty** [comment]
I've uploaded a workaround for the taskbar icon twitching as discussed. The window title (which is also used as the taskbar icon label) is padded with 50 non-break spaces. Note that 39 is likely not enough as I also made the taskbar font configurable and you could use a thinner font.
Please build mintty for testing.

About the original request to separate window and tab title, this would need to add title management to mintty which is currently not available (the title contents is simply maintained as the Windows title and retrieved from it when needed).

**Comment by mintty** [comment]
On Windows 10, the same procedure has a bad effect, so applying it only on Windows 11.

**Comment by mkq** [comment]
Thank you very much!

I have built master. But Windows Security doesn't let me execute it on my work computer, which is currently my only computer with Windows 11. I will try again in the next days. Sometimes, Windows Security changes its mind.

**Comment by mkq** [comment]
I could now run the self-built mintty. When I run my test loop from https://github.com/mintty/mintty/issues/1263#issuecomment-2110462863, with sufficiently large w, it looks good. But small w values still yield slim taskbar buttons.

I.e. I still need to pad with U+00A0 myself, which is not a problem for me, but your comment sounds like it should not be necessary on the user's side anymore.

**Comment by mintty** [comment]
I see no such effect from your script, provided I run it from an updated mintty instance.

**Comment by mkq** [comment]
Hmm, strange.

The about dialog in my self-built mintty.exe shows "mintty 3.7.1 (x86_64-pc-cygwin) [Windows 22631]" just like my installed version. Is that expected?

Can Windows Security not only block, but also silently replace programs??

**Comment by mintty** [comment]
The version stays the same until the next release. (Something I already wanted to enhance for a while...)
If you start from ../bin, the self-built version should be running.

**Comment by mkq** [comment]
I tried again with the self-build exe, and checked in Task Manager that that one is really running. I still need to pad the title myself:

Unpadded ⇒ slim button:
<img width="390" alt="image" src="https://github.com/mintty/mintty/assets/1584258/56f1e859-1a8d-4850-86df-c89b440d91ee">

Padded in my `printf '\033]0;x\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\007'; sleep 5` ⇒ wide button:
<img width="398" alt="image" src="https://github.com/mintty/mintty/assets/1584258/b50c0b76-97a9-4334-8407-689357a95eb2">

**Comment by mintty** [comment]
Excuse the question, your self-build was based on which sources? Did you get a fresh git pull?

**Comment by mintty** [comment]
I guess a found an error in the patch, hold on. I wonder though, how I could test it successfully on Windows 11...

**Comment by mkq** [comment]
OK, I'll answer anyway, in case it helps: 
Yes, I think it must have been commit d8594d27 which I built. (When I re-build that commit now, I get a mintty.exe with size 1734637, but Windows Security doesn't even let me `diff` it with the backup mintty.exe with which I tested yesterday. But the sizes match.)

**Comment by mintty** [comment]
The fix should now be fixed. Sorry for the confusion.

**Comment by mkq** [comment]
No problem. Thank you very much!

I've built commit 18d63f96. Let's see when Windows Security is ready to allow me run it…

**Comment by mkq** [comment]
I can now confirm that mintty's padding works for me, e.g. unpadded `printf '\033]0;i\007'` gives me a full width taskbar button.

Thanks a lot!

**Comment by mintty** [comment]
Released 3.7.2.
