### ISSUE TITLE
cant override cursor color when theme set them

### ISSUE THREAD

**Issue by nshopik** [mintty/mintty#1267]
It seems no possible to change cursor/background/foreground color if theme already have them set. But you can change colors if theme doesn't set them. 

Solution seems simple - set theme save and set theme to none save again, but for some reason after restarting some colors reset to default minitty theme even though .minttyrc still have previous theme color scheme.

Is this intended?

**Comment by mintty** [comment]
It can still be overridden dynamically, by an OSC 12 escape sequence.
I assume you wish to override theme cursor colour via the Options dialog.
No, this is not really intended. It is a random matter of implementation sequence and was not raised as a problem so far.
I'll check whether it can be easily changed without creating trouble.

**Comment by mintty** [comment]
I experimented with some tweaks to address the issue but it didn't work out.
Then, thinking again, some themes explicitly define for example a background colour, others don't. If they don't, manual changes persist as desired.
And if they do, I think it's intended by the them to override any specific background/foreground/cursor colour setting, so be it.
If you want a theme to not override your manual changes, you can easily create a copy with those settings removed.

**Comment by mintty** [comment]
I added a note on the wiki Tips page about this.
