### ISSUE TITLE
warning on inserting multiple lines from buffer

### ISSUE THREAD

**Issue by nshopik** [mintty/mintty#1268]
Would be nice to have option when enabled mintty warn me before inserting multiple lines from buffer. 

I kinda like it in windows terminal, but they still have way to go, so I prefer keep using mintty.

**Comment by mintty** [comment]
This is typically a feature of the shell nowadays, to be enabled there.

**Comment by nshopik** [comment]
Well maybe, but I don't have control on many shells where I'm user, for example network devices or any custom shells really on closed-source devices.

**Comment by mintty** [comment]
Another option to filter out newlines is setting `FilterPasteControls=NL,CR`.

**Comment by mintty** [comment]
I've uploaded an optional feature (``ConfirmMultiLinePasting=yes`) to prompt for confirmation. Please try.

**Comment by nshopik** [comment]
Hey thanks! I'm on cygwin so it only become available to me when you tag new release. I'd rather not build from source (at least for now)

**Comment by mintty** [comment]
Released 3.7.2.

**Comment by nshopik** [comment]
Tested with 3.7.2, looks good. Thanks again.

For some reason cygwin installed version doesn't report version number, only commit hash, but during upgrade it clearly said 3.7.2 even though 3.7.1 reported correctly. Could be cygwin build system mess up I guess.
```
---------------------------
mintty
---------------------------
mintty  5046cfa6 (x86_64-pc-cygwin) [Windows 22631]
© 2024 Thomas Wolff, Andy Koppe
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.

Please report bugs or request enhancements through the issue tracker on the mintty project page located at
http://mintty.github.io/.
See also the Wiki there for further hints, thanks and credits.
---------------------------
OK   
---------------------------
```

**Comment by mintty** [comment]
> build system mess up

Yes it is, and I will make another release soon.
