### ISSUE TITLE
vim fails to recognize Alt-key mappings

### ISSUE THREAD

**Issue by Yunus4832** [mintty/mintty#1272]
I've encountered an issue while using Vim within MSYS2, and after some experimentation, I suspect that the problem might be related to mintty. Here are the steps to reproduce the issue:

1. Launch a terminal using mintty, and modify the `TERM` environment variable in the terminal to either `xterm-256color` or `xterm`:
```bash
export TERM=xterm-256color
```
2. Prepare a minimal Vim configuration file to reproduce the problem:
```vimrc
" ~/.minvimrc
set nocompatible
" Alternatively, you can try: set <M-a>=a
exec "set <M-a>=\ea"
map <M-a> iabc<esc>
```
3. Start Vim with the specified configuration file:
```bash
vim -u ~/.minvimrc
```
At this point, pressing the test key mapping `<M-a>` does not insert `abc` into the document as expected. However, if we change the `TERM` environment variable from `xterm-256color` to `mintty` in step 1, the key mapping behaves as intended.

Initially, I suspected that the `TERM` environment variable might be influencing Vim's behavior, so I also tested on Konsole (Linux) and the Cmd (Windows). The issue appears exclusively in terminals opened by mintty, leading me to speculate that there might be something about the terminal emulator mintty itself—due to some unknown reasons—that is causing this problem.

**Comment by k-takata** [comment]
If $TERM is xterm (or some other values), Vim enables the modifyOtherKeys feature. See `:help modifyOtherKeys` in Vim for details.

**Comment by mintty** [comment]
I do not reproduce this issue, with either xterm or xterm-256color. I see however that in both cases modifyOtherKeys mode is activated by vim.
If vim uses modifyOtherKeys mode and then does not recognize the sequences thus produced while interpreting its macros, it's a vim bug.

**Comment by Yunus4832** [comment]
Thank you, indeed the root of the issue was because Vim had modifyOtherKeys enabled. I verified this by testing in both cmd and konsole, where even with `$TERM` set to `xterm`, Vim did not enable modifyOtherKeys. However, in mintty, it was recognized and modifyOtherKeys was indeed turned on. Following the guidance from` :help modifyOtherKeys`, the problem can be resolved by adding these two lines to Vim's configuration file to disable modifyOtherKeys mode:

```Vimrc
let &t_TI = ""
let &t_TE = ""
```

**Comment by mintty** [comment]
Well, modifyOtherKeys mode has its benefits. I suggest you submit an issue to them:
Whatever prevents macro recognition while modifyOtherKeys mode is active, should be fixed.

**Comment by Yunus4832** [comment]
Alright, I'm not certain if this qualifies as a bug, given the clear documentation within Vim. The documentation states that enabling modifyOtherKeys can lead to certain issues and provides instructions on how to disable it.

> For xterm, modifyOtherKeys is enabled by default in the built-in terminfo entry. If this isn't being utilized, you can manually enable modifyOtherKeys by adding these lines to your .vimrc:
>
> ``` vimrc
> let &t_TI = "\<Esc>[>4;2m"
> let &t_TE = "\<Esc>[>4;m"
> ```
> This sets modifyOtherKeys to level 2. Note that level 1 of modifyOtherKeys does not function properly. Some terminals do not support level 2 and may send keycodes that Vim cannot accurately interpret.
>
>Should modifyOtherKeys mode cause any problems, you can disable it as follows:
>
> ```vimrc
> let &t_TI = ""
> let &t_TE = ""
> ```
>These changes do not take effect immediately. To apply them without restarting Vim, execute a shell command, for example: !ls Alternatively, include these lines in your vimrc for the changes to persist.

So, this might be a known issue. I'll first verify if someone has already submitted a report about it.
