### ISSUE TITLE
Problems building MinTTY v3.7.2

### ISSUE THREAD

**Issue by dscho** [mintty/mintty#1276]
Isn't the new `appinfo.o` target missing `stamp` as a prerequisite in the `Makefile`?

I suspect that it is because of [this failure](https://github.com/git-for-windows/MSYS2-packages/actions/runs/9693770325/job/26749961420?pr=172#step:5:95) (IIRC this workflow uses parallel `make`, that may be the reason why this fails without a clear order between the `stamp` and the `appinfo.o` target).

**Comment by dscho** [comment]
Sorry, just noticed that this is a duplicate of https://github.com/mintty/mintty/issues/1275.

**Comment by mintty** [comment]
Yeah, and also the version info (About, `-V`) is broken as discussed there.
If you want me to make another release for that reason, please tell me.
If MSYS2 build still applies patches (as it used to), the version info would still be amended with a git commit tag...

**Comment by dscho** [comment]
> If you want me to make another release for that reason, please tell me.

Yes, please.

> Yeah, and also the version info (About, `-V`) is broken as discussed there. If you want me to make another release for that reason, please tell me. If MSYS2 build still applies patches (as it used to), the version info would still be amended with a git commit tag...

Well, yes, [patches are applied](https://github.com/git-for-windows/MSYS2-packages/blob/53e4e3933ae0d6b4b3dc09b2de6bf2687d677ec2/mintty/PKGBUILD#L29-L34), but I do not necessarily see any games being played with the commit.

**Comment by mintty** [comment]
> Well, yes, patches are applied, but I do not necessarily see any games being played with the commit.

The new version stamp mechanism detects if the source have been modified since the last tagged commit or commit, and adds info in that case. Purpose is to identify builds better for debugging cases. So after a patch, the plain version would not appear anymore.
I can try to provide a workaround for that (or withdraw the whole stamping altogether).
About the second patch (working directory), there have been improvements in mintty since the patch and I assume it's no longer necessary and could be dropped. Unsure about the launcher thing. Is it a good idea to patch a launcher into existing sources?

**Comment by dscho** [comment]
To be precise: these patches originate from MSYS2, and I lack the time to do anything specific in Git for Windows. So those patches are here to stay, for the time being, until a volunteer finds the time and inclination to work on that end.

**Comment by Biswa96** [comment]
The patches in git-for-windows differ from msys2 ones https://github.com/msys2/MSYS2-packages/tree/master/mintty

**Comment by mintty** [comment]
Hi Biswa. I suggest to drop the size patch for MSYS2. The new version stamp mechanism (fixed for 3.7.3) would add a commit tag to the version info if sources are patched.
If you really want to configure mintty to wider size by default, a good place to deploy this would be `/etc/minttyrc`.

**Comment by mintty** [comment]
Released 3.7.3.
