### ISSUE TITLE
How to hide the title bar when window is maximized?

### ISSUE THREAD

**Issue by netjune** [mintty/mintty#1280]
Does it support this?

**Comment by mintty** [comment]
Yes, two options:
Setting `Border`, `-B` from the command line, with values `frame` or `void`, which can be combined with setting `-w max`.
Or true full-screen mode -w full. Interactively toggle with Alt+Enter, Alt+F11 or from the menu.

**Comment by netjune** [comment]
It works. 
Thank you very much.

**Comment by netjune** [comment]
> Yes, two options: Setting `Border`, `-B` from the command line, with values `frame` or `void`, which can be combined with setting `-w max`. Or true full-screen mode `-w full`. Interactively toggle with Alt+Enter, Alt+F11 or from the menu.

I tried `-B frame`. The window has no title bar as expected. But the task bar also disappears after I maximize the window using autohotkey script. 
How to keep the task bar in this situation?

**Comment by netjune** [comment]
I use authotkey script to manager all the windows. So I dont use `-w xx` option and hot keys(Alt-Enter or Alt-F11).

**Comment by mintty** [comment]
The latter is a duplicate of #1114.

**Comment by netjune** [comment]
> The latter is a duplicate of #1114.

I looked at it. It seems that it is hard to fix?

I try `-B void -w max` now. I see that the emacs run in it doesn't occupy the whole mintty window. How to let emacs to adjust its size?
I googled and found that there is a signal `SIGWINCH`. I guess that emacs will adjust its size when it receives this signal?

**Comment by mintty** [comment]
Yes, screen-oriented programs adjust themselves on SIGWINCH. But after starting with `-w max` the initial size setting should fit. Otherwise check `stty size` and `type emacs` for diagnostics.

**Comment by netjune** [comment]
> Yes, screen-oriented programs adjust themselves on SIGWINCH. But after starting with `-w max` the initial size setting should fit. Otherwise check `stty size` and `type emacs` for diagnostics.

There is no shell here. I cant run the diagnostics tools. The emacs is started using the following command:
`mintty.exe -b void -w max ssh.exe -tt 192.168.1.10 /bin/emacs`

If I remove `-w max` in the command, the size is OK.

**Comment by mintty** [comment]
Oh, there's also ssh involved...
So run `mintty -B void -w max` with a shell instead of ssh, then `type ssh` and `stty size`, then ssh manually to your remote system, running a shell instead of emacs, then `uname`, `stty size` and `type emacs`. Any Windows tool in the chain?

**Comment by netjune** [comment]
It is ok with a shell. And it is also ok with emacs in WSL. It is only not ok with emacs via ssh.

**Comment by mintty** [comment]
I guess I can only close the issue if you do not answer my questions.

**Comment by netjune** [comment]
It is ok with a remote shell(It adjusts itself well). The remote is a debian 12 Linux server.

I dont understand: what is windows tools in the chain? I'm not familiar with windows tools. I just use the built-in ssh.exe in Windows 10 to connect to the Linux server.

**Comment by netjune** [comment]
It is ok with a remote shell(It adjusts itself well). The remote is a debian 12 Linux server.

```
$ uname -a
Linux debian-think 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
$ stty size
40 120
$ type emacs
emacs is /home/jun/bin/emacs
```
Then I run `emacs -Q` in the remote shell. The emacs doesn't occupy the whole window like the shell.

**Comment by mintty** [comment]
I was thinking you might be using a Windows ssh to connect to a remote machine (thus asking for `type ssh`, still not answered) but stty size saying 40 120 is against this.
On a Linux server, emacs should be respecting the stty size, and it seems to do that. Counting the screen lines in your video, there are more than 40, and emacs just uses the 40 which is correct behaviour.
Now we should find out why your Linux pty driver thinks there are only 40 lines. Is it different without the mintty parameters -w max or -B void?

**Comment by mintty** [comment]
Wondering whether it's related to #1071 but that issue got fixed.

**Comment by mintty** [comment]
Maybe there's an explicit stty setting in your Linux server startup files? (like .bashrc, .profile, ...) Please check.
I've tried with local ssh into WSL with no such effect. Can test with Linux servers in a few days.

**Comment by BrianInglis** [comment]
> I was thinking you might be using a Windows ssh to connect to a remote machine (thus asking for `type ssh`, still not answered) but stty size saying 40 120 is against this. 

["built-in ssh.exe in Windows 10"](https://github.com/mintty/mintty/issues/1280#issuecomment-2286216986)

**Comment by netjune** [comment]
> Wondering whether it's related to #1071 but that issue got fixed.

I see that the mintty I used is too old(3.4.3). After I upgrade it to the latest version, everything is ok now. Sorry for the old duplicate issue.
Thanks.
