### ISSUE TITLE
Copying a tab character with option CopyTab=true copies spaces and a tab

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#1281]
When option CopyTab is enabled, copying a tab character copies seven spaces plus a tab character to the clipboard. 

**Steps to reproduce**

1. Start a mintty with no config except CopyTab=true, e.g. `HOME="$(mktemp -d)" mintty -o CopyTab=true -e bash&`
2. In that mintty, call `printf 'a\n\tb\n'` and copy its output via mouse selection.
3. Look at clipboard, e.g. `od -a </dev/clipboard`

**Actual output**
`… a  cr  nl  sp  sp  sp  sp  sp  sp  sp  ht   b  cr  nl`

**Expected output**
`…  a  nl  ht   b  nl` (not sure about the carriage returns, but no tabs please)

After reading in #1037 that CopyTab was initiatially only enabled in combination with option DispTab, I guess those are the spaces for display of the DispTab feature. But I think, with CopyTab=true, they should not be copied regardless of DispTab, but especially not with DispTab disabled.

**Comment by mintty** [comment]
Released 3.7.5.
