### ISSUE TITLE
Support reordering tabs in the tabbar

### ISSUE THREAD

**Issue by cebaa** [mintty/mintty#1283]
I frequently have a bunch of tabs open. I tend to like having certain tabs in certain locations. E.g. the first three tabs are for tailing the three logs I'm most frequenly using. The rest may be ephemeral. Sometimes I either forget to start them in order or Ctrl+D out of one of them by mistake. Right now I resort to either closing the tabs or stopping and starting the require programs again in order. Reordering (either by dragging with the mouse or using a keyboard shortcut) would allow me to easily fix the mistake.

**Comment by mintty** [comment]
Released 3.7.5.
User-definable functions tab-left, tab-right can be attached to preferred function keys by setting KeyFunctions. Interactive drag-and-drop reordering remains an open task for now.

**Comment by mintty** [comment]
Drag-and-drop tab reordering is now also available, for the next release.

**Comment by mintty** [comment]
Released 3.7.6.
