### ISSUE TITLE
Bright flash in dark mode when opening new tabs

### ISSUE THREAD

**Issue by cebaa** [mintty/mintty#1284]
I'm using a dark mode theme. Whenever I open a new tab, it starts with what looks like full white. It switches to dark in what seems is a few 100ms or so. It's pretty tough on the eyes when this happens - even with eyelids closed :)

Not sure if there's a way to fix or work around the issue somehow.

**Comment by mintty** [comment]
I've tried to postpone ShowWindow() to the latest possible time during initialization.
It does prevent the white flickering but imposes a noticeable "hide flickering" instead, i.e. the current window disappears quite a moment before the new one appears. Maybe that's better.

**Comment by mintty** [comment]
I've uploaded a tweak to the repository. Testing appreciated.

**Comment by cebaa** [comment]
Thanks for a quick turnaround!

I still see the flashes, but not always, and when I see them they look to be much quicker, so this is an improvement from my standpoint. Interesting, on my end I don't see "hide flickering" at all.

As an alternative, is it perhaps possible to fill the new tab with background color before showing it?

**Comment by mintty** [comment]
> fill the new tab with background color before showing it

That's actually done already. Try `mintty --bg red --tabbar`.

**Comment by cebaa** [comment]
I already had `BackgroundColor` set via the theme to something dark (which seems to override the command line option - only removing the theme from the config makes it honor `--bg red`), but I still see a brief white flash (which I've read somewhere is a Windows default) before it's being painted. Perhaps the window is being shown before it's being painted. If that's correct, then painting before the show should fix it regardless of when the show happens, removing the need for show delays.

**Comment by mintty** [comment]
There is a function GdiFlush() with unclear purpose; you could try to add an invocation behind the call of win_paint() near the end of winmain.c; I doubt it makes a change though.

**Comment by mintty** [comment]
Released 3.7.5.

**Comment by mintty** [comment]
> How do you open a new tab 

Alt+F2 or from the system menu (click on upper-left corner in title bar).
