### ISSUE TITLE
DEC graphics (e.g. box characters) not working as expected if repeated

### ISSUE THREAD

**Issue by Wodan58** [mintty/mintty#1288]
The DEC escape sequences that allow drawing of a box have this result in ASCII art for a 12x3 box:
+-         +
|             |
+-         +
And this is expected:
+----------+
|                 |
+----------+
That is: the horizontals specified with `q` are printed, but only the first one is visible.
This occurs in Cygwin, mintty version 3.7.5-1 and not in 3.7.4-1, so I went back to the previous version and that solved my problem. I just wanted to report the issue.

**Comment by mintty** [comment]
ASCII art does not need DEC sequences; it is unclear which output produces which result for you.
Please describe your scenario in a reproducible way.

**Comment by Wodan58** [comment]
![mintty-3 7 4](https://github.com/user-attachments/assets/5df427a2-caad-404e-a447-f8f9ce9622ff)
![mintty-3 7 5](https://github.com/user-attachments/assets/a82a8066-45a5-47f7-86e1-10995663950f)

Included are the splash screens of my application. The last one shows the problem.
The application uses DEC sequences. Reproducing would require a small shell script that echoes the correct sequence, but I am not going to build that script.

**Comment by mintty** [comment]
As I don't see that issue, a reproducible case is needed for assessment. A screenshot does not help.
Run `mintty -l log` and produce the issue. Then upload the log file here.

**Comment by Wodan58** [comment]
That has to wait until later tonight.

**Comment by mintty** [comment]
Issue reproduced, no log file needed anymore.

**Comment by derekschrock** [comment]
I'm seeing the same thing with tmux panes boarders.   Is it the same issue?

A simple testcase would run tmux and run `C-b`  (escape), `:split-window`   See single character "-" followed by blank. to EOL.

**Comment by mintty** [comment]
Released 3.7.6.
