### ISSUE TITLE
Commands entered while other commands processing are no longer queued. Version 3.7.6

### ISSUE THREAD

**Issue by NicholasBrockman** [mintty/mintty#1289]
On older versions, when executing a command while another command was processing, the terminal would wait until the current command completes, and then immediately execute the next command that was entered. You could queue as many commands as desired. On version 3.7.6, this no longer works. A simple test of this would be
```
sleep 5s
git status
```
The "git status" would execute after the terminal was done sleeping.  This is this is the exact same issue as this windows terminal issue: https://github.com/microsoft/terminal/issues/17587.
I'm not exactly sure when this broke, but I was previously using a 3.4.X version where this was working. Just today when I upgraded to version 3.7.6 is when it stopped working.

Expected behavior: Commands entered while another command is processing should be queued, and executed when the previous command completes.

**Comment by mintty** [comment]
I confirmed it works well.
The issue itself and the coincidence with another terminal indicates this is not a terminal issue.
Maybe you've installed some background process that listens at the pty?
