### ISSUE TITLE
mintty 3.7.4 in wsltty has no terminal type 'xterm-direct'.

### ISSUE THREAD

**Issue by netjune** [mintty/mintty#1291]
mintty 3.7.4 in wsltty has no terminal type 'xterm-direct'. But mintty with same version in git-for-windows has the terminal type 'xterm-direct'.

How to use true color with mintty in wsltty?

**Comment by mintty** [comment]
This is described in the manual page, see "Terminal type". For WSL, mintty tries to check whether terminal types are supported in the distribution. True colour can always be used with the respective control sequences.

**Comment by netjune** [comment]
I set "Terminal type" to xterm-256color. Then I run emacs in WSL terminal. It is in 256 colors mode.

If I set `export TERM=xterm-direct` first, then emacs is in true color mode.

**Comment by netjune** [comment]
I set "Terminal type" to xterm-256color. Then I run emacs in WSL terminal. It is in 256 colors mode.

If I set `export TERM=xterm-direct` first, then emacs is in true color mode.

**Comment by mintty** [comment]
Yes, because emacs, or the terminal library it uses, looks at the variable to decide whether to use true colour or not.
An application could as well be programmed to use true colour in either case.

**Comment by netjune** [comment]
OK. 
Thanks.
