### ISSUE TITLE
In vt52 mode positioning sequence ESCYcxcy does not work correctly in mintty

### ISSUE THREAD

**Issue by sf-at-sf** [mintty/mintty#1299]
Hello,

In vt52 mode ESCYcycx sequence does not position cursor correctly if cy value exceed number of rows on the screen (24).

This is from email conversation with Thomas Dickey (xterm maintainer):
-----
the manual (EK-VT5X-OP-001_DECscope User's Guide) agrees with you:

        For "line#", the host sends the octal code 040 to specify the top line
        of the screen, 041 to specify the line below the top line, and so
        forth.  On the VT50H, 053 specifies the bottom line.  On the 24-line
        VT52, 067 specifies the bottom line.  If line# does not specify a line
        that exists on the screen, the VT50H will move the cursor to the bottom
        line of the screen.  However, the VT52 will not move the cursor
        vertically if the vertical parameter is out of bounds.  A Direct Cursor
        Addressing command with the first parameter greater than 067 can be
        issued to the VT52 to move the cursor arbitrarily in the horizontal
        direction without the flickering of the video that the full Direct
        Cursor Addressing command can cause.
 -----

The impact (which I observe):
Using hobbyist RT11 OS under SIMH and native DEC K52 editor. K52 will keep entered line always at the bottom and does not display or browse files correctly, keeping cursor at the last line for every entry.

Fix which I put for my self yet:

MINTTY Source VERSION 3.7.6
src/termout.c  file:

replace from line 125 :
 125     if (y >= term.rows)
 126       y = term.rows - 1;
 
with:

 125     if (y >= term.rows)
 126     {
 127       if (term.vt52_mode)
 128         y = curs->y;
 129       else
 130         y = term.rows - 1;
 131     }

Please let me know if any questions or concerns.

Thanks
Serguei

**Comment by BrianInglis** [comment]
Terminal emulations supported by `mintty` are: xterm{,-direct,256color,vt220}; vt{100,220,340,420,525}; mintty{,-direct}. 
Change your `mintty` and *RT11* settings to a supported *vt100*+ and use an editor that supports that terminal e.g. `KED` not `K52` see [KED Mini How-To Guide](https://avitech.com.au/?page_id=959) [AV-H854B-TC RT-11 Keypad Editor Reference Card](https://bitsavers.org/pdf/dec/pdp11/rt11/v5.6_Aug91/AV-H854B-TC_RT-11_Keypad_Editor_Reference_Card_1989.pdf) [AA-H853A-TC PDP-11 Keypad Editor Users Guide](http://bitsavers.informatik.uni-stuttgart.de/pdf/dec/pdp11/rt11/v4.0_Mar80/2b/AA-H853A-TC_PDP-11_Keypad_Editor_Users_Guide_Mar80.pdf) 
Or else install `TECO` and use `VTEDIT` [VTedit Keypad Text Editor and Corrector for TECO-11 User's Manual](https://manualzz.com/doc/19798014/digital-equipment-corporation-vtedit-user-s-manual) as from one of the macro collections under [Ibiblio (was Sunsite) TECO](https://www.ibiblio.org/pub/academic/computer-science/history/pdp-11/teco/) 
[AV-D53OA-TK d|i|g|i|t|a|l TECO pocket guide](https://web.archive.org/web/20020407074041/http://zane.brouhaha.com/~healyzh/teco/TecoPocketGuide.html) Wayback Archive of my *TECO pocket guide* scanned cover GIF and original HTML rendering which Zane Healy kindly added to his TECO site decades ago.

**Comment by mintty** [comment]
Right now, mintty behaves the same as xterm:
`printf '\e[?2l\eY  \eJ\eY!!!\eY000\eY@44\eY4~4\eY@0R\eY0~C\n\e<'`
When was your conversation with Thomas Dickey? Did he say he'd change xterm?
And would the same apply to an out-of-bounds column parameter?

**Comment by sf-at-sf** [comment]
Hi,

I contacted Thomas about a week ago or so. He checked the manual, acknowledged and said, that he will put it into his to-do list.

I offered Thomas possible fix also. He decided that it will not be necessary. And I believe he will be working of his to-do list and possibly would fix it in his own pace. Besides, I fixed only xterm itself but did not check unit tests or any other surrounding programs.
I used xterm 395 for the fix.

Yes, I believe at this moment Xterm works the same way as mintty for vt52 "ESC Y" sequence, till Thomas will do update.

According to manual for vt52 (which Thomas mentioned ), for column# value "if column# greater than [octal] 157 [79th column [0-79]] and, therefore, does not specify a column that exists on the screen, the cursor is moved to the rightmost column on a line on all models".  [I bet "all models" mean vt52, vt50H]

Thanks
Serguei

________________________________

**Comment by sf-at-sf** [comment]
Hi Brian,

Thanks for the additional info. I use KED for simh rt11 as well and my terminal is set as vt200.
I tried using k52 also while getting accustom to old soft and it was having the issue.

Thaks for mentioning TECO and info about it. I will try it too. I did not use it before and it is interesting to try.

As for vt models:

I understood that VT100+, vt200+ (100,102,200,220,240,320,340,420,525) support internal switching into vt52 mode and if vt52 mode is not working correctly, then compatibility is partial.

Mintty, xterm are solid software and I use them for my day-to-day work.
If I could make it better, I will.

________________________________

**Comment by j4james** [comment]
FWIW, this behavior is also defined in the DEC STD 070 manual in the chapter on VT52 emulation, which documents the conformance requirements for terminals that can emulate a VT52.

**Comment by BrianInglis** [comment]
In fact, that mode is `DECANM` *ANSI* Mode / *VT52 Compatible* mode, but *VT52* only keys and indicators, *Setup* features, *NVRAM* settings, optional *Printer Port* features, and the same *G0*/*G1* Graphic characters are not supported. 
The terminal is not expected to come up in *VT52 Compatible* mode, but has to be switched with *RM* *DECANM* *VT52* *CSI*`?2l`.
If then switched into ANSI X3.41-1974/X3.64-1977 mode with *ESC*`<`, the DEC Private parameter indicator `?` is replaced by `O` in many command and response sequences, the PF key parameter is prefixed by `O`, and the cursor key sequences are prefixed by *CSI* with optional parameter(s) and not just *ESC*.

**Comment by mintty** [comment]
So STD 070 contradicts the VT52 description? As that scanned PDF is not searchable, on which of its 1252 pages did you find it? Anyway, I'd rather integrate the patch above to reflect the original hardware and support legacy software.

**Comment by sf-at-sf** [comment]
For horizontal dimension, looks like, it contradicts the VT52 description, previously mentioned.
Same time, I am not certain on how to prove correctness of either one without real device or specific DEC testing/validation software. As I understood, on real device, exclusive horizontal cursor movement was done to decrease screen flickering (it was written in VT5x documents - EK-VT5X-OP-001_DECscope and EK-VT55E-TM-001 VT55-E, F, H, J DECgraphic Scope User's Manual).

This is from STD 70 book, page from bitsaver (It is good pdf with searchable text):

https://bitsavers.org/pdf/dec/standards/EL-SM070-00_DEC_STD_070_Video_Systems_Reference_Manual_Dec91.pdf

Page A-18:

Format: ESC Y line column
1/11 5/9 line column
Description: The Direct Cursor Address control moves the
active position to the specified line and column. The line and
column numbers are sent as the ASCII characters whose codes are
the decimal numbers of the line or column plus 31. For example,
decimal 32 (SPACE, 2/0) refers to the first line or column, and
decimal )11 (0, 6/15) refers to the eightieth column.
Notes:
1. This command has range limits of 1 to 24 lines with
parameters "SPACE" (2/0) to "7" (3/7), and 1 to 80
columns with parameters "SPACE" (2/0) to "0" (6/15). An
out of range parameter i~~ither dimension causes no
action in that dimension, but if the other parameter is
in range it will still be operated on.
State Affected:
ACTIVE POSITION: CHARACTER_POSITION,TYPE;
Algorithm:
PROCE'DURE CURSOR POSITION (LINE_VALUE,COLUMNVALUE: CHAR);
VAR Y: LINE_TYPE;
X: COLUMN_TYPE;
BEGIN
(* convert ascii characters to position values *)
Y:= ORD(LINE_VALUE) - 31;
X:= ORD(COLUMN_VALUE) - 31;
(* conditionally update line *)
IF ((Y >= 1) AND (Y <= MAX_NUM_LINES)) THEN
ACTIVE_POSITION.LINE:= Y;
IF ((X >= 1) AND (X <= MAX NUM_COLUMNS)) THEN
ACTIVE_POSITION.COLUMN:= X;
END;

**Comment by BrianInglis** [comment]
> So STD 070 contradicts the VT52 description? As that scanned PDF is not searchable, on which of its 1252 pages did you find it? Anyway, I'd rather integrate the patch above to reflect the original hardware and support legacy software.

The smaller bitsavers copy is searchable and Appendix A VT52 Emulation starts on page A-1/1051; Direct Cursor Address is on page A-28/1078 and says:

> This command has range limits of 1 to 24 lines with parameters "SPACE" (2/0) to "7" (3/7), and 1 to 80 columns with parameters "SPACE" (2/0) to "0" (6/15). An out of range parameter in either dimension causes no action in that dimension, but if the other parameter is in range it will still be operated on.

**Comment by mintty** [comment]
Using the VT102 emulator http://software.schmorp.de/pkg/vt102.html that uses the original ROM, I could verify that VT102 in VT52 mode runs DEC STD 070 behaviour, not the weird inconsistent behaviour described in VT52 docs. Whether VT52 actually behaved differently or its description was wrong, we emulate VT100, not VT52, so I think it's proper to follow that way.

**Comment by mintty** [comment]
Uploaded fix. Updated test file:
[xvt52pos.txt](https://github.com/user-attachments/files/18029949/xvt52pos.txt)

**Comment by mintty** [comment]
Released 3.7.7.
