### ISSUE TITLE
Allow font size specified in decimal instead of fixed integer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#141]
```
mintty not allow me to use font size 7.5.

For me, 7.5 Bitstream vera sans mono is the best setting for terminal fonts.
```

Original issue reported on code.google.com by `zar...@gmail.com` on 22 Oct 2009 at 6:26

**Comment by IceMan81** [comment]
There are lots of applications on Windows that allow half size increments for font sizes. Most Windows editors do, including Word, OneNote, Excel etc. Text editors like Sublime etc also support half size increments.

**Comment by mintty** [comment]
And there are lots of applications that don't. Concerning font handling, a terminal would be more comparable with `notepad` than with a text processing (and formatting) application. Also the Windows font selection dialog which mintty uses does not support it.
