### ISSUE TITLE
Add Minimize To Tray

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#178]
```
One feature I miss in MinTTY is an option to minimize it to the tray.  The
behavior of PuTTYtray to do that when Ctrl-Clicking on the minimize button
in particular is a very convenient (to me) way to do it.
```

Original issue reported on code.google.com by `fastcat@gmail.com` on 2 Apr 2010 at 9:12

**Comment by kevindelsh** [comment]
I'd like to re-open this issue for the following reasons:

1- Traying software are bloated with other unwanted functionalities.
2- mintty is a piece of software that in many cases you end up opening several instances of but just need to use a couple of them actively (the rest run in the background).
