### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#18]
```
Some terminal emulators have a background image feature. This is firmly in
the realms of visual frippery though and unlike transparency it needs more
than a couple of function calls.
```

Original issue reported on code.google.com by `andy.koppe` on 2 Jan 2009 at 7:09

**Comment by mintty** [comment]
Released 2.9.0.

**Comment by mintty** [comment]
Released 2.9.1. Image prefix '%' scales window to image aspect ratio.

**Comment by mintty** [comment]
Released 2.9.4 with option `Background==`.

**Comment by elliott-beach** [comment]
Could you please provide an example of what the format of an absolute path looks like in the configuration file?

**Comment by mintty** [comment]
Is https://github.com/mintty/mintty/wiki/Tips#background-image sufficient?
