### ISSUE TITLE
Fullscreen with font zoom

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#204]
```
When going fullscreen, it would occasionally be useful to be able to increase 
the font size along with the screen size, particularly when trying to demo 
something. At the moment, this can be done manually using Ctrl+'+', but it 
would be more convenient to do the fullscreen switch and font zoom in one step. 
Adding 'Shift' to the existing Alt+F11 (or Alt+Enter) shortcut is one 
possibility.

(First suggested at http://code.google.com/p/mintty/issues/detail?id=79#c3)
```

Original issue reported on code.google.com by `andy.koppe` on 25 Jul 2010 at 7:33

**Comment by mintty** [comment]
Implemented optional sync of font scaling with window scaling, triggered by Shift key:
•	Shift+mouse-drag on window border
•	Shift+maximize, Shift+minimize (click on window title)
•	Shift+Alt+Enter, Shift+Alt+F11
•	Shift+menu...“Full Screen”
See also #233.

**Comment by mintty** [comment]
General rule is now: when holding Shift while resizing or zooming, window size and font size are kept in sync.
