### ISSUE TITLE
ZMODEM support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#235]
```
Hi,

please add Z-Modem support for file up and downloads.

There is an open source implementation of the Z-Model protocol available at 
http://www.ohse.de/uwe/software/lrzsz.html 

Although lrzsz is only at version 0.12.20, it is rock solid and i've been using 
it for years SecureCRT.

Ideally, when sending a file (upload), one should just drag and drop the file 
on the terminal. When receiving a file (download), a dialog should pop up and 
ask where to store that file. Also, there should be an configuration parameter 
to specify a default download location.

Thanks :)
```

Original issue reported on code.google.com by `rojaro@gmail.com` on 16 Nov 2010 at 2:11

**Comment by mintty** [comment]
See #440 for handling of drag-and-drop; the dropped file/folder is now embedded in escape sequences in bracketed paste mode.

**Comment by mintty** [comment]
Released bracketed-paste-mode embedding of drag-and-drop contents in 2.3.7.
This gives a cooperating application the opportunity to send a dropped file anywhere.

**Comment by qins** [comment]
This is a very useful feature when scp is disabled.
Can't find any setting on wsl-terminal, instead X-shell did it painless.

**Comment by mintty** [comment]
This is not a genuine feature of a terminal and it has been fuzzy from the beginning.
Please describe precisely what feature you'd like to see, and why you think it could be a suitable task of a terminal. There are lots of file transfer applications around, so what's the task they don't accomplish?

**Comment by mintty** [comment]
> sz filename

That's also an application, right? So why can't you just run it? What's the supposed terminal support?
Also, how do you actually login to the remote side (ssh, telnet, ...)? In many cases, this will give you a transfer option already.
Still unclear what benefit you are asking for, I can only repeat, describe your idea *precisely*.

**Comment by qins** [comment]
1. Yes, that's an app on server side. 

2. I had run it, it works while run by X-shell terminal, but it did not work while run by mintty.

3. When I login remote server with ssh on this terminal, Filezilla still need to login to download a file.
Run sz directly on remote server which sshed with X-shell terminal, would download the file right away.

**Comment by mintty** [comment]
OK, but what does sz actually do to get a file transferred? Where's the procotol described?
Also, I don't see how Filezilla would get in. It's not related to the terminal, or is there a terminal version of Filezilla?
Finally, whatever the procotol may be, I assume it's causing a file to be written by certain escape sequences. This, however, would generally be considered a security risk - every misbehaving application could write any file to your disk. How should that be handled?

**Comment by mintty** [comment]
I understand that you run ssh (inside mintty) and would then want to run sz remotely to get a file transferred. Considering that you could be running ssh as well in any other terminal, and by the nature of the task split between a communication program (ssh) and the terminal (mintty), the file transfer should be managed by ssh, not the terminal.

**Comment by mintty** [comment]
Also, I don't think scp can be disabled where ssh works. There must be something else in your environment, maybe you'd rather try to debug your usage of scp. This is a mature solution that would not require new implementation with questionable security implications.

**Comment by mintty** [comment]
Also, anyone considering this feature should check out Andy's analysis above, please.
The most feasible alternative may be `screen`, so if anyone can contribute a working `screen` setup, that will be appreciated and I'll include it in the wiki.

**Comment by qins** [comment]
About scp, I think the server admin did something to hard drive permission to make scp useless.

After login to node02, I want copy a file from nlogin01:

> scp nlogin01:/work/project/WGS/WGS_00004_1or2.tsv ./
> M01@nlogin01's password:
> **\033(B\033[mC0640 4109 WGS_00004_1or2.tsv**

---

Sorry about the inadequate information.

Basically, There are 4 OS, one Debian on one win10's WSL, one remote node02, one remote nlogin01.

I can only login to node02, and then ssh to nlogin01. 

There is a tsv file on nlogin01 which need download to win10.

I tried scp first, and found the error.
But type "sz WGS_00004_1or2.tsv" on nlogin01 with X-shell terminal, a pop window just ask me where to store the file. **It's amazing!** 

So I searched why mintty or wsl-terminal can not do the same, and found this thread.

**Comment by mintty** [comment]
Note that Xshell is a combined terminal and ssh client (like putty), so it's not an example of a terminal supporting zmodem transfer. I still hold my statement that this would be the task of a communication component. Note also that these inband transfer protocols are legacy stuff and the only implementation of it that I found has not been maintained for almost 20 years.

**Comment by qins** [comment]
Thanks for your patience. It indeed is not a mainstream feature. I'll find
another way.

**Comment by qingyunha** [comment]
Hello, I made a ssh wrapper to support rz and sz. I hope you find it useful.

https://github.com/qingyunha/zssh

**Comment by mintty** [comment]
Well, thanks for the notice and I guess those who want to use ZMODEM know what it is and how to use it.
However, in the cygwin environment that mintty runs in, the Go language is not available as a package, so the script is a bit alien in this environment.

**Comment by BrianInglis** [comment]
> Ssh is, kind of, and could be one target to request this feature. But they will probably point to `scp` which seems not to work in this case (should still be debugged anyway).

Note that legacy `scp` is now deprecated and the default will be changed to use *SFTP* in the near future [Future deprecation notice](https://www.openssh.com/txt/release-8.8) which introduces some compatibility issues. 

Enhanced dialup modem data link protocols *V.92/bis* with *V.44* compression increased effective data rates to up to 320kbps, and dialup connection protocols like *X.21* for *X.25*, *PPP*, and *PPPoE* for *DSL*, eliminated the need for other forms of error detection and recovery, except on very limited platforms where *SLIP* is still preferred for low ovehead. 

Even then, low speed broadband over DSL or DOCSIS 1.0/J.112 2.0/J.122 was much faster, more reliable, and mostly up, even though more expensive than dialup in areas where local dialup calls were free, and charges were solely for Internet interconnection. 

This transition happened in urban areas between 1990 and 2000, but rural areas still have issues getting any network connections. 

(In the late 1980s, a notorious telco provisioned a cheap 175km digital link between field offices in our network using 2000km unloaded 4 wire circuits passing through two major cities 700km apart with up and down legs of 800km and 500km! Our local telco guys and we boggled at the waste!)
