### ISSUE TITLE
OSC 52 clipboard control (xterm)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#258]
```
small rfe, add support for xterm's clipboard OSC

paraphrasing from http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

Operating System Controls
OSC 52 ; Pc ; Pd ST
OSC 52 ; Pc ; Pd BEL

-> Manipulate Selection Data.

The first parameter, Pc, is used to construct a list of selection parameters 
for clipboard, primary, select, or cut buffers (not important at all).  If the 
parameter is empty, xterm uses s 0 , to specify the configurable 
primary/clipboard selection and cut buffer 0. (Would be enough to always 
default to clipboard)

The second parameter, Pd, gives the selection data.  Normally this is a string 
encoded in base64.  The data becomes the new selection, which is then available 
for pasting by other applications. (This is important, base64 encoded data 
should be decoded and saved in the clipboard)

If the second parameter is a ? , xterm replies to the host with the selection 
data encoded using the same protocol.
```

Original issue reported on code.google.com by `ailin.ne...@gmail.com` on 8 Apr 2011 at 7:39

**Comment by kangjianbin** [comment]
Hi mintty experts,

Is there still a chance for pull request #579? 
We need this because it is not a good user experience to use mouse to copy text if the line is wrapped.

With OSC52 support, we can also copy text in editors to client OS. Emacs supports this feature. And there are some configurations to make vim support it too.

This implementation has these limitations (or restrictions :-) ):
1. Only valid text is allowed to copy to clipboard.
2.  Doesn't allow server to read clipboard (ignores '?' command)
3. Selection parameters is ignored (always uses system clipboard)

That can avoid the security issues discussed above. 

If you still consider it to be dangerous, I can provide more restrictions:
1. Disable the feature by default unless user enables it in configuration (.minttyrc)
2.  Only allow clipboard selection parameter and ignore other parameters.

**Comment by mintty** [comment]
I think with these restrictions, the feature can be integrated.
Here are some :) comments:

* As the second parameter is ignored, it should also work if it's empty (like in xterm).
* What do you mean by "Only valid text is allowed"? I don't see any related restriction in the code.
* win_copy_text: I suggest to use cs__mbstowcs (with double "_") which does the proper allocation, then free the memory.
* Please test whether non-ASCII characters can be copied from a non-UTF-8 terminal session and pasted properly into a UTF-8 session.
* File diff in #579 introduces variable cmd_buf (and modifies config.*, term.*, winmain.c), the version I downloaded does not; I think the buffer size should not be limited but I'd prefer if do_clipboard uses its own buffer.
* Please use space around operators consistently ( `malloc(len-1)` , `base64_decode_clip(s+2, len - 2, output, len-2)` ).
* Please do not add .gitignore file.
* Please rebase against current repository (esp. termout.c).

**Comment by mintty** [comment]
> "Only valid text is allowed"

Also, I do not see specific security issues in allowing non-text, e.g. escape sequences. I see more risk in pasting something like "rm -fr *" into the command line.

**Comment by kangjianbin** [comment]
Thanks for the feedback. I will submit another pull request.
'Valid text' I meant is the text that can convert to unicode. 

"rm -fr *" is really a issue and I didn't think of it before :-).
One possible solution is to add unicode 0x200b (zero width space) at start of each line and skip all ESC characters. This makes bash fails to execute commands.
One possible solution is to add unicode 0x200b (zero width space) at start of each line and skip all ESC character. This makes bash fail to execute commands.
However it is not a standard way and editors running in terminal will show this character.

**Comment by mintty** [comment]
I would rather not modify the string, as xterm doesn't either.
Let's guard the feature with Boolean option `AllowSetSelection`.

**Comment by kangjianbin** [comment]
Hi mintty,
I didn't catch you point:
> I think the buffer size should not be limited but I'd prefer if do_clipboard uses its own buffer.

So I sent a pull request  #586 with limitation of 1536 characters.
The comment of cmd_buf is _OSC or DCS string buffer and length_, so why not use it as OSC52 clipboard buffer? OSC52 is also a OSC sequence thought it needs larger buffer.

**Comment by mintty** [comment]
Let's discuss patch details in the patch issue...

**Comment by mintty** [comment]
Released in 2.6.1.

**Comment by mintty** [comment]
I've noticed this in the base64 code:
`#define error(...) ... exit(1); ...`

This is not good. Can we please change the code so that any error would cancel the requested operation but not abort mintty?

**Comment by mintty** [comment]
Oh, it's in the test section only. Sorry; yet I'll add a warning any maybe remove the strange while(0) loop.
