### ISSUE TITLE
Better transparency

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#3]
```
Currently the same alpha value is applied to the whole window, including
text and window frame. This is done rather simply by turning the window
into a "layered" window and setting it LWA_ALPHA attribute.

It would look better though if only the background was transparent, which
could be done using UpdateLayeredWindow() and an appropriate BLENDFUNCTION.
Trouble is, the standard controls don't work with that, so that a custom
scrollbar and the window controls would need to be implemented. This would
be far too much bother for what it's worth though, so it ain't gonna happen.

Vista's "Desktop Window Manager", however, might make this more doable.
Here's a blog that explains it:

http://weblogs.asp.net/kennykerr/archive/2006/08/10/Windows-Vista-for-Developers
-_1320_-Part-3-_1320_-The-Desktop-Window-Manager.aspx


```

Original issue reported on code.google.com by `andy.koppe` on 26 Dec 2008 at 12:02

**Comment by mintty** [comment]
See #501 for a more recent request about transparency.
As I do not see how this request would ask for additional benefit, I'm closing the issue.

**Comment by simonmysun** [comment]
Hi, 

I would like to request a opaque text over transparent background as discussed in previous posts in this issue. As far as I read from your discussion, it seems that a glass mode was developed which supports opaque text but the opaque text is not supported in "legacy" transparent mode. And the glass mode might be deprecated(https://github.com/mintty/mintty/commit/bf429082c6315681221fabee20138042b51070a9)

Could you please reopen this issue or should I open another issue as a new feature request? Thank you.

**Comment by mintty** [comment]
In my tests, it is hardly recognizable that text is not fully opaque. But in general I acknowlege your request. This issue is very old, though. If you have an idea how to implement that, feel free to open a new one :)
