### ISSUE TITLE
Shell menu item

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#325]
```
Please add a Open Cygwin item to the shell right-click menu.

It requires a DLL but for example this http://code.kliu.org/cmdopen/ code can 
be used with a minor modification so the difficulty of this issue is easy.

Thanks! Great software!
```

Original issue reported on code.google.com by `john.s.peterson@live.com` on 8 Mar 2012 at 2:33

**Comment by mintty** [comment]
For the records: mintty has now (from release 2.6.2) an option `--dir` to set its starting directory, in order to support starting mintty (e.g. from the Explorer context menu) in *any* folder. The mechanism currently used by `chere` fails on non-ASCII folder names. See also #371.
