### ISSUE TITLE
byobu function keys are not responsive

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#368]
```
f2 - opens a new session
f3 - switches to next session
f4 - switches to previous session

These keys do not work, or work very well, when using mintty. If you pound the 
key like 10 times it eventually works, but otherwise pressing it does nothing. 

I have messed around with a bunch of the options in mintty and still can't get 
it working. 

I know it is not something with cygwin because opening the regular cygwin 
terminal byobu function keys work fine. 

using version 1.1.1

Thanks
```

Original issue reported on code.google.com by `logan.li...@gmail.com` on 16 Jan 2013 at 12:03

**Comment by mintty** [comment]
There have been recent fixes in cygwin (not mintty) that are supposed to resolve this issue.
Please retest.
If similar problems persist, please cross-test with xterm, too.

**Comment by stdedos** [comment]
Hello. I am using Mintty as part of [Git Portable](https://git-scm.com/download/win) package.
This issue still affects me.

To be honest, I am not interested in any alternative - but for completeness I downloaded cygwin and xterm - same problem (random sequences produce random characters)

> I can confirm the shift-F2 key combination does not work. (it writes ~ instead)

Has anything changed?

**Comment by mintty** [comment]
Thanks for reporting.
In your 2 test scenarios (Git+mintty, cygwin+xterm), is any of the other components mentioned above involved (byobu, tmux, ssh)?
How precisely can the effect be produced? If I simply run git-bash from Git-Portable, everything works as expected.

**Comment by stdedos** [comment]
I am connecting using ssh to a local raspberry installation (Or Ubuntu/16.04 or Debian/Jesse - doesn't matter), and I am using the combination byobu/tmux as my main working shell.

Some of the shortcuts work, some don't. I could track them one by one down, but I think there must be a way to automatically parse the charmap sent from each terminal (I have no idea how, however).

Terminal output for Shift+F# keys, F1-F12:
```
Stdedos@Stdedos-PC MINGW32 /e/Stdedos/Desktop $ PQRS;2~2~2~2~2~2~2~;2~
user@raspberry:~$ ~~~~~~~~;2'\0'~'\0''\0' # F9, F11, F12 == '\0'
```
`'\0' = NUL` output, i.e. shortcut is parsed

**Comment by mintty** [comment]
So you *first* log in remotely (ssh) then use byobu/tmux on the backend side, right?
So what's your frontend? Mintty on cygwin/msys/Git...? Which version?
And what do you Shift+Fx actually expect to do? They are "normal" function keys, the sequence you see is the normal escape sequence they send, with the leading escape prefix stripped by the shell.
Which of the components in your mintty-ssh-byobu-tmux queue is supposed to capture them?

**Comment by stdedos** [comment]
Yes, I **_first_** login to a remote server. Would you like me to find a way to install this on windows and test it? It would be too much, and afaik there is no way to include it to GitPortable (so _maybe_ this could happen on cygwin/xterm, but definitelly non on the mintty/GitPortable).

GitPortable v 2.10.2 (Downloaded from SourceTree, somehow it doesn't allow me to update it to 2.11.0, some random error)
![image](https://cloud.githubusercontent.com/assets/133706/22509189/abe4fdf6-e895-11e6-9838-e054d0521ac3.png)

Mintty 2.6.2 x32
![image](https://cloud.githubusercontent.com/assets/133706/22509226/c824800e-e895-11e6-8a45-c2a312f46eab.png)

In plain mintty, I obviously don't expect them to do anything.
byobu/tmux should caputre it (byobu is a configuration layer to tmux _or GNU Screen_)
ssh-ing from Ubuntu to any other machine sends all the shortcuts correclty _(unless e.g. GNOME captures those shortcuts)_

**Comment by mintty** [comment]
So it looks like a byobu bug, right?
There is a similar report on http://superuser.com/questions/651427/function-key-shortcuts-in-putty-mintty-and-tmux-byobu; however, there the sequences are assumed to be captured by tmux; also, the poster makes wrong assumptions on the escape sequences that tmux should expect (the ones shown are rxvt sequences, not xterm sequences).

As another cross-test, if I run git-bash, then ssh localhost to cygwin, then byobu, function keys work fine.

**Comment by stdedos** [comment]
> however, there the sequences are assumed to be captured by tmux;

Well byobu is a frontend, but you could _consider_ it as a _"big complex dot-file with some accompanying widgets"_ to tmux. So tmux is the actual program running (also verified by screenshots of freshly-rebooted system)

![image](https://cloud.githubusercontent.com/assets/133706/22513824/0918d578-e8a6-11e6-86d5-3106484d9c6f.png)


![image](https://cloud.githubusercontent.com/assets/133706/22513802/fbd5bde0-e8a5-11e6-9a3d-37ad6ab722d0.png)

Disclaimer: I am not familiar post's notation on "escape sequences" _(or escape sequences of any kind other than some plain coloring to be honest)_. I also don't know why OP "deduces" that mintty is 'the best candidate'.

Would you like me to perform that test?
I have some missing points on what exactly you ran:
```
========================================
|            Win #:localhost           |
|--------------------------------------|
|         ssh                       ssh:
| mintty =====> cygwin (receiving) =====> ? byobu/tmux
|                      (terminal?)     :
|--------------------------------------|
|                                      |
========================================
```
So, using cygwin as a layer of abstraction (or another layer, if you count ssh as 'layer'), miraculously every documented shortcut _(Shift+F1 on byobu)_ is accessible somehow?

**Comment by mintty** [comment]
*You* responded to a closed issue, not me... Anyway, if there's additional information in a byobu issue, does it have there a link you can post here?
My test chain was mintty(git portable) => ssh localhost => bash(cygwin) => byobu
Shift+F1 etc do something apparently desired in byobu.
I'll try later with remote ssh.

**Comment by stdedos** [comment]
> You responded to a closed issue, not me...

I merely meant that you were kind enough to re-consider ....

Well, my bug searches in https://bugs.launchpad.net/byobu failed to find the same issue - to be honest you found the issue closest to my problem that I've seen so far. If anything comes up at a later time, you will find it here.

A lot of key combinations do a lot of desired stuff - mainly those documented there (also accessible by F1 --> Help)

**Comment by mintty** [comment]
New test cases:
running from mintty (cygwin) first, then also from git-bash (Git Portable 32 and 64 bit),
ssh to a remote Linux system (Debian on PowerPC), fresh download of byobu, self-compiled,
running byobu, typing F1, F2, F3 opens new virtual shell windows, no escape sequence artefacts.

**Comment by stdedos** [comment]
![image](https://cloud.githubusercontent.com/assets/133706/22527251/2100fcc0-e8d7-11e6-9a73-15974224f837.png)

`F-keys` do work; The combination of `Shift+F-keys` (except `F9`, `F11`, `F12`) don't work
Also, `Alt + Shift + Down` does not work; `Alt + Shift + Up` does work though

**Comment by mintty** [comment]
Shift+F2: splits window. Shift+F3/F4: flashes split window panes. Alt+Shift+down: moves split border.
Shift+F1: display a help text. But it looks different than your screenshot. Probably a newer version of byobu.
Please test with the current version.

**Comment by stdedos** [comment]
Yes - because that screenshot is taken using `F1 --> Help` from mintty; as I told you `Shift+F1` is not available in mintty

Tested on my Ubuntu 16.04 LTS: byobu version 5.106 / tmux 2.1. (instead of byobu version 5.87 / tmux 1.9).

Keybindings still "resist" working

**Comment by mintty** [comment]
Retested with mintty (cygwin), ssh 1.0.2j, byobu 5.106, tmux 1.7. Works.
What's your `ssh -V`?

**Comment by stdedos** [comment]
`OpenSSH_7.3p1, OpenSSL 1.0.2j  26 Sep 2016`
