### ISSUE TITLE
adb shell 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#375]
```
open a conection whit adb shell for android terminal.

the line command is very well but the keys up and down don't print the last 
typed command.



```

Original issue reported on code.google.com by `leone...@gmail.com` on 7 Mar 2013 at 6:32

**Comment by mintty** [comment]
adb is not a cygwin package and I assume it's a Windows command-line tool.
As such, it does not interact with cygwin readline.
(Likely not working in xterm or cygwin console either.)
Not a mintty issue.
