### ISSUE TITLE
Use different encodings for native Windows commands output and remote output

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#376]
```
1. I am using a Windows 7 PC. The system encoding is GBK.
2. When I set "charset=UTF-8", the output of ssh is OK, but native Windows 
command output is garbled.
3. When I set "charset=GBK", native Windows command output is OK, but the 
output of ssh is garbled.

So, is it possible to use different encodings in these two different 
circumstances?

Thanks, :)
```

Original issue reported on code.google.com by `shinysky...@gmail.com` on 11 Mar 2013 at 3:04

**Comment by lexazloy** [comment]
chcp should work:
```
if [[ $OSTYPE == msys ]]; then
    chcp.com 65001 > /dev/null
fi
```

P.S. 65001 is UTF-8.

**Comment by mintty** [comment]
There are multiple ways for Windows programs to write output to the console/terminal.
chcp only affects some of them and works (as you suggest) for only a few programs

**Comment by mintty** [comment]
Also, like #56, this is not actually a mintty issue but a general cygwin issue.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
