### ISSUE TITLE
Disable middle click paste option

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#384]
```
Shift insert is enough.
```

Original issue reported on code.google.com by `ZoobyW...@gmail.com` on 18 Apr 2013 at 11:13

**Comment by mintty** [comment]
Added MiddleClickAction option.
No GUI configuration yet.

**Comment by mintty** [comment]
Added to Options menu.

**Comment by mintty** [comment]
GUI config released in 2.2.1.
