### ISSUE TITLE
More clear & bright text

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#389]
```
the xshell and securecrt show more clear and bright fonts than mingtty
```

Original issue reported on code.google.com by `BigMouse...@gmail.com` on 8 Jun 2013 at 9:11

Attachments:
* [a.png](https://storage.googleapis.com/google-code-attachments/mintty/issue-389/comment-0/a.png)
* [b.png](https://storage.googleapis.com/google-code-attachments/mintty/issue-389/comment-0/b.png)

**Comment by mintty** [comment]
You can choose your preferred font in the mintty Options menu.
