### ISSUE TITLE
Command shell window remains open in Windows 7 Beta

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#39]
```
What steps will reproduce the problem?

1. mintty.exe in C:\Program Files\mintty\
2. cygwin installed in C:\cygwin\
3. Shortcut to mintty.exe on Desktop
4. "Target" (desktop shortcut) set to '"C:\Program Files\mintty\mintty.exe"
/bin/bash -l'
5. "Start in" (desktop shortcut) set to 'C:\cygwin\bin'

(single apostrophe (') used for clarity, not used in shortcuts)

What is the expected output? What do you see instead?

MinTTY starts and works as expected. Command window that invokes MinTTY
does not close.

What version of the product are you using? 

Tested on 0.3.3 and 0.3.4

On what operating system?

Windows 7 Beta, build 7000

```

Original issue reported on code.google.com by `erik.berglind.allemann@gmail.com` on 15 Jan 2009 at 10:26

Attachments:
- [mintty.jpg](https://storage.googleapis.com/google-code-attachments/mintty/issue-39/comment-0/mintty.jpg)

**Comment by mfriedemann** [comment]
That last comment was most helpful, but still only a workaround for the real issue.
As hinted to earlier in the thread, some change in behaviour has occured for console applications in windows. The eclipse launcher has handling for that as well, had to mess with that earlier.

Anyway, lots of other applications supply a $namew.exe with subsystem windows for that reason, so it would be nice to do this here as well.

**Comment by mintty** [comment]
The last comment is 4 years old. What's your mintty version? (Options - About)

**Comment by mfriedemann** [comment]
I am aware of that, but it's still a problem, despite all the efforts you guys put into it (yes, I read the old thread on the cygwin ML).
As for the version, I specifically updated the cygwin installation yesterday, to see if that changes anything, but it didn't. Version is now 2.7.6, IIRC (not at the machine ATM).

Anyway, the suggestion from the Tips section to use `start mintty -` in a batch file does not actually help (console stays open), but putting the cygwin-console-helper into bin does (although the window appears and is hidden straight away, so it flickers, as described in the ML thread).
Also, while it was stated in the ML thread that mintty is itself built as a win32 application, the version installed with cygwin does appear to be a console application.

FWIW, that is a Windows 7 machine, where I undertook it to put together a minified cygwin directory to have a decent shell with essentials that I can copy to other machines.

**Comment by mintty** [comment]
OK, as this issue is quite lengthy, I am not familiar with it, and the systems it's based on are quite old (the original post mentions Windows 7 *Beta*, which is yours? `winver`?), please describe your symptoms completely. And in fact use a standard cygwin installation, please. If "minified" means that you removed cygwin-console-helper on purpose, that is likely disturbing normal operation and not supported.

**Comment by mfriedemann** [comment]
Symptom: tip from the wiki to use `start mintty -` in a batch file does not actually help, if not used together with other workaround (ie: cygwin-console-helper).
No, it's not a beta version of Windows 7, but this was the first place that mentions the second prerequisite (again, cygwin-console-helper). Hence, my comment saying that tip was/is most helpful (and could maybe be added to the Tips section, maybe I'll make a pull request later).

**Comment by mintty** [comment]
"does not help" is not really a symptom, but anyway...
cygwin-console-helper may have been a workaround when it was introduced years ago,
but it's now really part of the cygwin base installation, so removing it is asking for trouble - which we had
