### ISSUE TITLE
Ctrl-click jump to file:line_number

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#391]
```
Hello everyone!

If would be great, if when Ctrl-clicking something like

C:\projects\a\main.c:999

the :999 is interpreted as a line number and passed to editor accordingly.

Thank you very much and
Have a nice day.

Eugene
```

Original issue reported on code.google.com by `evolei...@gmail.com` on 13 Jun 2013 at 6:34

**Comment by mintty** [comment]
As there is no common standard way of passing extra information to an invoked application (e.g. a line number), I don't see how this is feasible. The suffix (:999 or 999) could be placed in an environment variable before starting, but then the respective application would need to be aware of that and handle it.
Useful proposals will be considered.

**Comment by mintty** [comment]
Furthermore, while some editor share the command-line option +999 to select the line, Ctrl+click does not start an application that way, but rather like `cygstart` would do, using Windows associations.
No apparent way to pass on this information.
