### ISSUE TITLE
Mouse handling doesn't work correctly (Where PuTTY does)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#395]
```
What steps will reproduce the problem?
1. Open an SSH connection to a server with tmux
2. Enable mouse mode, with selection and scrolling in tmux 
3. Try to scroll
4. Garbage characters are outputted and actions don't behave correctly

What is the expected output? What do you see instead?

Mouse should scroll and screens should be reliably selected. Notably PuTTY 
(tested v0.62) works correctly and as expected.

What versions of mintty, Cygwin/MSYS, and Windows are you using?

mintty 1.1.3
Cygwin 1.7
Windows 8 x64

Please provide any additional information below.

Possibly related to xterm utf8 mouse handling, however explicitly enabling or 
disabling it in tmux simply results in different garbage characters.
```

Original issue reported on code.google.com by `clickher...@gmail.com` on 2 Jul 2013 at 12:17

**Comment by mintty** [comment]
1.7.35 is a cygwin version, not a mintty version.
Anyway, as discussed in #366, this is likely to be an interworking problem of tmux and cygwin, not mintty.
Also there have been recent fixes (again) in cygwin that might finally resolve the issue.
Or maybe not... But before reporting again, please cross-test with xterm. Also describe precisely how to reproduce (e.g. "Enable mouse mode, with selection and scrolling in tmux": how? - for non-users of tmux to be able to quickly reproduce.)
