### ISSUE TITLE
add the ansi escape sequence for keys reassignment

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#404]
```
google says that there is a special ansi sequense
<ESC>[{key};"{string}"p
https://www.google.com/search?q=ansi+escape+reassign+keys
http://www.termsys.demon.co.uk/vtansi.htm

but the mintty seems does not support this feature
imho it would be a useful feature
```

Original issue reported on code.google.com by `bdim...@gmail.com` on 28 Aug 2013 at 3:16

**Comment by mintty** [comment]
This is a control sequence from the MSDOS world (ANSI.SYS), not from the Unix tradition which typical terminal emulators follow. Neither xterm nor the original DEC terminals have that sequence.
Not considered useful in general for that reason.
