### ISSUE TITLE
Show current process name in title

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#409]
```
Terminal emulators like OS X's Terminal.app and Window's Console and Powershell 
would show the name of current running process in the title bar, I think mintty 
should also do the same.
```

Original issue reported on code.google.com by `zcb...@gmail.com` on 1 Nov 2013 at 2:27

**Comment by mintty** [comment]
This is not a typical function of other terminal emulators (with some exceptions as mentioned).
Also the shell is a layer between the terminal and the application and it is not genuine knowledge of the terminal which application is being started, thus it would be tricky (and likely error-prone) to achieve anything like that.
You might submit an enhancement request for a hook to achieve that in bash or other shells.
