### ISSUE TITLE
Italic escape code and Glyphs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#418]
```
Currently, I'm using IRC client in cygwin. I'm able to see bold but not italic 
messages.

- Is it easy to add Italic support?

- I searched the code and findout wintext.c has win_check_glyphs function. Is 
there any way to print glyphs in different font(Segoe UI Symbol)?

```

Original issue reported on code.google.com by `leventd...@gmail.com` on 24 Jan 2014 at 5:32

**Comment by mintty** [comment]
Added italic and strikeout character attributes.
About font changes, there is no standard or typical escape sequence to select a different font for individual characters, thus rejecting for now.

**Comment by mintty** [comment]
Releases 2.7.6.
