### ISSUE TITLE
Can't launch vim

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#423]
```
What steps will reproduce the problem?
1.launch vim
2.
3.

What is the expected output? What do you see instead?



What versions of mintty, Cygwin/MSYS, and Windows are you using?
mintty1.13 MSYS in the windows xp


Please provide any additional information below.

```

Original issue reported on code.google.com by `crystalf...@gmail.com` on 12 Mar 2014 at 2:02

**Comment by mintty** [comment]
works as expected

**Comment by mintty** [comment]
might have been an instance of the interworking issues between Windows applications and pty-based terminals, if a Windows command line vim was meant
