### ISSUE TITLE
readme-msys.html: tip for msys.bat 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#426]
```
MinGW/MSYS users should change the desktop shortcut to MSYS.bat, adding 
"--mintty" to the Target field

This isn't documented in the readme, I had to figure it out by reading the 
msys.bat file!

```

Original issue reported on code.google.com by `robert...@gmail.com` on 14 Apr 2014 at 2:42

Attachments:
* [MSYS.bat shortcut.png](https://storage.googleapis.com/google-code-attachments/mintty/issue-426/comment-0/MSYS.bat shortcut.png)

**Comment by mintty** [comment]
added hint, thanks
