### ISSUE TITLE
Is it possible to add setting for 'Treat CJK ambiguous characters as wide' as in putty?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#433]
```
I am ssh-ing into an ubuntu server with powerline installed. Meet the problem 
mentioned in https://github.com/Lokaltog/powerline/issues/107. The solution in 
putty is just enabling the option, but it is not exist in mintty now.
```

Original issue reported on code.google.com by `chinalu...@gmail.com` on 7 Aug 2014 at 3:24

**Comment by mintty** [comment]
Added hint to wike page "Tips".

**Comment by mintty** [comment]
The problem in that powerline issue was actually that this option was enabled (causing the effect) and the solution was to disable it. Which is the default in mintty anyway.
Also, while xterm has such an option, it is a legacy setting for use with certain CJK fonts. Mintty enables the according behaviour automatically if those fonts are used. I can hardly imagine why any user would want to enable the ambiguous-as-wide behaviour when not using such a font.
Therefore I'm closing this issue.

**Comment by mintty** [comment]
Actually, it's the locale setting rather than the font that triggers ambiguous width behaviour, see the hint mentioned above:
```LC_CTYPE=zh_SG.utf8 mintty &```

**Comment by mintty** [comment]
2.8.1 introduced option `Charwidth=ambig-wide`.
