### ISSUE TITLE
Please use DrawThemeTextEx when glass is enabled.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#438]
```
Please replace ExtTextOutW with DrawThemeTextEx when glass is enabled.
See
ExtTextOut function (Windows)
http://msdn.microsoft.com/en-us/library/dd162713(VS.85).aspx
and
DrawThemeTextEx function (Windows)
http://msdn.microsoft.com/en-us/library/bb773317(v=vs.85).aspx
```

Original issue reported on code.google.com by `march...@gmail.com` on 1 Dec 2014 at 8:33

**Comment by mintty** [comment]
There seems to be a hierarchy of APIs for text renderig, with increasing capabilities but also increasing complexity and insanity:
* DrawText (#438)
* ExtTextOut (currently in use)
* Uniscribe
* DirectWrite (#430)

As the DrawText API (of which DrawThemeText is an extension) apparently supports fewer features than now, especially concerning right-to-left display and Arabic shaping, I'm closing this issue.
