### ISSUE TITLE
Request configuration file item to exclude characters from word selection

### ISSUE THREAD

**Issue by totsubo** [mintty/mintty#450]
I'd like to request a way to exclude certain characters from word selection when double-clicking.

The already exists WordChars to add characters, a configuration item to excluded characters would be nice too.

For example in the in-house language we use, % is used quite a lot for exmaple, %VLAUE1%, and I would like to be able to tell mintty to only select VALUE1 when I double-click.

**Comment by mintty** [comment]
Added WordCharsExcl.
A solution with a WordCharsPattern regex would be preferrable but more effort...
