### ISSUE TITLE
Add default copy and paste shortcuts

### ISSUE THREAD

**Issue by paladox** [mintty/mintty#451]
Hi please fix copy and paste short cuts since you have to do ctrl + sift + ins key to paste. not sure about copy but paste should be ctrl + v and copy should be ctrl + c. the default windows keys.

**Comment by mintty** [comment]
^X/^C/^V are typically mapped to cut/copy/paste in *applications* but not *terminals*. Traditionally, terminals have to deliver control keys as they are precisely to make them available to the applications (e.g. your editor). Therefore, while this might be an individual preference, it is certainly not a fix and will never be the default.

**Comment by mintty** [comment]
Released 2.9.1.

**Comment by mintty** [comment]
Released 3.6.0.
