### ISSUE TITLE
Fix text selection

### ISSUE THREAD

**Issue by paladox** [mintty/mintty#452]
Hi please fix text selection since when you try for example use a mouse and try to get to a word to change or add you carnt it will only allow the keybord arrow keys to get to the text. please fix it since it is hard to get to text and makes it a lot slower using keybord to get to text.

**Comment by mintty** [comment]
Text selection works fine. Please describe your issue more clearly. Which application is involved?

**Comment by paladox** [comment]
Git for windows. I reported it to them which came back and said it  is mintty. And because git changed the text editor to yours for version 2 of the program. text selection works in git 1.9.5.

**Comment by mintty** [comment]
I don't know git for Windows. (I thought it would be a GUI git but maybe they have a command line version too.)
You need to provide sufficient information so the issue can be assessed. Please send a reference to the discussion you had with git for Windows. Which editor do you mean? And maybe a screenshot would help.

**Comment by mintty** [comment]
Closing for insufficient information. It's not a mintty issue just because someone (who?) says something (what?).
