### ISSUE TITLE
Update desgn

### ISSUE THREAD

**Issue by paladox** [mintty/mintty#453]
Hi please update the desgn since some of the colours make it look like a horrible ui for users. It should be updated with more modern colours and lighter colours including improvements to ui.

**Comment by mintty** [comment]
Assessments like horrible are not helpful.
Terminals are not particularly designed to be modern in the sense of fancy.
Also, which colours do you actually mean? The borders and menu appearance follows Windows desktop settings, so no specific design is applicable. The available text colour attributes follow a traditional standard and can be adapted to your preference, others have designed mintty colour themes already.
Rejected.
