### ISSUE TITLE
2.0.1 released on july 1

### ISSUE THREAD

**Issue by paladox** [mintty/mintty#457]
Hi in your release notes it says 2.0.1 was released on the first of july but in the release tab it shows last release as being 1.x.

**Comment by XVilka** [comment]
@paladox https://github.com/mintty/mintty/commit/8846c83003f4269b177281268b7d4d4386bbfb00

But you right, probably this release could be added in the 'releases' tab.

**Comment by paladox** [comment]
Thanks.

**Comment by mintty** [comment]
Not sure what you mean. The release repository has folders for older releases and the current one is on top level. I will publish the release on the cygwin mailing list as soon as I find the time for the cygwin upload. About MinGW, I don't know how to publish there.

**Comment by XVilka** [comment]
@mintty I'm sure he means presence here: https://github.com/mintty/mintty/releases

**Comment by mintty** [comment]
Being new to github, I had not noticed that feature yet... (and created a release repository instead)
Thanks.
