### ISSUE TITLE
Doesn't start up after upgrading to 2.1.2 in Cygwin 64bit

### ISSUE THREAD

**Issue by gm6** [mintty/mintty#465]
Doesn't start up after upgrading to 2.1.2 in Cygwin 64 bit under Win 7, while after going back to old 2.0.3, it works.

**Comment by gm6** [comment]
Btw it's under Win 7.

**Comment by mintty** [comment]
Hmm, I had thought 2.1.2 to be a hotfix for other crash reports.
Can you provide more details, please? How do you start mintty? Did you give it the -D parameter? Do you get a stackdump file?

**Comment by gm6** [comment]
Hi, I just double click the shortcut "Cygwin64 Terminal", and then no terminal pops up. There was indeed a stackdump file appeared on the desktop after the double click. Now I'm back to 2.0.3, it works like before.

**Comment by gm6** [comment]
Hi, I just upgraded w32api-runtime and w32api-headers, then 2.1.2 works now. Don't know if they are related. Never mind. Thanks!

**Comment by mintty** [comment]
As there was no problem with 2.1.2 for most people, this is still an obscure issue but could well be related.
Thanks for the report, I'll close the issue soon.
