### ISSUE TITLE
The best windows keyboard shortcut, win + shift + up, is broken by 2.1.1's "Drag resize" feature

### ISSUE THREAD

**Issue by codesmacgodes** [mintty/mintty#467]
Until I last updated mintty, win + shift + up would resize the window to vertically fill the screen without widening the window or changing the font size. This is a feature of Windows. It still works by the letter of the law, but "shift" is part of that keyboard shortcut, so now mintty increases the font size, which defeats the purpose of stretching it vertically.

I can still get the same effect by switching to the mouse and vertically resizing the window to the top of the screen, but if you can find a way to exempt windows key shortcuts from the new "shift resizes font too" rule, it would re-establish the value of that keyboard shortcut.

**Comment by mintty** [comment]
I wasn't aware of this shortcut. I had hoped the consistent meaning of Shift in this context is a good idea to be retained, and had wondered already if someone would complain about the changed behaviour of Ctrl+Shift+F (which can still happen).
Also it's perhaps not possible to distinguish all cases of external window management (like clicking the maximize corner) from each other. I could possibly offer an option to ignore Shift for external events. Unfortunately, in the current implementation, this would even affect Shift-Alt-Enter.
This is going to be a little bit tricky. Still pondering, suggestions welcome.

**Comment by codesmacgodes** [comment]
I'd be perfectly happy with an option to disable the ability to zoom and resize at the same time, altogether. The font is already so easy to resize with ctrl-mousewheel, as it is.

Truth be told, I might not have the most useful input because I don't really get the new feature. If it's supposed to be a true zoom rather than a resize, shouldn't the terminal aspect ratio (rows x cols) be locked? Unless I can mentally calculate what size it's going to look like and what's going to be pushed off the edge of the bottom or right of the viewable area, and that that is what I truly desire, 19 times out of 20 I'm still going to adjust the size with the mousewheel after it picks a new font size anyway. I don't really know what the use case is -- I can take it on faith that some people like to use it, but I can't put myself in their shoes and predict the utility of it. The only time I ever want to resize the font is when I'm trying to use a lossy screen sharing application like google hangouts and I need text big enough to withstand the JPEG artifacts, and that is just so rare for me, ctrl-mousewheel or even going into "options..." would be fine. 
I even have the other keyboard-based font zoom shortcuts disabled, and I don't even have a reason to disable them. No terminal app I'm aware of uses them (yet), but I wanted to leave the shortcuts available to the terminal apps, just in case.

Maybe a better condition on whether to enable this feature would be whether the mouse is being used at all.
For the benefit of keyboard shortcuts, I'd say that unless the other keyboard zoom shortcuts are enabled (allowing us to assume a zoom is fine), if anything at all other than shift is active on the keyboard, don't zoom.

**Comment by mintty** [comment]
Release 2.1.4

**Comment by codesmacgodes** [comment]
Thanks! It's working great.
