### ISSUE TITLE
Mintty 2.1.4 crashing with Windows 8.1

### ISSUE THREAD

**Issue by KptainBiwouak** [mintty/mintty#473]
Crashing issue with mintty 2.1.4 when starting from Cygwin 2.2.0 base (Windows 8.1 - OS:6.3)

PC is crashing immediately with following message: UnexpectedKernelModeTrap

Starting from tcsh xterm: no problem

**Comment by mintty** [comment]
I had asked for more information in response to your report on the cygwin mailing list but seen no resonse yet; since nobody else has reported this, further details are needed:

Asking Google, this error may be related to hardware or driver issues.
Does this command work?
  cp /bin/mintty /bin/mintty1
If so, does mintty1 then work?
Did you recently update drivers? Do you overclock your CPU?
Since nobody else is reporting this, I suspect it's a local problem. If for example it's a hard disk problem, it could well persist over multiple reinstallation of mintty versions...

**Comment by KptainBiwouak** [comment]
It's strange. By using same Cygwin revision 2.2.1 with latest mintty (2.1.5), it's crashing under Windows 8.1. By copying  ".exe" : same result. By using it from Windows 7, it's work.
When I replace latest release on windows 8.1, by old release (1.1.2), it's why I confirm there is an issue. I'm waiting for your guidelines if i can help to identify root cause for this issue...
I'll try to rebuild from scratch a full cygwin baseline if it can help.

**Comment by mintty** [comment]
So you have a dual-boot system with the same cygwin installation running either under Windows 7 or 8?
Can you try with a fresh (second) cygwin installation (base would be sufficient)?
Rebuilding cygwin will not be necessary but if you could rebuild different versions of mintty, from 1.1.3 to current (using binary search beginning with 2.0.3) from the sources at https://github.com/mintty/mintty/releases, and identify a version from which it starts to crash, we could analyse from there.

**Comment by KptainBiwouak** [comment]
The last mintty release which is running without any issue on both Windows 7 and Windows 8.1 is mintty 1.2beta1 (Cygwin base 2.0.2). 
Starting from release 2.x.y, all releasse I've tried are producing issue highlighted above on Windows 8.1  including latest mintty 2.1.5 (Cygwin 2.2.1). I guess since release 2.x and higher mintty is accessing a reserved area producing security issue or something like that explaining why PC turn off  UnexpectedKernelModeTrap. 
Anyway, by using same cygwin repository on WIndows7, I've seen no issue.
About my PC: 16GB Ram/ I7 / SSD 256Go / HD 2To / CPU 2.5Ghz

**Comment by mintty** [comment]
Thank you for testing. Did you also recompile 1.2beta1? Please try that.
Also, your Windows 8.1 and Windows 7 systems, are they on different machines? Or dual-boot on one machine?
If you install a fresh copy of cygwin (to target C:\cygwintest), what happens then?

**Comment by mintty** [comment]
As there is no further diagnostic input and noone else is reporting this, I am quite convinced you are having a local problem on your system. So I'll close the issue.

**Comment by KptainBiwouak** [comment]
Yes I confirm link between these 2 issues but also after having downloaded Rev 2.3.5. from Cygwin distribution 2.4.1, that my PC is still crashing.

If you have any idea about root cause, let me know I would try to investigate more. Thanks
