### ISSUE TITLE
Can't launch node process from Mintty

### ISSUE THREAD

**Issue by xiaoping378** [mintty/mintty#474]
![image](https://cloud.githubusercontent.com/assets/5623173/9519948/dd5b386a-4cf5-11e5-969a-a584470fe618.png)

**Comment by xiaoping378** [comment]
I found this:
https://github.com/joyent/node/issues/6459

**Comment by xiaoping378** [comment]
Running the below command in cmd.exe can resolve this issue.
"C:\Program Files\Git\bin\bash.exe" --login -i

**Comment by it3xl** [comment]
I have occasionally found that creation of **mintty.bat** helps
Just put it near to the **mintty.exe** at `C:\Program Files\Git\usr\bin`
with the next content
`mintty bash --login -i`
