### ISSUE TITLE
Remember last window location

### ISSUE THREAD

**Issue by petebachant** [mintty/mintty#477]
It would be great if the window could open in the same location it was when closed last.

**Comment by mintty** [comment]
Duplicate #273.
Also I don't intend to introduce a history which does not currently exist, sorry.
And how should multiple windows be handled?
There's one thing I could imagine: an option to *report* the final position when closing. So you could invoke mintty in a wrapper, save the position whereever you want and do with it whatever you like.

**Comment by mintty** [comment]
Option -R released in 2.2.1.
