### ISSUE TITLE
call mintty from batch

### ISSUE THREAD

**Issue by jb-alvarado** [mintty/mintty#479]
Hello,
long time I call (msys2) mintty from batch, like:
```
mintty.exe --log 2>&1 %instdir%\build\compile.log -i /msys2.ico /usr/bin/bash --login %instdir%\build\media-suite_compile.sh
```
This has work very good, but now the batch process don't stop anymore until mintty is done. It continue directly.

Is there a change in mintty what makes this impossible?

Regards,
Jonathan

**Comment by mintty** [comment]
Yes, mintty is now detaching itself from the caller if invoked from a console in order to ensure proper handling of signals.
You can disable that with option ```-d``` (cf. #466).

**Comment by jb-alvarado** [comment]
Ok, thank you for your answer! That helps us.
