### ISSUE TITLE
Division by 0 when starting on a second monitor (mintty -p@2)

### ISSUE THREAD

**Issue by rupor-github** [mintty/mintty#489]
On Windows 10 with MSYS2 it is not possible to start minnty on second monitor (High DPI monitors, not sure it is relevant though) due to the fact that font size for scale_font_with_size is calculated before term structure is fully initialized. Basically win_adapt_term_size( ,,, true) is being called on WM_DPICHANGED too early or out of expected order. Simple check prevents this from happening - I submitted pull request (sorry - did not notice "No unsolicited pull requests!"), so I am creating an issue to correct this. Could cancel pull if you prefer.

**Comment by mintty** [comment]
Patch applied, thank you. Does it happen with cygwin mintty on Windows 10 too?

**Comment by rupor-github** [comment]
"Does it happen with cygwin mintty on Windows 10 too?" - will have to install cygwin at work, will let you know.

**Comment by mintty** [comment]
Fixed in 2.2.2.
