### ISSUE TITLE
How to disable password enter popup?

### ISSUE THREAD

**Issue by chinhodado** [mintty/mintty#496]
When I need to enter a password, a popup appears. How can I disable that and just enter my password inside the terminal?

**Comment by mintty** [comment]
You do not provide the slightest information about the context and the symptoms of your problem.
Not possible to provide any hints this way.
Apart from that, mintty does not pop up any window in result of any application interaction.

**Comment by chinhodado** [comment]
Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/1388219/11320599/673712bc-906b-11e5-816a-9a62a461d008.png)

Maybe that's an OpenSSH thing?

**Comment by mintty** [comment]
Quite obviously. And maybe it's not even a bug, if either git or openssh decides to do it that way. In general, mintty has no influence on what the applications are doing.

**Comment by thybzi** [comment]
Please try the following:
```git config --global core.askPass ""```
Source: http://stackoverflow.com/a/34396983/3027390
