### ISSUE TITLE
Cygwin/mintty opens multiple times instead of refocussing

### ISSUE THREAD

**Issue by utereg** [mintty/mintty#499]
Hi,

After updating Cygwin around early November (and also just now), the mintty shows a new, unwanted behavior: when I open it through a Win7 shortcut (CTRL+ALT+D), it now opens multiple windows instead of refocussing to an already open mintty instance.

Is this maybe linked to isse #486?

Judging from a short Google search, I can imagine that some folks like this behavior, however, I would rather have it configurable.

Anything I can configure to get back to the old behavior (sorry, don't know which version I had installed previously)?

Thanks!

**Comment by mintty** [comment]
This behaviour apparently changed with release 2.1.1, so not related to issue 486.
You can prevent it with option `-d` (in the shortcut).

**Comment by utereg** [comment]
Excellent, thanks a lot for the quick help!
Is it maybe an idea to add a respective sentence like the one below to the "-d"-description on the man-page? Even with somewhat of a technical background, I didn't make the link between nodaemon and my problem :)

"This option also prevents mintty from opening multiple instances/windows when invoked through a shortcut."

**Comment by mintty** [comment]
Sure, I only discovered this myself a few minutes ago...
Also there is already a change for the next release that may make this option unnecessary again, we'll see.

**Comment by mintty** [comment]
Released option `-D` in 2.2.3.
