### ISSUE TITLE
Transparency Enhancement

### ISSUE THREAD

**Issue by jbisbee** [mintty/mintty#501]
I'd like to ask for an enhancement to the background transparency.  In iTerm 2 on OSX they not only allowed for transpaency, but also allowed you to "blur" the transpancy as well.  This allowed for a great affect for coding windows as you could blur as little or as much as you wanted and the transparency would not affect code windows (vim/etc) when they stacked.

**Comment by mintty** [comment]
Not sure what you mean; some screenshots maybe?
Also, do you have the Windows knowledge to implement such stuff?

**Comment by jbisbee** [comment]
https://www.iterm2.com/documentation-preferences.html (CTRL+F "Blur").  I'll post screenshots from OSX later this evening.  And no, I presently don't have the knowledge, but it would be interesting to look into it.

**Comment by jbisbee** [comment]
Maybe something. https://msdn.microsoft.com/en-us/library/windows/desktop/aa969537(v=vs.85).aspx#blurbehind

**Comment by mintty** [comment]
I've added experimental blur-behind support. However, I don't see any positive effect in testing. On some systems, there is a very bad effect (big streaks over screen), on some there is no effect at all, on some the option also enforces glass background and not much more, where glass background implies blurring even without the option.
Please check (-o Blur=yes) with the current archive (Download ZIP button), but unless someone comes up with a working patch, I won't release the option.

**Comment by jdmansour** [comment]
Hi all,
I've been working a bit on this, and I got transparency with blur-behind working on Windows 7 and 10 (and Windows 8 if you use [AeroGlass](http://www.glass8.eu/)) in my fork ([jdmansour/mintty](https://github.com/jdmansour/mintty)):

![Screenshot](https://raw.githubusercontent.com/jdmansour/mintty/glass/wiki/screenshot.png)

The default background color is partially transparent, while the foreground and the other background colors are opaque, as well as the title bar.

On Windows 10, I'm using the undocumented SetWindowCompositionAttribute (which Windows itself uses to blur behind the start menu), and on older Windows versions DwmExtendFrameIntoClientArea. The trick is to ensure that everything gets drawn with the correct alpha channel. It is not easy since plain GDI does not know about alpha.

I think this branch would need a bit of work before merging. The drawing code is a bit messy since I have to work around GDI's limitations. There are some small visual artifacts and it is not as performant as regular mintty. However it is already quite stable and pretty, and I've been using it daily for a while, so I thought I might share it.

**Comment by mintty** [comment]
Thanks for this contribution, to be checked.
So I understand it would only work on Windows 10?
Do you see any relation to issues 438 and/or 430?
An undocumented API? Do you trust in it being maintained?

**Comment by jdmansour** [comment]
Hi, this has multiple parts:
- Drawing with the correct alpha channel: This is the biggest part, and greatly improves glass transparency on Vista, 7, 8 and 10. This solves the problem mentioned in #438. However, I don't use DrawThemeTextEx, but created a wrapper around ExTextOutW that draws with the correct alpha channel. The main reason is that the API is quite different, and I couldn't get DrawThemeTextEx to work properly. This code is in wintext.c ([MyExtTextOutW](https://github.com/jdmansour/mintty/blob/glass/src/wintext.c#L761) and [win_paint](https://github.com/jdmansour/mintty/blob/glass/src/wintext.c#L542)).

  There is actually some commented for DrawThemeTextEx in there, if someone wants to give it a try.

- Issue #430 (DirectWrite support) is not addressed

- The undocumented API is also used by [EarTrumpet](https://github.com/File-New-Project/EarTrumpet). I believe it will be supported in the near future, at least as long as the start menu can be transparent. I load it lazily via `load_sys_library` and only use it on Windows 10.

**Comment by mintty** [comment]
@jdmansour, please see https://github.com/mintty/mintty/pull/661#issuecomment-304834137

**Comment by Yamakuzure** [comment]
Hello everybody.

Are there plans to fix this for Windows 10? Currently "glass" looks like this on my system:

![mintty_glass_01](https://user-images.githubusercontent.com/1118655/39304857-6fbbe132-495b-11e8-91cb-6555642c0d7d.png)

(At least there is a glassy edge around the window, where the shadow should've been...)

Unfortunately I have no idea how to fix this.

My System:
Intel Core i7-6700@3.4MHz, 32GB RAM, AMD FirePro W4100
Windows 10 Pro x64, Version 1709, Build 16299.125

**Comment by Neo-Oli** [comment]
@Yamakuzure I have this too. Restarting mintty after making the settings change helps in my case.

**Comment by Byloth** [comment]
@Neo-Oli, yeah... That's correct!

As you say, after a mintty restart this is what you get (before and after): 

![example](https://user-images.githubusercontent.com/14953974/39307229-8db27500-4962-11e8-853f-bd89bb899e54.png)

But I don't think so that **THIS** is what we want... 

---

I hope that the final result will be as near as possible to the screen posted by @jdmansour some time ago...

**Comment by mintty** [comment]
> But I don't think so that THIS is what we want...

What can I do if you don't even know what you want...:)

> I hope that the final result will be as near as possible to the screen posted by @jdmansour some time ago...

Which is quite the same, except the title, right?
For me, it looks the same on a Windows 7 system, and updates immediately. On another system, however, there was some trouble...

**Comment by Yamakuzure** [comment]
Thank you all, but I "_fixed_" it:

![mintty_glass_02](https://user-images.githubusercontent.com/1118655/39318641-ef03c1d0-497e-11e8-9cd4-948341a25980.png)

All I had to do was to Install [Aero Glass for Win8.1+ v1.5.8](http://www.glass8.eu/download) and use [Winaero Tweaker](https://winaero.com/download.php?view.1796) to enable "_Aero Lite_" and "_Colored Title Bars_".

Before these tweaks, restarting MinTTY, not even restarting Windows, changed anything. The window stayed being snow white.

**Comment by mintty** [comment]
I can hardly believe it should be necessary to add third-party software from obscure download sources in order to make a Windows feature work. Sorry, but I don't think I'll add that to the Wiki.

**Comment by Yamakuzure** [comment]
> I can hardly believe it should be necessary to add third-party software from obscure download sources in order to make a Windows feature work.

Well, without "Aero Lite", which is already there but disabled by default, that Windows feature is simply not available but for the task bar and the start menu. However, the _obscure_ Winaero Tweaker does nothing more than changing settings, mainly through the registry, that you can change by hand, as well. It is all documented on their site.

As for "_Aero Glass_", I do not think that this is exactly necessary. It just adds a Theme that utilizes Direct3D to add a Glass effect to the title bars of regular windows. Doesn't work on non-regular ones, like Firefox, though. It's the second best way to get glassy looks back after having Microsoft to fully add Aero back. Which they might never do, no matter how many people complain.

> Sorry, but I don't think I'll add that to the Wiki.

I never asked you to...

Those are mere hints and leads. I have no idea where they lead to, or whether they are helpful at all. But fact is, that the Glass effect does not work ootb for me, and maybe others. If the description of what I did helps at least one other visitor searching for a solution, it's fine for me. You do as you see fit. ;-)

**Comment by mintty** [comment]
Sure, I didn't mean to question the information you added here as such. I just wanted to state that it does not help to make progress with this as a mintty issue. Which is unfortunate. If someone finds out how to enable that Aero feature (and its usage by mintty) with Windows on-board means, that would help us further.

**Comment by Yamakuzure** [comment]
Yes, of course.

Unfortunately I am completely at sea here.

I did some more experiments:
 - I deactivated the Aero Lite Theme, stopped the "Aero Glass" services and logged out and back in. The result was what I had before, a pearly white window.
 - I then switched back to the 'Aero Lite' theme, and the window became my tint color. Opaque, no glass effect, but I could at least read text again.
 - After a reboot the 'Aero Glass' service was back running, and now I have a glassed window in my tint color back.

I know that this is not perfect, and possibly no help at all. However, I have the looks from my first screenshot (the green one) back, and am rather happy with that.

However, I *might* be ably to provide a clue that _could_ be helpful after all:

To have this beautiful green window, I have unchecked "_Opaque when focused_".
 Result: The green tinted glassy window from my first screenshot.

When I then restart Mintty, the window is suddenly colorless, like in the second screenshot.
  Fix: Enable "_Opaque when focused_" -> "_Apply_" -> Disable "_Opaque when focused_" -> "_Apply_".

I think that the influence this option actually has on the application of the glass effect, might be worth investigating.
And it gave me another hint:
  Maybe I was too quick re-enabling the "Aero Glass" service and the "Aero Lite" theme back. So I will experiment some more and then edit this comment with the results.

**Comment by mintty** [comment]
Is this still an issue? Intending to close...

**Comment by Byloth** [comment]
Yes... This is still an issue.

Actually, I'm using Mintty 2.9.0...  
I noticed that Mintty 2.9.1 is now available but I didn't see any details about this ticket in [Release notes](https://github.com/mintty/mintty/releases/tag/2.9.1).

Has this ticket been solved in Mintty 2.9.1?
Can anyone tell us if this is still a problem even in Mintty 2.9.1 or not?

**Comment by mintty** [comment]
> Has this ticket been solved in Mintty 2.9.1?

No, I was just grooming old open issues...

So I'll keep the issue open for quite another while, but for any progress I'd expect that
* maybe someone describes the desired enhancement, again and in clear terms
* someone provides a patch that has a demonstrable benefit that I can verify, and
* both the patch and the demo work with Windows on-board means (i.e. without 3rd-party stuff)

**Comment by gyroknight** [comment]
Right now, the glass effect seems be limited to one global setting, where you either have white glass on everything or not. This works when the background is dark:
![image](https://user-images.githubusercontent.com/8902299/46912666-9f7afd80-cf49-11e8-9434-68bcee5f1b3e.png)
however, it makes the window very hard to use on lighter backgrounds:
![image](https://user-images.githubusercontent.com/8902299/46912676-ce916f00-cf49-11e8-98c9-5a57d7baa496.png)

I think the blur itself is fine, however, I'd love to see a way to control the tint of the window so that the background could be darker for better usability. I also think only changing the opacity of the background and keeping the text opaque would be a huge improvement from a usability standpoint.

Windows 10 has a built-in effect called Acrylic that might work, but it's only for UWP and might require too many changes to the rendering engine to be feasible. Here's the documentation and a potential mockup though, in case you want to take a look.

![image](https://user-images.githubusercontent.com/8902299/46912708-3e542980-cf4b-11e8-9b25-c6da8063282c.png)

https://docs.microsoft.com/en-us/windows/uwp/design/style/acrylic

**Comment by mintty** [comment]
> a way to control the tint of the window so that the background could be darker

Sure, if someone demonstrates how to achieve this.
Alternatively, it would be good to have a reliable way to extract the actual background image from Windows, so mintty could use it as background and manipulate it for that purpose as it likes.

> keeping the text opaque

? From your screenshots, it looks as this is the case already, isn't it?

> Acrylic ...

Well, again, the referred documentation might give some clue but not a clear recipe how to use this feature for a desktop window. So if someone likes to spend some months of investigation to craft such a feature...

**Comment by mintty** [comment]
It's hard to see text transparency, even at larger zoom, but in the lighter background image, the top-left digits 3, 4, 5 are obvious (4 with a white spot on top), and bottom-right the i of "unix" and final p of "cpp" stand out brightly.

**Comment by Avelina9X** [comment]
![image](https://user-images.githubusercontent.com/37878580/47877928-fec78180-de14-11e8-8b32-73c6c7f0668d.png)
 Side by side comparison. Unusable on lighter backgrounds. Text is transparent. Title bar is white. very sad considering otherwise it looks very pretty with glass.

**Comment by mintty** [comment]
"Glass" mode has never really worked for me. Simply don't combine it.
As a suggestion, you may also dim wallpaper background, like other image background:
`Background==,99`

**Comment by mintty** [comment]
Released 2.9.4 with option `Background==`.

**Comment by mintty** [comment]
I came across this pretty old patch (https://github.com/jdmansour/mintty/commits/glass) which had been hiding in the corner of my drawer..., sorry.
It turns out that suddenly this appears to work for me. Weird. Anyway, I'm considering to reintegrate the patch into the current master version.

**Comment by mintty** [comment]
I have to revert my previous comment. This patch does not work properly on Windows 10.

*“Just give up on glass effects. Microsoft clearly have.”*

https://stackoverflow.com/questions/31768259/what-is-the-replacement-for-drawthemetextex-on-windows-8-and-10

**Comment by mintty** [comment]
Released 3.1.5; deprecated the non-functional glass mode from the Options dialog.
