### ISSUE TITLE
Color setting doesn't work

### ISSUE THREAD

**Issue by dcbrwn** [mintty/mintty#502]
I tried to specify color scheme in *rc file and using escape sequences but only background, foreground and cursor colors are changing. I'm using mintty bundled with cygwin. Version 2.2.2 x86_64-pc-cygwin. Windows 10

**Comment by dcbrwn** [comment]
here is my .minttyrc

```
ZoomFontWithWindow=false
BoldAsFont=no
Columns=80
Rows=25
Font=Lucida Console
Transparency=off
OpaqueWhenFocused=no
CursorType=line
CursorBlinks=yes
FontSmoothing=full
Locale=en_US
Charset=UTF-8
ScrollbackLines=99000
ScrollMod=shift
PgUpDnScroll=yes
Term=xterm-256color
CopyAsRTF=no
RightClickAction=paste
FontHeight=12
ForegroundColour=131,148,150
BackgroundColour=0,43,54
CursorColour=220,50,47
Black=7,54,66
BoldBlack=0,43,54
Red=220,50,47
BoldRed=203,75,22
Green=133,153,0
BoldGreen=88,110,117
Yellow=181,137,0
BoldYellow=101,123,131
Blue=38,139,210
BoldBlue=131,148,150
Magenta=211,54,130
BoldMagenta=108,113,196
Cyan=42,161,152
BoldCyan=147,161,161
White=238,232,213
BoldWhite=253,246,227
```

**Comment by mintty** [comment]
Works fine here with your .minttyrc, see screenshot (foreground/background overridden by shell).
![502](https://cloud.githubusercontent.com/assets/12740416/11658249/f1a08880-9dc1-11e5-9c50-1e22ff318833.png)

**Comment by dcbrwn** [comment]
Odd. Maybe default cygwin installation has config with overrides somewhere?

**Comment by mintty** [comment]
Or maybe you're not loading the intended .minttyrc? Have you tried with an explicit `-c` option?

**Comment by dcbrwn** [comment]
Well all options including foreground and background colors are actually loaded from .minttyrc. I have tried to pass config to mintty, but this doesn't help.

**Comment by mintty** [comment]
Puzzling.
If you `cat $HOME/.minttyrc` (or whichever), then `mintty -c $HOME/.minttyrc` from the command line, are there any error messages?

**Comment by dcbrwn** [comment]
```
danila.shutov@o109 ~
$ echo $HOME
/home/danila.shutov

danila.shutov@o109 ~
$ pwd
/home/danila.shutov

danila.shutov@o109 ~
$ cat $HOME/.minttyrc
ZoomFontWithWindow=false
BoldAsFont=no
Columns=80
Rows=25
Font=Lucida Console
Transparency=off
OpaqueWhenFocused=no
CursorType=line
CursorBlinks=yes
FontSmoothing=full
Locale=en_US
Charset=UTF-8
ScrollbackLines=99000
ScrollMod=shift
PgUpDnScroll=yes
Term=xterm-256color
CopyAsRTF=no
RightClickAction=paste
FontHeight=12
ForegroundColour=131,148,150
BackgroundColour=0,43,54
CursorColour=220,50,47
Black=7,54,66
BoldBlack=0,43,54
Red=220,50,47
BoldRed=203,75,22
Green=133,153,0
BoldGreen=88,110,117
Yellow=181,137,0
BoldYellow=101,123,131
Blue=38,139,210
BoldBlue=131,148,150
Magenta=211,54,130
BoldMagenta=108,113,196
Cyan=42,161,152
BoldCyan=147,161,161
White=238,232,213
BoldWhite=253,246,227

danila.shutov@o109 ~
$ mintty -c $HOME/.minttyrc

```

Also tried to run mintty from cmd with different paths to .minttyrc (/c/cygwin64/home/user/.minttyrc, C:\cygwin64\home\user\.minttyrc, ~/.minttyrc)

**Comment by mintty** [comment]
As this works in general and I cannot reproduce your issue, it is hard to debug remotely.
One more attempt: Please send your .minttyrc as attachment (not inline), your testcase (e.g. file you output to display colours) and a screenshot.

**Comment by dcbrwn** [comment]
![image](https://cloud.githubusercontent.com/assets/12214069/11685456/295627bc-9e8a-11e5-983d-dbd86ed0c401.png)

[.minttyrc.txt](https://github.com/mintty/mintty/files/56769/default.minttyrc.txt)

By the way a miracle just happened. I tried to reset terminal with good 'ol `reset` command and colors cheme changed correctly O_o

P.S. GitHub declined to upload .minttyrc so i added .txt extension

**Comment by dcbrwn** [comment]
Same color scheme was defined using escape sequences in my .bashrc. I commented them and trick with `reset` stopped to work.

**Comment by mintty** [comment]
That might be a hint; could you attach your .bashrc as well (stripped down if it contains much personal stuff...)?

**Comment by dcbrwn** [comment]
Somehow it started to work. I guess this wasn't issue with mintty itself. Attached .bashrc is pretty default one. Hope it helps.

[.bashrc.txt](https://github.com/mintty/mintty/files/56850/default.bashrc.txt)

**Comment by mintty** [comment]
There is an escape sequence that would reset the palette: echo -e '\e]R'
Maybe that got somehow output to your terminal?
Anyway, shall we close the issue?

**Comment by dcbrwn** [comment]
Yes, of course.
