### ISSUE TITLE
CTRL+minus/plus does not work with ZoomShortcuts=no

### ISSUE THREAD

**Issue by maonx** [mintty/mintty#506]
When I set `ZoomShortcuts=no` in `.minttyrc`, Keymap `CTRL+minus/plus` not work in Vim.

**Comment by mintty** [comment]
Sure. That's the purpose of that option, as described in the manual. What did you expect?

**Comment by maonx** [comment]
When I set `ZoomShortcuts=no`, I wanna use my own keymap `CTRL+minus` in vim.  Is it conflict?

**Comment by mintty** [comment]
Misunderstood.
Here it works like this: `mintty -o ZoomShortcuts=no`, in the shell type `Control+V` then `Control+-` and the shell will echo the escape sequence `^[[1;5m`. You could map that in vim. However, xterm sends a different sequence in application keypad mode: `^[O5m`. Maybe mintty can change that.

**Comment by maonx** [comment]
Thanks,it is `^[[1;5m]` and map in vim.

**Comment by rdeforest** [comment]
Clarifying for the purposes of some day closing this issue:

User was looking for a way to re-assign mintty font size change keys for use in vim. User assumed ZoomShortcuts=no would enable this but didn't know how to also determine and re-map the character sequence generated by the keys after they were unbound from the zoom feature.

Requestor's issue is resolved, but question remains as to whether proximate documentation of ZoomShortcuts is sufficient.

(My advice: resolve as not-an-issue.)

**Comment by mintty** [comment]
It turns out in this issue that mintty does not send the same sequences as xterm or DEC terminals would in application keypad mode. I left the issue open because I'm considering whether to change that.

**Comment by mintty** [comment]
Release in 2.3.7.
