### ISSUE TITLE
"There is no font with that name" - but the font exists

### ISSUE THREAD

**Issue by DanielGGordon** [mintty/mintty#507]
Below you can see the error message. This is occuring in all my instances of Mintty (I have 3x - one for Git Bash, one for Babun, and a portable version of Git Bash).

So even though I installed these fonts, Mintty is telling me they don't exist. 

So I deleted them all via the control panel. Then I went back to Mintty, and the fonts still exist. Re-installing seemed to have no effect.

![image](https://cloud.githubusercontent.com/assets/11824880/11967041/71cf640a-a8c5-11e5-9c30-2b5db82f43c8.png)

**Comment by mintty** [comment]
Are they freeware fonts? Can you send a link to them?

**Comment by DanielGGordon** [comment]
So I was able to get rid of them from the menu after restarting my computer.

I then tried to add the fonts (manually, one by one). 

The fonts now show up in Babun (or anything that uses Mintty), but I now get the same error again.

These are [Powerline patched fonts](https://github.com/powerline/fonts), specifically, the Meslo family of fonts.

**Comment by mintty** [comment]
The names of these fonts are very long and weird, like `Meslo LG L DZ for Powerline RegularForPowerline`. The font doesn't work with a command-line option `-o Font=...` either, but without error message. The error popup is not generated by mintty.
With these observations, my current assumption is that some Windows component has a limit for font names.

**Comment by DanielGGordon** [comment]
Yes this has to do with name length of the font. Closing.

**Comment by mintty** [comment]
Well, `mintty -o Font="Meslo LG L DZ for Powerline"` works,
so actually it doesn't seem to be the length limit (which is 32) but the weird fact that the name used to present the font in the font selection menu is longer than the name used to select the font.
However, the font selection menu is handled by Windows (ChooseFont), not mintty.

**Comment by mintty** [comment]
It turns out that, with some new handling of the font selection menu, the Meslo fonts can be selected, but only with the new Apply button within the font selection menu.

**Comment by mintty** [comment]
Released a number of font selection problems in 2.2.4 although not particularly this one; but those fonts can now be selected with the new Apply button.

**Comment by exhuma** [comment]
FWIW, I found out that the names shown in Windows are quite inconsistent. The file-name does not correspond to the name listed in the "Fonts" window of windows, which in turn does not correspond to the font name stored in the TTF file(?), so knowing which one to use is a bit of guesswork.

After a bit of fiddling around with various settings, I found that the name which works for the `Font=...` setting in mintty is the one shown in the font detail window:

![image](https://user-images.githubusercontent.com/65717/35099183-58700f40-fc57-11e7-9329-b592a6d3c6f6.png)

**Comment by mintty** [comment]
My rule of thumb was to use the listed font name ("mononoki NF Regular" above) and leave out generic style suffixes ("Regular"), but that's a bit fuzzy.
Thanks for identifying this proper association, I should mention it on the wiki Tips page.

You may also be interested in the following:
For font families with unusual style sets, especially more than 4 styles, the Windows font chooser ("Font" - "Select...") is not capable to offer proper selection. In this case, however, the mintty built-in font menu helps out at is distinguishes them all. Option `-o FontMenu=0`; example Iosevka.

**Comment by exhuma** [comment]
@mintty as an addendum to my post, it seems this name does *not* work when using `.minttyrc`. Specifying that name in the `-o Font=` option works however!

**Comment by mintty** [comment]
Please check the exact spelling; trailing space is significant.

**Comment by mintty** [comment]
`Font=mononoki NF` in .minttyrc works fine here.
