### ISSUE TITLE
is there a way to add margin to window inner edge?

### ISSUE THREAD

**Issue by solor** [mintty/mintty#511]

**Comment by mintty** [comment]
No. But there is a static value for this already which I could make configurable if you motivate why a larger margin would be desirable.

**Comment by solor** [comment]
iterm has this setting so just become personal preference i guess, 
please make it happen :boom:

**Comment by mintty** [comment]
Please test the current patch (e.g. -o Padding=5). Note that it limits actual padding to the current character cell width.

**Comment by Winneon** [comment]
Works great for me! Thank you for adding this option in!

**Comment by mintty** [comment]
Released in 2.2.3.

**Comment by airstrike** [comment]
time to update mintty, I guess!

**Comment by ArtistsTechGuy** [comment]
@mintty Would it be possible to add only horizontal/vertical padding control, perhaps I just missed the setting?  (e.g. -o HPadding=5)

**Comment by mintty** [comment]
Why would you want that? I'd prefer to limit mintty to a comprehensive set of generally useful options, and not add hundreds of fine-tuning options for virtually everything.

**Comment by ArtistsTechGuy** [comment]
@mintty When looking to add a bit of padding away from the edge of the bezel of my monitor I found I was losing too much working area with the loss in height.  As most monitors now are 16:9 padding the width often makes reading more comfortable without losing functionality.

**Comment by mintty** [comment]
You could move the text away from the screen border by placement of the whole window, perhaps?
(Not yet really understood the use case.)
