### ISSUE TITLE
Failed to run C:\PROGRA~2\RATIONAL\RATION~1\NUTCROOT\mksnt\sh.exe: No such file or directory

### ISSUE THREAD

**Issue by dili19** [mintty/mintty#512]
I install this cgywin Program trice but still I can't acces it Properly due to this error

**Comment by mintty** [comment]
Your report is so sparse that I have no idea what to say...
What program did you install?
What is the invocation causing the error? (Command-line inside mintty?)
Where is the error reported? (Popup? Inline?)
Some minimal context of your problem is necessary or I can do nothing but close the issue.

**Comment by dili19** [comment]
this error showed in the Command  Line 
I  installed thses programs:
Binutils
cloog-isl
Cygwin
Gcc
Gdb
Libargp
Libargp
w32api-headers
w32api-runtime
windows-default-manifest

**Comment by mintty** [comment]
You are not saying *when* the error occurred, what command etc.
In any case, I don't see how this should be related to mintty. Please test with another terminal (Cygwin console, running C:\cygwin\Cygwin.bat, rxvt, xterm, ...) and you'll likely see the same thing happens.
Closing.
