### ISSUE TITLE
Control+Shift+<Character> inputs 'odd' characters

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#513]
For example pressing Ctrl+Shift+L and hitting enter will show:
```sh
-bash: $'\302\214': command not found
```
The setting `Ctrl+Shift+letter shortcuts` seems to have an effect on *some* of the keys, *enabling* it seems to make it go away.

But for example for the Enter key *isn't* affected by this setting and always outputs:
```sh
-bash: $'\302\236': command not found
```

I'm not quite sure what these characters are doing, but it does seem to only happen inside mintty, and it causes me to type commands wrongly often.

**Comment by mintty** [comment]
By default, Ctrl+Shift combinations send character codes in the "C1" range, as documented in https://github.com/mintty/mintty/wiki/Keycodes, sections "Ctrl" and "Special keys". This has been mintty behaviour since 0.6.1.

**Comment by mintty** [comment]
Unless someone asks this to be changed (optionally...), I'll close the issue.
