### ISSUE TITLE
[SHIFT]+[INSERT] does nothing in Windows 10

### ISSUE THREAD

**Issue by scovich** [mintty/mintty#514]
After upgrading from Windows 7 to Windows 10, I find that I can no longer paste in mintty using [SHIFT]+[INSERT] shortcut. The shortcut still works in native apps, and I can still right click and select "paste" from the context menu (which, still says the shortcut key should work). 

I'm running mintty-2.2.2-0, the latest version cygwin's setup.exe offers.

**Comment by mintty** [comment]
Can anyone confirm this? Maybe some context it depends on? As I don't have access to Windows 10 right now, I cannot reproduce the issue. Is Shift+Insert perhaps a new Windows shortcut key?

**Comment by thasmo** [comment]
Running `mintty 2.2.3 (x86_64-pc-cygwin)` and pasting using `shift + ins` works.

**Comment by scovich** [comment]
False alarm, turns out the upgrade from win7 to win10 messed up my custom settings that made [INS] work right on my funky keyboard. I didn't realize that was the issue at first because [INS] still worked for non-cygwin apps for some reason.
