### ISSUE TITLE
   Pause/Break doesn't seem to work

### ISSUE THREAD

**Issue by cnervi** [mintty/mintty#515]
mintty 2.2.2 - MSYS2 - windows 10 64bits

using:
stty susp '^]'
stty swtch '^]'
stty intr '^\'

and pressing Pause/Break doesn't work,  had to explicitly set:
Pause=^]
Break=^\

in my minttyrc to get it working

Not sure if has something to do but I'm using a 105 key Spanish keyboard with an US layout - the 'extra' key works as a duplicate of the \ key, using Ctrl+\ (with any of those 2) works as expected but Pause and Break won't do anything unless set in minttyrc

**Comment by mintty** [comment]
Sorry this was broken. It will be fixed and released soon.

**Comment by cnervi** [comment]
ok :(, thank you

**Comment by mintty** [comment]
Released in 2.2.3.
