### ISSUE TITLE
python blocks when launched in git-bash. #critical

### ISSUE THREAD

**Issue by jmagosta** [mintty/mintty#516]
Launching python from the prompt hangs, with no response.  This is true for both the Anaconda, version 2.7.11 and the vanilla python 3.5.1 from python.org. `python.exe` and `pythonw.exe` fail in the same way.  Running python -v shows the sequence of imports, but halts partway through printing to the console.  The error is not reproducible with cmd, PowerShell or other shells, such as the `win-bash` port.

**Comment by elieux** [comment]
I think this is another case of #56. Note that mintty is *not* a shell, it's a terminal emulator. Use `winpty python` or `python -i`.

**Comment by mintty** [comment]
... and, more specifically, of #503.
See there for hints. Closing.
