### ISSUE TITLE
Add hint/link to Github on the old Google Code page

### ISSUE THREAD

**Issue by bohni** [mintty/mintty#518]
Web search engines sill list the old page https://code.google.com/archive/p/mintty/ 

A link to the new home can only be found in the issue https://code.google.com/archive/p/mintty/issues/446

So it would be good to insert the link to Github also on the old homepage.

This issue is related to https://github.com/mintty/mintty/issues/446

**Comment by mintty** [comment]
Although this is technically not an issue against this repository :/ it is a valid point.
However, Google code is closed for any modifications so there is no way to get that done, sorry.
