### ISSUE TITLE
Vim and MinTTY?

### ISSUE THREAD

**Issue by zQueal** [mintty/mintty#522]
I'm trying to get MinTTY to launch Vim (cli) but I can't seem to get it. I tried navigating directly to the `Program Files` folder, but no such luck. It seems to hang on launch. I can launch `gvim.exe` right from MinTTY without issue.

Adding commands seems to be pretty difficult. I ended up creating a `C:\Utilities` folder which is added to my windows `%PATH%` -> `$PATH` which contains;

    #!/bin/bash
    "C:\Program Files\Vim\vim74\vim.exe" "$@"

Is there an easier way to do this? Setting up an alias is fine, but what if I need to pass arguments to Vim?

**Comment by mintty** [comment]
Adding commands is not related to mintty, rather to the shell you are using; e.g. if you run mintty with a cygwin environment, it's all following POSIX/Unix tradition.

About vim, the path you mention suggests you are not using a POSIX version of vim, rather a native Window version, intended to run in a Windows console. Thus this is another instance of the pty incompatibility problem, esp. #230.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
