### ISSUE TITLE
Consider adding XDG Base Directory support for minttyrc

### ISSUE THREAD

**Issue by sirblackheart** [mintty/mintty#525]
It would be nice if mintty would add support for the XDG_CONFIG_HOME location as defined in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/) which should default to HOME/.config/ if not set.
So basically mintty should looking for a XDG_CONFIG_HOME/mintty/config before looking for ~/.minttyrc

**Comment by mintty** [comment]
Although the cygwin installation of mintty supports an xdg menu entry already, I am not aware that XDG is wide-spread. Which similar applications use that configuration? Any terminals?
Would `$XDG_CONFIG_HOME/mintty/config` be the name of the config file or a folder for `.minttyrc`? Where in the spec is this defined?

**Comment by sirblackheart** [comment]
XDG Base directorys usage has become more widely spread. For a short overview you of some application support  the [arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) is a nice source.
In $XDG_CONFIG_HOME/mintty/config config would be a file and mintty the subdir as specified in point two. But config is just an example for the config file name. Git uses it. The filename could stay minttyrc, or .minttyrc.
> Specifications may reference this specification by specifying the location of a configuration file as $XDG_CONFIG_DIRS/subdir/filename. This implies that:
> - Default configuration files should be installed to $sysconfdir/xdg/subdir/filename with $sysconfdir defaulting to /etc.
> - A user specific version of the configuration file may be created in $XDG_CONFIG_HOME/subdir/filename, taking into account the default value for $XDG_CONFIG_HOME if $XDG_CONFIG_HOME is not set.
> - Lookups of the configuration file should search for ./subdir/filename relative to all base directories indicated by $XDG_CONFIG_HOME and $XDG_CONFIG_DIRS . If an environment variable is either not set or empty, its default value as defined by this specification should be used instead.

**Comment by mperry2** [comment]
I'd also like to see support for this. I'd prefer `$XDG_CONFIG_HOME/mintty/config` as the config file so my home directory isn't cluttered with so many dotfiles.

**Comment by mintty** [comment]
I plan to support `$XDG_CONFIG_HOME/mintty/config` with a fallback to `$HOME/.config/mintty/config` as specified. However, if `$HOME/.minttyrc` exists, too, which one should get precedence? I don't see a comment on that in the XDG specs. Furthermore, considering #201, I'm considering to also support `$APPDATA/mintty/config`. Which should be the order of precedence then?

**Comment by sirblackheart** [comment]
Git reads from all of them in the order found [here](https://git-scm.com/docs/git-config#FILES). With last value found taking precedence. It would be nice if mintty would do somethings similar. 
For backward compatibility this probably would mean if a `$HOME/.minttyrc` exists, write config changes to that file as settings there would overrule settings in earlier files. And if it does not exist write settings to `$XDG_CONFIG_HOME/mintty/config`.
The alternative would be a migration check and to move a found `$HOME/.minttyrc` to `$XDG_CONFIG_HOME/mintty/config` but that does not solve the case what to do if both files exist.

**Comment by mperry2** [comment]
In my opinion `$HOME/.minttyrc` should be looked for last since one of the points of the XDG spec is to reduce the clutter of dot files in the home directory.

I agree with @sirblackheart that the default config file should be `$XDG_CONFIG_HOME/mintty/config` and the settings should be saved there if no other config file exists.

As for issue #201, that appears to be a problem with the environment that msysgit provides, not with mintty. They should be the ones to fix it.

**Comment by mintty** [comment]
Modifying the plan, mintty should inspect config files in this order, giving precedence to the latest found and saving changes to that:
* /etc/minttyrc
* $APPDATA/mintty/config
* ~/.config/mintty/config
* (perhaps ~/.mintty/config)
* ~/.minttyrc

(Note that ~ is almost but not quite the same as $HOME)

And subdirectories `sounds` and `themes` shall be looked for in $APPDATA/mintty and ~/.config/mintty (and perhaps ~/.mintty, also perhaps /usr/share/mintty first).

(Not sure yet about ~/.mintty which was only recently introduced.)

This means the default XDG config directory will be supported but the environment variable XDG_CONFIG_HOME shall not be checked. The reason is that this would be asking for trouble because normally (esp. when mintty gets started from a desktop shortcut) this variable would not yet be defined when mintty starts, so people would wonder and complain why it is sometimes effective and sometimes not.

**Comment by mintty** [comment]
Release in 2.3.7.

**Comment by mintty** [comment]
Mintty now also supports the XDG default base directory for subfolders for resource files:
colour schemes ("themes") and wave files (for bell sound).

**Comment by mintty** [comment]
Extended XDG directory handling to other resouce files (colour themes, sound wave files).
Released with 2.4.0.

**Comment by BrianInglis** [comment]
`mintty` is a *Cygwin* Windows console application (originally based on *PUtty*) using a *Cygwin* `pty`, not an *X Window* application. 
*Cygwin* offers various *X Window* terminal emulators: `gnome-terminal`, `lxterminal`, `mate-terminal`, `qterminal`, `rxvt`/`-unicode`, `glade-`/`vala-`/`vte`, `xfce4-terminal`, `xterm` clients locally on the PC Cygwin X Server and anything similar on remote (e.g. ssh -X/-Y) links.

**Comment by mintty** [comment]
In a Unix/Linux desktop environment, that variable can be set globally (although some do it wrong), so it will be available to all terminal sessions. In cygwin, mintty is typically run from the Windows desktop, so if you set it in your profile (or xsession, see Brian's response), it will only apply to some mintty sessions, not to others.
I think that would be more confusing than helpful.

**Comment by BrianInglis** [comment]
Something else must have to be run or used to set or get these env vars in an *X Window* app as `XDG_CONFIG_HOME` is not set in an *Xwin* `mintty` `bash` shell, neither are `XDG_DATA_DIRS` nor `XDG_DATA_HOME`, although `~/.config/mintty/` could be added to `mintty` config/init file search path, but it would not be supported by anything else.
See [value replaced by `$UID`]:
```
$ set | grep '^XDG[^=]\+='	# shell and env vars
XDG_CURRENT_DESKTOP=X-Cygwin
XDG_MENU_PREFIX=xwin-
XDG_RUNTIME_DIR=/run/user/$UID/
$ echo $DISPLAY $XDG_RUNTIME_DIR $XDG_MENU_PREFIX $XDG_CURRENT_DESKTOP "'"$XDG_CONFIG_HOME"'"
:0 /run/user/$UID/ xwin- X-Cygwin ''
$ set | grep '.\+XDG'		# completions
    local -a dirs=(${BASH_COMPLETION_USER_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion}/completions);
    for dir in ${XDG_DATA_DIRS:-/usr/local/share:/usr/share};
            COMPREPLY+=($(_filedir_in "$XDG_DATA_DIRS"/meson/cross));
            COMPREPLY+=($(_filedir_in "$XDG_DATA_HOME"/meson/cross));
```

**Comment by mintty** [comment]
> ~/.config/mintty/ could be added to mintty config/init file search path

The hard-coded XDG config directory is already part of the mintty config procedure, just not the environment variable.
