### ISSUE TITLE
Build error on 64-bit-Windows starting with commit 9a9309d40243957e04fed1b3f913314bd16cda11

### ISSUE THREAD

**Issue by jmarter-fastenal** [mintty/mintty#526]
I get the following output running make with gcc 5.3.0 on Cygwin

$ make
#cd src; make exe
#cd src; make bin
cd src; make
make[1]: Entering directory '/d/repository/mintty.git/src'
gcc -c -MMD -MP -DTARGET=x86_64-pc-cygwin -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -g  winctrls.c -o ../bin/cygwin64/winctrls.o
winctrls.c: In function ‘select_font’:
winctrls.c:871:15: error: assignment from incompatible pointer type [-Werror=incompatible-pointer-types]
   cf.lpfnHook = applyfont;
               ^
cc1: all warnings being treated as errors
Makefile:120: recipe for target '../bin/cygwin64/winctrls.o' failed
make[1]: *** [../bin/cygwin64/winctrls.o] Error 1
make[1]: Leaving directory '/d/repository/mintty.git/src'
Makefile:19: recipe for target 'exe' failed
make: *** [exe] Error 2

The line in question was removed from a #ifdef on this commit.

**Comment by mintty** [comment]
This was actually a build error on 64-bit Windows.
Should be fixed now.

**Comment by jmarter-fastenal** [comment]
confirmed.  Thanks.
