### ISSUE TITLE
ALT+F2 doesn't open a new terminal anymore in v2.3.3

### ISSUE THREAD

**Issue by Whissi** [mintty/mintty#531]
I updated my *cygwin* installation, which upgraded *mintty* from *v2.2.3-0* to *v2.3.3-0*.

I noticed that I cannot create a new window anymore pressing `ALT+F2`. Nothing happens.

While preparing this bug report I run `mintty -d` and noticed that from *this* window, `ALT+F2` still works. However it is not working when using the *Cygwin64 Terminal* shortcut (calling `C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`).

```
$ mintty -V
mintty 2.3.3 (x86_64-pc-cygwin)
(C) 2013/2016 Andy Koppe / Thomas Wolff
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
```

**Comment by mintty** [comment]
It seems to happen occasionally (also with earlier versions) but isn't reproducable reliably. Likely a volatile resource problem. I'll check to improve error reporting in this case.

**Comment by mintty** [comment]
This seems to be a duplicate of #530 as it can be triggered with a Locale= configuration parameter.

**Comment by Whissi** [comment]
Yup, that's a dupe of #530. Closing this report...
