### ISSUE TITLE
copying wrapped text inserts an EOL character -- this did not happen in 2.2.3

### ISSUE THREAD

**Issue by kometes-** [mintty/mintty#534]
When copying wrapped text on the terminal, previous versions would copy exactly what is highlighted.  As of 2.3.3, a EOL char is inserted into the text where the wrapping occurs.  Can we have an option to control this behavior?  This behavior makes copying code a real challenge....

**Comment by kometes-** [comment]
I observed this behavior on cygwin...

**Comment by kometes-** [comment]
32-bit cygwin does not show this issue.

**Comment by kometes-** [comment]
This does not seem to be an issue with the mintty source -- it seems to be related to cygwin 64-bit...

**Comment by mintty** [comment]
Could not reproduce this behaviour anyway...

**Comment by kometes-** [comment]
Bah -- user error.  Documenting in case anyone googles this:  in my 64-bit installation, the env TERM was set to cygwin.  It should be export TERM=xterm.

Thanks for looking into it.

**Comment by mintty** [comment]
The mere setting of TERM=cygwin in a mintty session should not affect the copy/paste behaviour. More likely this sounds like you were copying in a Cygwin Console.

**Comment by kometes-** [comment]
Nope -- running c:\cygwin64\bin\mintty.exe from the Run dialog on a win7 64 bit machine.  I can reproduce the problem with 32-bit installation too by adding "export TERM=cygwin" to my .bashrc file.  Globally, SHELL=/bin/bash.exe
