### ISSUE TITLE
Allow Proportional Fonts

### ISSUE THREAD

**Issue by anikom15** [mintty/mintty#538]
Mintty should allow any font to be chosen for the terminal, regardless of whether it is fixed-width or not. Note that mintty is picky about what is a 'fixed-width' font, and not all fixed-width fonts are allowed.

**Comment by mintty** [comment]
It does, just not in the menu. Example: `mintty -o Font="Comic Sans MS"`.

**Comment by mintty** [comment]
Concerning your second sentence: by default, the font selection menu does not include fonts that are "hidden" (a Windows "feature") or have an OEM or SYMBOL character set. See the manual page or the Wiki page "Tips" how to change that.
Assuming we can close the issue?

**Comment by mintty** [comment]
I don't assume you'd want proportional fonts offered in the menu (most people wouldn't want that for a cell terminal), I'm closing the issue.
