### ISSUE TITLE
Differenciate AltGr+Space from Left Alt+Space

### ISSUE THREAD

**Issue by Watilin** [mintty/mintty#542]
Hi!
So I’ve reported an issue to Git-windows, but it turned out it’s actually a problem with mintty.

I’m using the Bépo keyboard layout. Typing an underscore `_` with this layout is achieved by hitting `AltGr`+`Space`. The problem is, this triggers the title bar menu.

I have the option to disable “Menu and Full Screen” in the options, but then, `Left Alt`+`Space` is not recognized neither.

I’m left with using `Ctrl`+`Left Alt`+`Space`, which I can be content with, but this is inconsistent with the typing flow of a regular Bépo user.

So, this isn’t that much impeding, but a problem anyway. I thought it was worth the report ;)

**Comment by mintty** [comment]
How would I activate the Bépo keyboard layout?

**Comment by Watilin** [comment]
Oh yes, sorry. You have to install it from [bepo.fr](http://bepo.fr/wiki/Windows). The installer I used is [this one](http://download.tuxfamily.org/dvorak/windows/bepo.exe).

**Comment by mintty** [comment]
I thought this was an easy tweak but it isn't...
For easier testing, is there another layout around that assigns AltGr+space but doesn't jumble all the usual keys?

**Comment by Watilin** [comment]
Um, not to my knowledge :/

**Comment by mintty** [comment]
Release tweak in 2.3.6. Please check.

**Comment by Watilin** [comment]
I’ll check next time I have the chance! This will probably be in the next week-end.

Meanwhile, I’ve been told a small trick that you might find interesting. With most Linux distributions, typing

    grep '<SPCE>' /usr/share/X11/xkb/symbols/* | more

in a terminal allows to see all usages of the spacebar in any keyboard layout. I hope this can help you ;)

**Comment by mintty** [comment]
Thanks, that might give a hint but not link to a test case because X11 keyboard layouts are not Windows keyboard layouts.
