### ISSUE TITLE
Option to set default window position

### ISSUE THREAD

**Issue by darealshinji** [mintty/mintty#543]
Can you implement an option to the settings to set the default position for the window on startup? I'd prefer the window to appear right in the middle of the screen, but it's always a bit off to the left and I don't know how to change that.

**Comment by mintty** [comment]
`mintty -p center -p right`

**Comment by darealshinji** [comment]
Well, I was actually thinking about something like the default size settings:
![settings](https://cloud.githubusercontent.com/assets/5700937/14708620/4cf68b66-07cc-11e6-930e-9ad0e81b069d.png)

**Comment by mintty** [comment]
Setting the position globally (per configuration) would mean that all terminal windows appear at the same position, while usually varying positions are assigned according to the Windows positioning strategy.
There are X= and Y= options available for .minttyrc; apart from them, that is not going to change; you can set individual positions with command-line arguments. Note also option `-R` perhaps.
See also #169 (duplicate).
