### ISSUE TITLE
PgDn PgUp key dont work in vim

### ISSUE THREAD

**Issue by nobk** [mintty/mintty#544]
After the last upgrade of my MSYS2 x64, PgDn PgUp keys don't work anymore, in vim. But my putty still work.
The version is mintty v2.2.3 (x86_64-pc-msys).
The Shift+PgDn(or PgUp) scroll screen feature is ok.

**Comment by mintty** [comment]
There is nothing that changed around these keys in mintty.
Your vim configuration may have changed, or whatever. Please analyse and describe your environment more clearly; check what Ctrl+V PgDn echoes on the command line, or report to MSYS.

**Comment by nobk** [comment]
I use both mintty with msys2 x64 and putty ssh to the ubuntu 12.04-LTS server, edit the txt file with vim, mintty's PgDn/PgUp don't work but putty do, I think thats the same remote enviroment. and I dont touch any vim config, using mintty and putty the same time with two login instance.

**Comment by mintty** [comment]
"Ctrl+V PgDn on the command line": What does it echo?

**Comment by nobk** [comment]
^[[6~

**Comment by mintty** [comment]
which is the escape sequence for PgDn, so that works.
This sounds weird but there is no evidence of any relation to mintty, sorry.
Closing, for now.

**Comment by nobk** [comment]
In command line it dose, but in vim, it become strange.

**Comment by mintty** [comment]
1. How do you connect remotely from MSYS mintty?
2. It could be that your keyboard is switched to VT220 mode and application keypad mode in which case the escape sequences would change and vim might not understand them. For a test, please kill your vim instance from a separate terminal, using `kill -9` (in order to prevent vim from resetting terminal properties), then repeat the echo test above.

**Comment by nobk** [comment]
option settings term type change to vt100 after upgrade, when i change it back to xterm, vim get the right PgDn input.

**Comment by mintty** [comment]
It's actually getting the same input, but not interpreting it under changed assumptions. Thanks for the notice.
