### ISSUE TITLE
Select All menu addition & switch off control-click-opens-things

### ISSUE THREAD

**Issue by morkk** [mintty/mintty#545]
Working on a slow RDP link recently I was getting spurious "control downs" whenever I double-clicked, resulting in stuff trying to open but usually popping an error window - most annoying.  So I scratched that itch with a new option "ControlClickOpen" defaulting to true.

Another itch is that a Select All option is on the popup menu but not the window menu - also scratched.

Patch attached.

PS thanks for including the ZoomFontWithWindow patch.

[Uploading mintty-235-control-click-switch.zip…]()

**Comment by mintty** [comment]
You mean on double-click mintty would think there was a Ctrl+mouse-click?
If that's so, shouldn't we first try to fix this bug rather than switch off the link opening feature?
Can the issue be reproduced without remote desktop (which I don't have set up)?
And, your patch didn't attach here.

**Comment by mintty** [comment]
Oh, and the menus; the popup menu is actually quite different from the window menu anyway as it refers more to the window text contents rather than to the window frame. There is already another request to add menu entries (#539) but I'm hesitating because the menus shouldn't get cluttered... I rather consider adding user-defined menu items (#100) but that will be some more effort.

**Comment by morkk** [comment]
Damn!  I'll try again with the patch.

The 'double-click looks like ctrl-click' issue only arose on one particular slow RDP link - I've not experienced it anywhere else - I don't think there is bug in mintty.  On the same link in other applications I was getting other weird mouse related issues;  I believe it was the crappy web-based RDP client I was forced to use to get through a firewall.

I get your point about the menus.  I use right-click to paste but have just discovered (doh!) that shift-right-click raises the content menu.  Oh well...
[mintty-235-control-click-switch.zip](https://github.com/mintty/mintty/files/243400/mintty-235-control-click-switch.zip)

**Comment by mintty** [comment]
So I assume you'd withdraw the patch? What about an option instead to limit the opening function to Ctrl+double-click, as some people might prefer?

**Comment by mintty** [comment]
Release in 2.3.7.
