### ISSUE TITLE
[IME]CursorColour does not work with specific BackgroundColour

### ISSUE THREAD

**Issue by experimentlain** [mintty/mintty#548]
When I enable IME, the cursor color does not change with the configuration below:

    BackgroundColour=  7,  54,  66
    IMECursorColour=   0, 138,   0

but it works with this config:

    BackgroundColour=  7,  54,  66
    IMECursorColour=   0, 139,   0

I attached .minttyrc to reproduce the problem.
I am using mintty 2.3.6 x86_64-pc-cygwin on Windows 7 x64 and MS Office IME 2010.
[minttyrc.txt](https://github.com/mintty/mintty/files/251605/minttyrc.txt)

**Comment by mintty** [comment]
Did it work with any earlier version of mintty?
How can the problem be reproduced? (Advice on IME download/activation, please)

**Comment by experimentlain** [comment]
I tried 2.1.5 and it does not work.
About IME, I do not know handy one, but Google IME (https://www.google.com/ime/) may be easy to install.

I glanced over mintty code, and probably I found the reason. In win_text() function in wintext.c:

    bool too_close = colour_dist(cursor_colour, bg) < 32768;

    if (too_close)
      cursor_colour = fg;

this code corrects the cursor color to the foreground color, if they are "too close". I tried commenting out this code, and my .minttyrc worked well.

This behavior may be an intended one, but I think this is too strict at least. I do not think colors (7, 54, 66) and (0, 138, 0) are "too close". About the color-contrast problem, I think it is the most simple to leave it to the users.

**Comment by mintty** [comment]
I have significantly reduced the minimum distance that triggers this behaviour. That restriction could arguably be removed at all, but the code has been in place for so long already...

**Comment by mintty** [comment]
Tweaked previous patch. Minimum trigger raised again (although lower than before) but "brightening" the cursor colour rather than just changing it (algorithm was already in use for brightened ANSI colours).

**Comment by mintty** [comment]
Released in 2.4.0.
