### ISSUE TITLE
Colors seem incorrect

### ISSUE THREAD

**Issue by Skeeve** [mintty/mintty#550]
I used the "solarized" color scheme, but the colors seem to be rendered incorrectly in mintty. this is the color settings of my .minttyrc

	ForegroundColour=101, 123, 131
	BackgroundColour=253, 246, 227
	CursorColour=    220,  50,  47
	
	Black=             7,  54,  66
	BoldBlack=         0,  43,  54
	Red=             220,  50,  47
	BoldRed=         203,  75,  22
	Green=           133, 153,   0
	BoldGreen=        88, 110, 117
	Yellow=          181, 137,   0
	BoldYellow=      101, 123, 131
	Blue=             38, 139, 210
	BoldBlue=        131, 148, 150
	Magenta=         211,  54, 130
	BoldMagenta=     108, 113, 196
	Cyan=             42, 161, 152
	BoldCyan=        147, 161, 161
	White=           238, 232, 213
	BoldWhite=       253, 246, 227

And this is how it renders.

![minttycolors](https://cloud.githubusercontent.com/assets/725404/15173116/8c11ddbc-175a-11e6-9ee1-c835257a3156.png)

Maybe I did something wrong? Maybe it's a bug? I have no clue, could someone please tell me any more information required in order to help solving the issue I face?

**Comment by mintty** [comment]
Which of the colours do you think is wrong?

By the way, are you aware that the colour scheme does not need to be merged into .minttyrc anymore but can be configured with -C or option ThemeFile or in the Options menu?

**Comment by Skeeve** [comment]
I fear I did something wrong. The Dark Blue / BoldBlue appeared wrong to me. But now, thanks to you asking me, I had a closer look and I noticed that I mixed up my understanding of which numbers are for red and which one is for blue - Sorry for this.
