### ISSUE TITLE
Mintty doesn't pass the VT100 Torture Test File

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#551]
Not sure how compatible with VT100 you want to be, but this might be interesting to you:

The test is located here: http://www.inwap.com/pdp10/vt100test.txt
To run it, download the file and `cat` it.

Here is an example of `Terminal`, that seems to pass it:
![4w2lmxf](https://cloud.githubusercontent.com/assets/2286713/15219482/e2c3c862-185b-11e6-9952-f859c59ac7f5.png)

And here is mintty's output:
![vttorturetest](https://cloud.githubusercontent.com/assets/2286713/15219654/81fe442a-185c-11e6-90d8-66e9e068d67e.PNG)

Also selection of text that is double width or double height is also (not surprisingly) broken.

**Comment by mintty** [comment]
Thanks for the notice; I see these issues:
* Line drawing horizontal lines. Mintty maps them to respective Unicode characters which are unfortunately not included in most fonts, so fallbacks are used. For a fix, they would need to be drawn directly (#130).
* Underlining could be positioned lower.
* Double-width text not visible after attribute changes.

**Comment by mintty** [comment]
Released in 2.3.7.

**Comment by mintty** [comment]
Released further tweaks in 2.4.0.
