### ISSUE TITLE
Load configuration file on the fly

### ISSUE THREAD

**Issue by ggomez91** [mintty/mintty#552]
Is there any way to load a configuration file and apply that configuration to the running mintty?
I find the -C and -o options to do this but in a new created window.

**Comment by mintty** [comment]
There is the new ThemeFile option which could be misused to load a configuration file but that wouldn't exactly achieve what you ask for (mintty would save to the original config file, including the ThemeFile option).
Mintty configuration should be kept simple; I don't see a strong use case for such a change.

**Comment by ggomez91** [comment]
Actually what I want is to change the theme (colours) on the same mintty I am, without opening a new one. The -o ThemeFile option does spawn a new mintty right?

**Comment by mintty** [comment]
The option can be configure from the Options menu, setting "Looks", popup "Theme" which shows all theme files in the config directory (empty by default), or takes a file name.

**Comment by mintty** [comment]
If the existing option does what you want, can we close the issue?

**Comment by ggomez91** [comment]
Sorry I did not specified but I hoped to achieve this on the terminal. This is to programatically change the theme according to events happening inside the shell. Specifically I want to change the colors when I ssh to a production server (I plan to do this based on the prompt which contains the host).

**Comment by mintty** [comment]
That is possible with escape sequences (from xterm). See https://github.com/mintty/mintty/wiki/Tips#changing-colours for an example, or put the codes in a file, to be cat'd to the terminal.
Some colour schemes are also distributed in that form.
