### ISSUE TITLE
Issue with high res displays on w10

### ISSUE THREAD

**Issue by AlexSamad** [mintty/mintty#554]
Hi

recently moved over to using mintty from rxvt-unicode in cygwin.
I run 2 external displays 2560x1440 and laptop 3200x1800

when I open mintty on the laptop screen it resizes to the approx right size. when i move the window to the lower resolution screen the font / window size is all wrong, The title bar size is wrong and the scroll bar size it wrong.

**Comment by mintty** [comment]
Duplicate #547, as far as window decoration is concerned. Note this is a Windows problem, not really a mintty problem.
About the font, expectations could be different. What do you actually see and what would you expect? Note also, that holding Shift while moving the window may affect the result.

**Comment by AlexSamad** [comment]
Thanks I have subscribed there and added comments

**Comment by mintty** [comment]
Also, about font scaling, please check whether your issue is the same as #492.

**Comment by mintty** [comment]
Closing duplicate.
