### ISSUE TITLE
Alt-number combination

### ISSUE THREAD

**Issue by arturocastro** [mintty/mintty#557]
`Alt`+`Number` keyboard combination does not seem to work when trying them on programs, for instance, create/switch tabs in ranger, or switch windows in irssi.

They work fine when running xterm or rxvt with X/Cygwin. Other combinations with `alt` work, like `alt`+`v` with emacs.

I haven't been able to come up with a solution, I was thinking about using AutoHotKey for mapping left alt, but it hasn't worked yet. I'd be happy with such a solution or with a potential fix for mintty.

Could this be considered as an issue with mintty, and if it could, is it fixable?

**Comment by mintty** [comment]
Does it work with the previous version (2.3.6)?
There was a change about modified keypad keys, now sending the *same* key sequences as xterm.
Do you use a dedicated cygwin configuration of key sequences for running your application (which, by the way?) in mintty than for running it in xterm? Try to change that to the same configuration.

**Comment by arturocastro** [comment]
(My bad, I should have mentioned my version. I'm running 2.3.6.)

I seems it was an issue with the way I was running Cygwin, because creating the shortcut again solved it.
I'm not sure what was wrong with the other one or what could have caused the issue, but it was consistent (when spawning a new mintty from the "bad" mintty, the new worked fine and the old one still didn't work with that keyboard combination).

Since I deleted the last shortcut by accident (it was pinned to the taskbar), I can't reproduce this issue anymore.

**Comment by mintty** [comment]
So can we close the issue?
