### ISSUE TITLE
Improve support for native console programs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mintty/mintty#56]
```
What steps will reproduce the problem?
1. Start the Win32 Python (not the Cygwin port) inside mintty

What is the expected output? What do you see instead?
The interactive Python prompt should be displayed. Instead, nothing happens
and the shell remains suspended until I press Ctrl-C.

What version of the product are you using? On what operating system?
0.3.5-1

Please provide any additional information below.
Win32 Python is works fine under Console2
(http://sourceforge.net/projects/console/), which is a different Windows
terminal emulator.
```

Original issue reported on code.google.com by `sami.kyo...@gmail.com` on 17 Feb 2009 at 3:07

**Comment by orgads** [comment]
After digging into this issue, I have a few insights:

* When an application is executed, mintty uses msys2/cygwin forkpty(), which creates pipes that are used to read/write to/from the application. These pipes are created using CreateNamedPipe (in [fhandler.tty](https://github.com/mirror/newlib-cygwin/blob/master/winsup/cygwin/fhandler_tty.cc#L1785) and [indirectly](https://github.com/mirror/newlib-cygwin/blob/master/winsup/cygwin/fhandler_tty.cc#L1725) in [pipe.cc](https://github.com/mirror/newlib-cygwin/blob/master/winsup/cygwin/pipe.cc#L284))
* cygwin/msys has its own libc, it doesn't use msvcrt, so [the hack used in Git](https://github.com/git-for-windows/git/blob/master/compat/winansi.c#L459-L528) (and [other](https://github.com/ruby/ruby/blob/trunk/win32/win32.c#L2308-L2487) MinGW products) cannot be used here.

There are [several](http://www.codeproject.com/Articles/16163/Real-Time-Console-Output-Redirection) [projects](https://code.google.com/archive/p/winpipe/downloads) that enable a pipe to become a virtual console. These 2 projects use an intermediate stub for that.

It looks complicated to integrate it though...

**Comment by mintty** [comment]
Thanks for looking into this.
I'm not sure where exactly the quoted Git code is hooked into and whether it has any impact on a Git application when running in mintty.
In general, such a console gateway would need to be hooked into cygwin, not mintty. We'd have to find the place where to hook it in, and where and how to distinguish cygwin applications from native Windows applications.
If that succeeds, console I/O could be redirected with pty I/O, and also character set transformation should be applied on that occasion. (An additional challenge might be signal handling.)
That's basically all I can contribute, I don't feel like digging into this Windows console stuff. If you find a working solution, I'm sure you'll earn a cygwin gold star, in addition to an entry in the mintty credits list.

**Comment by dragon788** [comment]
Msys2 has a winpty application that seems to do a lot of this.

**Comment by mintty** [comment]
Sure, you can use winpty or some similar wrappers in cygwin as well, but you'd need to invoke them explicitly with every native program activation.
The goal would be to have a wrapper like winpty hook in automatically within cygwin whenever a non-cygwin console application is started.

**Comment by e4lam** [comment]
The old google website is gone and I need to recompile conin for the latest cygwin. Where can I find the source code for it?

**Comment by mintty** [comment]
https://github.com/mintty/utils

**Comment by chaosreload** [comment]
I found when I use windows-native redis-cli.exe, mintty hangs and crash totally, while other interactive programs just hang and you can use Ctrl + C to stop the program

**Comment by be5invis** [comment]
Maybe you can take a look at ConPTY now. That's the missing part of Windows' console system recently filled.

**Comment by Biswa96** [comment]
ConPTY and Unix pty are totally different.

**Comment by Biswa96** [comment]
Cygwin now has Windows ConPTY support. See [this commit][1]. Released in Cygwin 3.1.0-0.3 test build.

[1]: https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by eximius313** [comment]
Is there any hope for solving this issue?

**Comment by mintty** [comment]
Yes, you can expect it to be solved with the next cygwin release which supports the new Windows ConPTY API.

**Comment by Biswa96** [comment]
@eximius313 You can also download and use the cygwin _test builds_ now by selecting test radio button in cygwin setup. But as they are test builds _random crashes_ may occur.

**Comment by eximius313** [comment]
I'm using it via GitBash, so it's not that easy ;)

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.

**Comment by cup** [comment]
https://github.com/mintty/mintty/issues/963

**Comment by codesculpture** [comment]
> Cygwin 3.1.0 has been released with ConPTY support.

Hey, i read the whole conversation but still cant figure how to effectively do `SetConsoleMode` in a `git bash`, If i fed PipedHandle which is got from `GetStdHandle(STD_INP_HANDLE)` it would result in InvalidHandle, Also if i get the console handle through `CreateFile` by `CONIN$` and it would not making any changes in `ConsoleMode` 
For ex: I need to disable Echo Mode in git bash, but seems i cant ?

**Comment by mintty** [comment]
That question is out of scope here. Mintty and bash provide POSIX style programming environments. ConPTY support is available (by cygwin) to support interworking, but if you wish to program Windows console style, you need to get advice elsewhere.

**Comment by mintty** [comment]
If you have a program that runs in native Windows console (the cmd thing) and does not work in cygwin, you may ask on the cygwin mailing list.

**Comment by codesculpture** [comment]
Thanks @mintty will reach cygwin then

**Comment by mintty** [comment]
One further note, as you mentioned git bash: I don't know whether git bash enables ConPTY support by defaultl meanwhile (as MSYS2 does). If not, you could set environment variable CYGWIN=enable_pcon and then start another terminal from the command line to enforce it.

**Comment by mintty** [comment]
OK, at least my instance of Git Bash does not support ConPTY (workaround see above), so maybe you should give _them_ an issue.

**Comment by mintty** [comment]
As a persistent workaround, configure it in your home .minttyrc file:
`echo ConPTY=on >> ~/.minttyrc`

**Comment by codesculpture** [comment]
@mintty this is actually working, `echo ConPTY=on >> ~/.minttyrc`. But can i know what is happening here, i dont quite understand where is the actual problem is please?

**Comment by mintty** [comment]
Console support (mentioned above, ConPTY) is provided by cygwin. It's enabled by default in cygwin and meanwhile MSYS2 but apparently not in Git bash. With the given option, mintty configures it to be enabled by cygwin/MSYS2.

**Comment by mintty** [comment]
You can also configure ConPTY support by adding `MSYS=enable_pcon` to file `/etc/git-bash.config` as described in the mintty wiki.
You can also enable ConPTY support during installation of Git for Windows, late in the "question and answer" game, by clicking the checkbox 
`Enable experimental support for pseudo consoles.`
