### ISSUE TITLE
Fullscreen mode should capture focus upon desktop switch

### ISSUE THREAD

**Issue by JasonKleban** [mintty/mintty#560]
Windows 10 finally supports multiple desktops.  Mintty in fullscreen mode should capture keyboard focus when the desktop switches to it.

**Comment by mintty** [comment]
Read the manual and press Alt+Enter.

**Comment by JasonKleban** [comment]
Yes, excellent.  Thanks.  I looked through the options but didn't see that shortcut.

I'll modify the issue for the remaining problem of focus.

**Comment by mintty** [comment]
You can also start mintty in fullscreen mode: `mintty -w full`.

About the other issue, what do you mean by desktop switch?

**Comment by mintty** [comment]
About to close the issue unless it is described properly.

**Comment by JasonKleban** [comment]
Desktop switch - the event of having switched the desktop.  Once you have at least a second desktop created in Windows 10 and you have mintty running in fullscreen on one of them, switching to that desktop (for example, with <kbd>Win</kbd><kbd>Ctrl</kbd><kbd>Right</kbd>) shows mintty but the focus is on the Windows Task Bar and mintty must subsequently be focused with the mouse or <kbd>Alt</kbd><kbd>Tab</kbd>.  I'm wondering if mintty can assume focus in this situation.

**Comment by mintty** [comment]
<kbd>Win</kbd><kbd>Ctrl</kbd><kbd>Right</kbd> does not work here as advertised.
If you describe a *reproducible* procedure to switch the desktop, I can trace whether that gets notified to the applications so mintty could handle it to grab the focus.

**Comment by mintty** [comment]
OK, so you didn't mean switching between multiple monitors but between virtual desktops, I suppose.
If mintty has the focus before leaving one of them, it will have it again after you switch back to it, so there is nothing to do.
If mintty does not have the focus, there is no specific message sent to it in that case.
