### ISSUE TITLE
Chances of relicensing to LGPL?

### ISSUE THREAD

**Issue by tkelman** [mintty/mintty#562]
I'd love to integrate mintty into a project where we'd prefer to avoid GPL if at all possible. I saw the great news today that the Cygwin library itself is going to be relicensed as ~~GPL~~ LGPL, so wanted to ask if it'd be possible at all here. Have you been in touch with previous developers at all, would it be possible to get their permission if this is something you'd be receptive to? Who holds the copyright here?

**Comment by mintty** [comment]
As I understand, the LGPL is intended for _libraries_ which mintty isn't.
What's the consequence? E.g. for your project (which one?).

**Comment by tkelman** [comment]
The project is the Julia language - http://julialang.org. We have a command line application for our interactive REPL that is built using mingw-w64, but has the right knowledge of Cygwin named pipes to work properly within mintty. Since many of our users are on Windows 7 where the default console sucks, we're considering bundling mintty (and its dependencies - the cygwin dll, along with stty.exe and maybe one or two others) in our default install. If we have any GPL dependencies, then it's questionable whether we can also include any non-GPL-compatibly licensed code, such as the Intel MKL math libraries, in the same install. Since we only communicate with mintty via named pipes we could be fine under the aggregation clause, but being LGPL would be clearer-cut and less of a gray area for us.

**Comment by mintty** [comment]
Reading just the wiki on LGPL, it makes a difference for projects with a more restrictive licence if they want to _integrate_ other software. However, as mintty isn't a library, I don't think it's being integrated but simply _bundled_ in other projects.
MinGW, e.g., also repackages mintty and even disguises it by calling it "MSys Shell" and Git for Windows even calls it "Git Bash". I see no problem here.
I would see a problem if I were to investigate into legal issues because that's giving normal people headaches:/ You would have to convince me further, and maybe point out some typical description of the matter concerning other projects...

**Comment by mintty** [comment]
Also see http://www.webopedia.com/TERM/L/LGPL.html:
> with LGPL the the requirement that you open up the source code to your own _extensions to the software_ is removed

1. You aren't extending mintty, so I see no relevant difference here.
2. If somebody were extending mintty, I wouldn't like to allow them to keep that secret, it should rather be offered to mintty for contribution.

**Comment by tkelman** [comment]
Depends what you mean by extension. There are many companies for which GPL software is just not allowed at all. LGPL would mean any changes to mintty itself that get distributed need to be made public. GPL means any changes to mintty, along with all of the source code of any larger projects that want to incorporate it need to be made public.

**Comment by mintty** [comment]
> LGPL would mean any changes to mintty itself that get distributed need to be made public.

This is the contrary of what I quoted above. Can you elaborate/explain/clarify?

**Comment by tkelman** [comment]
LGPL is still copyleft, but copyleft for the project itself rather than viral copyleft of all derived works. The legal gray area between what comprises a derived work vs what does not it the biggest uncertainty that leads many companies to just outright ban using/redistributing all GPL software as components within their projects.

**Comment by mintty** [comment]
Can you point out the precise wording in the LGPL that marks this difference?
Is the anti-patent clause of GPL retained?
How would dual-licensing work?
And, most important, since mintty was originally derived from putty, am I actually authorised to make this change??

**Comment by tkelman** [comment]
Putty appears to be licensed more permissively than either GPL or LGPL, so that would be fine - http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=blob;f=LICENCE;h=4d917ff227d0da0fb22eff7459713650afde5123;hb=HEAD which looks like the MIT license.

But it would require all contributors to agree to relicense, if contributions didn't come with a relicensing agreement originally.

The "Combined Work" section 4 of the LGPL 3 is the relevant one here, saying that a work that includes mintty could be distributed under any terms, as long as you follow the conditions there. Those conditions include the requirement to redistribute Minimal Corresponding Source - if mintty is modified at all then that would have to include those changes, if it's not modified then it could just be the upstream source here.

> Is the anti-patent clause of GPL retained?

I believe so, for mintty itself, and any modifications of it that need to be distributed under its original license (which "incorporates the terms and conditions of version 3 of the GNU General Public License, supplemented by the additional permissions listed below").

> How would dual-licensing work?

What do you mean by this? Dual-licensing mintty itself with the option of either GPL or LGPL? That would work too I think, but I'm not sure if there are other projects that do exactly that since the LGPLv3 includes the terms of the GPLv3 anyway.

**Comment by roeme** [comment]
IANAL, I think this depends on how you bundle mintty. If it's clear from the enduser's POV that it's _mintty_ that is running (i.e. you don't get some rebranded, heavily adjusted terminal emulator), then you don't need to fear that somebody claims your whole bundle a derivative work of mintty.

Doesn't solve some C-level suits being deaf to arguments though.

**Comment by mintty** [comment]
@tkelman: section 5 of GPL defines an "aggregate" and state that
> Inclusion of a covered work in an aggregate does not cause this License to apply to the other parts of the aggregate.

I think that sounds quite clear and should as such disperse your concerns, provided it's applicable to the whole thing; I only wonder why it's located in section 5 specifically.

Apart from that, I'm considering to amend the license with a prelude to the GPL, clarifying the interpretation so bundling is not considered a "work based on mintty". Would that be sufficient?

**Comment by tkelman** [comment]
The "aggregate" wording looks pretty directly targeted towards the "distribution iso archive" case. There are a lot of gray areas that would have to be decided by a lawyer in that section, and many companies would rather avoid the risk entirely and disallow use of GPL software. I need to provide a totally GPL-free build of Julia to satisfy those users. If mintty could be part of that, those users would have a better experience.

**Comment by mintty** [comment]
Well, what I had in mind is an explicit declaration that "bundling" mintty with other software in order to provide a stand-alone deployment for text-based applications is considered an "aggregate".
I could further declare this means that the license does not carry over to that other software (maybe except for the patent clause, which is actually a good achievement of GPL).

This is what I can offer *short-term*. For exchanging the GPL completely, I would need to gain more confidence that this does not raise any trouble.

**Comment by tkelman** [comment]
Some more explicit bundling exception wording would be a great start. The gcc runtimes and libgit2 havesomewhat similar linking exceptions that we use.

**Comment by mintty** [comment]
For libgit2, that would be https://github.com/libgit2/libgit2/blob/master/COPYING.
I've uploaded a new license scheme, please check, I plan the next release soon.

**Comment by mintty** [comment]
Released 2.4.0 with the "GPL bundling license".
Please check whether the issue can be closed.

**Comment by tkelman** [comment]
I still think LGPL would be even better than GPL + project-specific extra language, but that sounds less feasible for you. So thanks for the changes so far. I guess we can close for now.
