### ISSUE TITLE
Bolding of text

### ISSUE THREAD

**Issue by paul-martin3** [mintty/mintty#567]
Bolding of text

I have recently upgraded my version of mintty from : "mintty 2.3.7  i686-pc-cygwin" to : "mintty 2.4.0  i686-pc-cygwin".

A regression has emerged in the rendering of the ANSI bold text attribute. This regression affects my home-made .FON font, but can also be reproduced by selecting the font : Fixedsys Normal 9 pt (vgafix.fon).

With mintty 2.3.7, the Bold attribute is correctly simulated by rendering the text twice with a one-pixel offset, as stated in the documentation.

With mintty 2.4.0, the Bold attribute is indistinguishable from regular text.

In both cases, the "show bold as font" box is checked and the "show bold as color" box is unchecked.

Regards

Paul

**Comment by mintty** [comment]
Released fix in 2.4.1.
