### ISSUE TITLE
the bell doesn't emit any sounds....

### ISSUE THREAD

**Issue by idanb11** [mintty/mintty#568]
Pls help...

I just installed git windows version 2.9.2 and the bell doesn't make any sound...

**Comment by mintty** [comment]
Please check your configuration; Options – Terminal – Bell setting, and Options – About ... which version?

**Comment by mintty** [comment]
Actually, bell sound is disabled by default, as documented in the mintty manual page.
Maybe I should change that...

**Comment by idanb11** [comment]
Hi @mintty ,
I'm using mintty 2.0.3 (x86_64-pc-msys).

Yes, I've checked that the bell setting is on but still it is **not working**...

BTW, the flashing of the screen is not working too...
everything was ok when i was working with git ver1.9.5

**Comment by mintty** [comment]
Does your sound work at all? Maybe your sound scheme has no sound for the standard bell? Does it work in any other terminal?
Either way, bell works fine with current mintty, and also with 2.0.3 here.

**Comment by mintty** [comment]
Enabling Bell sound by default with 2.4.2.
