### ISSUE TITLE
Can't correctly display Chinese character(version 2.4.1 only)

### ISSUE THREAD

**Issue by XuJiandong** [mintty/mintty#570]
With the new version 2.4.1, It can't display Chinese character correctly. Version 2.4.0 is OK.
How to reproduce, put 
> 你好世界
in ~/text, then cat ~/text. There is difference between 2 console windows with 2.4.0 and 2.4.1.

mintty setting:
Locale: C
Character set: UTF-8

$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=C

**Comment by mintty** [comment]
Apologies for spoiling wide character display by a tweak (#123) that should make narrow characters wide.
Apparently, Windows reports wide characters to be narrow if they are wide only by the font fall-back mechanism. Using a CJK font directly would be a workaround, like:
```
mintty -o Font="Ms Mincho"
```
I've reverted that tweak and will release the fixed version soon.

**Comment by mintty** [comment]
Fixed with 2.4.2.

**Comment by mintty** [comment]
Released 2.6.2.
