### ISSUE TITLE
Add SIXEL graphics support

### ISSUE THREAD

**Issue by saitoha** [mintty/mintty#572]
Moved from #571.

>>> Why LICENSE.xterm? Why not LICENSE.sixel from libsixel?

>> OK, LICENSE.sixel is also needed. I'll add it.
>> LICENSE.xterm is needed only for the tiny function hls_to_rgb() in sixel.c.

> I wouldn't like to have a confusing license file named "xterm". Couldn't it be simply be embedded in sixel.c like in xterm itself? And I'll mention it in the main LICENSE file. Or the function could be moved to a separate file, to distinguish licenses more clearly.

I moved hls_to_rgb() to new separated file (4aa0ccd) .

> There's one more bug apparently:
> The cursor position after a sixel image is next to the right bottom of the image. I guess it should > be at the beginning of the next line (checked with xterm, also mentioned in the xterm manual page for "sixel scrolling").

OK, I fixed in 1d3ab0a.

> And we should also patch the Primary Device Attribute report in termout.c:
>
> - static const char primary_da[] = "\e[?1;2;6;22c";
> + static const char primary_da[] = "\e[?1;2;4;6;22c";

Fixed by aece93d.

**Comment by saitoha** [comment]
>> There's one more bug apparently:
>> The cursor position after a sixel image is next to the right bottom of the image. I guess it should
>> be at the beginning of the next line (checked with xterm, also mentioned in the xterm manual page for "sixel scrolling").

> OK, I fixed in 1d3ab0a.

Sorry, amend by 90b744f.

**Comment by mintty** [comment]
Still not like xterm (which moves to the horizontal beginning of the line, not of the image),
but note http://vt100.net/docs/vt3xx-gp/chapter14.html :
> When sixel display mode is enabled, the sixel active position begins at the upper-left corner of the ANSI text active position. Scrolling occurs when the sixel active position reaches the bottom margin of the graphics page. When sixel mode is exited, the text cursor is set to the current sixel cursor position.

So actually your previous approach was the original one and xterm does not implement it correctly.
I guess we should follow DEC here rather than xterm.
This applies to "Sixel Scrolling Mode Enabled"; "Sixel Scrolling Mode Disabled" does not seem very useful to me.

**Comment by mintty** [comment]
One more detail about the exit position: Is the "sixel cursor position" actually chosable in the sixel format, i.e. can the image be drawn with arbitrary final position? In that case, e.g. the exit position and subsequent cursor position could also be next to the *top* right corner which would be very useful for something like `ls` with icons...

**Comment by saitoha** [comment]
> xterm does not set a background (transparent background), which is not necessarily good if the terminal background is black. Your code sets white background which some people may not like for its brightness.

This is due to my careless implementation. SIXEL parser should respect terminal background color.
Fixed in 0176c66.

<img width="438" alt="2016-07-31 10 38 57" src="https://cloud.githubusercontent.com/assets/1162739/17274105/0ab8cb2c-570b-11e6-85c8-01e917766add.png">

> Where is actually your multiplt.dem file?

here.
http://gnuplot.cvs.sourceforge.net/viewvc/gnuplot/gnuplot/demo/multiplt.dem?revision=1.6&view=markup

**Comment by saitoha** [comment]
> Still not like xterm (which moves to the horizontal beginning of the line, not of the image),
> but note http://vt100.net/docs/vt3xx-gp/chapter14.html :

I tried to add sixel display mode in 440b8b4, but it brings us terrible rendering glitches.
Many rendering bug fixes are needed. I'll do it continuously.

> One more detail about the exit position: Is the "sixel cursor position" actually chosable in the sixel format, i.e. can the image be drawn with arbitrary final position? In that case, e.g. the exit position and subsequent cursor position could also be next to the *top* right corner which would be very useful for something like `ls` with icons...

I think this problem can be solved if we calculate next image position by using the pixel dimentions of cell (cell width / cell height).
mintty set `struct winsize` to terminal pixel size(https://github.com/mintty/mintty/blob/master/src/winmain.c#L902) and pass it to the pty over TIOCSWINSZ ioctl, so applications can detect pixel cell size with TIOCGWINSZ ioctl.

**Comment by mintty** [comment]
> I tried to add sixel display mode ...

I didn't mean to suggest that. I think Sixel Scrolling Mode is perfectly sufficient. I think mlterm only implements that too.

**Comment by saitoha** [comment]
> I didn't mean to suggest that. I think Sixel Scrolling Mode is perfectly sufficient. I think mlterm only implements that too. 

Oh, I got it. Do you prefer to remove this feature? I think it might be useful when implementing full-screen sixel application.

**Comment by mintty** [comment]
If there's code already, you can leave it in for later completion. It should eventually be switchable with the escape sequence ESC[?80h/l, and we can leave the switching out for now.
I just notice that xterm even has a switching sequence for the final cursor position:
ESC[?8452h Sixel scrolling leaves cursor to right of graphic (as you had first)
ESC[?8452l ... beginning of line
According to the DEC docs, "right of graphic" should be the default. If you want to offer the choice, we can do that, too.

**Comment by saitoha** [comment]
Tera Term maintainer @ttdoda, also known as VT collector, reported real behavior of SIXEL terminal VT382 and VT330.

He says, (summary)

> In VT382, the cursor returns to left *automatically*, in spite of lacking sixel next line charactor(-) at the end of SIXEL dump.
([twitter](https://twitter.com/ttdoda/status/370727508347322368))

> A SIXEL line has only 6-dot height, and the text line is higher than it. Because SIXEL active position is converted into text cursor position, it might not be at next line of bottom, but at the bottom-left corner of image.
([twitter](https://twitter.com/ttdoda/status/454484333588254720))

![SIXEL active position](https://pbs.twimg.com/media/Bl1YOrrCcAEJA0T.png:large)

I think we should follow Xterm's behavior because it is too complicated to emulate.

**Comment by mintty** [comment]
Thanks for investigating this.
So either VT382 deviates from VT330/VT340, or the DEC documentation itself is wrong.
Anyway, let's go the xterm way then, and move to the beginning of the line below the image (not the horizontal beginning of the image, in case the image is indented).

**Comment by mintty** [comment]
When scrolling, there are still some occasional artefacts, see screenshot after searching with Alt+F3 and scrolling back and forward with the mouse wheel a little bit:
![Uploading sixel-scroll.png…]()

But at least the position of the sixel image seems to be correct.

Sixel display mode, on the other hand, may leave some flickering artifacts aside the image.

For a first release, though, I would consider that acceptable, provided you fix the exit positioning problem. I would leave it up to you whether to disable the sixel scrolling mode switching sequence initially.

About licensing: I thought you'd want to add the hls code specific license to the separated sixel_hls.c file. But it reads there:
// Licensed under the terms of the GNU General Public License v3 or later.
which is the same as in sixel.c. If that's a proper licensing, there is no reason anymore to separate the files.

If these issues get sorted out, I'd be willing to integrate a pull request tomorrow if you want. Or leave your time if you prefer, and we'll proceed after my holidays.

**Comment by saitoha** [comment]
OK, I decided to disable Sixel display mode initially.
I understand that we have to reverse the order of calling termpaint and image_paint() to fix rendering problems. But now I leave it because it seems to be hard way.
Then I implemented private mode 8452 (db6ec3d).

> About licensing: I thought you'd want to add the hls code specific license to the separated sixel_hls.c file. But it reads there:
> // Licensed under the terms of the GNU General Public License v3 or later.
> which is the same as in sixel.c. If that's a proper licensing, there is no reason anymore to separate the files.

It was thoughtless of me, deleted wrong annotation in 5b6a691.
`sixel.c` is originally written by kmiya@cluti. original license is [here](https://github.com/saitoha/sixel/blob/master/README.md#license). 
I had contacted him and confirmed that he permits make his code re-license to GPL.
so we can distribute it under the GPL without any restriction.
`sixel_hls.c` is a part of graphics.c in Xterm pl#310 originally written by Ross Combs.
Its original license is [here](https://github.com/andreasjansson/xhrrmm/blob/master/graphics.c#L3-L31). We have to include it in somewhere in the package.

**Comment by mintty** [comment]
License: please include embedded in sixel_hls.c

Exit position: 8452 mode is OK, however the default you chose seems to be different from xterm (but compliant with the DEC description I mentioned, which in turn may be wrong...).
Also still check the position to go to the beginning of the line, please, of "sixel scrolls right" is off:
`echo -n margin; cat some.sixel`:
```
marginSSSSSS
      SSSSSS
      SSSSSS
X     M
```
xterm continues at `X`, mintty currently at `M`.

Rendering: When I resize the font (Control+mouse-wheel), considerable artifacts are left behind, even after restoring original font size (Control+0), which I don't understand.

**Comment by mintty** [comment]
Note I've just commited another patch that changes one line in wintext.c.

**Comment by saitoha** [comment]
> License: please include embedded in sixel_hls.c

Done in feef6dd. ok?

> Exit position: 8452 mode is OK, however the default you chose seems to be different from xterm (but compliant with the DEC description I mentioned, which in turn may be wrong...).

Actually, 8542 mode is originally implemented by [RLogin](http://nanno.dip.jp/softlib/man/rlogin/), a ssh/rlogin terminal emulator written by kmiya, for keeping compatibility between Xterm. In RLogin default settings, 8452 mode is off. I think it's DEC compliant way.
I forwarded that thing to Xterm maintainer Thomas Dickey. He implemented 8452 mode for solve compatibility problem, but default value is still on.
I think it's a matter of taste. I prefer RLogin's way because `cat *.sixel` works as intended when 8452 is off.

> With "sixel scrolls right" mode on, both xterm and mintty continue at R, so in a different line; weird;

It seems OK for me. If image size is pixel height is multiple of cell pixel height, the cursor position is at the right cell of bottom-right corner.
<img width="380" alt="2016-08-04 2 10 16" src="https://cloud.githubusercontent.com/assets/1162739/17374781/2a9b5488-59e9-11e6-9627-1ad53e6bab3e.png">
<img width="348" alt="2016-08-04 2 11 18" src="https://cloud.githubusercontent.com/assets/1162739/17374803/42f12a80-59e9-11e6-8739-979aba6fde01.png">

> Rendering: When I resize the font (Control+mouse-wheel), considerable artifacts are left behind, even after restoring original font size (Control+0), which I don't understand.

Still checking... Probably it is caused by setting ATTR_INVALID to cells behind the images.

<img width="449" alt="2016-08-04 2 22 54" src="https://cloud.githubusercontent.com/assets/1162739/17375062/68108238-59ea-11e6-9951-6778bdeda0d6.png">

**Comment by saitoha** [comment]
@ttdoda [tweeted](https://twitter.com/ttdoda/status/760832613531529217) about positioning behavior after SIXEL dump on real VT382J/VT340. RLogin/mlterm behavior looks more DEC complient then Xterm on this point.

**Comment by mintty** [comment]
Concerning the rendering problems after font resizing:
Since resizing was not a feature of original SIXEL terminals, this is not a matter of behaving like the original. It's just a question of achieving some acceptable result. I'll check how xterm behaves in that case. About the exit position, anyway, I think it's OK to define the exit position with respect to the line while it was output; please do not try to reflow the SIXEL output within the text output as that might cause other inconsistencies.

**Comment by mintty** [comment]
... xterm maintains the start position (which is desirable) but does not reflow the text, so that the rendered exit position would not be consistent after font resizing. I think that is the right thing to do.

**Comment by saitoha** [comment]
Added some improvements:
- make enable to overwrite image with text.
- scale image when the font size is changed.
- re-enabled SIXEL display mode.

https://github.com/mintty/mintty/compare/master...saitoha:sixel

Wrong positioning bug after window-resizing is still remained.
I need to understand what happened during the window is resized.

**Comment by mintty** [comment]
Some more background information I found about sixel scrolling:
In http://vt100.net/docs/vt3xx-gp/appendixb.html it says:

> The VT300 scrolls sixels. The VT240 does not scroll sixels.

This does not really affect the chosen design which follows xterm with its mode switching escape sequences. Maybe it suggests the default should be the more "modern" scrolling behaviour.

**Comment by mintty** [comment]
@saitoha: just a humble request for your plans; I'm eager to receive a stable patch to integrate. The current download does not display sixels here, unfortunately, any issues I can help with?

**Comment by saitoha** [comment]
@mintty Sorry for late reply!!
I squashed commits until now and make a big patch.

[0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt](https://github.com/mintty/mintty/files/447834/0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt)

> The current download does not display sixels here
Really? It seems OK for me in my win7-i686 cygwin environment. but I did not test it in high DPI environment...

Image positioning bugs caused by resizing or font-size change seem to be fixed now. Could you confirm it?

**Comment by mintty** [comment]
winimg_hibernate: Are you sure it's a good idea to keep around FILE pointers for each image? You may be getting a resource problem more serious than wasting some of the plenty of memory.

**Comment by mintty** [comment]
The DECRQSS for which ESP P is being reused don't seem to work anymore.

**Comment by mintty** [comment]
When tracing term.state in term_write, on output of a sixel file, DCS_START and DCS_PARAM occur once each, a lot of DCS_IGNORE, but no other DCS_* state occurs. Is that as it should be? Still no image output on Windows 7.

**Comment by saitoha** [comment]
> When tracing term.state in term_write, on output of a sixel file, DCS_START and DCS_PARAM occur once each, a lot of DCS_IGNORE, but no other DCS_* state occurs. Is that as it should be? Still no image output on Windows 7.

Sorry,it's my carelessness. wrong DCS_IGNORE occured.

```
--- a/src/termout.c
+++ b/src/termout.c
@@ -1617,7 +1617,7 @@ term_write(const char *buf, uint len)
             term.state = DCS_ESCAPE;
             term.esc_mod = 0;
           when '0' ... '9' or ';' or ':':  /* DCS parameter */
-            term.state = DCS_IGNORE;
+            term.state = DCS_PARAM;
           when '<' ... '?':
             term.dcs_cmd = term.dcs_cmd << 8 | c;
             term.state = DCS_PARAM;

```

**Comment by mintty** [comment]
Tracing back the commits, last version that works here is "supperss image rendering glich after resizing" of Aug 22, first version that breaks image display is "fix incorrect usage of when-clause" or Aug 23.
There are only a few commits from my repository between them, so maybe something went wrong when merging? I'm trying to hold on further commits until we're initially settled but there were some urgent fixes to be published, sorry.

**Comment by mintty** [comment]
Ah, well, here we are again! Thanks. (I may later remove some of the previous comments that are irrelevant now.)

**Comment by saitoha** [comment]
> The DECRQSS for which ESP P is being reused don't seem to work anymore.

It's also my mistake. I was insane.

```
--- a/src/termout.c
+++ b/src/termout.c
@@ -1128,15 +1128,15 @@ do_dcs(void)
       p += sprintf(p, "m\e\\");  // m for SGR, followed by ST
 
       child_write(buf, p - buf);
+    } else if (!strcmp(s, "r")) {  // DECSTBM (scroll margins)
+      child_printf("\eP1$r%u;%ur\e\\", term.marg_top + 1, term.marg_bot + 1);
+    } else if (!strcmp(s, "\"p")) {  // DECSCL (conformance level)
+      child_write("\eP1$r61\"p\e\\", 11);  // report as VT100
+    } else if (!strcmp(s, "\"q")) {  // DECSCA (protection attribute)
+      child_printf("\eP1$r%u\"q\e\\", (attr.attr & ATTR_PROTECTED) != 0);
+    } else {
+      child_write((char[]){CTRL('X')}, 1);
     }
-  when 'r':  // DECSTBM (scroll margins)
-    child_printf("\eP1$r%u;%ur\e\\", term.marg_top + 1, term.marg_bot + 1);
-  when CPAIR('"', 'p'):  // DECSCL (conformance level)
-    child_write("\eP1$r61\"p\e\\", 11);  // report as VT100
-  when CPAIR('"', 'q'):  // DECSCA (protection attribute)
-    child_printf("\eP1$r%u\"q\e\\", (attr.attr & ATTR_PROTECTED) != 0);
-  otherwise:
-    child_write((char[]){CTRL('X')}, 1);
   }
 }
```

```
$ echo -en "\033P\$qm\033\\"
$ P1$r0m
$ echo -en "\033P\$qr\033\\"
$ P1$r1;26r
$ echo -en "\033P\$p\"q\033\\"
$ P1$r61"p
$ echo -en "\033P\$q\"q\033\\"
$ P1$0"q
```

**Comment by saitoha** [comment]
> winimg_hibernate: Are you sure it's a good idea to keep around FILE pointers for each image? You may be getting a resource problem more serious than wasting some of the plenty of memory.

Indeed, Now I'm working to save the number of file descriptors.

**Comment by saitoha** [comment]
patch v2
[0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt](https://github.com/mintty/mintty/files/452466/0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt)

Now the number of temporary files are limited up to 16.
Every tmpfile can contain multiple images unless its size exceeds 16MB.
For more efficient implementation, we might have better to compress these images, using an embeddable routine such as [minigzip.c](https://github.com/madler/zlib/blob/master/test/minigzip.c) or [miniz.c](https://github.com/wkoszek/mini_gzip/blob/master/miniz.c).

**Comment by mintty** [comment]
Excellent. There's two things that I'd like to check out still:

In the reestablished response to the ESC P sequences I see an additional ^X inserted before the response now.

The exit position after an indented image is still inconsistent with xterm, see https://github.com/mintty/mintty/issues/572#issuecomment-236980261 (difference between 'X' and 'M' final positions); unfortunately, the clarification you quoted from @ttdoda does not mention this case. Maybe the current behaviour is more useful because you can easily add a CR control to go to the beginning of the line.

And please don't bother about compressing the images, I don't think it's worth the effort.

**Comment by saitoha** [comment]
> In the reestablished response to the ESC P sequences I see an additional ^X inserted before the response now.

DECRQSS was processed twice. fixed in 0273900.

> The exit position after an indented image is still inconsistent with xterm, see #572 (comment) (difference between 'X' and 'M' final positions); unfortunately, the clarification you quoted from @ttdoda does not mention this case. Maybe the current behaviour is more useful because you can easily add a CR control to go to the beginning of the line.

I would like to propose a new private mode(DECSET 7730, "sixel scrolls left" mode) to solve this issue.
```
CSI ? 7730 h
on: sixel scrolling moves cursor to beginning of the line

CSI ? 7730 l
off(default): sixel scrolling moves cursor to left of graphics
```
Implemented in 47a5e52.

I also added DECSET 1070: "private color register" mode(xterm).
Some applications such as [FFmpeg-SIXEL](https://github.com/saitoha/FFmpeg-SIXEL) requires global color registers.
demo: https://youtu.be/IkUTkqctP28

Patch V3: [0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt](https://github.com/mintty/mintty/files/453618/0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt)

**Comment by mintty** [comment]
Great. I see you're still making changes; when you feel confident to have a stable version, maybe you'd like to make another pull request?

**Comment by saitoha** [comment]
Patch V4: I think it's final version. 

[0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt](https://github.com/mintty/mintty/files/455405/0001-Add-initial-support-for-SIXEL-graphics-feature-DECSI.patch.txt)

Includes two imrovements.

- Now the mouse selection area is rendered over sixel images.
  I know this behavior is different with xterm/mlterm. But I belive it's more naturally for users.
<img width="622" alt="selection" src="https://cloud.githubusercontent.com/assets/1162739/18254192/3d50ff68-73d6-11e6-8c61-6821b36852f0.png">

- Now SIXEL is correctly erased by EL/ED sequences.
<img width="656" alt="erase" src="https://cloud.githubusercontent.com/assets/1162739/18254377/17d69930-73d8-11e6-9cee-8b70cec4a103.png">

**Comment by mintty** [comment]
I suggest you submit it as a pull request so you are automatically logged as its author. (Not sure whether I can "pull" from your repository with the same result.) Or I can apply your patch if you agree.

**Comment by saitoha** [comment]
@mintty OK, Now I have made a PR.

**Comment by mintty** [comment]
Released Sixel support in version 2.six.0.

**Comment by tkelman** [comment]
I just stumbled upon this feature while looking at the mintty home page - this is incredible, thank you both for working to get it integrated into mintty and released! Now I have an even better reason to get moving on bundling mintty by default with Julia on Windows.

**Comment by mintty** [comment]
Your feedback is appreciated, thanks.

**Comment by mintty** [comment]
Hi @saitoha, there is a crash condition when certain broken sixel files are output, only at certain font sizes...
A sample file is [biplane.six](https://github.com/mintty/mintty/files/3142811/biplane.six.txt).
I've uploaded a [patch](https://github.com/mintty/mintty/commit/42a0aaf12a5e31d60aa7ba596c0430c5928add7d) that adds a missing realloc where apparently the old image structure is reused to store a new one. At least that's what I guess about the purpose of that code.
I'd appreciate if you take a look at it. Also, why is the new img copied into the existing structure in stripes (`for` loop below patch)?
