### ISSUE TITLE
Use a fallback font to display missing characters

### ISSUE THREAD

**Issue by megapctr** [mintty/mintty#573]
My shell prompt displays a [hourglass character](http://www.fileformat.info/info/unicode/char/231b/index.htm) to indicate background jobs. This character is displayed as a rectangular block in mintty:
![image](https://cloud.githubusercontent.com/assets/4096683/17427580/08f063ce-5ae2-11e6-8937-f09df8c0aa68.png)

Gnome terminal displays the character properly:
![image](https://cloud.githubusercontent.com/assets/4096683/17427624/4ed000d4-5ae2-11e6-9e14-bf0821e69df3.png)

[This is how I print this character.](https://github.com/megapctr/.df/blob/master/fish/functions/fish_prompt.fish#L19) I'm using fish shell, but the problem is present on bash as well.
I tried various fonts, but the problem seems to be unaffected by this.

What else could I try to fix the problem?

**Comment by megapctr** [comment]
I'm using cygwin but on its side everything looks good:
```
~ > printf '\u231b' | hexdump
0000000 8ce2 009b
0000003
```

**Comment by mintty** [comment]
The rectangular block indicates that the character is not available in the font being used. This is not a bug as such. However, the character is displayed also, e.g., in notepad, configured to the same font as mintty. The only explanation that comes to my mind is that different "font fall-back" mechanisms of Windows are used. I don't know how this could be changed. Maybe it's not possible with the current output API (ExtTextOut).

**Comment by megapctr** [comment]
Yes, looks like notepad goes through available fonts to find one with the missing character. It would be nice if mintty could do that. Thanks for help anyway :smile:

**Comment by mintty** [comment]
Windows Font Linking can be configured in the registry:
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink
If you add an entry for your preferred mintty text font, it might work.
Maybe something similar can be achieved by Windows API calls, so mintty could establish some reasonable default behaviour. Suggestions welcome.

**Comment by mintty** [comment]
Further information:
https://msdn.microsoft.com/en-us/goglobal/bb688134.aspx
http://archives.miloush.net/michkap/archive/2005/10/01/476022.html

**Comment by Perlence** [comment]
Maybe this has to do with font, for example, DejaVu Sans Mono doesn't have symbols `⏎ \u23ce` and `⚠ \u26a0`, although they're shown correctly in mintty.

**Comment by Perlence** [comment]
Font linking does help.

**Comment by mintty** [comment]
Good that you could configure a personal workaround.
However, as a generic improvement, this approach is not suitable for mintty.
See my comment in #605.

**Comment by Perlence** [comment]
@mintty Latest SciTE supports font fallback and also ligatures:

![SciTE](https://cloud.githubusercontent.com/assets/1044300/19655594/4eb8d9ae-9a25-11e6-80e3-17347ba797ff.png)

**Comment by mintty** [comment]
Thanks, I see in the code it uses ExtTextOutW like mintty; if you can identify where/how it handles font fallback and ligatures, I will take a closer look.

**Comment by mintty** [comment]
Release Uniscribe support in 2.7.1.
This does not solve *all* potential font fallback cases, though.

**Comment by musm** [comment]
thank you!

**Comment by Perlence** [comment]
@mintty Amazing work!

**Comment by mintty** [comment]
Released 2.7.5 with default FontRender=uniscribe.
