### ISSUE TITLE
When updating a config option via the right click, my configs comments get obliterated - an autosave would be good.

### ISSUE THREAD

**Issue by PhilipOakley** [mintty/mintty#574]
It looks like the right-click options panel will overwrite a user's .minttyrc file, even if the file contains a user's manual comments.

In my case I had URLs and alternate colour settings (all behind # comments) within the .minttyrc. 

When I went to look at the 'show bold as font' option (to help view some man page changes - to support Git for Windows on MSYS2) I found that all my comments and alternates had been changed, and no backup had been saved.

Can an auto-backup option be included?

If I understand the code (I guessed that I should look here: https://github.com/mintty/mintty/blob/master/src/config.c#L827) the save_config() should rename the old file to .bak.nnnn on the first occurence, and then it can create the new .minttyrc.  It (autosave) could even have it's own config (default to autosave if not set) so if the user unsets it the save_config() then wouldn't do the backup.

The key point is that it allows the user to recover their old data once they discover it's been 'lost'.

**Comment by mintty** [comment]
Saving the comments is on my to-do list but I doubt backup would be a sufficient workaround because they would still be lost after saving twice...

**Comment by PhilipOakley** [comment]
Thanks; I was thinking that normally a user has very few changes of the config, so as long as it's saved the once just before the first update of a session then all the remaining changes shouldn't save over the top of the back up. That should be an easy flag to use.

Meanwhile I was thinking that the backup should also get a sequence number of some sort. I've seen them before in the msysgit/git-for-windows, though the backup number may be from the makefile.

Are you expecting folks to do many different sessions with config updates (that go through that save routine)?

I've been using the mintty for quite a while now (since the G4W development started) and this is the first time I've been hit, so I'm thinking the backup won't be that often.

**Comment by mintty** [comment]
I think typically while people work on configuration they try out multiple options and settings so they save quite often for a while. Unless you save every single version, backup won't help in keeping the comments.

**Comment by mintty** [comment]
Released in 2.6.1.
