### ISSUE TITLE
winpty and scripts in sub folders

### ISSUE THREAD

**Issue by tlescoat** [mintty/mintty#575]
`winpty` seems not to work when executing a script which is in a subfolder when the path contains slashes.
This is for mintty 2.0.3 which is quite old, but I did not see a fix in the changelogs, so I don't know if it happens with latest version.

Real-world example:

    $ winpty Scripts/create_vs_projects.bat
    'Scripts' is not recognized as an internal or external command, operable program or batch file.

Note: it used to work as expected in version of MinTTY older than the 2.0.3 ("expected" = actually calling the script).

**Comment by mintty** [comment]
I guess you have changed more than the mintty version in your environment as I do not see how this should be related to mintty.
Intending to close.

**Comment by tlescoat** [comment]
Well, that came from an installation of Git for Windows. I literally just ran the installer, and voila. They say they use stock mintty (well, unmodified 2.0.3 version), maybe it is more related to msys ?

**Comment by mintty** [comment]
Whatever; winpty cmd/some.bat works here.
