### ISSUE TITLE
ctrl-d not working properly

### ISSUE THREAD

**Issue by simenfd** [mintty/mintty#577]
I am using
```
$ mintty.exe --version
mintty 2.0.3 (x86_64-pc-msys)
(C) 2015 Andy Koppe
License GPLv3+: GNU GPL version 3 or later
There is no warranty, to the extent permitted by law.
```

When I run "bzip2" and write some text, then try to CTRL-D to EOF, nothing happens.  No matter if I try it after a newline, multiple CTRL-D, etc, I just can't close the stream.

Is there something wrong with the handling of CTRL-D?

**Comment by mintty** [comment]
Running just bzip2 in cygwin will not expect input. What application do you run? `type bzip2`
Interpreting Ctrl+D as EOF is not the task of mintty anyway, check `stty -a`.

**Comment by simenfd** [comment]
```
$ which bzip2
/mingw64/bin/bzip2
```

It does expect input.  Documentation says it reads from stdin, and it works in regular cmd.exe when using CTRL-Z to terminate.

```
$ stty -a
speed 38400 baud; rows 24; columns 80; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
eol2 = <undef>; swtch = ^Z; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff
-iuclc ixany imaxbel
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -tostop echoctl echoke
-flusho
```

**Comment by simenfd** [comment]
just adding, on my regular Ubuntu CTRL-D work (you have to press it twice though)

**Comment by mintty** [comment]
Oh, so you're using a MinGW, not a cygwin or MSYS binary. MinGW binaries' I/O works like Windows native programs' I/O and does not interact well with cygwin or MSYS (which mintty hosts). This is an instance of the pty problem, e.g. #380 and basically #56.

**Comment by simenfd** [comment]
thanks for your explanation and clarification!

**Comment by shula** [comment]
i'm on MINTTY 3.6.1  & MSYS2, and CTRL+d doesn't close the terminal, or open files.
e.g.

bash$ cat > file.txt
asdasd
asdasd
<Ctrl+D>  -- nothing.

Other CTRL shortcuts do work as expected:
CTRL+A: selected all text
CTRL+F: toggled fullscreen
CTRL+V: paste (my settings in .minttyrc:   CtrlShiftShortcuts=yes)
CTRL+C:   nothing
CTRL+D:  (on empy line)   nothing
CTRL+Fn+B:   "Quit (core dumped)" (but finally exited.
```````

**Comment by mintty** [comment]
Check your stty settings, maybe EOF is remapped. Anyway, as noted above, interpreting Ctrl+D is not handled by the terminal.
