### ISSUE TITLE
New versions of character graphics is not displayed with the default settings. CygWin, MC

### ISSUE THREAD

**Issue by DiNGeR2Sergey** [mintty/mintty#578]
I updated CygWin noticed that "mc" longer no displayed pseudographics. Even in the latest version Minty - 2.5.0 (x86_64-pc-cygwin).
That's what I see:
![mintty_250](https://cloud.githubusercontent.com/assets/13885422/18084829/5f5b6938-6eb1-11e6-9ba7-55cdddb01c45.PNG)

Checked all the available versions in CygWin, nowhere does not work - 2.5.0, 2.4.3 and 2.4.0

In the updated CygWin, replaced mintty.exe the old version, so works. I have an old version only 2.2.2, and 2.2.1. Here is how I see the old version 2.2.2 (x86_64-pc-cygwin):
![mintty_222](https://cloud.githubusercontent.com/assets/13885422/18087093/00c5a752-6ebc-11e6-9cb0-a9bbba84f8f4.PNG)

In version 2.5.0 there is pseudographics, if you increase the font(Lucida Console) on two points, from 9pt to 11pt.
Here:
![mintty_250_11pt](https://cloud.githubusercontent.com/assets/13885422/18087288/1892ae42-6ebd-11e6-864d-7ba1311b6aee.PNG)

The problem is repeated on two systems:
1) WinServer 2008R2 Standard connection for RDP
2) Win 7 Ultimate locally, but with disabled anti-aliasing font.

All checked in the default settings.

**Comment by mintty** [comment]
2.4.0 introduced
  * Manual drawing of VT100 line drawing graphics (#130, ~#551).

to ensure they are always shown (even if missing in the font), not to prevent their display, of course.
Line drawing width is being scaled with the font size; here apparently I forgot to limit the result to a minimum of 1...

**Comment by mintty** [comment]
Fixed in 2.5.1.

**Comment by DiNGeR2Sergey** [comment]
Thank you very much! It works.
