### ISSUE TITLE
how does mintty determine what shell to run?

### ISSUE THREAD

**Issue by musm** [mintty/mintty#582]
I installed mysys2 and installed the proper gcc to compile mintty using `make`

I copied the resulting `mintty.exe` no another folder `C:\mintty\mintty.exe`. 

Now I already have Git  for windows installed, which installed bash and all those tools to my path.
It looks like mintty  detects the  bash  I have in my path and runs it automatically.  

How can this behavior be modified?

**Comment by mintty** [comment]
See the mintty manual page:

SYNOPSIS
       mintty [OPTION]... [ - | PROGRAM [ARG]... ]
