### ISSUE TITLE
add padding

### ISSUE THREAD

**Issue by musm** [mintty/mintty#583]
Add an option to add some padding around the border

**Comment by mintty** [comment]
See the manual page, option `Padding`.

**Comment by musm** [comment]
Sorry but I can't seem to find the manual page
I looked: https://github.com/mintty/mintty/wiki

**Comment by musm** [comment]
I also can't seem to find how to change the ctrl+shift+copy to ctrl+copy and so forth ...

**Comment by j16180339887** [comment]
`mintty.exe -o Padding=5`

**Comment by j16180339887** [comment]
![GitHub Logo](http://i.imgur.com/YFBCCzH.png)

**Comment by mintty** [comment]
In cygwin or msys, `man mintty` shows the manual page.
It's also linked from the Mintty homepage http://mintty.github.io/; 
I'll check how to get it more prominent, e.g. also linking from the Wiki.
Mapping keys that are not mintty shortcuts is not the task of mintty, e.g. Ctrl+Shift+left sends a certain escape sequence which can be remapped with `$HOME/.inputrc` for your shell and many line-oriented applications, or more specifically for screen-oriented applications.

**Comment by j16180339887** [comment]
I agree.
Maybe you should remap keys in .inputrc,
or maybe you want to use tmux or GNU screen to do that.

**Comment by musm** [comment]
Thanks. I guess I was having difficulties finding the manpage since mintty with git on windows doesn't include it

**Comment by musm** [comment]
Any guides or places to look on how to get the remaps working in inputrc? I searched online to no avail.
I would love ctrl+shift+c to copy and ctrl+v to paste  and also ctr+left to left select and ctrl+right to right select

**Comment by j16180339887** [comment]
I don't know much about .inputrc, 
and I don't think you could done that by using git on windows.
I usually select and copy text by using mouse, paste by using shift + insert

**Comment by j16180339887** [comment]
I recommend [git for windows](https://github.com/git-for-windows/build-extra/releases), [msys2](https://msys2.github.io) or [cygwin](https://cygwin.com/install.html) .
Since they have package manager, you can install tmux or gnu screen and then [bind keys](http://stackoverflow.com/questions/1322594/cygwin-command-to-copy-to-windows-clipboard)

**Comment by mintty** [comment]
I would not suggest to involve a middleware layer just for the purpose to configure your input; note that using tmux etc comes with a few other limitations, particularly about input.

I attach my config file as an example, to be moved to `$HOME/.inputrc`: [HOME.inputrc.txt](https://github.com/mintty/mintty/files/461067/HOME.inputrc.txt)

Unfortunately, there does not seem to be a cygwin manual page for it, see https://cnswww.cns.cwru.edu/php/chet/readline/readline.html or https://cnswww.cns.cwru.edu/php/chet/readline/readline.html

To find out which escape sequence is actually sent by a key you want to remap, the easiest way in most cases is: type Ctrl+V in a shell, then the key.

**Comment by j16180339887** [comment]
But I think what he want is selecting some text and copying it to clipboard.
I don't think .inputrc could do that right, could it ?

**Comment by mintty** [comment]
No, the request (above) was "how to change the ctrl+shift+copy to ctrl+copy and so forth".
But it's getting more and more off-topic...

**Comment by j16180339887** [comment]
I don't understand what does `ctrl+shift+copy` mean.
I don't see "copy" key on the keyboard.

I'm serious.
