### ISSUE TITLE
SIXEL clipping area calculation is wrong

### ISSUE THREAD

**Issue by saitoha** [mintty/mintty#584]
v2.6.0 sixel support has wrong calculation problem of clipping area because it always assumes Padding=1.

<img width="636" alt="padding 5" src="https://cloud.githubusercontent.com/assets/1162739/18409937/d7251f68-778f-11e6-920b-d0c2ae938a4e.png">

patch:
https://github.com/saitoha/mintty-sixel/commit/72378a7c34aefd03253f372baa203149d932f1b3

**Comment by mintty** [comment]
Thanks, I'll fix that. I also notice that sixel image refresh causes some flickering, showing an intermediate picture of turned "L"-shape cell borders for an instance. It's not too bad, but maybe you find a way to avoid that.

**Comment by saitoha** [comment]
I confirmed this problem is fixed. Thanks.
