### ISSUE TITLE
Disabling Ctrl-Click

### ISSUE THREAD

**Issue by kbukin1** [mintty/mintty#585]
A touchpad on a laptop may require sensitivity adjustment. The one I happened to have now has only one setting I feel comfortable with. But the setting does not work well with mintty. The touchpad generates unintentional click events while I’m typing which often coincide with Ctrl key pressed. That results in mintty trying to open a file named with whatever mouse cursor happened to be over and an annoying “The system cannot find the file specified” dialog. 

I never use Ctrl-click feature. Could you add an option to disable Ctrl-Click behavior which opens file/dir? The option does not have to be in “Options” dialog. A setting in .minttyrc is good enough.

Thank you,
Konstantin.

**Comment by mintty** [comment]
See the manual page, option `OpeningClicks`; values 2, 3 or 0 may suit you. (#545)

**Comment by mintty** [comment]
Also duplicate of #220 (for the records).
