### ISSUE TITLE
Obviously mintty bug? - reading from STDIN stops the output also before the user input

### ISSUE THREAD

**Issue by MaxPerl** [mintty/mintty#590]
Hello, 
I have a problem with perl input from STDIN. If you ask for user input the script doesn't print the output before the input, but waits for the input.

here a simple perl script example:

`
print "What is your name?\n";
my $name = ;
print "\nHello $name\n";
`

the output should be (perl script.pl):
What is your name

Hello name

But instead of this. The shell doesn't output anything until you press enter
this bug only affects the mingw64 shell; the msys2 and mingw32 shell work just fine!!!

Also C programs seems to be affected. As a workaround you can install winpty with "pacman -S winpty". With this everything works fine...

**Comment by mintty** [comment]
This is quite *obviously* **not** a mintty bug. Therefore I'm closing it before explaining later.

**Comment by mintty** [comment]
Assuming that you use a non-cygwin/msys version of perl (and note that mingw is not msys), and considering it works with winpty, this is an instance of the pty interoperability restriction we're facing.
See #363 for a similar issue and link to the base problem.

**Comment by MaxPerl** [comment]
Thanks for your answers. In the MSys2 IRC the People said that I should post the bug here, because it looks lika a mintty bug. Sorry if this was not the reason and posting here was wrong...
I solved this in my perl scripts with `$| = 1;`. But this is only a Workaround. It would be better, if the shell behaves as usual and print the output if a newline was sent. Where the error is I don't know...
