### ISSUE TITLE
Fix heap corruption problem in SIXEL decoder

### ISSUE THREAD

**Issue by saitoha** [mintty/mintty#591]
patch:
https://github.com/saitoha/mintty-sixel/commit/6e2a5a96d309f0faa3217ffd36defab6a601b081

- Parameters for DECGRA are not verified. It may cause integer overflow and wrong size argument can be passed to malloc.
- Huge SIXEL input data can cause DoS. We should restrict image width and height.

**Comment by mintty** [comment]
Thank you;
maybe the size limitation should be dynamic?
Either current window size (win_get_pixels()) or current monitor size (~win_get_screen_chars() not scaling to cell size); how does xterm handle this?

**Comment by saitoha** [comment]
> maybe the size limitation should be dynamic?

I can't imagine the use case of exceeding the limit 4096x4096.
I think most people will be satisfied with this fixed limit.
BTW xterm seems to restrict sixel size to 1000x1000, it's insufficient for me.

win_get_pixels() and win_get_screen_chars() don't seem to have problems for me.

**Comment by mintty** [comment]
My concern was not the actual size but the fact to have a constant size at all. What if next year monitors get even higher resolution, and processors fast enough to process that? I'd rather avoid to adjust the limit then. So what about twice the monitor size (each direction)?

**Comment by mintty** [comment]
Released in 2.6.1.
