### ISSUE TITLE
Byte overflow problem in SIXEL decoder

### ISSUE THREAD

**Issue by saitoha** [mintty/mintty#593]
Forwarded from https://github.com/mattn/go-sixel/issues/5.

> The color register #255 is treated as 257th color in mintty.
> https://github.com/mintty/mintty/blob/324152bd503dac16fc7becfa06d53f52080d01cc/src/sixel.c#L599

> It will cause overflow in https://github.com/mintty/mintty/blob/324152bd503dac16fc7becfa06d53f52080d01cc/src/sixel.c#L395.

**Comment by saitoha** [comment]
test patch:
https://github.com/saitoha/mintty-sixel/commit/7b6bf811ba617e68a6717cbb5e06cb21470207c6

**Comment by mintty** [comment]
I wonder why and how SIXEL colour registers interfere with mintty's text colour handling.
What if the colours are redefined (with escape sequences); would that spoil image display?
Maybe the two mechanisms should be decoupled?

**Comment by saitoha** [comment]
I think if we need to emulate old hardware faithfully, text color registers have to be shared with that of SIXEL.
Actually, some old hardware users use -m(mapfile/fixed palette) option to integrate graphics on their 4bpp/8bpp framebuffer terminal.
But we can also implement separated color registers for each images. This strategy is convenient for users in modern GUI environment. Current mintty choose it.

**Comment by mintty** [comment]
So if there is currently no dependence of SIXEL colors on text 256 colors (if I understood you correctly, haven't had time to test it yet, sorry), why was there this surprising interference of the 257th color with mintty default color indications? Just trying to understand.

**Comment by mintty** [comment]
I was confused by "257th" color because a few internal attribute values above 256 are used for foreground etc by mintty. Unrelated, so forget my previous comments here.

About the patch: Do we really need *all* the type definitions, int8, int16, int32, uint8... I'm asking because that doesn't compile with an older gcc version.

**Comment by saitoha** [comment]
OK I use definitions of src/std.h and src/config.h in a664ed8.
Memory leak issue reported by https://github.com/saitoha/libsixel/issues/50#issuecomment-249444867 is fixed with e92d9a5.

**Comment by mintty** [comment]
Thanks a lot.
See also https://github.com/saitoha/libsixel/issues/50#issuecomment-249847726

**Comment by saitoha** [comment]
Thanks for merging!

**Comment by mintty** [comment]
Released 2.6.2.

**Comment by mintty** [comment]
I'm afraid I have to revert the latest patch from this issue, in order to resolve #740.

**Comment by mintty** [comment]
Released 3.0.2.
