### ISSUE TITLE
Scrolling slows down with commit b2d528b

### ISSUE THREAD

**Issue by saitoha** [mintty/mintty#594]
This commit might cause DC handle leak.
It seems to affect to the rendering performance.
https://github.com/mintty/mintty/commit/b2d528b7afc78167c589908613a990af0b1e641a#diff-bfc4b7247fef77f34620b54aa8b46976R1376

**Comment by mintty** [comment]
I had noticed while working on proper detection of characters to be "expanded" that win_char_width often fails (particularly on such "interesting" characters) with dc being NULL at that time.
So I added
  SelectObject(dc, fonts[FONT_NORMAL]);
on the assumption to be on the safe side. Maybe a paired ReleaseDC would help (but a quick-check had shown that this is often missing for other invocations of SelectObject, so my other assumption had been this wasn't necessary).
Thanks for the observation.

**Comment by mintty** [comment]
DC handle leak still to be checked.
But I do not reproduce a noticeable scrolling or other rendering performance. Can you describe the effect?

**Comment by saitoha** [comment]
Now I realize rendering performance problem is revealed only when SIXEL images are displayed.

![slow](https://cloud.githubusercontent.com/assets/1162739/18846045/2a869c96-845f-11e6-961b-1276330c5d51.gif)

```
```

![normal](https://cloud.githubusercontent.com/assets/1162739/18846057/390bbd1e-845f-11e6-9e44-872edb961c5a.gif)

**Comment by mintty** [comment]
Applied similar change, thank you.

**Comment by saitoha** [comment]
It's OK now. Thanks.

**Comment by mintty** [comment]
Released 2.6.2.

**Comment by mintty** [comment]
Released 2.6.2.
