### ISSUE TITLE
Command ssh could not work.

### ISSUE THREAD

**Issue by HeringGitHub** [mintty/mintty#596]
OS: WIN10 1607 64bit
Command ssh could not work for any host. But if I use putty, command ssh work well.
e.g.
ssh test@127.0.0.1
socket: Socket operation on non-socket
ssh: connect to host 127.0.0.1 port 22: Socket operation on non-socket

**Comment by mintty** [comment]
You are likely to be using an incompatible build of ssh from cygwin. Putty has its own ssh handling built-in so that's not really comparable.
What do `uname -a` and `type ssh` say?

**Comment by HeringGitHub** [comment]
Well, I mean the reason of it could not work irrespective of os. In fact, not only ssh, but telnet could not work. The same situation also occurred in the "openssh for windows". However these commands worked well before a few days ago. Previously I blamed its to updating os for my PC, but obvious that's not the reason.
uname -a
CYGWIN_NT-10.0 HeringPC 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64 Cygwin

**Comment by mintty** [comment]
> What do uname -a and `type ssh` say?
?
Anyway, as it also happens outside mintty, why do you submit a mintty issue report?

**Comment by HeringGitHub** [comment]
Ah, I'm sorry, I just want to know anyone else run into a situation like this. 

uname -a
CYGWIN_NT-10.0 HeringPC 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64 Cygwin
type ssh
ssh is /usr/bin/ssh

It seems useless.

**Comment by mintty** [comment]
Unlikely to find other users with similar problems here. I don't see how this should be related to mintty. Can we close it?

**Comment by HeringGitHub** [comment]
Ok, thank you. I will try some other ways.
