### ISSUE TITLE
Window moves/doesn't stay in position

### ISSUE THREAD

**Issue by xelra** [mintty/mintty#599]
I'm using the latest versiony of Cygwin and Mintty on Windows 10. When I resize the terminal to be the exact vertical 50% split of the screen, by dragging the window to the far left edge, I encounter a problem in vim.
When I'm in vim and the terminal window is sized like described above and then I set the columns with `:set columns=x`, the window doesn't only resize, but also moves slightly away from the edge. This is especially problematic in neovim, where it seems to somehow invoke `:set columns` on each start of neovim, which will always move the terminal window from this position.

This doesn't happen when the terminal window is floating freely or when it's in the position where it jumps to after the first time opening neovim. The problem would reoccur when moving the window back into the exact vertical split arrangement though.

**Comment by mintty** [comment]
Cannot reproduce on Windows 7.
Which escape sequence control is used to resize the window?
Was Windows AeroSnap involved in attaching the window to the edge?
Any difference if you position the window by command-line option `-p left`?

**Comment by xelra** [comment]
@mintty Yes, I think using this method (resizing it intp vertical split by dragging it to the left edge) is AeroSnap.

I've run `mintty -p left` and found out that it doesn't position the window at the left edge, but instead exactly at the same distance to the edge that my resized window has. Which is a bit less than 1 column from the edge.

**Comment by mintty** [comment]
Please run `mintty -p left -Rx`, let it snap off the edge, then exit. What does it report?

**Comment by xelra** [comment]
It reports `mintty -s 126,40 -p 0,78`.

**Comment by mintty** [comment]
That indicates that the window is at X position 0 in the Windows monitor coordinate system.
Do you run a multi-monitor setup? Is this monitor positioned above or below the other monitor and maybe shifted out left a few pixels (you can drag monitors in the Windows control panel)?

**Comment by xelra** [comment]
No, I only have exactly 1 monitor. But it's connected to a notebook via the docking station. The notebook is closed and Windows also does only show 1 monitor in the display settings.

**Comment by xelra** [comment]
I'm not exactly sure whether this is a bug in mintty or specific to my configuration.

Anyway, unfortunately my computer broke down yesterday and I cannot follow up on this any further. :sob: :cry:

Thank you for your efforts in trying to debug this with me.

**Comment by mintty** [comment]
I could reproduce this on Windows 10. Tracing revealed that both screen geometry and window geometry at the API were correct as expected.

It seems to be a Windows bug, see http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_desktop/windows-10-build-10122-offset-windows-borders-are/fa35041e-3ee4-4af8-9277-2edf08a2526a?auth=1.
Did you also run a Window Technical Preview release?

**Comment by mintty** [comment]
Also note it doesn't happen if you start borderless (`-Bvoid`).

**Comment by mintty** [comment]
Well, it doesn't seem to be *that* particular bug, but yet I'm convinced it's a Windows issue.

**Comment by mintty** [comment]
Release 2.7.0 has an option `-Rm` to report the Windows monitor layout.

**Comment by mintty** [comment]
See also https://stackoverflow.com/questions/35259756/wpf-and-windows-10-invisible-border-around-windows.
