### ISSUE TITLE
'mingw32' not supported

### ISSUE THREAD

**Issue by toiiggww** [mintty/mintty#603]
When I try to make mintty on msys, got this message.

> $ make
#cd src; make exe
#cd src; make bin
cd src; make
make[1]: Entering directory `/d/Documents/GitHub/mintty-2.6.2/src'
Makefile:58: *** Target 'mingw32' not supported.  Stop.
make[1]: Leaving directory `/d/Documents/GitHub/mintty-2.6.2/src'
make: *** [exe] Error 2

**Comment by elieux** [comment]
What does `uname` and `which gcc` say? Mintty can only be built as a Cygwin/MSYS program, using Cygwin/MSYS gcc.

**Comment by mintty** [comment]
That is correct. Mintty compiles with msys gcc, not with mingw gcc. The distinction may be a little bit obscure as long as you're not familiar with it.
See http://www.mingw.org/wiki/HOWTO_Create_an_MSYS_Build_Environment about the environment.
I will check where to add a hint about this with mintty.

**Comment by toiiggww** [comment]
I try to download MSYS from sf.net , it's suggest me to download the MinGW Installer, then ,I downed it. and install basic environment of msys, it's is mingw by default. I tried modified argument of msys.bat changed to msys, but fail aging. 
the uname and which gcc output as follow :
> $ uname
MSYS_NT-6.2

ItFunly@WIN-TPTT09IF8JC ~
$ cd /d/Documents/GitHub/mintty-2.6.2/

ItFunly@WIN-TPTT09IF8JC /d/Documents/GitHub/mintty-2.6.2
$ make
#cd src; make exe
#cd src; make bin
cd src; make
make[1]: Entering directory `/d/Documents/GitHub/mintty-2.6.2/src'
Makefile:58: *** Target 'mingw32' not supported.  Stop.
make[1]: Leaving directory `/d/Documents/GitHub/mintty-2.6.2/src'
make: *** [exe] Error 2

ItFunly@WIN-TPTT09IF8JC /d/Documents/GitHub/mintty-2.6.2
$ which gcc
/mingw/bin/gcc.exe

ItFunly@WIN-TPTT09IF8JC /d/Documents/GitHub/mintty-2.6.2
$ gcc --version
gcc.exe (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by toiiggww** [comment]
after use `mingw-get install msys-dvlpr` done , build successed.

**Comment by mintty** [comment]
`mingw-get` sounds like you installed old MinGW/MSYS which isn't updated anymore.
MSYS2 (supporting MinGW 32/64) is found on https://msys2.github.io/.
To build mintty there, you would `pacman -S gcc make`.
But nice to here that my efforts to keep mintty compilable on old MSYS were not in vain.

**Comment by toiiggww** [comment]
It's really great work, as you say, i down msys2, and it's has installed and set as default shell.
