### ISSUE TITLE
Misplaced underline

### ISSUE THREAD

**Issue by Perlence** [mintty/mintty#604]
I'm using mintty 2.6.1 and font [Iosevka Term](https://github.com/be5invis/Iosevka) 1.9.4.

To the left you can see _mintty's_ window, and _st's_ window is to the right. It's clear that underline is higher than it should be.

![mintty and st](http://i.imgur.com/7ao4t2d.png)

Here are font options:

![Font options](http://i.imgur.com/rITKCQq.png)

cc @be5invis

**Comment by mintty** [comment]
Normally, mintty uses an underlined font as generated by Windows, and that is actually the case with Iosevka Term. So the misplacement is caused by Windows, maybe caused by some strange metrics information of the font. So it may actually be a font bug.

Mintty has a workaround for bad underline placement already and draws underline itself in such cases which actually looks fine also with Iosevka Term.
But that workaround checks the other direction (underline outside of character cell), not this case. To include Iosevka in that workaround, suitable criteria will have to be found.
Or maybe mintty should always draw underline itself and never use Windows underlined font, or as an option?

**Comment by be5invis** [comment]
@mintty in `post` table?

**Comment by be5invis** [comment]
Maybe @mintty @Perlence can try to build the latest Iosevka in `master` and check whether it is determined by `post.underlinePosition`. AFAIK most applications do not use this value.

**Comment by mintty** [comment]
I have implemented a new option `UnderlineColour` on that occasion. While its main purpose is to configure a dedicated colour for all lining attributes (underline, doubly underline, strikeout, overline) it also enforces self-drawn linings for all of them.

**Comment by mintty** [comment]
@be5invis: Your comments sound like you're familiar with TrueType tables. Maybe you can help out with issue #601; the question is how could font ligature information be accessed using the Windows API...

**Comment by be5invis** [comment]
@mintty You cannot enable ligatures unless you switch from GDI to DirectWrite or FreeType.

**Comment by Perlence** [comment]
@mintty The fix does the trick! Thank you.

![iosevka](https://cloud.githubusercontent.com/assets/1044300/19570398/7d92236e-9702-11e6-9809-b2e7bd898500.png)

**Comment by kangjianbin** [comment]
Hi Mintty,

The line height is inconsistent for bold font. See following screen shots with/without 'UnderlineColour'.
See 'a.pl':
<img width="255" alt="ulc" src="https://cloud.githubusercontent.com/assets/121803/19619132/f5cd9710-9891-11e6-80ec-6dc96b150e5a.png">
<img width="363" alt="no-ulc" src="https://cloud.githubusercontent.com/assets/121803/19619133/f70eeeee-9891-11e6-9cb9-12f6a90b7492.png">

It may be as designed. But I think the second one (without UnderlineColour) is better.
What is your opinion?

**Comment by Perlence** [comment]
Yes, underline on Iosevka font also seems bit lower by a pixel with UnderlineColour.

**Comment by kangjianbin** [comment]
And the line looks thicker also.

**Comment by mintty** [comment]
The font-derived underline of Iosevka was reported to be too high , so with the fix it's of course lower.
The thicker underline for bold attribute seems indeed questionable. To be checked.

**Comment by mintty** [comment]
Released improved underline handling and option in 2.7.0.

**Comment by mintty** [comment]
Release 2.7.1: New option `UnderlineManual` to enforce manual lining with default colour.
