### ISSUE TITLE
Highlight in taskbar fails while window is minimized in 2.7.0

### ISSUE THREAD

**Issue by octangula** [mintty/mintty#607]
Having recently updated from an unknown old version, I've noticed that the mintty window is not lighting up on my taskbar when terminal bells happen. After some testing, it appears that it lights up correctly when the window is open and inactive, but fails to light up when the window is minimized.

This issue only affects 2.7.0; the only other version available in the Cygwin installer (2.6.2) does not have this issue. Additionally, this behaviour has only been observed with the 32-bit version; I do not have access to a 64-bit version so I am unable to test it.

**Comment by mintty** [comment]
Cannot reproduce. Here it flashes nicely.

**Comment by octangula** [comment]
Helps if I mention the important things, like OS version. Occurs on Windows 7, 64-bit. Untested on other versions. It's also possible that I've not isolated the cause correctly.

**Comment by mintty** [comment]
I tried Windows 7 64-bit too, with both Cygwin 64-bit and Cygwin 32-bit. Worked for me.

**Comment by octangula** [comment]
This is getting strange. With 2.6.2, it works correctly at first, and then after some time, it stops working. I cannot see anything in my .minttyrc that would suggest this behaviour. Which makes me wonder if the issue lies elsewhere...

**Comment by mintty** [comment]
This seems to be a property of the Windows flashing function. After it flashes, it continues to "gloom" for a while. I suppose while it's still doing that, it does not fully flash again. Just speculating, though.

**Comment by mintty** [comment]
Any further diagnostics available? Or maybe a screen video?

**Comment by mintty** [comment]
Released 3.0.2.
