### ISSUE TITLE
cmd encode and mintty encode

### ISSUE THREAD

**Issue by gMan1990** [mintty/mintty#609]
**OS: Windows 7 Professional with Service Pack 1 Build 7601 x64 zh-cn**

**the cmd default chcp is 936(The default font is a dot matrix font), you can change follow this step:**
1、chcp 936    (GBK)
2、Right-click the title bar, properties, click OK to make the settings take effect
if i set the font to ‘新宋体’ and run
chcp 65001 && "D:/Genuitec/MyEclipse 2016/binary/com.sun.java.jdk8.win32.x86_1.8.0.u66/bin/java.exe" -jar "D:/static_code_analysis/Checkstyle/checkstyle-7.2-all.jar" -c "D:/static_code_analysis/Checkstyle/google_checks.xml" "E:\Workspaces\test\common.xml"
this issues(https://github.com/checkstyle/checkstyle/issues/3569) can be fixed
![image](https://cloud.githubusercontent.com/assets/5050994/20469852/277e41ca-afde-11e6-8ce1-79416c80fb01.png)

**then use mintty (options > Text > Character > GBK)**
ipconfig output is right, checkstyle output is wrong
![image](https://cloud.githubusercontent.com/assets/5050994/20469945/19369fd0-afdf-11e6-8f0a-91e70acd2abd.png)
**then use mintty (options > Text > Character > UTF-8)**
ipconfig output is wrong, checkstyle output is right
![image](https://cloud.githubusercontent.com/assets/5050994/20470056/fc1ea892-afdf-11e6-89a3-1aa2c4fa3f6b.png)
**-------------------------------------------------------------------------**
**Option Ⅱ**
**cmd**
1、chcp 65001           (UTF-8)
2、Modify the font, do not use dot matrix fonts
3、run    "D:/Genuitec/MyEclipse 2016/binary/com.sun.java.jdk8.win32.x86_1.8.0.u66/bin/java.exe" -jar "D:/static_code_analysis/Checkstyle/checkstyle-7.2-all.jar" -c "D:/static_code_analysis/Checkstyle/google_checks.xml" "E:\Workspaces\test\common.xml"
the checkstyle output is right

**then use mintty (options > Text > Character > GBK)**
![image](https://cloud.githubusercontent.com/assets/5050994/20470205/393b4298-afe1-11e6-9362-cd078cc867f2.png)
**then use mintty (options > Text > Character > UTF-8)**
output looks like Option Ⅰ

**Comment by mintty** [comment]
Duplicate #376.
For Java, your workaround would be
```
java -Dfile.encoding=UTF-8
```
or more generally
```
java -Dfile.encoding=`locale charmap`
```
.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
