### ISSUE TITLE
french po file

### ISSUE THREAD

**Issue by Gozer-404** [mintty/mintty#611]
Related to issue #537, here is a first version of the `french.po` file, BTW there is apparently no 'install' entry in the Makefile for installing the po files (in `/usr/share/mintty/lang/` ?)
_(Sorry, maybe it's not the right place to provide this)_

- File renamed to `fr_po.txt` (instead of `fr.po`, as this one is rejected): [fr.po](https://github.com/mintty/mintty/files/619058/fr_po.txt)
- ![Terminal i18n screenshot](https://cloud.githubusercontent.com/assets/18137218/20711659/1be4d900-b641-11e6-8df2-68efe27e98d3.png)

**Comment by mintty** [comment]
Merci beaucoup!

Note that in the current repository version, there have been some simplications for menu items that have varying shortcuts. Those can be left away now (their explicit translations are dropped), so you need to translater only "&Close" -> "&Fermer" and not the TAB-separated shortcuts variants anymore.
Also some new translations have been added (`msgmerge` is supposed to handle that, but some of the entries have been wrongly reassigned, see those marked "fuzzy" in the attached update, I'll further fix that or you may). I have further replaced plain apostrophes "'" with typographic apostrophes "’" in the attached version.
New groups of strings are:
* Options dialog tree labels ("Looks", ...) as I finally found out how to display them in Unicode...
* System menu default items (provided by Windows, "Restore", ....) which are now also handled.


[fr_po_update_with_some_wrong_reassignemnts.txt](https://github.com/mintty/mintty/files/619167/fr_po_update_with_some_wrong_reassignemnts.txt)

**Comment by mintty** [comment]
I think I fixed the wrong entries. Missing entries are "&Restore", "&Move", "&Size", "Mi&nimize", "Ma&ximize" for the system menu, which you can copy from your default system menu.
[fr_po_update_with_some_missing_items.txt](https://github.com/mintty/mintty/files/619362/fr_po_update_with_some_missing_items.txt)

**Comment by mintty** [comment]
Committing the file with the following remaining translations:
msgid "&Restore"
msgstr "&Restaurer"
msgid "&Move"
msgstr "&Déplacer"
msgid "&Size"
msgstr "&Taille"
msgid "Mi&nimize"
msgstr "Di&minuer"
msgid "Ma&ximize"
msgstr "Ma&ximiser"

**Comment by mintty** [comment]
@Gozer-404: I've added localization support for the font and colour choosers and some of the French translations, too. To complete them, assuming that you are running a French Windows version, could be please do this (with the current version): `mintty -o OldFontMenu=true`, then make one screenshot each of the font chooser (Text – Select...) and the colour chooser (Looks – Cursor...).

**Comment by Gozer-404** [comment]
Here are the screenshots (mintty-2.7.1-0) started with `mintty -o OldFontMenu=true`.
BTW I corrected a few small errors in the fr.po file.
![fontchooser](https://cloud.githubusercontent.com/assets/18137218/21011222/a10cf106-bd50-11e6-8d46-3bcdb38ee59d.png)
![bgcolorchooser](https://cloud.githubusercontent.com/assets/18137218/21011223/a115257e-bd50-11e6-9375-5b6fd125bf85.png)
![cursorcolorchooser](https://cloud.githubusercontent.com/assets/18137218/21011224/a11bfe76-bd50-11e6-9796-e225f64a019e.png)
![fgcolorchooser](https://cloud.githubusercontent.com/assets/18137218/21011225/a1242c72-bd50-11e6-8fe3-1882c5c80907.png)
[fr.po.txt](https://github.com/mintty/mintty/files/639487/fr.po.txt)

**Comment by mintty** [comment]
Merci encore une fois.
Revised and uploaded changes to repository.

**Comment by mintty** [comment]
Released 2.7.2 with final tweaks.

**Comment by mintty** [comment]
@Gozer-404: I disambiguated a few entries meanwhile, so that you would now have the option to assign different translations to multiple occurences of "Font", "Colour", "Paste" if you prefer.

**Comment by mintty** [comment]
@Gozer-404, once again: I also disambiguated some keyboard shortcuts, in English and the translations. These are indicated by the '&' marks in the item labels. In the Options dialog, a few will remain ambiguous, that's not too bad. In the system and context menus, it's affecting the capability to invoke a menu item right away. May I ask you to check the following few details, please:
* In the context menu, "&Coller" and "&Copier" have the same shortcut. Please check how the shortcuts are defined by default in the French Windows version, and whether you'd like to assign different shortcuts.
* In the system menu (window title menu), "&Taille" and "Copier le &titre" both have shortcut 't'. I suggest to use "Copier le t&itre".
* Furthermore, I noticed a few items that appear untranslated. For "Flash" that's probably due to space limitation, but what about "Store" (Options - Looks) and "&Reset" (context menu)?

**Comment by mintty** [comment]
@Gozer-404: Can you please provide a translation for "Popup" for the revised Bell configuration section, to popup the window on bell? (émerger / surgir / avant-plan?)
Merci

**Comment by mintty** [comment]
There are 3 new items for the new extended context menu:
	"Copy → Paste"
		"Copier → Coller"
	"&Log to file"
		"Enregistrer dans fichier"
	"&Clear Scrollback"
		"Éteindre défilement"

**Comment by Gozer-404** [comment]
Another small update (includes the new items from comment above) based on git pull from today.

Cheers.
[0001-Updated-lang-fr__po__patch.txt](https://github.com/mintty/mintty/files/757867/0001-Updated-lang-fr__po__patch.txt)

**Comment by mintty** [comment]
Merci.
"&Popup" and some others: if the mapping is identical, the msgstr can be empty (same meaning)

 msgid "&Clear Scrollback"
-msgstr "Éteindre défilement"
+msgstr "Arrêter le défilement"
Doesn't arrêter mean "stop"? The function deletes the scrollback buffer.

And I even have a new one, again (not yet in code):
msgid "Display/Show Character Information"
msgstr "Afficher Information de Caractères" ?

**Comment by mintty** [comment]
Released 2.7.5; unsqueezing colour chooser dialog to make more space for localized labels.

**Comment by mintty** [comment]
If you'd like to further contribute to updates in the localization file (low frequency),
I would appreciate if you subscribe to issue #700.
It currently lists a few open translations as of release 2.8.0.

**Comment by Gozer-404** [comment]
I'll have a look asap...

Le 23 oct. 2017 10:17, "mintty" <notifications@github.com> a écrit :

If you'd like to further contribute to updates in the localization file
(low frequency),
I would appreciate if you subscribe to issue #700
<https://github.com/mintty/mintty/issues/700>.
It currently lists a few open translations as of release 2.8.0.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mintty/mintty/issues/611#issuecomment-338582296>, or mute
the thread
