### ISSUE TITLE
Russian po file

### ISSUE THREAD

**Issue by Rinat84** [mintty/mintty#614]
Посидел вечерком вот  что вышло
https://drive.google.com/open?id=0B2LswBZ7aN9uOEhLdFp4eUpVYmM

**Comment by mintty** [comment]
? Download is not a po file ??

**Comment by Rinat84** [comment]
Fixed

**Comment by mintty** [comment]
Thanks. Two questions:
* You changed the font sample text "Ferqœm’4€" back to the default "AaBbYyZz"; if you don't want to take my proposal, wouldn't you want to include some Cyrillic letters here?
* Does the Russian Windows localization translate "OK" already? In that case your translation "OK" -> "OK" would overwrite that back to the English button label, while e.g. "Cancel" would be Russian. Is that intended?

**Comment by Rinat84** [comment]
1.when switching the font will again  "AaBbYyZz"
2.it is possible to skip the  automatic wrote )

**Comment by Rinat84** [comment]
Minor edits
#: winctrls.c:934
msgid "Sc&ript:"
msgstr "Набор символов:"

**Comment by mintty** [comment]
1. Arrgh, you're right. But I fixed it :)
2. Not sure what you mean. Is this about the OK label?
Thanks for all updates, now with a Cyrillic text sample, maybe?

**Comment by Rinat84** [comment]
вот
https://drive.google.com/file/d/0B2LswBZ7aN9uOEhLdFp4eUpVYmM/view?usp=sharing

**Comment by mintty** [comment]
I'll think about resolving such ambiguities. Resources could be split into categories, as offered in the gettext model, or this could simply be distinguished explicitly. You can provide the two Russian "Paste" translations here already (as text), so I could then insert them.

One other remaining issue: My previous comment about "OK" may have been misleading, if you map it to "", and select Russian translation on a Chinese Windows system, you would see a Chinese OK button next to Russian other buttons. There should better be a dedicated translation. It that's "OK" -> "OK" because English "OK" is used on Russian computers, that's OK :) - Or a corresponding Russian label.

**Comment by Rinat84** [comment]
"Вставить"
"Вставка"

English is used "ОК"

**Comment by Rinat84** [comment]
updated

https://drive.google.com/open?id=0B2LswBZ7aN9uX2UtOHFvck9rOWM

**Comment by mintty** [comment]
Thank you.
I notice there's something wrong with the title of the Options menu. Will need to investigate.

**Comment by mintty** [comment]
The Russian "Options" window title would appear as all question marks, unless the Windows ANSI codepage were CP1251 (Windows Cyrillic), so you may not have noticed this flaw. Fixed.

**Comment by mintty** [comment]
Updated in 2.7.3.

**Comment by mintty** [comment]
@Rinat84: Can you please provide a translation for "Popup" for the revised Bell configuration section, to popup the window on bell? (Текст ?)
Thanks

**Comment by Rinat84** [comment]
Всплывающее

**Comment by mintty** [comment]
Thanks, but I'm afraid that's quite long, only "Всплыва" is shown.
Can you provide a shortcut (like ""Вспл." for "Flash" which is on the same line)?

**Comment by Rinat84** [comment]
Flash = Всплывающее
Highlight in taskbar = Подсветка

**Comment by mintty** [comment]
I'll try to balance the field widths dynamically, so your 2 longer labels may be compensated by the shorter "Highlight" label if that fits.
The request was actually to provide a shorter label, not a longer one. Thanks anyway.

**Comment by mintty** [comment]
There are 3 new items for the new extended context menu:
	"Copy → Paste"
		"Копировать → Вставить"
	"&Log to file"
		""
	"&Clear Scrollback"
		""

Also, in the colour chooser dialog, some of the tiny labels are too large and are getting clipped:
"|S&olid", "&Hue:", "&Sat:", "&Lum:", "&Red:", "&Green:"

**Comment by Rinat84** [comment]
"Copy → Paste"
"Копировать → Вставить" 
ОК

"&Log to file"
"Лог в файл"

"&Clear Scrollback"
"очистить скроллинг"


standard
http://i.piccy.info/i9/3c2e47970a38ac7eb97335cd291bae9d/1486130553/58607/1115216/Snymok.jpg

**Comment by mintty** [comment]
Thanks.
So apparently the geometry of the window is also tweaked in its localized versions.
I can try to handle that to some extent, like it's done for the font chooser already.

**Comment by mintty** [comment]
There's a new one:
"Character Information"
"Информацию символов" ?

**Comment by Rinat84** [comment]
MSYS2 error

gcc -c -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG -std=gnu99 -include std.h -Wall -Wextra -Wundef -Werror -mtune=atom -fomit-frame-pointer -O2  termout.c -o ../bin/msys64/termout.o
termout.c: В функции «term_write»:
termout.c:1615:11: ошибка: this «if» clause does not guard... [-Werror=misleading-indentation]
           if (i < lengthof(term.csi_argv))
           ^~
termout.c:1617:13: замечание: ...this statement, but the latter is misleadingly indented as if it is guarded by the «if»
             if ((int)term.csi_argv[i] < 0)
             ^~
cc1: все предупреждения считаются ошибками
make[1]: *** [Makefile:120: ../bin/msys64/termout.o] Ошибка 1
make[1]: выход из каталога «/home/user/mintty-2.7.4/src»
make: *** [Makefile:22: exe] Ошибка 2

**Comment by mintty** [comment]
Can I assume you confirm the translation I proposed previously?

It compiles well here on MSYS2; which gcc -v do you run?
I do see the misleading indentation, though, and will check it, thanks.

**Comment by Rinat84** [comment]
gcc версия 6.3.0 (GCC)

**Comment by Rinat84** [comment]
I can not say did not find that it does or displays

**Comment by mintty** [comment]
My request was about the translation of the new menu entry "Character Information"
which I derived from other translations as "Информацию символов", is that OK?

**Comment by Rinat84** [comment]
"Информация символов"

**Comment by mintty** [comment]
a new one, I've tried to translate by pattern and dictionary :)
"available" (like in "mintty release 2.7.5 (is) available") -> "доступный"

**Comment by mintty** [comment]
Released 2.7.5; unsqueezing colour chooser dialog to make more space for localized labels.

**Comment by mintty** [comment]
If you'd like to further contribute to updates in the localization file (low frequency),
I would appreciate if you subscribe to issue #700.
It currently lists a few open translations as of release 2.8.0.
