### ISSUE TITLE
can set character use Command Line，not Options(GUI)？

### ISSUE THREAD

**Issue by gMan1990** [mintty/mintty#621]
how?

**Comment by mintty** [comment]
All options are available from the command line, see the manual page http://mintty.github.io/mintty.1.html.
If that wasn't your issue, describe it clearly.

**Comment by gMan1990** [comment]
@mintty 
nonono.......how to change the current character with the opend mintty

**Comment by mintty** [comment]
What current character? You'd need to describe your wish precisely, or I could only speculate.

**Comment by gMan1990** [comment]
@mintty step：
1、open mintty（name "A"）
2、change "A" character, use command Line, not gui
3、maybe change back

**Comment by mintty** [comment]
We seem to be speaking different languages.
You are talking Twitter style, but this is an issue report.
What does `open mintty(name "A")` mean? Etc.
If nothing else helps, make a video.

**Comment by mintty** [comment]
What's your command line to start mintty? Is "A" the name of your desktop shortcut? Is this related to the mintty window title? If you something that can be changed on the GUI, what's the parameter name there?

**Comment by gMan1990** [comment]
@mintty just give it a name so the step two can make sure which mintty
1、open mintty   (D:\Cygwin\cygwin64\bin\mintty.exe)
2、change the mintty opend by step one   character, use command Line, not gui
3、maybe change back

**Comment by mintty** [comment]
I'm really willing to help you, so why don't you help me and answer my questions?
What's "give it a name"?
What "character" do you mean?

**Comment by k-takata** [comment]
> What "character" do you mean?

I assume that he meant "character set".

Normally, to change the state of a terminal from inside of it, escape sequences are used.
E.g. To change the window title: `echo -en "\033]2;Hello World.\007"`
I don't think there are such sequences to set the character set.

**Comment by mintty** [comment]
Actually, there is, see https://github.com/mintty/mintty/wiki/CtrlSeqs#locale.
Note that whether you change the character set this way or from the Options menu, it is advisable to change the respective locale environment variable (i.e. whichever is set of LC_ALL, LC_CTYPE, LANG) in your shell at the same time, because if this runs out of sync, your applications' output will not appear nicely in the terminal.

**Comment by k-takata** [comment]
Oh, I didn't know that. Thank you.

**Comment by mintty** [comment]
Consistent changing could be achieved with a shell function like the following, declared in `$HOME/.bashrc`:
```
changecs () {
	# determine which locale environment variables are set
	lcvars=`env | sed -e "s,^LANG=.*,LANG," -e "s,^\(LC_[A-Z]*\)=.*,\1," -e t -e d`
	# change them to the new character set; if none is set, set LC_CTYPE
	for lcvar in ${lcvars:-LC_CTYPE}
	do	lc=`eval echo '$'$lcvar`
		lc=`echo $lc | sed -e "s,[.@].*,,"`.$1
		eval $lcvar=$lc
		eval export $lcvar
	done
	# get effective character set, checking locale environment variables 
	# in order of precedence
	cs="${LC_ALL:-${LC_CTYPE:-$LANG}}"
	# now set mintty character set
	echo -en "\033]701;$cs\007"
}
```

**Comment by gMan1990** [comment]
hhhhhhhhhhhh,  yes yes ,,,,, character set
