### ISSUE TITLE
`which xxx.sh` not work

### ISSUE THREAD

**Issue by eromoe** [mintty/mintty#622]
I don't know if this is by mintty or msys2, so I post one here too. If not relevent, feel free to close it :).

In linux:

```
# which virtualenvwrapper.sh                                                                           
/usr/local/bin/virtualenvwrapper.sh
```

But on mintty(msys2, git-bash):
```
$ which virtualenvwrapper.sh
which: no virtualenvwrapper.sh in (/d/Python27:/d/Python27/Scripts:/d/Go/bin:/d/Go/gopath/bin:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/TortoiseGit/bin:/d/phantomjs-2.1.1-windows/bin:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/vim/vim80:/d/Windows Kits/8.1/Windows Performance Toolkit:/d/nodejs:/usr/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin)

$ ls /d/Python27/Scripts|grep virtualenvwrapper.sh
virtualenvwrapper.sh
```

Just can not find this .sh file

**Comment by mintty** [comment]
This is not related to mintty in any way. Mintty is a terminal, the shell runs inside it.
Apart from that, check the x permission of that script.

**Comment by eromoe** [comment]
@mintty 
Thanks for the tip, though `chmod` seems not work on windows,  I would do some research.
And a little suggestion:
Maybe you can add some words to `README.md` like :

http://unix.stackexchange.com/questions/4126/what-is-the-exact-difference-between-a-terminal-a-shell-a-tty-and-a-con

- terminal = tty = text input/output environment
- console = physical terminal
- shell = command line interpreter

Many people donot understand the differet among the above three.
