### ISSUE TITLE
Process the tmux clipboard control sequence

### ISSUE THREAD

**Issue by fpqc** [mintty/mintty#623]
The tmux documentation has the following:
```
set-clipboard [on | off]
                     Attempt to set the terminal clipboard content using the \e]52;...\007 xterm(1) escape sequences.  This option is on by default if there is an Ms entry in the terminfo(5) description for the client terminal. 
```

Could you make it so mintty processes that control sequence and saves the text to the Windows clipboard?  Thanks!

**Comment by mintty** [comment]
It does already, but you need to set the following option in your config file (e.g. `$HOME/.minttyrc`):
`AllowSetSelection=yes`

**Comment by fpqc** [comment]
@mintty Thanks!
