### ISSUE TITLE
Eliminate padding around screen in fullscreen mode

### ISSUE THREAD

**Issue by wildptr** [mintty/mintty#624]
When in fullscreen mode, mintty does not seem to utilize screen space to the fullest. Instead, it leaves a black padding around the screen. When running programs like vim, on a 1280x800 screen for example, assuming the font width is 8 pixels, only 159 columns are displayed rather than 160, with an ugly margin at the right border of the screen. This can be annoying.

**Comment by wildptr** [comment]
Resolved by adding "Padding=0" to configuration file (/etc/minttyrc).

**Comment by mintty** [comment]
I was about to ask whether that's the issue.
Arguably padding could not be applied in fullscreen mode implicitly, to be considered...
