### ISSUE TITLE
Transparency Hotkey

### ISSUE THREAD

**Issue by dsXero** [mintty/mintty#625]
I'd like a hotkey to toggle through the different levels of transparency.
Off->Low->Med->High->Glass->Off
The best I've figured out is Alt-Space -> O -> O (for Off)

**Comment by mintty** [comment]
You mean in the Options dialog? Or a direct toggle in the terminal?
What do you achieve with Alt+space?
You can address all the options with hotkey letters (o, l, m, h, s).

**Comment by mintty** [comment]
Assuming the hokeys mentioned address your issues; closing.

**Comment by dsXero** [comment]
Can the hotkeys be global? Meaning can we skip the Alt-Space -> O part?

**Comment by mintty** [comment]
Oh, so you mean a direct toggle from the terminal, without Options menu...

**Comment by mintty** [comment]
That might be useful for a few options, like transparency, cursor shape, scrollbar on/off.
But which hotkeys should be assigned? Configurable?

**Comment by dsXero** [comment]
Yes, that's what I mean! I'd love for them to configurable, but anything would work. 
Another thought is that Control-T would be memorable (t for transparency) and it could toggle in order of Off->Low->Med->High->Glass->Off.

**Comment by mintty** [comment]
Control+T is not available because it's a control character. Control+Shift+T might be an option.

**Comment by dsXero** [comment]
That would be perfect!

**Comment by mintty** [comment]
Please test the new feature. Note there's also interactive tuning while holding Ctrl+Shift+t if you use the numeric cursor keys (see also manual page).

**Comment by dsXero** [comment]
Very Very cool! Works like I've always dreamed it would.

I tried holding down Ctrl+Shift+t and it rolls through them nicely. It never goes to glass, but that is accessible Ctrl+Shift+t+5. I imagine that really is for the best since not everyone would want nor be able to use the glass feature, so this really is the correct behavior.

Ctrl+Shift+t+7 = medium
Ctrl+Shift+t+5 = glass 
Ctrl+Shift+t+9 = higher
Ctrl+Shift+t+3 = lower

When transparency is set to glass I got some artifacts, but it only happened when I was using tmux as well.
![capture](https://cloud.githubusercontent.com/assets/25390125/22572282/fac5722e-e968-11e6-8c93-63e02345a387.PNG)
I have been completely unable to replicate this.

I tested that the Ctrl+Shift+letter shortcuts must be checked for this to work, under options > keys.
Opening a new window defaults back to option setting as expected.

Very well done. Thank you.

**Comment by mintty** [comment]
Thanks for the feedback.
I have 3 potential improvements in mind, what do you think (are they worth the effort)?
* disable OpaqueWhenFocused temporarily to facilitate using the feature in opaque mode
* suppress cycling transparency on keyboard auto-repeat
* when using keypad-tuning, transparency would have been increased once already in a step initially; this isn't optimal; to avoid it, step increments would need to be applied only after T has been released

**Comment by dsXero** [comment]
disable OpaqueWhenFocused temporarily - This is a great idea. It would not be obvious why the Ctrl+Shift+t does nothing when it is enabled. The intended effect is to override the options default.

suppressing the cycling - You can hold down Ctrl+Shift and repeatedly tap t to get the same effect without adding any functionality. However the cycling isn't good for keypad-tuning.

If you want to keypad-tune multiple steps would you have to:
Ctrl+Shift+t > let it go > keypad-tune one step
Ctrl+Shift+t a second time > let it go > keypad-tune a second step
Or would it have an amount of time for you to do multiple keypad presses?

**Comment by dsXero** [comment]
Just tested the new version. Holding down the key no longer cycles.
OpaqueWhenFocused means that it is only opaque when while you are holding down Ctrl+Shift+t, however it still cycles. Perhaps when OpaqueWhenFocused is checked Ctrl+Shift+t should be only high transparency.

**Comment by mintty** [comment]
It "cycles", one step, when you release the hotkey.
OpaqueWhenFocused means not transparent when the window has the keyboard focus, for clearer viewing while you are working in the terminal.
This now temporarily disabled while holding Ctrl+Shift+t, so you can see what you are doing. So the actual feedback while holding the hotkey is not affected by the configured setting.
Not sure what you mean with "only high transparency" and why the Opaque setting should impact the available transparency values.

**Comment by dsXero** [comment]
If OpaqueWhenFocused is checked and you are holding Ctrl+Shift+t the first time you do so the transparency is about what the radio button indicates it should be. If you release and hold Ctrl+Shift+t a second time the transparency goes up, and every time it goes up, until it cycles back to off and then continues to cycle. It seems that the transparency should not change with holding Ctrl+Shift+t if the OpaqueWhenFocused is checked.

**Comment by mintty** [comment]
You think the cycling function should be dropped at all? Or just in OpaqueWhenFocused mode, which would not be consistent however. I thought you liked the cycling and just made it not cycle immediately, so you can alternatively use the fine-tuning with the cursor block, based on the previous setting (not on an already modified setting as with the first version).
I plan for a release perhaps next weekend so there's still some time for design tuning...

**Comment by dsXero** [comment]
You are correct that it wouldn't be consistent, I didn't think of that.
I am super happy with it as it is, I'd say ship it!

**Comment by mintty** [comment]
Released with 2.7.5.
