### ISSUE TITLE
Color chooser window lost one label

### ISSUE THREAD

**Issue by Gozer-404** [mintty/mintty#626]
In the color chooser dialog (with my choice of using FR language) one label is probably hidden somewhere .
It's the label for the saturation;
```
    //__ Colour chooser:
    setlabel(724, _W("&Sat:"));
```
The effect can be seen in the attached screen dump.
![newcolorchooser](https://cloud.githubusercontent.com/assets/18137218/22550029/5f6ab7d6-e94e-11e6-8fdd-a4d845ef9f6b.png)

**Comment by mintty** [comment]
Apparently some of the recent tweaks for the font chooser have impact to the colour chooser.
Workaround for testing: `-o OldFontMenu=yes`
But note that the labels are quite long and are getting clipped in my environment (don't know what distinguishes the environments here). Maybe we should drop the spaces before the colons here?
![couleur](https://cloud.githubusercontent.com/assets/12740416/22557188/07ea1968-e96a-11e6-916b-6ee50249d56d.png)

**Comment by mintty** [comment]
Released colour chooser geometry adjustments with 2.7.5.
