### ISSUE TITLE
Vertical tmux borders are dashed since mintty 2.7.4

### ISSUE THREAD

**Issue by kgraefe** [mintty/mintty#628]
Since I updated mintty via the Cygwin installer, vertical lines are broken (e.g. in tmux). My guess would be that [this commit](https://github.com/mintty/mintty/commit/cd5ec9e1e34ff41eabc46e6205dd57ca834349e9) causes the issue.

- Mintty 2.7.3: ![mintty_2 7 3](https://cloud.githubusercontent.com/assets/3797324/22684305/19ec8438-ed1c-11e6-8e52-677e0bf2c176.png)
- Mintty 2.7.4: ![mintty_2 7 4](https://cloud.githubusercontent.com/assets/3797324/22684308/1c02f8f6-ed1c-11e6-88fe-ea71781cb160.png)

**Comment by mintty** [comment]
How is that vertical line drawn? Is it ASCII character U+007C VERTICAL LINE?
(To find out, you might run mintty -l logfile.)
It wouldn't happen if the program used VT100 line drawing graphics.
I can see to handle that, or make the new behaviour optional.

**Comment by kgraefe** [comment]
tmux uses the UTF-8 character `U+2502 BOX DRAWINGS LIGHT VERTICAL` for that. This is preferred over ACS, apparently due to an [issue with PuTTY](https://github.com/tmux/tmux/commit/cb564bb427b9db5b1e48a74e6b818454f7ab0c77).

**Comment by mintty** [comment]
I can also simulate with `printf "│\n│\n│\n"` :)

**Comment by kgraefe** [comment]
I tested and confirmed it working in 2cc746667595e08f57b12cfa0df0b67787762620.

**Comment by mintty** [comment]
Released in 2.7.5.
