### ISSUE TITLE
Truecolors & COLORTERM

### ISSUE THREAD

**Issue by arcanis** [mintty/mintty#635]
The terminfo author has [made it clear](http://lists.gnu.org/archive/html/bug-ncurses/2017-02/msg00019.html) that he would never include truecolor support inside its databases. In response, a few applications and terminals have chosen to use the `COLORTERM=truecolors` environment variable to indicate that the terminal supports truecolors (currently VTE, Konsole and iTerm2; on the other hand, emacs has chosen to require users to manually patch their terminfo files, more details [here](https://gist.github.com/XVilka/8346728#detection)).

Should mintty set this environment variable when booting the shell?

**Comment by mintty** [comment]
Well, actually xterm is the declared behaviour model for mintty, and xterm doesn't set it.
The problem with setting an environment variable is that it propagates to all child processes, including other terminals which you may start from mintty, including those that do not support truecolor. Therefore terminals that do this create potential inconsistency. I don't think that's the right thing to do.
For that reason, there are escape sequences by which terminals can be identified, so applications may safely use specific features if they want.
The area of colour modes is chaotic anyway, e.g. it's hard to detect from an application whether a terminal runs in 256-colour mode or 88-colour mode, should that matter. This isn't properly solved by introducing features that are themselves problematic.

**Comment by mintty** [comment]
Closing, assuming the implied answer "no" is accepted.

**Comment by arcanis** [comment]
Well, I understand the reasoning, but it's unfortunate that there is no consensus to detect these features.

I'm gonna be honest, I hate terminfo with all my heart. I feel like terminal should be able to tell if they support a feature without needing a potentially out-of-date file to be added to the hosts.

**Comment by mintty** [comment]
See above:

> there are escape sequences by which terminals can be identified

`echo -en "\e[>c"` causes the terminal to identify itself. It's also possible to distinguish 16/88/256 colour modes in xterm.

**Comment by mintty** [comment]
For the records: terminfo support for true colour is meanwhile available. Terminfo entries xterm-direct and mintty-direct use it.
