### ISSUE TITLE
add search "Case sensitive" options

### ISSUE THREAD

**Issue by gMan1990** [mintty/mintty#636]
RT

**Comment by mintty** [comment]
You want search to be case-insensitive?
Could be changed, but some implementation effort is needed for handling a case mapping table.

**Comment by gMan1990** [comment]
yes, case-insensitive, 3q3q

**Comment by mintty** [comment]
Released 2.7.5.

**Comment by gMan1990** [comment]
where???
screenshot

**Comment by mintty** [comment]
Well, it's not exactly an option; I simply changed search to be case-insensitive because that's more useful.
