### ISSUE TITLE
Can improve on how to get themes working.

### ISSUE THREAD

**Issue by meffect** [mintty/mintty#639]
I spent long time getting themes to work I think we can improve docs/wiki a little to save some people some time if they run into similar problems

**Comment by mintty** [comment]
I'd appreciate more useful hints so documentation (and maybe procedures) can be improved.

Which error message was not helpful? What logs do you expect? Which documentation is weird (manual page, wiki page)?
What do you mean by environment variables in two different worlds‽ Etc.

I'm always willing to improve but first you should improve your own complaint by your own criteria.

**Comment by mintty** [comment]
And, for that matter, my willingness to improve is certain uncomparable to any Microsoft response. Be fair and change the title.

**Comment by meffect** [comment]
mission accomplished, sry about that, silly humor heh heh heh ehehheheh

**Comment by mintty** [comment]
Shortened title to fit in one line, and to cover not only docs but als procedures to achieve themes installation. Suggestions for both are always welcome.

**Comment by mintty** [comment]
Released 2.7.7.
