### ISSUE TITLE
Bold with underline causes rendering artefacts

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#641]
When using "Bold as Font" and Consolas, fonts which are bold with an underline get poor anti-aliasing:

The two kernel lines _above_ the bold+underlined line are bold and the two lines _below_ are normal.

![image](https://cloud.githubusercontent.com/assets/2286713/23603361/ce360758-024c-11e7-9a3f-31951ee7a0b3.png)

**Comment by mintty** [comment]
Please try option `UnderlineManual=true`.

**Comment by mintty** [comment]
Font rendering is done by Windows. Underlined font is a special option of Windows font rendering which is used by mintty. I have no idea why Windows renders a font differently if the underline flag is also set and there is nothing that mintty could do other than making `UnderlineManual=true` the default which I'm hesitating to do.

**Comment by ElvenSpellmaker** [comment]
This seems to fix the problem, but the underline is very thick in this mode;
![image](https://cloud.githubusercontent.com/assets/2286713/24352178/6cf8c922-12e0-11e7-82d4-3c711958c128.png)

**Comment by mintty** [comment]
Released 2.7.6.
