### ISSUE TITLE
Color chooser problem

### ISSUE THREAD

**Issue by k-takata** [mintty/mintty#642]
Color chooser is not shown properly with 2.7.5.
When I open the dialog box first time, it is shown as below.
Some texts are hidden by another parts.

<img width="426" alt="mintty-color1_2" src="https://cloud.githubusercontent.com/assets/840186/23829526/25ea495c-0737-11e7-847d-9c66b16b908e.png">

When I close the dialog box and open it again, some textboxes move to left.

<img width="426" alt="mintty-color2_2" src="https://cloud.githubusercontent.com/assets/840186/23829535/80acf006-0737-11e7-9f6a-5af13565c915.png">

(DPI setting is 150%.)

**Comment by mintty** [comment]
Cannot reproduce the clipping of the first screenshot.
Fixed the moved icons on later reopening of the colour chooser.

**Comment by mintty** [comment]
Released 2.7.6.
