### ISSUE TITLE
[Suggestion] Another methods to implement windows style copy/paste

### ISSUE THREAD

**Issue by cy18** [mintty/mintty#645]
The new feature added in #524 is not as good as expect since not only copy/paste, but all Ctrl hot keys are exchanged. 

Since what we need is just windows style copy/paste, or in the case of mine, just paste. What if  adding options  CtrlVExchangeCtrlShiftV and  CtrlCExchangeCtrlShiftC? 

Another idea is adding a new string option named CtrlExchangeShiftKeys to set what keys to exchange. For example, if someone want windows style copy and paste, then  set CtrlExchangeShiftKeys=cv. If he just want windows style paste, set CtrlExchangeShiftKeys=v.

**Comment by mintty** [comment]
So you want Ctrl+V to paste and Ctrl+X to insert ^X?
That would be kind of pretty inconsistent.
Do you really want that?
Really?

**Comment by cy18** [comment]
I use ctrl-C to terminate programs as often as using ctrl-V to paste. This is how conemu and cmd.exe in Windows 10 do. Forther more, when ctrl-C is presses, they send ^C if no text is selected, but copy the text if there is text selected. Believe me, it's more convenient than you thought. It would be great if mintty also support this. You say it is inconsistent, I'll say it is smart, since this is exactly what I want to do when I pressed ctrl-C and ctrl-V.

Using ctrl+shift+V is also good, but it's not compatible with the clipboard managers such as Ditto.

**Comment by mintty** [comment]
cmd.exe is a Windows shell. mintty normally hosts a cygwin shell. These are two different worlds.
That does not necessarily mean it's not possible to consider such "smartness" but since the described behaviour is somewhat alien in a Posix environment, I'd rather let the idea settle for a while and maybe see if others support the request.

**Comment by Biswa96** [comment]
The shift/ctrl+insert shortcut is similar with xterm. If someone is accustomed with that he may find that shortcut useful.
But Microsoft added an option to enable Ctrl+c/v to copy/paste in WSL: https://blogs.msdn.microsoft.com/commandline/2018/04/13/copy-and-paste-arrives-for-linuxwsl-consoles/ so Windows users also find that useful if there is an option to enable that shortcut like in that article.

**Comment by mintty** [comment]
The shortcut I see in the config screenshot is Ctrl+Shift+C/V.
Mintty has that already, just enable "Ctrl+Shift shortcuts".

**Comment by mintty** [comment]
Released 2.9.1.

**Comment by CadetSparklez** [comment]
> want that?

inconsistant? you would be making it ocnsitsant with everything else, you need you use ur right hand to shift ins which is on a mosue

**Comment by mintty** [comment]
Released 3.6.0.
