### ISSUE TITLE
Alt-F2 on second monitor makes 1x28 size window

### ISSUE THREAD

**Issue by keithdtyler** [mintty/mintty#649]
When I focus a mintty window on my secondary monitor, and press Alt-F2, the newly created mintty is about 1x28 text (yes that's 1 line, 28 chars wide, 8 pt default font). 

When I do Shift-Alt-F2 in that situation, the newly created mintty has about 1pt font @ 5x163 text, in the same physical window dimensions (I believe this is the minimum Windows window size).

Now... If I do Alt-F2 from a mintty in my primary monitor, the resulting window is as expected: 8pt, 24x80.

And get this -- if I pull down the window menu from the title bar, on the mintty in the secondary monitor, and I *select* the New Window option, it spawns on the *primary* monitor, but in the correct dimensions and point size.

ENvironment is a Surface Pro 4 running Win10. Mintty version 2.7.4.

My .minttyrc is:

    BoldAsFont=-1
    FontHeight=8
    Font=Consolas
    BackgroundColour=0,0,0
    ThemeFile= 
    Columns=80
    Rows=24

**Comment by mintty** [comment]
Closed the gap in monitor-stickyness for new windows created with Ctrl+Shift+n or from the menu.

**Comment by mintty** [comment]
I cannot reproduce the strange window dimensioning issue. You'll have to analyse whether there is anything weird in your environment.

**Comment by keithdtyler** [comment]
It may have something to do with per-monitor window scaling, a Win10 feature. My primary monitor is a high-pitch screen so it is set to 200% window scaling whereas the secondary monitor is 100% (i.e. actual) scaling.

I noticed today that when I move a window set to 201x50 from the primary to the secondary, it becomes 204x51.

**Comment by mintty** [comment]
Released 2.7.6 which sticks new window to current monitor with Ctrl+Shift+N and sysmenu-New.

**Comment by data-digger** [comment]
Checked on 2.7.6 - I have the same issue. Alt + F2 works fine on main, 4k display and on a regular 1920x1080 it scales down to 1x row. I'm not sure what Ctrl + Shift + N is supposed to do?

**Comment by keithdtyler** [comment]
@data-digger Is one of your displays, probably the 4K, using scaling?
(Display settings: "Change the size of text, apps, and other items" something other than 100%)

**Comment by data-digger** [comment]
@keithdtyler Yes, 150%

**Comment by mintty** [comment]
If you like to recompile mintty, you could try to enable #define debug_resize in win.h and perhaps #define debug_dpi in winmain.c. Maybe that provides some insights.

**Comment by mintty** [comment]
I've tentatively applied some tweaks that hopefully fix the 1-line size, but I'm not sure as I could not reproduce the issue. Please test current repository version (or wait for next release).

**Comment by mintty** [comment]
Released 2.7.7. Please recheck.
