### ISSUE TITLE
Password is shown when typing in

### ISSUE THREAD

**Issue by JackRainy** [mintty/mintty#650]
Hi,

When I type in my password it is shown on the screen.
It happens for different applications which prompts for credentials.
I would expect to have it hidden while I am typing - same as _cmd.exe_ does.

Example of the issue:
![screenshot 2017-04-13 10-07-51](https://cloud.githubusercontent.com/assets/27405436/24993931/37370020-2031-11e7-87b9-28353b16a44f.png)

Environment: Windows 8.1, mintty 2.7.3 (x86_64-pc-msys) , GNU bash 4.4.12(1)-release, Git 2.12.2.2-win-64.

Thank you in advance.

**Comment by mintty** [comment]
Mintty never echoes any input on the screen, this is done either by the application or its runtime environment. I assume your program is a Windows program, not a Cygwin program (what's the output of `type p4`?), making Windows console I/O calls that do not interoperate well with tty I/O. That would indicate this is a symptom of #56.

**Comment by JackRainy** [comment]
Yes, it happens for the Windows programs (even `java` console application). 
Is there any workaround for that?

**Comment by mintty** [comment]
There are the conin and winpty tools, see mintty home page https://mintty.github.io/ section "Compatibility", link "problems". Maybe I should mention that more prominently, but then I don't really wish to solicit a discussion about those tools which are not mine :/
The hope is that this functionality will one day be integrated into cygwin...

**Comment by mintty** [comment]
Released 2.7.7 with enhanced Wiki.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
