### ISSUE TITLE
mintty 2.7.5: lost ctrl-left/right keycodes

### ISSUE THREAD

**Issue by drm135** [mintty/mintty#651]
After the latest cygwin mintty update, I seem to have lost some keycodes.

I've set up ctrl-left/right arrow keys to move by words using this in my .inputrc:
    "\e[1;5C": forward-word
    "\e[1;5D": backward-word

This worked in mintty 2.7.4, but has no effect in 2.7.5 or 2.7.6.

If I type "echo ctrl-V ctrl-arrow", nothing appears. For other keys, this expands the keycode, e.g. "echo ctrl-V HOME" expands to "echo ^[[H", so it looks like mintty is no longer processing this key combination.

I looked through the settings but couldn't find anything appropriate. Have I missed something?

Thanks in advance,
David M

**Comment by mintty** [comment]
Duplicate #646.
