### ISSUE TITLE
make ctl-tab work with alt-tab

### ISSUE THREAD

**Issue by pocoleo** [mintty/mintty#652]
when using ctl-tab to switch windows the order of the windows as far as windows is concerned does not change.  this causes the window that you enter ctl-tab on to disappear if other windows open.  

can you make it so that if a user enters ctl_tab to switch windows alt-tab will take them back the same as shift-ctl-tab

this will have the advantage of keeping visible the window you leave using ctl-tab.

**Comment by mintty** [comment]
With Ctrl+TAB, Windows sometimes pops up another window between the two, depending on which windows have recently been activated and Windows' according internal order of windows. I see no way to influence that. You are welcome to check out function win_switch in winmain.c for experiments.

**Comment by mintty** [comment]
Actually, it might help to bring the current window to the top first (even if it's there already); cf. a trick recently added to function win_set_zorder.

**Comment by pocoleo** [comment]
I used to use the terminal emulator CRT from Van Dyke and it behaved the
way I am suggesting so I know it is possible.

**Comment by mintty** [comment]
Actually, even if a third-party window may pop in between the two mintty windows, Alt+TAB navigation back to the previous mintty window still works. So I'm not really sure what the problem is;
please explain
> windows alt-tab will take them back the same as shift-ctl-tab

**Comment by pocoleo** [comment]
currently when i leave a mintty window using ctl-tab the window i am
leaving disappears because using ctl-tab dose not affect the z-order.  this
is a problem because usually when I want to get to another mintty window
it's to look something up for the first mintty window and not being able to
see both windows on the screen at the same time (without resorting to
clicking on the task bar) is difficult.

when i leave a mintty window using ctl-tab,alt-tab does not take me back to
the last window i just left - only shift-ctl-tab will do that - alt-tab
takes me to the last tab in the z-order which ctl-tab in mintty has not
affected.  I find that counter intuitive.

this is a suggestion for an improvement - I am not saying there is no work
around.

**Comment by mintty** [comment]
> the window i am leaving disappears

Can you arrange your involved windows such that they overlap but not completely; the window being left should remain (partially) visible, right? Describe precisely what happens or make a screenshot, please.

> alt-tab does not take me back to the last window i just left

This does not happen here, Alt+TAB takes me back to the previous window, even if it got pushed into the background by Ctrl+TAB. Cannot reproduce as you describe.

**Comment by pocoleo** [comment]
w1 = non-mitty window that covers  the entire screen
w2 = mintty window that covers a quarter of the screen
w3 = mintty window that covers a quarter of the screen partially
overlapping w2

alt-tab to w1
alt-tab to w2
ctl-tab to w3

on my system w2 is now behind w1 and no longer visible.

while we're at it i have read the putty has added an option to "disable
switching to alternate terminal screen".   Is it possible to get that as
well.  The way it is, scroll back is disabled in vi and I lose what vi was
displaying when when I exit vi. same with man same with etc.   It is a
feature I do not have an easy way to disable.

Thanks

**Comment by mintty** [comment]
I found a tweak to avoid the current window being pushed behind others, please check current repository version if possible.

**Comment by mintty** [comment]
About the alternate screen, I do not really like such an option because it affects compatibility, and you'd better disable the usage of that feature on application level.
You can achieve the desired effect with either setting a TERMCAP environment variable or configuring your application; I'm pretty sure vi has such an option.

Having said that, however, since xterm is the paragon of mintty terminal features, and xterm does in fact have such an option (titeInhibit), I will add it too. I plan to call the option NoAltScreen.

**Comment by pocoleo** [comment]
I am not able to find the option in vi ( i am on AIX so its not vim )  and
there are a lot of other apps where I don't want it and I am pretty sure
there is no option to disable it such as man.  And I find modifying a
specific TERM like xterm an exercise in futility.

I very much appreciate you adding the option

Thanks

**Comment by mintty** [comment]
You can install vim on AIX, too.
With less, you can simply use option -X to disable using the alternate screen.
And in general, you can set TERM=xterm-r5 to get any application using termcap/terminfo to ignore the alternate screen. Just tested on AIX:
TERM=xterm-r5 less test.txt

**Comment by pocoleo** [comment]
xterm-r5 does the trick - thanks

**Comment by pocoleo** [comment]
When using xterm-r5 page-up and page-dn no longer work in vi.

Is that something I can control?

Thanks

**Comment by mintty** [comment]
I do not see that. Pg keys work as usual for me.

**Comment by pocoleo** [comment]
My mistake - TERM was wrong.    When will the new version be available as an executable?

**Comment by mintty** [comment]
There are 1 or 2 other issues ahead...

**Comment by mintty** [comment]
Released 2.7.7.

**Comment by mintty** [comment]
Released 2.7.8.
