### ISSUE TITLE
mintty started with Alt+F2 should not have environment variables MINTTY_BUFFER etc

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#654]
I just got the error message "The environment is too large for exec" from a find and an xargs invocation. Looking at what's so large in the env, its MINTTY_BUFFER. (MINTTY_OUTPUT and MINTTY_SELECT are also defined, but their size is not a problem.)

I think those variables should not have been set, because they were not set in the parent mintty, and the child mintty was started with Alt+F2, not as a user command (#100).

**Comment by mintty** [comment]
The only case in which mintty sets this variable is by running a user command.
Did you start a mintty window by user command previously, so it was already set, and Alt+F2 from there?

**Comment by mintty** [comment]
Actually, you are right. When revising the environment variable names, I forgot to unset a few after a user command, so that they would still be set on a subsequent Alt+F2.

**Comment by mkq** [comment]
> Did you start a mintty window by user command previously, so it was already set, and Alt+F2 from there?

I did not press Alt+F2 inside the user command-started mintty, but inside its parent. I.e.:

1. mintty A: long running shell session, started via start menu shortcut; no variable MINTTY_BUFFER defined
2. mintty B: invoked by a user command from inside A
3. probably some more invocations like 2.
4. mintty C started via Alt+F2 in A; huge MINTTY_BUFFER causes "The environment is too large for exec"

**Comment by mintty** [comment]
I guess you overlooked my second comment. The issue has meanwhile been fixed, please check if you can build yourself from the repository version.

**Comment by mintty** [comment]
Released 2.7.7.
