### ISSUE TITLE
Truncated characters in prompt

### ISSUE THREAD

**Issue by p5a0u9l** [mintty/mintty#655]
I have read through some of the existing threads with a similar issue and was unable to find a solution. I'm using

    mintty 2.7.2 (x86_64-pc-cygwin)

My font is source code pro and the following unicode characters are truncated right in my prompt. 

✗➜

    echo $LANG
    en_US.UTF-8

**Comment by mintty** [comment]
There has been a related change in 2.7.5 (cf. #638); please update.

**Comment by p5a0u9l** [comment]
installing latest version, 2.7.6, fixed issue. Thank you!
