### ISSUE TITLE
Copying text adds newlines when text wraps

### ISSUE THREAD

**Issue by pocoleo** [mintty/mintty#657]
When I copy text from a mintty window mintty does not distinguish multiple lines created by word wrap from multiple lines created by a newline.  So when I paste the copied text extra newlines are pasted in and I have to edit the text to rejoin the broken lines.  This is very apparent if the target window is much wider than the source window.

Is it possible to detect a newline caused by word wrap and suppress the newline in the copied text?

**Comment by mintty** [comment]
Actually mintty does mark and handle wrapped lines and copies them as one line.
Please describe your test case precisely so we can identify any specific conditions.

**Comment by pocoleo** [comment]
First window 60 cols wide, logged into unix using TERM=xterm-r5, and
running vi against a file with many lines greater than 60 cols which have
all visibly wrapped.

Select by dragging over all the displayed lines which auto copies to
clipboard.

Switch to second window which is 120 cols wide, logged into unix using
TERM=xterm-r5, and running vi in insert mode.

Paste the clipboard into the second window and, on my system, I do not see
a line greater than 60 cols wide.

I can join the broken lines in whch case the lines wraps at 120 cols as
expected.

**Comment by mintty** [comment]
Two cross-checks please:
1. Do the same locally, without remote login, and you'll see it works fine.
2. Try the same (with remote login) in another terminal.

and you'll see that mintty is not involved in your issue.

**Comment by pocoleo** [comment]
I know it did not used to happen when I ran CRT so I went back to CRT and
tested it and it did happen.  When switching to mintty the only thing I
changed was TERM - I went from ansi_ncc to xterm-r5.   So I switched TERM
to ansi_ncc on the narrow window, copied the text and when I pasted it into
the wide window ( where I did not change TERM ) it did not break the line.
It also did not break the line when there is a character in the last column
which is not always right but I am used to that.  So apparently under
ansi_ncc the copy process detects a space in the last column when a line
wraps and under xterm-r5 it does not.

Is there anything you can do?

**Comment by mintty** [comment]
No.

**Comment by mintty** [comment]
Your lengthy tale did not really enlighten me, sorry. Did you try the two cross-checks I asked for?

**Comment by pocoleo** [comment]
It does work locally.  I am RDP'd to a remote desktop and the problem is dependent on TERM.

**Comment by mintty** [comment]
Cryptic descriptions (RDP) don't help the issue.
Anyway, as it works locally, it's not a mintty issue.

**Comment by mintty** [comment]
Apparently older versions of vi output each screen line separately, applying explicit wrapping where the line wraps (reproduced with a remote system), while newer versions use the terminal auto-wrap mode for it.
If you copy from a terminal where the output was split already there is no way to recognise the source line later in the clipboard contents.

**Comment by mrinmoyg** [comment]
I am facing this issue, where newline gets inserted at the wrapping point

- This only happens when I login to a server (ssh) with mintty. When not logged in, I dont see the issue, and the newline is not inserted at wrapping point.
- This is not specific to vi. When I dump an output e.g cat a file, and try to copy it from the terminal, I encounter the issue
- Using 3.4.3 version
- Mintty Config:
 <pre>
$ cat ~/.minttyrc
Columns=80
Rows=63
BackgroundColour=100,100,100
ForegroundColour=232,232,232
Font=Courier
FontHeight=8
FontWeight=400
FontIsBold=no
CursorType=block
RightClickAction=paste
SwitchShortcuts=yes
ZoomShortcuts=no
ClickTargetMod=shift
ScrollMod=off
TrimSelection=yes
CursorBlinks=no
Term=xterm-256color
BoldAsColour=no
BoldAsFont=yes
ThemeFile=xterm
BellType=0
ScrollbackLines=10000
FontSmoothing=default
CopyAsRTF=yes
CopyAsHTML=no
AllowSetSelection=yes
CopyOnSelect=yes
CopyTab=yes
</pre>

Any pointers, I might be missing in the config

**Comment by mintty** [comment]
> I am facing this issue

Which issue? Clear and reproducible descriptions help to comment on an issue. I see none.

**Comment by pocoleo** [comment]
that is probably your term setting in unix ( assuming you are connectect to
unix )

i prefer TERM=-xterm-r5

**Comment by k-takata** [comment]
@mrinmoyg 
Aren't you using the Win32 version of ssh (instead of the Cygwin version)?
If a command is executed via ConPTY, such issues can happen.

**Comment by mintty** [comment]
> Win32 version of ssh

Good suggestion, but I cannot even run it for testing, it says:
```
Pseudo-terminal will not be allocated because stdin is not a terminal.
CreateProcessW failed error:2
ssh_askpass: posix_spawn: No such file or directory
Host key verification failed.
```

**Comment by pocoleo** [comment]
I believe the problem is on what you are trying to connect to which is what?

**Comment by mrinmoyg** [comment]
> @mrinmoyg
> Aren't you using the Win32 version of ssh (instead of the Cygwin version)?
> If a command is executed via ConPTY, such issues can happen.

Yes, I am using cygwin ssh. ssh is to a RHEL system

**Comment by mrinmoyg** [comment]
I am using cygwin SSH:
/cygdrive/c/Windows/System32/OpenSSH/ssh

No "Newline Insertion at wrapping point" without ssh [Good]:
https://user-images.githubusercontent.com/6013474/109400057-7be76080-7914-11eb-9f05-1c453f81fcd3.mp4

With ssh to RHEL (newline at wrapping point):
https://user-images.githubusercontent.com/6013474/109400135-f912d580-7914-11eb-9058-15ff0b3265e6.mp4

With Putty to the same server (No issue: no newline at wrapping point):
https://user-images.githubusercontent.com/6013474/109400224-73435a00-7915-11eb-8dde-b34d31013fef.mp4

Look for the line-number  (in the hardstatus bar at the bottom) in the vi to detect the newline

**Comment by mintty** [comment]
It's actually a duplicate of #971.

**Comment by mintty** [comment]
Cygwin 3.2.0 has been released which enabled ConPTY support only for non-cygwin apps.
