### ISSUE TITLE
Binaries Download Link?

### ISSUE THREAD

**Issue by strarsis** [mintty/mintty#659]
The mintty website links to Releases page of this GitHub repository - but only the source is available as download. Where can I find the latest binaries?

**Comment by mintty** [comment]
Binaries are not published, since release 2.0.1. The primary environment for mintty is cygwin, where binary packages are available with cygwin setup.

**Comment by strarsis** [comment]
So I install minitty using the Cygwin installer?

**Comment by mintty** [comment]
Yes, it's installed by default, within the base package category. Didn't you try?

**Comment by cup** [comment]
https://github.com/mintty/mintty/issues/812
