### ISSUE TITLE
new feature to show size of selected text.

### ISSUE THREAD

**Issue by pocoleo** [mintty/mintty#660]
Is it possible to have the size of selected text displayed when hovering over selected text.  this would also allow the screen size to be determined by selecting all the text in the window.

**Comment by mintty** [comment]
This would be possible (for a pattern see terminal size popup display while resizing) but I don't see the use case and have no personal interest to implement it.

**Comment by mintty** [comment]
Released 2.9.0.

**Comment by mintty** [comment]
Released 2.9.1.
