### ISSUE TITLE
Mintty fails to startup when environment variables contains Unicode U+26C4

### ISSUE THREAD

**Issue by donno** [mintty/mintty#662]
I had defined an environment variable through the System Properties -> Environment Variables in Windows 10, which was was called ☃ and value of Test.

Attempting to launch Mintty would result in nothing appearing but a mintty.exe.stackdump.

**Comment by mintty** [comment]
This happens only with Cygwin 64-Bit. It works fine with Cygwin 32-Bit.
Also it happens alike if you try to start a Cygwin Console (Cygwin.bat script), so it's not a mintty issue.
Please report to the cygwin mailing list.

**Comment by mintty** [comment]
Fixed in cygwin 2.8.1.
