### ISSUE TITLE
64 bit install refuses to launch

### ISSUE THREAD

**Issue by DracoMan671** [mintty/mintty#665]
it says it cannot find mintty, but i checked its directory and everything is there. should launch just fine, for now i am using 32 bit version. OS is windows 10 creators update.

**Comment by mintty** [comment]
This does not really sound like a mintty issue. Can you provide details of the error message (screenshot perhaps)?

**Comment by DracoMan671** [comment]
Cygwin 64 bit cannot find mintty when launched from start menu or desktop,
batch file in install location works fine but when launched from anywhere
else it says "windows cannot find mintty." I will select it manually but it
refuses to launch after. OS is windows 10 64 bit creators update. Processor
is AMD A10 8700P APU. This is on an ASUS X555DA-WS11 laptop. Do these specs
have anything to do with it?

**Comment by DracoMan671** [comment]
My computer wont be available for use until wednsday or thursday, i will
try and get a screenshot of the error when i can use it again.

**Comment by mintty** [comment]
I have no issue launching from the desktop, Windows version 1703.

**Comment by DracoMan671** [comment]
It might be my internet connection, i have so-so n. Not AC which is much
faster. I have also repeatedly encountered errors post-installation. It is
currently a post installation error. It installs then will not launch and
says "windows cannot find mintty" i have had errors during installation
though.

**Comment by DracoMan671** [comment]
Is it the x86_64 version or x86 version. I am using x86_64 version while
encountering the error.

**Comment by DracoMan671** [comment]
My specs might have something to do with the issue, please review them
thoroughly. (My specs are crap to be honest i cant get an even 2ghz out of
my processor)

On Jun 20, 2017 6:17 PM, "Drago DracoMan671" <luvpizza715@gmail.com> wrote:

Is it the x86_64 version or x86 version. I am using x86_64 version while
encountering the error.

**Comment by DracoMan671** [comment]
Im sorry if i am a bit annoying, i have ADHD, i can get pretty worked up if
something does not go as planned =P

**Comment by mintty** [comment]
There's no problem with you reporting this but the details are not really helpful, esp. the processor should not really matter. Also, as I said, since this works everywhere else, you seem to have a local issue, like you said (problems during installation) — what about a fresh installation?

**Comment by DracoMan671** [comment]
Tried force uninstalling using iobit, reinstalled, now it works fine =P

**Comment by mintty** [comment]
So I suggest you close this issue.

**Comment by DracoMan671** [comment]
Will do l8er, im out doing errands
