### ISSUE TITLE
Ctrl-Shift-Tab with a single window makes the window always-on-top

### ISSUE THREAD

**Issue by brechtm** [mintty/mintty#667]
Pressing the Switch Windows shortcut when only one mintty window is open causes that window to get stuck in always-on-top mode.

mintty version: 2.7.7 (x86_64-pc-msys)

**Comment by mintty** [comment]
I suppose you mean Ctrl+Shift+TAB.
This has been fixed in the repository version a week ago.

**Comment by brechtm** [comment]
I checked again, and indeed it's Ctrl-Shift-Tab that is the culprit. Thanks!

**Comment by mintty** [comment]
Released 2.7.8.
