### ISSUE TITLE
Glitches when displaying Unicode emoji

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/mintty#671]
mintty seems to misdetect the width of Unicode emoji (e.g.: 🍳), causing display glitches. The issue is not exclusive to mintty, it also happens with e.g. PuTTY, but I've ruled out mostly everything else. It happens even in a local shell with no tmux or anything, and my locale settings are all UTF-8 – both in mintty and the environment. Tried many different fonts: Consolas, DejaVu Sans Mono, Fira Mono, Input Mono...

**OS**: Windows 10 Home x64 (Creators Update), Ubuntu 17.04 in Windows Subsystem for Linux
**mintty**: 2.7.8 (wsltty 0.7.83)

Also tested with mintty 2.7.3 (Git Bash 2.12.2.windows.2)

<details>
<summary>Locale settings</summary>

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
</details>
<br />

Examples:
* https://i.imgur.com/M9xx2nK.png
* https://f.lewd.se/ESfyWU_2017-07-16_14-32-08.mp4
  * The text entered is `🍳 one 🍳 two 🍳 three 🍳 four 🍳 five`.

**Comment by mintty** [comment]
Unless with issues #638 or #615, in this case the respective character is wide, but only since Unicode 8.0, when it was changed from being narrow in earlier versions.
As soon as cygwin locale data are updated to be based on a later Unicode version, display should adapt automatically.
For now, the only solution would be to offer an option to define character width based on mintty's own width data (like xterm -mk_width, see also #88).

**Comment by alanfran** [comment]
There has been some activity on the Cygwin mailing list that appears to be about this issue.

[Original Post (July 26)](https://cygwin.com/ml/cygwin/2017-07/msg00366.html)
[Subject Index](https://cygwin.com/ml/cygwin/2017-07/subjects.html#00366)

**Comment by mintty** [comment]
Yes, I asked for an update and provided a patch meanwhile.

**Comment by nshtg** [comment]
2.8.0 has these Bugs. Has there been any progress?

Also: Is it planned to enable "custom" fonts to provide emojis (and other Unicode chars), e.g. with color?

**Comment by mintty** [comment]
As explained above, this is not really a mintty issue (although there could be a workaround) but a cygwin/locale issue. My request to update cygwin Unicode data has not yet been accepted.

**Comment by mintty** [comment]
Emojis can be displayed like normal glyphs if the selected font includes them.
Whether colour glyphs are displayed, depends on support by the Windows API being used (Uniscribe);
I doubt it.

**Comment by nshtg** [comment]
Is there a specific reason why you prefer Uniscribe over DirectWrite?

**Comment by mintty** [comment]
See #430.

**Comment by mintty** [comment]
Released 2.8.1 with new option `Charwidth=unicode` to activate built-in character width reference.

**Comment by nyuszika7h** [comment]
Looks good, I'm no longer getting the glitches with that option enabled.

**Comment by nshtg** [comment]
I can confirm the fix too. Thank you!!

**Comment by mintty** [comment]
The current repository upload provides full emoji support.

**Comment by lizy14** [comment]
`Charwidth` and `Emojis` does not work together.
steps:
1) paste an emoji
![image](https://user-images.githubusercontent.com/9985286/35995195-9c9b7810-0d4d-11e8-8be7-daa35990b1da.png)
2) press `Home`
![image](https://user-images.githubusercontent.com/9985286/35995204-a5241e56-0d4d-11e8-8daa-3dfbd7e14e95.png)
note that the cursor is no longer visible
3) key-in `12`
![image](https://user-images.githubusercontent.com/9985286/35995263-c255f3d2-0d4d-11e8-8763-8c8da49eb8a9.png)
note the unexpected width
4) press `Home` again
![image](https://user-images.githubusercontent.com/9985286/35995297-dde9dd84-0d4d-11e8-9719-72811f12b8c8.png)
note the unexpected cursor position
5) key-in `12` again
![image](https://user-images.githubusercontent.com/9985286/35995320-ed08acb4-0d4d-11e8-8267-119b578b9769.png)
nothing but chaotic. expecting `1212`, got ` 1 21212` instead.
config:
```
Charwidth=unicode
Emojis=apple
EmojiPlacement=middle
```
with Windows 10 latest.

**Comment by mintty** [comment]
Released 3.1.5 with explicit character width attribute support.

**Comment by fmaiabatista** [comment]
Hey guys,

I'm having difficulties understanding why I can't get an emoji to display inside Cygwin/Mintty whereas it is displayed correctly in Msys/Mintty

The image should be self explanatory - Cygwin/Mintty on the left, Msys/Mintty on the right - both Fira Code, 11pt, no other changes

Worth mentioning I'm not terminal/shell savvy to the point of not understanding exactly what is the definition of a terminal as opposed to a shell and how Cygwin x Mintty x Msys compare and interoperate.

More info: running [Fish ](https://fishshell.com/) as the shell and [Starship ](https://starship.rs/) as the theme. Windows 10.

![image](https://user-images.githubusercontent.com/1574224/85336781-9f205d00-b4b5-11ea-9321-352185a53423.png)

**Comment by mintty** [comment]
Where did you install the emojis? If you put them into your MSYS home directory (~/.config/mintty/emojis), cygwin cannot see them because your home directory is somewhere else (unless reconfigured). You'll have to copy (or hard-link) the emojis into your cygwin ~/.config/mintty/emojis, or move them to a common place: $APPDATA/mintty/emojis.

**Comment by fmaiabatista** [comment]
I'm not sure I know where I installed the "emojis" because all I did a while back was get the Fira Code font for my editor and also get the Powerline fonts. So because I'm on Windows all I did was install the fonts and now they appear in Font Manager.

![image](https://user-images.githubusercontent.com/1574224/85410483-8bb8d480-b53d-11ea-8c79-8c004190b839.png)

I couldn't find any of the paths you mentioned at `~/.config/mintty/emojis` (either cyg or msys) or `%appdata%/mintty/emojis`

**Comment by mintty** [comment]
So do you actually have coloured image emojis? Or just the font-included monochrome emoji glyphs?
In that case, it may just be a matter of using different fonts.

**Comment by fmaiabatista** [comment]
I believe it's the first case, monochrome font-included emoji glyphs.

> In that case, it may just be a matter of using different fonts.

That's the thing. I expected it would work in both because they are running the same "terminal emulator" behind (mintty 3.1.8)?

**Comment by mintty** [comment]
You have local configuration and common configuration.
To install real emojis, please check the wiki Tips.
