### ISSUE TITLE
Custom bell sound

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/mintty#672]
I can't see an option to set a custom bell sound. It would be nice, because in Windows 10, almost every single listed sound is the same, and it's really annoying as a terminal bell

**Comment by mintty** [comment]
Options – Terminal – Bell – Wave
You can select among the .wav files in your resource subdirectory `sounds` (see manual page for the possible locations of the resource directory).
Or you can drag-and-drop the name of a .wav file here.
(There isn't yet an option to drag-and-drop a URL like it can be done for the Theme.)

**Comment by mintty** [comment]
Duplicate #369.

**Comment by nyuszika7h** [comment]
Thanks. Maybe a "Browse" option should be added, or a note, because it's not obvious at all that you can drag and drop a .wav file to use a custom sound.
