### ISSUE TITLE
Starting mintty maximized reports default cols/lines

### ISSUE THREAD

**Issue by rmsr** [mintty/mintty#675]
(technically I noticed this in wsltty but this seems the right location)

Using a shortcut, mintty can be set to open as a maximized window, which works fine. However, the screen dimensions reported to the environment are the default ones until the window is un- and re-maximized.

**Comment by mintty** [comment]
How exactly do you tell it to open maximized?
If I start `mintty --window max` in cygwin, `stty size` reports properly.

**Comment by rmsr** [comment]
You provide some shortcuts in the wsltty package, if you open the shortcut properties tab, the run option lets you set it maximized.

**Comment by mintty** [comment]
In that case as well, Ubuntu on Windows reports `stty size` properly for me.
What if you try to maximize with the `--window max` option?

**Comment by rmsr** [comment]
That's working great, I'm a little embarrassed I didn't look for a cmdline flag as a solution. Ah, github does support attaching images. Well, here's some repro screenshots:

![stty_size](https://user-images.githubusercontent.com/118038/28999309-7dfd8d02-79f6-11e7-8d74-319d163b55d0.jpg)

![properties](https://user-images.githubusercontent.com/118038/28999310-8137c730-79f6-11e7-9aab-f2789d9c0dc7.jpg)

**Comment by mintty** [comment]
There must be something in your startup scripts (.profile/.bashrc) that causes this issue. Run: Maximized works for me, with proper `stty size`. Closing.
