### ISSUE TITLE
Backarrow sends ^H not applied on startup

### ISSUE THREAD

**Issue by sharktamer** [mintty/mintty#677]
The setting "Backarrow sends ^H" under the "Keys" section in the settings does not apply on startup if it is ticked. In order for it to work, the setting needs to be off at startup, then it needs to be ticked and config saved. It is only after this that the setting is applied to the current session.

**Comment by mintty** [comment]
Works here as expected. Maybe you have some startup or prompt code in your shell profile that dynamically resets this mode?

**Comment by mintty** [comment]
Closing as no bug was demonstrated.
