### ISSUE TITLE
Mintty windows stay on top after use of ctrl + shift + tab (windows 10)

### ISSUE THREAD

**Issue by begin-again** [mintty/mintty#678]
I'm using Git Bash with mintty 2.7.7 (x86_64-pc-msys) on Windows 10. I've noticed that if I open 1 or more terminals and then use the keyboard shortcut `ctrl+ shift + tab` to switch between them, I can no longer bring any other window on top of a mintty window that lost it's focus. The terminal that received focus is not effected unless I switch focus from it to another with `ctrl + shift + tab`.

**Comment by mintty** [comment]
Duplicate of #667; fixed in mintty 2.7.8.
