### ISSUE TITLE
How to change the theme from bash?

### ISSUE THREAD

**Issue by nowox** [mintty/mintty#685]
On the [wiki](https://github.com/mintty/mintty/wiki/Tips#using-colour-schemes-themes) section 'Using colour schemes (“Themes”)', it explains how to configure themes. However I haven't found any information on how to change the them on the fly. 

I had previously my color scheme set on my .bashrc with a function `dark` for the dark theme and `light` for the light theme. I often use the light theme is pretty useful for presentations. 

Now I have put these two themes on `~/.config/mintty/themes/light.minttyrc` and `~/.config/mintty/themes/dark.minttyrc`. I configured my default theme with `ThemeFile=dark.minttyrc`. 

How can I switch between dark and light themes directly form bash? I guess there is an escape key sequence to do this, but I haven't found it. 

Is that possible?

**Comment by mintty** [comment]
It's possible, but the theme files are not in a format that could be either sourced or catted directly.
I was once preparing a script to transform and apply that automatically and will look after it now.

**Comment by mintty** [comment]
I've uploaded a theme switcher script to the [utils](https://github.com/mintty/utils) repository.
Considering whether/how to include it in the main repository and future releases/deployment.

**Comment by nowox** [comment]
Awesome, it works like a charm and using themes is much more elegant than having the color settings in my .bashrc. 

Thanks

**Comment by mintty** [comment]
Released with 2.8.0.
