### ISSUE TITLE
mintty responds CAN(^X) when received an invalid DECRQSS request.

### ISSUE THREAD

**Issue by ttdoda** [mintty/mintty#689]
When mintty received an invalid DECRQSS requests, mintty responds CAN(^X).
https://github.com/mintty/mintty/blob/master/src/termout.c#L1373

I expected that "DCS 0 $ r ST" would be replied.
VT382 and VT525 reply "DCS 0 $ r ST".

**Comment by mintty** [comment]
Thanks. Do you have access to those original terminals?

**Comment by mintty** [comment]
Released 2.8.0.
