### ISSUE TITLE
DECSCUSR support for DECRQSS status query.

### ISSUE THREAD

**Issue by ttdoda** [mintty/mintty#690]
mintty supports DECSCUSR cursor shape change sequence, but not supported in DECRQSS status query and replies CAN(^X).

This issue and #689  are cause of mintty/wsltty#55.

**Comment by mintty** [comment]
Thanks for analyzing this. To be fixed.

**Comment by mintty** [comment]
Actually, xterm also responds ^X to DECSCUSR, so I'm puzzled how this should only happen in mintty.
To be fixed according to spec anyway.

**Comment by mintty** [comment]
Released 2.8.0.
