### ISSUE TITLE
Line buffer not working properly

### ISSUE THREAD

**Issue by wyykak** [mintty/mintty#691]
I am using mintty with msys2(x64). However,  I have found out that mintty's line buffer works like full buffer.
For example:
_...
printf("blablabla");
system("PAUSE");
..._
The result:
_Press any key to continue (I pressed a key)
blablabla_

What's worse, even if I use a scanf() to read data the context in the buffer won't be printed on the screen, which is against the C/C++ standard.

I have tested my program with Windows' cmd.exe, and it work properly. Now I have to use fflush() after every printf() or use setvbuf() to set the buffer mode to no buffer.

By the way, I'm using Windows 10 x64, mintty 2.7.7, and gcc 7.2.0.
Is this a bug?

**Comment by k-takata** [comment]
This behavior might be undesired, but it's not a bug. See the following links:
http://mintty.github.io/#compatibility
https://github.com/mintty/mintty/wiki/Tips#inputoutput-interaction-with-alien-programs

**Comment by wyykak** [comment]
Well, thanks! I'm sorry I didn't read the wiki thoroughly.
By the way, iostream(cout) works properly.

**Comment by mintty** [comment]
Thanks, @k-takata, for the clarification.
As you referred to the C standard, @wyykak, I'd like to add that `system("PAUSE")` is not C standard as it invokes an external program, outside the C domain.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
