### ISSUE TITLE
Windows On-Screen Keyboard: AltGr special characters not working

### ISSUE THREAD

**Issue by a-st** [mintty/mintty#692]
I'm experiencing issues while using Cygwin64 Terminal on my Windows 10 Pro x64 tablet while typing on the on-screen keyboard with German keyboard layout. It simply doesn't detect the AltGr special characters (like @, |, \, and so on).

**Screenshot**
![Screenshot](https://i.imgur.com/cz0RMtq.png)

**System information:**
- OS: Windows 10 Pro x64
- mintty 2.7.9 (x86_64-pc-cygwin)

**Comment by mintty** [comment]
The other modifiers work? (Strg, Umsch, Alt) Do you normally have to hold the modifier key and keep it pressed while pressing the second key?
Does it work in other programs, e.g. notepad?
For further diagnostics, you might compile mintty with some debugs enabled (remove "dont_" prefix):
#define debug_virtual_key_codes in wininput.c
maybe #define debug_messages in winmain.c

**Comment by mintty** [comment]
Apparently it's possible to run the on-screen keyboard on a non-touchscreen and use it with the mouse.
I can reproduce the issue.

**Comment by mintty** [comment]
The behaviour of the on-screen keyboard is not compatible with a real keyboard: it reports the AltGr without a scancode (0) and with VK_RMENU and VK_LMENU state exchanged.
This is a bug of the on-screen keyboard; please report to its author (assumedly Microsoft).

**Comment by mintty** [comment]
I've uploaded a workaround. Please check.

**Comment by a-st** [comment]
I compiled latest version of mintty and installed it in Cygwin. Now everything works as expected. Thanks a lot!

**Comment by mintty** [comment]
Released 2.8.0.

**Comment by danowar2k** [comment]
This workaround borks working via Teamviewer. See other issue.
