### ISSUE TITLE
put in vim doesn't work right

### ISSUE THREAD

**Issue by willt** [mintty/mintty#693]
when using vim if you yank a line (y) then put it with p or P it pastes the line on the same line instead of below or above the current line.

vim 8.0.606
mintty 2.7.9

**Comment by k-takata** [comment]
It doesn't seem to be related to mintty.

**Comment by willt** [comment]
how so ?

**Comment by k-takata** [comment]
What's the reason you think it is related to mintty? Does it occur only on mintty and doesn't occur on Command Prompt?
Does it occur when you execute vim with `vim -N -u NONE -i NONE` (no .vimrc and no plugins)?
Moreover, your description is unclear. `y` doesn't yank a line, `Y` or `yy` does.

**Comment by willt** [comment]
sorry for the type.
You right though. Turns out "set clipboard=unnamed" was breaking it.
thanks
