### ISSUE TITLE
URL detection in SSH?

### ISSUE THREAD

**Issue by nattofriends** [mintty/mintty#694]
I am using mintty from Git for Windows. URL detection seems to work when just using bash normally, but when I use ssh, mintty doesn't detect URLs in the terminal of the remote host.

**Comment by mintty** [comment]
Of course not. Mintty interprets path names locally, how else could it be?
If you have mounted your remote file system on Windows, too, however, you can trick it into corresponding pathname interpretation by suitable symbolic links.

**Comment by nattofriends** [comment]
I mean URLs like `http://www.google.com`, that doesn't need to be local to be detected.

**Comment by mintty** [comment]
If you Ctrl+click a web URL, mintty simply opens it. It does not matter which local or remote shell is running.
Please describe your issue more precisely, maybe with a screenshot, and all symptoms.

**Comment by mintty** [comment]
I was assuming you run a local mintty and invoke a remote shell within it.
Or are you running a remote Windows desktop with a mintty therein?
In that case, of course, mintty would try to open the URL on the remote system. Whether that is visible for you or not, depends on the features of the remote desktop system (maybe it's only a single remote window?).

**Comment by nattofriends** [comment]
Yes, I run a local mintty and ssh to a remote host. When there is a URL present in the output inside ssh, the URL is not clickable.

**Comment by k-takata** [comment]
Do you use any application when the URL is not clickable?
How about just typing a URL on bash or cat a text file which contains a URL?

**Comment by nattofriends** [comment]
Just typing the URL or catting a file with the URL does not work either.

**Comment by mintty** [comment]
@k-takata had a valid hint. I was puzzled by this report but your terminal has probably activated some mouse mode that prevents default click behaviour. May the ssh client itself, which are you using? Or is any additional terminal multiplexer involved, like screen or tmux?
This is not directly related to remote vs. local. When clicking, mintty just inspects what is on screen.

**Comment by nattofriends** [comment]
Sorry, that's something that I neglected to explain. I am using tmux. However, URL detection works inside tmux in iTerm, so I didn't think that it could be an issue.

**Comment by k-takata** [comment]
You may want to try Ctrl+Shift+click, if you want to use URL detection even if some kind of mouse mode is activated.

**Comment by nattofriends** [comment]
This works for me. Thanks!

**Comment by mintty** [comment]
Please support some further analysis:
*  Does it work for you without starting tmux (only ssh)?
*  After starting tmux, if you kill it (from another session, kill -9 please), and then click into the terminal, does it generate any mouse codes?

I've checked that cygwin tmux does not activate mouse mode precautiously, but some remote tmux might do so. If it doesn't, we still have no explanation.

**Comment by nattofriends** [comment]
I have mouse support enabled in the tmux which I started at the remote
host.

**Comment by mintty** [comment]
OK, for transparent mouse support (i.e. supporting mouse usage of remote applications) this would not be necessary, but if want to bind mouse actions to tmux functions, I understand.
However, this obviously means that some of the default mouse functionality is overridden.
And while apparently iTerm would in turn override that back if you click with Ctrl, mintty doesn't. The reason is that mintty supports applications to use distinct mouse events with a Ctrl modifier. This could not work in iTerm.

**Comment by nattofriends** [comment]
iTerm supports it with Cmd-click. So maybe iTerm still supports mouse events with Ctrl modifier.

**Comment by avih** [comment]
In mintty shift is the default to override application which use the mouse. Like ctrl+wheel for text size, but with an application which registers mouse events it becomes ctrl+shift+wheel, or double click to select a word, but shift + double click within an application that use the mouse, etc.

You can change it from shift to something else at the bottom of the mouse settings: "Modifier for overriding default".

**Comment by mintty** [comment]
Thanks, @avih, and I think we can close this issue as mintty supports the desired feature, just maybe not the same way as some other terminals.

**Comment by jdhao** [comment]
I have also met this issue. When mouse mode is enabled for Neovim and Tmux, to open an URL in browser, I have to use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+`click` . If the mouse mode is turned off, I can open an   URL with just <kbd>Ctrl</kbd>+`click`.

**Comment by mintty** [comment]
Released 2.9.7.
