### ISSUE TITLE
Window position moves relative to mouse cursor when moving between displays with different DPI scaling

### ISSUE THREAD

**Issue by Ede123** [mintty/mintty#696]
Also visible in the screen capture of #695:
The cursor position changes relative to the window position when moving between displays with different DPI scaling. The "error" accumulates eventually moving the cursor completely off the mintty window when moving back and forth several times.

![mintty_2 7 9](https://user-images.githubusercontent.com/904570/31627455-a0d73c20-b2ad-11e7-8c7a-acf898610a65.gif)

**Comment by mintty** [comment]
When rescaling to another DPI, mintty repositions itself. What the Windows mouse pointer does meanwhile, is out of control of mintty. Probably unfixable.

**Comment by Ede123** [comment]
If mintty repositions itself in a way that maintains the windows relative position to the mouse cursor the issue would probably be solved.

I agree this might require some effort that might not be worth it, but I fail to see how this could be unfixable?

**Comment by mintty** [comment]
Maybe my previous comment was a bit speculative as I don't have a dual-monitor Windows 10 system at hand. But whenever mintty rescales, it also calls a position fix win_fix_position

**Comment by mintty** [comment]
Maybe my previous comment was a bit speculative as I don't have a dual-monitor Windows 10 system at hand. But whenever mintty rescales, it also calls a position fix (win_fix_position in winmain.c) in order to prevent it from reaching out of the current monitor. Maybe it would help to drop that, at a cost...

**Comment by mintty** [comment]
Released 2.9.0 with support for DPI handling V2. Please recheck.

**Comment by Ede123** [comment]
2.9.0 works mostly. There's seems to be one rare case where the mouse pointer still changes position relative to the window when moving between monitors, but I wasn't able to find any system behind it yet (or steps to reproduce reliably for that matter). When moving multiple times back and forth it happens sporadically.

Thanks for fixing!

**Comment by mintty** [comment]
Released 2.9.5 with changed default HandleDPI=2.
