### ISSUE TITLE
Aero snap not always working after moving between displays with different DPI scaling

### ISSUE THREAD

**Issue by Ede123** [mintty/mintty#697]
Possibly related to #696:
After moving mintty between displays with different DPI scaling aero snap is broken in some cases (I often experience this issue as I grab mintty on my primary monitor, move it to my secondary monitor and then want to snap it to the side of this display).

Steps to reproduce with the setup described in #695:
* start with mintty on the primary (right) display with 100% scaling
* grab the window in the right part of the titlebar (e.g. close to the minimize button)
* move it over to the secondary (left) display with 150% scaling
* without releasing try to snap it to the left border of the secondary display
-> won't work (one needs to release and re-grab the window first

The same works the other way round:
* start with mintty on the secondary (left) display with 150% scaling
* grab the window in the left part of the titlebar (e.g. close to the icon)
* move it over to the primary (right) display with 100% scaling
* without releasing try to snap it to the right border of the primary display
-> won't work (one needs to release and re-grab the window first

Interestingly when grabbing the titlebar at the opposite end of what I described in these two scenarios Aero snap in fact *will* work.
An educated guess suggests #696 might cause this problem: As the cursor is moved off the mintty window, the mintty window has already left the active desktop area when the cursor hits the display border which probably causes Aero snap's implementation to fail.

**Comment by mintty** [comment]
2.8.3 includes a tweak that is possibly related or could at least have impact (mintty/wsltty#80).
Does it fix the issue?

**Comment by mintty** [comment]
Released 2.9.0 with support for DPI handling V2. Please recheck.

**Comment by Ede123** [comment]
2.9.0 works nicely as far as I can tell. Thanks for fixing!
