### ISSUE TITLE
Is there a way to run the terminal full screen?

### ISSUE THREAD

**Issue by sittim** [mintty/mintty#704]
Is it possible to run the terminal in full screen, so the windows taskbar and the windows header is not shown in windows 10?

**Comment by mintty** [comment]
Yes.

**Comment by sittim** [comment]
Is there a shortcut?

**Comment by mintty** [comment]
You can also start with `-w full`.
Fullscreen window size with title bar would be `-w max`, or click the Maximize button/menu item in the title bar.
