### ISSUE TITLE
Selectively enable Ctrl+Shift shortcuts

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/mintty#705]
I enabled Ctrl+Shift shortcuts to use Ctrl+Shift+C and Ctrl+Shift+V, but the shortcut Ctrl+Shift+R, which resets the terminal, conflicts with bash/zsh reverse history search, so I'd like to disable or remap it. (I know I could remap the shell's one, but I'd rather not.)

**Comment by mintty** [comment]
You could use option `CtrlExchangeShift` to assign copy/paste to unshifted Ctrl+C/V, but that may not be what you want, also it would reassign Ctrl+R, too (but not Ctrl+Shift+R in that case).
You could also support issue #645 if that's what you want.

**Comment by jnachtigall** [comment]
> I enabled Ctrl+Shift shortcuts to use Ctrl+Shift+C and Ctrl+Shift+V

@nyuszika7h Don't want to derail the issue, but how did you do this? I am looking for using `Ctrl+Shift+C` and `Ctrl+Shift+V` in Git bash for Windows - instead of the default `Ctrl+Ins`, but despite looking/searching for it some time now I cannot find any settings for this.

**Comment by mintty** [comment]
Options...
```
├─Keys
             ☑ Ctrl+Shift+letter shortcuts
```

**Comment by mintty** [comment]
Released 2.9.1.

**Comment by williford** [comment]
Was this closed because this feature will not be added or because there is a way to do this now? I also would like to enable just the ctrl-shift copy and paste commands without also enabling the ctrl-shift-R clear screen.

**Comment by johannish** [comment]
Thanks for `KeyFunctions=c:copy;v:paste`! That's what I was after.

The man page doesn't make it clear to me why that shouldn't be `KeyFunctions=CSc:copy;CSv:paste` (`CS` to specify "ctrl+shift"), but I tested that and it didn't work for the paste. Can anyone shed some light here why `c:copy` works and not `CSc`?

**Comment by mintty** [comment]
It's CS+c to separate the modifier from the key, or C+S+c.
