### ISSUE TITLE
New window comes up with super-small font when Ctrl+Shift+N is used

### ISSUE THREAD

**Issue by vadimkantorov** [mintty/mintty#708]
I'm using WSLtty.

When I open a new session with Alt+F2, the font size is the same as in the original window. If I use Ctrl+Shift+N, then the font size is much smaller. The laptop screen resolution is quite high, so super-small fonts are impossible to work with. And Alt+F2 requires finger squeezing to press actually Alt+Fn+F2.

Would also be super-nice if the new window respected the original window size (and position?) -
 especially when the graphic virtual tabs start working. Currently I have to maximize it every time manually.

Thanks!
![screen](https://user-images.githubusercontent.com/1041752/32408649-ec11c7bc-c19b-11e7-87b9-f738cf64055b.jpg)

**Comment by vadimkantorov** [comment]
The font problem happens mostly when the original windows was full-screen.

**Comment by mintty** [comment]
This is somehow related to font zooming on screen resizing (#204) but of course there is no resizing involved here from a user point of view.

**Comment by mintty** [comment]
Released 2.8.2.
