### ISSUE TITLE
Ctrl+U not working when entering ssh password

### ISSUE THREAD

**Issue by vadimkantorov** [mintty/mintty#709]
Works with Putty, and works with mintty outside ssh password typing.

I'm using WSLtty, so maybe it's actually a WSL problem?

**Comment by mintty** [comment]
There is no specific ^U handling in mintty.
Check:
^V^U in shell
stty -a
type ssh

**Comment by mintty** [comment]
It works neither in xterm nor in a Windows console (the WSL native launch method).
So it's not a mintty issue. Rather a peculiarity of WSL ssh. Putty has its own ssh client, so that's not a test case to compare.
