### ISSUE TITLE
Save scroll buffer to a file or auto log

### ISSUE THREAD

**Issue by nobk** [mintty/mintty#715]
When I close the mintty window, I will lost all scrollback info, and it will never come back.

mintty have 'Scrollback lines' settings already, can you add a feature to save that buffer to a file. That is very useful when I need to track back my working history.

It will be even better if mintty can make a auto log of the scroll buffer. In Options, turn on scrollback buffer log, and set log dir (eg. /var/log/mintty), mintty can auto log every output to files like '20171111-session3F0A.log'.

**Comment by mintty** [comment]
For saving the scroll buffer on demand: you could use a user command for that purpose, the scroll buffer is provided in variable MINTTY_BUFFER.
For unconditional logging: that feature is also available already.
Check the manual.
