### ISSUE TITLE
[feature request] Reset current session

### ISSUE THREAD

**Issue by vadimkantorov** [mintty/mintty#716]
A stalled ssh session takes many seconds to get "Connection reset", and Ctrl+C / Ctrl+Z doesn't help (I'm using WSLtty with WSL's ssh).

A terminal way (and a keyboard shortcut?) to kill the current session would be great.

**Comment by mintty** [comment]
Interrupt options are ^C, ^\ (stronger), and ^Z (after which you can kill explicitly).
If all don't work occasionally, that's normal Unix/Linux behaviour; I don't think it's the task of the terminal to intrude into the user's shell sessions. I don't know of any other terminal that would offer this. You can always close the terminal of course.  You could also trick a "user command" (see the manual) to achieve the desired function; I could add an environment parameter MINTTY_FGPID for that purpose.

**Comment by vadimkantorov** [comment]
Yep, basically I wished a convenient way to close-open the terminal in the same window localtion (and probably keep the same session name, position in the session list)

**Comment by mintty** [comment]
Released 2.8.2.

**Comment by vadimkantorov** [comment]
`Send Break` doesn't help to kill hung a stale ssh session.

Steps for repro: have an open ssh connection, hibernate the machine, restore it, observe the hung ssh connection, try `Send Break`

**Comment by mintty** [comment]
Send Break mimics the traditional "BRK" feature of terminals with serial connection. That's all that such a terminal could achieve. See the manual page, section "Terminal Break", about the inherent limitation of this feature, but also about a hint how to set up a stronger interruption.
