### ISSUE TITLE
avoid select while window active

### ISSUE THREAD

**Issue by lededev** [mintty/mintty#717]
When I switch from other application to mintty by mouse click, or switch between two mintty windows,  it is often get two effects: 
1. mintty window change from inactive to active.
2. some characters were selected by that mouse click with slightly mouse moving(with a high DPI mouse).

If I set the option 'Copy on select', that means my clipboard data was overwritten by this action.
I have to go back to copy source window and copy again because of that. Or I have to switch between mintty windows very carefully, and that will reduce my efficiency of operation.
Can you let the mouse select not so sensitive while a mintty window from inactive JUST become active? Or ignore select action at all while window just become active.

**Comment by lededev** [comment]
Hi, this commit of enhancement make mouse left button click to active mintty window avoid select action pretty good!
But mouse click using right or middle button actions also changed, only active window no pop up menu or paste, I think that is a side effect should not happen. Only handle left click to prevent select is ok, let right or middle click act as before well be better for users habit.

**Comment by mintty** [comment]
Thanks, and also a click on the window border should not be ignored, esp. to move the window.
Fixed.

**Comment by mintty** [comment]
Released 2.8.2.

**Comment by mintty** [comment]
I've revised the handling to allow other mouse functions (see issue referencing above).
You may like to check the update.

**Comment by mintty** [comment]
Released 2.8.4.

**Comment by mintty** [comment]
Another revision:
Suppressing selection completely was not satisfying. Introduced a threshhold of spanned mouse drag-and-drop distance (delta-x + delta-y > 1) above which even a drag-and-drop started with an initial focus click would cause text to be selected.
You may wish to check out this change.

**Comment by mintty** [comment]
Released 2.8.5: if you drag the mouse after focus-click, above a small distance threshhold, selection is reenabled.

**Comment by mintty** [comment]
I've uploaded a tweak that combines the cell distance (Euklidian) and elapsed time to decide whether to allow drag-and-drop selection after focus click:
Both are multiplied and if the result is > 999ms, selection is allowed.
Please check; the threshold could be adjusted but I do not currently plan to make it configurable.

**Comment by TyranicMoron** [comment]
I would really like a way to disable this, as it stops clicks passing through to tmux and weechat when the window is unfocused, requiring me to click twice.

I have mouse support enabled in both, and I use it to switch windows/panes in tmux and channels in weechat.
Having the mouse support enabled also means that accidental click+drag selection cannot happen, so I'm not getting any benefit out of this.

**Comment by mintty** [comment]
I'll check this myself too, but please describe in what way tmux avoids accidental mouse-triggered actions.

**Comment by mintty** [comment]
I intend to limit the suppression of focus-selection to non-application-mouse mode, i.e. while application mouse mode is enabled (and not overridden?), mouse clicks would be addressed to the application as usual, even if they are focus clicks. The idea behind this is that an application can detect all cases itself if it runs with application mouse mode.
Alternatively, focus-selection suppression could only be disabled if focus event reporting (and application mouse mode?) is enabled. The idea behind this variant is that it clearly indicates the application is aware of focus clicks and will handle them if desired.

Would that help with the tmux case? Have you configured tmux to enable mouse modes?
Comments appreciated.

**Comment by StarlitGhost** [comment]
tmux is configured to enable mouse modes, yes. Clicking and dragging in that mode uses tmux's own selection logic and does not copy into the system clipboard.

In weechat with mouse enabled, no selection occurs at all.

I'll see about building and trying this PR this weekend.

**Comment by mintty** [comment]
Released 2.9.0.

**Comment by mintty** [comment]
Released 2.9.1.

**Comment by YAMLcase** [comment]
for tmux, setting `set -g focus-events on` will enable the pane selection on focus feature.
