### ISSUE TITLE
2.8.1: Cygwin released version exponentially slows down with box drawing characters

### ISSUE THREAD

**Issue by rmzg** [mintty/mintty#722]
Situation: Have tmux session running on a debian unstable machine. Attach to the session from a device with a small screen. Attach to the same session from a windows 10 machine using mintty over ssh. 

The small screen causes tmux to draw several thousand box type characters to simulate the much smaller viewport of the other device. After slowly drawing about half the screen mintty will stop drawing, stop responding to keyboard inputs and cause the classic windows "window not responding" popup and must be force closed.

Good news: Compiling source from github:master doesn't exhibit this crash.

**Comment by mintty** [comment]
Duplicate of #712. Thanks for checking with the current version.
I wonder, though, why the box character frame should be redrawn so often...

**Comment by rmzg** [comment]
Yeah, that issue is what prompted me to try the master branch.

I didn't spend too much time debugging it but it felt like it got exponentially slower the more box type characters were being displayed.

**Comment by mintty** [comment]
Released 2.8.2.
