### ISSUE TITLE
(Not a bug) Mintty's ClearType rendering looks good on a 2.5k monitor, PuTTY's looks terrible

### ISSUE THREAD

**Issue by syskill** [mintty/mintty#723]
I'd like to find out why this is, so that PuTTY can be fixed. This isn't mentioned on the PuttyIssues wiki page, and AFAICT none of Mintty's closed issues relate to this. What's the secret?

**Comment by syskill** [comment]
Forgot to mention: this is on Windows 10.

**Comment by mintty** [comment]
What kind of "looking terrible" do you mean? Do you have a screenshot?
It might be related to DPI scaling; this is mentioned a lot of times in the mintty changelog, see for example release 2.5.0. If it's that, be aware! This was a nightmare to implement...

**Comment by syskill** [comment]
Here's Mintty and PuTTY, both using Consolas 11pt with the same color scheme:
![mintty-vs-putty](https://user-images.githubusercontent.com/93612/34063006-8410f812-e1bd-11e7-8f5f-61212efbe752.png)

Everything is smaller and blurrier in PuTTY. The serifs at the feet of the letters `i` and `l` look particularly  awful to me, like the stem is pushing through them.

I tried setting `EnableDPI=false` in my .minttyrc. That made the text bigger on my monitor but didn't make it more (or less) like PuTTY.

**Comment by mintty** [comment]
I suppose it's `HandleDPI` you were trying; you could further try whether `FontRender=textout` makes a difference, but I don't expect that. The `FontSmoothing` options (also available in the Options menu) might have an impact.

**Comment by mintty** [comment]
Any new insights?

**Comment by syskill** [comment]
Nope. `FontRender=textout` has no apparent effect. `FontSmoothing` does, but as I wrote above, I'm comparing Mintty and PuTTY with full ClearType enabled.

With only anti-aliasing enabled on both, PuTTY looks a bit better on my monitor and Mintty looks a lot worse. I don't think that's relevant, but I thought I'd mention it just in case.

**Comment by mintty** [comment]
I should have asked about your screen DPI, or "scaling" factor. Is it a high-resolution monitor?

**Comment by syskill** [comment]
The resolution is 2560x1440 on a 32" monitor, so not very high DPI.

PuTTY is looking much better for me after I changed the scaling factor of this monitor from 125% to 100% and then back to 125%. In the course of those changes I found that PuTTY does not handle moving between displays with different DPI (my laptop screen is FHD in 15"). So, I guess it was the DPI handling all along?

**Comment by mintty** [comment]
So it looks different after you switch back to the previous DPI? Strange. Apart from that, I see my first suspicion confirmed.

**Comment by syskill** [comment]
Ok, that's the answer then. Thanks!
