### ISSUE TITLE
Mintty 2.8.2  + ConEmu - Cannot select text after losing focus

### ISSUE THREAD

**Issue by Jekotia** [mintty/mintty#724]
Note:: Mintty has been acquired via cygwin in all instances here.

I'm submitting this as a mintty bug as I have confirmed the problem is not present on mintty 2.8.1, but IS on 2.8.2. I have tested this on two separate PC's, with fresh installs of cygwin+mintty.

When running mintty 2.8.2 within ConEmu, you lose the ability to select text once the window loses focus. I have found no way to restore this ability to an active terminal. Mintty on its own does no suffer from this bug.

**Comment by mintty** [comment]
See #717; a change was made on purpose to prevent accidental selection (and thus losing previous selection) when you actually just want to refocus mintty.
So you should be able to click into mintty, then select with another click. This is considered "a feature, not a bug".

**Comment by chanux** [comment]
First of all thanks for the great work!

I have the same issue after the update. Text selection capability goes away after refocus. I tried selecting after a click and it still doesn't work. Please advice on how the feature works.

**Comment by mintty** [comment]
How would a working session/"new console" configuration entry in ConEmu actually look like?

**Comment by chanux** [comment]
Hope this is what you are asking for
`%userprofile%\.babun\cygwin\bin\mintty.exe /bin/env CHERE_INVOKING=1 /bin/zsh.exe`

**Comment by mintty** [comment]
[That's not what I was asking for; I had the problem that Transparency spoils mintty display in ConEmu...]

**Comment by mintty** [comment]
It seems the root cause is ConEmu's incompatible usage of the WM_MOUSEACTIVATE message which should not be sent on every mouse click. Mintty now uses it to prevent mouse focus from accidentally selecting text already. Disabled for ConEmu as a workaround.

**Comment by avih** [comment]
This is a bit off topic, but I was using ConEmu too (with msys(1) and cmd.exe top shell windows - so not mintty in ConEmu), and moved to mintty with tmux-in-mintty, and haven't looked back. It gives me everything I used ConEmu for, and more, and has, IMO nicer integration of the window/terminal management and the terminal.

It does require setting up a new thing, which could take a while until you have everything to your liking.

Regardless though, making sure mintty and ConEmu can play nice together would be good anyway.

**Comment by chanux** [comment]
@avih I'd like to use tmux but I use a lot of byobu/tmux on servers I get on. I know there are workarounds but it's not very practical for me.

**Comment by mintty** [comment]
Released 2.8.3.

**Comment by mintty** [comment]
I've revised the tweak to allow other mouse functions.
You may like to check the update.

**Comment by CMCDragonkai** [comment]
> I just upgraded to mintty 2.8.4 and conemu 18.2.6.0. I have the child gui setting checked "Focus in child windows". This has changed one thing. I can now double click on a line, and get a highlight over it inside mintty. However Click + Drag for selection of the text still doesn't work.
> https://github.com/Maximus5/ConEmu/issues/1382

**Comment by mintty** [comment]
> Click + Drag for selection of the text still doesn't work. Maximus5/ConEmu#1382

See my comment there; the child application is getting sent a WM_MOUSEACTIVATE message every time a mouse button is clicked, independently of the "Focus in child windows" setting.
If I feel like it, I make check for another ConEmu-specific workaround...

**Comment by mintty** [comment]
Released 2.8.5 with a workaround.
