### ISSUE TITLE
The program mintty.exe version 2.3.6.0 stopped interacting with Windows and was closed. 

### ISSUE THREAD

**Issue by Slapbox** [mintty/mintty#727]
I'm using [Babun](https://github.com/babun/babun/) which uses Mintty. When I use `CTRL+C` to halt a process, Babun keeps running alright, but in the background Mintty stops responding, and shortly after Babun stops responding.

Windows Event Viewer shows: `The program mintty.exe version 2.3.6.0 stopped interacting with Windows and was closed. `

Do you have any thoughts on what may cause this? Thanks very much!

**Comment by mintty** [comment]
I have, vaguely. But 2.3.6 is a very outdated version and many things were fixed since.
So I cannot take this as an issue, sorry.
Please ask the Babun project for an update.

**Comment by Slapbox** [comment]
Thanks very much for at least that. It's still helpful.

I would have asked there, but it's seemed dead for so long. Turns out that as of one month ago it's showing signs of life.

**Comment by mintty** [comment]
Assuming you have `gcc` and `make` installed, it's easy to compile the current mintty version yourself.
