### ISSUE TITLE
Transparency slider?

### ISSUE THREAD

**Issue by rkitover** [mintty/mintty#728]
Would really like to be able to tweak the transparency level more, usually you can use a slider for this, the `high` setting is way too opaque for my taste.

If not a slider, being able to set a number in `.minttyrc` would also be good, e.g. something from `0` to `100` with `0` being completely opaque and `100` being completely transparent.

**Comment by BrianInglis** [comment]
Config numeric values allowed - see below. Used to use Glass for transparency, but many releases ago, when unfocused it became opaque background colour with no foreground content visible - maybe under Aero? 
Man page says:
"Transparency (Transparency=off)
    Window transparency level, with the following choices:
    – Off
    – Low
    – Medium
    – High
    – Glass
    The Glass option is only available on Vista and above with desktop compositing enabled.  To make this
    reasonably usable, the glass colour needs to be set to be as dark as possible in the Windows control
    panel: choose Personalize from the desktop context menu, click on Window Color, turn the colour 
    intensity up to the maximum, show the colour mixer, and turn the brightness down to black.
    Numeric transparency values ranging from 4 to 254 can be specified in config files or on the command
    line.  (Values below 4 are multiplied by 16, for backward compatibility reasons.)"

**Comment by mintty** [comment]
Duplicate of #140 "Transparency slider".
Duplicate of #682 "Precise transparency level".
See also the Transparency hotkey Ctrl+Shift+T.
If you want a transparency slider, you are welcome to propose an implementation.

**Comment by rkitover** [comment]
My apologies, I forgot to search the issues and missed the man page in the readme.

**Comment by mintty** [comment]
Since the other issue is closed, we could have left this one open.
However, as I said, I would ask for contributions. Not only would a proper Windows GUI element have to be identified and employed, it would also have to be woven into the complex hierarchy of mintty config GUI structures (winctrls.c, windialog.c). I had a look into this before and gave up because I didn't consider it worth the effort.

**Comment by mintty** [comment]
Released 3.5.1.
