### ISSUE TITLE
Option -B frame produces small title bar; unable to move window with Alt+Space.

### ISSUE THREAD

**Issue by R030t1** [mintty/mintty#729]
When passing `-B frame` there is a small title bar on the top of mintty when on Windows 10. Is this intentional? I expected the window border and nothing more.

I am also unable to move the mintty window using the "Move" option on the dialog box produced by `Alt+Space`. The cursor teleports to the small area of title bar above the text area, but the cursor is the selection caret. Attempting to click and drag selects text. If I move the cursor, without clicking, to the main text area, the cursor changes to the movement cross. Clicking and dragging at this point produces no movement.

To avoid creating another bug: Is `-B void` supposed to include the scroll bar? Would that option be considered?

**Comment by mintty** [comment]
This "title bar" is presumably part of the "frame" that you asked for. The options "frame" and "void" just configure some window style properties (see https://msdn.microsoft.com/en-us/library/windows/desktop/ms632600(v=vs.85).aspx), varying on WS_CAPTION, WS_BORDER, WS_THICKFRAME; I've also tried WS_DLGFRAME but that makes no difference. If this has the consequence that the window cannot be moved, that's out of control of mintty; ask Microsoft. However, the options were introduced to accomodate people who want a fixed and lean layout, so you would place the windows at your desired positions and not want to move them...

**Comment by R030t1** [comment]
After some testing it seems like the behavior of mintty is seen in other programs, and is new with Windows 10. It looks like it will be hard or impossible to fix. I will comment again on whether or not I was able to work around the issue; the most likely candidate for a fix seems to be keeping the title bar, but drawing over it.

**Comment by mintty** [comment]
Released 2.8.4.
