### ISSUE TITLE
Can't change initial dir in Msys app open in mintty on Windows 10 context-menu creation

### ISSUE THREAD

**Issue by BudiKusasi** [mintty/mintty#731]
it's very hard to change initial directory in Msys2 app open in mintty on Windows 10 context-menu
I created Windows 10 context-menu for Msys2 ready to open in correct preset so I created 

HKEY_CLASSES_ROOT\Directory\Background\shell\Open Msys2\command
@='
D:\MSYS\usr\bin\mintty.exe --dir "%V" -o 'AppLaunchCmd=D:\MSYS\msys2.exe' -o 'AppID=MSYS2.Shell.MSYS.9' -o 'AppName=MSYS2 MSYS Shell' --store-taskbar-properties -- -
"
But it stil open in current user home path : ~
did work without -- - , but then the MSYS2 presetting got screwed up

Can't put altogether both feature needs ?          Thanks much in advance..

**Comment by mintty** [comment]
With the final `-`, you are starting a login shell. That is likely to set the current directory to `~`. If you remove that setting from your login scripts, it will work.
