### ISSUE TITLE
Window not properly maximized when the Title Bar is hidden

### ISSUE THREAD

**Issue by bohrshaw** [mintty/mintty#732]
This command `mintty.exe --WSL= -w max -B frame -~ /bin/bash` makes a full screen window, not as expected a maximized window. The option `-B frame` seems make the OS paranoid.

**Comment by mintty** [comment]
I don't reproduce this. In the window, you can still press Alt+Enter and see the window flicker when switching from maximized to fullscreen then, which clearly indicates that it was maximized before.

**Comment by bohrshaw** [comment]
It does flicker. But my maximized window also hide the Windows Task bar (which should not be hidden).

**Comment by mintty** [comment]
Didn't notice that before because my task bar is usually in auto-hide mode.

**Comment by bohrshaw** [comment]
I previously also set the task bar auto-hide and switch between windows using Autohotkey. But I find it subtly annoying when it shows up unexpectedly from time to time. Thus today I try to experiment a different workflow with the task bar sit on the right and extremely narrowed. And then encountered this issue.

**Comment by mintty** [comment]
It seems to be a consequence of removing WS_CAPTION from the window style, as handled by Windows.
So this is a Windows bug and out of control of mintty. As a workaround, mintty could perhaps apply an explicitly calculated size and not technically maximize the window.

**Comment by bohrshaw** [comment]
As a temporary workaround, a user can simply experiment to reach a preferable window size. I settle down on `mintty.exe --WSL= -B void -~ -p 0,0 -s 187,51 /bin/bash`.

**Comment by mintty** [comment]
Uploaded a workaround.

**Comment by mintty** [comment]
Released 2.8.4.
