### ISSUE TITLE
`-s maxheight` makes the window's bottom exceed the screen

### ISSUE THREAD

**Issue by bohrshaw** [mintty/mintty#733]
Example command: `mintty.exe --WSL= -B void -~ -p 0,0 -s maxheight /bin/bash`.
Note I position the Windows task bar on the right side.

**Comment by mintty** [comment]
What I see is that the descender of the last line is clipped, but the last line is basically still visible. Is that your effect? By the way, this and #732 do not depend on `--WSL`, for some easier testing.

**Comment by bohrshaw** [comment]
Yes, that's my exact effect.

**Comment by mintty** [comment]
This behaviour is observed on Windows 10 but not on Windows 7. So I consider it a Windows bug.
I've uploaded a tentative workaround. For `B frame`, however, it makes the window 1 line too small.

**Comment by mintty** [comment]
Released 2.8.4.
