### ISSUE TITLE
How does mintty choose a Fraktur font?

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#734]
As most terminals don't offer this feature I'm interested as to how mintty chooses a Fraktur font? Currently the font seems to change to another font but I'm not sure which and it isn't any Fraktur fonts that I have installed (most, if not all, of which aren't monospace).

![image](https://user-images.githubusercontent.com/2286713/35274083-b25cb470-0032-11e8-990f-04a2fd5d1e07.png)

**Comment by mintty** [comment]
If you select an alternative font and none is installed, the system default font will be used, most likely Courier as seen in your screenshot.
For alternative font 10, the special rule gets in, that if no font is configured, mintty will try to find one itself, by matching installed font names for substring "Fraktur" or "Blackletter". If none is installed, the same fallback applies.

**Comment by mintty** [comment]
See also the manual page (and likewise in the Tips wiki page):
**Note:** Font10 has a special preference property; if it is not configured,
mintty will try to activate it anyway, looking for an installed
Fraktur or Blackletter font (ECMA-48 "Gothic").

**Comment by mintty** [comment]
Furthermore, the wiki page recommends:
To use this feature, it is suggested to install `F25 Blackletter Typewriter`.

**Comment by ElvenSpellmaker** [comment]
Thanks! =D
