### ISSUE TITLE
Can't get [ctrl+tab] working

### ISSUE THREAD

**Issue by ahmedmohiduet** [mintty/mintty#735]
My Ctrl+[shift]+tab key combination do not appear to be working properly. I have 8 Git Bash windows open. My 'ctrl+tab' key combinations letting switch me among only 3 Git Bash windows. This behaviour is changing as soon as I am switching to other Git Bash windows using 'alt+tab'. And then my 'ctrl+tab' keys letting me switch among only 4 windows with my newly focused git bash window. Any ideas how can I get around this?

I can't use 'alt+tab' since they bring up a long list of windows with other applications as well

 I am starting new windows by:
`start "" "C:\Program Files\Git\usr\bin\mintty.exe" -w full "C:\Program Files\Git\bin\bash.exe" --login`

Previously postted here: https://github.com/git-for-windows/git/issues/1417#issuecomment-361933257

**Comment by mintty** [comment]
Cannot reproduce. Works fine here. There must be something weird in your environment.
What if you start them a more usual way, e.g. by clicking the Start menu shortcut? Or running `mintty ... &` from within a shell?

**Comment by ahmedmohiduet** [comment]
It almost appearing to be happening 100% of time while resuming my windows 10 from hibernate. None my minty windows working for ctrl+tab. But as soon as I'm selecting any of my mintty windows via alt+tab. and that perticular window is now starting working fine keeping only these two particular minty windows switchable from each other via ctrl+tab

**Comment by mintty** [comment]
This is a very particular side condition and it would be useful in general to include such information with a bug report. Anyway, I still cannot reproduce this. Mintty uses a Windows API window enumeration function for cycling, and it is not guaranteed that the order of enumerated windows is stable, so that might be the technical background. I do not see this as a mintty issue.

**Comment by mintty** [comment]
Can you try to reproduce this with Cygwin, please? (To narrow down the conditions of the phenomenon.)

**Comment by ahmedmohiduet** [comment]
let me check!

**Comment by ahmedmohiduet** [comment]
ok. looks like its not happening within cygwin mintty. starting my cygwin via:
`C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`
in shortcuts

**Comment by mintty** [comment]
Thanks; you wrote it's *not* happening and later changed to "happening"; please confirm.
Does it happen only while resuming from hibernate or is it reproducible later?
Does it happen with less than 8 windows open (to reduce the test case)?

**Comment by ahmedmohiduet** [comment]
Hi mintty, this is weird. At first I had started 3 of my cygwin windows and had hibernated my windows and resumed again and it didnt happen. My ctrl+tabs switching were working fine withing 3 of my new cygwin windows. Then I started working on my new cygwin windows leaving my all my other git bash windows. But after some time (about 30/40 minutes) I had tried my ctrl+tab keys again and found that ctrl+tab not working again. looks like this is happening after 30/40 minutes of inactivity for other windows. PS: all my cygwin windows are in fullscreen

**Comment by mintty** [comment]
Can you please test whether it happens without fullscreen?

**Comment by ahmedmohiduet** [comment]
let me check!

**Comment by ahmedmohiduet** [comment]
Hi mintty! it looks like happening with non-fullscreen cygwin windows as well

**Comment by mintty** [comment]
I've uploaded a debug version, can you build that in cygwin (with packages gcc-core and make installed)?
Running that from a command-line, non-fullscreen and as few as possible to reproduce the issue, it will list trace output for all windows enumerated when switching to the terminal where it was started from.
If you need to start from a shortcut to reproduce the issue, add option `--trace /dev/pty0` to the invocation target, with the tty device of a terminal used for tracing (run `tty` in it to determine the actual device number to trace to).

**Comment by ahmedmohiduet** [comment]
got it

**Comment by ahmedmohiduet** [comment]
Hi mintty! I had downloaded your debug repo and have build it with `make` and run it via shortcut:
`D:\mintty\mintty\bin\cygwin64\mintty.exe --trace /dev/pty0`
I am getting error msg: "the application was unable to startt correctly (0xc000007b)":
![screenshot 2018-02-11 21 35 54](https://user-images.githubusercontent.com/3110101/36075113-136e4418-0f74-11e8-86a2-37e971f90b1c.png)
Any idea how can we get around it?

**Comment by mintty** [comment]
Does it start from a cygwin command line? If you need to run it from a shortcut, it still needs the cygwin environment. Copy it into you cygwin /bin, use a different name so you don't overwrite your installed version (minttytest.exe) and run C:\cygwin64\bin\minttytest.exe from the shortcut.

**Comment by ahmedmohiduet** [comment]
got it. ok trying

**Comment by ahmedmohiduet** [comment]
okay. its working now. I have 3 terminals open. now waiting 30/40 minutes...

**Comment by ahmedmohiduet** [comment]
Hi mintty! I have it reproduced. I have 3 windows open. first one has logs. ctrl+tabs not working on them. And I have selected 2nd window via alt+tab. and now my 1st and 2nd windows switching working via ctrl+tab. I have not selected my 3rd window. Because once we select it , it will start working again

**Comment by mintty** [comment]
I see 8 windows, 5 of which are iconized during the first two switching logs. From the third however, one more is iconized (0x1080e32). The current switching procedure skips iconized windows on purpose.

**Comment by ahmedmohiduet** [comment]
Yeah. Actually they are git bash mintty windows. But they are not working too

**Comment by mintty** [comment]
As I said, the trace tells us the windows that don't "work" are iconized (minimized to the taskbar) (which is significant information that would have helped before...).
If you confirm that, it's not a bug but rather works as expected.

**Comment by ahmedmohiduet** [comment]
ok got it. let me check

**Comment by ahmedmohiduet** [comment]
Hi mintty! Are there any implications turning it on for iconized windows as well? I'm closing it. Let me know how can I turn it on for iconized windows. I would like to be able to have my own build for this one

**Comment by mintty** [comment]
It's _not_ as easy as removing the !IsIconic condition from the respective function (I've tried), if that's solved it could e.g. be attached to Ctrl+Ctrl+TAB (meaning both Ctrl keys pressed)...
What you can do now, however, is to use the session switcher in the extended context menu (Ctrl+right-click) which allows use to select the window to switch to in a more comprehensive way than the more tentative Ctrl-TAB cycling.

**Comment by mintty** [comment]
Oh, I see a confused tag; so please do this as an alternative:
* Ctrl+right-mouse-button to open the extended context menu.
* From the "Session switcher", select the running terminal window session that you want to switch to; 
iconized windows are listed here as well and will be restored if selected.

**Comment by ahmedmohiduet** [comment]
okay.got it. haven't known about it 👍 :)

**Comment by mintty** [comment]
Released 2.9.0.
