### ISSUE TITLE
 How do I start Mintty with automatically running a code line or bash script file?

### ISSUE THREAD

**Issue by BudiKusasi** [mintty/mintty#736]
I tried to get into Mintty with intention to automatically configure path so after path is set to ready run mintty and bash, I typed

mintty -e bash -c 'PATH=/mingw64GCC71/bin:${PATH}'

not work...
Failed to run /d/msys/usr/bin/bash -c: No such file or directory

tried to move the code to a bash script SetPath.sh, in user home and typed

mintty -e bash -c '~/SetPath.sh'
(or run mintty from Windows cmd prompt: mintty -e bash -c '%homepath%\SetPath.sh')

not work too...

How can I get into Mintty with automatically setting and configuring the path

**Comment by mintty** [comment]
This is actually a shell question, not a terminal question.
The terminal runs your command until it terminates.
Your issue is that bash -c 'PATH=...' or whatever terminates after running the given command.

**Comment by mintty** [comment]
Depending on what you want to achieve, you may either:
* use `mintty -h alw ...` to leave mintty open to check the output, or
* `bash -c 'whatever; bash'` to continue the shell session interactively

**Comment by mintty** [comment]
Actually, on second glance, I overlooked this:

> not work... Failed to run /d/msys/usr/bin/bash -c: No such file or directory

which looks quite weird. However, also the background is unclear. What specifically do you mean with "not work" (where is that message seen, what about the terminal)? And what's your system environment anyway (`uname -a`)? You are not by chance trying to start an MSYS shell from Cygwin?

**Comment by BudiKusasi** [comment]
SOLVED !!!

mintty -e bash --login -c 'PATH=/mingw64GCC71/bin:${PATH}; bash -i'

THANK YOU SO MUCH FOR YOUR SINCERITY IN HELPING ME !!!
GOD BLESSES YOU.. AAMEEN !
