### ISSUE TITLE
Unexpected change of the working directory when started trhough a shortcut

### ISSUE THREAD

**Issue by peclik** [mintty/mintty#737]
2.8.3 introduced setting of working directory when started through a Windows shortcut:
> If the log file name is a relative path name, it is relative from the working directory mintty was started in. If mintty was started from a Windows shortcut (desktop/start menu) with no working directory ("Start in:") specified, mintty changes to the user's home directory first, except in WSL support mode where %LOCALAPPDATA%/Temp is used.

https://github.com/mintty/mintty/blob/725008b690ea2356544efa185552132582173125/src/winmain.c#L3241

Shortcuts are initiated not only by clicking a Desktop or a Start Menu item, they can be anywhere. Including in some %PATH% folder and then executed from command line.

When a shortcut has a blank 'Start in:' field, the program is supposed to be executed with the current working directory. In such case, mintty unexpectedly changes the working directory to $HOME.

I suggest either reverting the change or adding an option to disable this "feature".

**Comment by mintty** [comment]
Ah, agreed.
I was irritated by the effect that sometimes, in such cases, the shell starts in %SYSTEMROOT%/System32.
I may determine the effective directory and test that for the Windows dir explicitly, and only modify it in that case. Would you agree that's reasonable?

**Comment by peclik** [comment]
Well, I feel that solution would be kind of magic inside (probably worse than current solution).

I think, that by default Windows inserts directory of a program itself into the 'Start in:' field. This is also usual for shortcuts created by the installation programs. If someone changes this explicitly, he knows what he does and what he wants. And for the good user experience, the behavior shall be the same for all the applications.
There are already means to use for changing to HOME dir - command line option, shell profile script...

That's just my opinion, I don't want to offend the solution you've selected.

**Comment by mintty** [comment]
The Cygwin Terminal shortcut that Cygwin creates the Start Menu has an empty working directory. So if someone copies that for a modified target command, the .../System32 surprise is not unlikely to happen.
To start in the current directory, you could enter "." explicitly.

**Comment by mintty** [comment]
Let's go with my proposal for now, because it's not only about the shell start directory. Even if you start a login shell, the shortcut start directory would be used to locate a log file, likely raising an unexpected error. This should be avoided, so a directory within the Windows hierarchy will now be detected and redirected.

**Comment by peclik** [comment]
Thanks for the "." option.
While I still think it's unusual behavior, I can live with that. :-)

**Comment by mintty** [comment]
Released 2.8.4.
