### ISSUE TITLE
[MSYS2] Term=xterm-256color does not support backspace and command history correctly

### ISSUE THREAD

**Issue by LigH-de** [mintty/mintty#738]
mintty 2.8.3 (x86_64-pc-msys) with `Term=xterm-256color` in *.minttyrc*

When I press cursor-up to recall previous commands, the cursor does not return to the position after the prompt to delete the current content; instead, every previous command is appended to the current content of the command line being displayed.

When I type a command and press backspace to edit a typo, a forward space appears instead.

If I select the terminal mode `xterm` instead, it works as expected.

**Comment by avih** [comment]
This is likely an msys2/ncurses 6.1 issue which might require rebuilding programs which link with ncurses. See https://github.com/Alexpux/MSYS2-packages/issues/1124

**Comment by LigH-de** [comment]
Yes, it happens in MSYS2 (regularly updated by media-autobuild_suite). But according to /var/log/pacman.log, ncurses should be version 6.0.20170916-1.

**Comment by mintty** [comment]
Similar symptoms can occur as discussed in #191, #296, #355; see also https://github.com/mintty/mintty/issues/377#issuecomment-137728631. However, @avih's explanation may also be the solution.
Not a mintty issue.

**Comment by LigH-de** [comment]
Means: Waiting for MSYS2 to release updated packages?

**Comment by mintty** [comment]
No, why don't you just:
> If I select the terminal mode xterm instead, it works as expected.

**Comment by LigH-de** [comment]
The media-autobuild_suite seems to have pre-selected xterm-256color for some cmake report highlighting effects; if it runs straight, I would not even notice the cursor issue, as it works fully automated, but I also call mingw32 or mingw64 manually... well, just a minor lack of pretty colors if I go back to xterm, at least until updates are released.

**Comment by mintty** [comment]
Please report back when this is fixed in MSYS2 so the issue can be closed.

**Comment by timarandras** [comment]
I'm facing this issue also on native OpenSuse Linux, gnome-terminal, xfce-terminal. Setting:
`export $TERM=xterm` is a workaround. Waiting for update on bash, etc. that link to ncurses.

**Comment by mintty** [comment]
Thanks, in that case it's even less related to the terminal, and I'm closing the issue.

**Comment by LigH-de** [comment]
There was just an update to bash to version 4.4.019-1 in MSYS2; this fixed the shell history in xterm-265color mode.
