### ISSUE TITLE
Sixel display fails or breaks for some sixel data

### ISSUE THREAD

**Issue by mintty** [mintty/mintty#740]
It was observed (mintty/wsltty#90) that some sixel graphics cause trouble in the context of some font sizes. Their display either fails or it even crashes or locks mintty.

@saitoha, the following observations may be useful:

mintty260 (the original sixel release) and mintty261:
FontHeight 10 or 16 or 18: displays it
FontHeight 12 or 14 or 20: does not display it, does not crash

mintty262 (the revised sixel release) and current version:
FontHeight 10: displays it
FontHeight 12 or 14 or 20: does not display it, does not crash
FontHeight 16 or 18: crashes or hangs

If six-90 is output the first time, colours appear correctly. From second output onwards, colours are reduced to yellow/green. (Also if the first output did not display, when zooming between them.)

The crash/lock behaviour was introduced with [commit fe48cdc](https://github.com/mintty/mintty/commit/fe48cdc) "fixed SIXEL colour registers handling".

**Comment by mintty** [comment]
Two small sample files attached (and a bigger one that causes subsequent problems).

**Comment by mobluse** [comment]
I think the yellow and green colors can be explained by that there are default colors for \#0, \#1, \#2, but then they are redefined.

**Comment by mintty** [comment]
I'm not really familiar with the Sixel format, but shouldn't that be reset for a new image?
In xterm, colours are the same in repeated display.

**Comment by mobluse** [comment]
`mlterm` in Raspbian or Lubuntu on Raspberry Pi behaves in the same way when it comes to color as wsltty. In wsltty `printf '\ec'` resets the colors to the original, but in mlterm they don't change (you have to restart mlterm).

BTW mlterm has larger font size than 10pt, but still sixel graphics works. You cannot change font size in mlterm with a GUI, but it looks like 12pt.

**Comment by mintty** [comment]
@saitoha, do you have an opportunity to look into this issue?
I could try to detect the issue occurrence when reverting the last sixel patch (as mentioned above) step-by-step but without really knowing what I would be changing...

**Comment by mintty** [comment]
In one case, I could trace function `sixel_parser_init` not to return.

**Comment by mintty** [comment]
Released 2.8.5 with buggy patch removed.
