### ISSUE TITLE
Mintty 2.7.7 on Windows 7 stays on top with Ctrl+Tab

### ISSUE THREAD

**Issue by YodasWs** [mintty/mintty#741]
I'm using Git Bash in mintty 2.8.4 on Windows 7. The window keeps getting stuck in Always on Top mode when I hit Ctrl+Tab (and Ctrl+Shift+Tab even though you've said you fixed it in #678).

Could someone tell me how to get out of this without closing the window while we wait for a fix?

**Comment by mintty** [comment]
Cannot reproduce this in MSYS2 (which Git Bash is built on).
Please verify the version of the stuck terminal window in Options - About.
Does another window get stuck too?
Which was the last version that worked?

**Comment by YodasWs** [comment]
Okay, apparently I am on mintty 2.7.7 and the Options box says "▶ mintty 2.8.4 available ◀"&hellip; My apologies.

Do you know how to upgrade this?

**Comment by mintty** [comment]
No, I don't know how to update Git Bash. I don't know how to install additional packages (e.g. gcc and make) either. Git Bash appears to be locked up against such operations deliberately.

**Comment by YodasWs** [comment]
Thank you for your help nonetheless!
