### ISSUE TITLE
Clear selection when clipboard content updated.

### ISSUE THREAD

**Issue by AnrDaemon** [mintty/mintty#742]
This is more of a feature request, even though I could swear I once observed clipboard content replaced with mintty selection when focus passed back to it from another window.
But just to provide a better visual feedback of the system events, it would be best to clear window selection, when clipboard content is changed by another application.

P.S.
Obligatory "PuTTY does that" included.

**Comment by mintty** [comment]
Actually, xterm is the behaviour prototype of mintty, and in fact "xterm does that" too.
However, that's with the X clipboard. The Windows clipboard API does not seem to provide a mechanism to be notified when the clipboard is touched by another application. So it's probably not possible unless mintty would be polling the clipboard status.

**Comment by AnrDaemon** [comment]
http://msdn.microsoft.com/en-us/library/ms649016(v=vs.85).aspx#_win32_Adding_a_Window_to_the_Clipboard_Viewer_Chain

**Comment by mintty** [comment]
Thanks, actually, it's even easier, without setting up a viewer: https://msdn.microsoft.com/en-us/library/windows/desktop/ms649024(v=vs.85).aspx

**Comment by mintty** [comment]
Released 2.8.5.
