### ISSUE TITLE
ctrl+comma and ctrl+period key mapping is not available in newer mintty

### ISSUE THREAD

**Issue by guansong** [mintty/mintty#743]
Mintty used can do these key mapping as in xterm

                     Ctrl<Key>comma:                  string("\033[1;5l")\n\
                     Ctrl<Key>period:                 string("\033[1;5n")\n\

But it is not available recently. I noticed this in 2.8.3 git bash, later on when I upgrade my cygwin to 2.8.4

Is there an option to re-enable this?

Thanks.

**Comment by mintty** [comment]
Hmm, that feature may have got lost with the introduction of the Compose key (which is e.g. a single Ctrl followed by two other characters, like `Ctrl a e` to enter æ. I'll check.

**Comment by mintty** [comment]
No, it was 2.7.8:
* [Reverted capturing of Shift+Ctrl+0 (~#233) to enable language switching (#663).](https://github.com/mintty/mintty/commit/41489236ded1cca20fcb3334a87fd0081130f2dc)

now wininput.c line 1780.

**Comment by mintty** [comment]
Released 2.8.5.
