### ISSUE TITLE
How to set CHERE_INVOKING variable in mintty command-inline 

### ISSUE THREAD

**Issue by BudiKusasi** [mintty/mintty#744]
If one runs mintty for specified location,
mintty --dir ....
it doesn't succeed get there directly unless after he type cd - because CHERE_INVOKING is still unset
so how to set CHERE_INVOKING variable by command-inline... Thanks in advance

**Comment by mintty** [comment]
Check out on the [Tips wiki page](https://github.com/mintty/mintty/wiki/Tips#starting-in-a-particular-directory). If that doesn't help, report back and I'll try to improve the hint.

**Comment by BudiKusasi** [comment]
D:\CYGwin\bin\mintty.exe -i D:\CYGwin\Cygwin.ico --dir z:\temp /bin/env CHERE_INVOKING=1 /bin/bash -l

mine above perfectly works..
Thanks much for the useful guide.. God blesses you, ameen

**Comment by mintty** [comment]
I've changed my mind about setting CHERE_INVOKING even though it's shell-specific. But it makes sense to use an existing mechanism so that mintty can stay in the directory explicitly selected.

**Comment by mintty** [comment]
Released 2.8.5.
