### ISSUE TITLE
On Cygwin/MSYS,  what option to make conhost.exe terminated automatically, when mintty has been running  

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#746]
On Cygwin or MSYS on Windows 10,  what setting and/or option which make conhost.exe automatically get terminated when mintty has been running.
I really found it has no use.. left over of launching process... although just 3.95 - 9.75 MB
if terminal are multi then quite taking some resources.. Thanks in advance

**Comment by mintty** [comment]
Duplicate of #674. Situation unclear.

**Comment by mintty** [comment]
Closing this duplicate.
