### ISSUE TITLE
Unexpected behaviour when returning 0

### ISSUE THREAD

**Issue by vhoyer** [mintty/mintty#748]
So, when a routine returns 0 in bash, everything else that would happen halts. In Mintty only the current process halts. This may be hard to understand. And is also an egde case so, yeah, gonna give a exemple:

If you append this at the end of yout .bashrc, whenever you do a echo command: the echo halts and also the other routines (e.g.: `trap 'command' DEBUG`). In Ubuntu it happens as expected, but in mintty it echoes parts of the values being assinged with the `export` command.
```bash
func() {
    if [[ $BASH_COMMAND =~ (echo.*) ]]; then
        return 0
    fi
    #halts echo
}

trap 'func' DEBUG
```
```bash
func2(){
    export bgcolor="\[\e[48;2;38;38;38m\]" #hex:262626
    export fgcolor="\[\e[38;2;255;215;175m\]" #hex:ffd7af
    export termcolor="$fgcolor"

    export PS1="\[\e[0m\]$termcolor\u@\h:\[\e[0;38;5;2m\]\w\[\e[0;38;5;12m\]"
    export PS1=$PS1"\[\e[0m\]\n$fgcolor\@\$ $cmdCOLOR"
}
PROMPT_COMMAND=func2
```

**Comment by vhoyer** [comment]
If anyone is interested a possible workaround is the following:

```bash
func2(){
    if [[ $? == 0 ]]; then
        #check last exit code
        return 0
    fi

    export bgcolor="\[\e[48;2;38;38;38m\]" #hex:262626
    export fgcolor="\[\e[38;2;255;215;175m\]" #hex:ffd7af
    export termcolor="$fgcolor"

    export PS1="\[\e[0m\]$termcolor\u@\h:\[\e[0;38;5;2m\]\w\[\e[0;38;5;12m\]"
    export PS1=$PS1"\[\e[0m\]\n$fgcolor\@\$ $cmdCOLOR"
}
PROMPT_COMMAND=func2
```

**Comment by mintty** [comment]
I don't really get the point. Especially this does not look to be related to the terminal in any way.

**Comment by vhoyer** [comment]
Oh, sorry then. I thought it was a problem with the terminal since in ubuntu it works just fine. What do you think this has to do with then? I'm using the mintty that comes with git. Any way, don't you wanna close this? Also thanks for the attention and the quick reply.
