### ISSUE TITLE
CSI m not recognized anymore 

### ISSUE THREAD

**Issue by rovf** [mintty/mintty#750]
Not sure whether this is a bug in mintty or in git, as I have updated in Cygwin both git (to version 2.16.2) and mintty (to version 2.8.4), and found now that the (colorizing) git branch command produces a weird output:

> git branch
* ESC[32mmasterESC[m

Note the literal display of ESC .....  in the terminal. In the previous version, the ouptu would just be

* master

with the word 'master' coloured differently. Since all other coloring (Prompt, colorized output from man and grep etc.) looked fine, I first suspected that this is a bug in git. However, when redirecting the output to xxd, it looks like git is doing anything fine:
   
   git branch --color=always|xxd

shows the offending line as

     2a 201b 5b33 326d 6d61 7374 6572 1b5b 6d0a

So we have 1b5b33326d as a starting sequence for the colour, and 1b5b6d as ending sequence. I don't see why this would be wrong.

**Comment by mintty** [comment]
Must be the configuration of your pager.
`git branch` looks fine here, while `LESS= git branch` produces that effect.
`LESS=R git branch` is fine, so likely 'R' got lost from your $LESS value.
