### ISSUE TITLE
Question: Run mintty --WSL without wslbridge

### ISSUE THREAD

**Issue by Biswa96** [mintty/mintty#752]
Using mintty with wslbridge, I've seen something in Process Monitor. 

When `mintty -WSL` is used, mintty execute wslbridge.exe, then it execute bash.exe. In Linux side, wslbridge-backend executes bash and init. So there is total 3+2=5 processes are running at same time.

I've some idea to run mintty without wslbridge. Does mintty get standard in, out, error from a DLL?

**Comment by mintty** [comment]
POSIX functionality for mintty is served by cygwin1.dll. Note that there is need to bridge the different ways I/O are handled by Cygwin/WSL, thus wslbridge which accomplishes an amazing task at that. An attempt to reproduce that achievement internally means asking for trouble and I doubt it's worth the effort just to save 1 or 2 small processes.

**Comment by Biswa96** [comment]
I shall try that if you provide me some details about how mintty gets the standard input handle, output and error. You may provide any article or book.

**Comment by Biswa96** [comment]
Any help?

**Comment by mintty** [comment]
See function `child_create` in `child.c` about how mintty propagates its std file handles to the child process.

**Comment by mintty** [comment]
> get the I/O with capturing data packets from loopback interface. Is it for the pty mechanism of wslbridge?

I have no idea how this works.

**Comment by Biswa96** [comment]
I'm seeing the child.c file. You've used GetModuleHandle to load the kernel.dll. Am I right? But there is not any path mentioned so than any DLL named with kernel can be load. You should use LoadLibraryEx() function to load only the kernel.dll from system32 only.

**Comment by k-takata** [comment]
GetModuleHandle doesn't load the specified dll, just returns the handle of the dll which has been already loaded. So, using GetModuleHandle is safe.

**Comment by Biswa96** [comment]
I've facing some problem as @mintty said. But I shall try... Closing this issue temporarily...

**Comment by rprichard** [comment]
With wslbridge, the Cygwin frontend and WSL backend transfer pty I/O using loopback TCP sockets, without encryption. wslbridge makes an attempt to verify that the correct client has connected by passing a random string over the backend command-line and reading it back over the sockets.

AFAIK, a Windows process' command line is secret. They're public in WSL, but WSL instances aren't shared between users.

**Comment by Biswa96** [comment]
But with `ssh`  in cygwin I don't see the TCP packets in Wireshark.
