### ISSUE TITLE
How do I enable the "scrollback search bar" by default

### ISSUE THREAD

**Issue by ferg22** [mintty/mintty#753]
I am going to love this functionality! Especially the ability to combine its use with 'tail -f'

Is there anyway I can have it enabled by default in my ~/.minttyrc file?  Alt-F3 is a pain to remember.

**Comment by mintty** [comment]
Not now. But the feature is also in the context menu (right-click).

**Comment by mintty** [comment]
Released 2.8.5 with improved description, hope that's sufficient.
