### ISSUE TITLE
Weird behavior with Meslo fonts (inducing condensed ligatures)

### ISSUE THREAD

**Issue by avoidik** [mintty/mintty#754]
![image](https://user-images.githubusercontent.com/6435932/37660234-9849a4e0-2c5a-11e8-86ca-382a8a8d7046.png)

On the first line you can see in echo output that "f"-character somehow influences the next character after it. When I press Up arrow on keyboard (select previous command from history) same issue occurs for actual input.

mintty 2.8.4

Font MesloLGM NF from here:
https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Meslo/M/complete

**Comment by mintty** [comment]
"fl" is substituted by an fl ligature here.
For a fixed-width font, if it includes ligature replacement, the ligatures used as substitutes should not affect the total string width, like FiraCode does (see #601). Apparently this Meslo version does not respect fixed font width when handling ligatures. Please report this as a bug to the font.

**Comment by avoidik** [comment]
More interestingly that I haven't had any issues with 2.7.9 version

**Comment by mintty** [comment]
2.8.3 fixed ligature support. But the behaviour of that font is broken.

**Comment by ryanoasis** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/186 might be of relevance to you

**Comment by mintty** [comment]
Cannot reproduce with the linked font, was it updated meanwhile?
As a workaround, you could also try to set `-o FontRender=textout`.

**Comment by avoidik** [comment]
With `-o FontRender=textout` it worked as expected

**Comment by mintty** [comment]
Cannot reproduce with your config file. I doubt we're having the same font version because for me the font properties info show Leading: -3, Underline: manual.

**Comment by mintty** [comment]
I would have waited with closing this issue until I could reproduce a Meslo update that fixes this.
However, as I couldn't even reproduce the broken ligatures in the first place, can we close the issue or is anything still unclear?

**Comment by avoidik** [comment]
Yes, please close it

>

**Comment by mintty** [comment]
With the next release, it will be possible to configure using a "nerd font" or otherwise for for "Powerline" only for Private Use ranges.

**Comment by mintty** [comment]
Released 3.1.0.
