### ISSUE TITLE
Separate user commands menu

### ISSUE THREAD

**Issue by mkq** [mintty/mintty#755]
Currently the only way that the context menus (settings MenuMenu, MenuCtrlMenu, etc) can contain user commands is the "e: extended context menu" option. This contains the standard commands, so accelerator keys C, P, A and others are already "reserved".

(I know I can still assign those to user commands and press the key multiple times and then enter, but I would like to save those extra key strokes, so I am currently assigning numbers as a workaround.)

Could you please add an option to MenuMenu etc for user commands menu only? Thanks!

**Comment by mintty** [comment]
Released 2.8.5.
