### ISSUE TITLE
Add Ctrl+Tab for tmux section to Wiki

### ISSUE THREAD

**Issue by muellerj** [mintty/mintty#757]
Just underneath https://github.com/mintty/mintty/wiki/Tips#using-ctrltab-to-switch-session-in-gnu-screen, one could include a short section on how to integrate `tmux` with the mintty-keycodes for `C-Tab` and `C-S-Tab`:

## Using Ctrl+Tab to switch session in TMUX
The Ctrl+Tab and Ctrl+Shift+Tab key combinations can be used to switch panes/windows in `tmux` in a similar fashion. In order to do do, their use as shortcuts for switching mintty windows needs to be disabled on the Keys page of the options, and their keycodes mapped in `~/.tmux.conf`:

```
# Switch through windows with C-Tab
set -s user-keys[0] "\e[1;5I"
set -s user-keys[1] "\e[1;6I"
bind-key -n User0 next-window
bind-key -n User1 previous-window
```

**Comment by mintty** [comment]
Released 2.8.5.
