### ISSUE TITLE
Trailing space in theme file causes causes error message

### ISSUE THREAD

**Issue by rovf** [mintty/mintty#758]
If I have in my theme file a line, say

    HighlightForegroundColour=244,252,193

 with a trailing space (i.e. in this case, as space after the "193"), and I start mintty with this theme file (i.e. -o 'ThemeFile=....'), I get the error message

    Ignoring invalid value '244,252,193 ' for option 'HighlightForegroundColour'.

If I remove the trailing space, I don't get the error. Given that the theme file syntax is otherwise pretty tolerant when it comes to white space, I conclude that this is not the intended behaviour, but a bug.

**Comment by mintty** [comment]
Released 2.8.5.
