### ISSUE TITLE
mintheme --list: Unknown argument

### ISSUE THREAD

**Issue by b3bb** [mintty/mintty#759]
The mintheme tool does not work as described:
``` 
$ mintheme --help
Usage: mintheme [-h|-l] [theme]
...
Arguments:
  -l, --list    list available themes
```
--list argument returns "Unknown argument":
```
 $ mintheme --list
Unknown argument
```

**Comment by b3bb** [comment]
see pull request [Update mintheme for --list argument #760](https://github.com/mintty/mintty/pull/760)
and proposed change in mintheme: [Files changed](https://github.com/mintty/mintty/pull/760/files)

**Comment by mintty** [comment]
Oops, thanks.

**Comment by b3bb** [comment]
You're welcome
