### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by automatedzombies** [mintty/mintty#761]
Hi guys,

Any idea when there is going to be a new release ? 
There is a fix for conemu mouse events handling that I need badly and it should come in the next release....

This is just a question, I don't want to stress/pressure anyone.

Thanks!

**Comment by mintty** [comment]
One major and a few minor issues have recently been fixed. The same is still on the todo list.
For conemu, there's actually a workaround rather than a fix, which would be in the scope of conemu.

**Comment by valentinul** [comment]
Thank you for the ultra fast reply!
So what does this mean in terms of dates?

**Comment by mintty** [comment]
Some things are fast and some are slow. An oracle is not available.

**Comment by mintty** [comment]
Released 2.8.5.
