### ISSUE TITLE
mintheme: file as parameter

### ISSUE THREAD

**Issue by b3bb** [mintty/mintty#762]
I have implemented a proposal for loading theme from file:
[changed mintheme](https://github.com/b3bb/mintheme/blob/master/changes/mintheme.sh)

If wanted, I can open a pull request to test, discuss, ... this.

Usage & workflow are described in a extra [README](https://github.com/b3bb/mintheme/blob/master/changes/README.md). There is a section "changes" as an aid to understand the changes in code (diff does not really help).

**Comment by mintty** [comment]
Thanks, I'll integrate that enhancement, unless you prefer to place a pull request. In that case, however, please adhere to existing style consistently: no empty line after a case (`-f|--file)`), an empty line before a shell function please, consistent usage of TAB for indentation, and also no camel casing, please, like in the mintty sources.

**Comment by b3bb** [comment]
Go ahead!

**Comment by mintty** [comment]
Released 2.8.5.
