### ISSUE TITLE
Windows 10 system 64 bits install git and right run git bash here to generate a mintty. Exe. Stackdump file.

### ISSUE THREAD

**Issue by liuyi222** [mintty/mintty#763]
Exception: STATUS_ACCESS_VIOLATION at rip=00100409BA8
rax=FFFFFFFFFFFFFFFF rbx=00000000FFFFC5D0 rcx=0000000000000000
rdx=0000000000000001 rsi=0000000100468620 rdi=00000000FFFFC5CC
r8 =03FFFFFFFFFFFFFF r9 =8000000000000000 r10=0000000000000000
r11=0000000000379800 r12=0000000100468B20 r13=0000000100468608
r14=0000000000000018 r15=000000000000000E
rbp=0000000100468B20 rsp=00000000FFFFC580
program=D:\Program Files\Git\usr\bin\mintty.exe, pid 1072, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00100468B20  00100409BA8 (000FFFFC6C0, 7FFBB3252390, 7FFBB3252390, 00600000001)
000FFFFC6C0  00100437165 (0018018C93A, 000FFFFCC51, 001800576A0, 00600061410)
000FFFFCCB0  00180047C07 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045873 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045924 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
最好用中文

**Comment by mintty** [comment]
This is not really a useful bug report. At least the Git for Windows version is needed for assessment. And any specific environment conditions that you may have. Does it happen after a fresh unmodified installation of Git for Windows? Also it would help to check whether it happens also in a non-Git-Bash environment.

**Comment by liuyi222** [comment]
I reloaded the software. I also downloaded the latest. Same question，I need to work.Very urgent!

**Comment by mintty** [comment]
You did not answer my question: Which software precisely (version, download from where)?
Also, maybe you try your luck on the Git Bash issue tracker if it's so urgent...

**Comment by mintty** [comment]
I have Portable Git 2.16.2 installed with no problems.
If there was such a problem in the Git package, there had been lots of reports already, and mintty 2.8.4 would not be part of that package. There must be something weird in your environment which I cannot investigate remotely. Did you at least reboot Windows recently?

**Comment by Biswa96** [comment]
Newer Git for Windows 2.17.0 has mintty version 2.8.4.0. I've installed the portable one and no problem occurs. @liuyi222 which executable file did you execute? Is that mintty.exe or git.exe or git-bash.exe?

**Comment by mintty** [comment]
As one more diagnostic attempt, please upload your mintty config file here (or delete it and retry).

**Comment by liuyi222** [comment]
Sorry, I don't work on weekends.no timely return message
You remote my computer.Okay?

**Comment by mintty** [comment]
Please send your config file first. For remote diagnostics, we could try whether that works. Which tool would you use for it? We can try something within 4 hours from now, or 12/13 hours later.

**Comment by liuyi222** [comment]
[http]
	sslCAinfo = /ssl/certs/ca-bundle.crt
[diff "astextplain"]
	textconv = astextplain
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	required = true
	process = git-lfs filter-process
![image](https://user-images.githubusercontent.com/38338563/38843597-5d0447d6-4222-11e8-899d-a9aa2d5cb468.png)
Is this it?
In China use QQ，All right?

**Comment by k-takata** [comment]
No. The filename of the mintty config file is `.minttyrc`.
It is normally placed in `C:\Users\<username>\.minttyrc` (replace `<username>` with your actual user name) when you use Git for Windows.

**Comment by mintty** [comment]
As there is only one such report, without further evidence, and with 3rd-party packaging involved (git), so this does not seem to occur elsewhere or in a cygwin environment, I intend to close the issue.

**Comment by abhishektiwari8891** [comment]
Its still observed for me:
Exception: STATUS_ACCESS_VIOLATION at rip=7FFCACA8C20C
rax=00005B12E4473E10 rbx=0000000000000013 rcx=00000000FFE00000
rdx=0000000000004000 rsi=00000000FFFFC360 rdi=0000000100472954
r8 =00000000FFFFC201 r9 =0000000000000001 r10=0000000000000000
r11=0000000000000246 r12=0000000600044260 r13=00000000FFFFC5B0
r14=000000000000000F r15=000000010048DCA0
rbp=00000000FFFFC510 rsp=00000000FFFFC240
program=C:\Program Files\Git\usr\bin\mintty.exe, pid 10788, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC510  7FFCACA8C20C (7FFCCC67DE40, 00000000104, 00000000000, 000FFFFC000)
000FFFFC510  7FFCACA6A9CD (00100472954, 00100472954, 00000000013, 6F646E69575C3A43)
000FFFFC510  0010041AE76 (00080000000, 001004722B4, 0000000000F, 00080000000)
000FFFFC510  00100437EAF (00180190B4C, 0000000000E, 00180057A40, 0000000000E)
000FFFFCCD0  00180047F24 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180045A03 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045AB4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

**Comment by mintty** [comment]
Does a window appear before the crash? What's your Git-Bash version?
Do you have a mintty config file? Do you have a HOME environment setting on Windows level? Do you have a customized startup script (like .profile, .bashrc) in your Git-Bash home directory?

**Comment by swimfish09** [comment]
i see C:\Users\<username>\.minttyrc , i set config Rows too big

**Comment by kapsikarsuyog** [comment]
Hi, I am facing the same issue, git bash does not open. I am a new git user. It never opened on my system after 1st install. I subsequently uninstalled and installed git several times but it didn't work.
Also in C:\Users\<username>\ there in no file or folder named .minttyrc

**Comment by mintty** [comment]
What's your Windows version/build number (cmd /c ver or winver)?
There was a problem on older Windows versions which got fixed in mintty 3.1.7. This version is now available from git-bash, so an update should fix the problem.

**Comment by tecnicopa87** [comment]
Enfrento un problema similar, tengo Win8 x64, como antecedente tenía la versión desktop de github, instalé Git-2.27.0-64-bit.exe para VSCode, al principio funcionó unos días, luego ya no ejecutaba el Git en ninguna interfaz,Al reinstalar pregunta si deseo sobreescribir, le digo que sí y lo instalo con la opción de Git batch to Visual Studio Code default, al abrir mi proyecto aparece un archivo mintty.exe.stackdump en el directorio de mis archivos(como si yo lo ubiera modificado)`Exception: STATUS_ACCESS_VIOLATION at rip=7F9BC4BA694
rax=0000000000000000 rbx=0000000000000002 rcx=00000000FFFFC410
rdx=0000000000000001 rsi=00000000FFFFC500 rdi=0000000000000001
r8 =0000000000000002 r9 =0000000000000000 r10=0000000000000000
r11=00000000FFFFC440 r12=0000000080000000 r13=00000001004B24CC
r14=00000000FFFFC4C0 r15=00000001004C8780
rbp=00000000FFFFC428 rsp=00000000FFFFC3C8
program=C:\Program Files\Git\usr\bin\mintty.exe, pid 1224, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B`    nosé si pueda eliminarlo o qué hago con el archivo porque al intentar hacer un commit me muestra un conflicto con ese mintty.exe.stackdump. mi pregunta es si puedo eliminarlo? no afecta mi control de versiones?

**Comment by mintty** [comment]
Git 2.27 includes mintty 3.1.6 which has this bug on older Windows versions. Upgrade to a snapshot pre-release.

**Comment by mohdfahad12328** [comment]
Exception: STATUS_ACCESS_VIOLATION at eip=00060C8A
eax=00000000 ebx=0045028B ecx=0022C5CC edx=77D16C74 esi=004A0410 edi=80000000
ebp=0022CB48 esp=0022C614 program=D:\Program Files\Git\usr\bin\mintty.exe, pid 451, thread main
cs=001B ds=0023 es=0023 fs=003B gs=0000 ss=0023
Stack trace:
Frame     Function  Args
0022CB48  00060C8A (20041028, 20041032, 0022CD28, 6100AFA5)
0022CD28  6100AFA5 (00000000, 0022CD84, 61009DD0, 00000000)
0022CD84  610088B2 (00000000, 00000000, 00000000, 00000000)
End of stack trace


i need help , i re installed it and it doesnt works

**Comment by k-takata** [comment]
Install mintty 3.1.7 or later. If you use Git for Windows, install a snapshot pre-release.

**Comment by beckr** [comment]
I had the same issue and I installed Git-2.28.0-rc1-32-bit.exe (from https://wingit.blob.core.windows.net/files/Git-2.28.0-rc1-32-bit.exe) and it worked for me on Windows Server 2008 R2.
