### ISSUE TITLE
Error in ANSI Art

### ISSUE THREAD

**Issue by mobluse** [mintty/mintty#766]
I use mintty 2.8.4 - wsltty 1.8.4.

This has an error where the line that should be shown on top is shown at the bottom:
![pi lenovo5_ 2018-04-23 22_00_10](https://user-images.githubusercontent.com/5777329/39150552-ff1e9cb8-4742-11e8-9991-abbc1593ee74.png)  
`curl http://www.robvanderwoude.com/files/apple_ansi.txt | dos2unix | iconv -f CP437 -t UTF-8`

This is how it should look (from Cmd.exe in Microsoft Windows [Version 10.0.17128.1]):
![kommandotolken 2018-04-23 22_02_06](https://user-images.githubusercontent.com/5777329/39150563-06e80c40-4743-11e8-85d9-de9ba627b28d.png)
This was printed using:  
`chcp 437 | start /wait /b curl http://www.robvanderwoude.com/files/apple_ansi.txt`  
It looks the same in Ubuntu for WSL as in Cmd.exe, if one uses the command line for Linux.

It might be that the image from Cmd.exe is slightly wrong since the top row is black to the right of the apple, but I don't know for sure.

I use font DejaVu Sans Mono in both.

The file is from http://www.robvanderwoude.com/ansi.php

**Comment by mintty** [comment]
The test file is broken. It uses a weird mix of relative and absolute cursor positioning and even 255 cursor left movements finally, which is OK. But it displays its first line in the current line (without prior positioning) and uses absolute positioning on from the second line onwards. Therefore its output depends on the initial position. Not yet tested in Windows 10 console but try to move to the bottom before output.

**Comment by mobluse** [comment]
In WSLtty with Ubuntu 16.04 for WSL, using `pv` to slow down the output shows the blue line across the black is due to the mail text at top.
`clear; curl -s http://www.robvanderwoude.com/files/apple_ansi.txt | dos2unix | iconv -f CP437 -t UTF8 | pv -L 40 -q`

Skipping mail text makes it work:
`clear; curl -s http://www.robvanderwoude.com/files/apple_ansi.txt | dos2unix | tail -n +4 | iconv -f CP437 -t UTF8 | pv -L 40 -q`

It's still strange that Cmd.exe handles this file so that it looks better.

**Comment by mobluse** [comment]
I now understand why Cmd.exe handles this file so that it looks better: it homes the cursor when erasing the display `\033[2J`, but according to the standard one should not do this. So I close this, because this is a bug in Ubuntu for WSL when using Cmd.exe, since they say it's xterm-compatible.

**Comment by mintty** [comment]
Side note: the half-line shadows are only visible with option "Show bold as colour".
