### ISSUE TITLE
Invoking ClipX in mintty crashes ClipX

### ISSUE THREAD

**Issue by borekb** [mintty/mintty#767]
[ClipX](https://bluemars.org/clipx/) is an awesome clipboard manager for Windows, unfortunately unmaintained since 2008 but still works great in Windows 10 and I use it heavily every day. The only issue I have with it is when I try to invoke it when the focus is in some mintty window: at least in Git Bash and in WSL.

I realize this is probably pretty much an edge case for you but still, if something comes to mind, it would be awesome to see this fixed.

Maybe the problem is that ClipX is a separate, non-console window that tries to gain focus as soon as I invoke it? But in `cmd.exe`, it works fine.

**Comment by mintty** [comment]
> see this fixed

see _what_ fixed? You do not describe the symptoms. I can run clipx and mintty, copy/paste, also start clipx from mintty - nothing happens.

**Comment by borekb** [comment]
Hmm, I started observing this in `cmd.exe` as well, and in PowerShell. Not sure what that might be but it's not an mintty issue, sorry.

**Comment by borekb** [comment]
It turned out to be the x64 vs. x86 versions of ClipX – I'm on x64 Windows 10 so I installed x64 version of ClipX but now that I tried 32bit version, everything is fine.

Sorry again for creating this issue.

**Comment by mintty** [comment]
Thanks for reporting the actual cause, anyway, for the records.
