### ISSUE TITLE
Stuck in always on top mod after using Ctrl + Tab to cycle thru windows

### ISSUE THREAD

**Issue by rafareino** [mintty/mintty#769]
Somewath related to the issue #741

After using Ctrl+Tab to cycle thru windows it breaks the ability to change to other probrams windows (By Alt+Tab). The change in focus really works, but mintty window  keep stuck above other (forcing me to minimize/hide them.

Als relevant, I am using it to open a ssh session to a remote server, and have changed the transparency to high. In the screenshot this chrome window is focused but mintty is stuck above it

![000231](https://user-images.githubusercontent.com/1813322/39662831-6fdc06bc-503e-11e8-8cf2-483ccb80cc41.png)

Using version 2.8.4

**Comment by Biswa96** [comment]
Tip: Let say there are three programs are opened respectively 1. Firefox 2. Mintty (or git, cygwin etc) 3. Chrome. Press Win+1 to focus on Firefox.

**Comment by rafareino** [comment]
My guess is that this Transparency option has a lot to do with the problem, cause it is kinda rare on windows applications, probably some neat use of an obscure oprion of the 'window manager'.

I will try again without the transparency to see if I can reproduce it.

**Comment by mintty** [comment]
Cannot reproduce.
Any further special conditions?

**Comment by rafareino** [comment]
After my last restart it seems to have gone. Please close the issue.
