### ISSUE TITLE
Click on the terminal window to focus is difficult with a Wacom Tablet

### ISSUE THREAD

**Issue by ypapouin** [mintty/mintty#770]
If I need to paste a command line, I click on the terminal window to focus it with my Wacom Tablet but instead of focusing, the pointed line is selected and by design I'm losing my clipboard content.

This is due to the fact that a Wacom Tablet with a pen is working as an absolute device position instead of a mouse that is relative. That means that it is almost impossible to "click" with a pen without generating a minimal drag-delta.

A simple fix would be top increase the current min drag delta (that is 0px or 1px I believe) to a greater value. A good value could be (current mono font character width in pixel / 2).

**Comment by mintty** [comment]
The "drag delta" issue is handled since mintty 2.8.2, with later tweaks. Which version are you running?

**Comment by ypapouin** [comment]
I'm using 2.7.9 from Git for Windows install.
Happy to hear that it's already fixed, sorry for the noise.

**Comment by ypapouin** [comment]
I'm reopening since I have the same problem after updating Git for Windows to 2.17 with mintty 2.8.4

**Comment by mintty** [comment]
Actually, the drag delta that would make a difference is not measured by pixels but by character cells.
Anyway, the current repository version has some further tweaks, maybe you can compile and test it.

**Comment by mintty** [comment]
Assuming there is no problem anymore, I'll close this issue.
