### ISSUE TITLE
Text doesn't show if a program is paused (getchar, nanosleep, etc.)

### ISSUE THREAD

**Issue by shlopoto** [mintty/mintty#772]
Hello,

I am using GitBash to launch programs I am working on. I recently installed a newer version of Git (using a newer version of mintty I guess), and this behaviour appeared. Consider the following C program:

```
#include <stdio.h>
void main() {
    do {
        puts("Some text.");
    } while(getchar() != 'q');
}
```
Well, the 'Some text.' strings only appear after I finally press 'q' + Enter.
```
$ ./program.exe

q
Some text.
Some text.
$
```
In a similar way, another program displaying text every few seconds, using the nanosleep function to let some time pass, is displaying nothing until I stop the program with Ctrl+C, then all the text suddenly happens. It was not like that on the previous version of GitBash I was using. I tried to launch mintty.exe directly, with the same result.

The Git version I recently installed is 2.17.0, it is using mintty 2.8.4. Unfortunately I don't know the version I was using before, when it worked fine, so I can't give you a hint about when the new behaviour appeared.

Under Linux Mint or Windows 7 or 10's terminals, the program works as expected, with the lines being displayed before 'q' is pressed.

**Comment by mintty** [comment]
The first question here is whether you compiled the program with a cygwin-based compiler or a Windows compiler. What does `type cc` say? However, let's assume this is MSYS gcc (how did you install it in Git Bash, actually?)
Output and input are by default buffered. It is absolutely normal that getchar only delivers a character after you enter Enter. There is also no guarantee that puts flushes its output. Behaviour may vary, based on tty configuration (e.g. raw mode) and subtle implementation differences, but this is in no way related to the terminal. Thus closing.

**Comment by shlopoto** [comment]
It is compiled with MinGW's gcc. It was installed prior to GitBash, separately. I am familiar with getchar's behaviour and don't see it at fault here. The following program has the same issue and getchar isn't involved:
```
#include <time.h>
#include <stdio.h>
void main() {
	time_t when = time(0);
	struct timespec nano_time = {0, 250000000};
	while(1) {
		puts("Some text.");
		nanosleep(&nano_time, 0);
	}
}
```

I guessed the issue had to do with some text buffering, but for the text to not show at all for minutes or hours after a _puts_ command (if I don't terminate the program), that is pushing buffering a tad too far. :)

The program with _getchar_, without recompiling it, works as expected under other terminals running under Windows, that's why I was considering a problem in mintty. Out of curiosity, I tried to compile with [tcc](https://bellard.org/tcc/), with the same result. To be honest, I am baffled by your answer, it makes we wonder if I was not clear in my description. Sorry if that's the case.

**Comment by mintty** [comment]
> for the text to not show at all for minutes or hours after a puts command ..., that is pushing buffering a tad too far. :)

You may think so, and may discuss it with the inventors of Unix. Again, it has nothing to do with the terminal which is not doing the buffering.

> baffled by your answer, it makes we wonder if I was not clear in my description

My answer was trying to point out multiple possibilities of trouble in your scenario, and in fact you were not very clear, presenting just an end-user point of view. Also, since Git Bash does not provide a compiler by default, this could have been an essential information, too.

**Comment by BrianInglis** [comment]
To portably avoid these issues and immediately display output, use setvbuf(3) at the start of the program to change stdout buffering to line buffering _IOLBF or unbuffered _IONBF (immediately after open on other files such as logs), or call fflush(3) after each put call. 
Unless changed as above, put macros and functions on some systems will default to buffering output, to reduce the number of syscalls, I/Os, and overhead; other systems may default tty output to unbuffered, at the cost of per character syscall and I/O overhead.

**Comment by shlopoto** [comment]
Thanks BrianInGlis, it works with either the __IONBF_ setting or with _fflush(stdout)_ after each puts. __IOLBF_ doesn't work, I don't know why.
