### ISSUE TITLE
Support TERM_PROGRAM environment variables

### ISSUE THREAD

**Issue by silverwind** [mintty/mintty#776]
Some terminals set `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` to allow applications to detect which terminal they run in and which version it is. Would it be possible for mintty to set `TERM_PROGRAM=mintty` and maybe also `TERM_PROGRAM_VERSION=2.8.5` on all spawned shells?

**Comment by mintty** [comment]
The problem with such variables is that they are not only set in the child shells but also in any other terminal started from them. So if you run mintty and start an xterm in it, it will still have those values.
For that reason I do not think this is a good mechanism. Terminal identification is possible with escape sequences; full-screen applications like editors use them to determine terminal type and version.

**Comment by silverwind** [comment]
> The problem with such variables is that they are not only set in the child shells but also in any other terminal started from them

I think it'd be rather uncommon for someone to launch child terminals, and ideally these terminals would override the values.

> Terminal identification is possible with escape sequences; full-screen applications like editors use them to determine terminal type and version.

Care to show an example? I'm assuming it must involve `tput` or similar tools, but information on these escape sequences seems hard to find.

**Comment by mintty** [comment]
It's primary and secondary devices attributes as listed in http://invisible-island.net/xterm/ctlseqs/ctlseqs.html. (Testing them in a shell environment is a bit tricky as the sequences are not terminated with a line end.)

**Comment by mintty** [comment]
Actually, I am not aware of any terminal program that sets a generic variable TERM_PROGRAM.

**Comment by silverwind** [comment]
Let's see:

- [hyper](https://github.com/zeit/hyper/blob/9a536722f8b0a43e8f3741a033d519864f55a957/app/session.js#L35-L36)
- iterm (couldn't find a source code reference, but it does set `TERM_PROGRAM_VERSION=3.1.6beta5` and `TERM_PROGRAM=iTerm.app`)
- Apple Terminal (I think this one was the first to do so)
- [vscode integrated editor](https://github.com/Microsoft/vscode/blob/a87e82805092693d0d2534af58a1d311cf81f0c6/src/vs/workbench/parts/terminal/node/terminalEnvironment.ts#L63-L64)

And then there's a number of applications checking these variables, like [this one](https://github.com/yarnpkg/yarn/blob/bbef3ee90c3fc78dfa721bd15c674632f76ac8cc/src/cli/index.js#L89-L94) that made me aware of them. Thought I guess there are better ways to check if a terminal supports emoji.

**Comment by avih** [comment]
> Thought I guess there are better ways to check if a terminal supports emoji.

Doesn't emoji support basically come down to using a font which has them?

**Comment by silverwind** [comment]
> Doesn't emoji support basically come down to using a font which has them?

Yes that's my understanding. Browsers have a fallback mechanism that if a font does not have a certain glyph, they fall back to a font that is known to have it (depending on OS).

**Comment by mintty** [comment]
> Let's see:

OK, which variables do they set? You mention iterm, I know of mlterm which sets MLTERM (not very useful).

> Doesn't emoji support basically come down to using a font which has them?

Yes and no.
1. There are emoji sequences, which form emojis symbols from sequences of multiple characters.
2. There are nice and colourful graphical emojis which can be shown instead of plain and single-colour font-embedded emoji symbols.

Mintty supports both, see the sample screenshot on the home page.

**Comment by mintty** [comment]
Did you meanwhile succeed at requesting the terminal type and version (secondary device attributes) via escape sequences?
This can be demonstrated on the command line as follows:
* report primary device attributes: `echo -e '\e[c'`
* report secondary device attributes: `echo -e '\e[>c'`

Referring to my first comment, I'm closing the issue.

**Comment by DRSDavidSoft** [comment]
@silverwind I'm also in support of adding `TERM_PROGRAM` variable to terminal emulators because:
- [Yarn](https://yarnpkg.com/en/) and [neofetch](https://github.com/dylanaraps/neofetch) will be able to detect the terminal
- it's a quick and easy way to find the type of terminal from shell scripts

**Comment by mintty** [comment]
> it's a quick and easy way to find the type of terminal from shell scripts

But it's not safe as I had explained. What's wrong with the device attributes report? That's the well-established way to go with almost every terminal.

**Comment by DRSDavidSoft** [comment]
@mintty Is it possible for a terminal emulator to overwrite the `TERM_PROGRAM` variable thus eliminating the issue you described above?

Additionally, how can one use device attributes report to identify the terminal and determine its features, can you please specify an example?

**Comment by mintty** [comment]
I have no influence on what *other* terminals do. So inside them, the wrong TERM_PROGRAM would still appear.

For the report, you would send the escape sequence to the terminal and then read the response, in tty raw mode, with a timeout in case the used terminal does not support it. It's a bit tricky but screen-mode applications usually switch raw mode anyway.
For a command-line script, it's also a bit tricky but the attached script (renamed .txt to enable its upload) is an example. It determines and displays the terminal type.
[terminal.txt](https://github.com/mintty/mintty/files/2997714/terminal.txt)

**Comment by BrianInglis** [comment]
You need raw mode with a timeout if you don't yet know terminal type or features. 
I find read works nicely in mintty with little need for raw input: -p defines the prompt as the query escape sequence to send, -d defines the delimiter as the expected response terminator, -s suppresses echo. The following example gets the cursor position: 
    read -s -dR -p $'\E[6n' cp
    cp=${cp##*$'\E'\[}
    cc=${cp#*;}
    cr=${cp%;*}

**Comment by mintty** [comment]
Following the discussion in #881 and increased acceptance of those variables, mintty will set them too.

**Comment by mintty** [comment]
Released 3.1.5.
