### ISSUE TITLE
Option to use Ctrl+Shift+C/V for copy/paste

### ISSUE THREAD

**Issue by lolmaus** [mintty/mintty#778]
Ctrl+Shift+C/V is standard for Linux. I've got a deeply planted habit of using this keypresses.

When I use them in Git Bash, nothing happens visually. But in truth, an invisible control character is inserted which makes the command invalid. That's extremely annoying and frustrating.

Being able to just use Ctrl+Shift+C/V for copy/paste would be amazing. Please add an option for that.

**Comment by mintty** [comment]
This option is available, Ctrl+Shift+letter shortcuts in the Options dialog.
This is described in the manual. When disabled, the default is to generate Unicode control characters in the range U+0080...U+009F. This may not be too useful but it's a traditional mintty feature.

**Comment by lolmaus** [comment]
Thank you. :bow:

**Comment by longtth** [comment]
@mintty   I'm using mintty 3.5.0 (installed with Git Bash) and got the option **checked** but can't use `Ctrl Shift V` to paste content, 

How can I fix it? 

![image](https://user-images.githubusercontent.com/1010849/127900506-0df1d9c7-58e0-4971-b1b0-a2795a9db2ba.png)

**Comment by mintty** [comment]
Copy/Paste are not the functions which get mapped to Ctrl+Shift+letter by *that* option.
The copy/paste assignment is a different issue, see the manual and wiki Tips page.
I'll check whether the description needs improvement.
