### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by aschmitz13** [mintty/mintty#779]
![image](https://user-images.githubusercontent.com/22003192/41656938-8542b798-7489-11e8-8d7e-c98a94a6a9b4.png)

The feature list states that you can set a background. But i cannot find a way to do it.

**Comment by aschmitz13** [comment]
OK. I found a solution. it is not in the current release. i downloaded the source code and build it, added the background=~/filename.jpg to the ~/.minttyrc and it works with the new compiled exe.

**Comment by mintty** [comment]
Yes, the home page is a preview, sorry. The screenshots have a small popup that quote the next version...
