### ISSUE TITLE
About Virtual Tabs

### ISSUE THREAD

**Issue by angelog0** [mintty/mintty#786]
I have read that mintty has **Virtual Tabs** and that to switch one can use CTRL+mouse-R, but **HOW** can one create a new (virtual) tab? 

Meanwhile I have found [this](https://github.com/paolo-sz/fatty)...

**Comment by mintty** [comment]
It's all described in the mintty manual page. The main configuration parameter is `SessionCommands`.

**Comment by mintty** [comment]
Actually, there is issue #699 for any related dicussion; closing this one.

**Comment by mintty** [comment]
Released 3.0.3 with title-bar session switcher (Ctrl+right-click) which is the prototype of an optical tab bar.
