### ISSUE TITLE
mintty in 2.9.0 after running vim/tmux change cursor type from block to underscore

### ISSUE THREAD

**Issue by wine18** [mintty/mintty#787]
I experience this problem under cygwin and msys2. 

When I have configured CursorType=block at start, mintty has block type cursor but after running specific applications like vim or tmux the cursor change its appearance to underscore (in those application and after closing them also). Toggling of CursorType value in Options/Looks don't have any effect on this and underscore is permanently set.

I checked this also on 2.9.5 and I didn't find this problem.

**Comment by mintty** [comment]
What 2.9.5? The current mintty release is 2.9.0. Do you mean, by any chance, cygwin 2.9.5, and the problem does not occur?
As already discussed on the cygwin mailing list, this is due to a buggy terminfo entry (e.g. of screen-256color), causing some initialization code to send ESC[34h to the terminal, which is a cursor mode sequence supported newly in mintty 2.9.0. However, as it makes more trouble than it would help, I'm considering to revert this support.

**Comment by wine18** [comment]
Hi, sorry, my mistake. I was thinking about 2.8.5. In this version under cygwin and msys2 I didn't have any trouble. Upgrading it to 2.9.0 resulted in reported issue.

**Comment by jon-turney** [comment]
> As already discussed on the cygwin mailing list, this is due to a buggy terminfo entry (e.g. of screen-256color), causing some initialization code to send ESC[34h to the terminal, which is a cursor mode sequence supported newly in mintty 2.9.0

For reference, that discussion was https://cygwin.com/ml/cygwin/2018-07/msg00012.html

**Comment by wine18** [comment]
Ok. so I guess we can close this topic as not a bug.

**Comment by mintty** [comment]
It's not a mintty bug but yet an issue for mintty users; we can leave it open as long as the resolution is unclear.
I would appreciate if someone reports the terminfo issue somewhere "upstream".
Also I would appreciate a reproducible test case which I don't have yet.
And I would appreciate opinions on how to deal with it in mintty: withdraw the new codes (which aren't DEC codes but supported in latest xterm), make them optional, enable/disable by default?

**Comment by mintty** [comment]
Actually, I was confusing two sets of codes; the ones in question here are *not* supported by xterm, so I'll simply withdraw them again from mintty.

Yet I would appreciate if someone tries to clarify why they are in terminfo at all.

**Comment by mintty** [comment]
Released 2.9.1.
