### ISSUE TITLE
Wsltty and mintty windows share tab sequence

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#789]
It seems mintty shares the tab functionality with wsltty even when they're different installs and executables, which doesn't seem right to me...

![image](https://user-images.githubusercontent.com/2286713/44027925-29b1859e-9ef0-11e8-99da-5851dc7bf744.png)
The top entry is a mintty window and the bottom is a wsltty window which isn't part of my Cygwin install.
`C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`
and
`%LOCALAPPDATA%\wsltty\bin\mintty.exe --WSL= --configdir="%APPDATA%\wsltty" -~`

![image](https://user-images.githubusercontent.com/2286713/44028025-723e3316-9ef0-11e8-9a57-f4d43696a77f.png)

The terminals don't even share the same verison (mintty is 2.9.0 and wsltty is 2.8.5).

Is this intentional that all versions and types of terminal share the same tab sequence (without a modifier key)? 🤔

**Comment by mintty** [comment]
Windows for the session switcher are filtered in add_switcher (wininput.c) based on ATOM information from WINDOWINFO. This is the same for all mintty instances. WINDOWINFO does not provide Class or AppID information which could be criteria for more selective inclusion. This means, if such additional filtering should be implemented, additional interaction with the respective mintty windows would be required. Not worth the effort for me (and I'm fine with the current behaviour anyway) but patches for such an option may be considered.

**Comment by mintty** [comment]
Actually, my previous response was not quite correct. You can in fact group windows for switcher inclusion with the Class parameter (because that's included in the ATOM information).

**Comment by mintty** [comment]
... and that's actually already documented in the manual page, section Virtual Tabs.

**Comment by mintty** [comment]
Released 2.9.6.
