### ISSUE TITLE
mintheme: save in .minttyrc

### ISSUE THREAD

**Issue by st3ll1s** [mintty/mintty#794]
It would be nice if the `mintheme` tool could automatically update the `.minttyrc` file so  theme changes are persistent across restarts of mintty.

**Comment by mintty** [comment]
Please test the upload from the [utils](/mintty/utils) repository.

**Comment by mintty** [comment]
(Option name needs to be changed for the next release as two different forked versions of the script need to be consolidated.)

**Comment by st3ll1s** [comment]
From initial testing, this works great! I didn't know about the `ThemeFile` config setting. 
One small thing: Previously, I just used `mintheme solarized-light` for example, and then mintheme also searched in `~/.mintty` etc. for the theme. Is this also possible with `--save`?

**Comment by mintty** [comment]
The search and loading is just the same as with `-f`, it only saves the setting additionally.

**Comment by st3ll1s** [comment]
It would be nice though if `-f`/`--save` would also check the same directories as just using `mintheme [theme]` without any flags.

**Comment by mintty** [comment]
Uploaded a tweak (untested) to the repository; please check.

**Comment by st3ll1s** [comment]
With the changes from #798, it works perfectly. Thanks!

**Comment by mintty** [comment]
Released 2.9.1.
