### ISSUE TITLE
Selection "sticks" to the mouse when selecting unfocused window

### ISSUE THREAD

**Issue by silverwind** [mintty/mintty#795]
On current master, I observe a presumably recently regressed issue with text selection. Steps:

1. unfocus the mintty window
2. click and drag the mouse in the unfocused window to start a selecion
3. release the click
4. notice that the selection still follows the mouse while it should have stopped doing that after step 3

**Comment by mintty** [comment]
Fix uploaded.

**Comment by silverwind** [comment]
Thanks, confirming the fix.
