### ISSUE TITLE
WSL taskbar icons does not work as expected in mintty-2.9.1

### ISSUE THREAD

**Issue by angelog0** [mintty/mintty#801]
(See #784)

I have built 2.9.1 from git (last commit  78813a9). Then I have created a Desktop link called `WSL Terminal`(.lnk) and its target is:

```
 C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\utente\.minttyrc -t "WSL Terminal" --position 20,450 -o 'AppID=@' --WSL=Ubuntu -~
```

I have changed its icon to:

```
%SystemDrive%\Program_Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2018.817.0_x64__79rhkp1fndgsc/ubuntu.exe
```

When I start this link from Desktop all seems to work but mouse-Right (`M-R`) on the icon on the Task Bar (TB) already shows it is `MSYS2 Terminal` NOT `WSL Terminal` and with the MSYS2 icon NOT the above I chose from `ubuntu.exe`...

When I add it to the TB (`M-R Add`), the TB icon changes from the `ubuntu.exe` icon to `MSYS2` icon definitively!

For `WSL` I am still using the last of `2.8 series` renamed wslmintty in `/usr/bin` which works as expected from all point of view.

**Comment by Biswa96** [comment]
The executable path belongs to UWP world and that world is way beyond than msys2/cygwin. There may be some issue using that path directly. 

May I ask the Windows version of your PC to reproduce your issue? Also try to COPY that ubuntu.exe in desktop and change the shortcut path accordingly.

**Comment by mintty** [comment]
If you remove `-o AppID=@` from your invocation line (shortcut "target"), it should behave like it used to in 2.8.*. 2.9.1 only reverted a 2.9.0 change which turned out to solve some cases but cause trouble in others.

**Comment by angelog0** [comment]
> If you remove `-o AppID=@` from your invocation line (shortcut "target"), it should behave like it used to in 2.8.*. 2.9.1 only reverted a 2.9.0 change which turned out to solve some cases but cause trouble in others.

That would mean as the original link, i.e.

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\utente\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```

But DOES NOT work! It behaves exactly as in 2.9.0.

The first time I click the link, WSL starts normally and the TB contains its `ubuntu.exe` icon and mouse-R shows `WSL Terminal` (`screenshot-01.png` in the following tarball).

When with `ALT-F2` I start another instance, the result is as in `screenshot.png` and `screenshot-02.png`: another WRONG icon (MSYS2) and mouse-R on this icon shows `MSYS Terminal`

This is the tar ball: [screenshot.tar.gz](https://github.com/mintty/mintty/files/2406842/screenshot.tar.gz)


Thanks

**Comment by angelog0** [comment]
> May I ask the Windows version of your PC to reproduce your issue? Also try to COPY that ubuntu.exe in desktop and change the shortcut path accordingly.

NOTHING changes (see [this](https://github.com/mintty/mintty/issues/801#issuecomment-423655437))

**Comment by angelog0** [comment]
Just for the sake of completeness... 

I have built this new version using the same procedure MSYS2 people uses, i.e. using this [PKGBUILD](https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD) (adapting it to 2.9.1 and git source) which uses these patches:

[0002-add-msys2-launcher](https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/0002-add-msys2-launcher.patch)

[0003-fix-current-dir-inheritance-for-alt-f2-on-msys2](https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/0003-fix-current-dir-inheritance-for-alt-f2-on-msys2.patch)

I wonder if this maybe the difference... in case we need to flag this to that people.

**Comment by angelog0** [comment]
> I wonder if this maybe the difference... in case we need to flag this to that people.

NO. I jave just rebuilt without those patches and there is always the same issue...

**Comment by mintty** [comment]
I had forgotten MSYS runs a patched version. At least the 0003 patch isn't needed anymore.
Not sure about 0002. Actually, when you rebuilt "without", did you start with a fresh download or was it maybe still patched from the previous attempt? Sorry for asking; I'll try to reproduce the issue later.
Anyway, the MSYS people seem to be understanding Windows taskbar icon handling at least, which normal people don't because it's not reasonably documented anywhere... Maybe they could reveal their wisdom and perhaps provide some insights or even a patch for upstream mintty.

**Comment by angelog0** [comment]
> Not sure about 0002. Actually, when you rebuilt "without", did you start with a fresh download or was it maybe still patched from the previous attempt? 

I used the same `master.zip` (commit  78813a9), commented out the `patch` statements from [PKGBUILD](https://github.com/Alexpux/MSYS2-packages/blob/master/mintty/PKGBUILD) and removed the `.patch` files from the tree...

The first time I flagged these issue here I flagged the same to [MSYS2](https://github.com/Alexpux/MSYS2-packages/issues/1372) people but nobody took care of it...

Maybe the have a different usage and do not see the problem.

**Comment by mintty** [comment]
I cannot handle issues that are injected by additional patches.
If you encounter any such problem in a pure cygwin version, please describe and I'll take care. But this issue is likely to get closed.

**Comment by mintty** [comment]
I ignored your previous build statement, sorry. But still, you are running in a non-standard self-built environment that I cannot reproduce, so the second sentence still holds.

**Comment by angelog0** [comment]
>  But still, you are running in a non-standard self-built environment 

I don't understand what you mean with _non-standard self-built environment_...

I have built `mintty` in the same manner in which packages are built for MSYS2; then I have built `mintty' in a way which is the same as 

```
download source code
unpack
make
```

In both cases, for `mintty >=2.9.0`, I see issues which I don't see with `2.8.5` which I am still using for `WSL`... If you don't want to fix this mark it as `wontfix` and close the ticket but don't ask me to install Cygwin just to have a `standard self built environment`. After all I can use another terminal.

**Comment by mintty** [comment]
Label "wontfix" is for recognized bugs that won't be fixed. In this case I can not even reproduce the issue so far, that's not a "wontfix". It's the reason I suggested to demonstrate the issue based on cygwin, which is the native development environment for mintty. If you were eager to get this mystery resolved, you could easily install cygwin as a test case, before threatening to revoke mintty as a terminal which you are free to do anyway. This kind of hold-up is not helpful in open source projects.
After all, I have not refused to take care of this problem, it only needs to be analyzed first.

**Comment by angelog0** [comment]
> After all, I have not refused to take care of this problem, it only needs to be analyzed first.

you only made me waste time

**Comment by mintty** [comment]
And you wasted mine, presenting a problem in a way that could not be reproduced.
This is not a fruitful way to regard unresolved problems.

**Comment by mintty** [comment]
For the records:
After some experiments, it seems that Windows uses the AppID as soon as the taskbar icon is pinned to the taskbar and ignores the previously set icon then. This is insane behaviour of the Windows desktop. Maybe some Windows guru could comment on this but I don't see there is anything that mintty could do about it. Except if mintty pins itself to the taskbar explicitly (see manual page for the complicated setup that is again induced by obscure Windows paradigms) but that is not the purpose of the existing menu function to get pinned to the taskbar.

**Comment by mintty** [comment]
Mintty 2.9.1 behaves differently from 2.8.5 with respect to the AppID *only if* option `AppID=@`.
So if there is a difference, the suspicion is that this option is set either on the command line (as originally described above) or in the mintty config file. Or something completely weird happens which can well be the case because taskbar icons are a Windows desktop feature.

**Comment by mintty** [comment]
And, final note for now, if you google for such issues, a few reports about this and similar problems with other applications show up:
https://github.com/cmderdev/cmder/issues/154
https://support.mozilla.org/de/questions/1202813
https://www.sevenforums.com/general-discussion/140956-icon-changes-when-pinned-taskbar.html
https://superuser.com/questions/916413/pinning-task-bar-icon-shows-old-icon-image
http://www.tomshardware.co.uk/answers/id-2764777/pinned-icon-taskbar-change-display-custom-icon.html

This indicates other applications experience the same junk behaviour and this trouble is not specific to mintty. So redirect your harsh complaints to Microsoft; they deserve it, not this project.

**Comment by angelog0** [comment]
First of all, thanks for your time and `sorry` for my replay of few days ago.

> The misbehaviour occurs with 2.9.0 and with 2.9.1 with option `AppID=@`.
> It does not occur with 2.8.5 and with 2.9.1 without option `AppID=@`. Check your options.

I don't use that option:

```
$ cat .minttyrc
BoldAsFont=-1
ThemeFile=base16-default-mod-lighten.minttyrc
CursorType=block
Transparency=high
OpaqueWhenFocused=yes
Font=Lucida Console
FontHeight=12
Columns=112
Rows=30
X=70
Y=30

$ cat .mintty/themes/base16-default-mod-lighten.minttyrc
ForegroundColour=208,208,208
BackgroundColour=21,21,21
CursorColour=253,157,79
Black=21,21,21
BoldBlack=80,80,80
Red=172,65,66
BoldRed=194,94,94
Green=144,169,89
BoldGreen=166,187,123
Yellow=244,191,117
BoldYellow=248,213,165
Blue=106,159,181
BoldBlue=140,181,198
Magenta=170,117,159
BoldMagenta=190,149,181
Cyan=117,181,170
BoldCyan=151,199,190
White=208,208,208
BoldWhite=245,245,245
```

and, as I wrote, the link to start WSL is:

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\utente\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```

But to start MinTTY I use the package 

```
msys/msys2-launcher-git 0.3.32.56c2ba7-2 (base) [installato]
    Helper for launching MSYS2 shells
```

which was introduced and suggested a few years ago to `solve` the pinning issues!

Now I found its code on [GitHub,](https://github.com/elieux/msys2-launcher) and if I read correctly the `C` code I find:

```
"%s\\usr\\bin\\mintty.exe -i '%s' -o 'AppLaunchCmd=%s' -o 'AppID=MSYS2.Shell.%s.%d' -o 'AppName=MSYS2 %s Shell' -t 'MSYS2 %s Shell' --store-taskbar-properties -- %s %s"
```

So it seems that using `msys2-launcher` package uses the option `AppID=MSYS2.Shell.%s.%d`

At this point, may you suggest a `Target` to start MinTTY (so I can avoid the usage of `msys2-launcher`)? Notice that starting MSYS2 shell needs to set some environment variables (MSYSTEM, MSYS): it is for this reason that MSYS2 people use also `.cmd` files.

**Comment by mintty** [comment]
I am not familiar with MSYS2 building and packaging. Apparently C:\msys64\usr\bin\mintty.exe is a patched mintty, while C:\msys64\msys2.exe is an additional launcher they use for whatever reason.
In that case, actually option AppID is built into the patch, so somewhat hidden.
To use a mintty without the option, you would need to build your own and make sure you start that one.

If, on the other hand, you use the standard MSYS setup, you seem to be stuck with the AppID option, which is intended to support permanent setup of taskbar icons as managed by MSYS (there was an extensive mintty issue about that a while ago). While it may be useful for that use case, it apparently causes the opposite effect when handling "pin to taskbar" on-the-fly as you describe. My conclusion from this ambiguous picture is that the Windows implementation of the taskbar pinning feature is simply utterly broken, with no option for an application to workaround all different use cases at the same time...

**Comment by mintty** [comment]
Oh, and note that this misbehaviour can be demonstrated without involving WSL, so the test case can be simplified. On the other hand, keeping WSL in the issue seems to be the only way for now to find a place to report it to Microsoft and maybe expect an answer :/

**Comment by angelog0** [comment]
> Oh, and note that this misbehaviour can be demonstrated without involving WSL, so the test case can be simplified. On the other hand, keeping WSL in the issue seems to be the only way for now to find a place to report it to Microsoft and maybe expect an answer :/

Concord that there is something not working from the Windows side (btw I opened [this](https://github.com/Microsoft/WSL/issues/3568))

I did also this test (each time rebooting):

Removed the MSYS2 icon from the TB
Built MinTTY from the last `master.zip` without applying patches

Created a link with this target (and MSYS2 icon):

```
C:\msys64\usr\bin\mintty.exe -i /msys2.ico -t "MSYS Terminal" /usr/bin/env MSYSCON=mintty.exe MSYS=winsymlinks:nativestrict /usr/bin/bash --login
```

and another with (and ubuntu.exe icon)

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\utente\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```

Started the first link and pinned to TB
Started the second and pinned

Closing both. Restarting the first from TB and the second from TB. Both are OK each with its own icon. 

Then started another instance (ALT-F2) of the second (WSL): the new window instance has the right (ubuntu.exe) icon but on TB it is the icon of first link, MSYS2!

I think we can suspend the discussion until something new happens.

Thank you very much for your time and patience.

Ciao,
Angelo.

**Comment by mintty** [comment]
Planning to improve the situation for the next release in two ways:
* Alt+F2 in a window started from a shortcut could invoke the shortcut rather than just the binary (.exe), thus inheriting the same AppID from the shortcut as the running instance.
* Add placeholders to option AppID to be able to use it but distinguish various deployments, invocations etc as preferred (somewhat covered by value AppID=@ already but more flexible).

Not sure though whether that will really address this issue, thus not reopening.

**Comment by mintty** [comment]
Released 2.9.4 with improved taskbar icon grouping behaviour and configuration.

**Comment by angelog0** [comment]
@mintty, now 2.9.4 works as expected also for WSL! Thanks.

**Comment by angelog0** [comment]
I start WSL with a link on the TB and whose target is:

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\user\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```
and 

```
$ cat .minttyrc
BoldAsFont=-1
CursorType=block
Transparency=high
OpaqueWhenFocused=yes
Font=Lucida Console
FontHeight=12
Columns=112
Rows=30
X=70
Y=30
```
