### ISSUE TITLE
Windows ConPTY support and native Windows programs?

### ISSUE THREAD

**Issue by nojb** [mintty/mintty#804]
Would it be possible to use the recently introduced ConPTY API (https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) to improve the compatibility of `mintty` with native Windows programs (esp. interactive ones)?

**Comment by Biswa96** [comment]
Use [winpty] instead.

**Comment by Biswa96** [comment]
Use [winpty](https://github.com/rprichard/winpty) instead.

**Comment by mintty** [comment]
It's been announced for a while already but documentation is not yet available.
Anyway, this might be an enhancement for cygwin, but not for mintty, because that's the platform level where this kind of interoperability issue can be handled.

**Comment by nojb** [comment]
Thanks for the reply @mintty! I will ask in Cygwin's mailing list about it.

**Comment by Biswa96** [comment]
@nojb If you do that please share the link of that mail.

**Comment by nojb** [comment]
https://cygwin.com/ml/cygwin/2018-10/msg00021.html

**Comment by Biswa96** [comment]
@nojb You mentioned about native Windows Applications. But its not the case. No native console app use that CONPTY. Windows Console team mimics the PTY connection like in *nix systems in a whole different way.

**Comment by nojb** [comment]
Not sure I understand your objection, but if you look at the section `ConHost - Investing in yesterday for tomorrow` in the linked blog post, you will see it clearly states that this API can be used to make traditional, existing Console applications behave like typical Unix terminal applications (VT codes, etc.).

**Comment by Biswa96** [comment]
OK, I'll provide some codes for better understanding.

**Comment by Biswa96** [comment]
@nojb If you're interested in ConPty and want a in-depth view you can follow my repository [XConPty](https://github.com/Biswa96/XConPty.git).

**Comment by Biswa96** [comment]
@nojb If you're interested in ConPty and want a in-depth view you can follow my repository [XConPty](https://github.com/Biswa96/XConPty.git). That may help Cygwin developers to understand it better.

**Comment by fcharlie** [comment]
An exciting news, cygwin currently supports conpty. see commit: https://github.com/bminor/newlib/commit/169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by fcharlie** [comment]
An exciting news, cygwin currently supports conpty. see commit: https://github.com/bminor/newlib/commit/169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by mintty** [comment]
Yes, but note it's still a test release. We'll have to wait another few weeks until the official cygwin release.
And then I can close all the related issues here!

**Comment by fpqc** [comment]
@mintty Does this mean you won't need to use the bridge anymore?

**Comment by mintty** [comment]
Yes.

**Comment by fpqc** [comment]
@mintty By the way, you might find this interesting:

In the newer builds of windows, you know how you can access the linux filesystem from:
``\\wsl$\<distroname>``

well, if you set up your mintty shortcut for wsltty to start in:

``\\wsl$\<distroname>\home\<wslusername>``

you can omit the `~` parameter from wsl.exe.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/6083371/65791177-1ad4bf80-e159-11e9-9139-25e6be8ad654.png)

I just got it working with hvpty, but it works because of wsl.exe now automatically translating the ``\\wsl$\<Distroname>`` paths automatically.  This should make escaping parameters much easier and also obviate the need for a 'wsldir' or anything of that nature.

**Comment by mintty** [comment]
The `\\wsl$\` thing is interesting information, thanks, but of limited value. You wouldn't normally know the <wslusername>.

**Comment by Biswa96** [comment]
The path `\\wsl$\<Distroname>` is only valid when a WSL session is running. So, there may be some race condition between hvpty.exe execution (which executes wsl.exe) and the path translation. hvty and wslbridge2 already have a `wsldir` and `windir` option.

**Comment by Biswa96** [comment]
The path `\\wsl$\<Distroname>` is only valid when a WSL session is running. So, there may be some race condition between hvpty.exe execution (which executes wsl.exe) and the path translation. hvpty and wslbridge2 already have a `wsldir` and `windir` option.

**Comment by fpqc** [comment]
@Biswa96 nope. It's always valid.  It was in the recent video on the blog.  They actually launch an instance of wsl if you try to connect and it's not present.

**Comment by fpqc** [comment]
@mintty By the way, a consequence of \\wsl?\Distroname always being available is that you can just read /etc/passwd directly from windows to get all of that information.

**Comment by Biswa96** [comment]
May be it possible but I can't in my PC. Also the path is not available in older Windows 10 versions. I think its user who has to configure their own shortcuts. After all, hvpty & wslbridge2 do have the option to change WSL side path.

**Comment by Biswa96** [comment]
May be it possible but I can't in my PC. Also the path is not available in older Windows 10 versions. I think its user who has to configure their own shortcuts. After all, hvpty & wslbridge2 do have the option to change WSL side path from commandline.

**Comment by fpqc** [comment]
@Biswa96 Ah, ok, it does work on the most recent two fast ring builds. I don't know about slow ring.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.

**Comment by pagerc** [comment]
> The `\\wsl$\` thing is interesting information, thanks, but of limited value. You wouldn't normally know the `<wslusername>`.

Sorry for commenting on a closed issue, but thought this might have relevance to anyone reviewing this thread in the future.
It's possible to access the Windows environment variables from the path, so this is a good alternative to setting the ~ option.
\\wsl$\Ubuntu\home\%USER%

**Comment by mintty** [comment]
Fixing syntax and variable reference, that would be
`\\wsl$\Ubuntu\home\%USERNAME%`
where the actual distribution name seems to be ignored which is weird. `-~` works better.
