### ISSUE TITLE
Cannot start maximized

### ISSUE THREAD

**Issue by Bilge** [mintty/mintty#806]
Although the operating system provides a mechanism to specify the window mode when the application starts up (normal/minimized/maximized), mintty ignores this user preference and always starts in windowed (*normal*) mode.

![image](https://user-images.githubusercontent.com/470626/46529192-b35d9a00-c88d-11e8-835c-07c36075e3ad.png)

If the user wishes to start mintty maximized, this setting should be respected.

**Comment by mintty** [comment]
You can use mintty -w max (or mintty -w full) to configure maximized window.
You can also use the "Run: Maximized" shortcut option.
Both work with mintty. Whether the git-bash wrapper passes on one or the other way is out of scope here.
