### ISSUE TITLE
Too big letter spacing for BIZ-UDGothic font

### ISSUE THREAD

**Issue by nu774** [mintty/mintty#808]
Like this: https://i.imgur.com/AGjgvrW.png
BIZ-UDGothic is a Japanese font introduced in Windows 10 1809.
If I understand correctly, tmAvgCharWidth field of TEXTMETRIC structure is usually set to the width of alphanumeric characters in case of dual spaced East Asian fonts.
However, in this BIZ-UDGothic font, tmAvgCharWidth is set to a bigger value than that (maybe, actual average of all glyphs contains in this font), and mintty fails to compute appropriate cell size.

**Comment by nu774** [comment]
Well, negative ColSpacing doesn't work quite well:
https://i.imgur.com/KMblzs3.png
Some characters hear and there are cut off even with some leading space left.
Native ConsoleHost can render this font correctly:
https://i.imgur.com/dLnOAki.png

**Comment by mintty** [comment]
Can't view those screenshots. The server pops up a hint that it's going to collect data from me if I continue.
If you have a significant screenshot, why don't you upload it here?

**Comment by nu774** [comment]
Oh, sorry.
First image:
![clip001](https://user-images.githubusercontent.com/489444/46583133-bd99b700-ca8c-11e8-902f-934aafa739a8.png)
Second image (with negative ColSpacing):
![clip002](https://user-images.githubusercontent.com/489444/46583135-c7bbb580-ca8c-11e8-9888-c92415939ec6.png)
Third image (ConsoleHost):
![clip003](https://user-images.githubusercontent.com/489444/46583136-cd190000-ca8c-11e8-89b7-b6e32cb8a582.png)

**Comment by nu774** [comment]
As for BIZ-UD Gothic font not present in your system, it may be treated as Japanese language specific optional feature. Does this helps?
https://answers.microsoft.com/en-us/windows/forum/windows_10-start/some-fonts-are-missing-after-upgrade/95839dfa-0df2-4bc0-875a-fd6b57e61fe4

**Comment by nu774** [comment]
Since that page is written at 2015 for build 1607, this font cannot be listed there.
BIZ-UD gothic font can be downloaded from here: https://bizplus.morisawa.co.jp/  (written in Japanese,  registration required).
I guess it's easier to get from Microsoft in some way, it's officially provided for Japanese language at least.

**Comment by mintty** [comment]
OK, it's in the Japanese language pack.
The font reports an average width of 19, as opposed to 11 or 12 with other fonts.
I see no obvious way to determine a suitable cell width in this situation;
I do not agree that "mintty fails to compute appropriate cell size", rather the font fails to report an appropriate character width. Back to comment 1, this is a font bug.

**Comment by mintty** [comment]
By the way, notepad isn't a good example to compare with; it does not adjust its window width to the font at all. Also it seems to stretch the width of BIZ UDGothic, which is likely neither what most people appreciate. If you have a good design proposal how to deal with the situation, I'll consider it.

**Comment by nu774** [comment]
I don't understand why you are so sure that this is a "font bug".
tmAveCharWidth of GDI TEXTMETRIC structure comes from OS/2 compatibility table of TrueType fonts described here:
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#xavgcharwidth
If I understand the doc correctly, it's not a font bug. The meaning of xAvgCharWidth has changed, and the doc strongly recommends not to rely on the value for computing layout.
If you need to obtain pitch of latin alphabets to compute cell width, why don't you use GetCharWidth32() on them?

**Comment by mintty** [comment]
Well, all other fonts I checked maintain an average width that indicates cell width, but you are right, formally.
GetCharWidth32 cannot be used, also formally, because it is documented not to work for TrueType fonts, although it does in practice. It would be GetCharWidthFloatW then, to be measured for some selected character. What a crap.
Issue acknowledged, DPI dependencies checked (works fine, the determined width can be taken as a replacement for the average width).

**Comment by nu774** [comment]
Tried the latest commit just now, looks good to me.
Thanks!

**Comment by mintty** [comment]
Released 2.9.4.
