### ISSUE TITLE
Font Linking (composite fonts)

### ISSUE THREAD

**Issue by cup** [mintty/mintty#809]
here is a test using left-to-right - works with cmd.exe but not mintty:

Control arm
-----------

install:

~~~
usr/share/fonts/noto/NotoSansMyanmar-Regular.ttf
~~~

from:

~~~
noto-myanmar-fonts
~~~

Link font:

~~~sh
set 'HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink'
reg add "$1" /t REG_MULTI_SZ /v Consolas /d NotoSansMyanmar-Regular.ttf
~~~

test.txt:

~~~
U+1000 MYANMAR LETTER KA
[က]
~~~

Set font for `cmd.exe` to Consolas and test:

~~~
chcp 65001
type test.txt
~~~

Experimental arm
----------------

set font for `mintty.exe` to Consolas and test:

~~~sh
chcp.com 65001
cat test.txt
~~~

References
----------

- http://docs.microsoft.com/globalization/input/font-technology
- http://fileformat.info/info/unicode/char/1000/index.htm

**Comment by mintty** [comment]
As commented in #807, I do see the glyph in mintty.
Note, however, that Indic and other scripts have character widths that vary too much to fit into a cell-grid. They cannot be supported well by any terminal.

Now about font linking: this is not applied by mintty at all, it's a Windows feature. If it does not work in your windows version and configuration, there's nothing mintty could easily do about it.

**Comment by mintty** [comment]
You do not have configurated FontRender=textout, do you? That would likely disable font linking.

**Comment by cup** [comment]
@mintty it says here http://mintty.github.io:

> Running on Windows XP, Windows 7, Windows 10. 

so you saying "I do see the glyph in mintty" doesnt really mean anything unless
you have tested Windows 10 and Windows 7.

the issue is not specific to me because:

1. linking works in cmd.exe as i said before
2. i did my tests on a pristine virtual machine windows 7

in regard to `FontRender=textout`, i dont know that that is - if thats a default
setting for mintty - then i probably havent changed it - i can test when i get
home.

**Comment by mintty** [comment]
So your report doesn't mean much either as you didn't say which Windows version you run on :/
Let's put this aside, I am aware that font rendering works in more cases in Windows 10 than in Windows 7.
It doesn't matter anyway as it is completely out of control of mintty.
The default setting for mintty is FontRender=uniscribe which would enable font linking except for right-to-left.

**Comment by cup** [comment]
@mintty 

1. its not my job to put what version of windows im on - if i dont put a version it could be assumed im using one of the supported windows versions (which i am)

1. its your job to test all version if you purport to support all versions - especially if a user has said repeatedly which version they are using (i have)

1. its not out of control of mintty - as it works with cmd.exe, it can and should work with mintty

**Comment by mintty** [comment]
1. It's you who complained about version-specific difference without having specified your own environment (in this issue) - I was just mirroring.
2. It's every bug reporter's job to provide clear information as relevant for an issue.
3. It's not my job to do anything at all for you. Who do think you are? Do you have a paid mintty support contract?
4. I do not care about cmd.exe. If you complain about something mintty does not do which cmd.exe can do it's your job to analyse the difference.

**Comment by cup** [comment]
@mintty job is just a word - it doesnt pay or contract in this context - more
like duty or responsibility. now if you dont feel a duty to all versions listed
perhaps you should change to to Windows 10 only.

regardless of how i form my question - you cant say in good conscience that "it
works for me" unless you have properly tested all supported versions.

if cmd.exe can handle font linking, then its an error if mintty cannot do this.
you can say you dont care but it doesnt change that fact.

**Comment by mintty** [comment]
If you claim there is an error which I deny it's your responsibility to contribute evidence. This is not an error because mintty does not apply font linking at all - Windows does.
It's not your job to decide what's a fact and what's an error and it's not my job to teach you manners.

**Comment by cup** [comment]
@mintty it just as rude to masquerade something as working when its not.

its not a question that mintty has an error - its a fact

i have laid out steps of exactly how to reproduce that error

you have yet to say what version you are on - so i can only assume Windows 10

and until you or someone else tests windows 7 to contradict me - then my
position stands as fact.

mintty does apply font linking else you couldnt have made your position that it
works on (what i assume is) windows 10. currently mintty is failing with
windows 7.

**Comment by mintty** [comment]
In general, we'd better not escalate this but I cannot accept you adding insults to the issue.
It's you who started getting rude by claiming me responsible to serve your requests although this is a volunteer project.
One fact is that mintty does not actively control font linking. This is done by Windows. As Windows 10 quite naturally provides more feature support than Windows 7, the fact that something not under mintty control works in Windows 10 but not in Windows 7 is not a mintty error. If you continue to claim such nonsense, I'll check how to block you from the issue. You are failing to understand what I tried to explain. You are also failing to understand how open source projects work.
Having explained why this is not an error, I'm closing the issue.

**Comment by cup** [comment]
@mintty its too bad you have closed this valid issue

if you must block me so be it - but i will defend a valid issue as long as it
exists

i am well aware of what your responsibility is - i make thousands of
contributions a year http://github.com/cup - technically your responsibility is
nothing - only what you wish to contribute - but when you actively deceive on a
public forum that something is working when its not - then shame should be on
you

i feel likely that you havent even tested with Windows 7 - so its audacious for
you to make such claims. this is not a matter a windows 10 versus windows 7 
because cmd.exe with windows 7 support font linking - a fact that you are hard
to accept.

hopefully you will take down the brick wall of your resolve and see that this is
a valid and fixable issue for mintty.

**Comment by mintty** [comment]
You seem not to even read my comments.
I did not claim this would work on Windows 7. I just said it's not a mintty bug. And I explained why.
Shame is on those who insult open source contributors.
If you claim this is fixable for mintty, then provide a fix.

**Comment by cup** [comment]
@mintty why would i bother to pull request for a closed issue

perhaps if you reopen i can send a patch

thank you for your patience
