### ISSUE TITLE
Full and proper BiDirectional text support

### ISSUE THREAD

**Issue by XVilka** [mintty/mintty#814]
In the modern world, the support for some languages that are right-to-left and mixing them with left-to-write words and numbers is crucial for a different software. At some point, this should be supported everywhere, including the console.

I started to gather the information about BiDi support in various console terminals (and programs) in analogy with true color crusade at https://gist.github.com/XVilka/a0e49e1c65370ba11c17

**Comment by mintty** [comment]
Actually, mintty has always supported bidi already, so I'm not sure how to interpret this issue.

**Comment by mintty** [comment]
Bidi can be disabled with option `Bidi=0` or command line option `--nobidi`.

**Comment by mintty** [comment]
The next release will improve on bidi handling and mode settings.

**Comment by mintty** [comment]
Mintty 3.0.0 support paragraph-level bidi (to some extent), where a wrapped output line is considered a paragraph. It also supports ECMA-48 and other bidi controls, according to the (preliminary) recommendation https://terminal-wg.pages.freedesktop.org/bidi/.
