### ISSUE TITLE
mintty 2.9.3 stalls/crashes on output while selecting

### ISSUE THREAD

**Issue by rmzg** [mintty/mintty#816]
Version: mintty 2.9.3 (x86_64-pc-cygwin)
Windows 10

Setup:

mintty -> cygwin bash -> ssh -> linux -> tmux -> mysql CLI output

Given the above system if I rapidly click and highlight text from the mysql cli output, mintty will crash by disappearing completely from the screen.

**Comment by mintty** [comment]
I happened to face a similar effect just today; however, a reproducible and *minimal* test case is always a good idea to assess an issue. Can you reproduce without tmux/ssh, with some simpler creation of output? Can you describe the way you apply selection more precisely?

**Comment by rmzg** [comment]
Sorry, wish I had time to create a better test case.

![image](https://user-images.githubusercontent.com/1282791/48022770-a688cc00-e101-11e8-92f6-8c4d9f4ebdd5.png)

This is how the window looked when it stopped responding (windows greyed it out then popped up the "not responding" dialog.

To cause this all I did was put the mouse in the middle of the window and click and drag a bunch of times in a row.

**Comment by rmzg** [comment]
I'm fairly confident the problem is unique to tmux, I dont think I can reproduce without being attached to a tmux session.

**Comment by mintty** [comment]
This is inconsistent information. So does the window get grayed (stall) or disappear from the screen (crash)?

**Comment by rmzg** [comment]
Usually it crashes and disappears, this time it stalled out. I can't actually explain why one or the other happens.

**Comment by mintty** [comment]
Test case: `while true; do sleep 1; date; ls /etc; done` (no ssh or tmux needed). Select a few lines, release mouse, click again.
It's caused by the patches for #799 (2.9.2). Details to be analysed.

**Comment by rmzg** [comment]
Great. I downgraded to 2.9.1 via the cygwin installer, doesn't crash under your test case.

On a related note, as I'm sure you've noticed, when mintty explodes it tends to leave behind bash/ssh processes, any chance of getting those cleaned up?

**Comment by mintty** [comment]
Mintty is not supposed to "explode". This issue is a serious bug that shall be fixed soon.
If mintty is terminated regularly, it kills its child process (normally a shell).

**Comment by kgraefe** [comment]
I think I have the same issue with mintty 2.9.3 (x86_64-pc-cygwin) on Windows 10.

Thanks to tmux I can reproduce the situation: ![unbenannt](https://user-images.githubusercontent.com/3797324/48073822-d60e0600-e1df-11e8-9ee1-9275df0c7767.png)

I try to copy the snippet `time.clock() - start` while I have a `candump` running on the right pane capturing 1 packet every 1.88 seconds. When the `candump` changes while I am selecting the text (having the mouse button pressed), mintty crashes or stalls (both happened). When I select the text  within the timeframe between two packets, it works.

**Comment by mintty** [comment]
The error is an embarassing wrong calculation of the size of memory allocation for the "suspend output while selecting" buffer.
I'll fix that and make the buffer size configurable, including 0 which will disable the buffering.

**Comment by mintty** [comment]
Released 2.9.4.
