### ISSUE TITLE
copy/paste options on right click of title bar

### ISSUE THREAD

**Issue by earnie** [mintty/mintty#820]
Context: Using Cygwin's ssh to a Arch Linux VM I would like to be able to paste into a vim session and also copy and paste between separate such sessions.  The vim application takes over the mouse except for the title bar so the only right click actions for Mintty are on it.  Otherwise the right click actions are for vim; primarily a text selection.

**Comment by k-takata** [comment]
It's not a problem of mintty.
Try adding `set mouse=-a` in your `.vimrc` or use Shift+right click.

**Comment by mintty** [comment]
The scope of the "system menu" (which is also the title bar menu) is different from the context menu. Its functions are window-related, not terminal-related. Also, as k-takata noted, you can reach the context menu with Shift.
On the other hand, the context menu is already configurable, in modules, so two enhancements could be designed:
* Make system menu configurable like the context menu.
* Make both menus (or rather all menus, as distinguished by Ctrl/Shift modifiers) configurable in finer-grained terms, using the functions available for shortcut configuration (option KeyFunctions).

This is a mid-term design idea; comments appreciated.

**Comment by earnie** [comment]
On 11/13/2018 4:39 PM, K.Takata wrote:
> It's not a problem of mintty.
> Try adding |set mouse=-a| in your |.vimrc| or use Shift+right click.

$ cat ~/.vimrc
set mouse=-a

$ vim ~/.vimrc
Error detected while processing /home/USER/.vimrc:
line    1:
E539: Illegal character <->: mouse=-a
Press ENTER or type command to continue


However, `set mouse=` does do what you state but I didn't want to give 
up having vim control the mouse but Shift+right click might work for 
paste and perhaps I can do an session based `set mouse` to get the most 
of it.

-- 
Earnie

**Comment by earnie** [comment]
On 11/13/2018 5:35 PM, mintty wrote:
> The scope of the "system menu" (which is also the title bar menu) is 
> different from the context menu. Its functions are window-related, not 
> terminal-related. Also, as k-takata noted, you can reach the context 
> menu with Shift.
> On the other hand, the context menu is already configurable, in modules, 
> so two enhancements could be designed:
> 
>   * Make system menu configurable like the context menu.

This I like.

>   * Make both menus (or rather all menus, as distinguished by Ctrl/Shift
>     modifiers) configurable in finer-grained terms, using the functions
>     available for shortcut configuration (option KeyFunctions).
> 

I can see the benefits of this.

-- 
Earnie

**Comment by mintty** [comment]
Released 2.9.6.
