### ISSUE TITLE
Wrong DPI scale of dialog and popup windows from v2.9.4

### ISSUE THREAD

**Issue by enzy** [mintty/mintty#824]
After upgrade from 2.9.3 to 2.9.4 the Settings windows and Mouse popup window started to appear in the wrong DPI scale. The previous version was okay.

I have a multi-monitor setup, main 4K display at 150% UI scale, two 1080p displays at 100%. The scale is correct for the main monitor but too big for the others.

Correct state on the 150% main monitor:

![image](https://user-images.githubusercontent.com/809888/49021168-51852680-f192-11e8-8cec-8bb6d44ab53f.png)

Incorrect state on the 100% monitors:

![image](https://user-images.githubusercontent.com/809888/49021200-63ff6000-f192-11e8-8455-93acc6c7f37e.png)

On Windows 10 Pro 1809 (build 18282)

**Comment by mintty** [comment]
Please try setting `HandleDPI=2`.

**Comment by enzy** [comment]
Great, this settings has fixed the behavior. Thank you :)

**Comment by mintty** [comment]
Released 2.9.5.
