### ISSUE TITLE
'Copy as rich text' disabled, overridden by Copy as HTML

### ISSUE THREAD

**Issue by ScottRochford** [mintty/mintty#825]
I updated to mintty 2.9.4 today and immediately noticed that text I copied and pasted into emails, etc. contained colours and formatting.

I have the 'Copy as rich text' option turned off, so that shouldn't happen?

I notice https://github.com/mintty/mintty/issues/811 was implemented recently, perhaps this somehow broke the behaviour?

**Comment by mintty** [comment]
Sure, Copy as HTML will be optional with the next release. Still struggling with design issues.

**Comment by stavros7167** [comment]
Is there any way to bypass this while waiting for the next release? This is a serious headache.

**Comment by Biswa96** [comment]
@stavros7167 Download build tools in cygwin and compile the mintty.

**Comment by mintty** [comment]
Or revert to the previous release for now. Quite easy.
But relief is on its way, only taking a few days, I guess.

**Comment by mintty** [comment]
Released 2.9.5.

**Comment by stavros7167** [comment]
wonderful, thanks!
