### ISSUE TITLE
mintty + vim + mouse=a + split window resize does not work

### ISSUE THREAD

**Issue by anishsane** [mintty/mintty#827]
I use mintty to connect to my linux system over ssh. And there I use vim as editor.
I have enabled mouse in vim and I use it (among other uses) to resize the split windows in vim.
(The process to resize is to click on the split boundary and drag that boundary.)

When I am using mintty, this process causes visual selection instead of window resize.
In issue #199, it was claimed that resizing split windows works. However, it does not appear to. (Let me know if I am missing anything.)

Isolation:
1. This issue is not seen on gnome-terminal or putty.
On gnome-terminal or putty, this correctly resizes the window. Only the text selection leads to visual selection there. This is the expected behavior.
2. This issue is also seen with local vim from cygwin, i.e. without ssh.

mintty version: 2.9.4, x86_x4-pc-cygwin.
OS: Win10
Mouse: Laptop's trackpad, Logitech USB mouse.

**Comment by mintty** [comment]
I vaguely remember this was discussed before, but I didn't find it as an issue; maybe on the cygwin mailing list. I assume other application-specific mouse operations do work? Does vim provide separate configuration options for different mouse functions? When you compare vs. other terminals, do you use the same instance and configuration of vim?
Please provide a configuration of vim that enables me to reproduce the issue (not a vim user).

**Comment by mintty** [comment]
> I vaguely remember this was discussed before...

https://sourceware.org/ml/cygwin/2015-07/msg00203.html

It used to be a vim bug, I had assumed they fixed it meanwhile. Which vim version do you use?

**Comment by mintty** [comment]
I've verified that the behaviour can still be fixed if mintty pretends to be version 1 rather than 2.
This is definitely a vim bug, please report it there.

**Comment by anishsane** [comment]
> I assume other application-specific mouse operations do work?

Yes, the visual selection, selecting the split window, selecting the tab etc using mouse work in vim.

> Please provide a configuration of vim that enables me to reproduce the issue (not a vim user).

No special configuration (.vimrc) required.
1. Just launch vim (local cygwin or via ssh). Even `vim -u NONE` (it does not load any .rc file) should do.
2. run `:set mouse=a`
3. run `:vsplit` or `:split`
4. Add some random text in vim if required.
5. Try to resize the split windows by clicking the border between the split windows and dragging that border.
6. Instead of resizing the windows, it visually selects the text added.

**Comment by avih** [comment]
> Just launch vim (local cygwin or via ssh).  ...

I see the same behavior without mintty (e.g. `vim`` in `tmux` running on `st` terminal), i.e. dragging the splitter selects the splitter text.

Try adding `set ttymouse=xterm2` to your `.vimrc`.

After that, dragging the splitter works for me.

**Comment by k-takata** [comment]
`set ttymouse=sgr` might be better.

**Comment by anishsane** [comment]
Thanks a lot!
`ttymouse` settings seem to work.

And to add from the isolation I provided: `vim` on `gnome-terminal` and `putty` set it to `sgr` and `xterm2` respectively. `mintty` was setting it to `xterm`.

**Comment by k-takata** [comment]
Vim sends `ESC[>c` to get the xterm version. If the xterm version is reported to be 95 to 276, `ttymouse` will be set to `xterm2`. If it is reported to be 277 or higher, `ttymouse` will be set to `sgr`.
So, if mintty pretends to be xterm version 277 or higher, we would not need to set `ttymouse` manually.

**Comment by k-takata** [comment]
Sorry. mintty sends the version like `20904` (2.9.4), however, vim ignores such large version numbers (over 20000). That's why `ttymouse` is set to `xterm` on mintty.

**Comment by mintty** [comment]
Thanks for the configuration information, I'll add that to the mintty wiki.
@k-takata, could you identify where in the vim code this is determined?
Could someone submit a vim issue, please?

**Comment by k-takata** [comment]
Here is the part that vim ignores very large version number.
https://github.com/vim/vim/blob/97195685334c800c5ad1328d957d1bf21f5fa1fa/src/term.c#L4689-L4694

And here is the part that vim determines "sgr" or "xterm2" support.
https://github.com/vim/vim/blob/97195685334c800c5ad1328d957d1bf21f5fa1fa/src/term.c#L4748-L4764

**Comment by mintty** [comment]
2 questions:
Would ttymouse=xterm2 be mouse mode 1002, 1003 or 1005? And where is this documented for vim?
Reportedly, ttymouse=sgr does not work in tmux. So it should be set also dependent on $TERM. How could that be done in .vimrc?

**Comment by k-takata** [comment]
Hmm, I can confirm that `set ttymouse=sgr` works in tmux in mintty.
No need to set ttymouse depends on $TERM.

**Comment by k-takata** [comment]
For the help of `ttymouse`, see this: http://vimhelp.appspot.com/options.txt.html#%27ttymouse%27
(Or type `:help 'ttymouse'` on vim.)

**Comment by mintty** [comment]
Thanks; the doc says about option "sgr":
This option is backward compatible with "xterm2" because it can also decode "xterm2" style mouse codes.
So in fact sgr is sufficient, unless (see your second source link above) that option is not compiled in. Which leads to this which I found somewhere:
	if has("mouse_sgr")
	    set ttymouse=sgr
	else
	    set ttymouse=xterm2
	end
Unless, again, the user runs some other legacy terminal as listed in the vim doc. So the better solution is to fix automatic setting in vim. I'd still appreciate if someone submits an issue there...

**Comment by mintty** [comment]
Released 2.9.5.

**Comment by k-takata** [comment]
> I'd still appreciate if someone submits an issue there...

Mintty returns `ESC[>77;20904;0c` as a response of `ESC[>c`. What does `77` mean?
I want to know whether Vim can use `77` to detect mintty.

**Comment by mintty** [comment]
77 is ASCII 'M' for mintty, following the pattern of some other terminals:
82 'R' rxvt
83 'S' screen
84 'T' tmux
85 'U' urxvt

**Comment by k-takata** [comment]
I created a PR: vim/vim#3667.

**Comment by k-takata** [comment]
Fixed by Vim 8.1.0566.

**Comment by mintty** [comment]
Thanks. Noted in wiki.

**Comment by mintty** [comment]
> Unknown option: ttymouse=xterm2

What about ttymouse=sgr then?
Otherwise report this to nvim please.
