### ISSUE TITLE
StrokeIt Close (Mouse Gesture Programme) command not closing Window

### ISSUE THREAD

**Issue by ElvenSpellmaker** [mintty/mintty#833]
Hey,

This is a weird one as it used to work fine and I'm not sure if a changed setting, or something else in mintty is causing this.
Before I explain, if it's any help I use mintty 2.9.5, and on wsltty I am on 2.8.5 and it works in wsltty but not mintty, so it's been introduced since then.

I use a Mouse Gesture programme called StrokeIt and I have a gesture for closing a window:
![image](https://user-images.githubusercontent.com/2286713/49741315-0ee14500-fc8e-11e8-8151-8dcea52885ab.png)

As far as I know it just sends an Alt+F4 keyboard response to the Window, but I'm not so sure as Alt+F4 works fine (do you have special handling of the real Alt+F4 over virtualised or something, I admit I'm not sure if there's a difference 😅).

It used to work fine, but recently it's just been displaying a letter `S` in the terminal and not closing the window. This seems to work with almost every other programme still.

**Comment by mintty** [comment]
So how does this tool work? I've installed it but don't see how to add and apply a gesture.
If I cannot reproduce, I'll have to ask you to enable some debugging in mintty...

**Comment by ElvenSpellmaker** [comment]
The close gesture I believe is one that comes with it, to use it you draw with the right mouse button held.

In this case a `C` shape and release the right mouse button.

If you'd like me to enable some debugging I can have a look, thanks.

**Comment by mintty** [comment]
OK, reproduced, since mintty 2.9.1.

**Comment by mintty** [comment]
As a workaround, you can set OldAltGrDetection=true.
AltGr detection was changed in 2.9.1 for the sake of the buggy Windows on-screen keyboard.

**Comment by mintty** [comment]
StrokeIt tries to close a window by sending Alt+F4 key event messages.
So this would not work even before mintty 2.9.1 if you disable Alt+Fn shorcuts.
Unlike keyboard Alt+F4, the StrokeIt events come without scan codes, so they can be distinguished.
However, any tweak may have side-effects with other scenarios, so this will need to be carefully considered and tested...

**Comment by mintty** [comment]
The StrokeIt sequence has one other deviation from keyboard Alt+F4 which is the actual culprit not to be recognized at all: it sends Right-Alt rather than Left-Alt. Please report that as a bug to StrokeIt.

**Comment by mintty** [comment]
Uploaded a workaround.
Is there actually a similar problem with AutoHotkey?

**Comment by mintty** [comment]
Forgot to explain the letter 'S': when Alt+F4 is not interpreted as a shortcut, it is handled as normal input and the respective escape sequence is generated which is ^[[1;3S of which only the 'S' appears in a shell command line because it starts with an escape.

**Comment by ElvenSpellmaker** [comment]
Oh thanks for the information, that's really interesting to know, I did wonder why it was an `S` haha.

**Comment by mintty** [comment]
Released 2.9.6.

**Comment by mintty** [comment]
This workaround spoils proper AltGr handling for AutoHotKey (#932).
A temporary fix for the latter was uploaded. To be checked whether the fix for StrokeIt is now broken.

**Comment by ElvenSpellmaker** [comment]
I'll have a look

**Comment by ElvenSpellmaker** [comment]
I now get the problem back again, it displays an `S`

**Comment by mintty** [comment]
OK, so the fix needs to be more hacky...
Uploaded an attempt. Thanks for testing, can you test again please?

**Comment by ElvenSpellmaker** [comment]
I'll have a look when I get to work, thanks!

**Comment by ElvenSpellmaker** [comment]
As a side point, do you know why I get `Ignoring invalid value 'yes' for option 'HandleDPI'.` when I run mintty?

**Comment by mintty** [comment]
Thanks for testing.

HandleDPI values should be integeres (see manual). Default 2 should normally be good.

**Comment by ElvenSpellmaker** [comment]
Ahh I'll remove the value then, it seems looking in the changelog it used to be boolean, but it's changed recently.
