### ISSUE TITLE
use mintty shortcut to launch cygwin/wsl

### ISSUE THREAD

**Issue by silaoA** [mintty/mintty#839]
I'm using windows 10 1709 and cygwin, my cygwin installation directory is D:\Cygwin64，there's an ico file named Cygwin.ico. mintty-2.9.5.exe is in D:\Cygwin64\bin。
I have created a shortcut for mintty，which is named "MinttyCygwin.lnk"，its "**target**" is "D:\Cygwin64\bin\mintty-2.9.5.exe -i /Cygwin.ico -e /bin/bash --login -i" and "**start directory**" is empty.

case1.  I put it on desktop，double click "MinttyCygwin.lnk" and it runs correctly, while I expect otherwise. Under this case, how mintty knows the "rootfs"(I mean "D:\Cygwin64") and therefore locates ico file and bash?

case2.  I put "MinttyCygwin.lnk"  under D:\Cygwin64，double click "MinttyCygwin.lnk" and it behaves differently，shell complains "/usr/bin/tr: redundant parameters e" when loading my .bashrc, but it never happens under case 1. So that's why?

I want to make mintty independent of cygwin，and launch cygwin or wsl or something else just at will through shortcut, so I copy mintty-2.9.5.exe、cygwin-console-helper.exe、cygwin1.dll from D:\Cygwin64\bin to somewhere called "xxxxx". 

case3. I have created a shortcut named "MinttyCygwin2.lnk", its "**target**" is "xxxxx\mintty-2.9.5.exe -e /bin/bash --login -i" and "**start directory**" is "xxxxx"， I put it on desktop，double click "MinttyCygwin2.lnk" but it complains "Failed to run /bin/bash: no such file or directory", I realized that I have to specify the "rootfs"(I mean "D:\Cygwin64") or full path of bash. but why this is different from case 1?

case4. as in case3, I changed property of "MinttyCygwin2.lnk",now  its "**target**" is "xxxxx\mintty-2.9.5.exe -e ./bin/bash --login -i" and "**start directory**" is "D:\Cygwin64"，I double click "MinttyCygwin2.lnk" and bash runs, but bash missed loading /etc/profile and my .bashrc , therefore I faced a black terminal without prompt and unrecognizing any command. that's why?

many thanks!

**Comment by silaoA** [comment]
@mintty that means mintty can't act as a general terminal emulator for launching Cygwin/WSL ？

**Comment by mintty** [comment]
You can run WSL in mintty, and there is the standalone package [wsltty](https://github.com/mintty/wsltty) with installer. Maybe you hadn't tried that yet. Not sure what you mean with "general".
