### ISSUE TITLE
Why does Locale=en_US mess up Emoji?

### ISSUE THREAD

**Issue by jedmao** [mintty/mintty#842]
## Default Locale
![image](https://user-images.githubusercontent.com/1058243/51728587-7da81100-2036-11e9-96fb-212d68e7280a.png)

## Locale=en_US
![image](https://user-images.githubusercontent.com/1058243/51728274-4a18b700-2035-11e9-82cd-8461999d0efc.png)

### Configuration
```ini
ThemeFile=dracula
Transparency=low
OpaqueWhenFocused=yes
CursorType=block
CursorBlink=yes
Font=Fira Code Medium
FontHeight=34
FontWeight=500
FontSmoothing=full
AllowBlinking=no
CtrlShiftShortcuts=yes
Columns=71
Rows=21
Scrollbar=None
PgUpDnScroll=yes
Language=en_US
#Locale=en_US
Window=full
Charwidth=unicode
Emojis=emojione
EmojiPlacement=middle
```

**Comment by Biswa96** [comment]
Please provide some information. Which OS? Which program did you use with mintty? Is there any theme, font or specific settings you applied? etc. etc.

**Comment by jedmao** [comment]
Windows 10 / MINGW64 / xterm. This Bash shell came with [git](https://git-scm.com/) and I launch it directly from [GitHub Desktop](https://desktop.github.com/).

The program I'm running above is [`emoj`](https://www.npmjs.com/package/emoj).

The theme and fonts are defined in my config, along with all the specific settings I applied, which I included in the OP. But I already dissected that config and revealed that it was the `Locale=en_US` that was specifically messing up the [EmojiOne](https://www.emojione.com/) emoji.

**Comment by mintty** [comment]
Because Emojis cannot be encoded in non-Unicode locales.
Try `en_US.UTF-8`.

**Comment by jedmao** [comment]
Totally works! Thanks @mintty!
