### ISSUE TITLE
Thin/no border option broken in latest (2.9.6)

### ISSUE THREAD

**Issue by brianwhu** [mintty/mintty#843]
Mintty simply won't show up if -B frame or -B void is given on the command line.

**Comment by mintty** [comment]
It seems this happened only in Windows 7, not in Windows 10; the window is getting a WM_SETFOCUS message quite early, when not everything is initialized yet, so the implementation of the new display acceleration feature failed. Fixed now.

**Comment by avih** [comment]
> It seems this happened only in Windows 7

Not only. Also happened with 8.1 .

> Fixed now.

Confirmed in windows 8.1 both -B void/frame now work where previously no window showed up.

**Comment by mintty** [comment]
> Not only. Also happened with 8.1 .

Well, I meant before Windows 10. Which is 7 for me :)

**Comment by DArcMattr** [comment]
I'm on Windows 10. I can confirm use of the command line switch results in a non-starter, for either "void" or "frame" options.

**Comment by mintty** [comment]
As notified above, this issue is fixed already, for the next release.

**Comment by brianwhu** [comment]
Thank you!

**Comment by mintty** [comment]
Released 2.9.7.
