### ISSUE TITLE
How to run WTF (GO) in mintty?

### ISSUE THREAD

**Issue by E3V3A** [mintty/mintty#846]
This is not really a Mintty issue, but a usage question.

There's a pretty cool project called [WTF](https://github.com/wtfutil/wtf/), based on GO.

![wtf_2019-02-02_03-38-36](https://user-images.githubusercontent.com/194392/52158072-7c0cc780-268c-11e9-979a-1e2a981d93bc.png)

I've managed to install GO (MSI), and have it run in Mintty, I've also managed to compile and run WTF in any Windows native console (CMD, PowerShell) as [described here](https://github.com/wtfutil/wtf/issues/350). However, trying to run this from Mintty fails with: `Error: character set not supported`. I've played around with all sort of Terminal settings to little avail. 

Looking for ideas how to get this working. Someone, did get this to [work in Zsh](https://user-images.githubusercontent.com/1605754/52144682-a3c84500-2624-11e9-89fa-104591262bc6.png). But I'm using Bash.
 
Any ideas how to get this setup properly in *Mintty + Bash*?
(What kind of info can I provide to debug?)

**Comment by avih** [comment]
I'm guessing the executable is intended to use a windows console. To run in inside mintty (which is not a windows console), you need to run it using `winpty`. If you use msys2, run `pacman -S winpty` and then `winpty path/to/wtf.exe`. If you use cygwin then you'll have to build winpty yourself. Git for windows comes with winpty built in already.

**Comment by E3V3A** [comment]
Yes, I managed to get rid of the `Error: character set not supported` and replace it with [another error](): `No screen ...<somethig>`.

BUT then

Yes, I got it to run via WinPty as described in the link above. :+1: 

```bash
#--------------------------------------
# Run with WinPty
#--------------------------------------
#export TERM="xterm"
#export GOPATH="C:\Users\XXX\go"
export PATH=${PATH}:${GOPATH}/bin
cd ${GOPATH}/bin
winpty.exe -- wtf.exe
```

**Comment by E3V3A** [comment]
True, but there are 89 comments there and mostly outdated from several years ago.

**Comment by avih** [comment]
But it's not outdated. `winpty` was the solution then, and it still is now.

**Comment by E3V3A** [comment]
Well, sure, but at the end of the day, all WTF does is to display a bunch of (mostly ASCII) characters in the terminal. No graphics, so since Mintty is fully capable to display just about anything (SIXEL, GNUPLOT etc.). So except for the funny way the devs of the tcell lib used by WTF, there is not really any good reason it shouldn't work without WinPty.

**Comment by avih** [comment]
> Well, sure, but at the end of the day, all WTF does is to display a bunch of (mostly ASCII) characters in the terminal

Except that it does it using windows console APIs and not via printing escape sequences, hence mintty cannot support it natively.

**Comment by yumetodo** [comment]
Is there possibility to use [ConPTY API](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/)?

**Comment by mintty** [comment]
It might be an improvement for winpty to use ConPTY. Maybe ConPTY could even be integrated in Cygwin, to be involved automatically whenever a non-Cygwin program is started. This would be an improvement for all kinds of pty-based terminals alike (e.g. xterm) and is out of scope of a specific terminal.

**Comment by E3V3A** [comment]
Yeah, I was looking into trying to get this to compile in Cygwin, but I gave up due to shitty documentation and support after [my issue was closed](https://github.com/Biswa96/XConPty/issues/1).

**Comment by Biswa96** [comment]
@E3V3A Sir, be polite in public discussion, please. That issue isn't mine. Cygwin don't use the updated version of mingw-w64 toolchain. See the version list here https://mingw-w64.org/doku.php/download. Only msys2 has the latest one.

And my XConPty project is not an implementation of cygwin. I just showed how pseudo console work internally.

**Comment by mintty** [comment]
I was assuming he referred to the Windows documentation of ConPTY, which is virtually non-existant.

**Comment by Biswa96** [comment]
[wslbridge2/rawpty](https://github.com/Biswa96/wslbridge2/tree/master/rawpty) (uses ConPTY tech) can be used to run Win32 commandline programs in mintty.

**Comment by E3V3A** [comment]
@Biswa96 
How do we use it?

**Comment by Biswa96** [comment]
@E3V3A First, remember the program is not ready for "production". Download the wslbridge2.zip file from release page. Extract rawpty.exe. Run any command in mintty with just prepending rawpty.exe. For example, `rawpty.exe cmd.exe`.

**Comment by Biswa96** [comment]
Cygwin now has Windows ConPTY support. See [this commit][1]. Released in Cygwin 3.1.0-0.3 test build.

[1]: https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=169d65a5774acc76ce3f3feeedcbae7405aa9b57

**Comment by E3V3A** [comment]
@Biswa96
> rawpty.exe cmd.exe

Didn't do anything for me. 
Do we also need the other files?

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support. Please recheck.
