### ISSUE TITLE
Tried assign Control-V to something but failed

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#848]
Tried assign control-v such

`bind -x '"\C-v": paste-from-clipboard '`
(or the simple seq put in the .inputrc file)
not work and neither:

`bind -x '"\C-c": clear '`

Why does not work and how to resolve it ?
At least give the helpful, correct reference, hint and guidance

**Comment by mintty** [comment]
This is not a terminal issue.
In the case of .inputrc, find some information in `man bash`.
For the `bind` assignments, you didn't even say where you have them or which tool they apply to.
I assume vim or emacs. Note that they probably assume a clipboard to be reachable via X-Windows, and the paste-from-clipboard function is likely intended for the GUI version of an editor. This might possibly work in the command-line version but certainly not if you're not even running an X server as you normally do when using mintty in cygwin.
