### ISSUE TITLE
Copy and Paste from Vim

### ISSUE THREAD

**Issue by haruo-wakakusa** [mintty/mintty#849]
I'm using Windows 10(64bit), MSYS2(msys2-x86_64-20180531.exe).

I want to copy and paste texts between mintty and another mintty window or Windows applications. Mintty maybe does not use Windows Clipboard. Please change it into being able to use Windows Clipboard.

**Comment by haruo-wakakusa** [comment]
Sorry, I find the way.

AllowSetSelection=yes

But, I drag and drop from Vim, I cannot copy it. I can copy it from Bash.

**Comment by k-takata** [comment]
It's not a problem of mintty.
Try adding `set mouse-=a` in your `.vimrc` or use Shift+D&D.

**Comment by haruo-wakakusa** [comment]
Thank you, k-takata!! I did it!!
