### ISSUE TITLE
Ability to customize shortcuts

### ISSUE THREAD

**Issue by Trismegistos84** [mintty/mintty#851]
Many people like their own shortcuts additionally some of the default ones are not very convenient e.g. shift+insert. Ability to set own shortcuts would greatly enhance mintty usage. Moreover it is common functionality of most applications.

**Comment by mintty** [comment]
This is available already. See option `KeyFunctions`.

**Comment by Trismegistos84** [comment]
I have opened Options->Key and can not see this option. I have also searched in other Options submenu and didn't find it. I'm using latest mintty from cygwin.

**Comment by mintty** [comment]
It's not in the Options dialog. You'll have to edit the config file manually.

**Comment by Trismegistos84** [comment]
I have searched these locations: /etc/minttyrc, $APPDATA/mintty/config, ~/.config/mintty/config, ~/.minttyrc and didn't find any exemplary config file there. I also tried to grep internet, mintty wiki and manual page but with no result. Can you provide such file?

**Comment by mintty** [comment]
Once you click Save from the Options dialog, a config file should be written. The default location would be ~/.minttyrc unless you were running wsltty, in which case please also look at "$LOCALAPPDATA/wsltty/config".
An example entry could be:
`KeyFunctions=S+Insert:"insert";`

**Comment by mintty** [comment]
Note: `Insert` refers to the Insert key on the small "editing keypad", not the one below the numeric keypad.

**Comment by Trismegistos84** [comment]
So I wanted to set control+shift+v for insert and control+shift+c for copy. I tried following combinations:

    KeyFunctions=C+S+v:"insert"
    KeyFunctions=C+S+c:"copy"
    KeyFunctions=C+V:"insert"
    KeyFunctions=C+S+V:"insert"

but they didn't work. Is it possible to set such shortcuts?

**Comment by mintty** [comment]
1. You need to squeeze all assignments into one config parameter, but you can wrap it over multiple lines.
2. For letter combinations, only the combined Control+Shift modifier is supported (because each alone would have a standard character assigned), and so the prefix is not included in the spec: `v:"insert"`.
3. If you combine multiple modifiers, there is only one `+` after them: `CS+v:"insert"`.
4. The quoted value ("insert") was only an example, it is a literal string insertion. To attach a mintty function, its name must be used without quotes: `v:paste`.

So the configuration above could be achieved like
```
KeyFunctions=v:paste;\
                     c:copy;
```

**Comment by Trismegistos84** [comment]
Thx, mintty is good tool but documentation could be improved. One big file with all the options as for example would be sufficient in many cases.

**Comment by mintty** [comment]
That file is called the manual page and it's available online at http://mintty.github.io/mintty.1.html or interactively (from cygwin) via `man mintty`.
I guess there is some potential on improving about `KeyFunctions`. Please check out first.

**Comment by Trismegistos84** [comment]
As I said I was searching through manual but I haven't found what I was looking for. Probably adding some keywords like shortcut or shortkey in right places could help because this is what I was searching for.

**Comment by mintty** [comment]
There is a section "Keyboard shortcuts" and a subsection "User-defined shortcuts" in the introductory Usage chapter of the manual.

**Comment by mintty** [comment]
With 3.4.0, conditions 2. and 3. above are dropped, so the specification can now also look like:
`KeyFunctions=C+S+v:paste;C+S+c:copy`
