### ISSUE TITLE
the content in the mintty window becomes weird if I resize the mintty window

### ISSUE THREAD

**Issue by jdhao** [mintty/mintty#852]
I am using latest version of mintty (2.9.6) with Cygwin on Windows 10 (version 1803). I am connect to my remote server via ssh. When I try to resize the mintty window, the content in the window is messed up.

Step to reproduce:

+ open mintty a connect to the remote server
+ Use nvim to edit some file
+ resize the window to smaller size
+ the window becomes green or empty and can never become normal. When you navigate the file using `j`, `k`, the lines in the file also breaks. In summary, the content becomes messy and I have to exit nvim.

Here is how it looks like

![combine](https://user-images.githubusercontent.com/16662357/52893327-19f8aa00-31d6-11e9-9973-9feffa8e9534.jpg)

But this problem does not exist if I connect to the remote server with ssh client such as [zoc](https://www.emtec.com/zoc/) (everything is the same except I use zoc this time).

**Comment by mintty** [comment]
The information you supply is not sufficient to assess the issue. Maybe you used an ssh that does not transmit the size change. Which one do you use?
In any case, this is not a terminal issue.

**Comment by jdhao** [comment]
I am using openssh in Cygwin to connect to my server. If this is not a terminal issue, why don't I see this issue when I use Zoc terminal.

**Comment by mintty** [comment]
I assume you use cygwin ssh but please confirm, what does `type ssh` say?
When using the other terminal, do you use ssh too, or maybe telnet?
Do a remote login to the shell only, what does `stty size` say before and after resizing?

**Comment by jdhao** [comment]
The output of `type ssh` is: `/usr/bin/ssh`.  When I use Zoc terminal, the connection type is also ssh.

Loging to remote server inside cygwin terminal and the output of `stty size`:

+ Before resizing: 75 262
+ After resizing: 75, 262

**Comment by mintty** [comment]
Is WSL involved (cf https://github.com/mintty/mintty/issues/850#issuecomment-463165782)?
What server do you connect to (`uname -a`)?

**Comment by jdhao** [comment]
No, I am just using cygwin terminal to connect to my remote server.  I have also tried to connect to the remote server using wsltty (the distribution I use is Ubuntu on Windows). The behavior of wsltty is similar to cygwin.

The output of `uname -a` is like the following:

> Linux [the server's ip address] 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mintty** [comment]
I cannot debug this issue further remotely, sorry, I can only state that it works fine elsewhere.
Please get back if you have additional diagnostic information.

**Comment by jdhao** [comment]
Thanks for your works. Do you mean that you can not reproduce this issue on your machine?

**Comment by BrianInglis** [comment]
Info can sometimes be lost between mintty, ssh, and the target host. 
Non-gui editors sometimes require ^L or in neovim :redraw/! or :windo redraw/! to refresh: X window GUI editors seem to work more seamlessly. 
Zoc seems to be a commercial alternative to putty (from which mintty is derived) combining terminal emulation with supporting ssh connections as well as telnet.

**Comment by mintty** [comment]
@jdhao: I do not reproduce this issue.
@BrianInglis: Do you have an idea by what means or under what conditions size info could get lost?
Maybe there is an incompatibility between ssh clients and servers of different versions?

**Comment by avih** [comment]
I'd check `$TERM` at the host and remote system. I had no issues that with a remote session via cygwin ssh fails to detect terminal size changes.

**Comment by jdhao** [comment]
@avih are you connecting to a CentOS system? What is your mintty version? Which Windows version are your using?

**Comment by avih** [comment]
No, 2.96, 8.1-64

**Comment by mintty** [comment]
As a cross-check, please test the issue with another terminal, like xterm.

**Comment by jdhao** [comment]
@mintty , I am using Windows machine. AFAIK,  xterm is not available on Windows.

**Comment by mintty** [comment]
Sure, xterm and X11 are part of the cygwin distribution.
Is that cygwin putty or Windows putty?

**Comment by jdhao** [comment]
@mintty , I am using the Windows putty provided [here](https://www.putty.org/). I have tested xterm by installing it on WSL and Cygwin (I have installed the X server on my Windows). For both WSL and Cygwin, after I login to the remote server,  Xterm can not detect the window size change.

**Comment by mintty** [comment]
> Xterm can not detect the window size change

Thanks for confirming. So this is not a mintty issue.

**Comment by jdhao** [comment]
Why is this not a mintty issue if xterm can not detect the window size change? If I switch from mintty to putty, the issue disappears. The only variable that has changed is the terminal emulator.

**Comment by mintty** [comment]
According to your report, the same issue appears with xterm, so the cause of the issue is not mintty.

**Comment by mintty** [comment]
Thanks for closing. If you found the cause, please report back here anyway, for curiosity and also it might help others that have similar problems.

**Comment by jdhao** [comment]
Unfortunately, I have not found the cause (I will report back if I ever find it). Now, I just use mintty with the maximum window size and do not try to resize it. It does not cause much annoyance.
