### ISSUE TITLE
Black artifact near the vertical scroll bar

### ISSUE THREAD

**Issue by rosti-il** [mintty/mintty#853]
I have a laptop and two external monitors connected through the docking station. All three monitors have the same resolution of 1920 x 1080 but the laptop's internal monitor configured with a different scale of 125% (recommended by Windows 10) instead of 100% in the external monitors (also recommended by Windows 10). The internal monitor is on the left side and the external monitors are in the middle and in the right sides. When I move the mintty 2.9.4 (x86_64-pc-msys), that is part of my git 2.20.1 for Windows installation, from the middle monitor (100% scale) to the right monitor (125%) it flickers for a few seconds (probably because of the scale change) and moves to the right monitor successfully. But after that move there is a vertical black artifact right to the right scroll bar. If I move the mintty window back to the middle monitor it flickers for a few seconds again but that black artifact disappears. It seems like the scroll bar moves a little left and right inside the mintty window. There is no such an issue and no flicker when I move the mintty window between the external monitors with the same scale configurations.

Take a look at the attached screenshot.
![mintty_bug](https://user-images.githubusercontent.com/45571812/52961982-cf795800-33a4-11e9-948d-2e546ed7e872.png)

**Comment by mintty** [comment]
The description of your monitor configuration is inconsistent (right 100%/125%, internal left/middle?).
Anyway, the screenshot looks strange, but mintty does not place the scrollbar, Windows does it, so I don't know how to deal with this. Also, cannot reproduce now due to lack of monitors :)

**Comment by rosti-il** [comment]
The left monitor is internal with 125% scale. The middle and the right monitors are external with 100% scale.
[125%]-[100%]-[100%]
And there is no such an issue and no flicker when I move a CMD window by the same way.

**Comment by mintty** [comment]
So it happens when you move from the left to the middle or right, right?

**Comment by rosti-il** [comment]
The black artifact appears after I moved the mintty window from the middle monitor (100% scale) to the left (125% scale) and disappears after I moved it back from the left monitor to the middle one.

**Comment by mintty** [comment]
Windows handling of multi-monitor DPI scaling has changed a number of times. Mintty has been updated to the latest state-of-the-art (#774). Actually, the scrollbar looks not only displaced but also too thin in the screenshot. I've seen a similar effect occasionally in Firefox. So I guess there is something still bogus in Windows DPI handling...

**Comment by rosti-il** [comment]
Why it doesn't happen with the CMD window?

I also use the Far (File and archive manager) - a console file manager that looks similar to the famous Norton Commander file manager https://farmanager.com/ If I configure its height in the Screen Buffer Size Layout **bigger** than its height in the Window Size the same vertical scroll bar appears. But there also is no such an issue when I move the Far window like I move the mintty window. BTW the Far is open source and you can check how they handle the scale/DPI change.

![image](https://user-images.githubusercontent.com/45571812/52964634-72cd6b80-33ab-11e9-850c-84b657b680b1.png)

**Comment by rosti-il** [comment]
Also the latest Git for Windows version 2.20.1 comes with mintty 2.9.4 that is not latest. In which version of mintty the #774 was fixed?

**Comment by mintty** [comment]
> Far is open source ...

You are welcome to analyse it and make a proposal on improving mintty.

**Comment by BrianInglis** [comment]
To see the release fixing #774 select that thread link and scroll down to the last mintty post (before closed).

**Comment by mintty** [comment]
You could try option `HandleDPI=1` as an experiment. The default was changed to 2 in 2.9.5 which is not yet properly reflected in the manual page.

**Comment by rosti-il** [comment]
Just checked with the recently released Git for Windows 2.21.0 that contains mintty version 2.9.6 and now I'm not able to reproduce this issue. Seems like it was fixed and this bug report may be closed.
