### ISSUE TITLE
Command line clearing upon hitting enter

### ISSUE THREAD

**Issue by zingtech** [mintty/mintty#856]
For some reason mintty has begun to clear my command line and the scrollback when I hit the enter key.  I can't figure out how/why this happened.  If I enter the date command then enter return, the screen clears and the result of the command is printed.  Same thing for any other command. I have not changed anything with my bash prompt.

I am using version 1.2-beta1 from Cygwin 1.7.32 on a Windows 10 PC.

I have been searching for some kind of clue but have not had any luck finding an answer.

**Comment by mintty** [comment]
> has begun ...

You must have changed something. Please check. Mintty does not clear, and has never cleared, specifically a command line. Marking invalid.
And, for that matter, both cygwin 1.7 and mintty 1.2 are very, **very** outdated versions. Closing.
