### ISSUE TITLE
Recognize .bat and .cmd as executable files

### ISSUE THREAD

**Issue by birgersp** [mintty/mintty#857]
Hello,

Since `.bat` and `.cmd` files are executable in Windows, I suggest they should be treated as such in the terminal. So if I have a file in current directory named "my-batch-script.bat", autocompletion should (in my opinion, of course) suggest it when I type "./my-ba" and hit TAB.

If my file was named "my-executable.exe", autocompletion would suggest it right away.

**Comment by mintty** [comment]
Set the executable flag in the files. However, it's the shell that runs applications, this is not a terminal issue, thus marking invalid.

**Comment by birgersp** [comment]
> it's the shell that runs applications

Sorry, could you please point me in the right direction here? If this feature were to be implemented, which project would it be in?

**Comment by mintty** [comment]
The feature is available, provided by cygwin. You just need to set the flag (`chmod +x *.bat`) to enable the scripts to be recognized as executable.

**Comment by birgersp** [comment]
My proposal is that these filetypes should be recognized as executables by default. But I guess you're saying it is a cygwin issue?

**Comment by mintty** [comment]
https://cygwin.com/ml/cygwin/
