### ISSUE TITLE
Blurry font on 4k screen with size set to 200% after upgrading to 2.9.5

### ISSUE THREAD

**Issue by vbuslov** [mintty/mintty#858]
After updating to version 2.9.5 I now get blurry font in terminal window by default. Setting "Disable display scaling on high DPI setting" checkbox for msys2.exe binary fixes the issue.

Windows 10 Enterprise 1607, single 4k display with 200% size.

**Comment by mintty** [comment]
Please try mintty option `HandleDPI=1` with the previous msys2 settings.
The default was changed to 2 in 2.9.5.

**Comment by vbuslov** [comment]
Thanks. Closing the issue.

**Comment by mintty** [comment]
Does that mean the option solves the issue for you?
That does not really close the issue as mintty should not have blurred display with default settings.
With this diagnostic information, maybe someone with deeper Windows insights may try to analyse the situation. @v1ne who contributed #774 might have an idea.

**Comment by vbuslov** [comment]
The option does solve the issue for me.
I closed it because description of #774 says "This change adds basic support for per-window DPI awareness v2, introduced with Windows 10 1703." so I assume my Windows 10 Enterprise 1607 is not supported.

**Comment by mintty** [comment]
Correct: DPI mode "v2" is not supported in 1607, but then mintty should automatically fall back to "v1" which should not result in blurred display either - as I understood, but maybe that's wrong.
Or rather, as you got the issue when the mintty default was changed to 2, maybe the fallback does not work for some reason...

**Comment by mintty** [comment]
Please run the attached test program.
[testdpi.zip](https://github.com/mintty/mintty/files/3012040/testdpi.zip)

**Comment by mintty** [comment]
Closing due to lack of debugging info.
