### ISSUE TITLE
latest version breaks emacs editing

### ISSUE THREAD

**Issue by glumr** [mintty/mintty#860]
Sorry for lack of detail at the moment.

I updated cygwin today (for other reasons) and was updated to mintty 2.9.7-0
With this version, control keys (<CTRL> j,k,l) do not work to move within emacs and cause characters (numbers and ;) to be added into the document.
I'm running on Windows 7/64 in the tcsh shell.

Had to revert to my previous 2.9.5-0

**Comment by mintty** [comment]
That's been fixed with 2.9.8, please recheck.
Emacs uses xterm modifyOtherKeys mode which reports control chars as sequences. The base chars reported were capital rather than small letters in 2.9.7.

**Comment by glumr** [comment]
The mirror I use is now offering 2.9.8-0
But the problem is the same.
Arrow keys work.

<CTRL>j,k,l,m produce

6;5u7;5u8;5u9;5u

in the buffer.

**Comment by mintty** [comment]
Sorry, I blamed the wrong change for the bug. Now fixed in the repository but not yet released.

**Comment by mintty** [comment]
Hopefully, this time it's fixed. Released 2.9.9.

**Comment by glumr** [comment]
I verified that 2.9.9 is OK
Thanks
