### ISSUE TITLE
Improve Interactive Prompting

### ISSUE THREAD

**Issue by bitmvr** [mintty/mintty#861]
There seems to be a bug in `mintty` where input does work properly. 

There are tons of examples from various other issues opened across different tooling, but `mintty` seems likely to be the source of the problem. I'm willing to help possible fixes in the future if the team can decipher what might be going on from the examples below:

> https://github.com/terkelg/prompts/issues/35

> https://github.com/SBoudrias/Inquirer.js/issues/621?_pjax=%23js-repo-pjax-container

Thanks.

**Comment by mintty** [comment]
Some more relation to the terminal could be helpful in assessing such an issue; details of application software are not helpful here. Just looking at the mention of some rawmode function, it might be a duplicate of issue 56, but both referred issues are very fuzzy. No further comment at this time.

**Comment by bitmvr** [comment]
@mintty - It appears you're correct. It looks like it's a duplicate of #56

Expect this to be closed.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.
