### ISSUE TITLE
Bug? - MSYS2/MINGW64 - initial window dir =HOME - "New" window Initial dir =/ ???

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/mintty#870]

**Comment by aabatpurdue** [comment]
I seem to have clicked in the wrong place and submitted this missive before I wrote a description.  So ...

I use _mintty_ in Cygwin, GitForWindows, MSYS2/MINGW64, Ubuntu and Debian.  They all use identical **.bashrc** files so I hope this problem is not there. The initial directory set for all is the correct HOME directory.  For all except the MSYS2/MINGW64 invocation,  if I right click the title and left click "New" the initial directory is HOME.  On MSYS2/MINGW64, however, the initial "New" directory is **/**.

My fault???

**Comment by mintty** [comment]
[I guess you could have edited the description]

Reproduced sometimes, however, this is one the bugs that vanish when I try to trace them...
I could at least monitor that none of the explicit chdir calls in mintty seems to be applied in the buggy case, and also that mintty also is in "/" as current directory in the good case.
I suspect behaviour is interworking with the MSYS2 launcher script msys2_shell.cmd.
It seems to start the shell as a non-login shell, which may contribute to the problem.

As a workaround, you may want to use the OSC 7 feature:
https://github.com/mintty/mintty/wiki/Tips#spawning-a-new-terminal-window-in-the-same-directory

**Comment by mintty** [comment]
There were two changes to ensure "New" or Alt+F2 should start the new window in the proper directory:
https://github.com/mintty/mintty/commit/28dd680f8e1fc16b9e2adeef7f48004435b1233a
and
https://github.com/mintty/mintty/commit/a57eaa21178ec1b9a9bc4faced66821d4b2b1579

These would *probably* fix the issue if the shortcut handling was applied in MSYS2. However, the interworking with the launcher script prevents this, MSYS2 mintty does not know that it was initially started from a shortcut.

**Comment by aabatpurdue** [comment]
FMI - does clicking on **New** cause execution of _msys2_shell.cmd_?

I normally instantiate a MSYS2/MINGW64 session via _**C:\msys64\msys2.exe**_ or _**C:\msys64\mingw64.exe**_.

I may have found the problem code in _/etc/post-install/05-home-dir.post_ that is "dotted" in _/etc/profile_.  See its code  from about line 252-263.

**Comment by mintty** [comment]
> FMI - does clicking on New cause execution of msys2_shell.cmd?

First I had thought so, but no, in fact it doesn't.

> I may have found the problem code ...

Good. It's a bit weird that "post-install" scripts are sourced in the profile.

**Comment by aabatpurdue** [comment]
I cheat a bit.  I have the **CHERE_INVOKING=1** line in _C:\msys64\msys2.ini_ commented out.  Otherwise, I suspect that the window would always end up in **/** (:@{).

**Comment by mintty** [comment]
Have you found a solution? Did you report it to MSYS2?

**Comment by aabatpurdue** [comment]
No solution (:@{).  The code referenced above is actually correct and duplicates identical code found in 
Cygwin's _/etc/profile_.  It causes the observed behavior  because **CHOST_INVOKING=NULL** for the initial _mintty_ instantiation but **CHOST_INVOKING=1**  for any subsequent instantiation via **New** or **Alt-F2**.

**Comment by mintty** [comment]
CHERE_INVOKING was introduced in 2.8.5 to solve exactly this problem. It seems that in the context of the MSYS2 startup procedure, it has the opposite effect. References:
https://github.com/mintty/mintty/issues/500#issuecomment-378362945
https://github.com/mintty/mintty/pull/471#issuecomment-157375979
To be analyzed.

**Comment by mintty** [comment]
In the meantime, did you try the OSC 7 feature referred above?
It achieves even more, you can clone within the respective current directory.

**Comment by aabatpurdue** [comment]
OSC 7 seems like the long way to do it.

Note: **CHERE_INVOKING=1** for **New**/**Alt-F2** on Cygwin also.  The difference there is that the starting directory is **HOME** as  indicated by  the following _pwd_ for both initial and clone.  I put a 

    pwd
    echo CHERE_INVOKING = $CHERE_INVOKING

as the first two lines of _/etc/profile_ in both systems.

I instantiate _mintty_ using shortcuts.  There is an undocumented option, **--dir~** that works as a workaround for MSYS2 but can't be used for MINGW64 because the environment variable **MSYSTEM=MINGW64** cannot be defined (:@{).

**Comment by aabatpurdue** [comment]
Hooray, disk was replaced.  I suggested some time ago that _mintty_ could have an option to define environment variables.  That would solve the "can't do" in the previous  comment.

**Comment by mintty** [comment]
See https://github.com/mintty/mintty/wiki/Tips#setting-environment-variables about environment variables.
There are options --dir and -~, both are documented.
About MSYSTEM=MINGW64, as far as I understand, that is the variant of MSYS2 that lacks the POSIX support, so mintty could not run anyway. Not sure, however.

**Comment by avih** [comment]
> as far as I understand, that is the variant of MSYS2 that lacks the POSIX support

No. It's a variant where the toolchain defaults to mingw, but otherwise it's the same as the non-MINGW variant.

It's just a different `$PATH` where the mingw bin dir comes before the main bin dir. So it also takes various tools from there (like cmake or python) if their mingw variant is installed.

**Comment by mintty** [comment]
Ah, so what I remembered was that I couldn't *compile* mintty in MINGW; thanks for the explanation.

**Comment by mintty** [comment]
I could reproduce this with the mintty binary as distributed with MSYS2 but not with mintty compiled myself (for testing).
This reminds me that they used to apply a patch to mintty in that area which is no longer required (for quite some time already) because mintty handles Alt+F2 directory issues itself now.
However, the patch is apparently still applied, see https://github.com/msys2/MSYS2-packages/tree/master/mintty - which is likely to interfere with mintty's own handling and thus produces the problem. They should remove it.
Please report the issue to the MSYS2 project (referring to this comment).

**Comment by Biswa96** [comment]
@Alexpux may help.
