### ISSUE TITLE
Could KeyFunctions config remap to control combination?

### ISSUE THREAD

**Issue by palmtenor** [mintty/mintty#873]
For example, if I want to map `Esc` to `Control + E` (hypothetically), can I do that by using the `KeyFunctions` config? I tried `^E` with string literal syntax (quotes) but that doesn't seem to work.

**Comment by mintty** [comment]
> Space, Enter, Esc and Tab are only considered with at least one modifier

Also, key definitions may interfere with mintty keyboard shortcuts or Windows hotkeys...

**Comment by palmtenor** [comment]
I may have used a bad example. Let me explain my motivation.  I have `CtrlExchangeShift` turned on because I prefer Windows style copy / paste shortcuts. But I still want to use `Control + {}` for most other keys other than `c` and `v`, at least those I care about like `h` / `j` / `k` / `l` for `vim`. So I was wondering if I could write something like
```
KeyFunctions=h:^h;j:^j;...
```
which effectively make that I only do `CtrlExchangeShift` on `c` and `v`?

**Comment by mintty** [comment]
To achieve that, you'd have to enclose the text in double quotes, and embed the control character verbatim.
As noted in the manual, there is no escape notation. ^j will not work right now.

**Comment by palmtenor** [comment]
I see, that makes sense. How do I enter or find those control characters? Or do we want to add the ability to escape `^` in the `KeyFunction` value?

**Comment by mintty** [comment]
> How do I enter or find those control characters?

That depends entirely on your text editor.

> Or do we want to add the ability to escape ^ in the KeyFunction value?

Possibly.

**Comment by mintty** [comment]
Released 3.0.1.
