### ISSUE TITLE
question - no numberpad - pgup/pgdn/home/end combined with the arrow keys --

### ISSUE THREAD

**Issue by aabatpurdue** [mintty/mintty#874]
I have a new laptop with a keyboard that doesn't have a numberpad.  The pgup/pgdn/home/end keys are combined with the arrow keys.  pgup/pgdn no longer work as expected.  I've tried shift/ctrl/alt with the pgup/pgdn keys but had no success.

Question - is there any way that I can get the pgup/pgdn keys to work without a modifier?  FWIW - I have "PgUp and PgDn work without modifier" checked.  The pgup/pgdn keys work for me when they are in the numberpad.

--  Thanks

**Comment by mintty** [comment]
On such keyboards, you normally have an overlay key assignment, with PgUp etc marked in a colour (e.g. blue or red) and you'd have a "FN" key marked in the same colour. FN would then be a keyboard-internal modifier that sends your PgUp etc as if they were typed on a normal keyboard, i.e. without additional modifiers. This works without any involvement of Windows or even the terminal.

If your keyboard does not work like that, I'd call it broken and you should complain to the manufacturer. How does it look like, what's the laptop model? In that case, an expert with access to such keyboard would be helpful to craft a workaround if possible.

**Comment by BrianInglis** [comment]
Check your laptop docs for key maps. Some non-standard keyboards, like other devices, require an OS driver to translate non-standard keycodes into recognized function codes. Someone should be able to help at the online vendor or offline store it was bought from.

**Comment by aabatpurdue** [comment]
Using the **Fn** key does the trick.  Unfortunately, that is not a "no modifier" solution.  Oh well, at least something works.

The machine is a three week old Dell **Inspiron 7580**.  I saw no mention in any literature that I read that there was no number pad on the keyboard (:@{).

--  Thanks

**Comment by mintty** [comment]
Watch out what you buy! A 15" laptop would indeed have enough space for a real numberpad rather than that fiddly crap...
You could upgrade: https://www.amazon.com/s?k=numberpad&ref=nb_sb_noss_2
