### ISSUE TITLE
Why does scroll bar and its button to drag for fast page scrolling disappear in emacs

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#876]
I am fond of useing emacs on Msys terminal, but the scroll bar and its button to drag for fast page scrolling disappear in emacs.
How to solve this

**Comment by mintty** [comment]
In a screen-oriented application like a text editor, it does not make sense to use the terminal scrollbar, which would not refer to the actual application contents anyway.
For that reason, applications may temporarily switch off the scrollbar with the respective escape sequence.

**Comment by mintty** [comment]
You can enforce the scrollbar in the Shift+right-mouse-click menu and check out why it does not make sense with emacs.

**Comment by mintty** [comment]
It would be possible to support interaction with the system scrollbar via escape sequences.
However, I am not aware of any other terminal offering such a feature, so the sequences would have to be invented. Also, it would require cooperating applications to make use of such a feature, which do not yet exist.
If any application (such as emacs) expresses interest in such a mode, I'm willing to implement it.

**Comment by mintty** [comment]
Mintty supports an application scrollbar now.
However, its usage is up to an application.
