### ISSUE TITLE
Rich text and HTML clipboard selections have trailing spaces

### ISSUE THREAD

**Issue by bburhans** [mintty/mintty#878]
It seems as though the various feature and configuration changes around RTF and HTML clipboard copy features (great work, by the way!) have had a side effect regarding trailing whitespace for all non-plaintext clipboard formats.

I used to be able to copy short (unwrapped) or long (wrapped) lines written as "raw" newline-delimited console output (i.e. without `less` or `tmux` or some other application doing its own wrapping/paging/whitespace magic) and paste it into a rich text editor and it would Just Work, giving me text with foreground colors and my chosen mintty font but without the background colors and trailing spaces after newlines. Now, if I copy the output of `echo "      "` into such an editor, I get neither six spaces (as expected with `TrimSelection=false`) nor zero spaces (as expected with `TrimSelection=true`), but instead get my entire terminal's column width filled with spaces. This applies to every combination of the relevant configuration options, with the RTF used instead of any HTML format if selected because of my RTF editor's paste behavior:

![image](https://user-images.githubusercontent.com/311277/58216620-40464e00-7ccd-11e9-9ad3-f6ab9fb90835.png)

I believe this issue began on my local machine between 2019-03-29 and 2019-04-05 as a result of a new release of Git for Windows. My latest version when I began investigating it was mintty 2.9.6 in Git for Windows 2.21.0 x64; I have also tested the msys repo's binary distribution of mintty 3.0.0 x64 with no difference in this particular behavior. For reproduction tests, I used Outlook 2016 x64 as the RTF>HTML>plaintext paste target, and Windows 7 Notepad or bash in mintty itself as a plaintext paste target.

I have no other customizations to my `.minttyrc` except to test the `TrimSelection` option, and I have nothing in my `.inputrc` except `set enable-bracketed-paste on`.

Honestly, my use cases don't usually require colors, font sizes, and other HTML style attributes except a monospace font family; unfortunately, there's no good way for me to tell Outlook or mintty that all plaintext clipboard actions should be converted to a monospace font face, otherwise I'd turn off all rich clipboard features in mintty and do that instead.

Thanks for maintaining such a versatile piece of software to make Windows environments tolerable for terminal users. The fact that mintty is included in all of the best Windows compatibility frameworks is a testament to its success.

**Comment by mintty** [comment]
For RTF, I'm getting the expected results. For Copy as HTML text (and maybe Copy as HTML), I'll look into it, maybe trailing spaces can be dropped; however, I don't think this was handled differently since introducing HTML copy in 2.9.4.

> my use cases don't usually require colors, font sizes, and other HTML style attributes except a monospace font family

Choosing a set of attributes that make sense to be copied is a matter of taste to some extent, that's also why there are 3 options. "Monospace but no specific font" might be another option, or configurable... but dropping colours and other attributes does not make too much sense, that's where Copy as plain text would be applicable.

**Comment by bburhans** [comment]
I must have misrecorded the results of some tests, because RTF on and HTML completely off works as expected; my apologies. I had 3 instances open concurrently at one point (different releases) and I probably mixed up the options in each. On a different machine, I have since reproduced the issue on a "git bash" mintty 2.9.4, which was before the HTML options were configurable in the UI.

I also just identified a related issue in 3.0.0 that probably confused me yesterday without me realizing the cause: the RTF and HTML options affect each other when pasting to a program that accepts both, even though I'd assume it would just pick one from a list of preferred formats and ignore the others. For example, in 3.0.0, `Full` HTML with RTF disabled yields mintty's default background and foreground color (white-on-black in my case, barring escape sequences), but `Full` HTML with RTF enabled yields output with only explicit colors that are generated by escaped content. I'm not sure whether this is a bug in mintty or in the paste target, but both conditions still exhibit the trailing whitespace bug as originally reported unless HTML is completely disabled.

For now, RTF on without any HTML covers most of my use cases, at least!

**Comment by mintty** [comment]
> the RTF and HTML options affect each other when pasting to a program that accepts both ...

Not quite. I guess the target application picks HTML in your case. HTML format level for HTML-enabled default copy, however, is affected by the RTF setting: with RTF enabled, it's "HTML" rather than "HTML full". I don't remember the reason for this, and it's unfortunately not documented...

You can workaround that by using the desired copy format variation explicitly from the extended context menu (Control+right-click), also for better testing.

> both conditions still exhibit the trailing whitespace bug as originally reported unless HTML is completely disabled.

I wouldn't call it a bug in the case of "HTML full" because that's supposed to reproduce the exact screen layout. It would look quite ragged if you paste with background colour and get lines of differently trimmed length.

**Comment by bburhans** [comment]
>that's supposed to reproduce the exact screen layout. It would look quite ragged if you paste with background colour and get lines of differently trimmed length.

Ah, that makes sense, although I do recall at least one other terminal exhibiting the jagged-background behavior a while back and I guess I assumed that was normal.

The best alternative would be using a block wrapper element like `<div>` to set global styles, but it appears we're already doing that (see my demo below). I think that means we can simply avoid generating extra spaces inside the `<pre>` and that should be good enough.

As clip.exe only works with plaintext, I wrote a little web tool for inspecting the clipboard as markup and as rendered HTML to aid our testing: https://codepen.io/anon/pen/joZozE

You can copy and paste directly from mintty into the specified box. While using this tool, I noticed that the mintty-generated markup has external CSS references that probably never resolve to anything and Javascript used for blinking animations that can be replaced with CSS animations or removed. Thoughts?

**Comment by naknak-** [comment]
Nirsoft's [Inside Clipboard](http://www.nirsoft.net/utils/inside_clipboard.html) is a good tool for inspecting the clipboard.  No need to paste; it will show all the formats that are present.

> there's no good way for me to tell Outlook or mintty that all plaintext clipboard actions should be converted to a monospace font face, otherwise I'd turn off all rich clipboard features in mintty and do that instead.

I have a similar problem: pasting into Outlook tries to preserve my mintty font, which my audience probably won't have.  Mintty sets the font-family ("modern") properly but Outlook ignores that and renders a variable-width font when the named font is missing.   I [made a patch](https://github.com/mintty/mintty/compare/master...naknak-:master) that adds `CopyasRTFFont` and `CopyAsRTFFontHeight` options to .minttyrc;  it doesn't suppress colors, but it does allow the use of a good font in mintty while pasting into Outlook in Courier New or Lucida Console - the only two fixed-width fonts you can rely on Windows users having.

You can see from this patch how to affect behaviour of `win_copy_as()` in winclip.c, using a minttyrc directive of your own.  Suppressing formatting should be as simple as wrapping the attribute detection code with `if ( ! cfg.my_plain_rtf_option ) { ... }`

**Comment by mintty** [comment]
Thanks for the two tool hints. I had written my own command-line clipboard display tool at the time...
(The Nirsoft tool has an issue with LF-only line separators; I've sent them a suggestion to improve.)

Thanks for the RTFFont patch. Did you try whether it's possible to achieve something automatic? For example, by just leaving out the font name and only setting the "modern" family? Is "modern" actually proper or would something like "fixed", "mono" or "monospace" help here? If not, I'll apply your patch (or you may submit it to the repository if you prefer).

**Comment by naknak-** [comment]
It was a couple months since I made this patch and I don't remember exactly all the things I tried, but [from the spec](http://www.biblioscape.com/rtf15_spec.htm#Heading12) it looks like fontname is required (no question mark after it in the definition).  

Outlook has exactly the same problem with HTML (and it will prefer HTML over RTF when both are present in the clipboard, even if the e-mail is RTF).  With HTML, I did try things like listing extra fonts or specifying only font-family; no success.

I couldn't find any flaws in the generated RTF; the "modern" family is definitely correct (spec says which family names are valid and "fixed", etc. aren't there).  That's not to say that Outlook wouldn't magically work if you said "monospace" instead.

**Comment by mintty** [comment]
Looking the RTF clipboard, I see
`\fonttbl{\f0\fmodern DejaVu Sans Mono;}`
That looks as if a comma or some separator is missing.

**Comment by naknak-** [comment]
I think the syntax is right.  WordPad does the same thing (though with charset specified and family=nil):

`\fonttbl{\f0\fnil\fcharset0 DejaVu Sans Mono;}`

**Comment by BrianInglis** [comment]
In Outlook HTML you could try specifying downloadable web fonts e.g. 19 mono out of 916 total from Google: 
```<link href="https://fonts.googleapis.com/css?family=`_monofont1_`|`_monofont2[|...]_`" rel="stylesheet" type="text/css">```
browse on [Google](https://fonts.google.com/?category=Monospace&selection.family=Anonymous+Pro|B612+Mono|Cousine|Cutive+Mono|Fira+Mono|IBM+Plex+Mono|Inconsolata|Major+Mono+Display|Nanum+Gothic+Coding|Nova+Mono|Overpass+Mono|Oxygen+Mono|PT+Mono|Roboto+Mono|Share+Tech+Mono|Source+Code+Pro|Space+Mono|Ubuntu+Mono|VT323) and deal with fallbacks as suggested on [DM](https://www.campaignmonitor.com/resources/guides/web-fonts-in-email/#five-6):
```
<!--[if mso]>
<style type=”text/css”>
.fallback-text { font-family:monofont1,monofont2,Courier,monospace; }
</style>
<![endif]-->
```
using it like: 
```<td class=”fallback-text” style="font-family: monofont1, monofont2, Courier, monospace;”>Mono space font for all!</td>```
Hint: there are some good Direct Mail marketing consultant web sites which have great info on compatibility and usability across email clients and web browsers.

**Comment by mintty** [comment]
@naknak-, I've specified "fixed pitch" (\fprq1) for the font additionally, but Outlook ignores it.
If you want to submit your patch, please change `char copy_as_rtf_font_size;` to `int` and shorten the manual entry to
The font used in RTF may be changed by the settings \fBCopyAsRTFFont\fP and \fBCopyAsRTFFontHeight\fP to accommodate the case that the configured mintty font is not available when reading the contents (e.g. after sending it by mail).

**Comment by naknak-** [comment]
ok done

**Comment by mintty** [comment]
If I click "Create pull request" on the patch there is another "Create pull request" button below the comment field but it's disabled. I'm not versatile at handling git and github, it would help if you make a regular pull request to the repository. Or I can just manually make the change and commit on behalf of you.

**Comment by BrianInglis** [comment]
You don't create pull requests, others do in forks from your repo. 
You select Pull Request menu/tab at top then select PR CopyAsRTFFont[Height]: force RTF clipboard font #879. 
You should see a button or buttons with or that lead to options to Merge, Squish, or Rebase the PR from the fork into your repo. 
You may have to review or resolve conflicts.

**Comment by Biswa96** [comment]
@mintty Did you squash nanak's commits? The PR shows as one but it has 4 commits.

**Comment by mintty** [comment]
Yes, I always squash pull requests.

**Comment by mintty** [comment]
Released 3.0.1.

**Comment by kkoorndyk** [comment]
I'm seeing this behavior in mintty 3.2.0 (Cygwin).  Copy and paste into OneNote and Outlook consistently include trailing whitespace.

![image](https://user-images.githubusercontent.com/14894247/94184765-6310e580-fe72-11ea-8cec-8f0348fb1f6c.png)

**Comment by mintty** [comment]
Cannot reproduce. Spaces are trimmed for me in OneNote.
