### ISSUE TITLE
Handle U+FE0F variation selector to render characters as emoji

### ISSUE THREAD

**Issue by nyuszika7h** [mintty/mintty#880]
I've installed the Twitter emoji font in wsltty 3.0.1.2 per the mintty wiki's instructions, and the emoji rendering works for the most part. However, there are certain characters that are only to be rendered as emoji if followed by [U+FE0F](https://emojipedia.org/emoji/%EF%B8%8F/), and mintty does not render these as emoji even in presence of this variation selector.

Examples:
* https://emojipedia.org/pencil/ (`270f-fe0f.png`)
* https://emojipedia.org/information-source/ (`2139-fe0f.png`)

Screenshot:

![Screenshot](https://user-images.githubusercontent.com/482367/58839008-a2556a80-8660-11e9-9a16-dfb479ca87b4.png)

**Comment by mintty** [comment]
Works for me. I suppose the Twitter emoji set you installed does not include the respective emoji graphics. Try another one.

**Comment by nyuszika7h** [comment]
They are included, named like `270f-fe0f.png` for example like I said. Does mintty expect different file names?

**Comment by mintty** [comment]
In fact, yes, mintty assumes that emoji sequences with FE0F are displayed by graphics without that suffix.
It may have been the naming scheme of emoji graphics at the time I designed the implementation.
Could it have changed? To be checked.

About the width, that works as designed. As discussed in other issues, the display width is always made consistent with the locale-determined width of the respective character sequence. That also applies to emoji sequences, which can therefore be displayed in more than two cells width.

**Comment by nyuszika7h** [comment]
Does that mean there is no way to fix it? I just checked and for example the character sequence `\U1F937\U1F3FF\u200d\u2640\ufe0f` (🤷🏿‍♀️) shows up 5 characters wide, which is problematic too.

**Comment by mintty** [comment]
Quoting from wiki Tips:

> Emojis are displayed in the rectangular character cell group determined by the cumulated width of the emoji sequence characters. The option EmojiPlacement can adjust the location of emoji graphics within that area.

An application cannot know whether the terminal applies emoji graphic rendering or not. But in the cell-based traditional terminal paradigm, applications must know how many cells their output occupies. So I do not consider it a good idea to drop reliable width information for the sake of emoji display — _that_ would be problematic. It's a trade-off; there is no way to "fix" it because it's not a bug.

**Comment by nyuszika7h** [comment]
I don't understand why the emoji width information is provided like that, but if it's not possible to fix without breaking other things that makes sense I guess.

**Comment by nyuszika7h** [comment]
I found this, not sure if it helps:

> [[UTS51](https://www.unicode.org/reports/tr41/tr41-24.html#UTS51)] emoji presentation sequences behave as though they were East Asian Wide, regardless of their assigned East_Asian_Width property value.

https://www.unicode.org/reports/tr11/tr11-36.html#Recommendations

**Comment by mintty** [comment]
This was also discussed in https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9#note_121976 and subsequent comments. Unicode is not a good model for cell-based terminals in this respect, unfortunately. I could imagine an optional workaround...

**Comment by nyuszika7h** [comment]
If I understood correctly, this would also require the apps to agree with the terminal on the width of the characters, right?

As for the variation selector issue, it seems like the problem only happens with emojis that are two code points long (including the variation selector), mintty correctly detects the emoji for longer sequences even if the file name contains `-fe0f` at the end:

![Screenshot](https://user-images.githubusercontent.com/482367/58881730-0f0d4b00-86db-11e9-8b48-fde4642f13a1.png)

**Comment by mintty** [comment]
The Unicode database contains distinct files `emoji-data.txt`, `emoji-sequences.txt`, `emoji-zwj-sequences.txt` and `emoji-variation-sequences.txt`, thereby calling for non-uniform handling...

Try EmojiPlacement=align or =middle to avoid the stretching if you prefer.

**Comment by nyuszika7h** [comment]
That's better, it basically does what I was trying by resizing the images, not perfect but it does the trick.

**Comment by mintty** [comment]
So where did you download the failing repository? Extracting "twitter" emojis from the Unicode charts, using my script, gives me 2139.png and 270f.png both without suffix.

**Comment by nyuszika7h** [comment]
Here: https://github.com/iamcal/emoji-data/tree/master/img-twitter-72

It's mentioned in the [mintty wiki](https://github.com/mintty/mintty/wiki/Tips#installing-emoji-resources).

**Comment by mintty** [comment]
OK, that repository seems to be a clone of older emoji data, not updated recently, and following that naming scheme which I suppose is deprecated. I think I'll remove it from the wiki list.
You can deploy emoji data from the Unicode charts list. If only the script wouldn't be so slow...
