### ISSUE TITLE
Is it possible to have Programs Update without Creating a new line?

### ISSUE THREAD

**Issue by Jekuma** [mintty/mintty#882]
I'm not sure I'm using the right words for this, but a behavior I noticed when using mintty is that running programs (such as mpv) from the terminal, it updates itself by creating a new line.

For example:

```
Playing: Mario Kart Wii - Coconut Mall.m4a
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 44100Hz)
AO: [wasapi] 44100Hz stereo 2ch float
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)
A: 00:00:00 / 00:02:21 (0%)

```
Instead of it just updating the on one single line like in many other terminal emulators, it creates a new line for every update. Additionally I can't control it in any way.

Is there any way to allow updates to occur on one single line for programs like these? Thank you.

**Comment by avih** [comment]
mpv terminal output on Windows is for windows console - not for ansi/unix terminal.

To run mpv inside mintty, you need to translate the windows console output/input of mpv to ansi/unix terminal which is mintty. This can be done using `winpty` ( https://github.com/rprichard/winpty ).

`winpty` is available in msys2, but on cygwin you'll need to build and install it yourself.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support. Please recheck.
