### ISSUE TITLE
Up-arrow in 'less' only scrolls the top line 

### ISSUE THREAD

**Issue by squished-01** [mintty/mintty#884]
I don't know if this is a bug. Hopefully it's something I can fix.  I've also asked this question on superuser:  https://superuser.com/questions/1447068/when-i-press-up-arrow-in-less-in-mintty-cygwin-only-the-top-line-changes-h

![Image of Issue](https://i.imgur.com/poDFRWB.gif)

Can someone please help me fix this?

(To be clear, the issue occurs when I type less followed by the name of any text file. The man less in the gif is just an arbitrary command to demonstrate the visual behavior of my less command.)

**Comment by BrianInglis** [comment]
I've only seen those kinds of effects when TERM was set to something not supported by the underlying emulator, curses, readline, or equivalent libraries, or the termcap/info entry or content was bad.

**Comment by mintty** [comment]
Which version do you use? There was in fact a bug in 2.9.2 that could cause such behaviour.
Or some program you ran before could have set up a scrolling region and not cleared it.

**Comment by squished-01** [comment]
Oh good grief.  I was on 2.9.2.  Updating fixed it.  That feeling when you've been poking in config files and it's such a stupidly obvious solution.  Thanks.
