### ISSUE TITLE
Highlight in taskbar fails while window is minimized through the taskbar

### ISSUE THREAD

**Issue by ducalex** [mintty/mintty#887]
This bug has the same description as #607 except I think I have narrowed down the behavior.

flash_taskbar doesn't engage on a bell if the window was minimized by pressing its icon in the taskbar. (Or in other words if the window wasn't minimized by the minimize button.) The audio bell works in all cases.

I've made a short video to show the issue: https://imgur.com/a/4s7YGm7

OS: Windows 8.1
mintty: 3.0.1

**Comment by mintty** [comment]
Thanks for the diagnostics. It's because when you minimize that way, Windows still keeps the focus on the window. Easy fix.

**Comment by mintty** [comment]
Released 3.0.2.
