### ISSUE TITLE
Some warnings -> errors with gcc 9

### ISSUE THREAD

**Issue by avih** [mintty/mintty#891]
In cygwin (gcc 7.4.0) it builds fine, but in msys2 (gcc 9.1.0) there are some warnings which end up as errors:
```
In file included from ./std.h:22,
                 from <command-line>:
wininput.c: In function ‘append_commands’:
wininput.c:166:22: error: array subscript has type ‘char’ [-Werror=char-subscripts]
  166 |       while (isspace(*cmdp))
      |                      ^~~~~
wininput.c: In function ‘check_commands’:
wininput.c:589:24: error: array subscript has type ‘char’ [-Werror=char-subscripts]
  589 |         while (isspace(*cmdp))
      |                        ^~~~~
wininput.c: In function ‘pick_key_function’:
wininput.c:1703:24: error: array subscript has type ‘char’ [-Werror=char-subscripts]
 1703 |         while (isspace(*cmdp))
      |                        ^~~~~
In file included from ./std.h:22,
                 from <command-line>:
child.c: In function ‘user_command’:
child.c:893:26: error: array subscript has type ‘char’ [-Werror=char-subscripts]
  893 |           while (isspace(*cmdp))
      |                          ^~~~~
child.c: In function ‘child_launch’:
child.c:1232:26: error: array subscript has type ‘char’ [-Werror=char-subscripts]
 1232 |           while (isspace(*cmdp))
      |                          ^~~~~
term.c: In function ‘check_emoji’:
term.c:1481:25: error: taking address of packed member of ‘struct emoji_base’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
 1481 |     efnpoi = (wchar * *)&emoji_bases[e.idx].res;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from ./std.h:22,
                 from <command-line>:
winmain.c: In function ‘enum_commands’:
winmain.c:3659:24: error: array subscript has type ‘char’ [-Werror=char-subscripts]
 3659 |         while (isspace(*cmdp))
      |                        ^~~~~

```

The "char subscript" issues can be make to work by casting to `uchar` (though I don't know if that's correct).

I didn't try to work around the `-Werror=address-of-packed-member` issue.

**Comment by mintty** [comment]
Thanks for the hint.
I hope it doesn't become a habit that every new gcc version introduces additional peculiar, assumedly-helpful error checks (https://github.com/mintty/mintty/commit/f7df4adf1775638b2aa75defb01822c0c21d6bcd)...
gcc 9 is not yet available for cygwin...

**Comment by Biswa96** [comment]
cygwin itself [has issues](https://www.cygwin.com/ml/cygwin/2019-07/msg00039.html) with gcc 8.3.0.

**Comment by mintty** [comment]
Also, I don't see a problem in the code here. The signature of isspace specifies its parameter as int which extends implicitly from char. About the emoji check, if it did not complain 3 lines above, with the same scenario, that's strange. Maybe these should be reported as gcc bugs?

**Comment by mintty** [comment]
Try `make CCOPT=-Wno-char-subscripts` as a workaround.

**Comment by avih** [comment]
with `` it fails with
```
wintext.c: In function ‘scale_to_image_ratio’:
wintext.c:2185:7: error: taking the absolute value of unsigned type ‘uint’ {aka ‘unsigned int’} has no effect [-Werror=absolute-value]
 2185 |   if (abs(bw * h - bh * w) < w + h)
      |       ^~~
```

With
```
make CCOPT="-Wno-char-subscripts -Wno-address-of-packed-member -Wno-absolute-value"
```
it builds and seem to work.

If you think the warnings are not real issues, then I think you should make them not fail the build.

**Comment by avih** [comment]
The abs value issue is originally at line 2109 (moved down to 2185 due to my own unrelated patch adding some lines earlier in that file).

**Comment by mintty** [comment]
Actually, msys gcc version is also still 7.4.0...

**Comment by mintty** [comment]
>  if (abs(bw * h - bh * w) < w + h)

w and h are `int` in this context and the assumption is that `unsigned int` * `int` gives us `int` — did they change the rules?

**Comment by mintty** [comment]
I said
> About the emoji check, if it did not complain 3 lines above, with the same scenario ...

Actually, it's not quite the same, as the affected line refers to a packed struct. However, the warning description says it's about "when the address of packed member of struct or union is taken" which is not the case here (rather an address is read from the struct). So it is a gcc bug.

**Comment by avih** [comment]
> did they change the rules?

I don't think so. See https://stackoverflow.com/a/50632/3339341

**Comment by avih** [comment]
> Actually, msys gcc version is also still 7.4.0...

Is msys still maintained? and dows mintty works with it?

I thought mintty only works with cygwin and derivatives (msys2 is a derivative), and WSL.

**Comment by mintty** [comment]
> Is msys still maintained? and does mintty works with it?

I used msys as shorthand for msys2, but in fact, yes, mintty also still builds on ancient msys; I occasionally spent a few ifdefs to support it, just for fun.

> I thought mintty only works with cygwin and derivatives (msys2 is a derivative), and WSL.

Old msys was a derivative too, of cygwin 1.0. It has gcc 3.4.4.

> And in msys2 updated to gcc 9.1.0.

It installed 7.4.0 for me today...

**Comment by avih** [comment]
> It installed 7.4.0 for me today...

Huh, this is weird. These days I only use cygwin, but still have msys2 installed, and I updated it yesterday and it updated gcc to 9.1.0...

This is more than a week ago https://github.com/msys2/MSYS2-packages/commit/8f1f33aeabf4180cb8fd41a49f4dc0ddca08ba42

**Comment by mintty** [comment]
Have you configured an alternative msys2 repo?

**Comment by avih** [comment]
Nope. I ran `pacman -Syuu`, which I do once in a while for full update.

**Comment by mintty** [comment]
Tweaks uploaded.

**Comment by avih** [comment]
Confirmed, the build now succeeds with msys2. Thanks.
