### ISSUE TITLE
allow multiple modifiers for scrolling, disjunctive version

### ISSUE THREAD

**Issue by cjfp** [mintty/mintty#894]
This is related to #367 except that I would to be able to do either Shift-PgUp/PgDn or Ctrl-PgUp/PgDn, i.e. I would like mintty to respond as if both ScrollMod=1 and ScrollMod=4 were enabled at once, as opposed to the behavior of ScrollMod=5 where both Shift and Ctrl must be held down for scrolling to work.  The interface change could be to use checkboxes instead of radio buttons.  Further, a radio button to select "any of the above" or "all of the above" could be used to control or / and requirements.

**Comment by mintty** [comment]
Implemented part of this request: You can now specify an arbitrary combination of all 6 modifier keys as the (only) scrolling modifier combination.
![image](https://user-images.githubusercontent.com/12740416/61632806-00c8bd80-ac8e-11e9-9baa-e6dd4625b422.png)

No alternatives, though. Yet; but not sure whether that's desirable.

**Comment by cjfp** [comment]
Thank you.  As far as I understand, so far this provides an interface for #367.

To clarify, there are two reasons I want both Shift and Ctrl scrolling
enabled.  First, my other terminal emulator iTerm2 allows for both and
I'm used to it.  Second, I switch between a standard layout keyboard
and a Kinesis Essential ergonomic contoured keyboard.  On the first
keyboard Shift and Ctrl are really close, but on the Kinesis they're
really far apart.  Furthermore the Shift key on the Kinesis is where
the Ctrl key is on a regular keyboard, at the bottom left and bottom
right. One-handed scrolling is only reasonable on the Kinesis with
Ctrl, but if both hands are on the keyboard then Shift scrolling feels
more natural.

![](https://www.ergocanada.com/images/kinesis_essential.jpg)

In the end, switching between keyboards just ends up confusing me, and
the alternative key combinations aren't being used for anything else,
which means they just produce unwanted characters at the terminal when
I accidentally type them.  I suppose this could be considered an
accessibility request.

**Comment by cjfp** [comment]
Thank you.  As far as I understand, this provides an interface for #367.

To clarify, there are two reasons I want both Shift and Ctrl scrolling enabled.  First, my other terminal emulator iTerm2 allows for both and I'm used to it.  Second, I switch between a standard layout keyboard and a Kinesis Essential ergonomic contoured keyboard.  On the first keyboard Shift and Ctrl are really close, but on the Kinesis they're really far apart.  Furthermore the Shift key on the Kinesis is where the Ctrl key is on a regular keyboard, at the bottom left and bottom right. One-handed scrolling is only reasonable on the Kinesis with Ctrl, but if both hands are on the keyboard then Shift scrolling feels more natural.

In the end, switching between keyboards just ends up confusing me, and the alternative key combinations aren't being used for anything else, which means they just produce unwanted characters at the terminal when I accidentally type them.  I suppose this could be considered an accessibility request.

![](https://www.ergocanada.com/images/kinesis_essential.jpg)

**Comment by mintty** [comment]
I am open to consider this but your argument isn't really convincing.
As I understand, you could easily adapt to using Ctrl on both keyboards.
Accessibility isn't a point here either, because that does not mean support of frequent switching between more accessible and normal devices.

**Comment by cjfp** [comment]
Okay, I tested things more carefully.  Either Shift or Ctrl is easy for me to use on a regular keyboard.  On the Kinesis, it's different.  There are eight possibilities: one or two hands, Shift or Ctrl, Up/Dn or PgUp/PgDn.

1-handed Shift-Up/Dn: difficult
1-handed Ctrl-Up/Dn: difficult
1-handed Shift-PgUp/PgDn: almost impossible
1-handed Ctrl-PgUp/PgDn: easy

2-handed Shift-Up/Dn: easy
2-handed Ctrl-Up/Dn: awkward
2-handed Shift-PgUp/PgDn: awkward
2-handed Ctrl-PgUp/PgDn: awkward

1-handed Shift-Up/Dn and Ctrl-Up/Down are difficult because I'm left-handed and I have a nerve injury in my right hand.  Otherwise they would probably be fine.

The Kinesis keyboards are great for reducing RSI pain, but they aren't portable and they don't work in all situations, so I end up using normal ones too.  It's the kind of thing where if you use one 50% of the time it still makes a difference.

If it's too much work I can probably figure out how to do this with AutoHotKey.  Regardless, the discussion has been helpful, I wasn't exactly aware of what worked for me before and what didn't.  Thanks for your time, and for the software.

**Comment by cjfp** [comment]
Hi again.  I fixed my problem with AutoHotKey.  My solution is here in case it's helpful:

https://pastebin.com/raw/HTsvvYUx

Whether you want to close the issue or leave it open, I'm fine either way.

**Comment by mintty** [comment]
That makes me think of another solution which I didn't consider before:
The scroll functions can be made user-definable (with option `KeyFunctions`); I'll work that out.

**Comment by mintty** [comment]
Configuration example:
```
KeyFunctions=C+KP_Prior:scroll_pgup;S+KP_Prior:scroll_pgup;\
	C+KP_Next:scroll_pgdn;S+KP_Next:scroll_pgdn
```

**Comment by mintty** [comment]
Released 3.0.3.

**Comment by cjfp** [comment]
I tried adding:

    KeyFunctions=C+KP_Prior:scroll_pgup;S+KP_Prior:scroll_pgup;\
	    C+KP_Next:scroll_pgdn;S+KP_Next:scroll_pgdn

to .minttyrc in version 3.0.3 but it doesn't work; whatever ScrollMod is set to is what controls scrolling.  On the other hand AutoHotKey is working fine for me; I'm just following up since I filed the issue.

**Comment by mintty** [comment]
It works for me. The ScrollMod-defined combination works in addition.
