### ISSUE TITLE
Tek 401x Emulation Project Code Available and Licence Compatible

### ISSUE THREAD

**Issue by BrianInglis** [mintty/mintty#896]
Possibly useful project basis for adding high quality [Tek 401x](https://github.com/rricharz/Tek4010) emulation to mintty, if someone was interested in porting this across to mintty, as their GPL3 licences are compatible. 
Emulator is being used as a terminal for old CPU, OS, and program emulations that required Tek 401x vector graphic screens. 
See also articles with other links on [Raspberry Pi blog](https://www.raspberrypi.org/blog/historical-high-resolution-graphics-on-raspberry-pi/), [RPi Forum](https://www.raspberrypi.org/forums/viewtopic.php?p=1473632), [Tekscope mag](http://w140.com/tekwiki/images/f/f9/Tekscope_1972_V4_N4_Jul_1972.pdf), and [quote at top of article](http://old.carto.net/papers/svg/index_e.shtml).

**Comment by mintty** [comment]
Thanks, I had just recently considered that, to become fully compatible with xterm.
I don't think I can drive that myself but any porting plans are welcome and will receive cooperation.

**Comment by Biswa96** [comment]
Can you point out the features than can be ported to mintty from Tek401x?

**Comment by mintty** [comment]
I would check how modular that code is. Hopefully image construction and rendering (via X I assume) are well separated.
I would take the command interpretation (ESC sequence etc) and the rendering code and generate an internal image at Tek native resolution (of 4096 x 3072 pixels as I understand). The image can be stored/managed like Sixel images, or as one separate Tek image. The image would then be displayed and scaled to the actual terminal window size.

**Comment by mintty** [comment]
Alternative approach: store the Tek data in a raw format, render and scale to terminal window on demand. This has the advantage that native Windows font output can be used, for better text appearance and full Unicode support.

Also, I would try to leave the used modules from that library unmodified if possible, for easy integration of later updates. I would not try to port feature-wise.

**Comment by mintty** [comment]
Having taken a look at that code, it might as well be easier to reimplement from scratch, provided that Tek specs can be found...

**Comment by mintty** [comment]
@larsbrinkhoff, thanks for offering adaptation/integration support of the Tek4010 code into mintty.
Should we discuss details in this issue or shall I open an issue there?

**Comment by larsbrinkhoff** [comment]
I'm not sure whether @rricharz would be in favour of doing the changes necessary to his Tek4010 project, in which case it would be more appropriate here.

**Comment by BrianInglis** [comment]
What about offering Tek4010 as a separate Cygwin/X package that mintty can invoke, or that can use mintty as "transport" like it uses telnet, rsh, and serial, although I am unclear on the details of how that works? 
I built Tek4010 from github with cygport and a couple of minor patches for a conditional include and brain dead install rules and scripts, and it seems to run okay under Cygwin/X. 
I can post it on my Google drive for testing, and maybe also a Cygwin ITP, once I get the miscellaneous files packaging straight. 
Given that Tek4010 is written to gtk3 API, and mintty is written to Windows API, without any intermediate windows packaging layers, means there is a lot of GUI porting effort on one side, the other, or both.

**Comment by rricharz** [comment]
If anybody wants to implement a Tektronix 4010/4014 decoder from scratch, the Tektronix 4014 user and maintenance manuals are online and contain all details. And a lot of data to test such a decoder is in my tek4010  github repo. This would probably be a 1 month full time project, because the tektronix code is very complex. I am not going to do that myself, but I am willing to answer questions.

**Comment by mintty** [comment]
Brian, I don't see a point in combining Tek4010 as a standalone X program with mintty which doesn't use X. The idea is to have Tek inside mintty and use the Tek4010 library to that aim.
@rricharz, thanks for the offer to support on questions; I would have estimated ~1 month as well, the docs are quite obscure, but that's not an option for me.
I guess with the offer from @larsbrinkhoff to support on adaptations of Tek4010, time needed will be significantly smaller. I had outlined my idea about necessary tasks in rricharz/Tek4010#24.

**Comment by larsbrinkhoff** [comment]
@mintty, is there any way to run mintty on Linux?  Perhaps using Wine?

**Comment by mintty** [comment]
Never tried in Wine. What would be the benefit?

**Comment by larsbrinkhoff** [comment]
I don't have anything running Windows, so the benefit would be that I could test a Tektronix decoder against mintty.  But it sounds like that's not an option, so I would have to do my own vector rendering component.

**Comment by mintty** [comment]
It should be an Option.

**Comment by BrianInglis** [comment]
Cygwin and Wine have been cooperating for a while so mintty should run under recent Wine. 
If there are issues, report on the Cygwin mailing list and in the Wine Bugzilla. 
If you do so, please also suggest any other Cygwin issues be reported on the Cygwin mailing list, to improve Cygwin under Wine.

**Comment by mintty** [comment]
Pre-alpha Tek support is running in mintty, implemented from scratch.

**Comment by mintty** [comment]
Tek mode is now almost ready (something might be done about aspect ratio handling).
The only Tek screen features missing are write-through mode and GIN mode, mainly because I don't know how I could test them. Does anybody know some software that would use these modes?

**Comment by mintty** [comment]
@larsbrinkhoff, thanks for offering support with the other project, but it was really a fun endeavour to implement this from scratch now. Your testing and comments will be welcome.

**Comment by larsbrinkhoff** [comment]
The only Tektronix application I have readily available is Macsyma, but it doesn't use either GIN or write-through.

**Comment by mintty** [comment]
Released 3.3.0 with Tektronix 4014 emulation.

**Comment by mintty** [comment]
Released 3.4.7 with a bunch of fixes and tweaks.

**Comment by larsbrinkhoff** [comment]
Thanks for the update.  I'm reading the list of changes, and I see many subtle tweaks.  Since you have done all this work, do you have a collection of documents about Tektronix graphics, test cases, diagnostics, quirky applications?

**Comment by mintty** [comment]
Manuals:
https://vt100.net/docs/vt3xx-gp/chapter13.html
https://vt100.net/manx/details/5,5479
My collection of test files:
[tekplot.zip](https://github.com/mintty/mintty/files/6155014/tekplot.zip)

**Comment by mintty** [comment]
And some additional test files that I tuned specifically to the issues I noticed and handled:
[tektest.zip](https://github.com/mintty/mintty/files/6155065/tektest.zip)

**Comment by mintty** [comment]
Note that mintty also supports "writethru" and "defocused" modes and the write beam glow (xterm does not support those).
For writethru and defocused, colour indication can be configured. Defocused beam mode is also indicated by boldening.
Tek text font can be configured dynamically (OSC 50) and text output supports Unicode.
I'd still like to find a program that makes use of GIN mode other than vttest...

**Comment by larsbrinkhoff** [comment]
Thanks!
