### ISSUE TITLE
Mintty Printer Feature

### ISSUE THREAD

**Issue by konrad-schwarz** [mintty/mintty#897]
So I'd expect the Unix `sh` command
`{ tput mc5 && cat my_file.ps; tput mc4; }`
to output a Postscript file on a host (windows) printer -- possibly as source code, but it isn't printing at all; nothing ever shows up in the Windows printer queue.

`tput mc5 | od -c` results in

> 0000000 033   [   5   i
> 0000004

which looks right.  The Mintty option Terminal/Printer is not set to `None (printing disabled)`.

What am I doing wrong?

**Comment by mintty** [comment]
You need to configure the printer in the Options dialog, pane Terminal, popup selection Printer. What's your printer setting; does that printer work?
Note this feature is not intended for printing of arbitrary files, but terminal text output. A PostScript file would be printed as PostScript source code...

**Comment by konrad-schwarz** [comment]
I think I did all those things.

Our office’s big multi-function printer has automatic printer language detection, I tested this by using Windows lpr to print a Postscript file; however, you may be right that this is defeated when the standard Windows printer driver is used.

It may be that I messed up the Windows print queue for that particular printer -- I detected this only today (although I submitted the mintty ticket today, my attempts with the media copy control codes stem from last week.)

Basically I just wanted to ensure that the
tput mc5 && cat my_file; tput mc4
sequence was correct.

It would be really cool if the media copy codes worked to print e.g. Postscript files, because then I would no longer need to set up printers on the various virtual machines I use and could easily print from remote machines.  A cursory examination of https://docs.microsoft.com/en-us/windows-hardware/drivers/print/introduction-to-print-processors shows that besides Enhanced Metafile (EMF – GDI based imaging) and TEXT (basically ASCII rendered in some default font via GDI), the MS print processors also support RAW (my usage case – printer figures out what the data means) and PSCRIPT1 printer “data types”.   I expect a terminal emulator like mintty to use TEXT; but it would be neat if you could select the RAW or PSCRIPT1 data type instead via the mintty options dialog.  If I had to choose only one, the Microsoft documentation sounds like RAW could handle plain ASCII, with conventional interpretation of ASCII format-effecting control codes (CR, NL, FF, TAB, ...) – probably by the printer itself.

**Comment by konrad-schwarz** [comment]
I just re-checked this with different windows printers: it does not look like the media copy feature works.  Output to the terminal is suppressed after ESC [ 5 i and turned back on after ESC [ 4 i, but nothing is printed on my machine, regardless of which printer I set in the options dialog.

From: Schwarz, Konrad (CT RDA IOT SES-DE)
Sent: Monday, August 5, 2019 1:38 PM
To: mintty/mintty <reply@reply.github.com>; mintty/mintty <mintty@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [mintty/mintty] Mintty Printer Feature (#897)

I think I did all those things.

Our office’s big multi-function printer has automatic printer language detection, I tested this by using Windows lpr to print a Postscript file; however, you may be right that this is defeated when the standard Windows printer driver is used.

It may be that I messed up the Windows print queue for that particular printer -- I detected this only today (although I submitted the mintty ticket today, my attempts with the media copy control codes stem from last week.)

Basically I just wanted to ensure that the
tput mc5 && cat my_file; tput mc4
sequence was correct.

It would be really cool if the media copy codes worked to print e.g. Postscript files, because then I would no longer need to set up printers on the various virtual machines I use and could easily print from remote machines.  A cursory examination of https://docs.microsoft.com/en-us/windows-hardware/drivers/print/introduction-to-print-processors shows that besides Enhanced Metafile (EMF – GDI based imaging) and TEXT (basically ASCII rendered in some default font via GDI), the MS print processors also support RAW (my usage case – printer figures out what the data means) and PSCRIPT1 printer “data types”.   I expect a terminal emulator like mintty to use TEXT; but it would be neat if you could select the RAW or PSCRIPT1 data type instead via the mintty options dialog.  If I had to choose only one, the Microsoft documentation sounds like RAW could handle plain ASCII, with conventional interpretation of ASCII format-effecting control codes (CR, NL, FF, TAB, ...) – probably by the printer itself.

**Comment by mintty** [comment]
Just reproduced (with printer set to a CutePDF Writer or PDFCreator), it works fine here, for text.

**Comment by konrad-schwarz** [comment]
Thank you – I still can’t get it to work, even with a text file.  Looks like a problem on my machine.

**Comment by mintty** [comment]
Maybe printing can be restricted with access rights by Windows policy profiling?

**Comment by konrad-schwarz** [comment]
I couldn’t find any enabled printer-related restrictions in the Windows Group Policy Editor on my machine.  All such settings were “not configured”, both in the Computer and in the User Configuration folders.   So that doesn’t seem to be it.  (I fail to see the security utility of restricting printing to certain programs anyhow.).

Thanks again.

**Comment by mintty** [comment]
Please run another mintty instance from the terminal command line and retry.
It may be a PATH problem, only affecting a mintty instance started from a shortcut, as mintty uses notepad for printing.

**Comment by konrad-schwarz** [comment]
Hmm, notepad definitely won’t print postscript files as postscript.

If I ever got off my lazy ass, would you accept a patch that would (probably) use the Windows Print Spooling API to implement the media copy command?

**Comment by mintty** [comment]
Let's take the issues apart:
* For text files, does it work for you in a mintty instance invoked "manually" (from a cygwin command line)?
* If you know how to serve the Windows print API, I'll appreciate a patch. I just didn't feel like investigating in yet another of those insanely over-complex Windows APIs at the time, so I involved notepad.
* If the Windows print API would magically detect PostScript (by its initial line), I guess that'll be OK. Otherwise and in general this is not really how the legacy terminal print feature would work.

Also, I'd like to link to the somewhat related request to redirect print output to the clipboard (#815).

**Comment by konrad-schwarz** [comment]
1.  Yes, it works for a mintty instance invoked from the Cygwin command line – looks like your premonition regarding PATH was correct



  1.  It be new for me, too.  I’ve just been poking around e.g. https://docs.microsoft.com/en-us/windows/win32/printdocs/openprinter

I think the sequence would be something like

OpenPrinter , PrinterName at the user’s discretion

StartDocPrinter, DOC_INFO_1.DataType is set to “TEXT”, “RAW” or “PSCRIPT1” at the user’s discretion



WritePrinter ...



EndDocPrinter

ClosePrinter



You could probably leave out StartPagePrinter/EndPagePrinter



  1.  Actually, I think this is exactly how the legacy print feature would work: if you had a HP-GL plotter attached to your terminal’s printer port, it would start drawing given HP-GL codes (I don’t know if any HP plotters actually had a serial interface).  The same thing obviously goes for HP PCL, Postscript, or EPSON ESC/P – except that it probably was not common to attach a Postscript or PCL capable printer to an individual’s terminal.

Now, on the integrated printer of a VT-52 you probably could only mirror the screen contents, similar to what mintty does now, but you can attach any printer with a serial interface to a VT-102’s printer port.

**Comment by konrad-schwarz** [comment]
BTW, a printer’s print processors can be found with EnumPrintProcessor, and EnumPrintProcessorDatatypes returns the printer DataTypes, as described here: https://docs.microsoft.com/en-us/windows-hardware/drivers/print/introduction-to-print-processors

**Comment by mintty** [comment]
[could you try to respond without quoting the previous comment? so I don't have to delete the waste from every comment...]

**Comment by mintty** [comment]
Uploaded a fix for the PATH dependency.

**Comment by mintty** [comment]
Released 3.0.3.
