### ISSUE TITLE
Copy as HTML: "float: left" causes issues

### ISSUE THREAD

**Issue by mscha** [mintty/mintty#900]
The CSS used in “Copy as HTML” (mintty 3.0.2) contains:

    #vt100 {
        ...
        float: left;
    }

This messes up the layout of the text you're pasting this into.  For example:

Before paste:
![image](https://user-images.githubusercontent.com/227365/62613172-3960cc00-b909-11e9-96ac-d1953a09e6df.png)

After paste:
![image](https://user-images.githubusercontent.com/227365/62613300-7dec6780-b909-11e9-90ca-ab838d4c08dd.png)

Can you please remove the `float: left;` from the CSS?

**Comment by mintty** [comment]
According to a source comment, there used to be a reason for this, but I cannot reproduce it anymore.
Dropped.

**Comment by mintty** [comment]
Released 3.0.3.
