### ISSUE TITLE
Load font from storage?

### ISSUE THREAD

**Issue by Merith-TK** [mintty/mintty#901]
Basically, i want to install a font into my msys system, and have mintty load said font without it being installed on the Windows PC, this is useful because i intend on taking my msys2 setup with me to my school. where i wont have Adminperms, or even cmd.exe shell access. I plan on storing the font in `/opt/fonts/hack.ttf`

**Comment by mintty** [comment]
I see the use case but by the paradigm of Windows and considering that mintty is a Windows application, fonts needs to be installed in Windows. There is hardly a way to change this. Rather than using Windows font rendering, you would have to integrate some 3rd-party font rendering engine (e.g. Pango) and then output graphics instead of text, which might make output considerably slower in addition.

**Comment by mintty** [comment]
Maybe you'd like to try https://www.no-nonsens.nl/temporary-font-manager/.

**Comment by Biswa96** [comment]
Warning: Before doing anything in school pc ask teachers first. I've learnt it from past.

**Comment by Merith-TK** [comment]
Nah, the teachers dont know shit really. Only two staff in the DISTRICT i
would ask first
The School Computer Science teacher, (could work for District IT if he
wished)
And the District Head of IT, Whom we email back and forth consistently.
Simply because he likes keeping tabs on the technologically advanced
students.
—Merith

**Comment by Merith-TK** [comment]
@mintty that font loader actually appears to work. Going to send it to my District IT to see if it able to be used on the locked down system

**Comment by mintty** [comment]
For the library approach, https://en.wikipedia.org/wiki/Category:Text_rendering_libraries lists some that might be suitable, in theory.

**Comment by Merith-TK** [comment]
okay, that label `Difficulty-Insane` is pretty funny

**Comment by mintty** [comment]
Actually, this turned out to be much easier, using Windows function AddFontResourceEx.
Introduced new configuration subfolder `fonts` to drop dynamic fonts.
A portable installation would need to provide its config tree and set it in the invocation via command line parameter `--configdir`.

**Comment by Merith-TK** [comment]
Wouldnt it be easier to read minttyrc file from the default location? 

AS i generally use mintty with msys2, and [PortableAppsPlatform](https://portableapps.com), the latter does not support per app command arguments

**Comment by mintty** [comment]
There are multiple default locations. The $APPDATA/mintty location is not portable. The /usr/share/mintty location can be used, of course, as a portable invocation will create its own portable cygwin environment. I'll adapt the docs.

**Comment by Merith-TK** [comment]
alright, thanks for the information,

**Comment by mintty** [comment]
Actually, my comment above wasn't well-crafted but the docs are OK. I could mention /usr/share/mintty explicitly in the wiki Tips file in case that's not obvious.

**Comment by Merith-TK** [comment]
Yeah, that would be a good idea, definately would bring more awareness to this new feature

**Comment by mintty** [comment]
Released 3.4.1.
