### ISSUE TITLE
Unable to use ReadConsoleInputW from mintty

### ISSUE THREAD

**Issue by gbraad** [mintty/mintty#906]
For several applications we use a library called Survey (Golang) to deal with reading runes and replacing them with `*` (to hide sensitive information). However, this seems to fail from mintty (eg. gitbash) but not from Cmd or any other native terminal. The error returned is `Incorrect function`.

**Comment by Biswa96** [comment]
Any sample C/C++ code?

**Comment by Biswa96** [comment]
Any sample C/C++ code? The standard handles are pipes in cygwin realm.

**Comment by gbraad** [comment]
We have this in Golang https://github.com/AlecAivazis/survey/blob/4de88574e78145bdcfa6627ed766564231588b31/terminal/runereader_windows.go#L94

I do not remember this being an issue on Cygwin, but I'll verify

**Comment by mintty** [comment]
This may *possibly* (no promise) improve with ConPTY integration in cygwin, now available in test release 3.1.0.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support. Please recheck.
