### ISSUE TITLE
Problem with /b handling

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#910]
In order to reproduce the problem resize a terminal to 80 columns, next enter:

echo -e "\e[2J"
echo -e "\e[1;79Hx\b\vx\b\vx\n"
echo -e "\e[5;80Hx\b\vx\b\vx\n"

Mintty doesn't correctly handle \b on the right most column.

**Comment by mintty** [comment]
This behaviour is weird but correct.
It is related to the pending auto-wrap state of DEC terminals, which is cancelled by backspace.
Compare xterm.
You may also want to check mintty setting `OldWrapModes` but note the old behaviour is no compatible with DEC terminals and xterm.

**Comment by scandum** [comment]
Guess I should have double checked. I'll see if I can get this sorted out with Thomas Dickey as most terminals interpret this as 1 backspace instead of 2.

**Comment by mintty** [comment]
It's not 2 backspaces because after the 'x' in column 80, the cursor remains in column 80, on the 'x', as there is no column 81. That is the pending wrap position. Backspace from there goes back to column 79, ignoring the pending wrap state.
