### ISSUE TITLE
tmux pane borders rendering is off

### ISSUE THREAD

**Issue by antoineco** [mintty/mintty#911]
mintty 3.0.2

`tmux` panes borders are not rendered correctly in a `wsltty` terminal (Debian distro), regardless of the font used (tested with Fira Code, Source Code Pro and Deja Vu Sans Mono, which all support those characters).

* Vertical borders are invisible until the pane is switched, and the first column is covered by the border.
* Horizontal borders are visible immediately, but dashed and require two lines, also covering the first row. (note: this can also be observed in the output of [`bat`](https://github.com/sharkdp/bat))

The issue does not occur through the Windows Console wrapper (`debian.exe`).

![mintty_tmux_vert](https://user-images.githubusercontent.com/3299086/64869024-caca0900-d640-11e9-9927-59e190a991c3.png)
![mintty_tmux_hori](https://user-images.githubusercontent.com/3299086/64869025-caca0900-d640-11e9-9486-6f0c14e149ed.png)

**Comment by mintty** [comment]
For me, pane borders look fine. Please provide a reproducible test case. Not like "do something with tmux and look out for a pane border" but clear instructions for the non-daily tmux user. Best would be a screen log (to output with `cat` to demonstrate the issue).
Also, does the issue behave differently for you with a previous version?

**Comment by antoineco** [comment]
I haven't tried a previous version because I am using Windows for the first time with such setup (non-Unix terminal + WSL)

**Comment by mintty** [comment]
Debian does not have tmux installed by default.
Just ran tmux in Ubuntu and pane borders are fine.

**Comment by antoineco** [comment]
Thanks for verifying on your side, you indirectly pointed me in the right direction.

I checked my mintty configuration file and it had `Charwidth=ambig-wide` set in attempt to fix #892. Because I installed `tmux` only _after_ investigating that other issue, I didn't immediately see the correlation with that option.

Sorry for the noise! Problem solved 👍

**Comment by mintty** [comment]
Ah, right, Charwidth=ambig-wide is really just a compatibility option and most programs are confused by it.
