### ISSUE TITLE
Resizing back from full window detaches the size popup

### ISSUE THREAD

**Issue by Biswa96** [mintty/mintty#913]
To reproduce, make mintty in full window then drag it down by grabbing the tittle bar. Here is the screenshot:

![Capture](https://user-images.githubusercontent.com/31443074/64922212-25529900-d7ea-11e9-9acd-18616eb3e391.PNG)

**Comment by mintty** [comment]
But it vanishes as soon as you release the mouse. I'd say it's a harmless artefact but I'll look whether it can be changed easily.

**Comment by Biswa96** [comment]
Now its completely removed.

**Comment by mintty** [comment]
The use case for the popup is interactive resizing, not restoring from full-screen, so I think I'll leave it as it is now.

**Comment by Biswa96** [comment]
Though the issue is fixed I want to tinker something with that popup. Can you provide the source file name and functions name which show that popup? The popup does not blend with mintty window.

**Comment by mintty** [comment]
In wintip.c, functions win_show_tip and win_destroy_tip.

**Comment by mintty** [comment]
Released 3.0.3.
