### ISSUE TITLE
Unicode character squished at certain font size

### ISSUE THREAD

**Issue by ksalman** [mintty/mintty#914]
I am trying to display this character https://unicode-table.com/en/2717/ using FiraCode font. The character displays fine at certain font size but not all, where it gets squished, vertically. 

Here is how it looks at the font size I typically use, which happens to be 11pt
![image](https://user-images.githubusercontent.com/1268871/64932959-52597880-d7f7-11e9-8ac0-db379ed6361d.png)

When I increase the font size to 13pt, it displays properly. But notice, another character, which is https://unicode-table.com/en/25CB/, is now squished.
![image](https://user-images.githubusercontent.com/1268871/64932999-90569c80-d7f7-11e9-841f-408e78a85d66.png)

I see similar issues when trying another font, Consolas, where X character is squished. Though in this case when I increase the font size until X is displayed properly, the circle character is also displaying properly. 

I am using mintty 3.0.2 on Windows 10, at 1920x1200 resolution.

**Comment by ksalman** [comment]
Looks like there is a previous issue that this is a duplicate of https://github.com/mintty/mintty/issues/892

**Comment by antoineco** [comment]
I use the same font and have the same rendering issue. The current `master` branch has a new option `CharNarrowing` that solves it, if you want to give it a shot.
