### ISSUE TITLE
mintty 3.0.2 can not start on windows 7.

### ISSUE THREAD

**Issue by linux2014linux** [mintty/mintty#917]
I try run mintty on windows 7. It can not work. Mintty usage of memory always increase to process is killed.
![2019-09-25_175244](https://user-images.githubusercontent.com/7777721/65590819-fee8e680-dfbd-11e9-9cf1-f4fa7748e480.png)

**Comment by mintty** [comment]
I run mintty daily on Windows 7. Your screenshot shows it's actually MSYS2 terminal, which is a patched version of mintty. So maybe you should report to MSYS2. Is that MSYS2 64 bit you are running?
You can try to download and compile mintty yourself and see how that works.

**Comment by linux2014linux** [comment]
To https://github.com/msys2/MINGW-packages/issues/5815.

**Comment by Biswa96** [comment]
@mintty You can check this folder for any possible issue https://github.com/msys2/MSYS2-packages/tree/master/mintty.

**Comment by mintty** [comment]
> You can check this folder for any possible issue

Thanks, but if there is any trouble with their launcher, someone else should analyse it.

@linux2014linux, is that with pure MSYS2 or Git Bash? Can you compare with any other mintty installation (either self-compiled, or with cygwin)? Do you do anything unusual in your startup scripts (like displaying graphics in the terminal...)?

**Comment by linux2014linux** [comment]
@mintty Yes, I run mitty by clicking git-bash.

**Comment by mintty** [comment]
You are not supposed to start mintty directly from its folder in Git for Windows. Run it from the Start menu entry "Git Bash".

**Comment by linux2014linux** [comment]
@mintty Same information.
![2019-09-29_110907](https://user-images.githubusercontent.com/7777721/65825466-ca20ac00-e2a9-11e9-8e2a-a7f302e0a2b8.png)

**Comment by mintty** [comment]
> Can you compare with any other mintty installation (either self-compiled, or with cygwin)?

Please try to install MSYS2 and retry. 32bit or 64bit?

> Do you do anything unusual in your startup scripts (like displaying graphics in the terminal...)?

**Comment by linux2014linux** [comment]
@mintty Mintty is auto installed when I install git for windows. How should I replace mintty? Can I replace mintty of git-bash to my self-compiled mintty?

**Comment by mintty** [comment]
That's why I asked to install another system, either plain MSYS2 or cygwin, to compare.

**Comment by linux2014linux** [comment]
@mintty I installed MSYS2. The mintty is OK.

**Comment by mintty** [comment]
Thanks. Does it have 3.0.6 already?

**Comment by linux2014linux** [comment]
@mintty msys2-x86_64-20190524.exe. The mintty.exe information is as follows.
![2019-10-08_162727](https://user-images.githubusercontent.com/7777721/66379818-cd721100-e9e8-11e9-894c-7d1a7aa70fb7.png)

**Comment by mintty** [comment]
What if you update MSYS2 to 3.0.5 (`pacman -Syu`), then place that into git-bash?
Or later (when they release it) with 3.0.6?

**Comment by linux2014linux** [comment]
@mintty I update MSYS2 to 3.0.5. I replace git-bash's mintty.exe to MSYS2's mintty.exe(3.0.5). It still does not work. I directly start mintty of MSYS2's directory, it works. But replaced mintty.exe(3.0.5) of git-bash's directory does not work.

**Comment by mintty** [comment]
Did you report it to Git for Windows?

**Comment by linux2014linux** [comment]
@mintty I will try report it to git.

**Comment by mintty** [comment]
Marking invalid and closing as this was redirected to the Git project.
