### ISSUE TITLE
3.0.3 renders U+2500 (horizontal line) incorrectly

### ISSUE THREAD

**Issue by avih** [mintty/mintty#918]
Run the following test script:
```sh
#!/bin/bash

stty size | {
    read rows cols
    for x in `seq $cols`; do
        printf "\u2500"
    done
    echo
}
```

Expected result: horizontal line spanning the full width of the terminal.

Actual result: looks like spaced dashes, and it's shorter than expected.

This works in mintty 3.0.2 but not in 3.0.3, and affects e.g. `tmux` which uses such lines between panes.

I use the font Consolas.

**Comment by avih** [comment]
BTW, I noticed that you added some auto-narrowing functionality. FWIW, glyphs which should span the cell edge-to-edge (like U+2500) are typically wider/higher than the cell, such that they align well and without gaps regardless of different cell spacing.

Maybe the heuristics detects that the glyph is "too wide" and narrows it instead of clipping it? Regardless though, even if it does narrow it, it seems that the renders are not aligned to the cell boundaries, because N such consecutive glyphs end up shorter than the width of N cells.

**Comment by mintty** [comment]
Released 3.0.4.

**Comment by Biswa96** [comment]
This also fixed the horizontal separation line in tmux.

**Comment by avih** [comment]
Thanks.
