### ISSUE TITLE
High chance not able to start if using shortcut

### ISSUE THREAD

**Issue by GongT** [mintty/mintty#920]
I'm using mintty in cygwin.

I have created many shortcut on desktop, with argument like `C:\cygwin64\bin\mintty.exe -e /bin/bash --login -c "/bin/ssh -tt root@serverXXXX"`.

These works perfect for many years.

About few month ago, I update cygwin with setup.exe, and these shortcuts becomes "unstable", it have about 80% chance to crash and not start.    
Crash happens by double click shortcut, or press Alt+F2 in an existing window. (do not crashing old window, but new one not start)

Now I always click icon or press Alt+F2 many times to open a new window.

It never crash when click `mintty.exe` or use `Cygwin64 Terminal.lnk` *(C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -)    *
And I have tested paste shortcut argument into cmd, it seems not crashing.

I updated cygwin again, and this problem didn't go away.

Every time it not start, a new stackdump will generate on my desktop:
[mintty.exe.stackdump.zip](https://github.com/mintty/mintty/files/3667598/mintty.exe.stackdump.zip)
[mintty.exe.stackdump.zip](https://github.com/mintty/mintty/files/3667604/mintty.exe.stackdump.zip)
[mintty.exe.stackdump.zip](https://github.com/mintty/mintty/files/3667605/mintty.exe.stackdump.zip)

**Comment by mintty** [comment]
What if you drop the extra shell level:
`C:\cygwin64\bin\mintty.exe -e /bin/ssh -tt root@serverXXXX`
?
Also, please install package mintty-debuginfo from setup category "Debug" and recreate the stackdump.

**Comment by GongT** [comment]
I can not drop bash because I need "--login" to read profile before actual start ssh.

After I install mintty-debuginfo, the lnk still not work, but stackdump not generated anymore...🤦

**Comment by mintty** [comment]
Try this, just as an unguided experiment:
`C:\cygwin64\bin\bash.exe --login -e /bin/mintty -e /bin/ssh -tt root@serverXXXX`

**Comment by GongT** [comment]
It works. Command is:
> C:\cygwin64\bin\bash.exe --login -c '/bin/mintty -e /bin/ssh -tt root@server'


I found that I can run the lnk file from cmd (not copy 'target' from the lnk), it also not crash.

**Comment by mintty** [comment]
Thanks for the result of the experiment, which is good. Unfortunately I cannot interpret it, i.e. it does not give me a clue why you would have had crashes before.

**Comment by GongT** [comment]
Ok, I got more dump file.
[mintty.exe.zip](https://github.com/mintty/mintty/files/3693025/mintty.exe.zip)

**Comment by mintty** [comment]
Thanks, that gave me a hint. Uploaded a tentative fix.
If you can compile mintty yourself, please check the current repository version.

**Comment by mintty** [comment]
Released 3.0.6.
