### ISSUE TITLE
Unicode glyph width handling

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#922]
`[DIR N               ]  [ 56]  [ \u2191 ]  [ ↑ ]
[DIR NE              ]  [ 57]  [ \u2B08 ]  [ ⬈ ]
[DIR E               ]  [ 58]  [ \u2B95 ]  [ ⮕ ]
[DIR SE              ]  [ 59]  [ \u2b0A ]  [ ⬊ ]
[DIR S               ]  [ 60]  [ \u2193 ]  [ ↓ ]
[DIR SW              ]  [ 61]  [ \u2B0B ]  [ ⬋ ]
[DIR W               ]  [ 62]  [ \u2B05 ]  [ ⬅ ]
[DIR NW              ]  [ 63]  [ \u2B09 ]  [ ⬉ ]`

The drawing of several unicode characters is rather poor in mintty. Especially the west pointing arrow looks more like a blurred dash than an actual arrow. You'll have to paste the above into mintty to see for yourself.

It seems to be more than just a font issue as the arrows display nicely in wordpad. Anything that can be done to improve the situation?

**Comment by mintty** [comment]
This is, not just but, a font issue, and possibly a font fallback issue.
You should at least mention your configured font (and size) for such an issue, and maybe a screenshot.

**Comment by scandum** [comment]
Courier New, 12. 
![image](https://user-images.githubusercontent.com/52607428/66123898-56e9a380-e5e3-11e9-8bf6-4692cbd934d1.png)
 
Left pointing arrow is squished. I've also noticed some double width characters showing as single width, but haven't kept track of the codes.

**Comment by mintty** [comment]
Please use setting `CharNarrowing=100` to compensate.

**Comment by BrianInglis** [comment]
> This is, not just but, a font issue, and possibly a font fallback issue.

The left black arrow is not a glyph in most fonts, although the right black arrow is, and renders anywhere from well to badly. 
Both glyphs exist and render well in **Inconsolata**, okay in **Deja Vu Sans Mono** and **Fira Mono**, but not well in those fonts in `mintty 3.0.2` vanilla with no rendering tweaks. 
⬅  `U+02B05 LEFTWARDS BLACK ARROW`
⮕  `U+02B95 RIGHTWARDS BLACK ARROW`

**Comment by BrianInglis** [comment]
Does `CharNarrowing=100` work only on **`mintty`** later than **`3.0.2`**?

**Comment by mintty** [comment]
Yes.

**Comment by scandum** [comment]
Thanks, that makes a difference in Courier New.

With CharNarrowing set to 100 the tip of the east pointing arrow gets cut off in Consolas, but CharNarrowing=75 appears to strike a decent balance.

**Comment by mintty** [comment]
That's not so far from the current default, 70; maybe I'll tweak that to 80.
Also, I plan to exclude the character ranges U+2190 .. U+2BFF and U+1F000 .. U+1FAFF from auto-narrowing.

**Comment by mintty** [comment]
Released 3.0.6.

**Comment by mintty** [comment]
Some heuristic checking reveals that 75 is a better trade-off than 70 or 80. Adjusting again.
Limiting the procedure to ambiguous-width was an attempt still in the code, commented out, but checking shows it's not good. Double-width characters do not need special attention as they have double room anyway and don't need to be narrowed. Sample file attached.

[x-narrowing.txt](https://github.com/mintty/mintty/files/3824951/x-narrowing.txt)

**Comment by mintty** [comment]
Released 3.1.0.
