### ISSUE TITLE
Add KeyFunction for virtual tabs

### ISSUE THREAD

**Issue by dxhisboy** [mintty/mintty#923]
The virtual tabs feature are very useful, but mintty users, especially wsltty users may come from a variety of desktop environments, their terminals may have different way to switch tabs, for example, `Shift+Arrows` in konsole and `Ctrl+Page Up/Down` in GNOME terminal.
So I think there should be a configurable shortcut for virtual tabs switch function.
I've done the modification in the `wininput.c` to add two `KeyFunction`s: `switch_next`, `switch_prev`, if you don't mind I can initialize a pull request.

**Comment by Biswa96** [comment]
If the change is small we can discuss here. Can you put a sample patch file here?

**Comment by dxhisboy** [comment]
Here is the patch.
Just add two static functions, two doc entry and two KeyFunction definition.
[vt_switch.patch.txt](https://github.com/mintty/mintty/files/3689241/vt_switch.patch.txt)

**Comment by mintty** [comment]
That's a good idea, thank you.
Two issues, though:
* In general, multi-word definable function names have a dash "-" separator, not underscore "_"; please change. The "scroll_" functions are an exception as the suffix is kind of subordinate, and I'm not quite happy with that choice.
* Do you really want to include iconized windows in the feature? Or maybe define 4 functions, for a choice? (e.g. switch-visible-next...)
Also, please use false, true as win_switch parameters.

**Comment by mintty** [comment]
Released 3.0.6.
