### ISSUE TITLE
Cannot start WSL-Ubuntu after the upgrade to 3.0.5 [MSYS2}

### ISSUE THREAD

**Issue by angelog0** [mintty/mintty#924]
After the upgrade to this new version I cannot start WSL (Ubuntu) clicking usual links on Desktop and on toolbar (Really I can start it only from Start or by means of Windows Terminal). What happened?

**Comment by Biswa96** [comment]
Did you see the Windows 10 version requirement in README page?

**Comment by mintty** [comment]
I guess I failed some proper testing with WSL V2 mode, and this may also be due to the env problem (#193). Maybe just very few people use V2 already...
@Biswa96, can you define a new release soon, please, so I'll update wsltty.

**Comment by angelog0** [comment]
They are years (since Anniversary upgrade, I think) I use MinTTY+WS-Ubuntu in this way and doubt the Windows version can help...

Anyway I have W10 Pro 64, updated (`10.0.18362.356`).

BTW, I use MSYS2.

**Comment by angelog0** [comment]
@mintty, I do not use WSL2, just WSL (from the Store). I think WSL2 is experimental and for insider. I am not an insider...

Nothing was changed on my system.

**Comment by angelog0** [comment]
Now I see, [Tips](https://github.com/mintty/mintty/wiki/Tips) you have changed the things. Now you use wslbridge2, but here it does not seem to work.

In MSYS2:

```
cd /tmp
wget https://github.com/Biswa96/wslbridge2/archive/master.zip
aunpack master.zip

cd wslbridge2-master
make
```



In WSL-Ubuntu (from Windows terminal):

```
cd /mnt/c/msys64/tmp/wslbridge2-master
make
```

In MSYS2:

```
cd /tmp/wslbridge2-master/bin
cp wslbridge2.exe rawpty.exe hvpty.exe wslbridge2-backend hvpty-backend /bin
```

Then on the Desktop I created a link with this target:

`C:\msys64\usr\bin\mintty.exe --WSL=Ubuntu -`

(`C:\msys64\bin\mintty.exe --WSL=Ubuntu -` does not work)

If I have understood, that is all I need to do... but it does not work. Clicking the link on desktop (or my old links with target: `C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\angelo\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~`) starts MinTTY in the same way of /msys2_shell.cmd, i.e. it asks which shell to start, msys2, mingw32 or mingw64. See 
![ubuntu-wslbridge2](https://user-images.githubusercontent.com/35931460/66216795-6aba0600-e6c6-11e9-87ff-5d8e9ac26025.png)

**Comment by Biswa96** [comment]
The mintty in msys2 realm is not updated. They wait some days after mintty release in cygwin (for stability). You can compile mintty in msys2.

**Comment by mintty** [comment]
Actually, after updating MSYS2, it has mintty 3.0.5 here, and I can start WSL with it, no problem seen.

**Comment by angelog0** [comment]
@Biswa96, please I do not understand. Today I have update mintty in MSYS2:


$ pacman -Ss mintty
msys/mintty 1~3.0.5-1 (base) [installato]
    Terminal emulator with native Windows look and feel

so do you mean 3.0.5 does not work to start WSL-Ubuntu?

**Comment by Biswa96** [comment]
Oh! I was wrong, I got the update now.

**Comment by Biswa96** [comment]
Oh! I was wrong, I got the update now. Then It should work as usual. Can you wait for one day? I will release a new binary tomorrow.

**Comment by angelog0** [comment]
@mintty, How do you start it? Which wslbridge do you use? The [old](https://github.com/rprichard/wslbridge/releases/download/0.2.4/wslbridge-0.2.4-msys64.tar.gz) or the [new](https://github.com/Biswa96/wslbridge2)? I followed the [Tips](https://github.com/mintty/mintty/wiki/Tips#manual-setup-of-wsl-terminal) and it does not work. I reverted MinTTY to 3.0.2 and it works as expected to start WSL (with the old wslbridge). Reinstalling 3.0.5 does not. In short, 3.0.5 behaves as if no wslbridge were installed.

**Comment by mintty** [comment]
I checked your description above and `mintty --WSL=Ubuntu-18.04` and other distros work fine.
What does `wsl -l -v` tell you?

**Comment by angelog0** [comment]
@mintty, from MinTTY (3.0.2):

```
$ wsl -l -v
Copyright (c) Microsoft Corporation. Tutti i diritti sono riservati.

Sintassi: wsl.exe [Argomento] [Opzioni...] [CommandLine]

Argomenti per l'esecuzione dei file binari di Linux:

    Se non viene specificata alcuna riga di comando, wsl.exe avvia la shell predefinita.

    --exec, -e <CommandLine>
        Esegue il comando specificato senza usare la shell di Linux predefinita.

    --
        Passa la riga di comando rimanente cos� com'�.

Opzioni:
    --distribution, -d <DistributionName>
        Esegue la distribuzione specificata.

    --user, -u <UserName>
        Esegui come utente specificato.

Argomenti per la gestione del sottosistema Windows per Linux:

    --export <DistributionName> <FileName>
        Esporta la distribuzione in un file tar.
        Il nome del file pu� essere   per l'output standard.

    --import <DistributionName> <InstallLocation> <FileName>
        Importa il file tar specificato come nuova distribuzione.
        Il nome del file pu� essere   per l'input standard.

    --list, -l [Options]
        Elenca le distribuzioni.

        Opzioni:
            --all
                        Elenca le distribuzioni, incluse le distribuzioni attualmente
        in fase di installazione o disinstallazione.

            --running
                Elenca solo le distribuzioni attualmente in fase di esecuzione.

    -setdefault, -s <DistributionName>
        Imposta la distribuzione come predefinita.

    --terminate, -t <DistributionName>
        Termina la distribuzione.

    --unregister <DistributionName>
        Annulla la registrazione della distribuzione.

    --upgrade <DistributionName>
        Aggiorna la distribuzione al formato del file system WslFs.

    --help
        Visualizza informazioni sull'utilizzo.
```

From WSL-Ubuntu (in MinTTY 3.0.2 + wslbridge-0.2.4):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Comment by mintty** [comment]
OK, your `wsl` apparently does not support the `-l` option yet. What does `mintty -RW` report?

**Comment by angelog0** [comment]
@mintty, this:

```
$ mintty -RW
WSL distribution name Ubuntu
-- guid {64c48dcd-9a51-4b60-83ce-358ca70c189e}
-- root C:\Users\angelo\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs
-- pack CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
-- icon C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc\images\icon.ico
```

As I wrote, I do not use WSL2, just the default from the Store..

**Comment by mintty** [comment]
And you are not running 3.0.5 as your output tells me.

**Comment by angelog0** [comment]
Because, as I wrote, I reinstalled 3.0.2 which works...

Anyway, from 3.0.5:

```
$ wsl -l -v
Copyright (c) Microsoft Corporation. Tutti i diritti sono riservati.

Sintassi: wsl.exe [Argomento] [Opzioni...] [CommandLine]

Argomenti per l'esecuzione dei file binari di Linux:

    Se non viene specificata alcuna riga di comando, wsl.exe avvia la shell predefinita.

    --exec, -e <CommandLine>
        Esegue il comando specificato senza usare la shell di Linux predefinita.

    --
        Passa la riga di comando rimanente cos� com'�.

Opzioni:
    --distribution, -d <DistributionName>
        Esegue la distribuzione specificata.

    --user, -u <UserName>
        Esegui come utente specificato.

Argomenti per la gestione del sottosistema Windows per Linux:

    --export <DistributionName> <FileName>
        Esporta la distribuzione in un file tar.
        Il nome del file pu� essere   per l'output standard.

    --import <DistributionName> <InstallLocation> <FileName>
        Importa il file tar specificato come nuova distribuzione.
        Il nome del file pu� essere   per l'input standard.

    --list, -l [Options]
        Elenca le distribuzioni.

        Opzioni:
            --all
                        Elenca le distribuzioni, incluse le distribuzioni attualmente
        in fase di installazione o disinstallazione.

            --running
                Elenca solo le distribuzioni attualmente in fase di esecuzione.

    -setdefault, -s <DistributionName>
        Imposta la distribuzione come predefinita.

    --terminate, -t <DistributionName>
        Termina la distribuzione.

    --unregister <DistributionName>
        Annulla la registrazione della distribuzione.

    --upgrade <DistributionName>
        Aggiorna la distribuzione al formato del file system WslFs.

    --help
        Visualizza informazioni sull'utilizzo.
```

and 

```
$ mintty -RW
WSL distribution name Ubuntu
-- guid {64c48dcd-9a51-4b60-83ce-358ca70c189e}
-- flag 7
-- root C:\Users\angelo\AppData\Local\Packages\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc\LocalState\rootfs
-- pack CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc
-- full CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc
-- icon C:\Program Files\WindowsApps\CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc\images\icon.ico
```

**Comment by mintty** [comment]
The "flags" value confirms you don't use WSL V2; sorry for insisting but I have no further clue; except

> your wsl apparently does not support the -l option yet

This actually also tells us you run an older version of Windows. What does `winver` report? (The 4-dibit Version, not the Build.)

**Comment by Biswa96** [comment]
Released new binaries v0.4. You can extract those binaries and dump into the `bin` folder in wsltty installation.

**Comment by angelog0** [comment]
@mintty, here the last version is:

![settings_winver](https://user-images.githubusercontent.com/35931460/66260185-7cc9a080-e7bb-11e9-8995-d637e5644417.png)

(the same from `winver`) maybe the next week, with monthly updates, we will get 1909.

I never said to use WSL2 which is for 'insider'. The MS Store support only WSL not WSL2. Why have I to repeat things?

@Biswa96, I never said to use `wsltty`.. just MinTTY+MSYS2. Anyway, in MinTTY-3.0.5 and MSYS2 I did

```
wget https://github.com/Biswa96/wslbridge2/releases/download/v0.4/wslbridge2_msys2_x86_64.7z
aunpack -X /bin wslbridge2_msys2_x86_64.7z
```

but it does not work: the [above](https://user-images.githubusercontent.com/35931460/66216795-6aba0600-e6c6-11e9-87ff-5d8e9ac26025.png) shows up when I click **my** link to start WSL-Ubuntu whose target is:

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\angelo\.minttyrc -t "WSL Terminal" --position 20,450 --WSL=Ubuntu -~
```

**Comment by Biswa96** [comment]
Do not run `C:\msys64\usr\bin\mintty.exe` directly in msys2 realm. msys2 repository applies some patches over mintty. Try this:

    C:\msys64\msys2.exe wslbridge2.exe -d Ubuntu

**Comment by angelog0** [comment]
@Biswa96, this partially work but it starts Ubuntu in `/mnt/c/msys64` and not in the user HOME (see the taget of the link in task bar I use for years). I want it with `ubuntu.ico` (with which I configured the above link) but even if I change the icon (`Change icon`) only the link has the icon, the window uses the msys2 icon also un the task bar it uses the msys2 icon...

Please give detailed instructions on how to start Ubuntu with wslbridge2 with its own link on Desktop/task bar...

**Comment by angelog0** [comment]
I have resolved using this target:

```
C:\msys64\usr\bin\mintty.exe -c C:\msys64\home\angelo\.minttyrc -t "WSL Terminal" --position 20,450 /usr/bin/wslbridge2.exe -d Ubuntu -W "~"
```

Please, update your [Tips](https://github.com/mintty/mintty/wiki/Tips#supporting-linuxposix-subsystems)

**Comment by angelog0** [comment]
This [#921](https://github.com/mintty/mintty/issues/921) confirms you have broken the old `wslbridge` usage in combination wit MinTTY to start WSL, the **default**.

Anyway, now you have to implement real Tabs...

**Comment by mintty** [comment]
What default? What broken?
Your attitude is a bit alienating, and I certainly do not have to implement anything, particularly not Tabs.
