### ISSUE TITLE
horizontal scroll wheel event handling

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#925]
Feature request,

xterm has support for horizontal scroll wheels, which mintty appears to be lacking.

I'm using "\e[?1000h\e[?1002h\e[?1004h\e[?1006h" and mintty does not generate a CSI < response.

**Comment by mintty** [comment]
What sequences does it generate?

**Comment by scandum** [comment]
scroll up is 64, down 65, left 66, and right 67.

\e[<64;27;16M
\e[<65;27;16M
\e[<66;45;10M
\e[<67;44;16M

The 2nd value is the column number, and the 3rd value is the row number. 

xterm generates two identical sequences for each left and right click which is somewhat odd.

When the horizontal scroll wheel is held to the left or right it will begin spawning sequences at a rate identical to a keyboard key that is held down.

**Comment by mintty** [comment]
I've tentatively implemented support for reporting horizontal mouse scrolling but I cannot test it right now. Can you compile the current repository version and test it?

**Comment by scandum** [comment]
Both mousewheel left and mousewheel right report \e[<65;1;1M

This should be \e[<66;1;1M and \e[<67;1;1M. Other than that everything works correctly.

**Comment by mintty** [comment]
Thanks for testing. Please try the uploaded tweak.

**Comment by scandum** [comment]
Works beautifully, thanks!

The only difference with xterm is that xterm sends 2 identical sequences at once at the initiation of a left or right scroll.

I assume this allows detecting the difference between a single left/right mousewheel click and sequences generated while keeping the mouse wheel pressed to the left or right.

So on xterm on a single left scroll wheel click: \e[<66;1;1M\e[<66;1;1M

On mintty: \e[<66;1;1M

**Comment by mintty** [comment]
Released 3.0.6.

**Comment by scandum** [comment]
Any word on the behavioral differences I mentioned between mintty and xterm? (still exists in 3.0.6) I can check with the xterm dev for clarification if it'd help you.

**Comment by mintty** [comment]
Possibly there is on sequence when you hit the scroll button and another when you release it?
Otherwise (2 sequences on hit already) that wouldn't be too intuitive.
Anyway, for fine-tuning I think I'd better have a test setup, i.e. a horizontal scrolling mouse, which I don't have.

**Comment by scandum** [comment]
I checked with the xterm developer and apparently it's not indented behavior. It might be a cygwin x window bug. So mintty is up to spec.
