### ISSUE TITLE
Some character ranges are narrowed to fit in a cell

### ISSUE THREAD

**Issue by antoineco** [mintty/mintty#927]
(Follow up on #892, possibly related #570)

Making `CharNarrowing` configurable solves the problem of _squashed_ characters, but I'm still seeing rendering glitches on mintty 3.0.5 with most symbols in the 2100-2300 ranges, such as `\u2192` (→), `\u2388` (⎈) or `\u2318` (⌘).

Example with `CharNarrowing=80` (the new default) and the `DejaVu Sans Mono` (as well as most other popular mono fonts), the size of the symbol is simply reduced to fit into one cell.
![image](https://user-images.githubusercontent.com/3299086/66254738-f8572d80-e77a-11e9-860e-f5fb37998a4c.png)

What I see instead in GNOME Terminal and macOS Terminal, and expect to see in mintty:
![image](https://raw.githubusercontent.com/jonmosco/kube-ps1/master/img/screenshot2.png)

Some other wide characters, like chinese, are displayed properly.

---

And just for the curiosity, the `Fira Code` font shows a clipped `\u2388` character, but this is most likely specific to the font:
![image](https://user-images.githubusercontent.com/3299086/66254526-b1b40400-e777-11e9-822c-db49de73f8aa.png)

**Comment by antoineco** [comment]
I just saw your comment from yesterday on https://github.com/mintty/mintty/issues/922#issuecomment-538384738
> I plan to exclude the character ranges U+2190 .. U+2BFF and U+1F000 .. U+1FAFF from auto-narrowing.
Sounds sensible to me 👍

**Comment by mintty** [comment]
The trade-off and alternative approaches have been discussed in the other issue.
Try CharNarrowing=100 as a workaround.
Please also quote the exact output (including formatting controls) of your text example.

**Comment by antoineco** [comment]
I'm using the Zsh shell and this prompt equals `%{%F{4}%}⎈ %{%f%}%{%F{1}%}microk8s%{%f%}:%{%F{6}%}default%{%f%}`. It can be printed using Zsh's builtin `print -P`.

```console
$ print -P "$RPROMPT" | sed -n l
\033[34m\342\216\210 \033[39m\033[31mmicrok8s\033[39m:\033[36mdefault\
\033[39m$
```

**Comment by antoineco** [comment]
`CharNarrowing` works okay-ish, but characters are still not full size, while they are on all the macOS and Linux terminal emulators I've tried. It's not a big deal and I understand a Windows environment is different, it just looks a bit funny in prompts that make heavy use of those characters. One example: [denysdovhan/spaceship-prompt](https://github.com/denysdovhan/spaceship-prompt).

**Comment by mintty** [comment]
Actually, with DejaVu Sans Mono, that's simply how that character looks. Rendering is proper, CharNarrowing has no effect. Rendering in notepad is the same.
Your comparison from other terminals also uses another font, so it's not significant.

**Comment by mintty** [comment]
Furthermore, your example symbol, U+2388, is clearly defined to have the Narrow width property in Unicode, so the other terminals are buggy about it.

**Comment by antoineco** [comment]
Source Code Pro, the font I actually use on other machines, also has the snipped character issue. I believe you, but it can't _only_ be the "font's" or "other people's mistake" when mintty is the only terminal emulator with which I experience this clipping or squashing.

![image](https://user-images.githubusercontent.com/3299086/66258518-5a795800-e7a6-11e9-99ab-10f7621c0a68.png)

**Comment by mintty** [comment]
Actually, I'm afraid your report there was a bit premature.
The glyph is not included in either Fira Code or Source Code Pro (as can be checked in mintty with the glyph coverage enquiry: `echo -en "\e]7771;?;9096\a"`), so what you see is some Windows-managed font fallback; on my system, the (fallback) glyph is not clipped with all 3 fonts (where DejaVu Sans Mono actually has the glyph).
You could  bypass the Windows font fallback and define a secondary font as suggested in the manual page:
```
FontChoice=PictoSymbols:2
Font2=DejaVu Sans Mono
```

**Comment by antoineco** [comment]
You're right about Source Code Pro, it was a bad example. I can see the character in Fira Code ([v2](https://github.com/tonsky/FiraCode/releases/tag/2)) though.

**Comment by mintty** [comment]
Updated the font and ran
`mintty -fn "Fira Code Regular" -o CharNarrowing=100`
but the character is not clipped here.

**Comment by antoineco** [comment]
I don't have an old version installed (new computer) and I don't have `Fira Code Regular` in my font selection menu, only `Fira Code` and `Fira Code Retina`.

![image](https://user-images.githubusercontent.com/3299086/66259248-f6a75d00-e7ae-11e9-842e-db086a39cb34.png)

**Comment by mintty** [comment]
The terminal icon does not look like it's mintty, and the half symbol does not look like the respective character that Fira Code V2 has. Anyway, what does the glyph enquiry sequence say?

**Comment by antoineco** [comment]
> The terminal icon does not look like it's mintty

Because it was started from one of the wsltty shortcuts. And before you ask, yes, I'm certain of what versions I'm using, both the Fira Code font and mintty version.

How do I use that sequence? Just append the character to it? What output do you expect?

**Comment by mintty** [comment]
I quoted the sequence above. After the "?;" it takes a semicolon-separated sequence of decimal character values. For each, the value will be reported back if the character has a glyph in the font, or an empty position otherwise.

**Comment by antoineco** [comment]
In a Bash shell:
![image](https://user-images.githubusercontent.com/3299086/66259920-1a22d580-e7b8-11e9-83a1-571b41526d68.png)

**Comment by antoineco** [comment]
> the half symbol does not look like the respective character that Fira Code V2 has

The character looks the same to me:

![image](https://user-images.githubusercontent.com/3299086/66259968-88679800-e7b8-11e9-89d1-b8ff9c56b351.png)

**Comment by BrianInglis** [comment]
You can easily display Unicode chars, convert from hex to dec and back, and test esc seqs using `printf`, or capture test output with `read`: 
```
$ printf "%d\n" 0x2388
9096
$ printf "%#x\n" 9096
0x2388
$ printf "%#x\n" 9100
0x238c
$ printf "\u2388\u238c\n"
⎈⎌
$ printf "\E]7771;?;9096\a"
$ 7771;!;9096 [echo]
$ read -n15 -s -t1 -p $'\E]7771;?;9096\a' t; cat -A <<< "$t"
^[]7771;!;9096^[$
$ printf "\E]7771;?;9096;9100\a"
$ 7771;!;9096;
$ read -n20 -s -t1 -p $'\E]7771;?;9096;9100\a' t; cat -A <<< "$t"
^[]7771;!;9096;^[$
```
the list entry for the missing glyph is empty.

**Comment by antoineco** [comment]
@BrianInglis thanks for the explanation, I understand the values in the previous command now 👍 
If you're saying Fira Code v2 does _not_ have the glyph, how come I can see it in the character map? As a comparison, I don't see it for another font like Source Code Pro.

**Comment by antoineco** [comment]
The author of Fira Code responded. He made the character double width by design, which is not gonna work with mintty's auto-narrowing, so I'm gonna go ahead and close this and link to this comment for future readers: https://github.com/mintty/mintty/issues/892#issuecomment-512315526

Thanks both for your comments.

**Comment by BrianInglis** [comment]
Can or should he be doing that with that Unicode code point? 
Can and does he mark the glyph with that property/attribute?

**Comment by antoineco** [comment]
> Can and does he mark the glyph with that property/attribute?

Yes: https://github.com/tonsky/FiraCode/commit/af1c556584c5679c5b8f5188441e8cfd2ee00c54#diff-bcc7446d7140b9d68e08440b67a2fe85R95557

**Comment by antoineco** [comment]
Regardless, the rendering looks perfect on mintty 3.0.6 due to disabling auto-narrowing for that problematic range. Thanks @mintty!

**Comment by mintty** [comment]
> Can or should he be doing that with that Unicode code point?

No, they shouldn't. It's a bug.
