### ISSUE TITLE
Sixel is still broken

### ISSUE THREAD

**Issue by mattn** [mintty/mintty#929]
Version 3.0.6 include [fix of sixel](https://github.com/mintty/mintty/commit/3b95758f5ff0bc5dd034b78a389bb43431459415) but still broken. This attached "logo.drcs" can be displayed in 3.0.2 but 3.0.6 display black empty area.

[logo.zip](https://github.com/mintty/mintty/files/3705038/logo.zip)

**Comment by mintty** [comment]
It displays fine for me, but in fact another sixel fails occasionally, typically the second time on repeated output.
[boticelli.zip](https://github.com/mintty/mintty/files/3705894/boticelli.zip)

**Comment by mattn** [comment]
In my case, always display nothing.

**Comment by mintty** [comment]
Uploaded a fix to the repository.

**Comment by mattn** [comment]
Works fine. Thank you.
![image](https://user-images.githubusercontent.com/10111/66719469-429b7700-ee2b-11e9-94f9-334f6e024d89.png)

**Comment by XVilka** [comment]
Should be this closed then?

**Comment by mattn** [comment]
yes, thank you.

**Comment by mintty** [comment]
Thanks, but it's still broken in the current release. I'll close with 3.0.7.

**Comment by mintty** [comment]
Released 3.1.0.
