### ISSUE TITLE
Cursor color is changed to black inside Neovim/Vim for the latest mintty (3.0.6)

### ISSUE THREAD

**Issue by jdhao** [mintty/mintty#930]
Today I updated my mintty for Cygwin to version 3.0.6 and found a strange problem: the cursor color inside neovim became dark instead of the color I set for the color scheme.

I have also ubuntu on Windows which has mintty 3.0.0 installed.  I logged in the same server and opened neovim, the cursor color is normal (green, this is what I have set in terminal theme).

# version info

+ neovim: NVIM v0.5.0-159-g7faa6c41c
+ mintty: 3.0.6

# steps to produce

1. Open cygwin terminal and ssh to a server with neovim installed.
2. Open a file with `nvim -u NORC test.txt`

The cursor color becomes black.  When I exit the remote server and go back to cygwin terminal, the cursor color is still black.

Black cursor inside neovim

![image](https://user-images.githubusercontent.com/16662357/66546082-beb56680-eb6e-11e9-87a5-019246e7cd57.png)

Normal cursor color inside neovim:

![image](https://user-images.githubusercontent.com/16662357/66546118-d8ef4480-eb6e-11e9-8f45-8ea837a31065.png)

I have tried to log in to another server with neovim  0.4.0 installed. The same issue occurs. I have also tried Vim (version 7.4) and found the same issue. 

# Further test and summary

I have also tested mintty 3.0.4 and the issue persists. So in summary:

+ the version of mintty which changes cursor color: 3.0.4, 3.0.6
+ vim version tested and affected: 7.4
+ nvim version tested and affected: 0.4.0, 0.5.0

**Comment by mintty** [comment]
So HOW does it occur? A reproducible test case is requested.

**Comment by jdhao** [comment]
After my computer is rebooted, I can not reproduce this issue now.  I have no clue why...

**Comment by jdhao** [comment]
After some time, when I log in to the server, the issue re-appear (see the image below for an example). I can not seem to reproduce from a local cygwin terminal.

![mintty](https://user-images.githubusercontent.com/16662357/66622185-6c7d4f80-ec19-11e9-82c2-9f53dadd635a.gif)

PS, if you have a remote server, you can use the following script to install neovim:

```
echo "Installing Neovim"
echo "Creating nvim directory under tools directory"
NVIM_DIR=$HOME/tools/nvim
NVIM_SRC_NAME=$HOME/packages/nvim-linux64.tar.gz
NVIM_CONFIG_DIR=$HOME/.config/nvim
NVIM_LINK="https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz"

if [ ! -d "$NVIM_DIR" ]; then
    mkdir -p "$NVIM_DIR"
fi

echo "Downloading Neovim"
if [ ! -f $NVIM_SRC_NAME ]; then
    wget $NVIM_LINK -O $NVIM_SRC_NAME
fi

echo "Extracting neovim"
tar zxvf $NVIM_SRC_NAME --strip-components 1 -C $NVIM_DIR
```

**Comment by mintty** [comment]
>  Please make a minimal screen log to show the effect.

Let's try this first. If possible, for comparison also with a previous version which does not show the effect.

**Comment by jdhao** [comment]
OK, I have installed a previous version of mintty via wsltty  and the version is 3.0.2. 

I log in my remote server again and open the same file. This time, the cursor color is normal.

**Open nvim on a remote server with mintty version 3.0.2**

![mintty-3 0 2](https://user-images.githubusercontent.com/16662357/66693351-a2363d00-ecda-11e9-92a0-397c3e0dc858.gif)

**Comment by mintty** [comment]
So we're back here:
> Please provide a reproducible test case.
> Please make a minimal screen log to show the effect.

**Comment by jdhao** [comment]
I am afraid this is as far as I can get. I do not know the reason why the cursor go black. So it is hard to reproduce on the local machine without log in to the remote server.

**Comment by mintty** [comment]
I did not say you must not login remotely. Just make a screen log. If it contains the colour switch, it can then be replayed locally for analysis.

**Comment by BrianInglis** [comment]
Thomas Wolff (`mintty`) is asking you to install and run the `screen` utility and use it to capture a log of the activity including the escape sequences, so he can replay and analyze what is happening. 

Could the poster use the `mintty -l `_`log`_ or the `script` utility to capture the escape sequences?

**Comment by mintty** [comment]
Sure, the mintty log will be helpful, or any other log.

**Comment by jdhao** [comment]
I think I have found the cause of this issue. It is caused by an input method application I have installed. It changes the cursor color to black. If I switch back to Microsoft IME, the cursor color are restored to its original color.

The IME causing this issue is [weasel](https://github.com/rime/weasel).

**Comment by mintty** [comment]
Do you have a mintty setting for option `IMECursorColour`? What if you use it?

**Comment by jdhao** [comment]
Thanks, after settings `IMECursorColour` to red, cursor color when weasel is activated is changed red. However, when I press `Shift` key to change to English mode, the cursor color is still red.

If I use Microsoft IME, the cursor color is changed to red when Chinese mode is on. When I press `Shift` key to activate English mode, the cursor color is restored to its original color.

Under English keyboard (i.e., neither Microsoft IME or weasel is used), the cursor color is always its original color.

![mintty_imecolor](https://user-images.githubusercontent.com/16662357/66900826-17ce4000-f030-11e9-9f58-b88abe18252a.gif)

**Comment by mintty** [comment]
I cannot test it as there is no binary download for weasel and I do not have a Windows build environment.
You could try to analyse the different behaviour with weasel vs. MS IME if you build mintty yourself and activate message debugging by changing this line in winmain.c:
`#define dont_debug_messages`
to
`#define debug_messages`

**Comment by jdhao** [comment]
The weasel binary package can be downloaded [here](https://dl.bintray.com/rime/weasel/weasel-0.14.3.0-installer.exe). It is for typing Chinese. I am not sure if you can use it on your Windows machine. It should work.

**Comment by mintty** [comment]
I observe weird and buggy behaviour of the weasel tool.
Particularly, it never sends a WM_IME_NOTIFY message with IMN_SETOPENSTATUS command. This would be used to switch the IME status.
It sends lots of WM_IME_NOTIFY messages, even if nothing is happening on the keyboard, it does not always refocus to the terminal window, its popup placement is not always proper, it lays a white box over the text...
