### ISSUE TITLE
Troubleshooting issues with global hotkeys

### ISSUE THREAD

**Issue by danielepaolella** [mintty/mintty#932]
I'm using global AltGr key combinations to insert special chars which are not available in my keyboard layout. They work everywhere but in mintty, where nothing is printed.

Before I had to reinstall my system, the hotkeys were working in mintty too, so I suspected it might have to do with a recent update and set up the same version I had earlier (2.9.3); unfortunately the hotkey didn't work either, so we can rule out a regression being introduced recently.
So the question is: how would you troubleshoot this? I have little understanding of what mintty could be doing with key combinations. I expected it to somehow capture and swallow some event before it was passed to the program handling the keystrokes, so I tried monitoring them on the side of this latter program, but it seems they are received correctly, whether I type my combination in mintty or a different window.

I tried experimenting with different settings, including `OldAltGrDetection=yes`, so far to no avail.

**Comment by mintty** [comment]
For complete and flexible key input handling, mintty interprets AltGr itself. However, it also uses system keyboard layout as a fallback. To check out what happens for you, it would be useful to replay the issue. Which tool do you use to define AltGr key assignments, what's the configuration?

**Comment by danielepaolella** [comment]
Thanks for your fast reply, I'd have spared you from setting up 3rd party tools, especially because I'm using your beloved [AutoHotKey](https://www.autohotkey.com/), version 1.1.31.01.

I'm attaching a basic configuration: [AutoHotKey.zip](https://github.com/mintty/mintty/files/3727803/AutoHotKey.zip); once you installed the program and unzipped the archive, double-clicking on the ahk file should enable two combinations:

- `AltGr` + `'` = `` ` `` (`AltGr` + "apostrophe" to produce a backtick)
- `AltGr` + `ì` = `~` (`AltGr` + "small i with grave accent" to produce a tilde)

You can disable them and exit the program by right-clicking the green "H" icon ![image](https://user-images.githubusercontent.com/53744340/66808341-4e6e6280-ef2b-11e9-8382-e03a69edfe76.png) in your systray and choose "Exit".

Since you also mentioned, it seems relevant I'm using the [Italian keyboard layout](https://docs.microsoft.com/en-us/globalization/keyboards/kbdit.html) on Windows 10 Home version 1903 build 18362.418.
It looks like the issue is very specific to some layout, because the same hotkey with an [alternative layout](https://docs.microsoft.com/en-us/globalization/keyboards/kbdit142.html) appears to work as expected in mintty too, which is possibly even more confusing.
In case you're setting the same environment, you'll find the two involved keys immediately left of the backspace.

![image](https://user-images.githubusercontent.com/53744340/66808970-ace81080-ef2c-11e9-86ef-2e1935adccae.png)

Concerning mintty, I'm using 3.0.2 as bundled with the latest [Git for Windows](https://git-scm.com/download/win) 2.23.0, I deleted .minttyrc and it seems there aren't [other configs](https://github.com/mintty/mintty/wiki/Tips#user-content-configuring-mintty) around, so all options should be back to default - for completeness, I see the same behaviour whether I'm running Git Bash or mintty.exe directly.

**Comment by mintty** [comment]
In your setup, Windows generates the following sequence of "virtual key codes":
VK_CONTROL, VK_MENU (which in this combination and with some additional side conditions indicates AltGr), and then
VK_PACKET, which I've never seen before.

To be investigated: meaning and handling options of VK_PACKET.

**Comment by mintty** [comment]
Actually, mintty handles the VK_PACKET case and invokes the Windows layout for it, and it even generates the desired character (~), it just prefixes it with an ESC because it thinks Alt is pressed.
Test in a shell: Control+V AltGr+ì

**Comment by mintty** [comment]
There is a workaround, actually for another hotkey tool (StrokeIt), which is counterintuitive:
option `SupportExternalHotkeys=0`

**Comment by mintty** [comment]
A temporary fix was uploaded. To be checked whether the fix for StrokeIt is now broken :(

**Comment by danielepaolella** [comment]
Thank you for the update, can't compile and test it right now, but I'll do as soon as possible.

In the remote chance that anybody stumbles into the same issue before mintty's next release, a workaround is to [downgrade AutoHotkey](https://www.autohotkey.com/download/1.1/): apparently they introduced the new behavior [somewhere between 1.1.26.1 and 1.1.31](https://www.autohotkey.com/docs/AHKL_ChangeLog.htm), shame on me for not thinking of that any earlier.

**Comment by mintty** [comment]
Released 3.1.0.
