### ISSUE TITLE
Mintty : Powershell security issue - Password 

### ISSUE THREAD

**Issue by dst1ny** [mintty/mintty#933]
Hi ,

I'm using Mintty everyday from maybe 1 year ago, it is a very powerful terminal with a very good features for peoples working in the IT services.  I start creating Powershell scripts which uses mintty.exe with plink command. The connection is working well , but the problem is that when the plink request is sent To Mintty , the username as well as the password are displayed in the title of the terminal window.

Could you please help me resolving that ?

Thans in advance for your help

Regards

dst1ny

**Comment by Biswa96** [comment]
Are you using cygwin? Did you try to use a shell script instead of a PowerShell script? cygwin realm has some conflicts with Windows command line programs.

**Comment by dst1ny** [comment]
Yes , i'm using cygwin on windows , i will try for the shell script and give you a feedback soon ! Thanks

**Comment by dst1ny** [comment]
I tested and confirm, from my linux station, it is working fine, shell scripts are good, the issue is with the Windows station. I really would like to find a solution for it...

**Comment by mintty** [comment]
Your scenario description is quite fuzzy. Do you invoke mintty with a plink command that logs in somewhere with user and password? In that case it's not a surprise that the whole command line appears in the title as that is what mintty does by default.
You can use the `-t` title parameter to override it.

**Comment by mintty** [comment]
Closing as the previous comment explained the issue and provided a workaround.

**Comment by BrianInglis** [comment]
As you have Cygwin you could install Cygwin openssh package and use those commands directly instead of putty plink. 
With Cygwin you could use (POSIX/Bourne) sh instead of PowerShell scripts, unless you are also accessing Windows platform info in those scripts, although Cygwin/POSIX/GNU utilities often offer equivalent or better access to some info.
