### ISSUE TITLE
Unicode box drawing

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#935]
Mintty doesn't display several unicode line drawing characters correctly in courier-new. I'll make a quick compilation for testing. Better results in consolas, but not all of 'm perfect either.

https://en.wikipedia.org/wiki/Box-drawing_character

```
echo -e '╭──╮\n│  │\n╰──╯'
╭──╮
│  │
╰──╯
echo -e '╲ ╱\n ╳\n'
╲ ╱
 ╳
echo -e '╺╋╸'
```
Displays fine on Cygwin's xterm.

**Comment by mintty** [comment]
Workaround:
```
FontChoice=PictoSymbols:2
Font2=DejaVu Sans Mono
```
or
```
FontChoice=PictoSymbols:2
Font2=Consolas
```

**Comment by scandum** [comment]
DejaVu works alright, I'll use that from now on.

**Comment by scandum** [comment]
Unfortunately DejaVu isn't a Windows default font unlike Consolas so it's not a solid alternative for wide distribution. Or is there some guaranteed way to get mintty to work with DejaVu for 3rd parties?

echo -e '╲ ╱\n ╳\n'

Looks like there's just a slight width issue in consolas there.

**Comment by mintty** [comment]
This is how it looks in xterm with Consolas, size 14:
![935](https://user-images.githubusercontent.com/12740416/68290033-87f84080-0087-11ea-90bb-652e40e9591d.png)
Not perfect either. It's a font issue. Closing.

**Comment by mintty** [comment]
See also #1119 and mintty/wsltty#353.
I'm experimenting with self-drawing of Box Drawing characters (like apparently Windows Terminal and others do) but it's another fight against Windows APIs...
A workaround (that I'd also describe in the manual and wiki) is:
`FontChoice=|Box Drawing:2`
`Font2=Consolas` (or DejaVu Sans Mono if you have it)

**Comment by mintty** [comment]
> boxdraw

Thanks, however, that one uses Xft while mintty has to deal with a Windows API (GDI+ maybe; Windows Terminal even uses the insanely-to-use D2D1).

**Comment by avih** [comment]
> that one uses Xft

I'm was well aware of that when I wrote it.

> mintty has to deal with a Windows API

Obvious as well. Hence once you get past the API barrier (to draw rectangles - which is the only thing that patch does with Xft), the logic in that patch might be helpful.

**Comment by mintty** [comment]
Released 3.7.5.

**Comment by scandum** [comment]
Could this be added to the self-draw support?

https://en.wikipedia.org/wiki/Symbols_for_Legacy_Computing_Supplement

This block is relatively new, officially added in Unicode Version 16.0 on September 10, 2024.

The unicode guys decided to be difficult and follow the 'no duplicate characters' rule, so the octant range doesn't use an identical mapping to the braille block, and borrows from the block elements range instead. I reckon that may need to be included in the self-draw if there are any issues.

https://en.wikipedia.org/wiki/Block_Elements

**Comment by mintty** [comment]
The octants U+1CD00..U+1CDE5 can be added, Block Elements are already covered.
