### ISSUE TITLE
How close/kill/terminate a mintty.exe from another

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#937]
How close/kill/terminate a mintty.exe from another mintty.exe being active now,
by some linux command (preferably the most common one even  if longer/more option rather than the less one, quite rare) ?

**Comment by mintty** [comment]
The name of the command is `kill`, you find the process id with `ps`.

**Comment by Biswa96** [comment]
Perhaps, the terminate option can be added in the right click option menu.

**Comment by mintty** [comment]
It's available as a user-definable menu entry.
But what @abdulbadii wants is to close one terminal from another. So in addition to the "Session switcher" (Ctrl+right-click), there could in theory be a "Session killer". I don't consider that a good idea, however.

**Comment by abdulbadii** [comment]
Thanks great, i think **ps** will do some good work here
