### ISSUE TITLE
ANSI color and 256 color interaction

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#939]
![image](https://user-images.githubusercontent.com/52607428/68140203-b52fdc00-ff2b-11e9-8ac1-069d278649a9.png)

To reproduce:

echo -e "\e[1m\e[38;5;46mtest"
echo -e "\e[0m\e[38;5;46mtest"

When a 256 color code is prefixed by 1m it fattens the font even with show bold as color enabled. Is this a bug? Or is there some way to disable this?

**Comment by avih** [comment]
It's not a bug, and you can't disable fattening only for this case without disabling fattening completely. See https://github.com/mintty/mintty/issues/936 .

**Comment by scandum** [comment]
#936 is no solution as that breaks ANSI color support.

Ideally there'd be an option to disable font fattening completely, as that's the only thing I (and others) have an issue with.

**Comment by mintty** [comment]
The manual page says that `BoldAsColour` applies only to foreground and basic 8 ANSI colours. It is actually just a legacy feature, referring to old IBM PC VGA card features, so it's not expandable to full colour support. In a 216-colour space, any significantly different "bright" colour variant would already be closer to other colours of that space than to the original colour, so it makes no sense.

> #936 is no solution as that breaks ANSI color support.

Please explain. The suggestion there is the `SuppressSGR=1` setting. It does not break any colours.

**Comment by scandum** [comment]
SuppressSGR=1 disables BoldAsColour for ANSI colors, and I assume it also breaks the other SGR options.

I have 'Show bold as font' disabled, yet mintty shows 256 colors in a bold font. So it looks like the config option is worded badly or not working as intended.

xterm works as expected when disabling 'bold fonts', disabling font bolding across all color modes.

**Comment by mintty** [comment]
SuppressSGR=1 disables the bold attribute altogether, and no other SGR codes.
The "Show bold as font/colour" settings are not completely independent. Particularly if both are disabled, mintty falls back to some xterm compatibility behaviour, as described in the manual page.
The selection of the four options might be improved, I had considered that before.
About referring to xterm, which config options do you use for "disabling font bolding"?

**Comment by scandum** [comment]
In Cygwin's xwindow's xterm it's the option from the "VT Fonts" tab named "Bold Fonts".

**Comment by avih** [comment]
> The selection of the four options might be improved

Well, the whole reason that we ended up with this xterm compatibility mode when both are off was, in part, because you refused to allow disabling both as font and as color together. You wanted the bold attribute to always render differently than non bold. That's also the reason why the "extended" colors will always use as font.

We can simplify it completely such that "as color" is independent and only affects the default color and ANSI8, and "as font" is independent and affects everything equally. So if one enables only "as color" then the extended colors in bold are indistinguishable from non bold.

**Comment by mintty** [comment]
See also https://github.com/mintty/mintty/issues/777#issuecomment-418163783;
The fact that some people were quite unhappy with the solution that came up after endless discussions made me introduce SuppressSGR. So it is in fact possible to suppress bold in mintty.
I'd need some really convincing arguments to open that can of worms again.
As I said above, we could however agree on a better way to configure the 4 options, not pretending they were 2×2 options.

**Comment by scandum** [comment]
Is it possible that the flaw is that you try to mimic xterm default behavior with both options disabled, while the xterm default is to have both options enabled?

So if that reasoning is correct, both options enabled in mintty should mimic xterm default behavior, while disabling show bold as font should disable all font bolding.
 
I'm not sure if xterm has a 'show bold as color' toggle, if it does it's not in the main gui, because that's something few people would want to disable as it'll halve the available colors.

I assume xterm compatibility is a good argument, and right now mintty isn't in this regard.

**Comment by mintty** [comment]
The xterm fallback was an agreement to settle a long discussion and I would not call it a flaw as such.
Please check out the previous issues first.

**Comment by scandum** [comment]
I checked the previous issues and I'm not really seeing anything of relevance, nor do I want to turn this into a long discussion. ;-)

I'll leave this open as an xterm incompatibility.

**Comment by mintty** [comment]
Mintty does not claim to be xterm-compatible with respect to configuration.
Compability is mainly about terminal features, particularly escape sequences etc.

**Comment by scandum** [comment]
xterm has an emulation mode (which happens to be the preferred mode for many users) where all font fattening is disabled without breaking ANSI color support. MinTTY does not support this emulation mode. So it is an incompatibility, not a different way of going about configuration.

**Comment by mintty** [comment]
I'd prefer if you clarify on your claims instead of getting more fuzzy.
What emulation mode? Why do you think users prefer it? How do you think mintty breaks colour support? And how do you claim mintty should do the same thing?
Layout differences, by the way, are certainly not incompatibilities with respect to terminal features.

**Comment by scandum** [comment]
xterm has the 'Bold Fonts' config option, which completely disables bold fonts when disabled. Mintty has the 'Show bold as font' option which does not completely disable bold fonts when disabled.

**Comment by mintty** [comment]
That is correct. Mintty does not support interactive disabling of the bold attribute.

**Comment by scandum** [comment]
Looks like font fattening also has different box drawing rendering.

![image](https://user-images.githubusercontent.com/52607428/68667286-e9b42100-0545-11ea-9ef5-f3c164416f6c.png)

![image](https://user-images.githubusercontent.com/52607428/68667303-f5074c80-0545-11ea-9e63-e001b7bff8f4.png)
 
The only difference is that in the bottom image \e[22;32m is replaced with \e[38;5;35m.

**Comment by mintty** [comment]
Not reproduced, with a bunch of fonts. Which is yours? And which are the characters?

**Comment by mintty** [comment]
With Lucida Console, and U+2015 HORIZONTAL BAR for the horizontal lines, and bold lines in one case, I'm getting a similar picture. So I assume lines are bold in your upper screenshot.

**Comment by scandum** [comment]
Forgot to mention, the font is DejaVu Sans Mono. The off-center lines are indeed bolded.

Interesting enough there is no font fattening when using Consolas. So I guess I can work around the issue by setting Consolas as the default for my mintty distribution.

![image](https://user-images.githubusercontent.com/52607428/68698879-2dc51700-0582-11ea-89a9-9c7f8b5ba6d8.png)

**Comment by mintty** [comment]
Released 3.1.0.

**Comment by scandum** [comment]
The configuration still doesn't seem to allow displaying \e[1;32mtest\e[38;5;24mtest as entirely non-fat.

**Comment by mintty** [comment]
The change in 3.1.0 intends to make the options clearer. They have not changed, as explained above. You can still use the SuppressSGR option.
