### ISSUE TITLE
Can't make window full screen when search bar is enabled

### ISSUE THREAD

**Issue by Biswa96** [mintty/mintty#940]
Steps: Press Alt +F3 which opens search bar at bottom. Press Alt + F11 which does not make it full screen. But if I don't enable the search bar then Alt + F11 works as usual.

**Comment by mintty** [comment]
Actually, Alt+F11 still works but the focus needs to be in the terminal pane (or "window", technically, as seen in Windows). After opening a search bar with Alt+F3, the focus is in that window, so it does not work. Click in the terminal area and it works again.
Not sure whether the effort to make things work alike in the search bar is worth it. Maybe I'd just add some documentation?

**Comment by Biswa96** [comment]
> Click in the terminal area and it works again.

It works but if I'm working with keyboard I've to move my hand to mouse. Ergonomics!?

**Comment by BrianInglis** [comment]
Just press Tab to get back to terminal pane.

**Comment by Biswa96** [comment]
Ya, it's a good workaround.

**Comment by mintty** [comment]
... which I wasn't aware of (someone else implemented the search feature).
Added a hint to the manual page.
