### ISSUE TITLE
fzf does not work on mintty

### ISSUE THREAD

**Issue by soerenwolfers** [mintty/mintty#941]
According to https://github.com/junegunn/fzf/wiki/Cygwin fzf doesn't work on mintty. 

Can this be fixed on the mintty side?

**Comment by mintty** [comment]
As fzf is apparently a Windows program, this is likely the incompatibility of console I/O with the pty-based I/O used by terminals. To be fixed with cygwin 3.1.0 (already available as test release).

**Comment by soerenwolfers** [comment]
Fzf does work in cygwin bash, just not in mintty. Does that still make sense?

**Comment by mintty** [comment]
Yes.

**Comment by mintty** [comment]
Cygwin 3.1.0 has been released with ConPTY support.

**Comment by soerenwolfers** [comment]
Finally got around to trying this, and fzf still doesn't work with the latest 3.1.0

**Comment by mintty** [comment]
Note there is a cygwin package of fzf.
If you want me to check out why the Windows version may not work, please provide reproducible instructions how to install it and how to demonstrate a problem.

**Comment by marcotrosi** [comment]
> As fzf is apparently a Windows program, this is likely the incompatibility of console I/O with the pty-based I/O used by terminals. To be fixed with cygwin 3.1.0 (already available as test release).

I'm confused. I used in 2019 fzf without issues with mintty from Cygwin 3.0.7. Today I updated to Cygwin 3.1.2 and now it crashes.

/usr/bin/fzf:929:in `getc': No such process @ io_fillbuf - fd:11 /dev/tty (Errno::ESRCH)

I guess that's the wrong project to address that, and my intention is also not to address it here, but I'm confused that @soerenwolfers says fzf doesn't work with mintty. Did I miss something?

Thank you

**Comment by marcotrosi** [comment]
Okay I caused the issue myself. Fixed it. But I can definitely say that fzf works with mintty.

**Comment by harisund** [comment]
Can you tell me if you did anything special to configure it? I don't even know what to start debugging this , to be honest (@marcotrosi ) 

`CYGWIN_NT-10.0 HARISUN-QGFZR 3.1.2(0.340/5/3) 2019-12-21 15:25 x86_64 Cygwin`

`cygcheck (cygwin) 3.1.2

System Checker for Cygwin
Copyright (C) 1998 - 2019 Cygwin Authors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

Did you build it yourself? When I execute fzf, nothing happens really. I don't get an error message, but the "pop up" I see on Linux doesn't show up. Any idea how I can debug?

**Comment by marcotrosi** [comment]
I did nothing special. I tried the Cygwin fzf (installed via setup.exe) and also the Windows fzf (newer version written in Go, pre-build binary).

can you try to pipe some lines from a text file into fzf and see if it works?

`cat foo.txt | fzf`

**Comment by jmiguel-hdez** [comment]
was this fixed? what was the change required? 
I still issues on latest git for windows  using mintty 
when I run cat foo.txt | fzf 
it doesn't show anything, need to type ctrl-c to be able to control the console again.
