### ISSUE TITLE
Wide ambiguous character width for unicode '‘' (0x2018) with font Monaco with CJK Locale option

### ISSUE THREAD

**Issue by kangjianbin** [mintty/mintty#945]
Hi experts,
I find that when using Monaco font, mintty will treat '‘' as a 2-char width, which cause emacs's display and edit to be abnormally.
My first thought is, that is the problem of Monaco font. However I find it displays correctly in emacs GUI.

Would someone please provide some guide on how to solve the problem? 

The character information is:
```
             position: 1 of 7 (0%), column: 0
            character: ‘ (displayed as ‘) (codepoint 8216, #o20030, #x2018)
    preferred charset: unicode (Unicode (ISO10646))
code point in charset: 0x2018
               script: symbol
               syntax: . 	which means: punctuation
             category: .:Base, c:Chinese, h:Korean, j:Japanese

```
Mintty with GoMono font:
![mintty-GoMono](https://user-images.githubusercontent.com/121803/70386649-53eda380-19d6-11ea-8a0b-7cf48c878b18.jpg)

Mintty with Monaco font:
![mintty-Monaco](https://user-images.githubusercontent.com/121803/70386653-59e38480-19d6-11ea-91cb-20470e165894.jpg)

Emacs-GUI with Monaco font:
![emacs-Monaco](https://user-images.githubusercontent.com/121803/70386665-71bb0880-19d6-11ea-96d7-9130ba118f61.jpg)

**Comment by mintty** [comment]
Cannot reproduce. Looks fine here in cygwin or MSYS2.
The character displays single-width unless I use option `-o Charwidth=ambig-wide` in which case it is double-width, independently of the font.
There must be something in your configuration that triggers ambiguous-wide behaviour. What does `locale` say? What does the Options dialog, section Text, say for Locale and Charset?

**Comment by kangjianbin** [comment]
Thanks. Looks like it is really locale releated.
However, if I change the font to 'GoMono', it works well in 'zh-CN' locale:

Locale 'zh-CN' and character set 'UTF-8':
![图片](https://user-images.githubusercontent.com/121803/70388943-9d002080-19f3-11ea-8be5-7f7f6dbe5992.png)


Locale 'C' and character set 'UTF-8':

![图片](https://user-images.githubusercontent.com/121803/70388948-b1441d80-19f3-11ea-8132-568a49e2c8ad.png)


Locale 'zh-CN' and character set 'UTF-8', but with 'GoMono' font:
![图片](https://user-images.githubusercontent.com/121803/70388929-5c080c00-19f3-11ea-9fb6-cae2013b6dd7.png)

**Comment by mintty** [comment]
I had asked about the output of `locale` which might give further insights.
If an explicit `Locale` option is used with a CJK locale, ambiguous width behaviour does indeed depend on font properties, as documented in the manual page.

**Comment by kangjianbin** [comment]
The default local output is (same as zh-CN):
```
[~]$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=
```

When I set locale to 'C' and restart mintty, locale output is:
```
[~]$ locale
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

```

**Comment by mintty** [comment]
OK, please start mintty with the Monaco font (either configured or via command line `--fn Monaco`). What does `locale` say then?
As a workaround, try to start with empty `Locale` option, setting the locale per variable and see whether results differ:
`LC_ALL=zh_CN.UTF-8 mintty -o Locale= --fn=Monaco`

**Comment by kangjianbin** [comment]
1.  Start mintty with 'Monaco' font, it still shows 2-char width. output of locale is:
```
[~]$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=
```

2.  Start with command line `LC_ALL=zh_CN.UTF-8 mintty -o Locale= --fn=Monaco`, still 2-char width. output of locale is (*NOTE that LC_ALL is set to zh_CN.UTF-8*):
```
[~]$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```

3. I tried the commad line with 'GoMono', now 'GoMono' doesn't work either. 
`LC_ALL=zh_CN.UTF-8 mintty -o Locale= --fn='Go Mono'`. locale output:
```
[~]$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```
![图片](https://user-images.githubusercontent.com/121803/70389441-3c281680-19fa-11ea-8932-bfaee62fc8b4.png)

**Comment by kangjianbin** [comment]
Hi @mintty ,

Thanks for your help!
Seems it works with empty locale setting. If this is an expected behavior, we can close the issue.

**Comment by mintty** [comment]
Actually, in a CJK locale, displaying that character wide is correct behaviour.
(If another program gets confused, that program is buggy.)
If you don't want that, you could set a modified locale:
`LC_ALL=zh_CN.UTF-8@cjknarrow mintty`
