### ISSUE TITLE
Possible regression in 3.1.0

### ISSUE THREAD

**Issue by pandasauce** [mintty/mintty#946]
Same TTF pixel font gets picked up differently in 3.0.6 and 3.1.0.

3.0.6: picks up leading=4, respects RowSpacing, renders as expected

3.1.0: picks up leading=-2, ignores RowSpacing, results in clipped lines

**Comment by mintty** [comment]
From the changelog:

Font rendering
  * Adjust row spacing ("Leading") for high DPI monitors (#777).

> Same TTF 

which?

> pixel font

pixel? Not a good choice.

Font size? Monitor DPI? ...
Provide sufficient information to assess the report, or I can only close it.

**Comment by pandasauce** [comment]
I can provide the TTF privately, it's not a publicly downloadable font and it was converted (traced) from a BDF using non-free tools because Windows doesn't support Unicode in its actual bitmap font (`.fon`) format. Pixel fonts are great for terminals/code on non-HiDPI screens and they work just as good on HiDPI screens as long as no blurry resampling is applied.

Font size 12, standard DPI on external screens (one of them marked as main display) and a 4K internal. Mintty launches on the main display and is only used on the standard DPI externals.

Is mintty using the DPI value of the active monitor for these calculations? It sounds like it may be applying the calculation for the HiDPI screen (first display) in my case regardless of which screen is in use. I can test it on a machine with no HiDPI screens attached tonight if that's of any value.

**Comment by mintty** [comment]
Using a tool does not normally impose a license restriction on the result of the operation, you're not going to upload the tool anyway. Otherwise, if you uploaded a (zipped) font here and we delete it from the comment after transfer, I'd consider it sufficiently private...

Yes, please test on a non-high-DPI machine. The scenario you describe *should* not make a difference but who knows.

**Comment by pandasauce** [comment]
I am happy to provide in in private i.e. email/Tg (same nickname).

I've tested this on a non-HiDPI machine and the behavior is the similar: leading=-3, clipped rows that ignore RowSpacing on 3.1.0, but working as expected on 3.0.6.

**Comment by pandasauce** [comment]
![Capture](https://user-images.githubusercontent.com/7682940/71043461-93c73000-2126-11ea-918a-b31f16fa4468.PNG)
![Capture2](https://user-images.githubusercontent.com/7682940/71043463-93c73000-2126-11ea-94f1-5eaa303dbfb3.png)

Above: 3.1.0
Below: 3.0.6

**Comment by mintty** [comment]
Released 3.1.4.

**Comment by mintty** [comment]
Released 3.4.7 with new heuristics for auto-adjustment of line spacing.

**Comment by mintty** [comment]
Released 3.5.3.
