### ISSUE TITLE
Supports "DropCommands" under WSL(Windows Subsystem for Linux) environment.

### ISSUE THREAD

**Issue by mikelue** [mintty/mintty#947]
I'm using [WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl2-index)(Windows Subsystem for Linux) under [wsltty](https://github.com/mintty/wsltty) as my environment.

Whatever the setting of `DropCommands` is, the only action is of pasting filename.

Thanks a lot. Mintty is great.

----
Careless thought:

The `DropCommands` is not working as expected. It seems that `child.c` uses `/proc/%u/exename`  for inspecting the name of process.

Is it possible making Mintty supports `/proc/<pid>/cmdline`([manual proc(5)](http://man7.org/linux/man-pages/man5/proc.5.html)) for inspecting the name of process?

https://github.com/mintty/mintty/blob/cdf94c3b4e37ce5b04933160fc1080f089288c49/src/child.c#L831

**Comment by mintty** [comment]
The use case of considering the whole command line is a bit fuzzy as parameters vary.
Anyway, as you're talking about wsltty, it would require *much* more than that to make it work at all.
Mintty cannot simply determine the foreground process within the WSL domain as it can within cygwin, and it cannot simply access the /proc filesystem of WSL either. Cygwin /proc will not tell it what you'd like to consider.

**Comment by Biswa96** [comment]
Can you give an example of usage of "DropCommands" option?

**Comment by mikelue** [comment]
This is copied from **Drag-and-drop application-targetted commands** section of `man mintty`.
```
DropCommands=vim:^[:e %s^M
```

**Comment by mikelue** [comment]
> 
> 
> The use case of considering the whole command line is a bit fuzzy as parameters vary.
> Anyway, as you're talking about wsltty, it would require _much_ more than that to make it work at all.
> Mintty cannot simply determine the foreground process within the WSL domain as it can within cygwin, and it cannot simply access the /proc filesystem of WSL either. Cygwin /proc will not tell it what you'd like to consider.

You are absolutely right. I forgot that Mintty is based on cygwin environment. 😅

**Comment by mintty** [comment]
Released 3.1.4.
