### ISSUE TITLE
Line height too narrow for some fonts

### ISSUE THREAD

**Issue by Veltas** [mintty/mintty#948]
Using proggytiny TTF font on Windows 10, with and without font smoothing I see at least one pixel of the font is being cut off.

This font previously worked with an older version of mintty.

Using cygwin-x86_64 distributed mintty-3.1.0-1:  
Leading is reported as -2, font height is too small, RowSpacing has no visible effect with values -4, -2, 0, 2, 4.  
Screenshot:  
![mintty_issue1](https://user-images.githubusercontent.com/2104118/71256608-2505f480-2329-11ea-808d-df8da68ae0dd.png)

Using cygwin-x86_64 distributed mintty-3.0.6-1:  
Leading is reported as 0, correctly rendered, changing RowSpacing has a visible effect.  
Screenshot with RowSpacing=0:  
![mintty_issue2](https://user-images.githubusercontent.com/2104118/71256610-27684e80-2329-11ea-9a48-cb0351ee93ab.png)

**Comment by mintty** [comment]
Likely same issue as #946. Can you provide the font for testing please?

**Comment by BrianInglis** [comment]
[Proggy Fonts Site](https://proggyfonts.net/)
[Proggy Fonts Downloads](https://proggyfonts.net/downloads/)
[Proggy Tiny TTF Zip](https://cdn.proggyfonts.net/wp-content/downloads/ProggyTiny.ttf.zip)

**Comment by mintty** [comment]
Thanks for the test case.
The font contains an internal leading advice of -5 which is causing the squeezed line height.
Why the previous mintty version did not consider this, I cannot say right now. I'll check that out later (in January) for curiosity. But I'd say the change was rather a fix than a bug, and the font is buggy.

**Comment by Veltas** [comment]
I can believe the font is buggy. I can't remember if I tried with RowSpacing=5 or higher, will try when I get back to work after holidays. But if that doesn't change the rendering then maybe there's a bug in not being able to force different leading? I'd like to continue using my albeit buggy font.

**Comment by Veltas** [comment]
This is with RowSpacing=10, still seems to make no difference. (mintty-3.1.0-1 cygwin-x86_64)

![image](https://user-images.githubusercontent.com/2104118/71663042-9abb8880-2d4b-11ea-8f2c-254d0ed32334.png)

**Comment by mintty** [comment]
RowSpacing should indeed compensate for the negative internal leading value...

**Comment by mintty** [comment]
This was caused by a bug in 3.1.0 "fix"
  * Adjust row spacing ("Leading") for high DPI monitors (#777).
caused by the declaration of the dpi value as unsigned and the quirky fact that C coerces both operands to unsigned in a signed / unsigned arithmetic division;
with the result of a leading value of 44739236 which is apparently and fortunately handled as invalid by Windows...

**Comment by mintty** [comment]
Released 3.1.4.

**Comment by mintty** [comment]
Released 3.4.7 with new heuristics for auto-adjustment of line spacing.

**Comment by Veltas** [comment]
Line spacing is now too wide for ProggyTinyTTSZ, need RowSpacing=-8 to get it to align like in second screenshot of OP.

**Comment by mintty** [comment]
The negative font leading of that font is  really weird and likely a bug.
Anyway, I'm now reducing its effect on row spacing. Please test the uploaded tweak.

**Comment by mintty** [comment]
Released 3.5.3.
