### ISSUE TITLE
Handle passed to SetClipboardData should not be freed

### ISSUE THREAD

**Issue by ANH25** [mintty/mintty#950]
According to [Microsoft documentation of the SetClipboardData function](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setclipboarddata), handle passed to `SetClipboardData` should not be freed if the call succeeds:
> If SetClipboardData succeeds, the system owns the object identified by the hMem parameter. The application may not write to or free the data once ownership has been transferred to the system, but it can lock and read from the data until the CloseClipboard function is called. (The memory must be unlocked before the Clipboard is closed.)

But in winclip.c `GlobalFree` is called right after `SetClipboardData`:
https://github.com/mintty/mintty/blob/3f816b6726fdc67ef592a17980e13af9fce07731/src/winclip.c#L754

Also, it seems that `clipdatahtml` is not freed if the lock fails.

**Comment by mintty** [comment]
So it seems an
      }
      else {
is missing between SetClipboardData and GlobalFree. No problem in this area has been reported; can you suggest how mintty could be affected?

**Comment by ANH25** [comment]
I'm not sure exactly how it could be affected actually. but since the handle is owned by the system now I think we should not tamper with it even if mintty is not directly affected.

**Comment by mintty** [comment]
Released 3.1.4.
