### ISSUE TITLE
Passing env variables to the WSL gateway

### ISSUE THREAD

**Issue by mskyaxl** [mintty/mintty#951]
Am I correct that if I want to provide additional variables to the wslbridge2 gateway I should use something like:

mintty.exe  --configdir "%APPDATA%\wsltty"  -t "test" --WSLmode -e /bin/wslbridge2  -e VAR1=VAL1 
?

**Comment by mintty** [comment]
This would be a wsltty, not mintty issue. Can't you simply try it?
Some documentation should be added, anyway.

**Comment by mskyaxl** [comment]
I have tried, it seems to be working but I need a confirmation that this is the right way of using --WSLmode

**Comment by mintty** [comment]
`--WSLmode` is documented quite precisely. Admittedly, the options triple --WSLmode, --WSL, --wsl is a bit confusing and I may improve on the documentation. Options to wslbridge2 are actually in the domain of @Biswa96, but I should consolidate documentation as well, in that case on the wsltty project page...

**Comment by mskyaxl** [comment]
Thanks!
