### ISSUE TITLE
Mouse control codes appearing in terminal

### ISSUE THREAD

**Issue by eggbean** [mintty/mintty#952]
I looked for other posts regarding this, as I assumed it would be a common issue, as it has always happened with different installations.

I always get mouse control codes in the terminal with any movement of the mouse.

eg..

`~$ 32;67;59M32;67;59M32;67;58M32;67;57M32;67;55M32;67;54M32;68;53M32;68;52M32;70;50M32;71;48M32;71;47M32;72;47M32;95;45M32;98;44M32;108;42M32;119;40M32;119;39M32;116;40M32;115;40M32;110;41M32;108;42M32;107;43M32;106;43M32;107;44M32;108;45M32;109;46M32;111;47M32;114;49M32;115;50M32;118;52M32;119;52M32;120;53M32;121;53M32;121;54M32;122;54M32;121;55M32;120;56M32;120;57M32;120;58M32;120;59M32;119;59M32;118;59M32;117;59M32;116;59M32;115;59M32;114;59M^C`

However, it does not happen within tmux, so I have never done anything about it.  But as it does not happen within tmux, I assume there is a fix.

**Comment by mintty** [comment]
Please check which applications you were running before this happened and whether they were terminated properly.

**Comment by mintty** [comment]
OK, some application has enabled application mouse mode and not disabled it properly. Tmux uses mouse mode itself, that explains the difference.
