### ISSUE TITLE
Find a way to turn off Session Switcher function on title bar

### ISSUE THREAD

**Issue by GeekDuanLian** [mintty/mintty#953]
I have a program that defines the function of Ctrl + left-clicking on the window title, but conflicts with the Session Switcher function on minty, so I hope there is a way to turn off the Session Switcher function of minty.

**Comment by mintty** [comment]
Released 3.1.4.

**Comment by GeekDuanLian** [comment]
Thanks a lot! Donated $10 as a thanks.
By the way, on the donation page, click on the $10 coin in the second line, and then jump to paypal and it will display the amount as $1. The page may not be set up correctly.

**Comment by mintty** [comment]
Thank you. Amounts fixed.
