### ISSUE TITLE
The arrow on the search interface is not displayed properly

### ISSUE THREAD

**Issue by GeekDuanLian** [mintty/mintty#955]
On my computer with Chinese locale, the arrow is not displayed properly, but it is displayed correctly on computer with English locale:
![image](https://user-images.githubusercontent.com/6257434/72209951-62f0d580-34ef-11ea-94e4-9cd69175e069.png)

I hope to change the arrow to ▲ ▼ instead of ◀ ▶, because it will not only display normally on computers in all language regions, but also easier to understand:
![image](https://user-images.githubusercontent.com/6257434/72209979-e4e0fe80-34ef-11ea-9aa1-b49663d52092.png)

**Comment by mintty** [comment]
Up/down arrows may indeed be more suitable than left/right... However, will they display in more cases, or just in other cases?
I'll look into checking glyph availability, and/or making the symbols configurable.

**Comment by GeekDuanLian** [comment]
> Up/down arrows may indeed be more suitable than left/right... However, will they display in more cases, or just in other cases?
> I'll look into checking glyph availability, and/or making the symbols configurable.

At least in Chinese locale, the ◀ ▶ is never shows up correctly, tested on mine and others' computers.

**Comment by mintty** [comment]
Released 3.1.4.
