### ISSUE TITLE
Prompt when selecting does not disappear

### ISSUE THREAD

**Issue by GeekDuanLian** [mintty/mintty#956]
Like this:
![image](https://user-images.githubusercontent.com/6257434/72210413-00e79e80-34f6-11ea-92e3-d47038a1a7d8.png)

It will be displayed at the top through any application, and there is no timeout so it will always be displayed forever.

Hope to be able to fix this, thanks!

**Comment by mintty** [comment]
The info popup should disappear as soon as the selection highlighting is cleared.
If this fails, please describe how to reproduce it.

**Comment by GeekDuanLian** [comment]
> The info popup should disappear as soon as the selection highlighting is cleared.
> If this fails, please describe how to reproduce it.

Normally, selecting-> copying-> switching applications to paste does not cancel the selection, so when I switch applications, the prompt will always be displayed on top.
The prompt will disappear immediately after deselecting, this is no problem.
I hope that the prompt should be shown and hidden with the state of the window. When the window is in the back, the prompt should only be displayed in the back.

**Comment by mintty** [comment]
Oh, point seen.

**Comment by mintty** [comment]
Released 3.1.4.
