### ISSUE TITLE
mintty does not show any output from mpv

### ISSUE THREAD

**Issue by ivan** [mintty/mintty#958]
mintty 3.1.0 does not appear to show any output from mpv:

```
# /cygdrive/c/opt/mpv/mpv --help
#
```

When redirecting with `> out`, it does write that help output to a file.

In cmd:

```
C:\Temp>C:\opt\mpv\mpv --help
Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name
```

My `C:\opt\mpv\mpv.exe` is from mpv-0.31.0-x86_64.7z in https://sourceforge.net/projects/mpv-player-windows/files/stable/

I tested on Windows 10 1909, latest updates installed.

**Comment by mintty** [comment]
Please upgrade to cygwin 3.1.0.

**Comment by mintty** [comment]
This mpv exe is reported as malware here. Closing as invalid.

**Comment by avih** [comment]
mpv is not malware (I contribute to it occasionally).

There are two issues:
1. mpv.exe is not a console application. You need to run mpv.con - which is a console application, which then launches mpv.exe and communicate its output to the terminal.
2. mpv.com is a windows-console application. You'll need winpty to have correct terminal output with it.

Bottom line: `winpty path/to/mpv.com ....` will sort all your issues.

**Comment by adisib** [comment]
I don't think winpty is needed since Cygwin 3.1.0

> Support pseudo console in PTY. Pseudo console is a new feature
  in Windows 10 1809, which provides console APIs on virtual
  terminal. With this patch, native console applications can work
in PTYs such as mintty, ssh, gnu screen or tmux.

**Comment by mintty** [comment]
My enterprise virus guard is a bit over-anxious, sorry; so I couldn't test.
I asked the OP to update the environment already, curious to hear whether it solves it.

**Comment by k-takata** [comment]
> There are two issues:

Interesting.
cmd.exe uses $PATHEXT to search executables and `.com` has a higher priority than `.exe`. If a user types `mpv`, `mpv.com` will be executed. So, `mpv --help` will show the help message, because it is a console program.
However, Cygwin doesn't search `.com`. If a user types `mpv`, `mpv.exe` will be executed. So, `mpv --help` won't show the help message, because it is a GUI program. Redirect should still work even for a GUI program.

If `mpv.com` is not an interactive program, neither winpty nor Cygwin 3.1.0 might be needed.
`mpv.com --help` might be enough.

**Comment by avih** [comment]
> If `mpv.com` is not an interactive program, neither winpty nor Cygwin 3.1.0 might be needed.
> `mpv.com --help` might be enough.

It can be both. It's non interactive with `--help` or if there are startup errors (file cannot be opened etc), but is interactive during playback - it takes keypresses and writes non trivial output to the console (moves the cursor etc).

But for `--help`, indeed you don't need winpty/cygwin3.1, and mpv.com is enough.

**Comment by ivan** [comment]
@k-takata thank you very much, I was unaware of the `.com` or the priority difference.

@mintty thanks for looking into it, I was running 3.1.0 when I tested it.
