### ISSUE TITLE
REQUEST: How can I have mintty on ubuntu mate replacing its terminal

### ISSUE THREAD

**Issue by abdulbadii** [mintty/mintty#959]
How can I have a mintty terminal on ubuntu mate replacing mate terminal?
Please guide us to definitive method and procedures in step by step tutorial.
Thanks for concerning before.

**Comment by k-takata** [comment]
mintty is a Windows application. You cannot use it on Ubuntu.
You can still use mintty to connect an Ubuntu server via ssh, though.

**Comment by mintty** [comment]
This would be a porting endeavour, from the Windows API to an X-Windows or maybe Wayland backend. Mintty was once derived from putty, stripping off its X backend. It has its own middle layer to support different backends already. However, during further development, this has not always been strictly adhered to, and further Windows functionality as needed has been interwoven with mintty code at various places. I'd like such a port but I'm afraid it would be much more effort than the tabbar integration which is the next big step.

**Comment by Biswa96** [comment]
Is [wine][1] a viable workaround for this issue? There may be no code change required in mintty/cygwin side.

[1]: https://www.winehq.org/

**Comment by abdulbadii** [comment]
Thanks I see now.
