### ISSUE TITLE
Single-width display option

### ISSUE THREAD

**Issue by mintty** [mintty/mintty#964]
In https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9#note_406682
there is a proposal for single-width CJK character display. See there for a rationale.
While this may appear alien for terminal users who are used to the established dual-width paradigm, some people may in fact prefer it, looking like this:
![image](https://user-images.githubusercontent.com/12740416/74422728-5abdea00-4e4f-11ea-8e5b-2d7511f9a9e7.png)
I've implemented experimental options `Charwidth=single` and `Charwidth=single-unicode`.

**Comment by aycabta** [comment]
I understand this feature may simplify some technical problems but I don't think it demonstrates respect for East Asians' cultures, civilizations, and historical backgrounds. East Asians may not necessarily know Germanic and Romance languages well, but we generally try our best to support features of those languages like word-wrap, half-width and singular/plural forms in our software.  

I think this feature could create negative user experiences for CJK people. In many cases, people who are not from East Asia adopt broken full-width character support without respect for East Asians' historical background. I think it's important to support our languages fully, and I consider it a sign of respect for our languages and cultures.

I'm a native Japanese speaker, and I'm the maintainer of [IRB](https://github.com/ruby/irb) and [Reline](https://github.com/ruby/reline). Both come bundled with [Ruby](https://github.com/ruby/ruby) and have good full-width character support. It may take some additional effort but I want you to know it matters to me and many others.

**Comment by mintty** [comment]
Please exchange rationales pro/con on the page I linked above.
Whether you appreciate the feature or not, I think the commenter there had arguments for it that are absolutely in your spirit, i.e. supporting East Asian text design.
It is certainly not the purpose of the feature to simplify anything technically, on the opposite, it created some implementation trouble. And note, it's only an option, offered to those who like it.

**Comment by aycabta** [comment]
Sure. I'll comment on my technical opinion at the original thread later.

**Comment by mintty** [comment]
OK, but please present your arguments there, not just referring here, as this is not a good place for follow-ups to that proposal.

**Comment by mintty** [comment]
Released 3.1.4.

**Comment by mintty** [comment]
Released 3.1.5.
