### ISSUE TITLE
specific Sixel examples not working

### ISSUE THREAD

**Issue by john-critchley** [mintty/mintty#967]
Hi, I'm confused! Can you help please?

I have:
john@LAPTOP-MQ1NUS24 MSYS ~
$ mintty -V
mintty 3.1.0 (x86_64-pc-msys)
© 2013/2019 Andy Koppe / Thomas Wolff

john@LAPTOP-MQ1NUS24 MSYS ~
$ ./hi.sizel.bash
_nothing appears_

john@LAPTOP-MQ1NUS24 MSYS ~
$ cat hi.sizel.bash
#!/bin/bash
echo -e '\ePq'
echo -e '#0;2;0;0;0#1;2;100;100;0#2;2;0;100;0'
echo -e '#1~~@@vv@@~~@@~~$'
echo -e '#2??}}GG}}??}}??-'
echo -e '#1!14@'
echo -e '\e\\'

![image](https://user-images.githubusercontent.com/56046216/75098609-447eff00-55b0-11ea-9e51-fb65d51b77ea.png)

I also checked this on mlterm and it works OK there.
Wasn't this fixed at commit b60c883b6b4e030a0edda25e535abc31428ce921?
Is it a regression?
Why can't I compile this myself?

**Comment by mintty** [comment]
This tiny picture also works in xterm 
![nixsix](https://user-images.githubusercontent.com/12740416/75099452-1efaf100-55c2-11ea-9f46-7318d181e66b.png)
But it has never worked in mintty, so it's not a regression.
Maybe it's too small? Anyway, I'm not familiar with details of Sixel code interpretation.

**Comment by BrianInglis** [comment]
Works just fine for me in mintty 3.1.0 under Cygwin 3.1.2 and Windows 10 1909, with real escapes at the start of the first and last lines in the file:
$ cat -A hi.sixel
^[Pq$
#0;2;0;0;0#1;2;100;100;0#2;2;0;100;0$
#1~~@@vv@@~~@@~~$$
#2??}}GG}}??}}??-$
#1!14@$
^[\$
Looks like tiny green superscript small caps HI on a light yellow background, although that could be a visual artifact of the window or display.

**Comment by mintty** [comment]
It seems to be a problem if the final height of the sixel image is less than a terminal line.
Zooming the font size before display may confirm this.
To be checked.

**Comment by BrianInglis** [comment]
Checked - confirmed - allows one size zoom which displays ok - then next size zoom and higher nothing displays - with .minttyrc defaults:
$ fgrep -i font ~/.minttyrc
# Text                  Text and Font properties
# Font
Font=DejaVu Sans Mono
#FontHeight=9                   # Size
#FontIsBold=no                  # Style
BoldAsFont=yes
# Font smoothing        default|none|partial|full
#FontSmoothing=default

**Comment by john-critchley** [comment]
Indeed it is working for larger images. I have been using sixels for inline graphing on linux; I just tried ssh'ing to my linux host from it and larger output works (see attached).
![image](https://user-images.githubusercontent.com/56046216/75119813-3b5c6380-567e-11ea-86de-ce744e997035.png)

I tried the 'hi' image as I expected it to work if anything did - it is taken from the Wikipedia page. 
[https://en.wikipedia.org/wiki/Sixel#Sample]
Clearly if it is only a microscopic test image which doesn't work, it isn't so critical!
Thanks for the response.

**Comment by mintty** [comment]
Your HI example isn't quite the same as on Wikipedia (not relevant here).
I've found the bug meanwhile; it's a rounding error, strange it was lurking in the code for so long.
However, another bug revealed during testing...
Where do you have that nice df_sixel tool from?

**Comment by john-critchley** [comment]
> 
> 
> Your HI example isn't quite the same as on Wikipedia (not relevant here).
> I've found the bug meanwhile; it's a rounding error, strange it was lurking in the code for so long.
> However, another bug revealed during testing...
> Where do you have that nice df_sixel tool from?
It was a quick thing I wrote a year or two ago.  It's not done as perfectly as it could be:
#!/usr/bin/perl
use constant DCS => "\eP";
$lwm=80;
$hwm=95;
$c=chr(63+56);
open(P, '-|', join(' ', 'df -k', @ARGV)) or die $!;
while(<P>)
{
        print;
        @_=split;
        $_[4]=/(\d+)%/ or next;
        $p=$1;$q=100-$p;
        ($r, $g, $b)=$p<$lwm?(0,100,0):$p>$hwm?(100,0,0):(100,100,0);
        #($r, $g, $b)=(100,100,100);
        print DCS."q";
        print "#1;2;$r;$g;$b";
        print '#0;2;50;50;50';
        print '#1';
        print "!$p$c";
        print '#0';
        print "!$q$c";
        print '$-';
        print "\e\\";
}

**Comment by mintty** [comment]
Released 3.1.4.
