### ISSUE TITLE
alias not work 

### ISSUE THREAD

**Issue by long-nguyenxuan** [mintty/mintty#968]
## steps to reproduce 

1. installed msys2 in `D:\msys64`
2. update `D:\msys64\home\MyUserName\.bashrc` and add

```rc
gs='git status -s'
gaa='git add .'
gcm='git commit -m'
gpom='git push origin master'
```
3. Open terminal in a git directory & input `gs` 

## Problem 
`-bash: gs: command not found`

## Expect 
`gs` got translated to `git status -s` 

How could I fix it?

**Comment by Biswa96** [comment]
It should be `alias gs='git status -s'`. This is not a mintty question. Please learn about using shell (bash) before.

**Comment by BrianInglis** [comment]
You could also type $gs at the prompt to execute the command defined in the variable gs.

**Comment by long-nguyenxuan** [comment]
Sorry, It's my fault :(
thank you very much for helping newbie like me.
