### ISSUE TITLE
Out of bounds Mouse wheel scrolling

### ISSUE THREAD

**Issue by scandum** [mintty/mintty#972]
When you have mintty maximized and the terminal adds a filler row on the bottom, using mouse scroll wheel up/down at the very bottom will report an out of bounds mouse location (bottom row + 1).

Button presses report (bottom row + 0) at the same position, which I guess is correct behavior.

**Comment by mintty** [comment]
Hmm. Unlike the button presses, for mouse wheel scrolling the position is largely irrelevant and only included for protocol compatibility. So why not report that it is in a padding area...?
I vaguely remember that I noticed this glitch and decided to leave it at the time.

**Comment by scandum** [comment]
For TinTin++ the position is quite relevant for scroll wheel handling.

The best behavior would be to report the bottom row, as that way things work as expected when the user enters the padding area by 1 pixel with the mouse pointer while trying to scroll the input history.

**Comment by mintty** [comment]
Released 3.1.5.
