### ISSUE TITLE
Mintty Sends Incorrect Keycode for Shift+Enter

### ISSUE THREAD

**Issue by skywind3000** [mintty/mintty#977]
Every regular terminals, including `gnome-terminal`, `xshell`, `SecureCRT` and `xterm`, will send `^M (0x0d) ` for `Shift+Enter`:

SecureCRT:

![图片](https://user-images.githubusercontent.com/3035071/76742952-d7284d80-67ac-11ea-8097-e8379c414979.png)

Gnome-terminal:

![图片](https://user-images.githubusercontent.com/3035071/76742989-e5766980-67ac-11ea-8c75-01c815ac8395.png)

But `mintty` sends `^J (0x0a)` for `Shift+Enter`, which is very easy to make mistake:

When I am editing in vim, I type fast:

```
while (0) { <cursor>
```

If I just input a `{`, and my left shift has been released then I press enter, mintty will send a `^J`.

But `CTRL+J` or `^J` has other purpose in vim, I use it to switch window:

```VimL
inoremap <c-j> <esc><c-w>j
```

So, if I type fast in vim, I have chance to trigger `Shift+Enter`, and lead to an unexpected behavior.

Please change `Shift+Enter` to `^M` like other terminals.

**Comment by mintty** [comment]
Marking invalid for the claim current behaviour would be "incorrect". Who is the authority to decide that? Any standard references...?
Mintty has supported to send ^J from Shift+Enter since its very first releases and no one has ever complained before.

**Comment by mintty** [comment]
Also, as described in the manual page, your preferred key mapping can be configured:
`KeyFunctions=S+Enter:^M`

**Comment by skywind3000** [comment]
Thanks. I believe `/usr/bin/xterm` in ubuntu and other linux distributions is de facto "standard".
