### ISSUE TITLE
Copy & Paste colour issues

### ISSUE THREAD

**Issue by antonp01** [mintty/mintty#978]
Copy and Paste is broken in version 3.x

I have a black background configured and cygwin prompt is: green text of userid@host with white text. In previous 2.x version copying when selected Rich Text and HTML - None, it copied correctly to any other program like Word, or Outlook email.

In version 3.x - check/uncheck Rich Text copy, copies the same, adds black background in Word or Outlook email.  Select HTML none, partial, full, still copies the same into Word our Outlook email.

**Comment by mintty** [comment]
I do not see a difference to previous versions. However, I do see weird impact of various colour configuration, e.g. adding the following might fix the issue:
```
ForegroundColour=0,255,128
Green=0,255,0
```
Please verify your observations, making sure to use identical configuration for different instances of mintty.
I have a suspicion this is caused by the palette reduction algorithm in the RTF generation code.

**Comment by antonp01** [comment]
You have misunderstood the problem.  I will attach images.

**Comment by antonp01** [comment]
[screen.pdf](https://github.com/mintty/mintty/files/4371901/screen.pdf)

**Comment by mintty** [comment]
OK, but I don't reproduce your issue. So you copy from a black-on-white terminal and it pastes white-on-black?
Please retest with an empty mintty configuration, and provide a minimal mintty configuration that causes your issue.

**Comment by antonp01** [comment]
My setup is vanilla.  I have just installed cygwin, and changed colors in mintty to have a black background and white letters.  Here is the config:

anton@IP-C613CC92 ~
$ cat .minttyrc
BoldAsFont=no
Columns=230
Rows=45
Transparency=high
MiddleClickAction=void
RightClickAction=paste
Language=@
ClicksTargetApp=no
CopyAsHTML=16777216
ThemeFile=windows10
Locale=en_US
Charset=UTF-8
CopyAsRTF=yes
FontSmoothing=full
EmojiPlacement=align
ScrollbackLines=100
Term=vt100
Font=Consolas
CursorColour=255,128,128
BackgroundColour=0,0,0
ForegroundColour=192,192,192
BoldAsColour=no
AllowSetSelection=yes
PgUpDnScroll=yes
BellType=-1
FontHeight=9
TrimSelection=yes

This setup is basic, I was not fiddling with .minttyrc file, just whatever is present in the GUI in windows. 

When using 2.x version it copies and pastes as rich text, using black letters on white background (i.e. in outlook top picture).  If I upgrade cygwin mintty to 3.x it copies white letters on black background (i.e. outlook bottom picture) as if doing carbon copy of the terminal into the email - this is undesirable behavior.  This happens whether I select HTML none, or any other options.  Given static config above (I do not change .minttrc files) when I use cygwin setup to downgrade to 2.x the copy & paste restores to "good" behavior, i.e. just pastes font and prompt color.  3.x adds background color and preserves foreground color regardless of HTML option chosen.  I can do zoom conf with you & share screen if you would like to see.

**Comment by mintty** [comment]
This config is neither vanilla nor basic, it has a weird entry `CopyAsHTML=16777216` that mintty would not generate, and it is certainly not minimal as I requested. So unlike suggested by your previous description, your terminal is white-on-black, and the pasted text is black-on-white, right?
I confirm that observation, however in either version of mintty, with a Windows application (not Outlook). You weird setting of CopyAsHtml might in fact trigger HTML clipboard type. I'll test that with Outlook later. Try to set your config properly meanwhile. And minimize your test case!

**Comment by mintty** [comment]
And in fact with your weird setting of CopyAsHTML, you are copying fully-formatted HTML to the clipboard which is properly pasted e.g. into Thunderbird.

**Comment by antonp01** [comment]
Ok after I removed .minttyrc and upgraded to 3.x I confirm that copy paste now works correctly.  Although I never modified the .minttyrc by hand before...

![mintty3x](https://user-images.githubusercontent.com/47365079/77479703-87193e80-6ddd-11ea-9aac-ab12dd3144a0.PNG)
