### ISSUE TITLE
Precisely one color value sent from Node.js reproduced incorrectly

### ISSUE THREAD

**Issue by Undercat** [mintty/mintty#981]
One ANSI SGR color value is reproduced incorrectly. The value is rgb(118,118,118). If you change _any_ of the component values to 117 or 119, the defect vanishes.

![bug](https://user-images.githubusercontent.com/7122603/77958972-ba9b1380-728a-11ea-85a3-14da0ed4db9d.png)

In the screen-cap above, the dark band in the greyscale part of the VGA256 spectrum is for the defective color. It renders prefectly in the default Powershell console. It also renders perfectly in MobaXterm. I haven't tried other consoles, but it certainly seems to be limited to mintty.

The first greyscale row in the image uses 24-bit SGR codes. The second greyscale row uses 8-bit SGR codes (the defective VGA color ID is 243). The row with numbers in it is a greyscale ramp in true 24 bit color (i.e., rgb(117,117,117), rgb(118,118,118), etc.). The last row is a differential ramp (rgb(117,117,118), rgb(117,118,117), rgb(117,118,118), etc.).

It is _only_ the rgb(118,118,118) value that is defective, no matter what color mode coding is used to generate it.

I spent an hour or so back-tracking through the code to try to find where the problem was, but it doesn't appear to be a parsing issue and the rendering code is too difficult to comprehend at first glance...I do not have time to delve further into this issue right now. Apologies.

**Comment by mintty** [comment]
I would have noticed such weird behaviour before, I do have colour ramps around.
Meaning that I do not reproduce this issue, everything looks fine.
Please provide the file to produce your image, and also your configuration just in case.

**Comment by Undercat** [comment]
```js
'use strict';
console.log('\x1b[48;2;117;117;117m  \x1b[48;2;118;118;118m  \x1b[48;2;119;119;119m  \x1b[m');
console.log('\x1b[48;5;242m  \x1b[48;5;243m  \x1b[48;5;244m  \x1b[m');
console.log('\x1b[38;5;7;48;5;243m test \x1b[m');
console.log('\x1b[38;5;7;48;5;244m test \x1b[m');
```

MobaXterm
![bug2a](https://user-images.githubusercontent.com/7122603/77975351-b2ed6600-72ae-11ea-9965-984cfe848bbb.png)

PowerShell
![bug2b](https://user-images.githubusercontent.com/7122603/77975371-bda7fb00-72ae-11ea-9d21-5e02150d05ad.png)

mintty
![bug2c](https://user-images.githubusercontent.com/7122603/77975379-c698cc80-72ae-11ea-8732-c19fae8f7cd3.png)

config
![bug3](https://user-images.githubusercontent.com/7122603/77975396-ce587100-72ae-11ea-99a8-bce2768134b8.png)

Installed from Cygwin binary installer for Windows: `CygWin_setup-x86_64.exe` downloaded on 2020-03-29.

**Comment by Undercat** [comment]
It's Node. Wrote a C version of the test program to be sure...

```c
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

int main() {
  printf("\e[48;2;117;117;117m  \e[48;2;118;118;118m  \e[48;2;119;119;119m  \e[m\n");
  printf("\e[48;5;242m  \e[48;5;243m  \e[48;5;244m  \e[m\n");
  printf("\e[38;5;7;48;5;243m test \e[m\n");
  printf("\e[38;5;7;48;5;244m test \e[m\n");
}
```
...and it produces correct results, even on mintty; therefore, something about the way Node sends data to mintty causes the problem. As I pointed out, the problem <i>only</i> arises with mintty, so it's something unique about the interface between in and mintty that cases the problem. Version makes no difference.

**Comment by mintty** [comment]
OK, so make a screen log please. Run `mintty -l .minlog.981` and produce the strange output.

**Comment by Undercat** [comment]
Bingo. If I log the output on mintty, as you instruct, I get the following output for...

**Node**
```
^[[?25l^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C^[[H^[[?25h^[[?25l^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C
^[[80X^[[80C^[[H^[[?25h^[[?25l^[[48;2;117;117;117m  ^[[100m  ^[[48;2;119;119;119m  ^[[48;2;108;108;108m
  ^[[100m  ^[[48;2;128;128;128m  ^[[100m
 test ^[[48;2;128;128;128m
 test
^[[?25h
```

**C reference program**
```
^[[48;2;117;117;117m  ^[[48;2;118;118;118m  ^[[48;2;119;119;119m  ^[[m
^[[48;5;242m  ^[[48;5;243m  ^[[48;5;244m  ^[[m
^[[38;5;7;48;5;243m test ^[[m
^[[38;5;7;48;5;244m test ^[[m
```

In the Node case, the color value in question is not being sent correctly (in addition to a bunch of cursor manipulations and character erases being sent). The color "bright-black" is substituted. **But** if I redirect stdout to a file, the correct data (same as the C program) is recorded.

Funny thing is, Node does not think it's attached to a tty device (process.stdout.isTTY == false) on MobaXterm, but _does_ for both mintty and PowerShell. Yet MobaXterm and PowerShell produce correct output and mintty does not.

Hope this helps.

**Comment by mintty** [comment]
> MobaXterm and PowerShell produce correct output and mintty does not.

1. Apparently we now have evidence that this is not a mintty issue. So "mintty does not [produce correct output]" is the wrong way to speak about the issue.
2. MobaXterm likely includes an older version of cygwin, particularly before 3.1.0 which introduced ConPTY support which most probably makes a difference here. Two cross tests would reveal more: run this in xterm from current cygwin; run this in mintty with environment setting`CYGWIN=disable_pcon node ...`.

**Comment by mintty** [comment]
Also, please run `uname -a` in MobaXterm.

**Comment by mintty** [comment]
Open the Options dialog, select Theme: windows10. You'll notice that you don't notice the issue anymore. Apparently some module (assumedly in Node.js but possibly in the Windows ConPTY code) thinks it would be clever to replace that true colour with the shorter setting "bright black" which looks the same in the standard Windows colour scheme. But not in other colour schemes, so it's not clever at all. Please report this to Node.js.

**Comment by mintty** [comment]
Actually I would expect the same issue to appear with bright red etc settings. Please test.

**Comment by Undercat** [comment]
Yes, it does indeed remap all the colors that match Win10 ANSI color values:

```
(118,118,118) => 100
(231,72,86) => 101
etc.
```
And yes, using the Windows10 color scheme obviates the visual artifacting, because the "right" RGB values are then displayed for "bright black." Crazy.

Node uses libuv to handle its console I/O; the problem may lie there...they seem to shadowing the console state, but there are so many layers of abstraction in their tty code that I have no idea what I'm really looking at. It might take me days to thread it all out. I'll just reference them this issue and see what they make of it.

Sorry for the bother.

Oh, btw, it looks like MobaXterm is using v3.0.4, as you suggested.

**Comment by mintty** [comment]
Actually it seems to be the Windows console layer rather than Node.js.
Put the test string ^[[48;2;117;117;117m 117 ^[[48;2;118;118;118m 118 ^[[48;2;119;119;119m 119 ^[[m (with ESCs) into a text file, `cat` it in mintty which looks fine. Then run cmd.exe and `type` the same file.
So the bug report should go to https://github.com/microsoft/terminal.

**Comment by Undercat** [comment]
So it would seem. The libuv folks actually wrote a small Windows test program to set the underlying console device mode to ENABLE_VIRTUAL_TERMINAL_PROCESSING and discovered the same thing: the console device is relabeling the values. Thanks for the verification.

Cheers.

**Comment by mintty** [comment]
Thanks for the concise report you posted them. Please report back here if the eradicate this nonsense.

**Comment by Undercat** [comment]
They won't fix it.

Evidently, being able to trigger the user's &ldquo;carefully crafted&rdquo; palette of colors for the primary colors is more important than 24-bit color uniformity. In other words, the ConPTY device is not really truecolor. At least not yet, and given that this issue has been open since Sept of last year, it probably won't be for a while.

Read the above-referenced thread for details

**Comment by DHowett-MSFT** [comment]
It’s not that we won’t fix it, it’s that we won’t fix it while we are focused on Windows Terminal v1. That’s not to say we’re giving up on our commitment to the pseudoconsole inbox in Windows; on the contrary: every conpty change that supports Terminal does flow back into inbox.

The discussion would be soundly and firmly closed if we weren’t going to fix it :smile:

**Comment by DHowett-MSFT** [comment]
(Fixing that issue is my personal top “I would bring this back into v1 if we get our bug count under control” favorite, by the way!)

**Comment by Undercat** [comment]
lol. Okay, okay. I'll fork it and look at it myself.

I'm a little reticent to do so, not because I don't have C programming experience, but because I'm an utter GitHub newbie and have never worked on someone else's code here, much less issued a pull request.

But...there's a first for everything, I suppose. 😸

**Comment by DHowett-MSFT** [comment]
We would love to have you. Feel free to ask any questions over in terminal 2661; I’d be happy to oblige. d

**Comment by mintty** [comment]
@DHowett-MSFT,
> won’t fix it while ...

I understand that in general, but in this case, it's not about implementing anything, rather just removing some nonsense mapping (after finding it), so the fix should be trivial. Maybe that's a cause to do it earlier :)
