### ISSUE TITLE
Add option to disable path conversion

### ISSUE THREAD

**Issue by kxzxxx** [mintty/mintty#982]
I think mintty is best terminal on Windows. So I use it for Powershell Core. It is very handy when using mouse. But drag-n-drop in mintty alway convert to cygdrive format or wsl format. Could you add a command line switch like --wsl to disable drag-n-drop path conversion?

**Comment by mintty** [comment]
With the patch just uploaded, you can use configuration `DropCommands` to specify Windows path insertion for certain foreground programs, e.g.
`DropCommands=cmd:%w`
or for PowerShell respectively. Still surrounded by single quotes which may not be desirable, to be tweaked.

**Comment by mintty** [comment]
With the latest commit, change the config to
`DropCommands=cmd:%W`
(capital W) for proper quote embedding.

**Comment by kxzxxx** [comment]
Thanks! I really appreciate it. It will be very handy when using powershell core.

**Comment by mintty** [comment]
Released 3.1.5.
