### ISSUE TITLE
Enhanced dark mode in Windows 10

### ISSUE THREAD

**Issue by Berrysoft** [mintty/mintty#983]
Code here needs to be modified for Windows 10 1903+:
https://github.com/mintty/mintty/blob/ee2edc877658817c0f6a852e415e9c3dc07f254d/src/winmain.c#L4943

`ShouldAppsUseDarkMode` should be replaced by `ShouldSystemUseDarkMode` at ordinal 138, according to issue [here](https://github.com/ysc3839/win32-darkmode/issues/3). I've confirmed that.

Also, this constant should be alerted:
https://github.com/mintty/mintty/blob/ee2edc877658817c0f6a852e415e9c3dc07f254d/src/winmain.c#L4948

According to pull request [here](https://github.com/microsoft/terminal/pull/4817), (I had decompiled the dll provided by the DWM team, and found that) `DWMWA_USE_IMMERSIVE_DARK_MODE` maybe `20` on newer systems, and we should try to set both(`19` and `20`) to `TRUE` to ensure. As for the order, the DWM team choose to try `20` at first.

Also, for dark title bar and menus, we should call function at ordinal 135(`AllowDarkModeForApp(TRUE)` in 1809 or `SetPreferredAppMode(AllowDark)` in 1903) and `FlushMenuThemes()` at ordinal 136. The declaration of these functions could be found [here](https://github.com/ysc3839/win32-darkmode/blob/master/win32-darkmode/DarkMode.h).

**Comment by mintty** [comment]
Uploaded a patch, please test.

**Comment by Berrysoft** [comment]
I've confirmed on Windows 10 20H1 that the title bar is dark now, but not the menu bar(it needs the function `AllowDarkModeForApp(TRUE)` or `SetPreferredAppMode(AllowDark)`, and `FlushMenuThemes()`). Also I'm afraid that it will not work on Windows 10 1809, because the call to `ShouldAppsUseDarkMode` has been replaced.

**Comment by mintty** [comment]
OK, so we have two dynamic alternatives; what's the exact version when Windows broke the previous API?
By "menu bar" you mean the system menu and the context menu? They should be dark too?
So when should those functions be applied? Once for initialisation? Please be more specific.

**Comment by Berrysoft** [comment]
Oh, my fault to misspelled that. I mean the system and context menu. `SetPreferredAppMode(AllowDark)` should be called once for init, and `FlushMenuThemes()` should be called together with `DwmSetWindowAttribute`.

Windows 10 1903, aka 18362, broke the API. The function at ordinal 135 is `AllowDarkModeForApp` before, and `SetPreferredAppMode` after 1903. It also broke `ShouldAppsUseDarkMode`, which always return `TRUE`(actually, random runtime not zero) after 1903.

Before 1903, `BOOL __stdcall AllowDarkModeForApp(BOOL)` only accepts TRUE or FALSE. TRUE means dark mode is allowed and vice versa. After 1903, `PreferredMode __stdcall SetPreferredAppMode(PreferredMode)` accepts 4 valid value: `Default`, `AllowDark`, `ForceDark`, `ForceLight`.

The result of `ShouldSystemUseDarkMode` is not influenced by `SetPreferredAppMode`, but the color of menus do. Only if `SetPreferredAppMode(AllowDark)` or `SetPreferredAppMode(ForceDark)` is called, the menus could be dark.

**Comment by Biswa96** [comment]
Code speaks louder than words! Would you like to send a patch file or make a PR to be reviewed? A Windows version checking function may be required also.

**Comment by Berrysoft** [comment]
Ok. I didn't send PR because I've noticed that the README says "No unsolicited pull requests!"🤣

**Comment by mintty** [comment]
The extended context menu (Ctrl+right-click) is not yet dark! @#!§%!!

**Comment by mintty** [comment]
That happens whenever a multi-column menu is created (via config, using '|').
Apparently Windows mangles the menu style when a flag MF_MENUBARBREAK (or MF_MENUBREAK) is used.

**Comment by Biswa96** [comment]
> The extended context menu (Ctrl+right-click) is not yet dark! @#!§%!!

Which source file and function does create that menu?

**Comment by mintty** [comment]
wininput.c, see the commit for analysis;
if you suppress the usage of MF_MENUBARBREAK, the menu will be dark;
note that also icon display is affected

**Comment by Berrysoft** [comment]
It seems that menu with `MF_MENUBARBREAK` is "deprecated" - it is not applied with visual styles. That's why it couldn't be dark, I think.

**Comment by mintty** [comment]
The flag is documented in https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-appendmenuw. I don't see any indication of it being deprecated. It's a Windows bug.

**Comment by Berrysoft** [comment]
That's why I cover the word *deprecated* with quotation marks. It is probably a bug, but I don't think Microsoft will fix it.

If you want the menu dark, I suggest replacing vertical separator with horizontal separator.

**Comment by mintty** [comment]
Released 3.1.5.

**Comment by mintty** [comment]
This crashes mintty in Windows 7.
Hopefully, it's still working in earlier Windows 10 versions...

**Comment by mintty** [comment]
There are now reports that this also fails in earlier Windows 10 versions, for example 10.0.15063.
So we'll have to add additional checks to guard the usage of those functions.

**Comment by mintty** [comment]
@Berrysoft, can you find information on the minimum version to support this, or at least not crash?
I'm tentatively setting it to build 17763 as mintty runs on one system I have with that build.

**Comment by Berrysoft** [comment]
The dark mode is introduced in Windows 10 Anniversary Update, aka 1809 or 17763. Thus the minimum version should be 17763, I think.

**Comment by mintty** [comment]
We may be getting another issue as reported in mintty/wsltty#157, not yet reproduced.

**Comment by Berrysoft** [comment]
I'm using 2004 and the title bar *is* dark now...

**Comment by mintty** [comment]
Released 3.1.7.
