### ISSUE TITLE
custom emoji support?

### ISSUE THREAD

**Issue by mskyaxl** [mintty/mintty#985]
Hi,
what are the conditions for adding a custom emoji folder?
certain name for the folder?
certain size for the pictures?
certain metadata included in the pictures?

I notices that for example if I change the folder name for the apple folder and select that folder name they would not be displayed. also if I replace images with the ones that have the same size I get the same result - nothing is displayed.

Thanks!

**Comment by mintty** [comment]
Drop-in replacement of emoji images should work.
The set of emoji styles is currently hard-coded. The reason is the different filename formats of the popular emoji repositories.
What other emoji set do you have in mind? If it's publically available and worth supporting, I'll check that.

**Comment by mskyaxl** [comment]
I have in mind this https://openmoji.org/library/.

I was thinking that maybe is better adding some rules for the naming of any folder name which is not in the hard coded list to give the possibility of adding any.

**Comment by mintty** [comment]
Uploaded a patch to support OpenMoji.

**Comment by mskyaxl** [comment]
thanks!

**Comment by mintty** [comment]
Released 3.1.5.
