### ISSUE TITLE
mintty with WSL waits for setsid to finish

### ISSUE THREAD

**Issue by Perlence** [mintty/mintty#993]
Hello,

I'm using mintty 3.1.4 to start WSL1 via wslbridge2:

```bat
> C:\cygwin\bin\mintty.exe --WSL
```

Next, I do the following in mintty:

```sh
$ setsid sleep 10
$ exit
```

I expect the mintty window to close immediately. However, the terminal waits for `sleep` to finish before closing.

Is this a bug?

**Comment by mintty** [comment]
This also happens with wslbridge2 called from cmd, without mintty involved.
(Could be reported in wsltty or wslbridge2 projects).
@Biswa96?

**Comment by Biswa96** [comment]
Looking into it.

**Comment by Perlence** [comment]
Moved the issue to https://github.com/Biswa96/wslbridge2/issues/23.

**Comment by Biswa96** [comment]
@mintty any idea about this issue? I can't figure out the exact cause. I think the issue is in wslbridge2-backend's waitpid logic. The shell process becomes zombie one after `setsid sleep 10; exit`.

**Comment by mintty** [comment]
I am not familiar with the circumstances that cause zombie processes and the like. Maybe some system handle is still open? Maybe related to the recent fix for unclosed sockets (#197)? Does it still happen with that fix?
