### ISSUE TITLE
SetConsoleTextAttribute support

### ISSUE THREAD

**Issue by nu8** [mintty/mintty#994]
Using this Go program:

~~~go
package main
import "syscall"
func main() {
   o_kernel := syscall.NewLazyDLL("kernel32.dll")
   o_attr := o_kernel.NewProc("SetConsoleTextAttribute")
   n_hand := uintptr(syscall.Stdout)
   n_red := uintptr(4)
   o_attr.Call(n_hand, n_red)
   println("Sunday")
}
~~~

Produces color output with `cmd.exe`, but not `mintty.exe`. Does Mintty only
support color via ANSI escape codes?

**Comment by mintty** [comment]
Yes, because that's what terminals do.
Actually, since cygwin 3.1.0 (or with winpty before), the console API should be mediated towards the terminal so it should also work, outside the scope of mintty, however.

**Comment by muv1** [comment]
This issue is precisely about the scope of mintty, so I don't understand your comment. If I am using a program outside of mintty, then that's cmd and it's not an issue.

**Comment by mintty** [comment]
Calling SetConsoleTextAttribute is something that native Windows program do.
Interpreting that call is in the scope of the Windows console API, not mintty.
The wrapper winpty is a gateway between them, and so is the built-in ConPTY support of cygwin 3.1.0.
What's your cygwin version? If below 3.1.0, please upgrade or try winpty.

**Comment by muv1** [comment]
Not sure what version I had before, but I just tried again with 3.1.4 and it still outputs in blank and white.

**Comment by mintty** [comment]
The test program below displayes everything in green. The issue must be caused by some specific handling within the Go environment.
```
#include <stdio.h>
#include <windows.h>

void main()
{
  char * s = "coloured text\n";
  HANDLE conout = GetStdHandle(STD_OUTPUT_HANDLE);
  DWORD len;
  SetConsoleTextAttribute(conout, FOREGROUND_GREEN);
  printf("printf:\n");
  printf("%s", s);
  printf("WriteConsole:\n");
  WriteConsoleA(conout, s, strlen(s), &len, 0);
}

**Comment by muv1** [comment]
Nope, just tried again with your program. Still black and white.

**Comment by k-takata** [comment]
I confirmed that your Go program showed the message in red.

You can check your cygwin version by `uname -a`.
Also note that you need to use Windows 10 1809 or later to use ConPTY.

**Comment by muv1** [comment]
I have an older Windows, so I will need to use ANSI escape until I upgrade. Thank you

**Comment by mintty** [comment]
@muv1:
> I have an older Windows, 

This is an opportunity to ask you for help about another issue: Does mintty 3.1.6 run for you?

**Comment by muv1** [comment]
Yes

**Comment by muv1** [comment]
Actually I take that back, scrolling with LESS is slow and awful, I will be downgrading
