### ISSUE TITLE
Displayed images sometimes disappear 

### ISSUE THREAD

**Issue by rmccampbell** [mintty/mintty#995]
Using the mintty [ITerm2 image escape](http://mintty.github.io/#image) support, sometimes the images will randomly disappear after showing for several minutes, and be replaced with white boxes. It will simultaneously effect all images previously displayed as well as all new images, which will also be replaced with white boxes, so the terminal must be reopened to display images again. 

After this happens the terminal otherwise appears to work normally. When I scroll up the white boxes are replaced with the terminal background, and after that new images will be invisible, no longer with white boxes but still allocating the space for them. 

If the terminal window is resized after the images disappear then the graphics of the entire terminal become frozen. New text will no longer display on the terminal, scrolling stops working, and the resized portions of the window are filled with the edge values of the initial window. This makes the terminal effectively unusable, although it still can run commands (as side effects can still be observed, i.e. `echo hello > out.txt`). 

I haven't figured out any deterministic way to trigger this. I have only observed it happening in WSLtty running Ubuntu, but I think it is a problem with MinTTY itself and not any WSL-specific modifications, and I simply haven't used it enough in Cygwin to confirm whether the problem exists. It only seems to happen after the terminal is open for long periods, whether or not I am actively using it, and it may be effected by the number and/or size of the images displayed. I also haven't confirmed whether this effects SIXEL graphics, i.e. images displayed via `img2sixel`.

**Comment by rmccampbell** [comment]
Some screenshots:
Before:
![image](https://user-images.githubusercontent.com/8339155/82519562-fb2b4680-9aef-11ea-8b8e-ceeae09071bb.png)
After (terminal is at different point but should be showing the same image):
![image](https://user-images.githubusercontent.com/8339155/82519635-1dbd5f80-9af0-11ea-9ff4-22df561074b2.png)
After resizing:
![image](https://user-images.githubusercontent.com/8339155/82519709-49d8e080-9af0-11ea-8d87-fcb01e71ff30.png)

**Comment by mintty** [comment]
Thanks for the detailed description. It sounds like a leak of Windows handle resrouces.

**Comment by mintty** [comment]
It happened after display/redisplay of any image ~10000 times. Uploaded a fix.

**Comment by mintty** [comment]
Released 3.1.6.
