### ISSUE TITLE
mintty 3.1.5 closes randomly on key press

### ISSUE THREAD

**Issue by salavessa** [mintty/mintty#996]
Can't reproduce this consistently but since version `3.1.5` `mintty` keeps closing randomly on key press (never happened to before in `3.1.4`).
It happens quite frequently (got it 3 times in 10 minutes) and it seems to be while using function keys like `Alt` combinations, `PgUp`, `PgDn`, `Arrow` keys.
It also seems to be a graceful shutdown though as all times it happened while using `vi`, re-editing the file `vi`'s swap file was never present.
Maybe also worth noting that I also observed a "chain effect": one of the times I had two `mintty` windows opened and they both got closed.

**Comment by mintty** [comment]
I'm not aware of such behaviour although I used the update often already. Any further hint will be useful.
About the "chain effect", I guess that's unrelated. It may be caused by recent cygwin pty changes and also happens with xterm. To be reported to the cygwin mailing list.

**Comment by salavessa** [comment]
I figure out a way to reproduce it: by pressing and holding a key down (e.g. `ArrowRight`, `ArrowDown`, `PgDn`,...), the window closes in few seconds (maybe something related with keypress buffering).
This is reproducible in a couple of different hosts (win7 and win10) to which I'm connected via `Chrome Remote Desktop`.
No "chain effect" is observable (this probably happened because I kept the key pressed after the first window closed and then the same happened in the second one).
I've also downgraded to test same scenarios in `3.1.4` and everything works fine.

**Comment by mintty** [comment]
So does it only occur with Remote Desktop? Please try locally.

**Comment by mintty** [comment]
Does perhaps Remote Desktop use WM_CHAR messages for character injection?
Please compile mintty with some diagnostics in winmain.c:
Either uncomment `#define dont_debug_messages` -> `#define debug_messages`
or place a printf behind `    when WM_CHAR or WM_SYSCHAR:` (and start mintty from a command line to see the output).

**Comment by salavessa** [comment]
>
>
> So does it only occur with Remote Desktop? Please try locally.

Unfortunately I don't have physical access to the machines hosts, so can't really check this.


> 
> 
> Does perhaps Remote Desktop use WM_CHAR messages for character injection?
> Please compile mintty with some diagnostics in winmain.c:
> Either uncomment `#define dont_debug_messages` -> `#define debug_messages`
> or place a printf behind ` when WM_CHAR or WM_SYSCHAR:` (and start mintty from a command line to see the output).

Honestly it's the first time I'm hearing about `WM_CHAR`. I install `mintty` from `cygwin` setup, compiling on my side seems extreme.
If you can provide the standalone package/binaries I'll give it a go.

**Comment by mintty** [comment]
Building mintty is much easier than many other packages. You'd only need to install cygwin packages gcc-core and make. Then download (or git-checkout) mintty, go into its directory and run `make`.
It that doesn't work for you, I'll upload a test binary here.

**Comment by salavessa** [comment]
Binary would be great, thanks.

**Comment by mintty** [comment]
OK, github doesn't allow to upload an .exe file here, so it's zipped.
On the remote machine, from a (normal) mintty session start another session using this binary and log its output to the first terminal (which you could run with option -l).
The output may give some hints, or not, who knows. I can also try to setup Chrome Remote Desktop myself the next days.
[mintty-debug_messages.zip](https://github.com/mintty/mintty/files/4663643/mintty-debug_messages.zip)

**Comment by salavessa** [comment]
Got a `Floating point exception (core dumped)` error - replicated by pressing and holding `Arrow Right` a couple of times.
Output and stackdump file: [Floating point exception (core dumped).zip](https://github.com/mintty/mintty/files/4663703/Floating.point.exception.core.dumped.zip)

**Comment by BrianInglis** [comment]
Also issues on Cygwin list. If not already tried, you may want to cross check with previous and current Cygwin releases, and latest Cygwin snapshot to pick up console and I/O fixes, in case it's them not you! ;^>

**Comment by mintty** [comment]
Released 3.1.6.
