### ISSUE TITLE
Change keys to enter keyboard selection mode?

### ISSUE THREAD

**Issue by reckoner** [mintty/mintty#997]
What I can I change in my minttyrc to change the 

    Shift+middle-keypad-key (Shift+"5")

default for entering keyboard selection mode to something like

    ctrl+alt+k

or something?

**Comment by mintty** [comment]
Currently nothing.
I had planned to make it configurable (it's even mentioned in the manual already) but apparently lost track of it.

**Comment by reckoner** [comment]
I am not able to remap to these keys using autohotkey. Is that normal?

**Comment by mintty** [comment]
Does Autohotkey offer Shift+middle-keypad for a definition?

**Comment by reckoner** [comment]
The Following will map `ctrl+alt+m` to trigger entering into the keyboard selection mode.

    !^m::Send,+{NumpadClear}

**Comment by mintty** [comment]
I've implemented a key function to start keyboard selection. Right now, pressing middle-keypad while selecting (to refocus) could not be replaced by the defined key, would that be sufficient?
Also for printable characters, keyboard function assignment supports only Ctrl+Shift as modifier, not Ctrl+Alt in order not to override the assignment it already has.

**Comment by reckoner** [comment]
Are you saying that Ctrl+Shift+A would enter keyboard selection mode? What configuration in minttyrc would have to be set up to facilitate this?

**Comment by mintty** [comment]
`KeyFunctions=a:kb-select`

**Comment by reckoner** [comment]
Thanks! I don't know how to build the source myself. Will this commit be in the next release?

**Comment by mintty** [comment]
Released 3.1.7.
